export type Role = 'founder' | 'lawyer';
export type WorkflowState = 'queued' | 'waiting_for_document_slot' | 'retrieving_context' | 'assessing' | 'needs_information' | 'drafting' | 'validating' | 'repairing' | 'needs_human_review' | 'awaiting_founder' | 'awaiting_lawyer' | 'ready_to_finalize' | 'finalized' | 'closed_no_change' | 'rejected' | 'superseded' | 'failed';
export type Json = null | boolean | number | string | Json[] | { [key: string]: Json };
export interface Fact { fact_id: string; fact_key: string; knowledge: 'known' | 'unknown' | 'conflicted'; value: Json; provenance: string; }
export interface Clause { clause_id: string; heading: string; body: string }
export interface Revision { revision_id: string; document_id: string; revision_number: number; base_revision_id: string | null; title: string; policy_updated_on: string; clauses: Clause[]; content_hash: string; created_at: string; evidence_bindings?: Binding[]; generation?: 'scripted' | 'openai' | 'human_edit'; semantic_validation?: {passed:boolean; codes:string[]; reviewed_content_hash:string; model:string; checked_at:string} }
export interface Provision { provision_key: string; source_version_id: string; title: string; url: string; text: string; content_hash: string; source_hash: string; effective_from: string; retrieved_at: string; }
export interface Binding { clause_ids: string[]; fact_refs: {fact_key: string; fact_id: string}[]; legal_refs: {provision_key: string; source_version_id: string}[]; rationale: string }
export interface Assessment { outcome: 'covered' | 'not_covered' | 'needs_information'; summary: string; missing_facts: string[]; basis: string[]; criteria: {label: string; result: 'pass' | 'fail' | 'unknown'; evidence: string}[]; }
export interface Validation { validation_id: string; created_at: string; stage: 'context_readiness' | 'proposal'; passed: boolean; codes: string[]; explanation: string; repaired: boolean; }
export interface Approval { approval_id: string; role: Role; action: 'viewed' | 'reviewed' | 'approved' | 'requested_changes' | 'rejected'; actor_id: string; bundle_hash: string; created_at: string; note: string }
export interface Feedback { feedback_id: string; workflow_id: string; role: Role; type: 'fact_correction' | 'document_edit' | 'legal_interpretation_note' | 'harness_improvement'; text: string; created_at: string; status: 'recorded' | 'applied'; fact_key?: string; proposed_value?: Json; clause_id?: string; }
export interface PostalAddress { line1:string; city:string; region:string; postal_code:string; country:string }
export interface Workflow { workflow_id: string; tenant_id: string; reset_epoch: number; state: WorkflowState; state_version: number; created_at: string; updated_at: string; customer_name: string; postal_address?: PostalAddress; residence: string; scenario: string; event_id: string; base_revision_id: string; candidate_revision_id: string | null; harness_version: number; context_epoch: number; facts: Fact[]; assessment: Assessment | null; validations: Validation[]; repair_count: number; missing_bundle_repairs: number; approvals: Approval[]; bundle_hash: string | null; review_input_hash: string | null; freshness_valid_until: string; model_mode: 'scripted' | 'openai'; model_status: string; model_attempts: number; input_tokens: number; output_tokens: number; reserved_cost: number; cost_usd: number; unknown_charge: boolean; lease_owner: string | null; lease_epoch: number; lease_until: string | null; failure: string | null; evidence_keys: string[]; citation_offset: number | null; }
export interface Event { event_id: string; tenant_id: string; reset_epoch: number; aggregate_seq: number; workflow_id: string | null; type: string; title: string; detail: string; created_at: string; }
export interface Notification { notification_id: string; workflow_id: string; reset_epoch: number; kind: 'lawyer_review_requested' | 'document_finalized'; mode: 'preview' | 'delivery'; status: 'pending' | 'sending' | 'previewed' | 'sent' | 'delivered' | 'bounced' | 'failed' | 'unknown_delivery' | 'canceled'; subject: string; body: string; to: string; created_at: string; provider_message_id: string | null; attempts: number; failure: string | null; dedupe_key: string; bundle_hash?: string; lease_until?: string | null }
export interface Harness { version: number; harness_id: string; prefetch: boolean; created_at: string; status: 'active' | 'retired' | 'candidate'; reason: string; }
export interface Evaluation { evaluation_id: string; created_at: string; baseline_version: number; candidate_version: number; mode: 'deterministic_executed' | 'live_executed' | 'inconclusive'; cases: { name: string; expected: string; actual: string; passed: boolean }[]; baseline_repairs: number; candidate_repairs: number; passed: boolean; duration_ms: number; promoted: boolean; dataset_hash: string }
export interface State { schema_version: 1; tenant_id: string; reset_epoch: number; state_version: number; context_epoch: number; company_name: string; facts: Fact[]; revisions: Revision[]; current_revision_id: string; workflows: Workflow[]; events: Event[]; feedback: Feedback[]; notifications: Notification[]; harnesses: Harness[]; champion_version: number; champion_generation: number; evaluations: Evaluation[]; receipts: Record<string, {hash: string; result: Json}>; worker_heartbeat: string | null; }
export interface Session { demo_id?:string; role: Role; actor_id: string; tenant_id: string; reset_epoch: number; csrf: string; expires_at: number }
export class AppError extends Error { constructor(public code: string, message: string, public status = 409) { super(message); } }
