import {Resend} from 'resend';
import {transaction,readState} from '../data/store';
import {event} from '../workflow/engine';
import {AppError} from './contracts';
export async function dispatchNotification(){const task=await transaction(s=>{const n=s.notifications.find(n=>n.status==='pending');if(!n)return null;const w=s.workflows.find(w=>w.workflow_id===n.workflow_id);if(n.reset_epoch!==s.reset_epoch||!w||w.bundle_hash===null||n.bundle_hash!==w.bundle_hash||['rejected','superseded'].includes(w.state)){n.status='canceled';return null;}if(n.mode==='preview'){n.status='previewed';event(s,w,'notification.previewed','Email preview ready',n.subject+' · No email sent.');return null;}if(process.env.KIARA_ALLOW_LIVE_EMAIL!=='true'||!process.env.RESEND_API_KEY||!process.env.KIARA_EMAIL_FROM||n.to.endsWith('.test')){n.status='failed';n.failure='Delivery requires explicit live-email authorization, provider credentials, verified sender and a real approved recipient.';return null;}if(n.attempts>=5||Date.now()-Date.parse(n.created_at)>23*60*60*1000){n.status='failed';n.failure='Delivery retry budget exhausted.';return null;}n.status='sending';n.attempts++;n.lease_until=new Date(Date.now()+30000).toISOString();return structuredClone(n);});if(!task)return;let providerId:string|null=null;let failure:string|null=null;let unknown=false;try{const resend=new Resend(process.env.RESEND_API_KEY!);const timeout=AbortSignal.timeout(15000);const result=await Promise.race([resend.emails.send({from:process.env.KIARA_EMAIL_FROM!,to:task.to,subject:task.subject,text:task.body},{idempotencyKey:task.dedupe_key}),new Promise<never>((_,reject)=>timeout.addEventListener('abort',()=>reject(new Error('send_timeout')),{once:true}))]);if(result.error){const status=(result.error as any).statusCode;const definitive=Number.isInteger(status)&&[400,401,403,404,409,422,429].includes(status);unknown=!definitive;failure=definitive?`Provider rejected the request (${result.error.name}).`:'Provider response is uncertain. Reconcile the retained delivery key before retrying.';}else providerId=result.data?.id||null;if(!providerId&&!failure)unknown=true;}catch{unknown=true;failure='Provider response unavailable; delivery may have been accepted. Reconcile before retrying.';}await transaction(s=>{if(s.reset_epoch!==task.reset_epoch)return;const n=s.notifications.find(n=>n.notification_id===task.notification_id);if(!n||!['sending','unknown_delivery'].includes(n.status))return;n.lease_until=null;n.provider_message_id=providerId;n.failure=failure;n.status=unknown?'unknown_delivery':failure?'failed':'sent';if(providerId)reconcileWebhooks(s,n);event(s,s.workflows.find(w=>w.workflow_id===n.workflow_id)||null,unknown?'notification.delivery_unknown':failure?'notification.failed':'notification.sent',unknown?'Email delivery unknown':failure?'Email delivery failed':'Email sent',n.subject);});}
export async function retryNotification(id:string,epoch:number){return transaction(s=>{if(s.reset_epoch!==epoch)throw new AppError('RESET_EPOCH_MISMATCH','Refresh first.');const n=s.notifications.find(n=>n.notification_id===id);if(!n)throw new AppError('NOT_FOUND','Notification not found.',404);if(n.status==='unknown_delivery')throw new AppError('DELIVERY_RECONCILIATION_REQUIRED','Unknown deliveries must be reconciled with the provider before retrying.');if(n.status!=='failed')throw new AppError('RETRY_NOT_AVAILABLE','This notification does not need a retry.');n.status='pending';n.failure=null;return {status:'pending'};});}
export async function webhook(request:Request){if(!process.env.RESEND_WEBHOOK_SECRET)throw new AppError('WEBHOOK_NOT_CONFIGURED','Webhook verification is not configured.',503);const raw=await request.text();if(raw.length>100000)throw new AppError('PAYLOAD_TOO_LARGE','Webhook too large.',413);let payload:any;try{payload=new Resend(process.env.RESEND_API_KEY||'not-used-for-verification').webhooks.verify({payload:raw,headers:{id:request.headers.get('svix-id')||'',timestamp:request.headers.get('svix-timestamp')||'',signature:request.headers.get('svix-signature')||''},webhookSecret:process.env.RESEND_WEBHOOK_SECRET});}catch{throw new AppError('INVALID_SIGNATURE','Webhook signature rejected.',401);}return transaction(s=>{const key=s.reset_epoch+':webhook:'+request.headers.get('svix-id');if(s.receipts[key])return {received:true};const n=s.notifications.find(n=>n.provider_message_id===payload.data?.email_id);if(n){const mapping:Record<string,'delivered'|'bounced'|'failed'>={'email.delivered':'delivered','email.bounced':'bounced','email.failed':'failed'};const status=mapping[payload.type];if(status&&!(n.status==='bounced'&&status==='delivered'))n.status=status;}s.receipts[key]={hash:'verified-provider-event',result:{kind:'verified_delivery_event',received:true,provider_message_id:payload.data?.email_id||'',type:payload.type,received_at:new Date().toISOString()}};return {received:true};});}

export async function recoverNotifications(){return transaction(s=>{let recovered=0;for(const n of s.notifications){if(n.mode==='delivery'&&n.status==='sending'&&Date.parse(n.lease_until||n.created_at)<=Date.now()){n.status='unknown_delivery';n.failure='Worker dispatch lease expired; provider outcome must be reconciled using the retained idempotency key.';recovered++;}}return recovered;});}

function reconcileWebhooks(s:import('./contracts').State,n:import('./contracts').Notification){const events=Object.values(s.receipts).map(r=>r.result as any).filter(r=>r?.kind==='verified_delivery_event'&&r.provider_message_id===n.provider_message_id);if(events.some(e=>e.type==='email.bounced'))n.status='bounced';else if(events.some(e=>e.type==='email.failed'))n.status='failed';else if(events.some(e=>e.type==='email.delivered'))n.status='delivered';}
