import {createHash} from 'node:crypto';
import {fixture,provisions} from '../data/fixtures';
import {readState,transaction} from '../data/store';
import {AppError,type Role,type Json} from './contracts';
import {event,terminal,scoped} from '../workflow/engine';
import {id,now,hash} from './hash';
const allowed=new Set(['cppa.ca.gov','leginfo.legislature.ca.gov']);
/** Fetch only a registered official source, with redirects, bytes and time bounded. */
export async function fetchRegisteredSource(url:string){let target=new URL(url);const signal=AbortSignal.timeout(10000);for(let hop=0;hop<4;hop++){if(target.protocol!=='https:'||!allowed.has(target.hostname)||target.port||target.username||target.password)throw new AppError('SOURCE_UNTRUSTED','The source is outside the registered official-origin allowlist.',400);const response=await fetch(target,{redirect:'manual',signal,headers:{Accept:'application/pdf,text/html,text/plain'}});if([301,302,303,307,308].includes(response.status)){const location=response.headers.get('location');if(!location)throw new AppError('SOURCE_FETCH_FAILED','Invalid source redirect.',502);target=new URL(location,target);continue;}if(!response.ok||!response.body)throw new AppError('SOURCE_FETCH_FAILED','The official source could not be retrieved.',502);const length=Number(response.headers.get('content-length')||0);if(length>4*1024*1024)throw new AppError('SOURCE_TOO_LARGE','The source exceeds the original-byte admission limit.',413);const reader=response.body.getReader();const chunks:Uint8Array[]=[];let size=0;while(true){const item=await reader.read();if(item.done)break;size+=item.value.byteLength;if(size>4*1024*1024){await reader.cancel();throw new AppError('SOURCE_TOO_LARGE','The source exceeds the original-byte admission limit.',413);}chunks.push(item.value);}const bytes=Buffer.concat(chunks);return {sha256:createHash('sha256').update(bytes).digest('hex'),byte_count:size,url:target.href};}throw new AppError('SOURCE_REDIRECT_LIMIT','Too many source redirects.',502);}
export async function recheckSources(workflow_id:string,role:Role,epoch:number){if(role!=='lawyer')throw new AppError('FORBIDDEN','An assigned lawyer must recheck authoritative sources.',403);const before=await readState(),w=scoped(before,workflow_id,epoch);if(terminal.has(w.state))throw new AppError('TERMINAL_WORKFLOW','Completed review packets remain immutable.');const sources=fixture<any[]>('legal_source_versions.ejson.json');const ids=[...new Set(provisions().filter(p=>w.evidence_keys.includes(p.provision_key)).map(p=>p.source_version_id))];if(!ids.length)throw new AppError('EVIDENCE_REQUIRED','Retrieve the review evidence first.');const verified:{source_version_id:string;source_hash:string;url:string;byte_count:number}[]=[];for(const source_id of ids){const s=sources.find(s=>s._id===source_id);if(!s)throw new AppError('SOURCE_NOT_FOUND','Source is not registered.',404);const result=await fetchRegisteredSource(s.url);if(result.sha256!==s.original_sha256)throw new AppError('SOURCE_CHANGED','The official source bytes have changed. Reingestion and legal review are required; the old packet remains blocked.');verified.push({source_version_id:source_id,source_hash:result.sha256,url:result.url,byte_count:result.byte_count});}return transaction(s=>{const current=scoped(s,workflow_id,epoch);if(current.state_version!==w.state_version)throw new AppError('STATE_VERSION_MISMATCH','The workflow changed during source recheck.');const attestation_id=id(),valid_until=new Date(Date.now()+24*60*60*1000).toISOString();const result={attestation_id,workflow_id,actor_role:role,verified_at:now(),valid_until,method:'official_origin_exact_bytes',sources:verified};s.receipts[`${epoch}:source_recheck:${attestation_id}`]={hash:hash(result),result:result as Json};current.freshness_valid_until=valid_until;current.bundle_hash=null;current.review_input_hash=null;current.state=current.candidate_revision_id?'validating':'retrieving_context';current.state_version++;current.updated_at=now();event(s,current,'approval.invalidated','Official sources rechecked','Exact registered source bytes verified. A new review seal and both approvals are required.');return result;});}
