import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {GET,POST} from '../src/app/api/[...path]/route';
import {readState,transaction} from '../src/data/store';
import {signup} from '../src/workflow/engine';
import {withDemoScope} from '../src/server/demo-context';
import {issueSession} from '../src/server/auth';
import {globalSpendStatus,reserveGlobalSpend,settleGlobalSpend} from '../src/server/global-spend';

const origin='https://kiara.example';
const route=(path:string)=>({params:Promise.resolve({path:path.split('/')})});
test('new public demo preserves old audit and global spend while enforcing auth, CSRF and active-charge gates',async t=>{
 const previous={...process.env},dir=await mkdtemp(join(tmpdir(),'kiara-new-demo-'));
 delete process.env.MONGODB_URI;delete process.env.VERCEL;delete process.env.KIARA_WORKER_MODE;
 Object.assign(process.env,{KIARA_DATA_DIR:join(dir,'workspace'),KIARA_GLOBAL_BUDGET_DIR:join(dir,'operator'),KIARA_AUTH_MODE:'public_demo',KIARA_SESSION_SECRET:'test-only-session-secret-'.repeat(3),KIARA_MODEL_MODE:'openai',KIARA_PUBLIC_LIVE_ENABLED:'true',OPENAI_API_KEY:'test-placeholder-never-dispatched',KIARA_OPENAI_BUDGET_USD:'50',KIARA_EMAIL_MODE:'preview',KIARA_ALLOW_LIVE_EMAIL:'false'});
 t.after(async()=>{for(const k of Object.keys(process.env))if(!(k in previous))delete process.env[k];Object.assign(process.env,previous);await rm(dir,{recursive:true,force:true});});
 const boot=await GET(new Request(origin+'/api/workspace'),route('workspace'));assert.equal(boot.status,200);
 const first=await boot.json(),cookie=boot.headers.get('set-cookie')!.split(';')[0],scope={id:first.session.demo_id,expires_at:first.session.expires_at};
 const post=(overrides:Record<string,string>={},body:unknown={})=>POST(new Request(origin+'/api/demo/new',{method:'POST',headers:{origin,cookie,'x-csrf-token':first.session.csrf,'content-type':'application/json',...overrides},body:JSON.stringify(body)}),route('demo/new'));
 assert.equal((await post({cookie:''})).status,401);
 assert.equal((await post({'x-csrf-token':'wrong'})).status,403);
 assert.equal((await post({origin:'https://other.example'})).status,403);
 assert.equal((await post({}, {demo_id:'f'.repeat(32)})).status,400);
 await reserveGlobalSpend('new_demo_test_charge',2);await settleGlobalSpend('new_demo_test_charge',1.25);
 const accepted=await withDemoScope(scope,()=>signup({customer_name:'Explicit synthetic retained audit',residence:'US-CA',scenario:'covered',expected_reset_epoch:1},'new-demo-retained-event'));
 await withDemoScope(scope,()=>transaction(s=>{s.workflows[0].model_status='running';}));
 assert.equal((await post()).status,409);
 await withDemoScope(scope,()=>transaction(s=>{s.workflows[0].model_status='blocked';s.workflows[0].unknown_charge=true;}));
 assert.equal((await post()).status,409);
 await withDemoScope(scope,()=>transaction(s=>{s.workflows[0].unknown_charge=false;}));
 const before=await withDemoScope(scope,readState),spendBefore=await globalSpendStatus();
 const created=await post();assert.equal(created.status,201);assert.deepEqual(await created.json(),{new_workspace:true,reset_epoch:1,prior_audit_retained:true,shared_spend_retained:true});
 const freshCookie=created.headers.get('set-cookie')!.split(';')[0];assert.notEqual(freshCookie,cookie);
 const freshResponse=await GET(new Request(origin+'/api/workspace',{headers:{cookie:freshCookie}}),route('workspace'));assert.equal(freshResponse.status,200);
 const fresh=await freshResponse.json();assert.notEqual(fresh.session.demo_id,scope.id);assert.equal(fresh.session.role,'founder');assert.equal(fresh.state.workflows.length,0);assert.equal(fresh.state.events.length,0);
 const retainedResponse=await GET(new Request(origin+'/api/workspace',{headers:{cookie}}),route('workspace'));const retained=await retainedResponse.json();assert.equal(retained.state.workflows[0].workflow_id,accepted.workflow_id);assert.deepEqual(retained.state.events,before.events);
 assert.deepEqual(await globalSpendStatus(),spendBefore);assert.equal(spendBefore.spent_usd,1.25);assert.equal(spendBefore.budget_usd,50);
 process.env.KIARA_AUTH_MODE='demo_simulated';const local=await issueSession('founder',1);
 const denied=await POST(new Request('http://localhost/api/demo/new',{method:'POST',headers:{origin:'http://localhost',cookie:local.cookie.split(';')[0],'x-csrf-token':local.session.csrf,'content-type':'application/json'},body:'{}'}),route('demo/new'));assert.equal(denied.status,403);assert.equal((await denied.json()).error.code,'DEMO_ONLY');
});
