import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,rm,mkdir,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {spawn} from 'node:child_process';
import {seed,provisions,ACTORS,fixture,candidate} from '../src/data/fixtures';
import {transaction,readState,readPhysicalCollections,seedStore,resetStore,verifyStore,closeStore} from '../src/data/store';
import {hash} from '../src/server/hash';
import type {Workflow} from '../src/server/contracts';

function child(source:string,env:NodeJS.ProcessEnv){return new Promise<void>((resolve,reject)=>{const p=spawn(process.execPath,['--import','tsx','--input-type=module','-e',source],{cwd:process.cwd(),env,stdio:['ignore','pipe','pipe']});let error='';p.stderr.on('data',d=>error+=String(d));p.on('error',reject);p.on('close',code=>code===0?resolve():reject(new Error(`Child failed (${code}): ${error}`)));});}
function workflow(s:ReturnType<typeof seed>):Workflow {return {workflow_id:'4a2ca6ed-cd38-4b16-8a70-62454234f470',tenant_id:s.tenant_id,reset_epoch:s.reset_epoch,state:'drafting',state_version:1,created_at:'2026-09-26T18:00:00.000Z',updated_at:'2026-09-26T18:00:00.000Z',customer_name:'Synthetic CA Person',residence:'US-CA',scenario:'main',event_id:'0914b080-73a9-49a8-9d38-dffb7e289fb3',base_revision_id:s.current_revision_id,candidate_revision_id:null,harness_version:1,context_epoch:1,facts:structuredClone(s.facts),assessment:null,validations:[],repair_count:0,missing_bundle_repairs:0,approvals:[],bundle_hash:null,review_input_hash:null,freshness_valid_until:'2026-09-27T18:00:00.000Z',model_mode:'scripted',model_status:'not_started',model_attempts:0,input_tokens:0,output_tokens:0,reserved_cost:0,cost_usd:0,unknown_charge:false,lease_owner:null,lease_epoch:0,lease_until:null,failure:null,evidence_keys:[],citation_offset:null};}

test('persistence: deterministic baseline, atomic transactions, fences and physical records',async t=>{
 const directory=await mkdtemp(join(tmpdir(),'kiara-persistence-test-'));
 const oldDir=process.env.KIARA_DATA_DIR,oldMongo=process.env.MONGODB_URI;
 process.env.KIARA_DATA_DIR=directory;delete process.env.MONGODB_URI;
 t.after(async()=>{await closeStore();if(oldDir===undefined)delete process.env.KIARA_DATA_DIR;else process.env.KIARA_DATA_DIR=oldDir;if(oldMongo===undefined)delete process.env.MONGODB_URI;else process.env.MONGODB_URI=oldMongo;await rm(directory,{recursive:true,force:true});});
 await t.test('baseline is deterministic and seed twice is a byte-identical no-op',async()=>{assert.deepEqual(seed(),seed());assert.equal((await seedStore()).ok,true);const first=await readFile(join(directory,'state.json'),'utf8');await seedStore();assert.equal(await readFile(join(directory,'state.json'),'utf8'),first);const physical=await readPhysicalCollections();assert.equal(physical.customers.length,1);assert.equal(physical.customers[0].residency_evidence[0].region,'NY');assert.equal(physical.review_actions.length,0);assert.equal(physical.evaluation_runs.length,0);assert.equal(physical.legal_source_versions.length,3);assert.equal(physical.legal_chunks.length,32);assert.equal((await readState()).facts.find(f=>f.fact_key==='declared_legal_residence')?.value,'US-NY');assert.ok(provisions().some(p=>p.provision_key==='prov_ccpa_cpi'&&p.text.includes('$26,625,000')));assert.ok(fixture<any[]>('actors.ejson.json').some(a=>a._id===ACTORS.lawyer&&a.roles.includes('lawyer')));});
 await t.test('an exception or async callback cannot commit a partial write',async()=>{const before=await readState();await assert.rejects(transaction(s=>{s.company_name='Partial';throw new Error('abort');}),/abort/);await assert.rejects(transaction((async(s:any)=>{s.company_name='Async';}) as any),/synchronous/);assert.deepEqual(await readState(),before);});
 await t.test('tenant injection, stale epoch and stale CAS are rejected',async()=>{await assert.rejects(transaction(s=>{s.tenant_id='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';}),/another tenant/);await assert.rejects(transaction(()=>null,{expected_reset_epoch:999}),/workspace has reset/);await assert.rejects(transaction(()=>null,{expected_state_version:999}),/workspace changed/);});
 await t.test('immutable revision edits fail; appending a new sealed revision succeeds',async()=>{await assert.rejects(transaction(s=>{s.revisions[0].clauses[0].body='Tampered';}),/sealed hash/);await assert.rejects(transaction(s=>{const r=s.revisions[0];r.clauses[0].body='Resealed tamper';r.content_hash=hash({document_id:r.document_id,title:r.title,policy_updated_on:r.policy_updated_on,clauses:r.clauses});}),/immutable/);await transaction(s=>{s.revisions.push(candidate(s.revisions[0]));});assert.equal((await readState()).revisions.length,2);});
 await t.test('concurrent independent processes do not lose increments',async()=>{const start=(await readState()).context_epoch;const env={...process.env};const source="import {transaction} from './src/data/store.ts';for(let i=0;i<12;i++)await transaction(s=>{s.context_epoch++;});";await Promise.all(Array.from({length:4},()=>child(source,env)));assert.equal((await readState()).context_epoch,start+48);});
 await t.test('dead-owner lock recovers without manual data deletion',async()=>{await mkdir(join(directory,'write.lock'));await writeFile(join(directory,'write.lock','owner'),JSON.stringify({pid:2147483647,token:'dead-owner'}));await transaction(s=>{s.company_name='Recovered';});assert.equal((await readState()).company_name,'Recovered');});
 await t.test('CA event produces scoped customer, context and durable dispatch rows',async()=>{await transaction(s=>{const w=workflow(s);w.facts.find(f=>f.fact_key==='declared_legal_residence')!.value='US-CA';s.workflows.push(w);s.events.push({event_id:w.event_id,tenant_id:s.tenant_id,reset_epoch:s.reset_epoch,aggregate_seq:1,workflow_id:w.workflow_id,type:'user.signed_up',title:'Synthetic CA signup',detail:'Explicit fixture',created_at:w.created_at});});const physical=await readPhysicalCollections();assert.equal(physical.customers.length,2);assert.equal(physical.jobs.length,1);assert.equal(physical.telemetry_spans.length,1);assert.ok(!JSON.stringify(physical.telemetry_spans).includes('Synthetic CA Person'));assert.ok(!JSON.stringify(physical.telemetry_spans).includes('Synthetic CA signup'));assert.ok(physical.company_context_versions.some(c=>c.workflow_id));assert.ok(physical.customers.find(c=>c.workflow_id)?.residency_evidence[0].source_event_id);});
 await t.test('reset retains evaluation campaign reservations and unknown charges',async()=>{const initial=await readState(),key=`${initial.reset_epoch}:campaign:test`;await transaction(s=>{s.receipts[key]={hash:'synthetic-test',result:{kind:'evaluation_campaign',status:'running',unknown_charge:false,reserved_cost_usd:18}};});await assert.rejects(resetStore(initial.reset_epoch),/evaluation campaigns/);await transaction(s=>{(s.receipts[key].result as any).status='complete';});await assert.rejects(resetStore(initial.reset_epoch),/evaluation campaigns/);await transaction(s=>{const result=s.receipts[key].result as any;result.reserved_cost_usd=0;result.unknown_charge=true;});await assert.rejects(resetStore(initial.reset_epoch),/evaluation campaigns/);await transaction(s=>{(s.receipts[key].result as any).unknown_charge=false;});});
 await t.test('reset blocks unknown charges and preserves a surviving monotonic guard',async()=>{await transaction(s=>{s.workflows[0].unknown_charge=true;});const state=await readState();await assert.rejects(resetStore(state.reset_epoch),/unknown charges/);await transaction(s=>{s.workflows[0].unknown_charge=false;});const before=await readState();await resetStore(before.reset_epoch);const after=await readState();assert.equal(after.reset_epoch,before.reset_epoch+1);assert.ok(after.state_version>before.state_version);assert.equal(after.workflows.length,0);assert.equal(after.champion_version,1);assert.equal(after.revisions.length,1);await assert.rejects(transaction(s=>{s.company_name='Old result';},{expected_reset_epoch:before.reset_epoch}),/workspace has reset/);assert.equal((await verifyStore()).ok,true);});
});
