import test,{beforeEach,after} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createHash} from 'node:crypto';
import {command,snapshot} from '../src/v2/service';
import {closeV2Store,readWorkspace,transactWorkspace} from '../src/v2/store';
import {redactHistoricalWorkspace} from '../src/v2/retention';
import type {ActorContext,Role,WorkspaceCommand} from '../src/v2/contracts';

const dirs:string[]=[];
beforeEach(async()=>{await closeV2Store();const dir=await mkdtemp(join(tmpdir(),'kiara-collaboration-'));dirs.push(dir);process.env.KIARA_V2_DATA_DIR=dir;delete process.env.MONGODB_URI;process.env.KIARA_V2_AI_MODE='local'});
after(async()=>{await closeV2Store();await Promise.all(dirs.map(dir=>rm(dir,{recursive:true,force:true})))});
const actor=(id:string,roles:Role[]):ActorContext=>({tenantId:'collaboration-test',actorId:id,mode:'local_demo',expiresAt:Date.now()+3600000,bootstrapRoles:roles});
const owner=()=>actor('owner',['member','business_owner','admin']);
const engineer=()=>actor('engineer',['member','fact_owner']);
const other=()=>actor('other',['member']);
const future=()=>new Date(Date.now()+86400000).toISOString();
let sequence=0;
const send=async(a:ActorContext,change:WorkspaceCommand)=>command(a,{idempotencyKey:`collaboration-${++sequence}`,expectedVersion:(await snapshot(a)).version,command:change});
const code=(expected:string)=>(failure:unknown)=>(failure as {code:string}).code===expected;
async function scenario(){const a=owner(),b=engineer();await snapshot(b);const conversation=await send(a,{type:'conversation.create',title:'PRIVATE CONVERSATION HISTORY',scope:{kind:'private',actorIds:['owner']}});const conversationId=String(conversation.result.conversationId);const created=await send(a,{type:'message.send',conversationId,text:'What if PRIVATE SECRET ASSUMPTION stays internal?'});const original=created.snapshot.scenarios[0];const edited=await send(a,{type:'scenario.update',scenarioId:original.id,expectedRecordVersion:original.version,assumptions:['PRIVATE SECRET ASSUMPTION','Selected hypothetical: synthetic test data only']});return {a,b,conversationId,scenario:edited.snapshot.scenarios[0]}}
async function shared(){const state=await scenario();const r=await send(state.a,{type:'scenario.share',scenarioId:state.scenario.id,expectedRecordVersion:state.scenario.version,title:'Selected test scenario',assumptionIndexes:[1],includeQuestions:false,recipientActorIds:['engineer'],validUntil:future()});return {...state,share:r.snapshot.sharedScenarios[0]}}
async function matter(){const a=owner(),b=engineer();await snapshot(b);const r=await send(a,{type:'matter.create',title:'Team product decision',objective:'Confirm a factual question without delegating legal authority',scope:{kind:'team',actorIds:[]}});return {a,b,m:r.snapshot.matters[0]}}
async function acceptedDelegation(){const state=await matter();const offered=await send(state.a,{type:'delegation.offer',matterId:state.m.id,expectedMatterVersion:state.m.version,recipientActorId:'engineer',topics:['product_facts'],validUntil:future()});const d=offered.snapshot.delegations[0];const accepted=await send(state.b,{type:'delegation.accept',delegationId:d.id,expectedRecordVersion:d.version});return {...state,d:accepted.snapshot.delegations[0]}}

test('selected scenario sharing discloses only inspected assumptions, never private history or origin IDs',async()=>{
 const {a,b,scenario:origin,conversationId,share}=await shared(),recipient=await snapshot(b);
 assert.equal(recipient.sharedScenarios.length,1);const view=recipient.sharedScenarios[0];assert.deepEqual(view.assumptions,['Selected hypothetical: synthetic test data only']);assert.deepEqual(view.questions,[]);assert.equal(view.originScenarioId,undefined);assert.equal('provenance' in view,false);assert.equal('scenarioId' in view,false);assert.equal(recipient.conversations.length,0);assert.equal(recipient.messages.length,0);assert.equal(recipient.scenarios.length,0);
 const serialized=JSON.stringify(recipient);assert.ok(!serialized.includes('PRIVATE SECRET ASSUMPTION'));assert.ok(!serialized.includes('PRIVATE CONVERSATION HISTORY'));assert.ok(!serialized.includes(origin.id));assert.ok(!serialized.includes(conversationId));
 const unrelated=await snapshot(other());assert.equal(unrelated.sharedScenarios.length,0);await send(a,{type:'scenario.share_revoke',shareId:share.id,expectedRecordVersion:share.version,reason:'Selected review ended'});assert.equal((await snapshot(b)).sharedScenarios.length,0);
});

test('scenario edits immediately stale the approved frozen share instead of disclosing new text',async()=>{const {a,b,scenario:origin}=await shared();await send(a,{type:'scenario.update',scenarioId:origin.id,expectedRecordVersion:origin.version,assumptions:['A new private assumption']});assert.equal((await snapshot(b)).sharedScenarios.length,0);const retained=(await snapshot(a)).sharedScenarios[0];assert.equal(retained.status,'stale');assert.deepEqual(retained.assumptions,['Selected hypothetical: synthetic test data only'])});

test('recipient membership revision and expiry withdraw scenario viewing',async()=>{const {a,b}=await shared();await transactWorkspace(a.tenantId,s=>{s.memberships.find(member=>member.actorId===b.actorId)!.version++});assert.equal((await snapshot(b)).sharedScenarios.length,0);await transactWorkspace(a.tenantId,s=>{s.memberships.find(member=>member.actorId===b.actorId)!.version--;s.scenarioShares![0].validUntil=new Date(0).toISOString()});assert.equal((await snapshot(b)).sharedScenarios.length,0)});

test('sharing cannot promote restricted source access or use stale selections',async()=>{const {a,b,scenario:origin}=await scenario();const saved=await send(a,{type:'document.add',title:'Restricted evidence',body:'Private contract detail',authority:'executed',scope:{kind:'private',actorIds:['owner']}});await transactWorkspace(a.tenantId,s=>{s.scenarios.find(record=>record.id===origin.id)!.provenance.sourceIds=[String(saved.result.sourceId)]});await assert.rejects(()=>send(a,{type:'scenario.share',scenarioId:origin.id,expectedRecordVersion:origin.version,title:'Selected scenario',assumptionIndexes:[1],includeQuestions:false,recipientActorIds:[b.actorId],validUntil:future()}),code('SOURCE_SHARING_DENIED'));await assert.rejects(()=>send(a,{type:'scenario.share',scenarioId:origin.id,expectedRecordVersion:origin.version-1,title:'Old scenario',assumptionIndexes:[0],includeQuestions:false,recipientActorIds:[b.actorId],validUntil:future()}),code('VERSION_CONFLICT'));assert.equal((await snapshot(b)).sources.length,0)});

test('routing requires existing capacity, recipient acceptance and a separate grantor choice',async()=>{
 const {a,b,m}=await matter();await assert.rejects(()=>send(a,{type:'delegation.offer',matterId:m.id,expectedMatterVersion:m.version,recipientActorId:'engineer',topics:['legal_questions'],validUntil:future()}),code('RECIPIENT_CAPACITY'));
 const offered=await send(a,{type:'delegation.offer',matterId:m.id,expectedMatterVersion:m.version,recipientActorId:'engineer',topics:['product_facts'],validUntil:future()}),d=offered.snapshot.delegations[0];await assert.rejects(()=>send(a,{type:'delegation.accept',delegationId:d.id,expectedRecordVersion:d.version}),code('RECIPIENT_ACCEPTANCE_REQUIRED'));await assert.rejects(()=>send(a,{type:'routing.set',delegationId:d.id,expectedRecordVersion:d.version,topic:'product_facts'}),code('DELEGATION_REQUIRED'));
 const accepted=await send(b,{type:'delegation.accept',delegationId:d.id,expectedRecordVersion:d.version});assert.equal(accepted.snapshot.matters[0].tasks[0].ownerId,'owner');const current=accepted.snapshot.delegations[0];const routed=await send(a,{type:'routing.set',delegationId:current.id,expectedRecordVersion:current.version,topic:'product_facts'});assert.equal(routed.snapshot.matters[0].tasks.find(task=>task.kind==='fact')!.ownerId,'engineer');assert.equal(routed.snapshot.approvals.length,0);assert.equal(routed.snapshot.facts.length,0);
 await transactWorkspace(a.tenantId,s=>{assert.equal(s.matters[0].tasks[0].ownerId,'owner')});
 await send(b,{type:'delegation.revoke',delegationId:current.id,expectedRecordVersion:current.version,reason:'Reviewer unavailable'});const fallback=await snapshot(a);assert.equal(fallback.matters[0].tasks[0].ownerId,'owner');assert.equal(fallback.routing[0].effective,false);assert.equal(fallback.matters[0].tasks[0].status,'pending');
});

test('routing expiry derives the base owner without mutating stored task authority',async()=>{const {a,m,d}=await acceptedDelegation();await send(a,{type:'routing.set',delegationId:d.id,expectedRecordVersion:d.version,topic:'product_facts'});await transactWorkspace(a.tenantId,s=>{s.routingDelegations![0].validUntil=new Date(0).toISOString()});const result=await snapshot(a);assert.equal(result.matters.find(record=>record.id===m.id)!.tasks[0].ownerId,'owner');assert.equal(result.routing[0].effective,false);assert.equal(result.delegations[0].status,'expired')});

test('existing conversation links preserve identity and refuse private-to-team scope expansion',async()=>{const {a,m}=await matter();const privateConversation=await send(a,{type:'conversation.create',title:'Private context',scope:{kind:'private',actorIds:['owner']}});const p=privateConversation.snapshot.conversations[0];await assert.rejects(()=>send(a,{type:'conversation.link_matter',conversationId:p.id,matterId:m.id,expectedConversationVersion:p.version,expectedMatterVersion:m.version}),code('LINK_SCOPE_MISMATCH'));const created=await send(a,{type:'conversation.create',title:'Same team conversation',scope:{kind:'team',actorIds:[]}});const c=created.snapshot.conversations.at(-1)!;const linked=await send(a,{type:'conversation.link_matter',conversationId:c.id,matterId:m.id,expectedConversationVersion:c.version,expectedMatterVersion:m.version});assert.equal(linked.snapshot.matters.length,1);assert.deepEqual(linked.snapshot.matters[0].conversationIds,[c.id]);assert.equal(linked.snapshot.conversations.find(record=>record.id===c.id)!.matterId,m.id);const transcript='Confirm this is still the same work',next=await send(a,{type:'message.send',conversationId:c.id,text:transcript,channel:'voice',voiceConfirmed:true,voiceInterpretation:{transcriptHash:createHash('sha256').update(transcript,'utf8').digest('hex'),subjectId:'',subjectHash:'',names:[],dates:[],amounts:[],ambiguityResolved:true}});assert.equal(next.snapshot.matters.length,1);assert.equal(next.snapshot.messages.at(-1)!.conversationId,c.id)});


test('source deletion redacts selected scenario sharing from current and historical records',async()=>{
 const {a,b,scenario:origin}=await scenario();const saved=await send(a,{type:'document.add',title:'SHARE-SOURCE confidential register',body:'SHARE-SOURCE permitted source',authority:'executed',scope:{kind:'team',actorIds:[]}});const sourceId=String(saved.result.sourceId);await transactWorkspace(a.tenantId,s=>{const record=s.scenarios.find(record=>record.id===origin.id)!;record.provenance.sourceIds=[sourceId];record.assumptions=['SHARE-SOURCE selected assumption']});
 await send(a,{type:'scenario.share',scenarioId:origin.id,expectedRecordVersion:origin.version,title:'SHARE-SOURCE selected snapshot',assumptionIndexes:[0],includeQuestions:false,recipientActorIds:[b.actorId],validUntil:future()});assert.equal((await snapshot(b)).sharedScenarios.length,1);const before=await readWorkspace(a.tenantId);await send(a,{type:'source.revoke',sourceId,delete:true,reason:'Remove the supplied collaboration source'});const state=await readWorkspace(a.tenantId);assert.equal((await snapshot(b)).sharedScenarios.length,0);assert.equal((await snapshot(a)).sharedScenarios.length,0);assert.deepEqual(state.scenarioShares![0].assumptions,[]);assert.equal(state.scenarioShares![0].title,'Removed evidence');assert.doesNotMatch(JSON.stringify(state),/SHARE-SOURCE/);const historical=structuredClone(before);redactHistoricalWorkspace(historical,state.deletionJobs![0]);assert.doesNotMatch(JSON.stringify(historical),/SHARE-SOURCE/);
});

test('a business owner cannot link another user’s private conversation, even when the proposed scopes match',async()=>{
 const a=owner(),b=actor('other-owner',['member','business_owner']);await snapshot(a);const created=await send(b,{type:'conversation.create',title:'Other owner private history',scope:{kind:'private',actorIds:[b.actorId]}}),conversation=created.snapshot.conversations[0];const work=await send(b,{type:'matter.create',title:'Other owner private work',objective:'Private objective',scope:{kind:'private',actorIds:[b.actorId]}}),m=work.snapshot.matters[0];assert.deepEqual(conversation.scope,m.scope);await assert.rejects(()=>send(a,{type:'conversation.link_matter',conversationId:conversation.id,matterId:m.id,expectedConversationVersion:conversation.version,expectedMatterVersion:m.version}),code('NOT_FOUND'));const snapshotA=await snapshot(a);assert.equal(snapshotA.conversations.length,0);assert.equal(snapshotA.matters.length,0);assert.equal((await snapshot(b)).conversations[0].matterId,null);
});
