import test,{beforeEach,after} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {command,snapshot} from '../src/v2/service';
import {closeV2Store,transactWorkspace} from '../src/v2/store';
import type {ActorContext,CounselEngagement,Role,WorkspaceCommand} from '../src/v2/contracts';
let dir:string;const dirs:string[]=[];
beforeEach(async()=>{await closeV2Store();dir=await mkdtemp(join(tmpdir(),'kiara-counsel-'));dirs.push(dir);process.env.KIARA_V2_DATA_DIR=dir;delete process.env.MONGODB_URI;process.env.KIARA_V2_AI_MODE='local';});
after(async()=>{await closeV2Store();await Promise.all(dirs.map(d=>rm(d,{recursive:true,force:true})));});
const actor=(id:string,roles:Role[]):ActorContext=>({tenantId:'counsel-test',actorId:id,roles,mode:'local_demo',expiresAt:Date.now()+3600000,bootstrapRoles:roles} as ActorContext);
const owner=()=>actor('owner',['member','business_owner','fact_owner','admin']);const reviewer=()=>actor('counsel',['member','legal_reviewer']);
let sequence=0;const send=async(a:ActorContext,c:WorkspaceCommand)=>command(a,{idempotencyKey:`counsel-${++sequence}`,expectedVersion:(await snapshot(a)).version,command:c});
const future=()=>new Date(Date.now()+86400000).toISOString();const code=(value:string)=>(e:unknown)=>(e as {code:string}).code===value;
async function setup(){const a=owner(),b=reviewer();await snapshot(b);const privateScope={kind:'private' as const,actorIds:['owner']};await send(a,{type:'conversation.create',title:'Private conversations never in counsel packet',scope:privateScope});const doc=await send(a,{type:'document.add',title:'Private selected agreement',body:'Selected contract: 30 day notice, exceptions require review.',authority:'executed',kind:'agreement',scope:privateScope});const matter=await send(a,{type:'matter.create',title:'Private legal review',objective:'Review selected notice obligations',scope:privateScope});const m=matter.snapshot.matters[0];const prepared=await send(a,{type:'matter.prepare',matterId:m.id,expectedRecordVersion:m.version});const p=prepared.snapshot.proposals[0];const req=await send(a,{type:'counsel.request',matterId:m.id,route:'existing',providerName:'Named existing counsel'});return {a,b,m,p,e:req.snapshot.counsel[0],sourceId:String(doc.result.sourceId)};}
async function ready(a:ActorContext,e:CounselEngagement){let r=await send(a,{type:'counsel.intake',engagementId:e.id,expectedRecordVersion:e.version,counselActorId:'counsel',conflictsCleared:true,intakeEvidence:'Owner recorded external intake/conflicts approval, reference intake-2026-1.'});e=r.snapshot.counsel[0];r=await send(a,{type:'counsel.engage',engagementId:e.id,expectedRecordVersion:e.version,terms:'Review the selected agreement and return proposed revisions. No external filing or signing.',feeCap:500,currency:'USD',responseDueAt:future()});return r.snapshot.counsel[0];}
async function share(a:ActorContext,e:CounselEngagement){return send(a,{type:'counsel.share',engagementId:e.id,expectedRecordVersion:e.version,packetHash:e.packetHash!,recipientActorId:'counsel',validUntil:future()});}

test('counsel intake, fee approval and exact packet sharing are separate recorded decisions',async()=>{const {a,b,e}=await setup();assert.equal((await snapshot(b)).counsel.length,0);await assert.rejects(()=>share(a,e),code('COUNSEL_MEMBERSHIP_REQUIRED'));await assert.rejects(()=>send(a,{type:'counsel.intake',engagementId:e.id,expectedRecordVersion:e.version,counselActorId:'counsel',conflictsCleared:false,intakeEvidence:'Pending'}),code('CONFLICTS_PENDING'));const engaged=await ready(a,e);assert.equal(engaged.feeCap,500);assert.equal(engaged.status,'sharing_pending');assert.equal((await snapshot(b)).sources.length,0);await assert.rejects(()=>send(a,{type:'counsel.share',engagementId:e.id,expectedRecordVersion:engaged.version,packetHash:'unreviewed',recipientActorId:'counsel',validUntil:future()}),code('SHARING_INTENT_CHANGED'));const shared=await share(a,engaged);assert.equal(shared.snapshot.counsel[0].status,'review_pending');const visible=await snapshot(b);assert.equal(visible.matters.length,1);assert.equal(visible.documents.length,1);assert.equal(visible.proposals.length,1);assert.equal(visible.conversations.length,0);assert.equal(visible.messages.length,0);assert.match(visible.counsel[0].packet,/complete records/);const other=actor('another-reviewer',['member','legal_reviewer']);assert.equal((await snapshot(other)).counsel.length,0);assert.equal((await snapshot(other)).sources.length,0);});

test('source, recipient membership, explicit revoke and expiry immediately withdraw granted records',async()=>{for(const mode of ['source','membership','revoke','expiry'] as const){await beforeReset();const {a,b,e,sourceId}=await setup();const shared=await share(a,await ready(a,e));const current=shared.snapshot.counsel[0];assert.equal((await snapshot(b)).sources.length,1);if(mode==='source')await send(a,{type:'source.revoke',sourceId,reason:'Access withdrawn'});if(mode==='membership')await transactWorkspace(a.tenantId,s=>{s.memberships.find(m=>m.actorId===b.actorId)!.version++;});if(mode==='revoke')await send(a,{type:'counsel.revoke',engagementId:e.id,expectedRecordVersion:current.version,reason:'Engagement ended'});if(mode==='expiry')await transactWorkspace(a.tenantId,s=>{s.counsel[0].sharing!.expiresAt=new Date(0).toISOString();});const visible=await snapshot(b);assert.equal(visible.sources.length,0,mode);assert.equal(visible.proposals.length,0,mode);assert.equal(visible.counsel.length,0,mode);}});
async function beforeReset(){await closeV2Store();dir=await mkdtemp(join(tmpdir(),'kiara-counsel-reset-'));dirs.push(dir);process.env.KIARA_V2_DATA_DIR=dir;}

test('counsel returned edits preserve original proposal and require new exact decisions',async()=>{const {a,b,e,p,m}=await setup();await send(a,{type:'approval.record',proposalId:p.id,proposalHash:p.contentHash,capacity:'business',validUntil:future()});const shared=await share(a,await ready(a,e));const current=shared.snapshot.counsel[0];const returned=await send(b,{type:'counsel.return',engagementId:e.id,expectedRecordVersion:current.version,proposalId:p.id,proposalHash:p.contentHash,disposition:'revised_proposal',body:'Proposed reviewed notice text; legal clearance remains a separate decision.',note:'Preserve the contractual exception; confirm release scope.'});const result=await snapshot(a);assert.equal(result.proposals.length,2);assert.equal(result.proposals.find(x=>x.id===p.id)!.body,p.body);assert.equal(result.proposals.find(x=>x.id===p.id)!.status,'superseded');assert.equal(result.matters.find(x=>x.id===m.id)!.state,'business_review');assert.ok(result.approvals.filter(x=>x.capacity==='business').every(x=>x.status==='invalidated'));assert.equal(result.approvals.filter(x=>x.capacity==='legal').length,0);assert.equal(returned.snapshot.counsel[0].status,'returned');assert.equal(returned.snapshot.proposals.length,2);const next=result.proposals.find(x=>x.id===result.matters[0].proposalId)!;await send(a,{type:'approval.record',proposalId:next.id,proposalHash:next.contentHash,capacity:'business',validUntil:future()});assert.equal((await snapshot(b)).matters.length,1);const cleared=await send(b,{type:'approval.record',proposalId:next.id,proposalHash:next.contentHash,capacity:'legal',validUntil:future()});assert.equal(cleared.snapshot.matters[0].state,'authorized_action');});

test('escalation invalidates prior engagement and access; referral stays unavailable; terminal work cannot revive',async()=>{const {a,b,e,m}=await setup();const shared=await share(a,await ready(a,e));const escalated=await send(a,{type:'counsel.escalate',engagementId:e.id,expectedRecordVersion:shared.snapshot.counsel[0].version,reason:'budget_increase',detail:'Requested fee cap 750 requires a new explicit decision.'});assert.equal(escalated.snapshot.counsel[0].engagementApproval,null);assert.equal(escalated.snapshot.counsel[0].feeCap,500);assert.equal((await snapshot(b)).sources.length,0);await assert.rejects(()=>share(a,escalated.snapshot.counsel[0]),code('ENGAGEMENT_REQUIRED'));const referral=await send(a,{type:'counsel.request',matterId:m.id,route:'referral'});assert.equal(referral.snapshot.counsel.at(-1)!.status,'unavailable');const current=referral.snapshot.matters[0];await send(a,{type:'matter.cancel',matterId:m.id,expectedRecordVersion:current.version,reason:'Withdrawn'});await assert.rejects(()=>send(a,{type:'counsel.request',matterId:m.id,route:'existing'}),code('MATTER_TERMINAL'));});

test('sharing an older packet cannot disclose newly revised proposal bytes or added matter tasks',async()=>{
 for(const change of ['proposal','task'] as const){await beforeReset();const {a,b,e,p,m}=await setup();if(change==='proposal')await send(a,{type:'proposal.revise',proposalId:p.id,expectedRecordVersion:p.version,body:'New confidential wording absent from the prepared packet.'});else await transactWorkspace(a.tenantId,s=>{s.matters.find(x=>x.id===m.id)!.tasks.push({id:'new-private-task',title:'New confidential task absent from the packet',ownerId:a.actorId,status:'pending',kind:'fact',dueAt:null,deadlineType:'undated',evidenceIds:[]});});const prepared=await ready(a,e);await assert.rejects(()=>share(a,prepared),code('COUNSEL_PACKET_STALE'));assert.equal((await snapshot(b)).proposals.length,0);assert.equal((await snapshot(b)).counsel.length,0);}
});


test('counsel sharing rejects expired, future and malformed bound facts even when versions match',async()=>{
 for(const mode of ['expired','future','malformed'] as const){await beforeReset();const {a,b,e}=await setup();await transactWorkspace(a.tenantId,s=>{const p=s.proposals[0],m=s.matters[0],id='time-bound-fact';s.facts.push({...structuredClone(p),id,entityId:s.entityId,predicate:'scope',value:'planned only',status:'confirmed',practice:'planned',ownerId:a.actorId,observedAt:new Date().toISOString(),validFrom:mode==='future'?new Date(Date.now()+86400000).toISOString():null,validUntil:mode==='expired'?new Date(0).toISOString():mode==='malformed'?'invalid':null,confirmedBy:a.actorId,confirmedAt:new Date().toISOString(),supersedesId:null,originVersion:1,reuse:'company',conversationId:null});p.dependencies.factVersions[id]=p.version;m.factIds.push(id);});const prepared=await ready(a,e);await assert.rejects(()=>share(a,prepared),code('DEPENDENCIES_CHANGED'));assert.equal((await snapshot(b)).proposals.length,0);}
});
