import test,{beforeEach,after} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {command,snapshot} from '../src/v2/service';
import {closeV2Store,readWorkspace} from '../src/v2/store';
import {documentHeads,compareDocumentText} from '../src/v2/document-lifecycle';
import {retainOriginal,readOriginal} from '../src/v2/objects';
import {exportReviewDocx,parseDocument} from '../src/v2/document-files';
import type {ActorContext,Role,WorkspaceCommand} from '../src/v2/contracts';
const dirs:string[]=[];let sequence=0;
beforeEach(async()=>{await closeV2Store();const dir=await mkdtemp(join(tmpdir(),'kiara-doc-lifecycle-'));dirs.push(dir);process.env.KIARA_V2_DATA_DIR=dir;process.env.KIARA_ORIGINALS_DIR=join(dir,'originals');delete process.env.MONGODB_URI;delete process.env.KIARA_ORIGINALS_MODE;process.env.KIARA_V2_AI_MODE='local';});
after(async()=>{await closeV2Store();delete process.env.KIARA_ORIGINALS_DIR;await Promise.all(dirs.map(d=>rm(d,{recursive:true,force:true})));});
const actor=(id:string,roles:Role[]):ActorContext=>({tenantId:'document-test',actorId:id,mode:'local_demo',expiresAt:Date.now()+3600000,bootstrapRoles:roles});
const owner=()=>actor('owner',['member','business_owner','fact_owner','admin']);
const send=async(a:ActorContext,c:WorkspaceCommand,trusted?:{originalObjectRef?:string})=>command(a,{idempotencyKey:`document-${++sequence}`,expectedVersion:(await snapshot(a)).version,command:c},trusted);
const code=(value:string)=>(e:unknown)=>(e as {code:string}).code===value;

test('template substitution creates a private unapproved draft without expanding scope or treating values as company facts',async()=>{
 const a=owner(),peer=actor('peer',['member']);await snapshot(peer);const t=await send(a,{type:'document.add',title:'Private notice template',body:'Dear {{CUSTOMER}},\nNotice date: {{DATE}}.\nRegards {{CUSTOMER}}.',authority:'template',kind:'template',scope:{kind:'private',actorIds:['owner']}});const template=t.snapshot.documents[0];await assert.rejects(()=>send(a,{type:'document.from_template',templateRevisionId:template.id,expectedContentHash:template.contentHash,title:'Notice',values:{CUSTOMER:'Acme'}}),code('TEMPLATE_FIELDS_CHANGED'));const created=await send(a,{type:'document.from_template',templateRevisionId:template.id,expectedContentHash:template.contentHash,title:'Acme proposed notice',values:{CUSTOMER:'Acme $&',DATE:'Proposed 2027-01-01'}});const draft=created.snapshot.documents.at(-1)!;assert.match(draft.body,/Dear Acme \$&,/);assert.equal(draft.authority,'draft');assert.notEqual(draft.documentId,template.documentId);assert.deepEqual(draft.scope,template.scope);assert.equal(created.snapshot.facts.length,0);assert.equal(created.snapshot.approvals.length,0);assert.equal((await snapshot(peer)).documents.length,0);assert.equal(created.snapshot.documents[0].body,template.body);await send(a,{type:'source.revoke',sourceId:template.sourceId,reason:'Template no longer approved'});assert.equal((await snapshot(a)).documents.length,0);
});
test('reimport retains exact original bytes and immutable revisions, rejects stale heads and invalidates dependent decisions',async()=>{
 const a=owner();let result=await send(a,{type:'document.add',title:'Review draft',body:'Thirty days notice.\nPreserve this exception.',authority:'draft',kind:'draft'});const old=structuredClone(result.snapshot.documents[0]);result=await send(a,{type:'matter.create',title:'Review notice',objective:'Prepare a controlled draft',scope:{kind:'team',actorIds:[]}});const m=result.snapshot.matters[0];const objective=await send(a,{type:'fact.propose',predicate:'business_objective',value:m.objective,practice:'planned'}),fact=objective.snapshot.facts.at(-1)!;await send(a,{type:'fact.confirm',factId:fact.id,expectedRecordVersion:fact.version,expectedOriginVersion:fact.originVersion});result=await send(a,{type:'matter.prepare',matterId:m.id,expectedRecordVersion:m.version});const p=result.snapshot.proposals[0];await send(a,{type:'approval.record',proposalId:p.id,proposalHash:p.contentHash,capacity:'business',validUntil:new Date(Date.now()+86400000).toISOString()});const bytes=await exportReviewDocx({title:'Returned edits',body:'Forty-five days notice.\nPreserve this exception.',manifest:['Review copy; no approval.']});const parsed=await parseDocument(bytes,'returned.docx'),ref=await retainOriginal(a.tenantId,bytes);
 result=await send(a,{type:'document.reimport',baseRevisionId:old.id,expectedContentHash:old.contentHash,body:parsed.text,note:'Counsel returned a proposed notice-period change; distinct legal review still required.'},{originalObjectRef:JSON.stringify(ref)});const next=result.snapshot.documents.at(-1)!;assert.deepEqual(result.snapshot.documents.find(d=>d.id===old.id),old);assert.equal(next.documentId,old.documentId);assert.equal(next.parentRevisionId,old.id);assert.equal(next.revision,2);assert.equal(next.authority,'draft');assert.equal(result.snapshot.proposals[0].status,'invalidated');assert.ok(result.snapshot.approvals.every(x=>x.status==='invalidated'));assert.equal(result.snapshot.matters[0].state,'needs_facts');assert.deepEqual(await readOriginal(a.tenantId,ref),bytes);
 await assert.rejects(()=>send(a,{type:'document.reimport',baseRevisionId:old.id,expectedContentHash:old.contentHash,body:'Stale concurrent edits',note:'Must not overwrite'}),code('DOCUMENT_BASE_CHANGED'));assert.deepEqual(documentHeads((await readWorkspace(a.tenantId)).documents).map(x=>x.id),[next.id]);
 result=await send(a,{type:'matter.prepare',matterId:m.id,expectedRecordVersion:result.snapshot.matters[0].version});assert.deepEqual(result.snapshot.matters[0].documentIds,[next.id]);
});
test('signed and effective originals require a separate amendment instead of replacement',async()=>{
 const a=owner();for(const authority of ['executed','effective'] as const){const r=await send(a,{type:'document.add',title:'Protected original',body:'Original promise.',authority,kind:'agreement'});const d=r.snapshot.documents.at(-1)!;await assert.rejects(()=>send(a,{type:'document.reimport',baseRevisionId:d.id,expectedContentHash:d.contentHash,body:'Replacement promise.',note:'Not permitted in place'}),code('AMENDMENT_REQUIRED'));assert.equal((await snapshot(a)).documents.find(x=>x.id===d.id)!.body,'Original promise.');}
});
test('comparison reconstructs both complete texts and preserves insertions, removals and exceptions',()=>{
 const left='Header\n30 days\nExcept synthetic data\nEnd',right='Header\n45 days\nExcept synthetic data\nNew remedy\nEnd';const result=compareDocumentText(left,right);assert.equal(result.granularity,'paragraph');assert.equal(result.changes.filter(c=>c.kind!=='added').map(c=>c.text).join('\n'),left);assert.equal(result.changes.filter(c=>c.kind!=='removed').map(c=>c.text).join('\n'),right);assert.ok(result.changes.some(c=>c.kind==='unchanged'&&c.text==='Except synthetic data'));assert.ok(result.changes.some(c=>c.kind==='removed'&&c.text==='30 days'));const fallback=compareDocumentText('a\n'.repeat(1200),'b\n'.repeat(1200));assert.equal(fallback.granularity,'whole_document');
});
