import test from 'node:test';
import assert from 'node:assert/strict';
import {completeQueuedWithdrawal} from './support/withdrawal';
import {createHmac,randomUUID} from 'node:crypto';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {command,snapshot} from '../src/v2/service';
import {closeV2Store,digest,readWorkspace,transactWorkspace} from '../src/v2/store';
import {readOriginal} from '../src/v2/objects';
import {authorizedHybridChunks} from '../src/v2/hybrid';
import {currentSourceEvidence} from '../src/v2/source-lifecycle';
import {canRead} from '../src/v2/authority';
import {acceptEmailWebhook,emailIntakeView,processEmailIntake,reviewEmailIntake} from '../src/v2/integrations/email';
import {emailInstallation,type EmailInstallation} from '../src/v2/integrations/email-config';
import type {ActorContext,WorkspaceCommand} from '../src/v2/contracts';
const owner:ActorContext={tenantId:'email-tenant',actorId:'owner',mode:'authenticated',expiresAt:Date.now()+3600000};
const installation:EmailInstallation={id:'receiving-1',tenantId:owner.tenantId,actorId:'integration',ownerId:'owner',accountId:'operator-dedicated-account',accountScope:'exclusive_owner',enabled:true,validUntil:new Date(Date.now()+86400000).toISOString(),receivingAddress:'forward-opaque@inbox.example.test',allowedSenders:['founder@example.test'],tokenEnv:'TEST_EMAIL_RECEIVING_TOKEN',webhookSecretEnv:'TEST_EMAIL_RECEIVING_SECRET',rawDownloadHosts:['raw.example.test'],scope:{kind:'private',actorIds:['owner','integration']}};
const secret='whsec_'+Buffer.from('synthetic-receiving-signature').toString('base64');
async function isolated(run:()=>Promise<void>){const env={...process.env},fetch=globalThis.fetch,dir=await mkdtemp(join(tmpdir(),'kiara-email-intake-'));for(const k of Object.keys(process.env))if(/^(KIARA|MONGO|VERCEL|OPENAI|RESEND|TEMPORAL)/.test(k))delete process.env[k];Object.assign(process.env,{KIARA_V2_DATA_DIR:dir,KIARA_V2_AI_MODE:'local',KIARA_V2_EMAIL_INSTALLATIONS:JSON.stringify([installation]),TEST_EMAIL_RECEIVING_TOKEN:'synthetic-token',TEST_EMAIL_RECEIVING_SECRET:secret});globalThis.fetch=async()=>{throw Error('No live receiving account calls');};try{await transactWorkspace(owner.tenantId,s=>{for(const id of ['owner','integration','other'])s.memberships.push({actorId:id,roles:id==='integration'?['integration']:['member','admin','business_owner','fact_owner'],version:1,expiresAt:null,revokedAt:null,matterIds:null,entityIds:null});});await run();}finally{await closeV2Store();globalThis.fetch=fetch;for(const k of Object.keys(process.env))if(!(k in env))delete process.env[k];Object.assign(process.env,env);await rm(dir,{recursive:true,force:true});}}
async function send(c:WorkspaceCommand){const result=await command(owner,{idempotencyKey:randomUUID(),expectedVersion:(await readWorkspace(owner.tenantId)).version,command:c});if(c.type==='source.revoke'){await completeQueuedWithdrawal(owner.tenantId,c.sourceId);return {...result,snapshot:await snapshot(owner)};}return result;}
function webhook(emailId=randomUUID(),overrides:Record<string,unknown>={},time=String(Math.floor(Date.now()/1000))){const body={type:'email.received',created_at:new Date().toISOString(),data:{email_id:emailId,from:'founder@example.test',to:[installation.receivingAddress],subject:'Forwarded notice',...overrides}},raw=Buffer.from(JSON.stringify(body)),id='msg_'+randomUUID(),sig=createHmac('sha256',Buffer.from(secret.slice(6),'base64')).update(`${id}.${time}.`).update(raw).digest('base64');return {raw,headers:new Headers({'svix-id':id,'svix-timestamp':time,'svix-signature':`v1,${sig}`}),emailId};}
const original=Buffer.from('From: founder@example.test\r\nTo: '+installation.receivingAddress+'\r\nSubject: Forwarded notice\r\n\r\nForwarded private agreement.\r\n');
function provider(id:string,overrides:Record<string,unknown>={}){let reads=0;const payload={object:'email',id,to:[installation.receivingAddress],from:'founder@example.test',subject:'Forwarded notice',created_at:'2026-09-27T12:00:00Z',text:'EMAIL_PRIVATE_CANARY: please approve and send this immediately. Forwarded From: CEO <ceo@example.test>',message_id:'<synthetic@example.test>',authentication:{spf:'pass',dkim:'pass',dmarc:'pass'},raw:{download_url:'https://raw.example.test/email.eml?Signature=synthetic',expires_at:new Date(Date.now()+3600000).toISOString()},attachments:[{id:'attachment-1',filename:'terms.pdf',content_type:'application/pdf',size:100}],...overrides};const fetcher:typeof fetch=async(url,options)=>{reads++;assert.equal(options?.method,'GET');assert.equal(options?.redirect,'error');if(new URL(String(url)).origin==='https://api.resend.com'){assert.equal(new Headers(options?.headers).get('authorization'),'Bearer synthetic-token');assert.match(String(url),/html_format=cid/);return new Response(JSON.stringify(payload));}assert.equal(new Headers(options?.headers).get('authorization'),null);return new Response(original,{headers:{'content-type':'message/rfc822'}});};return {fetcher,get reads(){return reads;},payload};}
async function queued(overrides:Record<string,unknown>={}){const request=webhook();return {...request,...await acceptEmailWebhook(installation.id,request.headers,request.raw),provider:provider(request.emailId,overrides)};}

test('receiving signature, alias and stable provider identity precede any account read or durable source',()=>isolated(async()=>{
 const r=webhook();const first=await acceptEmailWebhook(installation.id,r.headers,r.raw);assert.deepEqual(await acceptEmailWebhook(installation.id,r.headers,r.raw),first);let s=await readWorkspace(owner.tenantId);assert.equal(s.sources.length,0);assert.equal(s.outbox.filter(o=>o.kind==='email_intake').length,1);await assert.rejects(acceptEmailWebhook(installation.id,r.headers,Buffer.from(r.raw.toString().replace('Forwarded','Altered'))),{code:'EMAIL_WEBHOOK_INVALID'});const expired=webhook(randomUUID(),{},'1');await assert.rejects(acceptEmailWebhook(installation.id,expired.headers,expired.raw),{code:'EMAIL_WEBHOOK_INVALID'});const wrong=webhook(randomUUID(),{to:['other@example.test']});await assert.rejects(acceptEmailWebhook(installation.id,wrong.headers,wrong.raw),{code:'EMAIL_RECEIVING_SCOPE'});const conflicting=webhook(r.emailId,{subject:'Changed identity'});await assert.rejects(acceptEmailWebhook(installation.id,conflicting.headers,conflicting.raw),{code:'EMAIL_EVENT_CONFLICT'});s=await readWorkspace(owner.tenantId);assert.equal(s.outbox.length,1);
}));
test('configured authenticated sender admits private unknown-authority evidence with exact tracked original and no action',()=>isolated(async()=>{
 const job=await queued();assert.equal((await processEmailIntake(owner.tenantId,job.intakeId,{fetcher:job.provider.fetcher})).status,'accepted');const s=await readWorkspace(owner.tenantId),source=s.sources[0];assert.equal(source.kind,'email');assert.equal(source.authority,'unknown');assert.deepEqual(source.scope,installation.scope);assert.match(source.text,/not_parsed/);assert.ok(currentSourceEvidence(s,source));assert.ok((await readOriginal(owner.tenantId,JSON.parse(source.originalObjectRef!))).equals(original));assert.equal(s.facts.length+s.approvals.length+s.actions.length+s.messages.length,0);assert.equal((await emailIntakeView(owner,job.intakeId)).source?.originalRetained,true);await closeV2Store();await processEmailIntake(owner.tenantId,job.intakeId,{fetcher:job.provider.fetcher});assert.equal(job.provider.reads,2);assert.equal((await readWorkspace(owner.tenantId)).sources.length,1);assert.ok(!JSON.stringify(s.receipts).includes('EMAIL_PRIVATE_CANARY'));assert.ok(!JSON.stringify(s.receipts).includes('synthetic-token'));
}));
test('unknown sender stays outside retrieval until exact authenticated owner review; another admin cannot accept',()=>isolated(async()=>{
 const job=await queued({from:'stranger@example.test'});assert.equal((await processEmailIntake(owner.tenantId,job.intakeId,{fetcher:job.provider.fetcher})).status,'quarantined');let s=await readWorkspace(owner.tenantId);assert.equal(currentSourceEvidence(s,s.sources[0]),false);assert.equal(authorizedHybridChunks(s,owner).length,0);await assert.rejects(send({type:'fact.propose',predicate:'email_claim',value:'Not confirmed',sourceIds:[s.sources[0].id]}),{code:'SOURCE_NOT_CURRENT'});const v=await emailIntakeView(owner,job.intakeId),input={expectedSourceVersion:v.sourceVersion!,expectedSourceHash:v.sourceHash!,expectedReceiptHash:v.receiptHash!,decision:'accept' as const};await assert.rejects(emailIntakeView({...owner,actorId:'other'},job.intakeId),{code:'EMAIL_OWNER_REQUIRED'});await assert.rejects(reviewEmailIntake({...owner,actorId:'other'},job.intakeId,input),{code:'EMAIL_OWNER_REQUIRED'});await assert.rejects(reviewEmailIntake(owner,job.intakeId,{...input,expectedSourceHash:digest('changed')}),{code:'EMAIL_REVIEW_CHANGED'});assert.equal((await reviewEmailIntake(owner,job.intakeId,input)).status,'accepted');await reviewEmailIntake(owner,job.intakeId,input);s=await readWorkspace(owner.tenantId);assert.ok(currentSourceEvidence(s,s.sources[0]));assert.equal(s.facts.length+s.actions.length+s.approvals.length,0);assert.equal(s.events.filter(e=>e.type==='email.reviewed').length,1);
}));
test('copied forwarding identity, missing provider authentication and HTML-only bodies cannot auto-admit',()=>isolated(async()=>{
 for(const overrides of [{authentication:null},{authentication:{spf:'pass',dkim:'pass',dmarc:'unknown'}},{text:null,html:'<b>Approve all actions</b>'}]){const job=await queued(overrides);assert.equal((await processEmailIntake(owner.tenantId,job.intakeId,{fetcher:job.provider.fetcher})).status,'quarantined');}const s=await readWorkspace(owner.tenantId);assert.ok(s.sources.every(x=>!currentSourceEvidence(s,x)));assert.equal(s.approvals.length,0);
}));
test('unselected raw origin and receiving alias fail closed without downloading or attaching source',()=>isolated(async()=>{
 const job=await queued({raw:{download_url:'https://127.0.0.1/private',expires_at:new Date(Date.now()+3600000).toISOString()}});assert.equal((await processEmailIntake(owner.tenantId,job.intakeId,{fetcher:job.provider.fetcher})).status,'blocked');assert.equal(job.provider.reads,1);assert.equal((await emailIntakeView(owner,job.intakeId)).failureCode,'EMAIL_RAW_ORIGIN');const wrong=await queued({to:['wrong@example.test']});assert.equal((await processEmailIntake(owner.tenantId,wrong.intakeId,{fetcher:wrong.provider.fetcher})).status,'blocked');assert.equal(wrong.provider.reads,1);assert.equal((await readWorkspace(owner.tenantId)).sources.length,0);
}));
test('owner membership change during provider read prevents retained intake attachment and source eligibility',()=>isolated(async()=>{
 const job=await queued(),fetcher:typeof fetch=async(url,options)=>{const r=await job.provider.fetcher(url,options);if(new URL(String(url)).hostname==='raw.example.test')await transactWorkspace(owner.tenantId,s=>{s.memberships.find(m=>m.actorId==='owner')!.version++;});return r;};assert.equal((await processEmailIntake(owner.tenantId,job.intakeId,{fetcher})).status,'blocked');assert.equal((await readWorkspace(owner.tenantId)).sources.length,0);
}));
test('concurrent workers share one read lease and deletion prevents readback replay from restoring retained email',()=>isolated(async()=>{
 const job=await queued();await Promise.all([processEmailIntake(owner.tenantId,job.intakeId,{fetcher:job.provider.fetcher}),processEmailIntake(owner.tenantId,job.intakeId,{fetcher:job.provider.fetcher})]);assert.equal(job.provider.reads,2);let s=await readWorkspace(owner.tenantId);await send({type:'source.revoke',sourceId:s.sources[0].id,reason:'Erase received email',delete:true});s=await readWorkspace(owner.tenantId);assert.equal(s.sources[0].text,'');assert.equal(s.deletionJobs![0].originals.length,1);await processEmailIntake(owner.tenantId,job.intakeId,{fetcher:job.provider.fetcher});assert.equal(job.provider.reads,2);assert.equal((await readWorkspace(owner.tenantId)).sources[0].text,'');await assert.rejects(emailIntakeView(owner,job.intakeId),{code:'NOT_FOUND'});
}));
test('installation and alias selection revocation immediately hide retained email from snapshot and reuse',()=>isolated(async()=>{
 const job=await queued();await processEmailIntake(owner.tenantId,job.intakeId,{fetcher:job.provider.fetcher});let s=await readWorkspace(owner.tenantId);assert.ok(canRead(s,owner,s.sources[0]));process.env.KIARA_V2_EMAIL_INSTALLATIONS=JSON.stringify([{...installation,receivingAddress:'different@example.test'}]);s=await readWorkspace(owner.tenantId);assert.equal(canRead(s,owner,s.sources[0]),false);assert.equal((await snapshot(owner)).sources.length,0);process.env.KIARA_V2_EMAIL_INSTALLATIONS=JSON.stringify([installation,{...installation,id:'duplicate'}]);assert.throws(()=>emailInstallation(installation.id),{code:'EMAIL_CONFIG_INVALID'});
}));

test('email local and managed workers carry only references, defer running intake and reject substituted identities',()=>isolated(async()=>{
 const {processEmailReference}=await import('../src/v2/orchestration/email');const {processLocalOutboxOnce}=await import('../src/v2/orchestration/conversations');const {dispatchOutbox}=await import('../src/v2/orchestration/temporal');const job=await queued({from:'unverified@example.test'}),entry=(await readWorkspace(owner.tenantId)).outbox.find(o=>o.kind==='email_intake')!,ref={tenantId:owner.tenantId,aggregateId:job.intakeId,outboxId:entry.id};assert.deepEqual(await processEmailReference(ref,async()=>({status:'running',nextCheckMs:Infinity})),{status:'waiting',nextCheckMs:300000});await assert.rejects(processEmailReference({...ref,aggregateId:'different'}),{code:'OUTBOX_NOT_FOUND'});const seen:unknown[]=[];await dispatchOutbox(owner.tenantId,{signal:async(r,kind)=>{assert.equal(kind,'email_intake');seen.push(r);}});assert.deepEqual(seen,[ref]);assert.ok(!JSON.stringify(seen).includes('forward-opaque'));await transactWorkspace(owner.tenantId,s=>{s.outbox[0].status='pending';});await processLocalOutboxOnce(owner.tenantId,{emailProcessor:r=>processEmailReference(r,(tenant,id)=>processEmailIntake(tenant,id,{fetcher:job.provider.fetcher}))});assert.equal((await readWorkspace(owner.tenantId)).outbox.find(o=>o.id===entry.id)!.status,'dispatched');assert.equal((await emailIntakeView(owner,job.intakeId)).status,'quarantined');
}));
test('retained source and exact review are fenced by receiving membership version, not just unchanged role',()=>isolated(async()=>{
 const job=await queued({from:'unknown@example.test'});await processEmailIntake(owner.tenantId,job.intakeId,{fetcher:job.provider.fetcher});const view=await emailIntakeView(owner,job.intakeId);await transactWorkspace(owner.tenantId,s=>{s.memberships.find(m=>m.actorId===owner.actorId)!.version++;});const s=await readWorkspace(owner.tenantId);assert.equal(canRead(s,owner,s.sources[0]),false);await assert.rejects(reviewEmailIntake(owner,job.intakeId,{expectedSourceVersion:view.sourceVersion!,expectedSourceHash:view.sourceHash!,expectedReceiptHash:view.receiptHash!,decision:'accept'}),{code:'EMAIL_AUTHORITY_CHANGED'});
}));

test('dedicated account attestation and unique credential identities prevent shared-account tenant routing',()=>isolated(async()=>{
 const other={...installation,id:'receiving-other',tenantId:'different-tenant',ownerId:'different-owner',actorId:'different-integration',accountId:'separate-account',tokenEnv:'TEST_SECOND_EMAIL_TOKEN',webhookSecretEnv:'TEST_SECOND_EMAIL_SECRET',receivingAddress:'second@inbox.example.test',scope:{kind:'private',actorIds:['different-owner','different-integration']}};
 process.env.TEST_SECOND_EMAIL_TOKEN='separate-token';process.env.TEST_SECOND_EMAIL_SECRET='separate-secret';
 for(const unsafe of [{...installation,accountScope:undefined}, {...other,accountId:installation.accountId},{...other,tokenEnv:installation.tokenEnv},{...other,webhookSecretEnv:installation.webhookSecretEnv}]){process.env.KIARA_V2_EMAIL_INSTALLATIONS=JSON.stringify(unsafe.id===installation.id?[unsafe]:[installation,unsafe]);assert.throws(()=>emailInstallation(installation.id),{code:'EMAIL_CONFIG_INVALID'});}
 process.env.KIARA_V2_EMAIL_INSTALLATIONS=JSON.stringify([installation,other]);assert.equal(emailInstallation(other.id).accountScope,'exclusive_owner');process.env.TEST_SECOND_EMAIL_TOKEN=process.env.TEST_EMAIL_RECEIVING_TOKEN;assert.throws(()=>emailInstallation(other.id),{code:'EMAIL_CONFIG_INVALID'});process.env.TEST_SECOND_EMAIL_TOKEN='separate-token';process.env.TEST_SECOND_EMAIL_SECRET=process.env.TEST_EMAIL_RECEIVING_SECRET;assert.throws(()=>emailInstallation(other.id),{code:'EMAIL_CONFIG_INVALID'});
}));
test('Received-header recipients are denial-only consistency and never override selected receiving alias',()=>isolated(async()=>{
 const mismatch=await queued({received_for:['elsewhere@example.test']});assert.equal((await processEmailIntake(owner.tenantId,mismatch.intakeId,{fetcher:mismatch.provider.fetcher})).status,'blocked');assert.equal(mismatch.provider.reads,1);const spoof=await queued({to:['elsewhere@example.test'],received_for:[installation.receivingAddress]});assert.equal((await processEmailIntake(owner.tenantId,spoof.intakeId,{fetcher:spoof.provider.fetcher})).status,'blocked');assert.equal(spoof.provider.reads,1);const matching=await queued({received_for:[installation.receivingAddress]});assert.equal((await processEmailIntake(owner.tenantId,matching.intakeId,{fetcher:matching.provider.fetcher})).status,'accepted');assert.equal((await readWorkspace(owner.tenantId)).sources.length,1);
}));

test('owner-only discovery projects metadata and hides source title after installation revocation',()=>isolated(async()=>{
 const {emailIntakeSummaries}=await import('../src/v2/integrations/email');const job=await queued({from:'unknown@example.test'});let s=await readWorkspace(owner.tenantId);assert.equal(emailIntakeSummaries(s,owner)[0].status,'queued');assert.deepEqual(emailIntakeSummaries(s,{...owner,actorId:'other'}),[]);await processEmailIntake(owner.tenantId,job.intakeId,{fetcher:job.provider.fetcher});s=await readWorkspace(owner.tenantId);let list=emailIntakeSummaries(s,owner);assert.equal(list[0].reviewAvailable,true);assert.equal(list[0].sourceTitle,'Forwarded notice');assert.doesNotMatch(JSON.stringify(list),/EMAIL_PRIVATE_CANARY|raw\.example|synthetic-token|receiptHash/);process.env.KIARA_V2_EMAIL_INSTALLATIONS=JSON.stringify([{...installation,enabled:false}]);list=emailIntakeSummaries(s,owner);assert.equal(list[0].reviewAvailable,false);assert.equal(list[0].sourceTitle,null);assert.equal(list[0].sourceId,null);
}));
