import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyWorkspace,digest} from '../src/v2/store';
import {applySourceDeletion,redactHistoricalWorkspace} from '../src/v2/retention';
import {applyValueCommand,valueView} from '../src/v2/value';
import type {ActorContext,RecordBase,Source,Message,Conversation} from '../src/v2/contracts';
import type {StrategyFeedback,StrategyCandidate} from '../src/v2/strategies';
import {sourceDependencyHash} from '../src/v2/tasks';
const a:ActorContext={tenantId:'engagement-retention',actorId:'owner',mode:'local_demo',expiresAt:Date.now()+60000};
const base=(id:string,sources:string[]=[]):RecordBase=>({id,tenantId:a.tenantId,version:1,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),scope:{kind:'private',actorIds:['owner']},provenance:{actorId:'owner',sourceIds:sources,description:'Synthetic review fixture'}});

test('deletion erases useful-output and strategy payloads without replacing the original first-useful receipt',()=>{
 const s=emptyWorkspace(a.tenantId);s.memberships=[{actorId:'owner',roles:['member','business_owner','admin'],version:1,expiresAt:null,revokedAt:null,matterIds:null,entityIds:null}];
 const source:Source={...base('source'),title:'PRIVATE-PAYLOAD evidence',kind:'manual',externalId:null,externalRevision:null,text:'PRIVATE-PAYLOAD terms',contentHash:digest('PRIVATE-PAYLOAD terms'),url:null,status:'active',aclVersion:1,observedAt:new Date().toISOString(),effectiveAt:null,authority:'unknown',originalObjectRef:null};s.sources.push(source);
 const c:Conversation={...base('conversation',['source']),title:'PRIVATE-PAYLOAD discussion',entityId:s.entityId,reuse:'conversation_only',matterId:null,scenarioId:null};s.conversations.push(c);
 const m:Message={...base('message',['source']),conversationId:c.id,role:'assistant',channel:'web',text:'PRIVATE-PAYLOAD response',intent:'question',artifactIds:[],citations:[],generation:'bounded_local',retention:'workspace_policy',voiceConfirmed:true};s.messages.push(m);
 const goalId=String(applyValueCommand(s,a,{type:'value.goal.define',title:'PRIVATE-PAYLOAD goal',successCriteria:'PRIVATE-PAYLOAD criteria',conversationId:c.id}).goalId),goal=s.valueGoals!.find(x=>x.id===goalId)!,out=valueView(s,a).outputs[0];
 const receiptId=String(applyValueCommand(s,a,{type:'value.output.assess',goalId,expectedGoalVersion:goal.version,outputKind:'answer',outputId:m.id,expectedOutputVersion:m.version,outputHash:out.hash,disposition:'useful',reason:'PRIVATE-PAYLOAD explanation'}).receiptId);
 applyValueCommand(s,a,{type:'value.goal.assess',goalId,expectedRecordVersion:goal.version,disposition:'reported_achieved',receiptId,reason:'PRIVATE-PAYLOAD result'});
 const feedback:StrategyFeedback={...base('feedback',['source']),ownerId:'owner',subjectKind:'message',subjectId:m.id,subjectVersion:1,subjectHash:digest(m),category:'retrieval_miss',detail:'PRIVATE-PAYLOAD feedback',status:'active',original:{input:{kind:'ranking',query:'PRIVATE-PAYLOAD query',items:[{id:'synthetic-document',title:'PRIVATE-PAYLOAD title',body:'PRIVATE-PAYLOAD body'}]},expected:'synthetic-document'},withdrawalReason:null};s.strategyFeedback=[feedback];
 const candidate:StrategyCandidate={...base('candidate',['source']),key:'exact_clause_reference',feedbackId:feedback.id,feedbackHash:digest(feedback),title:'PRIVATE-PAYLOAD strategy',rationale:'PRIVATE-PAYLOAD rationale',authorId:'owner',status:'promoted',evaluation:null,evaluationHash:null,evaluatorId:null,evaluatorMembershipVersion:null,ownerId:null,ownerMembershipVersion:null,validUntil:null,shadowIds:[],promotionShadowHash:null,effectiveVersion:1,affectedRecordIds:[],rollbackReason:'PRIVATE-PAYLOAD reason'};s.strategyCandidates=[candidate];
 s.notificationDeliveries=[{...base('notification',['source']),ownerId:'owner',enrollmentId:'enrollment',grantHash:'hash',membershipVersion:1,kind:'required',window:'condition',itemKeys:['hashed-condition'],status:'prepared',providerReceipt:null,reason:null,leaseToken:null,leaseUntil:null,dispatchToken:null,dispatchedAt:null,completedAt:null}];
 s.matters.push({...base('matter',['source']),title:'PRIVATE-PAYLOAD work',objective:'PRIVATE-PAYLOAD objective',entityId:s.entityId,state:'business_review',ownerId:a.actorId,conversationIds:[],scenarioId:null,eventIds:[],sourceIds:[source.id],factIds:[],documentIds:[],proposalId:null,tasks:[{id:'task',title:'PRIVATE-PAYLOAD negotiation',purpose:'work',kind:'business',ownerId:a.actorId,status:'done',dueAt:null,deadlineType:'undated',evidenceIds:[source.id],completion:{kind:'human_attestation',actorId:a.actorId,membershipVersion:1,at:new Date().toISOString(),note:'PRIVATE-PAYLOAD completed terms',sourceIds:[source.id],sourceVersions:{[source.id]:1},proofHash:sourceDependencyHash(s,[source.id])}}],blockers:[],outcome:null,closedAt:null,ruleVersion:1});
 const historical=structuredClone(s),baseline=structuredClone(s.valueSessions![0]),job=applySourceDeletion(s,a,source.id);
 assert.doesNotMatch(JSON.stringify(s),/PRIVATE-PAYLOAD/);assert.equal(s.valueSessions![0].observedStartedAt,baseline.observedStartedAt);assert.equal(s.valueSessions![0].firstUsefulReceiptId,receiptId);assert.equal(valueView(s,a).report.firstUsefulState,'unavailable');assert.equal(s.strategyCandidates![0].status,'rolled_back');assert.equal(s.notificationDeliveries![0].status,'canceled');
 assert.equal(s.matters[0].tasks[0].completion,undefined);redactHistoricalWorkspace(historical,job);assert.doesNotMatch(JSON.stringify(historical),/PRIVATE-PAYLOAD/);assert.equal(historical.valueSessions![0].firstUsefulReceiptId,receiptId);assert.equal(historical.matters[0].tasks[0].completion,undefined);
});
