import test,{beforeEach,afterEach} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {getEncoding} from 'js-tiktoken';
import {command,snapshot} from '../src/v2/service';
import {processConversationRun,type ConversationProvider} from '../src/v2/ai';
import {closeV2Store,digest,readWorkspace,transactWorkspace} from '../src/v2/store';
import {embedAuthorized,embeddingTokens,EMBEDDING_POLICY,reconcileEmbedding,type EmbeddingProvider} from '../src/v2/embeddings';
import {authorizedHybridChunks,hybridConfig,hybridPipelines,reciprocalRankFusion,retrieveHybridEvidence,syncHybridIndex,purgeHybridRecords,type HybridAdapter,type HybridChunk} from '../src/v2/hybrid';
import {globalSpendStatus,reserveGlobalSpend} from '../src/server/global-spend';
import type {ActorContext,WorkspaceCommand} from '../src/v2/contracts';
const keys=['KIARA_V2_DATA_DIR','KIARA_GLOBAL_BUDGET_DIR','MONGODB_URI','VERCEL','KIARA_V2_AI_MODE','OPENAI_API_KEY','KIARA_OPENAI_BUDGET_USD','KIARA_MODEL','KIARA_REVIEW_MODEL','KIARA_REASONING_EFFORT','KIARA_V2_RETRIEVAL_MODE','KIARA_V2_ATLAS_URI','KIARA_V2_ATLAS_SEARCH_INDEX','KIARA_V2_ATLAS_VECTOR_INDEX','KIARA_V2_STORE_MODE'];
const old=Object.fromEntries(keys.map(k=>[k,process.env[k]]));let dir:string;
beforeEach(async()=>{dir=await mkdtemp(join(tmpdir(),'kiara-hybrid-'));for(const key of keys)delete process.env[key];Object.assign(process.env,{KIARA_V2_DATA_DIR:join(dir,'workspaces'),KIARA_GLOBAL_BUDGET_DIR:join(dir,'budget'),KIARA_V2_AI_MODE:'local',KIARA_V2_RETRIEVAL_MODE:'atlas',KIARA_V2_ATLAS_URI:'mongodb://injected-test-only',KIARA_V2_ATLAS_SEARCH_INDEX:'keyword_v1',KIARA_V2_ATLAS_VECTOR_INDEX:'vector_v1',OPENAI_API_KEY:'injected-test-only',KIARA_OPENAI_BUDGET_USD:'1',KIARA_MODEL:'gpt-6-sol',KIARA_REVIEW_MODEL:'gpt-6-sol'});});
afterEach(async()=>{await closeV2Store();for(const k of keys){if(old[k]===undefined)delete process.env[k];else process.env[k]=old[k];}await rm(dir,{recursive:true,force:true});});
const actor=(id='alice'):ActorContext=>({tenantId:'hybrid-tenant',actorId:id,mode:'local_demo',expiresAt:Date.now()+3600000,bootstrapRoles:['member','business_owner','fact_owner','admin']});
async function send(a:ActorContext,c:WorkspaceCommand){return command(a,{idempotencyKey:randomUUID(),expectedVersion:(await snapshot(a)).version,command:c});}
function provider(hook?:()=>Promise<void>){let calls=0;const requests:number[][]=[];const adapter:EmbeddingProvider={create:async r=>{calls++;requests.push(r.input);await hook?.();return {model:r.model,data:[{index:0,embedding:Array(1536).fill(0.01)}],usage:{prompt_tokens:r.input.length,total_tokens:r.input.length},_request_id:'mock-embedding-'+calls};}};return {adapter,requests,get calls(){return calls;}};}
function index(){const rows=new Map<string,HybridChunk>();let searchCalls=0;const adapter:HybridAdapter={upsert:async chunk=>{rows.set(chunk.id,chunk);},present:async(tenant,ids)=>ids.filter(id=>rows.get(id)?.tenantId===tenant),ids:async tenant=>[...rows.values()].filter(x=>x.tenantId===tenant).map(x=>x.id),remove:async(tenant,ids)=>{for(const id of ids)if(rows.get(id)?.tenantId===tenant)rows.delete(id);},search:async input=>{searchCalls++;return {keywordIds:input.chunkIds,vectorIds:[...input.chunkIds].reverse()};}};return {adapter,rows,get calls(){return searchCalls;}};}
async function question(){const a=actor(),d=await send(a,{type:'document.add',title:'Acme notice agreement',body:'A new processor requires 30 days advance written notice. Synthetic data is excluded.',authority:'executed',kind:'agreement'}),message=await send(a,{type:'message.send',text:'Explain Acme notice'});return {a,d,c:String(message.result.conversationId),m:message.snapshot.messages.filter(x=>x.role==='user').at(-1)!.id};}
const errorCode=(expected:string)=>(e:unknown)=>!!e&&typeof e==='object'&&'code' in e&&e.code===expected;

test('exact embedding tokens preserve multilingual and adversarial special-token text',()=>{const text='Hello 世界 <|endoftext|> \n🔒';const tokens=embeddingTokens(text);assert.equal(getEncoding('cl100k_base').decode(tokens),text);assert.ok(tokens.every(Number.isInteger));});
test('embedding reserves exact tokens under the shared cap and durable replay makes no provider call',async()=>{const a=actor();await snapshot(a);const f=provider(),authorize=()=>{},key='test-owner';const first=await embedAuthorized(a,key,'approved authorized context',digest('authority'),authorize,{provider:f.adapter});await closeV2Store();assert.deepEqual(await embedAuthorized(a,key,'approved authorized context',digest('authority'),authorize,{provider:f.adapter}),first);assert.equal(f.calls,1);const ledger=await globalSpendStatus();assert.equal(ledger.request_count,1);assert.equal(ledger.unknown_charges,0);assert.equal(ledger.reserved_usd,0);assert.ok(ledger.spent_usd>0);assert.equal(ledger.budget_usd,1);});
test('embedding budget exhaustion prevents dispatch; unknown charges never invoke again',async()=>{const a=actor();await snapshot(a);process.env.KIARA_OPENAI_BUDGET_USD='0.0000001';const f=provider();await assert.rejects(()=>embedAuthorized(a,'budget','Many tokens '.repeat(100),digest('x'),()=>{},{provider:f.adapter}),errorCode('GLOBAL_BUDGET_EXHAUSTED'));assert.equal(f.calls,0);process.env.KIARA_OPENAI_BUDGET_USD='1';const broken:EmbeddingProvider={create:async()=>{throw new Error('network reset after request');}};await assert.rejects(()=>embedAuthorized(a,'uncertain','Some text',digest('x'),()=>{},{provider:broken}));assert.equal((await globalSpendStatus()).unknown_charges,1);await assert.rejects(()=>embedAuthorized(a,'uncertain','Some text',digest('x'),()=>{},{provider:f.adapter}),errorCode('EMBEDDING_CHARGE_UNKNOWN'));assert.equal(f.calls,0);});
test('revocation during embedding wait cannot retain or attach the returned vector',async()=>{const {a,d}=await question();const authorize=(s:Awaited<ReturnType<typeof readWorkspace>>)=>{if(s.sources.find(x=>x.id===d.result.sourceId)?.status!=='active')throw Object.assign(new Error('revoked'),{code:'SOURCE_REVOKED'});};const f=provider(async()=>{await send(a,{type:'source.revoke',sourceId:String(d.result.sourceId),reason:'Removed during embedding'});});await assert.rejects(()=>embedAuthorized(a,'revoked','Source excerpt',digest('source'),authorize,{provider:f.adapter}),errorCode('SOURCE_REVOKED'));const job=(await readWorkspace(a.tenantId)).receipts['embedding:revoked'].result.job as {vector:unknown};assert.equal(job.vector,null);assert.equal((await globalSpendStatus()).unknown_charges,0);});
test('expired dispatched embedding recovery is durable without a second provider invocation',async()=>{const a=actor();await snapshot(a);const id=randomUUID();await reserveGlobalSpend(id,0.00001);await transactWorkspace(a.tenantId,s=>{s.receipts['embedding:interrupted']={hash:'fixture',result:{job:{id,key:'interrupted',status:'dispatched',leaseUntil:Date.now()-1,recoveryPending:false}}};});await closeV2Store();await reconcileEmbedding(a.tenantId,'interrupted');const job=(await readWorkspace(a.tenantId)).receipts['embedding:interrupted'].result.job as {status:string;recoveryPending:boolean};assert.equal(job.status,'unknown');assert.equal(job.recoveryPending,false);assert.equal((await globalSpendStatus()).unknown_charges,1);});
test('both Atlas branches prefilter tenant, entity and immutable authorized IDs and return no indexed text',()=>{const config=hybridConfig(),p=hybridPipelines({config,tenantId:'tenant-a',entityId:'entity-a',chunkIds:['current-version-id'],question:'notice',vector:[0.1]});const keyword=JSON.stringify(p.keyword),semantic=JSON.stringify(p.semantic);for(const text of [keyword,semantic]){assert.match(text,/tenant-a/);assert.match(text,/entity-a/);assert.match(text,/current-version-id/);assert.match(text,/embeddingPolicyHash/);assert.match(text,/"\$project":\{"_id":0,"id":1\}/);}assert.match(keyword,/"filter"/);assert.match(semantic,/"filter"/);assert.equal(reciprocalRankFusion([['a','b','a'],['b','c']])[0].id,'b');assert.equal(reciprocalRankFusion([['a'],['a']])[0].score,2/61);});
test('scoped sync and hybrid fusion hydrate actual retained quotes; replay reuses index embeddings',async()=>{const {a,d,c,m}=await question(),f=provider(),idx=index();const result=await syncHybridIndex(a,[String(d.result.documentId)],{adapter:idx.adapter,provider:f.adapter});assert.equal(result.indexed,1);await syncHybridIndex(a,[String(d.result.documentId)],{adapter:idx.adapter,provider:f.adapter});assert.equal(f.calls,1);const packet=await retrieveHybridEvidence(a,c,m,'run-1',{adapter:idx.adapter,provider:f.adapter});assert.equal(packet.version,'v2-atlas-hybrid-1');assert.match(packet.evidence[0].quote,/30 days/);assert.equal(idx.calls,1);assert.equal(f.calls,2);assert.equal(packet.evidence[0].sourceId,d.result.sourceId);assert.match(packet.limitations[0],/reciprocal rank fusion/);});
test('private and expired evidence cannot enter index query allowlist; stale indexes fail explicitly',async()=>{const {a,c,m}=await question(),b=actor('bob');await snapshot(b);await send(a,{type:'document.add',title:'Private secret',body:'Secret price 987654',authority:'draft',scope:{kind:'private',actorIds:['alice']}});const state=await readWorkspace(a.tenantId);assert.ok(!authorizedHybridChunks(state,b).some(x=>x.text.includes('987654')));const idx=index(),f=provider();await assert.rejects(()=>retrieveHybridEvidence(a,c,m,'unindexed',{adapter:idx.adapter,provider:f.adapter}),errorCode('HYBRID_INDEX_STALE'));assert.equal(f.calls,0);assert.equal(idx.calls,0);delete process.env.KIARA_V2_ATLAS_VECTOR_INDEX;assert.throws(()=>hybridConfig(),errorCode('HYBRID_NOT_CONFIGURED'));});
test('revocation during search and malicious cross-scope search IDs never reach model context',async()=>{const {a,d,c,m}=await question(),idx=index(),f=provider();await syncHybridIndex(a,[String(d.result.documentId)],{adapter:idx.adapter,provider:f.adapter});idx.adapter.search=async()=>({keywordIds:['foreign-private-id'],vectorIds:[]});await assert.rejects(()=>retrieveHybridEvidence(a,c,m,'bad-index',{adapter:idx.adapter,provider:f.adapter}),errorCode('HYBRID_RESULT_SCOPE'));idx.adapter.search=async input=>{await send(a,{type:'source.revoke',sourceId:String(d.result.sourceId),reason:'Source revoked while index search runs'});return {keywordIds:input.chunkIds,vectorIds:[]};};await assert.rejects(()=>retrieveHybridEvidence(a,c,m,'revoked-search',{adapter:idx.adapter,provider:f.adapter}),errorCode('EVIDENCE_CHANGED'));});
test('conversation worker uses accepted run identity for hybrid query then grounded answer and review',async()=>{const {a,d}=await question(),idx=index(),f=provider();await syncHybridIndex(a,[String(d.result.documentId)],{adapter:idx.adapter,provider:f.adapter});process.env.KIARA_V2_AI_MODE='openai';const r=await send(a,{type:'message.send',text:'Explain Acme notice'});let calls=0;const model:ConversationProvider={count:async()=>1000,create:async request=>{calls++;const data=JSON.parse(String(request.input)),output=data.answer?{safe:true,checks:[{paragraphId:'p1',supported:true,reason:'Exact clause including condition.'}]}:{paragraphs:[{id:'p1',kind:'grounded',text:'The agreement requires 30 days notice for a new processor.',citationIds:[data.evidence[0].id]}]};return {id:'response-'+calls,model:String(request.model),status:'completed',output_text:JSON.stringify(output),usage:{input_tokens:100,output_tokens:40,total_tokens:140,input_tokens_details:{cached_tokens:0,cache_write_tokens:0},output_tokens_details:{reasoning_tokens:0}}};}};const run=await processConversationRun(a.tenantId,String(r.result.runId),{provider:model,embeddingProvider:f.adapter,hybridAdapter:idx.adapter});assert.equal(run.status,'complete',JSON.stringify(run));assert.equal(calls,2);assert.equal((await snapshot(a)).messages.at(-1)!.generation,'model');assert.equal((await globalSpendStatus()).request_count,4);});

test('expired parent lease during index admission cannot dispatch a query embedding',async()=>{const {a,d}=await question(),idx=index(),f=provider();await syncHybridIndex(a,[String(d.result.documentId)],{adapter:idx.adapter,provider:f.adapter});process.env.KIARA_V2_AI_MODE='openai';const message=await send(a,{type:'message.send',text:'Explain Acme notice'}),runId=String(message.result.runId);const present=idx.adapter.present;idx.adapter.present=async(tenant,ids)=>{await transactWorkspace(tenant,s=>{const run=s.receipts['conversation-run:'+runId].result.run as {leaseUntil:number};run.leaseUntil=Date.now()-1;});await processConversationRun(tenant,runId,{embeddingProvider:f.adapter,hybridAdapter:idx.adapter});return present(tenant,ids);};let modelCalls=0;const model:ConversationProvider={count:async()=>{modelCalls++;return 100;},create:async()=>{throw new Error('Must never invoke');}};const result=await processConversationRun(a.tenantId,runId,{provider:model,embeddingProvider:f.adapter,hybridAdapter:idx.adapter});assert.equal(result.status,'blocked');assert.equal(f.calls,1);assert.equal(modelCalls,0);});

test('an old prepared embedding cannot dispatch or mutate a successor admission after recovery',async()=>{const a=actor();await snapshot(a);const f=provider();let releaseA!:()=>void,releaseB!:()=>void,readyA!:()=>void,readyB!:()=>void;const gateA=new Promise<void>(r=>releaseA=r),gateB=new Promise<void>(r=>releaseB=r),startedA=new Promise<void>(r=>readyA=r),startedB=new Promise<void>(r=>readyB=r);const first=embedAuthorized(a,'same-owner','Authorized input',digest('same-authority'),()=>{},{provider:f.adapter,afterReservation:async()=>{readyA();await gateA;}});await startedA;await transactWorkspace(a.tenantId,s=>{const job=s.receipts['embedding:same-owner'].result.job as {leaseUntil:number};job.leaseUntil=Date.now()-1;});await reconcileEmbedding(a.tenantId,'same-owner');const second=embedAuthorized(a,'same-owner','Authorized input',digest('same-authority'),()=>{},{provider:f.adapter,afterReservation:async()=>{readyB();await gateB;}});await startedB;const before=(await readWorkspace(a.tenantId)).receipts['embedding:same-owner'].result.job as {id:string;status:string};releaseA();await assert.rejects(()=>first,errorCode('EMBEDDING_LEASE_EXPIRED'));const after=(await readWorkspace(a.tenantId)).receipts['embedding:same-owner'].result.job as {id:string;status:string};assert.equal(after.id,before.id);assert.equal(after.status,'prepared');assert.equal(f.calls,0);releaseB();assert.equal((await second).length,1536);assert.equal(f.calls,1);assert.equal((await globalSpendStatus()).unknown_charges,0);});

test('a permanently fenced record cannot be reinserted by an index writer paused across deletion',async()=>{const {a,d}=await question(),idx=index(),f=provider();const fenced=new Set<string>();const upsert=idx.adapter.upsert;let release!:()=>void,ready!:()=>void;const gate=new Promise<void>(r=>release=r),started=new Promise<void>(r=>ready=r);idx.adapter.upsert=async(chunk,vector)=>{ready();await gate;if(fenced.has(chunk.recordId))throw Object.assign(new Error('Deleted index identity'),{code:'INDEX_RECORD_DELETED'});await upsert(chunk,vector);};idx.adapter.removeRecords=async(tenant,recordIds)=>{recordIds.forEach(id=>fenced.add(id));for(const [id,row] of idx.rows)if(row.tenantId===tenant&&recordIds.includes(row.recordId))idx.rows.delete(id);};const sync=syncHybridIndex(a,[String(d.result.documentId)],{adapter:idx.adapter,provider:f.adapter});await started;await send(a,{type:'source.revoke',sourceId:String(d.result.sourceId),delete:true,reason:'Delete source while indexing is in progress'});const deleted=(await readWorkspace(a.tenantId)).deletionJobs![0];const ids=deleted.records.map(x=>x.id);assert.equal((await purgeHybridRecords(a.tenantId,deleted.id,ids,{adapter:idx.adapter})).status,'complete');release();await assert.rejects(()=>sync,errorCode('INDEX_RECORD_DELETED'));assert.equal(idx.rows.size,0);assert.equal((await purgeHybridRecords(a.tenantId,deleted.id,ids,{adapter:idx.adapter})).replayed,true);});

test('late embedding receipt survives unknown-charge recovery without restoring vector or clearing uncertainty',async()=>{const a=actor();await snapshot(a);let release!:()=>void,entered!:()=>void;const ready=new Promise<void>(r=>entered=r),gate=new Promise<void>(r=>release=r);let calls=0;const adapter:EmbeddingProvider={create:async req=>{calls++;entered();await gate;return {model:EMBEDDING_POLICY.model,_request_id:'late-embedding-provider-receipt',data:[{index:0,embedding:Array(1536).fill(0.1)}],usage:{prompt_tokens:req.input.length,total_tokens:req.input.length}};}};const attempt=embedAuthorized(a,'late-receipt','A bounded authorized query',digest('late-authority'),()=>{},{provider:adapter});await ready;await transactWorkspace(a.tenantId,s=>{const job=s.receipts['embedding:late-receipt'].result.job as {leaseUntil:number};job.leaseUntil=Date.now()-1;});await reconcileEmbedding(a.tenantId,'late-receipt');assert.equal((await globalSpendStatus()).unknown_charges,1);release();await assert.rejects(attempt,errorCode('GLOBAL_CHARGE_UNKNOWN'));const j=(await readWorkspace(a.tenantId)).receipts['embedding:late-receipt'].result.job as {status:string;vector:unknown;requestId:string;responseHash:string;observedUsage:{totalTokens:number;estimatedUsd:number};recoveryPending:boolean};assert.equal(j.status,'unknown');assert.equal(j.vector,null);assert.equal(j.requestId,'late-embedding-provider-receipt');assert.ok(j.responseHash);assert.ok(j.observedUsage.totalTokens>0);assert.ok(j.observedUsage.estimatedUsd>0);assert.equal(j.recoveryPending,false);assert.equal((await globalSpendStatus()).unknown_charges,1);await assert.rejects(embedAuthorized(a,'late-receipt','A bounded authorized query',digest('late-authority'),()=>{},{provider:adapter}),errorCode('EMBEDDING_CHARGE_UNKNOWN'));assert.equal(calls,1);});
