import test,{beforeEach,afterEach} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {command,snapshot} from '../src/v2/service';
import {closeV2Store,digest,readWorkspace,transactWorkspace} from '../src/v2/store';
import {processIndexJob,previewIndexRecovery,requeueIndexJob,previewUnknownEmbeddingRepair,repairUnknownEmbedding} from '../src/v2/index-maintenance';
import {identityBindingKey} from '../src/v2/oidc-identities';
import {inventoryCurrent,assertProposalInventory} from '../src/v2/inventory';
import {assertExecutable} from '../src/v2/execution/authority';
import {reserveGlobalSpend,settleGlobalSpend,recoverGlobalSpend,conservativelyAccountUnknownCharge,globalSpendStatus} from '../src/server/global-spend';
import type {HybridAdapter,HybridChunk} from '../src/v2/hybrid';
import type {EmbeddingProvider} from '../src/v2/embeddings';
import {V2Error,type ActorContext,type Role,type WorkspaceCommand} from '../src/v2/contracts';
const keys=['KIARA_V2_DATA_DIR','KIARA_GLOBAL_BUDGET_DIR','MONGODB_URI','VERCEL','KIARA_V2_AI_MODE','OPENAI_API_KEY','KIARA_OPENAI_BUDGET_USD','KIARA_MODEL','KIARA_REVIEW_MODEL','KIARA_REASONING_EFFORT','KIARA_V2_RETRIEVAL_MODE','KIARA_V2_ATLAS_URI','KIARA_V2_ATLAS_SEARCH_INDEX','KIARA_V2_ATLAS_VECTOR_INDEX','KIARA_V2_STORE_MODE','KIARA_V2_INDEX_POLICY','KIARA_V2_AUTH_MODE','KIARA_OIDC_IDENTITY_SOURCE','KIARA_OIDC_ISSUER','KIARA_OIDC_IDENTITIES'];const old=Object.fromEntries(keys.map(k=>[k,process.env[k]]));let dir:string;
beforeEach(async()=>{dir=await mkdtemp(join(tmpdir(),'kiara-index-inventory-'));for(const key of keys)delete process.env[key];Object.assign(process.env,{KIARA_V2_DATA_DIR:join(dir,'workspaces'),KIARA_GLOBAL_BUDGET_DIR:join(dir,'budget'),KIARA_V2_AI_MODE:'local',KIARA_V2_RETRIEVAL_MODE:'atlas',KIARA_V2_ATLAS_URI:'mongodb://injected-test-only',KIARA_V2_ATLAS_SEARCH_INDEX:'keyword_v1',KIARA_V2_ATLAS_VECTOR_INDEX:'vector_v1',OPENAI_API_KEY:'injected-test-only',KIARA_OPENAI_BUDGET_USD:'1',KIARA_MODEL:'gpt-6-sol',KIARA_REVIEW_MODEL:'gpt-6-sol'});});
afterEach(async()=>{await closeV2Store();for(const k of keys){if(old[k]===undefined)delete process.env[k];else process.env[k]=old[k];}await rm(dir,{recursive:true,force:true});});
const roles:Role[]=['member','business_owner','fact_owner','legal_reviewer','publisher','admin'];
const actor=(id='alice',r=roles):ActorContext=>({tenantId:'index-inventory',actorId:id,mode:'local_demo',expiresAt:Date.now()+3600000,bootstrapRoles:r});
const future=(minutes=60)=>new Date(Date.now()+minutes*60000).toISOString();
async function send(a:ActorContext,c:WorkspaceCommand){return command(a,{idempotencyKey:randomUUID(),expectedVersion:(await snapshot(a)).version,command:c});}
const code=(name:string)=>(e:unknown)=>!!e&&typeof e==='object'&&'code'in e&&e.code===name;
function policy(scopeKinds=['team']){process.env.KIARA_V2_INDEX_POLICY=JSON.stringify([{tenantId:'index-inventory',enabled:true,actorIds:['alice'],scopeKinds,maxChunksPerJob:10,validUntil:future()}]);}
function provider(hook?:()=>Promise<void>){let calls=0;const value:EmbeddingProvider={create:async r=>{calls++;await hook?.();return {model:r.model,data:[{index:0,embedding:Array(1536).fill(.01)}],usage:{prompt_tokens:r.input.length,total_tokens:r.input.length},_request_id:'mock-'+calls};}};return {value,get calls(){return calls;}};}
function index(){const rows=new Map<string,HybridChunk>(),adapter:HybridAdapter={upsert:async c=>{rows.set(c.id,c);},remove:async(_t,ids)=>{ids.forEach(id=>rows.delete(id));},ids:async()=>[...rows.keys()],present:async(_t,ids)=>ids.filter(id=>rows.has(id)),search:async()=>({keywordIds:[],vectorIds:[]})};return {rows,adapter};}
const doc=(title='Agreement'):WorkspaceCommand=>({type:'document.add',title,body:'Customer notice requires 30 days. Retain applicable amendments.',authority:'executed',kind:'agreement'});
test('maintenance stays disabled by default and an explicit standing grant allows scoped member work without admin',async()=>{const a=actor('alice',['member']);await send(a,doc());assert.equal((await snapshot(a)).indexing.length,0);policy();const result=await send(a,doc('Second agreement'));assert.equal(result.snapshot.indexing.length,1);const idx=index(),f=provider(),id=result.snapshot.indexing[0].id;assert.equal((await processIndexJob(a.tenantId,id,{provider:f.value,adapter:idx.adapter})).status,'complete');await closeV2Store();assert.equal((await processIndexJob(a.tenantId,id,{provider:f.value,adapter:idx.adapter})).status,'complete');assert.equal(f.calls,1);assert.equal(idx.rows.size,1);});
test('standing policy does not authorize private scope or a changed policy or member',async()=>{policy();const a=actor();await send(a,{...doc(),scope:{kind:'private',actorIds:['alice']}} as WorkspaceCommand);assert.equal((await snapshot(a)).indexing.length,0);const r=await send(a,doc()),f=provider(),idx=index();policy(['team','matter']);const blocked=await processIndexJob(a.tenantId,r.snapshot.indexing[0].id,{provider:f.value,adapter:idx.adapter});assert.equal(blocked.reason,'INDEX_GRANT_CHANGED');assert.equal(f.calls,0);const r2=await send(a,doc('Third agreement'));await transactWorkspace(a.tenantId,s=>{s.memberships[0].version++;});assert.equal((await processIndexJob(a.tenantId,r2.snapshot.indexing.at(-1)!.id,{provider:f.value,adapter:idx.adapter})).reason,'INDEX_MEMBERSHIP_CHANGED');assert.equal(f.calls,0);});
test('revocation during embedding preserves accounted cost but cannot write index content',async()=>{policy();const a=actor(),r=await send(a,doc()),f=provider(async()=>{await send(a,{type:'source.revoke',sourceId:String(r.result.sourceId),reason:'Removed during maintenance'});}),idx=index();const done=await processIndexJob(a.tenantId,r.snapshot.indexing[0].id,{provider:f.value,adapter:idx.adapter});assert.equal(done.status,'blocked');assert.equal(idx.rows.size,0);assert.equal(f.calls,1);assert.ok((await globalSpendStatus()).spent_usd>0);});
test('global concurrency delays the same job; a later retry invokes the provider once',async()=>{policy();const a=actor(),r=await send(a,doc()),f=provider(),idx=index(),id=r.snapshot.indexing[0].id;const ids=[randomUUID(),randomUUID()];await reserveGlobalSpend(ids[0],.001);await reserveGlobalSpend(ids[1],.001);assert.equal((await processIndexJob(a.tenantId,id,{provider:f.value,adapter:idx.adapter})).status,'queued');assert.equal(f.calls,0);await settleGlobalSpend(ids[0],0);await settleGlobalSpend(ids[1],0);await transactWorkspace(a.tenantId,s=>{(s.receipts['index-maintenance:'+id].result.job as {nextAttemptAt:null}).nextAttemptAt=null;});assert.equal((await processIndexJob(a.tenantId,id,{provider:f.value,adapter:idx.adapter})).status,'complete');assert.equal(f.calls,1);});
test('budget exhaustion and ambiguous provider failure never trigger automatic resubmission',async()=>{policy();const a=actor(),r=await send(a,{type:'document.add',title:'Bounded budget document',body:'Many exact counted words '.repeat(100),authority:'executed',kind:'agreement'}),f=provider(),idx=index(),id=r.snapshot.indexing[0].id;process.env.KIARA_OPENAI_BUDGET_USD='0.000000001';assert.equal((await processIndexJob(a.tenantId,id,{provider:f.value,adapter:idx.adapter})).status,'blocked');assert.equal(f.calls,0);process.env.KIARA_OPENAI_BUDGET_USD='1';const next=await send(a,doc('Unknown outcome')),nextId=next.snapshot.indexing.at(-1)!.id;let calls=0;const broken:EmbeddingProvider={create:async()=>{calls++;throw new Error('Connection reset after dispatch');}};assert.equal((await processIndexJob(a.tenantId,nextId,{provider:broken,adapter:idx.adapter})).status,'unknown');assert.equal((await processIndexJob(a.tenantId,nextId,{provider:broken,adapter:idx.adapter})).status,'unknown');assert.equal(calls,1);});
test('global unknown guard blocks before dispatch and audited operator requeue requires a clear ledger and exact plan',async()=>{policy();const a=actor(),r=await send(a,doc()),id=r.snapshot.indexing[0].id,idx=index(),f=provider(),external=randomUUID();await reserveGlobalSpend(external,.001);await recoverGlobalSpend(external,true);const blocked=await processIndexJob(a.tenantId,id,{provider:f.value,adapter:idx.adapter});assert.equal(blocked.status,'blocked');assert.equal(blocked.reason,'GLOBAL_CHARGE_UNKNOWN');assert.equal(f.calls,0);await transactWorkspace(a.tenantId,s=>{(s.receipts[`index-maintenance:${id}`].result.job as {status:string}).status='unknown';});const pending=await previewIndexRecovery(a,id);assert.equal(pending.ready,false);await assert.rejects(()=>requeueIndexJob(a,id,{expectedVersion:pending.workspaceVersion,planHash:pending.planHash,reason:'Reviewed global ledger and retained job proof.'}),code('GLOBAL_CHARGE_UNKNOWN'));await conservativelyAccountUnknownCharge({charge_id:external,expected_reserved_usd:.001,actor:'test-operator',reason:'Reviewed and covered the entire reservation without retrying the original charge.',confirmation:'charge_full_reservation_without_retry'});const inspected=await previewIndexRecovery(a,id);assert.equal(inspected.ready,true);assert.equal(inspected.neverDispatchedChunks,1);await assert.rejects(()=>requeueIndexJob(a,id,{expectedVersion:inspected.workspaceVersion,planHash:'0'.repeat(64),reason:'Reviewed global ledger and retained job proof.'}),code('INDEX_RECOVERY_CHANGED'));const recovered=await requeueIndexJob(a,id,{expectedVersion:inspected.workspaceVersion,planHash:inspected.planHash,reason:'Reviewed global ledger and retained job proof.'});assert.equal(recovered.job.status,'queued');const state=await readWorkspace(a.tenantId);assert.equal((state.receipts[`index-recovery:${recovered.outboxId}`].result as {operatorId:string}).operatorId,a.actorId);assert.equal(state.outbox.filter(x=>x.aggregateId===id&&x.kind==='index_maintenance').length,2);assert.equal((await processIndexJob(a.tenantId,id,{provider:f.value,adapter:idx.adapter})).status,'complete');assert.equal(f.calls,1);});
test('recovery reuses completed chunks but fences an uncertain embedding',async()=>{policy();const a=actor(),r=await send(a,{type:'document.add',title:'Two clauses',body:'First clause contains retained terms.\n\nSecond clause contains additional terms.',authority:'executed',kind:'agreement'}),id=r.snapshot.indexing[0].id,idx=index(),external=randomUUID();let calls=0;const f:EmbeddingProvider={create:async request=>{calls++;if(calls===1){await reserveGlobalSpend(external,.001);await recoverGlobalSpend(external,true);}return {model:request.model,data:[{index:0,embedding:Array(1536).fill(.01)}],usage:{prompt_tokens:request.input.length,total_tokens:request.input.length}};}};const blocked=await processIndexJob(a.tenantId,id,{provider:f,adapter:idx.adapter});assert.equal(blocked.reason,'GLOBAL_CHARGE_UNKNOWN');assert.equal(blocked.status,'blocked');assert.equal(calls,1);await conservativelyAccountUnknownCharge({charge_id:external,expected_reserved_usd:.001,actor:'test-operator',reason:'Covered the separate unknown reservation before restarting index maintenance.',confirmation:'charge_full_reservation_without_retry'});const inspected=await previewIndexRecovery(a,id);assert.ok(inspected.reusableCompletedChunks>=1);assert.ok(inspected.neverDispatchedChunks>=1);await requeueIndexJob(a,id,{expectedVersion:inspected.workspaceVersion,planHash:inspected.planHash,reason:'Reviewed completed and pre-dispatch chunk receipts.'});assert.equal((await processIndexJob(a.tenantId,id,{provider:f,adapter:idx.adapter})).status,'complete');assert.equal(calls,inspected.chunkCount);const next=await send(a,doc('Uncertain chunk'));const unknownId=next.snapshot.indexing.at(-1)!.id;const bad:EmbeddingProvider={create:async()=>{throw new Error('Provider outcome unknown');}};assert.equal((await processIndexJob(a.tenantId,unknownId,{provider:bad,adapter:idx.adapter})).status,'unknown');await assert.rejects(()=>previewIndexRecovery(a,unknownId),code('INDEX_RECOVERY_NOT_ELIGIBLE'));await transactWorkspace(a.tenantId,s=>{(s.receipts[`index-maintenance:${unknownId}`].result.job as {reason:string}).reason='GLOBAL_CHARGE_UNKNOWN';});await assert.rejects(()=>previewIndexRecovery(a,unknownId),code('INDEX_EMBEDDING_UNCERTAIN'));});
test('recovery rechecks an OIDC binding even while administrator membership persists',async()=>{policy();const a=actor(),r=await send(a,doc()),id=r.snapshot.indexing[0].id,issuer='https://issuer.example.test',subject='synthetic-operator';await transactWorkspace(a.tenantId,s=>{const j=s.receipts[`index-maintenance:${id}`].result.job as {status:string;reason:string};j.status='blocked';j.reason='GLOBAL_CHARGE_UNKNOWN';});process.env.KIARA_OIDC_IDENTITY_SOURCE='fixture_env';process.env.KIARA_OIDC_ISSUER=issuer;process.env.KIARA_OIDC_IDENTITIES=JSON.stringify([{subject,tenantId:a.tenantId,actorId:a.actorId}]);const bound:ActorContext={...a,mode:'authenticated',oidcBinding:{key:identityBindingKey(issuer,subject),version:1}};const preview=await previewIndexRecovery(bound,id);assert.equal(preview.ready,true);process.env.KIARA_OIDC_IDENTITIES='[]';await assert.rejects(()=>requeueIndexJob(bound,id,{expectedVersion:preview.workspaceVersion,planHash:preview.planHash,reason:'Reviewed current actor and recovery proof.'}),code('IDENTITY_GRANT_CHANGED'));assert.equal((await readWorkspace(a.tenantId)).memberships[0].revokedAt,null);process.env.KIARA_V2_AUTH_MODE='oidc';await assert.rejects(()=>previewIndexRecovery(a,id),code('IDENTITY_GRANT_INVALID'));});
test('covered unknown embedding can be replaced by a distinct audited title-aware attempt with Atlas readback',async()=>{
 policy();const a=actor(),created=await send(a,doc('Test employer terms')),jobId=created.snapshot.indexing[0].id,idx=index();let failedCalls=0;const failed:EmbeddingProvider={create:async()=>{failedCalls++;throw new Error('Ambiguous transport failure');}};
 assert.equal((await processIndexJob(a.tenantId,jobId,{provider:failed,adapter:idx.adapter})).status,'unknown');const state=await readWorkspace(a.tenantId),job=state.receipts[`index-maintenance:${jobId}`].result.job as {chunkIds:string[];status:string},chunkId=job.chunkIds[0],old=Object.values(state.receipts).map(r=>r.result.job as {id?:string;key?:string;status?:string}|undefined).find(j=>j?.key?.startsWith('index:'))!;
 const pending=await previewUnknownEmbeddingRepair(a,jobId,chunkId,{adapter:idx.adapter});assert.equal(pending.ready,false);await assert.rejects(()=>repairUnknownEmbedding(a,jobId,chunkId,{expectedVersion:pending.workspaceVersion,planHash:pending.planHash,reason:'Reviewed uncertain attempt and exact source.'},{provider:provider().value,adapter:idx.adapter}),code('INDEX_REPAIR_CHARGE_UNCOVERED'));
 await conservativelyAccountUnknownCharge({charge_id:old.id!,expected_reserved_usd:.000001,actor:'test-operator',reason:'Covered the original uncertain embedding ceiling without retrying it.',confirmation:'charge_full_reservation_without_retry'});
 const inspected=await previewUnknownEmbeddingRepair(a,jobId,chunkId,{adapter:idx.adapter});assert.equal(inspected.ready,true);await assert.rejects(()=>repairUnknownEmbedding(a,jobId,chunkId,{expectedVersion:inspected.workspaceVersion,planHash:'0'.repeat(64),reason:'Reviewed uncertain attempt and exact source.'},{provider:provider().value,adapter:idx.adapter}),code('INDEX_REPAIR_CHANGED'));
 let repairedCalls=0;const repaired:EmbeddingProvider={create:async request=>{repairedCalls++;return {model:request.model,data:[{index:0,embedding:Array(1536).fill(.02)}],usage:{prompt_tokens:request.input.length,total_tokens:request.input.length}};}};
 const result=await repairUnknownEmbedding(a,jobId,chunkId,{expectedVersion:inspected.workspaceVersion,planHash:inspected.planHash,reason:'Reviewed uncertain attempt and exact source.'},{provider:repaired,adapter:idx.adapter});assert.equal(result.status,'complete');assert.equal(result.oldAttemptId,old.id);assert.notEqual(result.newAttemptId,old.id);assert.equal(repairedCalls,1);assert.equal(failedCalls,1);assert.deepEqual(await idx.adapter.present(a.tenantId,[chunkId]),[chunkId]);
 const after=await readWorkspace(a.tenantId),original=Object.values(after.receipts).map(r=>r.result.job as {id?:string;status?:string}|undefined).find(j=>j?.id===old.id),audit=after.receipts[`index-embedding-repair:${chunkId}`].result;assert.equal(original?.status,'unknown');assert.equal((after.receipts[`index-maintenance:${jobId}`].result.job as {status:string}).status,'unknown');assert.equal(audit.atlasReadback,true);assert.notEqual(audit.oldInputHash,audit.newInputHash);assert.equal((await globalSpendStatus()).request_count,2);await assert.rejects(()=>previewUnknownEmbeddingRepair(a,jobId,chunkId,{adapter:idx.adapter}),code('INDEX_REPAIR_ALREADY_COMPLETE'));
});
test('unknown embedding repair fails closed if the operator OIDC binding changes after preview',async()=>{
 policy();const a=actor(),created=await send(a,doc()),jobId=created.snapshot.indexing[0].id,idx=index(),issuer='https://issuer.example.test',subject='repair-operator';await processIndexJob(a.tenantId,jobId,{provider:{create:async()=>{throw new Error('Ambiguous dispatch');}},adapter:idx.adapter});const state=await readWorkspace(a.tenantId),chunkId=(state.receipts[`index-maintenance:${jobId}`].result.job as {chunkIds:string[]}).chunkIds[0],old=Object.values(state.receipts).map(r=>r.result.job as {id?:string;key?:string}|undefined).find(j=>j?.key?.startsWith('index:'))!;
 await conservativelyAccountUnknownCharge({charge_id:old.id!,expected_reserved_usd:.000001,actor:'test-operator',reason:'Covered the uncertain original embedding before reviewing repair.',confirmation:'charge_full_reservation_without_retry'});process.env.KIARA_OIDC_IDENTITY_SOURCE='fixture_env';process.env.KIARA_OIDC_ISSUER=issuer;process.env.KIARA_OIDC_IDENTITIES=JSON.stringify([{subject,tenantId:a.tenantId,actorId:a.actorId}]);const bound:ActorContext={...a,mode:'authenticated',oidcBinding:{key:identityBindingKey(issuer,subject),version:1}},preview=await previewUnknownEmbeddingRepair(bound,jobId,chunkId,{adapter:idx.adapter});process.env.KIARA_OIDC_IDENTITIES='[]';let calls=0;await assert.rejects(()=>repairUnknownEmbedding(bound,jobId,chunkId,{expectedVersion:preview.workspaceVersion,planHash:preview.planHash,reason:'Reviewed original charge and current legal scope.'},{provider:{create:async request=>{calls++;return {model:request.model,data:[{index:0,embedding:Array(1536).fill(.01)}],usage:{prompt_tokens:request.input.length,total_tokens:request.input.length}};}},adapter:idx.adapter}),code('IDENTITY_GRANT_CHANGED'));assert.equal(calls,0);
});
test('unknown embedding repair cannot upsert after the source is revoked during the new dispatch',async()=>{
 policy();const a=actor(),created=await send(a,doc('Revoked during repair')),jobId=created.snapshot.indexing[0].id,idx=index();await processIndexJob(a.tenantId,jobId,{provider:{create:async()=>{throw new Error('Ambiguous original dispatch');}},adapter:idx.adapter});const state=await readWorkspace(a.tenantId),chunkId=(state.receipts[`index-maintenance:${jobId}`].result.job as {chunkIds:string[]}).chunkIds[0],old=Object.values(state.receipts).map(r=>r.result.job as {id?:string;key?:string}|undefined).find(j=>j?.key?.startsWith('index:'))!;
 await conservativelyAccountUnknownCharge({charge_id:old.id!,expected_reserved_usd:.000001,actor:'test-operator',reason:'Covered original unknown charge before the bounded source check.',confirmation:'charge_full_reservation_without_retry'});const preview=await previewUnknownEmbeddingRepair(a,jobId,chunkId,{adapter:idx.adapter});const changed:EmbeddingProvider={create:async request=>{await send(a,{type:'source.revoke',sourceId:String(created.result.sourceId),reason:'Withdraw during bounded repair'});return {model:request.model,data:[{index:0,embedding:Array(1536).fill(.02)}],usage:{prompt_tokens:request.input.length,total_tokens:request.input.length}};}};
 await assert.rejects(()=>repairUnknownEmbedding(a,jobId,chunkId,{expectedVersion:preview.workspaceVersion,planHash:preview.planHash,reason:'Reviewed original charge and current source access.'},{provider:changed,adapter:idx.adapter}),code('INDEX_EVIDENCE_CHANGED'));assert.deepEqual(await idx.adapter.present(a.tenantId,[chunkId]),[]);assert.equal((await readWorkspace(a.tenantId)).receipts[`index-embedding-repair:${chunkId}`].result.status,'pending');
});
test('unknown embedding repair removes the exact Atlas chunk if authority changes after upsert',async()=>{
 policy();const a=actor(),created=await send(a,doc('Revoked after Atlas upsert')),jobId=created.snapshot.indexing[0].id,idx=index();await processIndexJob(a.tenantId,jobId,{provider:{create:async()=>{throw new Error('Ambiguous original dispatch');}},adapter:idx.adapter});const state=await readWorkspace(a.tenantId),chunkId=(state.receipts[`index-maintenance:${jobId}`].result.job as {chunkIds:string[]}).chunkIds[0],old=Object.values(state.receipts).map(r=>r.result.job as {id?:string;key?:string}|undefined).find(j=>j?.key?.startsWith('index:'))!;
 await conservativelyAccountUnknownCharge({charge_id:old.id!,expected_reserved_usd:.000001,actor:'test-operator',reason:'Covered original unknown charge before the post-upsert authority check.',confirmation:'charge_full_reservation_without_retry'});
 let revoked=false,removedIds:string[]=[];const adapter:HybridAdapter={...idx.adapter,present:async(tenant,ids)=>{const found=await idx.adapter.present(tenant,ids);if(found.includes(chunkId)&&!revoked){revoked=true;await send(a,{type:'source.revoke',sourceId:String(created.result.sourceId),reason:'Withdraw after Atlas upsert'});}return found;},remove:async(tenant,ids)=>{removedIds=ids;await idx.adapter.remove(tenant,ids);}};
 const preview=await previewUnknownEmbeddingRepair(a,jobId,chunkId,{adapter});await assert.rejects(()=>repairUnknownEmbedding(a,jobId,chunkId,{expectedVersion:preview.workspaceVersion,planHash:preview.planHash,reason:'Reviewed original charge and exact current source.'},{provider:provider().value,adapter}),code('INDEX_EVIDENCE_CHANGED'));assert.equal(revoked,true);assert.deepEqual(removedIds,[chunkId]);assert.deepEqual(await idx.adapter.present(a.tenantId,[chunkId]),[]);
 const after=await readWorkspace(a.tenantId);assert.equal((after.receipts[`index-maintenance:${jobId}`].result.job as {status:string}).status,'unknown');assert.equal(after.receipts[`index-embedding-repair:${chunkId}`].result.status,'pending');
});
test('unknown embedding repair does not remove another writer\'s conflicting Atlas row',async()=>{
 policy();const a=actor(),created=await send(a,doc('Concurrent Atlas writer')),jobId=created.snapshot.indexing[0].id,idx=index();await processIndexJob(a.tenantId,jobId,{provider:{create:async()=>{throw new Error('Ambiguous original dispatch');}},adapter:idx.adapter});const state=await readWorkspace(a.tenantId),chunkId=(state.receipts[`index-maintenance:${jobId}`].result.job as {chunkIds:string[]}).chunkIds[0],old=Object.values(state.receipts).map(r=>r.result.job as {id?:string;key?:string}|undefined).find(j=>j?.key?.startsWith('index:'))!;
 await conservativelyAccountUnknownCharge({charge_id:old.id!,expected_reserved_usd:.000001,actor:'test-operator',reason:'Covered original unknown charge before a concurrent index conflict.',confirmation:'charge_full_reservation_without_retry'});
 let removals=0;const adapter:HybridAdapter={...idx.adapter,upsert:async chunk=>{await idx.adapter.upsert(chunk,Array(1536).fill(.04));throw new V2Error('HYBRID_INDEX_CONFLICT','Another writer already inserted an immutable vector.');},remove:async()=>{removals++;}};const preview=await previewUnknownEmbeddingRepair(a,jobId,chunkId,{adapter});assert.equal(preview.atlasPresent,false);
 await assert.rejects(()=>repairUnknownEmbedding(a,jobId,chunkId,{expectedVersion:preview.workspaceVersion,planHash:preview.planHash,reason:'Reviewed original charge and concurrent Atlas ownership.'},{provider:provider().value,adapter}),code('HYBRID_INDEX_CONFLICT'));assert.equal(removals,0);assert.deepEqual(await idx.adapter.present(a.tenantId,[chunkId]),[chunkId]);const after=await readWorkspace(a.tenantId);assert.equal((after.receipts[`index-maintenance:${jobId}`].result.job as {status:string}).status,'unknown');assert.equal(after.receipts[`index-embedding-repair:${chunkId}`].result.status,'pending');
});
async function inventoryFixture(){delete process.env.KIARA_V2_INDEX_POLICY;const a=actor();const document=await send(a,doc());const draft=await send(a,{type:'document.add',title:'Draft amendment',body:'Amendment awaiting execution.',authority:'draft',kind:'agreement'});await send(a,{...doc('Private unrelated agreement'),scope:{kind:'private',actorIds:['alice']}} as WorkspaceCommand);const created=await send(a,{type:'matter.create',title:'Notice assessment',objective:'Assess the supplied Acme agreement register.'}),m=created.snapshot.matters[0],candidate=created.snapshot.inventoryCandidates[0];return {a,m,document,draft,candidate};}
async function attest(f:Awaited<ReturnType<typeof inventoryFixture>>){return send(f.a,{type:'inventory.attest',matterId:f.m.id,expectedMatterVersion:f.m.version,title:'Acme supplied agreements',scopeDescription:'Acme customer agreements in the shared company register, confirmed by the contract owner.',documentIds:f.candidate.documentIds,sourceIds:[String(f.document.result.sourceId)],validUntil:future(5)});}
test('inventory requires every current head including draft authority, preserves exact counts and does not claim external discovery',async()=>{const f=await inventoryFixture();assert.equal(f.candidate.count,2);await assert.rejects(()=>send(f.a,{type:'inventory.attest',matterId:f.m.id,expectedMatterVersion:f.m.version,title:'Incomplete',scopeDescription:'Acme',documentIds:[String(f.document.result.documentId)],sourceIds:[String(f.document.result.sourceId)],validUntil:future()}),code('INVENTORY_SET_CHANGED'));const r=await attest(f);assert.equal(r.snapshot.inventories[0].count,2);assert.equal(r.snapshot.inventories[0].current,true);const ready=await send(f.a,{type:'matter.prepare',matterId:f.m.id,expectedRecordVersion:f.m.version});const p=ready.snapshot.proposals[0];assert.equal(p.inventoryComplete,true);assert.equal(p.inventory?.count,2);assert.match(p.body,/human attestation.*external discovery/);});
test('new current agreement heads invalidate attested completeness; historical drafts cannot satisfy a successor',async()=>{const f=await inventoryFixture(),r=await attest(f),state=await readWorkspace(f.a.tenantId);assert.equal(inventoryCurrent(state,state.inventories![0]),true);const d=r.snapshot.documents.find(d=>d.id===f.draft.result.documentId)!;await send(f.a,{type:'document.reimport',baseRevisionId:d.id,expectedContentHash:d.contentHash,body:'Revised amendment, still unsigned.',note:'Returned revision'});const latest=await snapshot(f.a);assert.equal(latest.inventories[0].current,false);assert.equal(latest.inventoryCandidates[0].count,2);assert.ok(!latest.inventoryCandidates[0].documentIds.includes(d.id));const ready=await send(f.a,{type:'matter.prepare',matterId:f.m.id,expectedRecordVersion:latest.matters[0].version});assert.equal(ready.snapshot.proposals.at(-1)!.inventoryComplete,false);});
test('attestation expiry independently blocks fresh approval and final execution without a record mutation',async()=>{const f=await inventoryFixture();await attest(f);const objective=await send(f.a,{type:'fact.propose',predicate:'business_objective',value:f.m.objective});const fact=objective.snapshot.facts[0];await send(f.a,{type:'fact.confirm',factId:fact.id,expectedRecordVersion:fact.version,expectedOriginVersion:fact.originVersion});const ready=await send(f.a,{type:'matter.prepare',matterId:f.m.id,expectedRecordVersion:f.m.version}),p=ready.snapshot.proposals[0];for(const capacity of ['business','legal'] as const)await send(f.a,{type:'approval.record',proposalId:p.id,proposalHash:p.contentHash,capacity,validUntil:future()});const planned=await send(f.a,{type:'action.plan',matterId:f.m.id,proposalId:p.id,title:'Retain reviewed packet',kind:'internal_document',content:p.body}),action=planned.snapshot.actions[0];await send(f.a,{type:'action.authorize',actionId:action.id,expectedRecordVersion:action.version,contentHash:action.contentHash,validUntil:future()});const s=await readWorkspace(f.a.tenantId);assertExecutable(s,f.a,s.actions[0]);const now=Date.now;try{Date.now=()=>now()+10*60000;assert.throws(()=>assertProposalInventory(s,p),code('INVENTORY_CHANGED'));assert.throws(()=>assertExecutable(s,f.a,s.actions[0]),code('INVENTORY_CHANGED'));await assert.rejects(()=>send(f.a,{type:'approval.record',proposalId:p.id,proposalHash:p.contentHash,capacity:'business',validUntil:future()}),code('INVENTORY_CHANGED'));}finally{Date.now=now;}});
test('private attestation evidence cannot be copied into a team proposal',async()=>{const f=await inventoryFixture(),b=actor('bob',['member']);await snapshot(b);const secret=await send(f.a,{type:'document.add',title:'Private scope proof',body:'Private inventory canary 7654321',authority:'unknown',scope:{kind:'private',actorIds:['alice']}});await send(f.a,{type:'inventory.attest',matterId:f.m.id,expectedMatterVersion:f.m.version,title:'Scoped register',scopeDescription:'Private inventory canary 7654321',documentIds:f.candidate.documentIds,sourceIds:[String(secret.result.sourceId)],validUntil:future()});await send(f.a,{type:'matter.prepare',matterId:f.m.id,expectedRecordVersion:f.m.version});const other=await snapshot(b),serialized=JSON.stringify(other);assert.ok(!serialized.includes('7654321'));assert.equal(other.proposals.length,1);assert.equal(other.proposals[0].inventoryComplete,false,'private completeness evidence is not adopted into the team packet');});

test('malformed maintenance policy or missing Atlas configuration never rolls back source or member revocation',async()=>{const a=actor(),b=actor('bob',['member']);await snapshot(b);const first=await send(a,doc());process.env.KIARA_V2_INDEX_POLICY='{invalid';const revoked=await send(a,{type:'source.revoke',sourceId:String(first.result.sourceId),reason:'Remove access immediately'});assert.equal((await readWorkspace(a.tenantId)).sources.find(x=>x.id===first.result.sourceId)?.status,'revoked');assert.equal(revoked.snapshot.indexing.at(-1)?.reason,'INDEX_POLICY_INVALID');await send(a,{type:'membership.revoke',actorId:b.actorId});assert.ok((await readWorkspace(a.tenantId)).memberships.find(x=>x.actorId===b.actorId)?.revokedAt);delete process.env.KIARA_V2_INDEX_POLICY;const second=await send(a,doc('Second source'));policy();delete process.env.KIARA_V2_ATLAS_VECTOR_INDEX;const missing=await send(a,{type:'source.revoke',sourceId:String(second.result.sourceId),reason:'Remove despite background configuration failure'});assert.equal((await readWorkspace(a.tenantId)).sources.find(x=>x.id===second.result.sourceId)?.status,'revoked');assert.equal(missing.snapshot.indexing.at(-1)?.reason,'HYBRID_NOT_CONFIGURED');});
