import test,{beforeEach,afterEach} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {command,snapshot} from '../src/v2/service';
import {closeV2Store,digest,readWorkspace,transactWorkspace} from '../src/v2/store';
import {processIndexJob} from '../src/v2/index-maintenance';
import {inventoryCurrent,assertProposalInventory} from '../src/v2/inventory';
import {assertExecutable} from '../src/v2/execution/authority';
import {reserveGlobalSpend,settleGlobalSpend,globalSpendStatus} from '../src/server/global-spend';
import type {HybridAdapter,HybridChunk} from '../src/v2/hybrid';
import type {EmbeddingProvider} from '../src/v2/embeddings';
import type {ActorContext,Role,WorkspaceCommand} from '../src/v2/contracts';
const keys=['KIARA_V2_DATA_DIR','KIARA_GLOBAL_BUDGET_DIR','MONGODB_URI','VERCEL','KIARA_V2_AI_MODE','OPENAI_API_KEY','KIARA_OPENAI_BUDGET_USD','KIARA_MODEL','KIARA_REVIEW_MODEL','KIARA_REASONING_EFFORT','KIARA_V2_RETRIEVAL_MODE','KIARA_V2_ATLAS_URI','KIARA_V2_ATLAS_SEARCH_INDEX','KIARA_V2_ATLAS_VECTOR_INDEX','KIARA_V2_STORE_MODE','KIARA_V2_INDEX_POLICY'];const old=Object.fromEntries(keys.map(k=>[k,process.env[k]]));let dir:string;
beforeEach(async()=>{dir=await mkdtemp(join(tmpdir(),'kiara-index-inventory-'));for(const key of keys)delete process.env[key];Object.assign(process.env,{KIARA_V2_DATA_DIR:join(dir,'workspaces'),KIARA_GLOBAL_BUDGET_DIR:join(dir,'budget'),KIARA_V2_AI_MODE:'local',KIARA_V2_RETRIEVAL_MODE:'atlas',KIARA_V2_ATLAS_URI:'mongodb://injected-test-only',KIARA_V2_ATLAS_SEARCH_INDEX:'keyword_v1',KIARA_V2_ATLAS_VECTOR_INDEX:'vector_v1',OPENAI_API_KEY:'injected-test-only',KIARA_OPENAI_BUDGET_USD:'1',KIARA_MODEL:'gpt-6-sol',KIARA_REVIEW_MODEL:'gpt-6-sol'});});
afterEach(async()=>{await closeV2Store();for(const k of keys){if(old[k]===undefined)delete process.env[k];else process.env[k]=old[k];}await rm(dir,{recursive:true,force:true});});
const roles:Role[]=['member','business_owner','fact_owner','legal_reviewer','publisher','admin'];
const actor=(id='alice',r=roles):ActorContext=>({tenantId:'index-inventory',actorId:id,mode:'local_demo',expiresAt:Date.now()+3600000,bootstrapRoles:r});
const future=(minutes=60)=>new Date(Date.now()+minutes*60000).toISOString();
async function send(a:ActorContext,c:WorkspaceCommand){return command(a,{idempotencyKey:randomUUID(),expectedVersion:(await snapshot(a)).version,command:c});}
const code=(name:string)=>(e:unknown)=>!!e&&typeof e==='object'&&'code'in e&&e.code===name;
function policy(scopeKinds=['team']){process.env.KIARA_V2_INDEX_POLICY=JSON.stringify([{tenantId:'index-inventory',enabled:true,actorIds:['alice'],scopeKinds,maxChunksPerJob:10,validUntil:future()}]);}
function provider(hook?:()=>Promise<void>){let calls=0;const value:EmbeddingProvider={create:async r=>{calls++;await hook?.();return {model:r.model,data:[{index:0,embedding:Array(1536).fill(.01)}],usage:{prompt_tokens:r.input.length,total_tokens:r.input.length},_request_id:'mock-'+calls};}};return {value,get calls(){return calls;}};}
function index(){const rows=new Map<string,HybridChunk>(),adapter:HybridAdapter={upsert:async c=>{rows.set(c.id,c);},remove:async(_t,ids)=>{ids.forEach(id=>rows.delete(id));},ids:async()=>[...rows.keys()],present:async(_t,ids)=>ids.filter(id=>rows.has(id)),search:async()=>({keywordIds:[],vectorIds:[]})};return {rows,adapter};}
const doc=(title='Agreement'):WorkspaceCommand=>({type:'document.add',title,body:'Customer notice requires 30 days. Retain applicable amendments.',authority:'executed',kind:'agreement'});
test('maintenance stays disabled by default and an explicit standing grant allows scoped member work without admin',async()=>{const a=actor('alice',['member']);await send(a,doc());assert.equal((await snapshot(a)).indexing.length,0);policy();const result=await send(a,doc('Second agreement'));assert.equal(result.snapshot.indexing.length,1);const idx=index(),f=provider(),id=result.snapshot.indexing[0].id;assert.equal((await processIndexJob(a.tenantId,id,{provider:f.value,adapter:idx.adapter})).status,'complete');await closeV2Store();assert.equal((await processIndexJob(a.tenantId,id,{provider:f.value,adapter:idx.adapter})).status,'complete');assert.equal(f.calls,1);assert.equal(idx.rows.size,1);});
test('standing policy does not authorize private scope or a changed policy or member',async()=>{policy();const a=actor();await send(a,{...doc(),scope:{kind:'private',actorIds:['alice']}} as WorkspaceCommand);assert.equal((await snapshot(a)).indexing.length,0);const r=await send(a,doc()),f=provider(),idx=index();policy(['team','matter']);const blocked=await processIndexJob(a.tenantId,r.snapshot.indexing[0].id,{provider:f.value,adapter:idx.adapter});assert.equal(blocked.reason,'INDEX_GRANT_CHANGED');assert.equal(f.calls,0);const r2=await send(a,doc('Third agreement'));await transactWorkspace(a.tenantId,s=>{s.memberships[0].version++;});assert.equal((await processIndexJob(a.tenantId,r2.snapshot.indexing.at(-1)!.id,{provider:f.value,adapter:idx.adapter})).reason,'INDEX_MEMBERSHIP_CHANGED');assert.equal(f.calls,0);});
test('revocation during embedding preserves accounted cost but cannot write index content',async()=>{policy();const a=actor(),r=await send(a,doc()),f=provider(async()=>{await send(a,{type:'source.revoke',sourceId:String(r.result.sourceId),reason:'Removed during maintenance'});}),idx=index();const done=await processIndexJob(a.tenantId,r.snapshot.indexing[0].id,{provider:f.value,adapter:idx.adapter});assert.equal(done.status,'blocked');assert.equal(idx.rows.size,0);assert.equal(f.calls,1);assert.ok((await globalSpendStatus()).spent_usd>0);});
test('global concurrency delays the same job; a later retry invokes the provider once',async()=>{policy();const a=actor(),r=await send(a,doc()),f=provider(),idx=index(),id=r.snapshot.indexing[0].id;const ids=[randomUUID(),randomUUID()];await reserveGlobalSpend(ids[0],.001);await reserveGlobalSpend(ids[1],.001);assert.equal((await processIndexJob(a.tenantId,id,{provider:f.value,adapter:idx.adapter})).status,'queued');assert.equal(f.calls,0);await settleGlobalSpend(ids[0],0);await settleGlobalSpend(ids[1],0);await transactWorkspace(a.tenantId,s=>{(s.receipts['index-maintenance:'+id].result.job as {nextAttemptAt:null}).nextAttemptAt=null;});assert.equal((await processIndexJob(a.tenantId,id,{provider:f.value,adapter:idx.adapter})).status,'complete');assert.equal(f.calls,1);});
test('budget exhaustion and ambiguous provider failure never trigger automatic resubmission',async()=>{policy();const a=actor(),r=await send(a,{type:'document.add',title:'Bounded budget document',body:'Many exact counted words '.repeat(100),authority:'executed',kind:'agreement'}),f=provider(),idx=index(),id=r.snapshot.indexing[0].id;process.env.KIARA_OPENAI_BUDGET_USD='0.000000001';assert.equal((await processIndexJob(a.tenantId,id,{provider:f.value,adapter:idx.adapter})).status,'blocked');assert.equal(f.calls,0);process.env.KIARA_OPENAI_BUDGET_USD='1';const next=await send(a,doc('Unknown outcome')),nextId=next.snapshot.indexing.at(-1)!.id;let calls=0;const broken:EmbeddingProvider={create:async()=>{calls++;throw new Error('Connection reset after dispatch');}};assert.equal((await processIndexJob(a.tenantId,nextId,{provider:broken,adapter:idx.adapter})).status,'unknown');assert.equal((await processIndexJob(a.tenantId,nextId,{provider:broken,adapter:idx.adapter})).status,'unknown');assert.equal(calls,1);});
async function inventoryFixture(){delete process.env.KIARA_V2_INDEX_POLICY;const a=actor();const document=await send(a,doc());const draft=await send(a,{type:'document.add',title:'Draft amendment',body:'Amendment awaiting execution.',authority:'draft',kind:'agreement'});await send(a,{...doc('Private unrelated agreement'),scope:{kind:'private',actorIds:['alice']}} as WorkspaceCommand);const created=await send(a,{type:'matter.create',title:'Notice assessment',objective:'Assess the supplied Acme agreement register.'}),m=created.snapshot.matters[0],candidate=created.snapshot.inventoryCandidates[0];return {a,m,document,draft,candidate};}
async function attest(f:Awaited<ReturnType<typeof inventoryFixture>>){return send(f.a,{type:'inventory.attest',matterId:f.m.id,expectedMatterVersion:f.m.version,title:'Acme supplied agreements',scopeDescription:'Acme customer agreements in the shared company register, confirmed by the contract owner.',documentIds:f.candidate.documentIds,sourceIds:[String(f.document.result.sourceId)],validUntil:future(5)});}
test('inventory requires every current head including draft authority, preserves exact counts and does not claim external discovery',async()=>{const f=await inventoryFixture();assert.equal(f.candidate.count,2);await assert.rejects(()=>send(f.a,{type:'inventory.attest',matterId:f.m.id,expectedMatterVersion:f.m.version,title:'Incomplete',scopeDescription:'Acme',documentIds:[String(f.document.result.documentId)],sourceIds:[String(f.document.result.sourceId)],validUntil:future()}),code('INVENTORY_SET_CHANGED'));const r=await attest(f);assert.equal(r.snapshot.inventories[0].count,2);assert.equal(r.snapshot.inventories[0].current,true);const ready=await send(f.a,{type:'matter.prepare',matterId:f.m.id,expectedRecordVersion:f.m.version});const p=ready.snapshot.proposals[0];assert.equal(p.inventoryComplete,true);assert.equal(p.inventory?.count,2);assert.match(p.body,/human attestation.*external discovery/);});
test('new current agreement heads invalidate attested completeness; historical drafts cannot satisfy a successor',async()=>{const f=await inventoryFixture(),r=await attest(f),state=await readWorkspace(f.a.tenantId);assert.equal(inventoryCurrent(state,state.inventories![0]),true);const d=r.snapshot.documents.find(d=>d.id===f.draft.result.documentId)!;await send(f.a,{type:'document.reimport',baseRevisionId:d.id,expectedContentHash:d.contentHash,body:'Revised amendment, still unsigned.',note:'Returned revision'});const latest=await snapshot(f.a);assert.equal(latest.inventories[0].current,false);assert.equal(latest.inventoryCandidates[0].count,2);assert.ok(!latest.inventoryCandidates[0].documentIds.includes(d.id));const ready=await send(f.a,{type:'matter.prepare',matterId:f.m.id,expectedRecordVersion:latest.matters[0].version});assert.equal(ready.snapshot.proposals.at(-1)!.inventoryComplete,false);});
test('attestation expiry independently blocks fresh approval and final execution without a record mutation',async()=>{const f=await inventoryFixture();await attest(f);const objective=await send(f.a,{type:'fact.propose',predicate:'business_objective',value:f.m.objective});const fact=objective.snapshot.facts[0];await send(f.a,{type:'fact.confirm',factId:fact.id,expectedRecordVersion:fact.version,expectedOriginVersion:fact.originVersion});const ready=await send(f.a,{type:'matter.prepare',matterId:f.m.id,expectedRecordVersion:f.m.version}),p=ready.snapshot.proposals[0];for(const capacity of ['business','legal'] as const)await send(f.a,{type:'approval.record',proposalId:p.id,proposalHash:p.contentHash,capacity,validUntil:future()});const planned=await send(f.a,{type:'action.plan',matterId:f.m.id,proposalId:p.id,title:'Retain reviewed packet',kind:'internal_document',content:p.body}),action=planned.snapshot.actions[0];await send(f.a,{type:'action.authorize',actionId:action.id,expectedRecordVersion:action.version,contentHash:action.contentHash,validUntil:future()});const s=await readWorkspace(f.a.tenantId);assertExecutable(s,f.a,s.actions[0]);const now=Date.now;try{Date.now=()=>now()+10*60000;assert.throws(()=>assertProposalInventory(s,p),code('INVENTORY_CHANGED'));assert.throws(()=>assertExecutable(s,f.a,s.actions[0]),code('INVENTORY_CHANGED'));await assert.rejects(()=>send(f.a,{type:'approval.record',proposalId:p.id,proposalHash:p.contentHash,capacity:'business',validUntil:future()}),code('INVENTORY_CHANGED'));}finally{Date.now=now;}});
test('private attestation evidence cannot be copied into a team proposal',async()=>{const f=await inventoryFixture(),b=actor('bob',['member']);await snapshot(b);const secret=await send(f.a,{type:'document.add',title:'Private scope proof',body:'Private inventory canary 7654321',authority:'unknown',scope:{kind:'private',actorIds:['alice']}});await send(f.a,{type:'inventory.attest',matterId:f.m.id,expectedMatterVersion:f.m.version,title:'Scoped register',scopeDescription:'Private inventory canary 7654321',documentIds:f.candidate.documentIds,sourceIds:[String(secret.result.sourceId)],validUntil:future()});await send(f.a,{type:'matter.prepare',matterId:f.m.id,expectedRecordVersion:f.m.version});const other=await snapshot(b),serialized=JSON.stringify(other);assert.ok(!serialized.includes('7654321'));assert.equal(other.proposals.length,1);assert.equal(other.proposals[0].inventoryComplete,false,'private completeness evidence is not adopted into the team packet');});

test('malformed maintenance policy or missing Atlas configuration never rolls back source or member revocation',async()=>{const a=actor(),b=actor('bob',['member']);await snapshot(b);const first=await send(a,doc());process.env.KIARA_V2_INDEX_POLICY='{invalid';const revoked=await send(a,{type:'source.revoke',sourceId:String(first.result.sourceId),reason:'Remove access immediately'});assert.equal((await readWorkspace(a.tenantId)).sources.find(x=>x.id===first.result.sourceId)?.status,'revoked');assert.equal(revoked.snapshot.indexing.at(-1)?.reason,'INDEX_POLICY_INVALID');await send(a,{type:'membership.revoke',actorId:b.actorId});assert.ok((await readWorkspace(a.tenantId)).memberships.find(x=>x.actorId===b.actorId)?.revokedAt);delete process.env.KIARA_V2_INDEX_POLICY;const second=await send(a,doc('Second source'));policy();delete process.env.KIARA_V2_ATLAS_VECTOR_INDEX;const missing=await send(a,{type:'source.revoke',sourceId:String(second.result.sourceId),reason:'Remove despite background configuration failure'});assert.equal((await readWorkspace(a.tenantId)).sources.find(x=>x.id===second.result.sourceId)?.status,'revoked');assert.equal(missing.snapshot.indexing.at(-1)?.reason,'HYBRID_NOT_CONFIGURED');});
