import test,{beforeEach,afterEach} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {command,snapshot} from '../src/v2/service';
import {readWorkspace,transactWorkspace,closeV2Store} from '../src/v2/store';
import type {ActorContext,Matter,Role,WorkspaceCommand} from '../src/v2/contracts';
let dir:string;const keys=['KIARA_V2_DATA_DIR','MONGODB_URI','VERCEL','KIARA_V2_AI_MODE'];const old=Object.fromEntries(keys.map(k=>[k,process.env[k]]));
beforeEach(async()=>{dir=await mkdtemp(join(tmpdir(),'kiara-learning-'));process.env.KIARA_V2_DATA_DIR=dir;delete process.env.MONGODB_URI;delete process.env.VERCEL;process.env.KIARA_V2_AI_MODE='local';});
afterEach(async()=>{await closeV2Store();for(const k of keys){if(old[k]===undefined)delete process.env[k];else process.env[k]=old[k];}await rm(dir,{recursive:true,force:true});});
const actor=(actorId='owner',roles:Role[]=['member','business_owner','fact_owner','admin']):ActorContext=>({actorId,tenantId:'learning-tenant',mode:'local_demo',expiresAt:Date.now()+3600000,bootstrapRoles:roles});
const evaluator=()=>actor('evaluator',['member','evaluator']);const lawyer=()=>actor('counsel',['member','legal_reviewer']);
const code=(c:string)=>(e:unknown)=>(e as {code:string})?.code===c;
async function send(a:ActorContext,c:WorkspaceCommand){return command(a,{idempotencyKey:randomUUID(),expectedVersion:(await snapshot(a)).version,command:c});}
async function confirm(a:ActorContext,predicate:string,value:string|boolean,sourceIds?:string[],practice:'planned'|'live'='live'){const r=await send(a,{type:'fact.propose',predicate,value,practice,sourceIds}),f=r.snapshot.facts.at(-1)!;return send(a,{type:'fact.confirm',factId:f.id,expectedRecordVersion:f.version,expectedOriginVersion:f.originVersion});}
async function matter(a:ActorContext,title='Release work'){const r=await send(a,{type:'matter.create',title,objective:'Assess the release and its customer data commitments'}),m=r.snapshot.matters.at(-1)!;return send(a,{type:'matter.prepare',matterId:m.id,expectedRecordVersion:m.version});}
async function candidate(){const a=actor();await confirm(a,'deployment','Production AI summaries are live');await confirm(a,'business_objective','Assess the release and its customer data commitments');const origin=await matter(a);const m=origin.snapshot.matters[0];const r=await send(a,{type:'learning.propose',matterId:m.id,...reviewedOrigin(m),title:'Require a cited release confirmation',rule:'Do not present a live deployment as ready without confirmed current release evidence.',kind:'procedure',scopeDescription:'This workspace scope; live deployment assertions only.',procedureKey:'release_evidence_before_live_claim'});return {a,origin,m,l:r.snapshot.learning[0]};}
async function promoted(){const {a,m,l}=await candidate();const evald=await send(evaluator(),{type:'learning.run_evaluation',candidateId:l.id,expectedRecordVersion:l.version}),ready=evald.snapshot.learning[0];const p=await send(a,{type:'learning.promote',candidateId:ready.id,expectedRecordVersion:ready.version,evaluationHash:ready.evaluationHash!});return {a,m,l:p.snapshot.learning[0]};}
const future=()=>new Date(Date.now()+7*86400000).toISOString();
const reviewedOrigin=(m:Pick<Matter,'version'|'title'|'scope'>)=>({expectedOriginVersion:m.version,expectedOriginTitle:m.title,expectedOriginScope:m.scope});

test('reviewed lesson origin is an explicit current matter, title and scope',async()=>{
 const a=actor(),first=(await matter(a,'First project')).snapshot.matters[0];
 const second=(await matter(a,'Second project')).snapshot.matters.find(m=>m.title==='Second project')!;
 const input={type:'learning.propose' as const,matterId:second.id,expectedOriginVersion:second.version,expectedOriginTitle:second.title,expectedOriginScope:second.scope,title:'Release evidence',rule:'Require current release evidence.',kind:'procedure' as const,scopeDescription:'Second project only'};
 await assert.rejects(send(a,{...input,expectedOriginTitle:first.title}),code('LESSON_ORIGIN_CHANGED'));
 await assert.rejects(send(a,{...input,expectedOriginScope:{kind:'private',actorIds:[a.actorId]}}),code('LESSON_ORIGIN_CHANGED'));
 await assert.rejects(send(a,{...input,expectedOriginVersion:second.version-1}),code('LESSON_ORIGIN_CHANGED'));
 await assert.rejects(send(a,{...input,expectedOriginVersion:undefined} as unknown as WorkspaceCommand),code('LESSON_ORIGIN_CHANGED'));
 const saved=await send(a,input);assert.equal(saved.snapshot.learning.at(-1)?.originMatterId,second.id);
});

test('server-owned frozen replay measures improvement and records immutable independent receipt',async()=>{const {a,l}=await candidate();await assert.rejects(()=>send(a,{type:'learning.run_evaluation',candidateId:l.id,expectedRecordVersion:l.version}),code('FORBIDDEN'));const e=evaluator();const r=await send(e,{type:'learning.run_evaluation',candidateId:l.id,expectedRecordVersion:l.version}),c=r.snapshot.learning[0];assert.equal(c.evaluation!.candidateFailures,0);assert.ok(c.evaluation!.baselineFailures>0);assert.deepEqual(new Set(c.evaluation!.cases.map(t=>t.group)),new Set(['original','near_miss']));assert.ok(c.evaluation!.cases.some(t=>t.baseline!==t.candidate));assert.equal(c.evaluation!.qualification,'deterministic_replay_not_legal_quality');const raw=await readWorkspace(a.tenantId);assert.equal(raw.receipts['learning-evaluation:'+c.evaluationHash].result.candidateId,l.id);assert.equal(c.status,'evaluated');assert.equal(raw.ruleVersion,1);});

test('promotion changes later comparable work without reconfirming settled current facts; release evidence resolves the real gate',async()=>{const {a}=await promoted();const later=await matter(a,'Later comparable release'),m=later.snapshot.matters.at(-1)!,p=later.snapshot.proposals.at(-1)!;assert.equal(m.state,'needs_facts');assert.match(m.blockers.join(' '),/release/i);assert.equal(later.snapshot.facts.filter(f=>f.predicate==='deployment').length,1);assert.equal(m.tasks.find(t=>t.kind==='fact')!.status,'done');await assert.rejects(()=>send(a,{type:'approval.record',proposalId:p.id,proposalHash:p.contentHash,capacity:'business',validUntil:future()}),code('PROCEDURE_REQUIREMENTS_PENDING'));const source=await send(a,{type:'document.add',title:'Release evidence',body:'Named engineering release record for production change R123.',authority:'effective'});await confirm(a,'production_release_verified',true,[String(source.result.sourceId)]);const current=(await snapshot(a)).matters.find(x=>x.id===m.id)!;const fixed=await send(a,{type:'matter.prepare',matterId:m.id,expectedRecordVersion:current.version}),next=fixed.snapshot.proposals.at(-1)!;assert.equal(fixed.snapshot.matters.find(x=>x.id===m.id)!.state,'business_review');await send(a,{type:'approval.record',proposalId:next.id,proposalHash:next.contentHash,capacity:'business',validUntil:future()});assert.equal((await snapshot(a)).matters.find(x=>x.id===m.id)!.state,'legal_review');});

test('planned deployment remains distinct and does not trigger a live-claim requirement',async()=>{const {a}=await promoted();await confirm(a,'deployment','Staging only',undefined,'planned');const r=await matter(a);assert.equal(r.snapshot.matters.at(-1)!.state,'business_review');assert.ok(!r.snapshot.matters.at(-1)!.blockers.some(x=>x.startsWith('Approved procedure:')));});

test('rollback is monotonic, identifies affected later work, invalidates its proposal and removes only that behavior',async()=>{const {a,l}=await promoted();const later=await matter(a,'Affected release'),m=later.snapshot.matters.at(-1)!,p=later.snapshot.proposals.at(-1)!;const current=(await snapshot(a)).learning.find(x=>x.id===l.id)!;const r=await send(a,{type:'learning.rollback',candidateId:l.id,expectedRecordVersion:current.version,reason:'Independent review found the scope too broad; restore prior rules and review affected work.'});assert.ok((r.result.affectedMatterIds as string[]).includes(m.id));assert.equal(r.snapshot.ruleVersion,3);assert.equal(r.snapshot.proposals.find(x=>x.id===p.id)!.status,'invalidated');const again=await send(a,{type:'matter.prepare',matterId:m.id,expectedRecordVersion:r.snapshot.matters.find(x=>x.id===m.id)!.version});assert.equal(again.snapshot.matters.find(x=>x.id===m.id)!.state,'business_review');});
test('rollback adds an owned review task even when affected open work has no proposal',async()=>{const {a,l}=await promoted();const opened=await send(a,{type:'matter.create',title:'Unprepared later work',objective:'Assess the release and its customer data commitments'}),matter=opened.snapshot.matters.at(-1)!;assert.equal(matter.proposalId,null);const rolled=await send(a,{type:'learning.rollback',candidateId:l.id,expectedRecordVersion:l.version,reason:'Scope was too broad.'}),updated=rolled.snapshot.matters.find(item=>item.id===matter.id)!;assert.ok((rolled.result.affectedMatterIds as string[]).includes(matter.id));assert.ok(updated.tasks.some(task=>task.title.includes('procedure rollback')&&task.ownerId===matter.ownerId&&task.status==='pending'));assert.match(updated.blockers.join(' '),/rolled back/);});

test('stale evaluator authority, baseline change and reused scope without improvement cannot promote',async()=>{const {a,l}=await candidate();const r=await send(evaluator(),{type:'learning.run_evaluation',candidateId:l.id,expectedRecordVersion:l.version}),c=r.snapshot.learning[0];await transactWorkspace(a.tenantId,s=>{s.memberships.find(m=>m.actorId==='evaluator')!.version++;});await assert.rejects(()=>send(a,{type:'learning.promote',candidateId:c.id,evaluationHash:c.evaluationHash!,expectedRecordVersion:c.version}),code('EXECUTED_EVALUATION_REQUIRED'));});

test('procedure owner expiry is an explicit blocker and cannot silently remove a promoted safeguard',async()=>{const {a,l}=await promoted();await transactWorkspace(a.tenantId,s=>{s.learning.find(x=>x.id===l.id)!.reviewDueAt=new Date(0).toISOString();});const r=await matter(a);assert.match(r.snapshot.matters.at(-1)!.blockers.join(' '),/requires owner review/);});

test('a private lesson never changes unrelated team work',async()=>{const a=actor();await confirm(a,'deployment','Live');const r=await send(a,{type:'matter.create',title:'Private release',objective:'Privately examine evidence',scope:{kind:'private',actorIds:[a.actorId]}}),m=r.snapshot.matters[0];const prepared=await send(a,{type:'matter.prepare',matterId:m.id,expectedRecordVersion:m.version});const reviewed=prepared.snapshot.matters.find(item=>item.id===m.id)!;const c=await send(a,{type:'learning.propose',matterId:m.id,...reviewedOrigin(reviewed),title:'Private control',rule:'Release evidence required',kind:'procedure',scopeDescription:'Private only',procedureKey:'release_evidence_before_live_claim'});const e=actor('owner',['member','evaluator']);await assert.rejects(()=>send(e,{type:'learning.run_evaluation',candidateId:c.snapshot.learning[0].id,expectedRecordVersion:1}),code('FORBIDDEN'));const team=await matter(a);assert.equal(team.snapshot.matters.at(-1)!.state,'business_review');assert.equal((await snapshot(evaluator())).learning.length,0);});

async function source(){const a=actor(),d=await send(a,{type:'document.add',title:'Supplied legal text',body:'A source supplied for named legal review. Not a verified legal conclusion.',authority:'effective'});const registered=await send(a,{type:'coverage.source.add',sourceId:String(d.result.sourceId),title:'Supplied source',sourceUrl:'https://example.test/authority',domain:'privacy',jurisdiction:'example-jurisdiction',authorityType:'guidance'});const auth=registered.snapshot.legalAuthorities[0];const defined=await send(a,{type:'coverage.define',domain:'privacy',jurisdiction:'example-jurisdiction',authorityIds:[auth.id],limitations:['Only the supplied source and declared reviewer scope are included.']});return {a,sourceId:String(d.result.sourceId),auth,entry:defined.snapshot.coverage[0]};}
async function reviewed(){const state=await source(),legal=lawyer();const v=await send(legal,{type:'coverage.source.verify',authorityId:state.auth.id,expectedRecordVersion:state.auth.version,sourceVersion:1,verificationEvidence:'Named reviewer checked the exact retained source revision and effective dates.',reviewDueAt:future()});assert.equal(v.result.current,true);const r=await send(legal,{type:'coverage.review',coverageId:state.entry.id,expectedRecordVersion:state.entry.version,qualificationEvidence:'Local fictional role review; no real professional qualification represented.',reviewDueAt:future(),limitations:['No external certification or matter clearance is implied.']});return {...state,legal,r};}

test('source verification and coverage qualification are distinct exact-version legal reviewer decisions',async()=>{const {a,auth,entry}=await source();assert.equal(entry.status,'pending_review');await assert.rejects(()=>send(a,{type:'coverage.source.verify',authorityId:auth.id,expectedRecordVersion:auth.version,sourceVersion:1,verificationEvidence:'I checked it',reviewDueAt:future()}),code('FORBIDDEN'));await assert.rejects(()=>send(lawyer(),{type:'coverage.review',coverageId:entry.id,expectedRecordVersion:entry.version,qualificationEvidence:'Reviewer evidence',reviewDueAt:future(),limitations:[]}),code('SOURCE_REVIEW_REQUIRED'));});

test('coverage becomes stale dynamically when source version, reviewer membership or review deadline changes',async()=>{const {a,sourceId,legal,r}=await reviewed();assert.equal(r.snapshot.coverage[0].status,'available');assert.equal(r.snapshot.coverage[0].qualification,'fictional_local_attestation');const before=await readWorkspace(a.tenantId);await transactWorkspace(a.tenantId,s=>{s.sources.find(x=>x.id===sourceId)!.version++;});assert.equal((await snapshot(a)).coverage[0].status,'stale');await transactWorkspace(a.tenantId,s=>{s.sources.find(x=>x.id===sourceId)!.version=before.sources[0].version;s.memberships.find(x=>x.actorId===legal.actorId)!.version++;});assert.equal((await snapshot(a)).coverage[0].status,'stale');});

test('explicit unsupported coverage remains unavailable and legal clearance is never automatically created',async()=>{const {a,r}=await reviewed();const entry=r.snapshot.coverage[0];const out=await send(a,{type:'coverage.unavailable',coverageId:entry.id,expectedRecordVersion:entry.version,reason:'No maintained expertise is available for this scope.'});assert.equal(out.snapshot.coverage[0].status,'unsupported');assert.equal(out.snapshot.approvals.length,0);assert.equal(out.snapshot.actions.length,0);});

test('registered authority must preserve source scope and exact domain/jurisdiction inventory',async()=>{const {a,auth}=await source();await assert.rejects(()=>send(a,{type:'coverage.define',domain:'tax',jurisdiction:'other',authorityIds:[auth.id],limitations:[]}),code('COVERAGE_SCOPE'));await assert.rejects(()=>send(a,{type:'coverage.source.add',sourceId:auth.sourceId,title:'Bad URL',sourceUrl:'javascript:secret()',domain:'privacy',jurisdiction:'example',authorityType:'guidance'}),code('INVALID_URL'));});


test('renewing a source review does not silently renew old coverage approval; expiry is checked at read time',async()=>{const {a,legal,auth,r}=await reviewed();const authority=r.snapshot.legalAuthorities.find(x=>x.id===auth.id)!;await send(legal,{type:'coverage.source.verify',authorityId:auth.id,expectedRecordVersion:authority.version,sourceVersion:1,verificationEvidence:'Rechecked source under a new review decision.',reviewDueAt:future()});assert.equal((await snapshot(a)).coverage[0].status,'stale');const entry=(await snapshot(a)).coverage[0];await send(legal,{type:'coverage.review',coverageId:entry.id,expectedRecordVersion:entry.version,qualificationEvidence:'Current named qualification evidence',reviewDueAt:future(),limitations:['Bounded review only.']});assert.equal((await snapshot(a)).coverage[0].status,'available');await transactWorkspace(a.tenantId,s=>{s.coverage[0].reviewDueAt=new Date(0).toISOString();});assert.equal((await snapshot(a)).coverage[0].status,'stale');});

test('an already active same-scope rule has no measured improvement and cannot be promoted again',async()=>{const {a,m}=await promoted();const r=await send(a,{type:'learning.propose',matterId:m.id,...reviewedOrigin((await snapshot(a)).matters.find(item=>item.id===m.id)!),title:'Duplicate guard',rule:'Same release guard',kind:'procedure',scopeDescription:'Same current scope',procedureKey:'release_evidence_before_live_claim'}),c=r.snapshot.learning.at(-1)!;const measured=await send(evaluator(),{type:'learning.run_evaluation',candidateId:c.id,expectedRecordVersion:c.version}),ready=measured.snapshot.learning.at(-1)!;assert.equal(ready.evaluation!.baselineFailures,0);await assert.rejects(()=>send(a,{type:'learning.promote',candidateId:ready.id,expectedRecordVersion:ready.version,evaluationHash:ready.evaluationHash!}),code('EXECUTED_EVALUATION_REQUIRED'));});


test('owner can renew an unchanged qualified deterministic rule after its review deadline',async()=>{const {a,l}=await promoted();await transactWorkspace(a.tenantId,s=>{s.learning[0].reviewDueAt=new Date(0).toISOString();});const current=(await snapshot(a)).learning[0];const renewed=await send(a,{type:'learning.renew',candidateId:l.id,expectedRecordVersion:current.version,evaluationHash:current.evaluationHash!});assert.ok(Date.parse(renewed.snapshot.learning[0].reviewDueAt!)>Date.now());assert.equal(renewed.snapshot.ruleVersion,2);const later=await matter(a);assert.match(later.snapshot.matters.at(-1)!.blockers.join(' '),/release/i);assert.ok(!later.snapshot.matters.at(-1)!.blockers.some(x=>x.includes('owner review')));});


test('holdout names, labels, outputs and evidence stay server-only across evaluator-to-author role changes',async()=>{
 const {a,l,m}=await candidate(),e=evaluator();const evaluated=await send(e,{type:'learning.run_evaluation',candidateId:l.id,expectedRecordVersion:l.version});
 const raw=await readWorkspace(a.tenantId),receipt=raw.receipts['learning-evaluation:'+evaluated.snapshot.learning[0].evaluationHash].result.evaluation as {cases:{id:string;group:string}[]},holdouts=receipt.cases.filter(c=>c.group==='holdout');assert.ok(holdouts.length>0);
 for(const identity of [a,e]){const view=await snapshot(identity);const lesson=view.learning[0];assert.equal(lesson.evaluation!.withheldHoldoutCount,holdouts.length);assert.equal(lesson.evaluation!.totalCaseCount,receipt.cases.length);assert.ok(lesson.evaluation!.cases.every(c=>c.group!=='holdout'));assert.ok(lesson.tests.every(c=>c.group!=='holdout'));for(const row of holdouts)assert.ok(!JSON.stringify(view).includes(row.id));}
 await transactWorkspace(a.tenantId,s=>{s.memberships.find(x=>x.actorId===a.actorId)!.roles.push('evaluator');s.memberships.find(x=>x.actorId===e.actorId)!.roles.push('business_owner');});
 const authored=await send(e,{type:'learning.propose',matterId:m.id,...reviewedOrigin((await snapshot(e)).matters.find(item=>item.id===m.id)!),title:'Later candidate by the prior evaluator',rule:'Require release evidence.',kind:'procedure',scopeDescription:'Same declared scope.',procedureKey:'release_evidence_before_live_claim'});assert.equal(authored.snapshot.learning.at(-1)!.provenance.actorId,e.actorId);
 for(const identity of [a,e]){const view=await snapshot(identity);for(const row of holdouts)assert.ok(!JSON.stringify(view).includes(row.id));}assert.ok(raw.learning[0].evaluation!.cases.every(c=>c.group!=='holdout'));
});
