import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {closeV2Store,readWorkspace,transactWorkspace} from '../src/v2/store';
import {processNotificationWatchReference,processNotificationDeliveryReference} from '../src/v2/orchestration/notifications';
import {processLocalOutboxOnce} from '../src/v2/orchestration/conversations';
import {dispatchOutbox} from '../src/v2/orchestration/temporal';
async function isolated(run:()=>Promise<void>){const env={...process.env},fetch=globalThis.fetch,dir=await mkdtemp(join(tmpdir(),'kiara-notification-workers-'));for(const k of Object.keys(process.env))if(/^(KIARA|MONGO|VERCEL|OPENAI|RESEND|TEMPORAL)/.test(k))delete process.env[k];process.env.KIARA_V2_DATA_DIR=dir;globalThis.fetch=async()=>{throw Error('Live messages forbidden');};try{await transactWorkspace('notice-worker',s=>{const base={tenantId:s.tenantId,version:1,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),scope:{kind:'private' as const,actorIds:['owner']},provenance:{actorId:'owner',sourceIds:[],description:'Synthetic notification'}};s.notificationEnrollments=[{...base,id:'enrollment',ownerId:'owner',mode:'required_and_digest',grantHash:'hash',membershipVersion:1,active:true}];s.notificationDeliveries=[{...base,id:'delivery',ownerId:'owner',enrollmentId:'enrollment',grantHash:'hash',membershipVersion:1,kind:'required',window:'window',itemKeys:[],status:'unknown',providerReceipt:null,reason:'UNKNOWN',leaseToken:null,leaseUntil:null,dispatchedAt:base.createdAt,dispatchToken:'synthetic-dispatch',completedAt:null}];for(const [id,kind] of [['enrollment','notification_watch'],['delivery','notification_delivery']] as const)s.outbox.push({id:'outbox-'+id,tenantId:s.tenantId,kind,aggregateId:id,commandId:id,status:'pending',owner:'v2',createdAt:base.createdAt});});await run();}finally{await closeV2Store();globalThis.fetch=fetch;for(const k of Object.keys(process.env))if(!(k in env))delete process.env[k];Object.assign(process.env,env);await rm(dir,{recursive:true,force:true});}}
const watch={tenantId:'notice-worker',aggregateId:'enrollment',outboxId:'outbox-enrollment'},delivery={tenantId:'notice-worker',aggregateId:'delivery',outboxId:'outbox-delivery'};
test('notification references omit recipients/content and validate exact retained identity before processor',()=>isolated(async()=>{
 const seen:unknown[]=[];await dispatchOutbox(watch.tenantId,{signal:async(ref,kind)=>{seen.push({ref,kind});}});assert.deepEqual(seen,[{ref:watch,kind:'notification_watch'},{ref:delivery,kind:'notification_delivery'}]);let calls=0;await assert.rejects(processNotificationDeliveryReference({...delivery,aggregateId:'other'},async()=>{calls++;return {status:'delivered',nextCheckMs:0};}),{code:'OUTBOX_NOT_FOUND'});assert.equal(calls,0);assert.deepEqual(await processNotificationWatchReference(watch,async()=>({status:'active',nextCheckMs:Infinity})),{status:'waiting',nextCheckMs:300000});assert.deepEqual(await processNotificationDeliveryReference(delivery,async()=>({status:'unknown',nextCheckMs:21600000})),{status:'waiting',nextCheckMs:21600000});
}));
test('local notification loop reschedules unknown delivery, stops completed watch and never invents a completion',()=>isolated(async()=>{
 let watches=0,deliveries=0;const deferred=new Map<string,number>();const options={deferred,notificationWatchProcessor:(ref:typeof watch)=>processNotificationWatchReference(ref,async()=>{watches++;return {status:'stopped',nextCheckMs:0};}),notificationDeliveryProcessor:(ref:typeof delivery)=>processNotificationDeliveryReference(ref,async()=>{deliveries++;return {status:'unknown',nextCheckMs:21600000};})};await processLocalOutboxOnce(watch.tenantId,options);await processLocalOutboxOnce(watch.tenantId,options);const s=await readWorkspace(watch.tenantId);assert.equal(watches,1);assert.equal(deliveries,1);assert.equal(s.outbox.find(o=>o.id===watch.outboxId)!.status,'dispatched');assert.equal(s.outbox.find(o=>o.id===delivery.outboxId)!.status,'pending');assert.equal(s.notificationDeliveries![0].status,'unknown');
}));
