import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {snapshot,command} from '../src/v2/service';
import {closeV2Store,readWorkspace,transactWorkspace} from '../src/v2/store';
import {applyNotificationCommand,notificationView,processNotificationWatch,processNotificationDelivery,reconcileNotificationDelivery} from '../src/v2/notifications';
import {applyAttentionCommand} from '../src/v2/attention';
import type {ActorContext} from '../src/v2/contracts';
const actor:ActorContext={tenantId:'independent-notification-review',actorId:'owner',mode:'local_demo',expiresAt:Date.now()+3600000,bootstrapRoles:['member','business_owner','fact_owner']};
const grant={tenantId:actor.tenantId,actorId:actor.actorId,email:'owner@example.invalid',from:'sender@example.invalid',mode:'resend',tokenEnv:'TEST_NOTIFICATION_REVIEW_TOKEN',appOrigin:'https://app.example.invalid',validUntil:'2099-01-01T00:00:00Z'};
async function isolated(run:()=>Promise<void>){const env={...process.env},native=globalThis.fetch,dir=await mkdtemp(join(tmpdir(),'kiara-notify-review-'));await closeV2Store();for(const k of Object.keys(process.env))if(/^(KIARA|MONGO|OPENAI|RESEND|TEMPORAL)/.test(k))delete process.env[k];Object.assign(process.env,{KIARA_V2_DATA_DIR:dir,KIARA_V2_AI_MODE:'local',KIARA_V2_NOTIFICATION_GRANTS:JSON.stringify([grant]),KIARA_ALLOW_LIVE_EMAIL:'true',TEST_NOTIFICATION_REVIEW_TOKEN:'synthetic-never-live'});globalThis.fetch=async()=>{throw Error('No live requests');};try{await run();}finally{await closeV2Store();globalThis.fetch=native;for(const k of Object.keys(process.env))if(!(k in env))delete process.env[k];Object.assign(process.env,env);await rm(dir,{recursive:true,force:true});}}
async function prepared(){await command(actor,{idempotencyKey:'matter',expectedVersion:(await snapshot(actor)).version,command:{type:'matter.create',title:'PRIVATE_CANARY',objective:'Private details stay inside app',scope:{kind:'private',actorIds:[actor.actorId]}}});const e=(await transactWorkspace(actor.tenantId,s=>{s.matters[0].tasks=s.matters[0].tasks.slice(0,1);s.matters[0].tasks[0].dueAt='2020-01-01T00:00:00Z';s.matters[0].tasks[0].deadlineType='response_target';applyAttentionCommand(s,actor,{type:'attention.configure',expectedRecordVersion:0,timezone:'UTC',quietEnabled:false,quietStart:'18:00',quietEnd:'09:00',digestAt:'00:00',approachingHours:24});return applyNotificationCommand(s,actor,{type:'notification.configure',expectedRecordVersion:0,mode:'required_and_digest',expectedGrantHash:notificationView(s,actor).configuration.grantHash}).enrollmentId;})).result;process.env.KIARA_ALLOW_LIVE_EMAIL='false';await processNotificationWatch(actor.tenantId,String(e));process.env.KIARA_ALLOW_LIVE_EMAIL='true';return (await readWorkspace(actor.tenantId)).notificationDeliveries![0];}
async function configure(mode:'off'|'required_and_digest'){return (await transactWorkspace(actor.tenantId,s=>applyNotificationCommand(s,actor,{type:'notification.configure',expectedRecordVersion:s.notificationEnrollments!.at(-1)!.version,mode,expectedGrantHash:mode==='off'?null:notificationView(s,actor).configuration.grantHash}))).result.enrollmentId;}

test('independent final grant mutation blocks posting to a recipient never reviewed',()=>isolated(async()=>{const d=await prepared();let posts=0;await processNotificationDelivery(actor.tenantId,d.id,{fetcher:async()=>{posts++;return Response.json({id:'unexpected'});},beforeDispatch:async()=>{process.env.KIARA_V2_NOTIFICATION_GRANTS=JSON.stringify([{...grant,email:'different@example.invalid'}]);}});assert.equal(posts,0);assert.equal((await readWorkspace(actor.tenantId)).notificationDeliveries![0].status,'canceled');}));
test('unknown dispatch remains deduped after explicit off and on; no automatic resend',()=>isolated(async()=>{const d=await prepared();let posts=0;const fetcher:typeof fetch=async()=>{posts++;throw Error('Provider may have accepted');};await processNotificationDelivery(actor.tenantId,d.id,{fetcher});assert.equal((await readWorkspace(actor.tenantId)).notificationDeliveries![0].status,'unknown');await configure('off');const e=await configure('required_and_digest');await processNotificationWatch(actor.tenantId,String(e),{fetcher});assert.equal(posts,1);assert.equal((await readWorkspace(actor.tenantId)).notificationDeliveries!.length,1);}));
test('provider acknowledgment after opt-out and expired lease is retained without another send',()=>isolated(async()=>{const d=await prepared();let posts=0,payload:any,started!:()=>void,release!:()=>void;const entered=new Promise<void>(r=>{started=r;}),waiting=new Promise<void>(r=>{release=r;});const fetcher:typeof fetch=async(_url,init)=>{if(init?.method==='POST'){posts++;payload=JSON.parse(String(init.body));started();await waiting;return Response.json({id:'late-ack'});}return Response.json({...payload,id:'late-ack',last_event:'delivered'});};const job=processNotificationDelivery(actor.tenantId,d.id,{fetcher});await entered;await configure('off');await transactWorkspace(actor.tenantId,s=>{s.notificationDeliveries![0].leaseUntil=Date.now()-1;});await processNotificationDelivery(actor.tenantId,d.id,{fetcher});release();await job;const s=await readWorkspace(actor.tenantId);assert.equal(posts,1);assert.equal(s.notificationDeliveries![0].providerReceipt,'late-ack');assert.equal(s.notificationDeliveries![0].status,'delivered');assert.equal(notificationView(s,actor).effective,false);}));
test('readback with extra HTML or attachment content cannot certify exact generic delivery',()=>isolated(async()=>{const d=await prepared();let payload:any;const fetcher:typeof fetch=async(_url,init)=>{if(init?.method==='POST'){payload=JSON.parse(String(init.body));return Response.json({id:'receipt'});}return Response.json({...payload,id:'receipt',last_event:'sent'});};await processNotificationDelivery(actor.tenantId,d.id,{fetcher});for(const extra of [{html:'<h1>Unapproved extra message</h1>'},{attachments:[{filename:'private.pdf'}]}]){const current=(await readWorkspace(actor.tenantId)).notificationDeliveries![0];await assert.rejects(reconcileNotificationDelivery(actor.tenantId,d.id,'receipt',{actor,expectedVersion:current.version,fetcher:async()=>Response.json({...payload,...extra,id:'receipt',last_event:'delivered'})}),{code:'NOTIFICATION_READBACK_MISMATCH'});}assert.equal((await readWorkspace(actor.tenantId)).notificationDeliveries![0].status,'accepted');}));

for(const retainedStatus of ['unknown','sending','accepted'] as const)test(`legacy ${retainedStatus} without a proven identity cannot repeat through grant renewal`,()=>isolated(async()=>{
 const d=await prepared();let posts=0;const fetcher:typeof fetch=async()=>{posts++;throw Error('Lost provider response');};await processNotificationDelivery(actor.tenantId,d.id,{fetcher});await transactWorkspace(actor.tenantId,s=>{const old=s.notificationDeliveries![0];delete old.identityHash;old.status=retainedStatus;if(retainedStatus==='accepted')old.providerReceipt='retained-old-receipt';});process.env.KIARA_V2_NOTIFICATION_GRANTS=JSON.stringify([{...grant,validUntil:'2099-02-01T00:00:00Z'}]);const e=await configure('required_and_digest');await processNotificationWatch(actor.tenantId,String(e),{fetcher});assert.equal(posts,1);assert.equal((await readWorkspace(actor.tenantId)).notificationDeliveries!.length,1);
}));
