import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyWorkspace,digest,validateWorkspace} from '../src/v2/store';
import {normalizeWorkspace,hydrateWorkspace,normalizedDiff,normalizedMigrationPlan} from '../src/v2/normalized-store';
function fixture(){const state=emptyWorkspace('normalized-tenant');state.memberships=[{actorId:'alice',roles:['member'],version:1,revokedAt:null,expiresAt:null,matterIds:null,entityIds:null}];state.receipts['accepted-command']={hash:'accepted',result:{effectId:'never-repeat'}};state.outbox=[{id:'outbox',tenantId:state.tenantId,kind:'matter_changed',aggregateId:'matter',commandId:'accepted-command',status:'pending',owner:'v2',createdAt:'2026-09-27T00:00:00Z'}];return state;}
test('normalization round-trips optional collections, durable receipts and outbox without identity loss',()=>{const state=fixture(),image=normalizeWorkspace(state,'generation-1');assert.deepEqual(hydrateWorkspace(image),state);assert.equal(image.rows.receipts[0].recordKey,'accepted-command');assert.equal(image.rows.memberships[0].recordKey,'alice');assert.ok(!('receipts' in image.head.metadata));assert.equal(image.head.stateHash,digest(state));});
test('normalized integrity rejects mixed tenant, generation, content, ordering or unexpected records',()=>{const original=normalizeWorkspace(fixture(),'generation-1');for(const mutate of [(x:typeof original)=>{x.rows.receipts[0].tenantId='other';},(x:typeof original)=>{x.rows.receipts[0].generation='other';},(x:typeof original)=>{x.rows.receipts[0].value={leak:true};},(x:typeof original)=>{x.rows.receipts[0].ordinal=2;},(x:typeof original)=>{x.head.metadata.companyName='tampered';}]){const image=structuredClone(original);mutate(image);assert.throws(()=>hydrateWorkspace(image));}});
test('normalized diff touches changed records only and preserves append ordering',()=>{const state=fixture(),before=normalizeWorkspace(state,'g1');state.memberships[0].version++;state.receipts['second']={hash:'second',result:{}};state.version++;const after=normalizeWorkspace(state,'g1'),diff=normalizedDiff(before,after);assert.equal(diff.find(d=>d.kind==='memberships')!.upserts.length,1);assert.equal(diff.find(d=>d.kind==='receipts')!.upserts.length,1);assert.equal(diff.find(d=>d.kind==='outbox')!.upserts.length,0);assert.ok(diff.every(d=>!d.deletes.length));assert.throws(()=>normalizedDiff(before,normalizeWorkspace(state,'other')));});
test('normalized storage removes aggregate BSON ceiling but enforces individual record allowance',()=>{const state=fixture();for(let i=0;i<14;i++)state.receipts['large-'+i]={hash:String(i),result:{payload:'x'.repeat(1_000_000)}};assert.throws(()=>validateWorkspace(state));const image=normalizeWorkspace(state,'g1');assert.equal(Object.keys(hydrateWorkspace(image).receipts).length,15);state.receipts['too-large']={hash:'huge',result:{payload:'x'.repeat(12_000_001)}};assert.throws(()=>normalizeWorkspace(state,'g1'));});
test('migration dry-run plan is deterministic, binds exact state and never dispatches effects',()=>{const state=fixture(),original=structuredClone(state),a=normalizedMigrationPlan(state),b=normalizedMigrationPlan(state);assert.deepEqual(a,b);assert.deepEqual(state,original);assert.equal(a.providerDispatches,0);assert.equal(a.records.receipts,1);state.receipts['new-effect']={hash:'new',result:{unknown:true}};assert.notEqual(normalizedMigrationPlan(state).sourceHash,a.sourceHash);});

test('empty normalized bootstrap contends on the same aggregate tenant key',async()=>{const {normalizedBootstrapFence}=await import('../src/v2/normalized-store');const state=emptyWorkspace('shared-tenant'),fence=normalizedBootstrapFence(state,'generation');assert.equal(fence._id,state.tenantId);assert.equal(fence.storageFence?.mode,'normalized');assert.equal(fence.storageFence?.generation,'generation');assert.deepEqual(fence.state,state);const collection=new Map<string,unknown>();const insert=(row:{_id:string})=>{if(collection.has(row._id))throw new Error('duplicate key');collection.set(row._id,row);};insert(fence);assert.throws(()=>insert({_id:state.tenantId}));collection.clear();insert({_id:state.tenantId});assert.throws(()=>insert(fence));});
