import test,{beforeEach,after} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {command,snapshot} from '../src/v2/service';
import {closeV2Store,transactWorkspace} from '../src/v2/store';
import {assertObligationsReady} from '../src/v2/obligations';
import type {ActorContext,Role,WorkspaceCommand} from '../src/v2/contracts';
const dirs:string[]=[];let sequence=0;
beforeEach(async()=>{await closeV2Store();const dir=await mkdtemp(join(tmpdir(),'kiara-operations-'));dirs.push(dir);process.env.KIARA_V2_DATA_DIR=dir;delete process.env.MONGODB_URI;process.env.KIARA_V2_AI_MODE='local';});
after(async()=>{await closeV2Store();await Promise.all(dirs.map(d=>rm(d,{recursive:true,force:true})));});
const actor=(id:string,roles:Role[]):ActorContext=>({tenantId:'ops-test',actorId:id,mode:'local_demo',expiresAt:Date.now()+3600000,bootstrapRoles:roles});
const owner=()=>actor('owner',['member','business_owner','fact_owner','admin']);const reviewer=()=>actor('reviewer',['member','legal_reviewer']);
const send=async(a:ActorContext,c:WorkspaceCommand)=>command(a,{idempotencyKey:`ops-${++sequence}`,expectedVersion:(await snapshot(a)).version,command:c});
const code=(value:string)=>(e:unknown)=>(e as {code:string}).code===value;
async function setup(){const a=owner(),b=reviewer();await snapshot(b);const doc=await send(a,{type:'document.add',title:'Notice agreement',body:'Notice must arrive at least 30 days before the change.',authority:'executed',kind:'agreement'});const r=await send(a,{type:'matter.create',title:'Review planned change',objective:'Assess notice before changing the service',scope:{kind:'team',actorIds:[]}});return {a,b,m:r.snapshot.matters[0],sourceId:String(doc.result.sourceId)};}
async function propose(){const v=await setup();const r=await send(v.a,{type:'obligation.propose',matterId:v.m.id,title:'Deliver contractual notice',ownerId:'owner',dueAt:'2020-01-01T17:00:00Z',deadlineType:'contractual',sourceId:v.sourceId,quote:'Notice must arrive at least 30 days before the change.',rationale:'Reviewer must confirm the exact event date and calendar basis.'});return {...v,o:r.snapshot.obligations![0]};}

test('contractual dates require exact source and legal review; reminders and manual fulfillment stay distinct',async()=>{
 const {a,b,m,o}=await propose();assert.equal(o.status,'proposed');assert.equal(o.overdue,true);await assert.rejects(()=>send(a,{type:'obligation.review',obligationId:o.id,expectedRecordVersion:o.version,basisHash:o.basisHash}),code('FORBIDDEN'));await assert.rejects(()=>send(b,{type:'obligation.review',obligationId:o.id,expectedRecordVersion:o.version,basisHash:'stale'}),code('DEADLINE_CHANGED'));
 const reviewed=await send(b,{type:'obligation.review',obligationId:o.id,expectedRecordVersion:o.version,basisHash:o.basisHash});assert.ok(!reviewed.snapshot.matters[0].blockers.includes('Review the proposed obligation and its deadline basis.'));let current=reviewed.snapshot.obligations![0];const acknowledged=await send(a,{type:'obligation.acknowledge',obligationId:o.id,expectedRecordVersion:current.version});current=acknowledged.snapshot.obligations![0];assert.equal(current.status,'active');assert.equal(current.completion,null);assert.equal(acknowledged.snapshot.matters[0].tasks.find(t=>t.id===`obligation:${o.id}`)!.status,'pending');
 await assert.rejects(()=>send(a,{type:'obligation.fulfill',obligationId:o.id,expectedRecordVersion:current.version,basisHash:o.basisHash,kind:'human_attestation',evidence:'Owner cannot interpret legal completion alone.'}),code('FORBIDDEN'));await assert.rejects(()=>send(b,{type:'obligation.fulfill',obligationId:o.id,expectedRecordVersion:current.version,basisHash:o.basisHash,kind:'verified_action',actionId:'unbound',evidence:'Unbound action does not fulfill the reviewed obligation.'}),code('OBLIGATION_ACTION_BINDING_REQUIRED'));const complete=await send(b,{type:'obligation.fulfill',obligationId:o.id,expectedRecordVersion:current.version,basisHash:o.basisHash,kind:'human_attestation',evidence:'Named owner reports the required notice was delivered and retained in the customer correspondence register.'});assert.equal(complete.snapshot.obligations![0].completion!.kind,'human_attestation');assert.equal(complete.snapshot.obligations![0].completion!.completedLate,true);assert.equal(complete.snapshot.matters.find(x=>x.id===m.id)!.tasks.find(t=>t.id===`obligation:${o.id}`)!.status,'done');
});
test('stale deadline source or reviewer authority blocks action and closure; source revocation hides derived dates',async()=>{
 const {a,b,m,o,sourceId}=await propose();await send(b,{type:'obligation.review',obligationId:o.id,expectedRecordVersion:o.version,basisHash:o.basisHash});await transactWorkspace(a.tenantId,s=>{s.memberships.find(x=>x.actorId===b.actorId)!.version++;assert.throws(()=>assertObligationsReady(s,a,m.id),code('DEADLINE_REVIEW_REQUIRED'));});assert.equal((await snapshot(a)).obligations![0].eligibility,'stale');await send(a,{type:'source.revoke',sourceId,reason:'Contract access removed'});assert.equal((await snapshot(a)).obligations!.length,0);assert.equal((await snapshot(a)).matters.length,0);
});
test('deadline proposal rejects false source quotes, ambiguous dates and inaccessible owners',async()=>{
 const {a,m,sourceId}=await setup();const c:WorkspaceCommand={type:'obligation.propose',matterId:m.id,title:'Notice',ownerId:'owner',dueAt:'2027-01-01T17:00:00Z',deadlineType:'contractual',sourceId,quote:'Not in the contract',rationale:'A proposed interpretation'};await assert.rejects(()=>send(a,c),code('QUOTE_MISMATCH'));await assert.rejects(()=>send(a,{...c,quote:'Notice must arrive',dueAt:'2027-01-01'}),code('INVALID_DEADLINE'));await assert.rejects(()=>send(a,{...c,quote:'Notice must arrive',ownerId:'unknown'}),code('OWNER_REQUIRED'));
});
test('effort totals count all stages once, distinguish estimates, retain supersession and reject overlapping timers',async()=>{
 const {a,b,m}=await setup();await send(a,{type:'baseline.record',matterId:m.id,minutes:120,method:'estimate',comparisonScope:'Equivalent drafting and review, including setup and corrections',evidence:'Owner estimate from a comparable earlier matter; no measured savings claim.'});const current=await snapshot(a),envelope={idempotencyKey:'one-recorded-interval',expectedVersion:current.version,command:{type:'effort.log',matterId:m.id,stage:'setup' as const,minutes:15,evidence:'Actual setup interval reported by the owner.'} as const};await command(a,envelope);assert.equal((await command(a,envelope)).replayed,true);await send(b,{type:'effort.log',matterId:m.id,stage:'review',minutes:35,evidence:'Reviewer reports 35 minutes spent reviewing this exact work.'});await send(a,{type:'effort.log',matterId:m.id,stage:'correction',minutes:10,evidence:'Owner reports correcting the draft.'});let s=await snapshot(a);assert.equal(s.effortComparisons[0].recordedMinutes,60);assert.equal(s.effortComparisons[0].differenceMinutes,60);assert.equal(s.effortComparisons[0].baselineMethod,'estimate');await send(a,{type:'baseline.record',matterId:m.id,minutes:100,method:'observed_comparable_work',comparisonScope:'Same scope and review standard',evidence:'Attributed timesheet of the comparable completed case.'});s=await snapshot(a);assert.equal(s.effortBaselines!.length,2);assert.equal(s.effortBaselines!.filter(x=>x.current).length,1);assert.equal(s.effortComparisons[0].differenceMinutes,40);
 const running=await send(a,{type:'effort.start',matterId:m.id,stage:'coordination'});const timer=running.snapshot.effortEntries!.at(-1)!;await assert.rejects(()=>send(a,{type:'effort.start',matterId:m.id,stage:'drafting'}),code('TIMER_ALREADY_RUNNING'));await assert.rejects(()=>send(b,{type:'effort.stop',entryId:timer.id,expectedRecordVersion:timer.version,evidence:'Attempting to stop another person'}),code('EFFORT_OWNER_REQUIRED'));await send(a,{type:'effort.void',entryId:timer.id,expectedRecordVersion:timer.version,reason:'Accidental timer; no effort claimed.'});s=await snapshot(a);assert.equal(s.effortComparisons[0].recordedMinutes,60);assert.equal(s.effortComparisons[0].runningTimers,0);
});
test('amendment inherits exact original scope and retains its source lineage',async()=>{
 const a=owner(),b=reviewer();await snapshot(b);const original=await send(a,{type:'document.add',title:'Private signed agreement',body:'Private promise retained.',authority:'executed',kind:'agreement',scope:{kind:'private',actorIds:['owner']}});const doc=original.snapshot.documents[0];await assert.rejects(()=>send(a,{type:'document.add',title:'Over-broad amendment',body:'New terms',authority:'draft',amendsDocumentId:doc.documentId,scope:{kind:'team',actorIds:[]}}),code('AMENDMENT_SCOPE'));const amended=await send(a,{type:'document.add',title:'Proposed amendment',body:'Separate proposed replacement wording.',authority:'draft',amendsDocumentId:doc.documentId});assert.equal(amended.snapshot.documents.length,2);assert.equal(amended.snapshot.documents[0].body,doc.body);assert.deepEqual(amended.snapshot.documents[1].scope,doc.scope);assert.equal((await snapshot(b)).documents.length,0);await send(a,{type:'source.revoke',sourceId:doc.sourceId,reason:'Source no longer authorized'});assert.equal((await snapshot(a)).documents.length,0);
});
