import test,{beforeEach,afterEach} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {command,snapshot} from '../src/v2/service';
import {backupWorkspace,closeV2Store,digest,readWorkspace,restoreWorkspace,transactWorkspace} from '../src/v2/store';
import {canRead} from '../src/v2/authority';
import {installationActor,type Installation} from '../src/v2/integrations/config';
import type {ActorContext,Role,WorkspaceCommand} from '../src/v2/contracts';
let dir:string;const old={dir:process.env.KIARA_V2_DATA_DIR,mongo:process.env.MONGODB_URI,vercel:process.env.VERCEL,installations:process.env.KIARA_V2_INSTALLATIONS,aiMode:process.env.KIARA_V2_AI_MODE};
beforeEach(async()=>{dir=await mkdtemp(join(tmpdir(),'kiara-v2-test-'));process.env.KIARA_V2_DATA_DIR=dir;delete process.env.MONGODB_URI;delete process.env.VERCEL;process.env.KIARA_V2_AI_MODE='local';delete process.env.KIARA_V2_INSTALLATIONS;});
afterEach(async()=>{await closeV2Store();for(const [key,value] of Object.entries({KIARA_V2_DATA_DIR:old.dir,MONGODB_URI:old.mongo,VERCEL:old.vercel,KIARA_V2_INSTALLATIONS:old.installations,KIARA_V2_AI_MODE:old.aiMode})){if(value===undefined)delete process.env[key];else process.env[key]=value;}await rm(dir,{recursive:true,force:true});});
const all:Role[]=['member','fact_owner','business_owner','legal_reviewer','publisher','signatory','admin','evaluator','integration'];
const actor=(id='alice',roles:Role[]=all,tenant='tenant-a'):ActorContext=>({tenantId:tenant,actorId:id,expiresAt:Date.now()+3600000,mode:'local_demo',bootstrapRoles:roles});
async function send(a:ActorContext,c:WorkspaceCommand,key=randomUUID()){const current=await snapshot(a);return command(a,{idempotencyKey:key,expectedVersion:current.version,command:c});}
const expires=()=>new Date(Date.now()+3600000).toISOString();
const code=(name:string)=>(e:unknown)=>!!e&&typeof e==='object'&&'code'in e&&e.code===name;
async function prepare(a=actor()){
 await send(a,{type:'document.add',title:'Acme agreement',body:'Notice must precede a new subprocessor by 30 days. This applies to production personal data.',authority:'executed',kind:'agreement'});
 const created=await send(a,{type:'matter.create',title:'Support summaries',objective:'Assess adding a vendor for support summaries'});const matter=created.snapshot.matters.at(-1)!;
 const f=await send(a,{type:'fact.propose',predicate:'business_objective',value:matter.objective,practice:'planned'});const fact=f.snapshot.facts.at(-1)!;await send(a,{type:'fact.confirm',factId:fact.id,expectedRecordVersion:fact.version,expectedOriginVersion:fact.originVersion});
 const ready=await send(a,{type:'matter.prepare',matterId:matter.id,expectedRecordVersion:matter.version});return {a,p:ready.snapshot.proposals.at(-1)!,m:ready.snapshot.matters.at(-1)!};
}
async function approve(a:ActorContext,p:{id:string;contentHash:string}){await send(a,{type:'approval.record',proposalId:p.id,proposalHash:p.contentHash,capacity:'business',validUntil:expires()});await send(a,{type:'approval.record',proposalId:p.id,proposalHash:p.contentHash,capacity:'legal',validUntil:expires()});}

test('empty workspace, useful first response, and separate hypothetical memory',async()=>{const a=actor();assert.equal((await snapshot(a)).documents.length,0);const result=await send(a,{type:'message.send',text:'What if we add AI support summaries using synthetic-only data?'});assert.equal(result.snapshot.matters.length,0);assert.equal(result.snapshot.facts.length,0);assert.equal(result.snapshot.scenarios.length,1);assert.match(result.snapshot.messages.at(-1)!.text,/synthetic|current practice/);assert.equal(result.snapshot.messages.at(-1)!.generation,'bounded_local');const scenario=result.snapshot.scenarios[0];const adopted=await send(a,{type:'scenario.adopt',scenarioId:scenario.id,expectedRecordVersion:scenario.version});const again=await send(a,{type:'scenario.adopt',scenarioId:scenario.id,expectedRecordVersion:scenario.version});assert.equal(again.result.matterId,adopted.result.matterId);assert.equal(again.snapshot.matters.length,1);assert.equal(again.snapshot.facts.length,0);});

test('ambiguous approval and unconfirmed voice cannot mutate consequential records',async()=>{const a=actor();await send(a,{type:'message.send',text:'Go ahead'});await send(a,{type:'message.send',text:'Our retention is 2030 days',channel:'voice',voiceConfirmed:false});const s=await snapshot(a);assert.equal(s.approvals.length,0);assert.equal(s.actions.length,0);assert.equal(s.facts.length,0);assert.match(s.messages.at(-1)!.text,/correct this transcript/);});

test('unauthorized corrections remain candidates and stale proposals cannot replace a newer fact',async()=>{const owner=actor(),member=actor('engineer',['member']);await snapshot(owner);const r=await send(member,{type:'fact.propose',predicate:'retention_days',value:30});const f=r.snapshot.facts[0];await assert.rejects(()=>send(member,{type:'fact.confirm',factId:f.id,expectedRecordVersion:f.version,expectedOriginVersion:f.originVersion}),code('FORBIDDEN'));await send(owner,{type:'fact.confirm',factId:f.id,expectedRecordVersion:f.version,expectedOriginVersion:f.originVersion});const first=await send(owner,{type:'fact.propose',predicate:'retention_days',value:60});const stale=first.snapshot.facts.at(-1)!;const newer=await send(owner,{type:'fact.propose',predicate:'retention_days',value:90});const current=newer.snapshot.facts.at(-1)!;await send(owner,{type:'fact.confirm',factId:current.id,expectedRecordVersion:current.version,expectedOriginVersion:current.originVersion});await assert.rejects(()=>send(owner,{type:'fact.confirm',factId:stale.id,expectedRecordVersion:stale.version,expectedOriginVersion:stale.originVersion}),code('STALE_FACT_INTENT'));assert.equal((await snapshot(owner)).facts.find(x=>x.status==='confirmed')!.value,90);});

test('personal preference applies immediately without leaking to other members',async()=>{const a=actor(),b=actor('bob',['member']);await snapshot(b);await send(a,{type:'message.send',text:'Please give me the short answer first'});assert.equal((await snapshot(a)).preferences[0].value,'short answer first');assert.equal((await snapshot(b)).preferences.length,0);assert.equal((await snapshot(a)).facts.length,0);});

test('selected-team ACL and source lineage deny content to another team member and tenant',async()=>{const a=actor(),b=actor('bob',['member']);await snapshot(a);await snapshot(b);const added=await send(a,{type:'document.add',title:'Restricted agreement',body:'Private price is 987654 dollars.',authority:'executed',kind:'agreement',scope:{kind:'team',actorIds:['alice']}});const sourceId=String(added.result.sourceId);await send(a,{type:'message.send',text:'Explain the private price agreement',scope:{kind:'team',actorIds:[]}});const own=await snapshot(a);assert.ok(own.messages.some(m=>m.provenance.sourceIds.includes(sourceId)));const other=await snapshot(b);assert.equal(other.documents.length,0);assert.equal(other.sources.length,0);assert.ok(!JSON.stringify(other).includes('987654'));const foreign=await snapshot(actor('alice',all,'tenant-b'));assert.equal(foreign.messages.length,0);assert.equal(foreign.documents.length,0);});

test('restricted counsel sees only explicitly allowed matter records and their scoped sources',async()=>{const a=actor(),b=actor('counsel',['member','legal_reviewer']);await snapshot(b);const m=await send(a,{type:'matter.create',title:'Allowed matter',objective:'Review selected packet'});const id=String(m.result.matterId);await send(a,{type:'matter.create',title:'Unrelated matter',objective:'Not shared'});await send(a,{type:'document.add',title:'Global confidential document',body:'Workspace secret',authority:'executed'});await send(a,{type:'document.add',title:'Selected packet',body:'Scope limited counsel packet',authority:'draft',scope:{kind:'matter',actorIds:[],matterId:id}});await transactWorkspace(a.tenantId,s=>{s.memberships.find(x=>x.actorId==='counsel')!.matterIds=[id];});const s=await snapshot(b);assert.deepEqual(s.matters.map(x=>x.id),[id]);assert.deepEqual(s.documents.map(x=>x.title),['Selected packet']);assert.ok(!JSON.stringify(s).includes('Workspace secret'));});

test('revocation immediately denies derived summaries with stale content still retained',async()=>{const a=actor();const r=await send(a,{type:'document.add',title:'Vendor agreement',body:'Vendor stores transcripts for 17 days.',authority:'executed'});await send(a,{type:'message.send',text:'Explain vendor transcripts agreement',scope:{kind:'team',actorIds:[]}});const before=await snapshot(a);assert.ok(before.messages.some(m=>m.role==='assistant'&&m.text.includes('17 days')));await send(a,{type:'source.revoke',sourceId:String(r.result.sourceId),reason:'Access removed'});const after=await snapshot(a);assert.equal(after.documents.length,0);assert.ok(!after.messages.some(m=>m.role==='assistant'&&m.text.includes('17 days')));const raw=await readWorkspace(a.tenantId);assert.ok(raw.messages.some(m=>m.text.includes('17 days')));assert.equal(canRead(raw,a,raw.sources[0]),false);});

test('command retry remains idempotent after restart and stale concurrent command conflicts',async()=>{const a=actor();const state=await snapshot(a);const c:WorkspaceCommand={type:'matter.create',title:'One matter',objective:'One accepted command'};const envelope={idempotencyKey:'durable-key',expectedVersion:state.version,command:c};const first=await command(a,envelope);await closeV2Store();const replay=await command(a,envelope);assert.equal(replay.replayed,true);assert.equal(replay.result.matterId,first.result.matterId);assert.equal(replay.snapshot.matters.length,1);await assert.rejects(()=>command(a,{...envelope,command:{...c,title:'Changed intent'}}),code('IDEMPOTENCY_CONFLICT'));await assert.rejects(()=>command(a,{...envelope,idempotencyKey:'another-key'}),code('VERSION_CONFLICT'));});

test('review binds exact proposal and conditioned or expired approvals cannot authorize effects',async()=>{const {a,p,m}=await prepare();await send(a,{type:'approval.record',proposalId:p.id,proposalHash:p.contentHash,capacity:'business',conditions:['Waiting for procurement'],validUntil:expires()});await assert.rejects(()=>send(a,{type:'approval.record',proposalId:p.id,proposalHash:p.contentHash,capacity:'legal',validUntil:expires()}),code('BUSINESS_APPROVAL_REQUIRED'));await approve(a,p);await assert.rejects(()=>send(a,{type:'action.plan',matterId:m.id,proposalId:p.id,kind:'send',title:'Send',content:'Different text',recipients:['recipient@example.test']}),code('ACTION_CONTENT_REVIEW_REQUIRED'));const revised=await send(a,{type:'proposal.revise',proposalId:p.id,body:'Counsel revised proposal',expectedRecordVersion:p.version});assert.notEqual(revised.result.proposalId,p.id);await assert.rejects(()=>send(a,{type:'approval.record',proposalId:p.id,proposalHash:p.contentHash,capacity:'business',validUntil:expires()}),code('STALE_PROPOSAL'));});

test('manual outcome remains pending until evidence, no-counsel route stays open, and cancellation cannot revive',async()=>{const {a,p,m}=await prepare();await approve(a,p);const counsel=await send(a,{type:'counsel.request',matterId:m.id,route:'referral'});assert.equal(counsel.snapshot.counsel[0].status,'unavailable');assert.ok(counsel.snapshot.counsel[0].packet.includes('Objective'));const plan=await send(a,{type:'action.plan',matterId:m.id,proposalId:p.id,kind:'publish',title:'Publish approved notice',content:p.body,destination:'https://example.test/privacy'});const action=plan.snapshot.actions[0];const authorized=await send(a,{type:'action.authorize',actionId:action.id,contentHash:action.contentHash,expectedRecordVersion:action.version,validUntil:expires()});assert.equal(authorized.snapshot.actions[0].status,'pending_manual');assert.equal(authorized.snapshot.actions[0].providerReceipt,null);const current=authorized.snapshot.matters[0];assert.ok(current.tasks.some(task=>task.kind==='action'&&task.ownerId===a.actorId&&task.status==='pending'&&task.evidenceIds.includes(action.id)));await assert.rejects(()=>send(a,{type:'matter.close',matterId:m.id,expectedRecordVersion:current.version,reason:'Done'}),code('TASKS_PENDING'));const cancel=await send(a,{type:'matter.cancel',matterId:m.id,expectedRecordVersion:current.version,reason:'Launch withdrawn'});assert.equal(cancel.snapshot.actions[0].status,'canceled');assert.ok(!cancel.snapshot.matters[0].tasks.some(task=>task.kind==='action'&&task.evidenceIds.includes(action.id)));await assert.rejects(()=>send(a,{type:'action.plan',matterId:m.id,proposalId:p.id,kind:'publish',title:'Retry',content:p.body}),code('MATTER_TERMINAL'));await assert.rejects(()=>send(a,{type:'approval.record',proposalId:p.id,proposalHash:p.contentHash,capacity:'business',validUntil:expires()}),code('MATTER_TERMINAL'));});

test('action-specific manual evidence closes work; runtime completion enum and signing-original checks fail closed',async()=>{const {a,p,m}=await prepare();await approve(a,p);const planned=await send(a,{type:'action.plan',matterId:m.id,proposalId:p.id,kind:'publish',title:'Publish',content:p.body,destination:'https://example.test/policy'});let action=planned.snapshot.actions[0];const auth=await send(a,{type:'action.authorize',actionId:action.id,contentHash:action.contentHash,expectedRecordVersion:action.version,validUntil:expires()});action=auth.snapshot.actions[0];await assert.rejects(()=>send(a,{type:'action.attest',actionId:action.id,expectedRecordVersion:action.version,artifact:'fake',completionKind:'readback' as 'human_attestation'}),code('INVALID_COMPLETION'));const completed=await send(a,{type:'action.attest',actionId:action.id,expectedRecordVersion:action.version,artifact:'I verified the published text at https://example.test/policy matches this authorized content.',completionKind:'human_attestation'});assert.equal(completed.snapshot.actions[0].completion!.kind,'human_attestation');assert.ok(completed.snapshot.matters[0].tasks.some(task=>task.kind==='action'&&task.status==='done'&&task.evidenceIds.includes(action.id)));const closed=await send(a,{type:'matter.close',matterId:m.id,expectedRecordVersion:completed.snapshot.matters[0].version,reason:'All required actions have named evidence.'});assert.equal(closed.snapshot.matters[0].state,'closed');});

test('no-action cannot close unresolved effects or required tasks',async()=>{const {a,p,m}=await prepare();await approve(a,p);await send(a,{type:'approval.record',proposalId:p.id,proposalHash:p.contentHash,capacity:'no_action',validUntil:expires()});const planned=await send(a,{type:'action.plan',matterId:m.id,proposalId:p.id,kind:'send',title:'Send',content:p.body,recipients:['owner@example.test']});await transactWorkspace(a.tenantId,s=>{s.actions[0].status='uncertain';});let current=(await snapshot(a)).matters[0];await assert.rejects(()=>send(a,{type:'matter.close',matterId:m.id,expectedRecordVersion:current.version,reason:'No action',noAction:true}),code('RECONCILIATION_REQUIRED'));await transactWorkspace(a.tenantId,s=>{s.actions[0].status='failed';s.matters[0].tasks[0].status='pending';});current=(await snapshot(a)).matters[0];await assert.rejects(()=>send(a,{type:'matter.close',matterId:m.id,expectedRecordVersion:current.version,reason:'No action',noAction:true}),code('TASKS_PENDING'));assert.equal(planned.snapshot.actions.length,1);});

test('reviewed no-action decision retires an authorized but unsent action task without claiming delivery',async()=>{const {a,p,m}=await prepare();await approve(a,p);await send(a,{type:'approval.record',proposalId:p.id,proposalHash:p.contentHash,capacity:'no_action',validUntil:expires()});const planned=await send(a,{type:'action.plan',matterId:m.id,proposalId:p.id,kind:'send',title:'Fictional notice that will not be sent',content:p.body,recipients:['owner@example.test']}),action=planned.snapshot.actions[0];const authorized=await send(a,{type:'action.authorize',actionId:action.id,expectedRecordVersion:action.version,contentHash:action.contentHash,validUntil:expires()});assert.ok(authorized.snapshot.matters[0].tasks.some(task=>task.kind==='action'&&task.status==='pending'&&task.evidenceIds.includes(action.id)));const matter=authorized.snapshot.matters[0],closed=await send(a,{type:'matter.close',matterId:m.id,expectedRecordVersion:matter.version,reason:'Reviewed decision not to send this fictional notice.',noAction:true});assert.equal(closed.snapshot.actions[0].status,'canceled');assert.equal(closed.snapshot.actions[0].completion,null);assert.ok(!closed.snapshot.matters[0].tasks.some(task=>task.kind==='action'&&task.evidenceIds.includes(action.id)));assert.equal(closed.snapshot.matters[0].state,'closed');});

test('expired sessions, revoked membership and authenticated unknown users cannot use bootstrap claims',async()=>{const a=actor(),b=actor('bob',['member']);await snapshot(a);await snapshot(b);await send(a,{type:'membership.revoke',actorId:b.actorId});await assert.rejects(()=>snapshot(b),code('MEMBERSHIP_REVOKED'));await assert.rejects(()=>snapshot({...a,expiresAt:0}),code('SESSION_EXPIRED'));await assert.rejects(()=>snapshot({...actor('intruder',all),mode:'authenticated'}),code('MEMBERSHIP_REVOKED'));});

test('provider events require installation authority, deduplicate and link to one existing matter',async()=>{const a=actor(),m=await send(a,{type:'matter.create',title:'RelayAI plan',objective:'Review planned integration'});const c:WorkspaceCommand={type:'event.ingest',provider:'github',externalEventId:'delivery-1',externalObjectId:'github-installation-1:test/repo:pr-218',externalRevision:'abc123',occurredAt:timestampForTest(),title:'PR merged',text:'Integration merged; deployment not established.',matterId:String(m.result.matterId)};await assert.rejects(()=>send(a,c),code('INSTALLATION_REQUIRED'));const binding:Installation={id:'github-installation-1',provider:'github',tenantId:a.tenantId,actorId:a.actorId,enabled:true,tokenEnv:'TEST_GITHUB_TOKEN',webhookSecretEnv:'TEST_GITHUB_SECRET',resources:['test/repo'],scope:{kind:'team',actorIds:[]},providerInstallationId:'1'};process.env.KIARA_V2_INSTALLATIONS=JSON.stringify([binding]);const installation=installationActor(binding);const first=await send(installation,c);const replay=await send(installation,c);assert.equal(first.result.eventId,replay.result.eventId);assert.equal(replay.snapshot.sources.length,1);assert.equal(replay.snapshot.matters.length,1);assert.equal(replay.snapshot.facts.length,0);const raw=await readWorkspace(a.tenantId);assert.ok(raw.outbox.some(x=>x.aggregateId===m.result.matterId));});
function timestampForTest(){return new Date().toISOString();}

test('deletion tombstones survive backup dry run, tampered backup is rejected, restore is restartable',async()=>{const a=actor();const r=await send(a,{type:'document.add',title:'Delete me',body:'Sensitive original text.',authority:'draft'});await send(a,{type:'source.revoke',sourceId:String(r.result.sourceId),reason:'Deletion requested',delete:true});const backup=await backupWorkspace(a.tenantId);assert.equal(backup.state.sources[0].text,'');assert.equal(backup.state.documents[0].body,'');assert.equal(backup.hash,digest(backup.state));const dry=await restoreWorkspace(backup,backup.state.version,true);assert.equal(dry.tombstones,1);await assert.rejects(()=>restoreWorkspace({...backup,hash:'wrong'},backup.state.version),code('BACKUP_INTEGRITY'));const restored=await restoreWorkspace(backup,backup.state.version,false);assert.equal(restored.dryRun,false);assert.equal((await snapshot(a)).documents.length,0);});

test('learning requires an independent evaluator and owner with frozen evidence identity',async()=>{const {a,m}=await prepare();const proposal=await send(a,{type:'learning.propose',matterId:m.id,expectedOriginVersion:m.version,expectedOriginTitle:m.title,expectedOriginScope:m.scope,title:'Deployment evidence',rule:'Require production release evidence before stating deployed.',kind:'procedure',scopeDescription:'Support summary deployment'});const candidate=proposal.snapshot.learning[0];const tests=[{name:'Original staging case',group:'original' as const,passed:true,evidence:'immutable://eval/original'},{name:'Release evidence',group:'near_miss' as const,passed:true,evidence:'immutable://eval/near'},{name:'Independent holdout',group:'holdout' as const,passed:true,evidence:'immutable://eval/holdout'}];await assert.rejects(()=>send(a,{type:'learning.evaluate',candidateId:candidate.id,tests,expectedRecordVersion:candidate.version}),code('INDEPENDENT_EVALUATOR_REQUIRED'));const evaluator=actor('evaluator',['member','evaluator']);const evaluated=await send(evaluator,{type:'learning.evaluate',candidateId:candidate.id,tests,expectedRecordVersion:candidate.version});const ready=evaluated.snapshot.learning[0];await assert.rejects(()=>send(a,{type:'learning.promote',candidateId:ready.id,evaluationHash:'wrong',expectedRecordVersion:ready.version}),code('EVALUATION_REQUIRED'));await assert.rejects(()=>send(a,{type:'learning.promote',candidateId:ready.id,evaluationHash:ready.evaluationHash!,expectedRecordVersion:ready.version}),code('EXECUTED_EVALUATION_REQUIRED'));assert.equal((await snapshot(a)).ruleVersion,1);});

test('private confirmed facts cannot leak through a team response or proposal and cannot overwrite team truth',async()=>{const a=actor(),b=actor('bob',['member']);await snapshot(b);const team=await send(a,{type:'fact.propose',predicate:'retention',value:30});const global=team.snapshot.facts[0];await send(a,{type:'fact.confirm',factId:global.id,expectedRecordVersion:global.version,expectedOriginVersion:global.originVersion});const conversation=await send(a,{type:'conversation.create',title:'Private planning'});const privateFact=await send(a,{type:'fact.propose',predicate:'retention',value:987654,conversationId:String(conversation.result.conversationId)});const secret=privateFact.snapshot.facts.at(-1)!;assert.equal(secret.supersedesId,null);await send(a,{type:'fact.confirm',factId:secret.id,expectedRecordVersion:secret.version,expectedOriginVersion:secret.originVersion});assert.equal((await snapshot(a)).facts.find(x=>x.id===global.id)!.status,'confirmed');await send(a,{type:'message.send',text:'Explain our retention',scope:{kind:'team',actorIds:[]}});assert.ok((await snapshot(a)).messages.some(m=>m.role==='assistant'&&m.text.includes('987654')));assert.ok(!JSON.stringify(await snapshot(b)).includes('987654'));const m=await send(a,{type:'matter.create',title:'Shared work',objective:'Review retention'});await send(a,{type:'matter.prepare',matterId:String(m.result.matterId),expectedRecordVersion:m.snapshot.matters[0].version});const teamProposal=(await snapshot(b)).proposals;assert.equal(teamProposal.length,1);assert.ok(teamProposal[0].body.includes('retention: 30'));assert.ok(!JSON.stringify(await snapshot(b)).includes('987654'));});

test('source originals are bound only through trusted upload metadata, never a client command property',async()=>{const a=actor(),s=await snapshot(a);const payload:WorkspaceCommand={type:'document.add',title:'Executed original',body:'Signed source text',authority:'executed',kind:'agreement'};await assert.rejects(()=>command(a,{idempotencyKey:'untrusted-upload',expectedVersion:s.version,command:{...payload,originalObjectRef:'forged'} as WorkspaceCommand}),code('UNKNOWN_FIELD'));const r=await command(a,{idempotencyKey:'upload-1',expectedVersion:s.version,command:payload},{originalObjectRef:'encrypted://tenant-a/immutable-source'});assert.equal(r.snapshot.sources[0].originalObjectRef,'encrypted://tenant-a/immutable-source');await assert.rejects(()=>command(a,{idempotencyKey:'upload-1',expectedVersion:s.version,command:payload},{originalObjectRef:'encrypted://tenant-a/different-source'}),code('IDEMPOTENCY_CONFLICT'));});

test('expired authorization and absent signed original keep consequential work pending',async()=>{const {a,p,m}=await prepare();await approve(a,p);const planned=await send(a,{type:'action.plan',matterId:m.id,proposalId:p.id,kind:'signature_request',title:'Collect executed agreement',content:p.body,recipients:['signer@example.test']});const action=planned.snapshot.actions[0];const auth=await send(a,{type:'action.authorize',actionId:action.id,contentHash:action.contentHash,expectedRecordVersion:action.version,validUntil:expires()});const pending=auth.snapshot.actions[0];await assert.rejects(()=>send(a,{type:'action.attest',actionId:action.id,expectedRecordVersion:pending.version,artifact:'The request was sent',completionKind:'executed_agreement'}),code('SIGNED_ORIGINAL_REQUIRED'));await transactWorkspace(a.tenantId,s=>{s.approvals.find(x=>x.id===pending.authorizationId)!.validUntil=new Date(0).toISOString();});await assert.rejects(()=>send(a,{type:'action.attest',actionId:action.id,expectedRecordVersion:pending.version,artifact:'The request was sent',completionKind:'executed_agreement'}),code('AUTHORIZATION_EXPIRED'));assert.equal((await snapshot(a)).actions[0].status,'pending_manual');});


test('a superseded confirmed fact keeps historical matter access while current proposals must be rebuilt',async()=>{const {a,p,m}=await prepare();const before=await snapshot(a),old=before.facts.find(f=>f.status==='confirmed')!;const candidate=await send(a,{type:'fact.propose',predicate:old.predicate,value:'Production is now live',practice:'live'}),f=candidate.snapshot.facts.at(-1)!;await send(a,{type:'fact.confirm',factId:f.id,expectedRecordVersion:f.version,expectedOriginVersion:f.originVersion});const changed=await snapshot(a);assert.equal(changed.matters[0].id,m.id);assert.equal(changed.proposals.find(x=>x.id===p.id)!.status,'invalidated');const fresh=await send(a,{type:'matter.prepare',matterId:m.id,expectedRecordVersion:changed.matters[0].version});assert.equal(fresh.snapshot.matters[0].factIds.includes(f.id),true);assert.equal(fresh.snapshot.matters[0].factIds.includes(old.id),false);assert.notEqual(fresh.result.proposalId,p.id);});


test('required business and legal tasks stay open with named owners until current unconditioned decisions',async()=>{const {a,m,p}=await prepare();const initial=(await snapshot(a)).matters.find(x=>x.id===m.id)!;assert.ok(initial.tasks.some(t=>t.kind==='business'&&t.status==='pending'&&t.ownerId));assert.ok(initial.tasks.some(t=>t.kind==='legal'&&t.status==='pending'&&t.ownerId));const conditional=await send(a,{type:'approval.record',proposalId:p.id,proposalHash:p.contentHash,capacity:'business',conditions:['Confirm vendor terms'],validUntil:expires()});assert.equal(conditional.snapshot.matters[0].tasks.find(t=>t.kind==='business')!.status,'blocked');assert.equal(conditional.snapshot.matters[0].state,'business_review');await approve(a,p);const reviewed=await snapshot(a);assert.ok(reviewed.matters[0].tasks.filter(t=>t.kind==='business'||t.kind==='legal').every(t=>t.status==='done'&&t.evidenceIds.length));const revised=await send(a,{type:'proposal.revise',proposalId:p.id,expectedRecordVersion:p.version,body:'Revised proposal requiring a new review'});assert.ok(revised.snapshot.matters[0].tasks.filter(t=>t.kind==='business'||t.kind==='legal').every(t=>t.status==='pending'&&t.evidenceIds.length===0));});

test('time-expired or future facts cannot authorize a current proposal and reprepare omits them',async()=>{const {a,p,m}=await prepare();await transactWorkspace(a.tenantId,s=>{s.facts[0].validUntil=new Date(Date.now()-1000).toISOString();});await assert.rejects(()=>send(a,{type:'approval.record',proposalId:p.id,proposalHash:p.contentHash,capacity:'business',validUntil:expires()}),code('FACT_VALIDITY_CHANGED'));const current=(await snapshot(a)).matters.find(x=>x.id===m.id)!;const refreshed=await send(a,{type:'matter.prepare',matterId:m.id,expectedRecordVersion:current.version});assert.equal(refreshed.snapshot.matters.find(x=>x.id===m.id)!.factIds.length,0);await transactWorkspace(a.tenantId,s=>{s.facts[0].validUntil=null;s.facts[0].validFrom=new Date(Date.now()+60000).toISOString();});const now=(await snapshot(a)).matters.find(x=>x.id===m.id)!;const future=await send(a,{type:'matter.prepare',matterId:m.id,expectedRecordVersion:now.version});assert.equal(future.snapshot.matters.find(x=>x.id===m.id)!.factIds.length,0);});
