import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdtemp,rm,readFile,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {command,snapshot} from '../src/v2/service';
import {processConversationRun,pendingConversationRuns,type ConversationProvider} from '../src/v2/ai';
import {applyRunControlCommand,controlledRun,runVersion} from '../src/v2/run-control';
import {closeV2Store,readWorkspace,transactWorkspace} from '../src/v2/store';
import {globalSpendStatus,reserveGlobalSpend} from '../src/server/global-spend';
import type {ActorContext,WorkspaceCommand} from '../src/v2/contracts';
const a:ActorContext={tenantId:'run-cancellation',actorId:'owner',mode:'local_demo',expiresAt:Date.now()+3600000,bootstrapRoles:['member','admin','business_owner','fact_owner']};
async function isolated(run:()=>Promise<void>){const env={...process.env},native=globalThis.fetch,dir=await mkdtemp(join(tmpdir(),'kiara-run-control-'));await closeV2Store();for(const key of Object.keys(process.env))if(/^(KIARA|MONGO|OPENAI|RESEND|TEMPORAL|VERCEL)/.test(key))delete process.env[key];Object.assign(process.env,{KIARA_V2_DATA_DIR:join(dir,'workspace'),KIARA_GLOBAL_BUDGET_DIR:join(dir,'spend'),KIARA_V2_AI_MODE:'openai',OPENAI_API_KEY:'injected-never-live',KIARA_OPENAI_BUDGET_USD:'1',KIARA_MODEL:'gpt-6-sol',KIARA_REVIEW_MODEL:'gpt-6-sol',KIARA_REASONING_EFFORT:'low'});globalThis.fetch=async()=>{throw Error('No live model calls');};try{await run();}finally{await closeV2Store();globalThis.fetch=native;for(const k of Object.keys(process.env))if(!(k in env))delete process.env[k];Object.assign(process.env,env);await rm(dir,{recursive:true,force:true});}}
async function send(c:WorkspaceCommand,actor=a){return command(actor,{idempotencyKey:randomUUID(),expectedVersion:(await snapshot(actor)).version,command:c});}
async function queue(){const r=await send({type:'message.send',text:'Explain the missing agreement notice evidence.'});return String(r.result.runId);}
const raw=()=>readWorkspace(a.tenantId);
async function cancel(id:string,actor=a,version?:number){return transactWorkspace(a.tenantId,s=>applyRunControlCommand(s,actor,{type:'run.cancel',runId:id,expectedRecordVersion:version??runVersion(controlledRun(s,id)),reason:'Stop this investigation; I will review the evidence separately.'}));}
function fake(hook?:(stage:'answer'|'review')=>Promise<void>){let calls=0,counts=0;const adapter:ConversationProvider={count:async()=>{counts++;return 1000;},create:async request=>{calls++;const input=JSON.parse(String(request.input)),stage=input.answer?'review':'answer';await hook?.(stage);return {id:'synthetic-response-'+calls,model:String(request.model),status:'completed',output_text:JSON.stringify(stage==='answer'?{paragraphs:[{id:'p1',kind:'limitation',text:'No agreement evidence was supplied.',citationIds:[]}]}:{safe:true,checks:[{paragraphId:'p1',supported:true,reason:'Explicit evidence gap.'}]}),usage:{input_tokens:100,output_tokens:20,total_tokens:120,input_tokens_details:{cached_tokens:0,cache_write_tokens:0},output_tokens_details:{reasoning_tokens:0}}};}};return {adapter,get calls(){return calls;},get counts(){return counts;}};}

test('queued cancellation survives restart, leaves user message and makes zero provider/count/reservation calls',()=>isolated(async()=>{const id=await queue(),f=fake();const result=await cancel(id);assert.equal(result.result.status,'canceled');await closeV2Store();assert.equal((await processConversationRun(a.tenantId,id,{provider:f.adapter})).status,'canceled');assert.equal(f.calls+f.counts,0);assert.equal((await globalSpendStatus()).request_count,0);const s=await raw();assert.equal(s.messages.length,1);assert.equal(s.events.filter(e=>e.type==='conversation.run_cancel_requested').length,1);assert.equal(s.outbox.find(o=>o.aggregateId===id)!.status,'canceled');assert.equal((await pendingConversationRuns(a.tenantId)).length,0);}));
test('only initiating owner with current membership and exact run version may cancel',()=>isolated(async()=>{const id=await queue(),other={...a,actorId:'other'};await snapshot(other);await assert.rejects(cancel(id,other),{code:'RUN_OWNER_REQUIRED'});await assert.rejects(cancel(id,a,999),{code:'VERSION_CONFLICT'});await transactWorkspace(a.tenantId,s=>{s.memberships.find(m=>m.actorId===a.actorId)!.revokedAt=new Date().toISOString();});await assert.rejects(cancel(id),{code:'MEMBERSHIP_REVOKED'});assert.equal(controlledRun(await raw(),id).status,'queued');}));
test('cancel during asynchronous count prevents reservation and first generation',()=>isolated(async()=>{const id=await queue(),f=fake();f.adapter.count=async()=>{await cancel(id);return 1000;};const result=await processConversationRun(a.tenantId,id,{provider:f.adapter});assert.equal(result.status,'canceled');assert.equal(f.calls,0);assert.equal((await globalSpendStatus()).request_count,0);assert.equal((await raw()).messages.length,1);}));
test('cancel in flight waits for actual usage, discards result and never starts review',()=>isolated(async()=>{const id=await queue(),f=fake(async stage=>{assert.equal(stage,'answer');assert.equal((await cancel(id)).result.status,'cancel_requested');const pending=await processConversationRun(a.tenantId,id,{provider:f.adapter});assert.equal(pending.status,'cancel_requested');assert.equal((await globalSpendStatus()).unknown_charges,0);});const result=await processConversationRun(a.tenantId,id,{provider:f.adapter});assert.equal(result.status,'canceled');assert.equal(result.cancellation?.accounting,'settled');assert.equal(f.calls,1);const ledger=await globalSpendStatus();assert.ok(ledger.actual_spent_usd>0);assert.equal(ledger.reserved_usd+ledger.unknown_charges,0);const s=await raw();assert.equal(s.messages.length,1);assert.equal((s.receipts['conversation-run:'+id].result.run as any).attempts[0].output,null);await processConversationRun(a.tenantId,id,{provider:f.adapter});assert.equal(f.calls,1);}));
test('cancel during final review preserves both actual charges without attaching an answer',()=>isolated(async()=>{const id=await queue(),f=fake(async stage=>{if(stage==='review')await cancel(id);});const result=await processConversationRun(a.tenantId,id,{provider:f.adapter});assert.equal(result.status,'canceled');assert.equal(result.cancellation?.accounting,'settled');assert.equal(f.calls,2);assert.equal((await globalSpendStatus()).request_count,2);assert.equal((await raw()).messages.length,1);}));
test('lost provider response after cancellation remains unknown and cannot be retried',()=>isolated(async()=>{const id=await queue(),f=fake(async()=>{await cancel(id);throw Error('Response lost after dispatch');});const result=await processConversationRun(a.tenantId,id,{provider:f.adapter});assert.equal(result.status,'canceled');assert.equal(result.cancellation?.accounting,'unknown');assert.equal((await globalSpendStatus()).unknown_charges,1);await closeV2Store();await processConversationRun(a.tenantId,id,{provider:f.adapter});assert.equal(f.calls,1);assert.equal((await raw()).messages.length,1);}));
test('restart after cancellation of dispatched attempt waits until lease then reconciles unknown without dispatch',()=>isolated(async()=>{const id=await queue(),charge=randomUUID();await reserveGlobalSpend(charge,0.01);await transactWorkspace(a.tenantId,s=>{const r=controlledRun(s,id);r.status='running';r.leaseToken='interrupted';r.leaseUntil=Date.now()+60000;r.attempts.push({id:charge,status:'dispatched'});});await cancel(id);await closeV2Store();const f=fake();assert.equal((await processConversationRun(a.tenantId,id,{provider:f.adapter})).status,'cancel_requested');assert.equal((await globalSpendStatus()).inflight,1);await transactWorkspace(a.tenantId,s=>{controlledRun(s,id).leaseUntil=Date.now()-1;});const result=await processConversationRun(a.tenantId,id,{provider:f.adapter});assert.equal(result.status,'canceled');assert.equal(result.cancellation?.accounting,'unknown');assert.equal((await globalSpendStatus()).unknown_charges,1);assert.equal(f.calls+f.counts,0);assert.equal((await pendingConversationRuns(a.tenantId)).length,0);}));
test('prepared cancellation releases reservation and retires any not-yet-created reservation identity',()=>isolated(async()=>{for(const reserved of [true,false]){const id=await queue(),charge=randomUUID();if(reserved)await reserveGlobalSpend(charge,0.01);await transactWorkspace(a.tenantId,s=>{const r=controlledRun(s,id);r.status='running';r.leaseToken='prepared';r.leaseUntil=Date.now()+60000;r.attempts.push({id:charge,status:'prepared'});});await cancel(id);const f=fake();assert.equal((await processConversationRun(a.tenantId,id,{provider:f.adapter})).status,'canceled');assert.equal(f.calls+f.counts,0);assert.equal((await globalSpendStatus()).reserved_usd,0);await assert.rejects(reserveGlobalSpend(charge,0.01));}assert.equal((await globalSpendStatus()).unknown_charges,0);}));
test('query embedding submitted before cancellation owns its charge and no generation may start',()=>isolated(async()=>{const id=await queue(),charge=randomUUID();await reserveGlobalSpend(charge,0.00001);await transactWorkspace(a.tenantId,s=>{const r=controlledRun(s,id);r.status='running';r.leaseUntil=Date.now()+60000;s.receipts['embedding:query:'+id]={hash:'synthetic',result:{job:{id:charge,key:'query:'+id,status:'dispatched',leaseUntil:Date.now()+60000,recoveryPending:false}}};});await cancel(id);const f=fake();assert.equal((await processConversationRun(a.tenantId,id,{provider:f.adapter})).status,'cancel_requested');await transactWorkspace(a.tenantId,s=>{controlledRun(s,id).leaseUntil=Date.now()-1;});const done=await processConversationRun(a.tenantId,id,{provider:f.adapter});assert.equal(done.status,'canceled');assert.equal(done.cancellation?.accounting,'unknown');assert.equal((await globalSpendStatus()).unknown_charges,1);assert.equal(f.calls+f.counts,0);}));

test('real idempotent cancellation command replays once and source deletion clears cancellation reason',()=>isolated(async()=>{
 const document=await send({type:'document.add',title:'Cancellation evidence',body:'PRIVATE_CANCELLATION_CANARY notice terms.',authority:'draft'}),r=await send({type:'message.send',text:'Explain Cancellation evidence terms'}),id=String(r.result.runId),current=await snapshot(a),run=current.aiRuns.find(x=>x.id===id)!;const envelope={idempotencyKey:'explicit-stop',expectedVersion:current.version,command:{type:'run.cancel' as const,runId:id,expectedRecordVersion:run.version,reason:'PRIVATE_CANCELLATION_CANARY is no longer needed.'}};
 const first=await command(a,envelope);assert.equal(first.result.status,'canceled');assert.equal((await command(a,envelope)).replayed,true);assert.equal((await raw()).events.filter(x=>x.type==='conversation.run_cancel_requested').length,1);await send({type:'source.revoke',sourceId:String(document.result.sourceId),delete:true,reason:'Erase cancellation evidence'});const state=await raw();assert.equal(controlledRun(state,id).cancellation?.reason,'');assert.doesNotMatch(JSON.stringify(state.receipts),/PRIVATE_CANCELLATION_CANARY/);
}));
test('canceling a model work plan creates neither a proposed artifact nor an accepted matter',()=>isolated(async()=>{const c=await send({type:'conversation.create',title:'Plan to cancel',scope:{kind:'private',actorIds:[a.actorId]}}),r=await send({type:'message.send',conversationId:String(c.result.conversationId),text:'Prepare a work plan for our proposed vendor change'}),id=String(r.result.runId),f=fake(async()=>{await cancel(id);});assert.ok((await raw()).receipts['conversation-run:'+id].result.run);const result=await processConversationRun(a.tenantId,id,{provider:f.adapter});assert.equal(result.status,'canceled');const s=await snapshot(a);assert.equal(s.drafts.length+s.matters.length+s.actions.length,0);assert.equal(s.messages.filter(m=>m.role==='assistant').length,0);assert.equal(f.calls,1);}));
test('refs-only local processing waits for cancellation accounting and completes only after lease recovery',()=>isolated(async()=>{const {processLocalOutboxOnce,processConversationReference}=await import('../src/v2/orchestration/conversations'),id=await queue(),charge=randomUUID();await reserveGlobalSpend(charge,0.01);await transactWorkspace(a.tenantId,s=>{const r=controlledRun(s,id);r.status='running';r.leaseUntil=Date.now()+60000;r.attempts.push({id:charge,status:'dispatched'});});await cancel(id);const entry=(await raw()).outbox.find(o=>o.aggregateId===id)!,ref={tenantId:a.tenantId,aggregateId:id,outboxId:entry.id};assert.deepEqual(await processConversationReference(ref),{status:'cancel_requested'});const first=await processLocalOutboxOnce(a.tenantId);assert.equal(first.waiting,1);assert.equal((await raw()).outbox.find(o=>o.id===entry.id)!.status,'pending');await transactWorkspace(a.tenantId,s=>{controlledRun(s,id).leaseUntil=Date.now()-1;});await processLocalOutboxOnce(a.tenantId);assert.equal((await raw()).outbox.find(o=>o.id===entry.id)!.status,'canceled');assert.equal((await globalSpendStatus()).unknown_charges,1);}));

test('a late valid provider receipt after canceled lease recovery preserves metadata without clearing unknown charge',()=>isolated(async()=>{
 const id=await queue();let entered!:()=>void,release!:()=>void;const started=new Promise<void>(r=>{entered=r;}),wait=new Promise<void>(r=>{release=r;});const f=fake(async()=>{entered();await wait;});const running=processConversationRun(a.tenantId,id,{provider:f.adapter});await started;await cancel(id);await transactWorkspace(a.tenantId,s=>{controlledRun(s,id).leaseUntil=Date.now()-1;});assert.equal((await processConversationRun(a.tenantId,id,{provider:f.adapter})).status,'canceled');assert.equal((await globalSpendStatus()).unknown_charges,1);release();const result=await running;assert.equal(result.status,'canceled');assert.equal(result.cancellation?.accounting,'unknown');const attempt=(await raw()).receipts['conversation-run:'+id].result.run as any;assert.equal(attempt.attempts[0].status,'unknown');assert.equal(attempt.attempts[0].responseId,'synthetic-response-1');assert.match(attempt.attempts[0].responseHash,/^[a-f0-9]{64}$/);assert.ok(attempt.attempts[0].actualUsd>0);assert.equal(attempt.attempts[0].output,null);assert.equal((await globalSpendStatus()).unknown_charges,1);assert.equal(f.calls,1);assert.equal((await raw()).messages.length,1);
}));
test('revoked source hides cancellation free text but preserves safe accounting; deletion erases audit reason',()=>isolated(async()=>{
 const doc=await send({type:'document.add',title:'Cancellation private terms',body:'A confidential notice applies.',authority:'draft'}),r=await send({type:'message.send',text:'Explain Cancellation private terms'}),id=String(r.result.runId);await transactWorkspace(a.tenantId,s=>applyRunControlCommand(s,a,{type:'run.cancel',runId:id,expectedRecordVersion:runVersion(controlledRun(s,id)),reason:'REVOKED_REASON_CANARY: the confidential fee is unnecessary.'}));assert.match((await snapshot(a)).aiRuns.find(x=>x.id===id)!.cancellation!.reason,/REVOKED_REASON_CANARY/);let s=await raw(),event=s.events.find(e=>e.type==='conversation.run_cancel_requested')!;assert.ok(event.provenance.sourceIds.includes(String(doc.result.sourceId)));await send({type:'source.revoke',sourceId:String(doc.result.sourceId),reason:'Remove evidence access'});let visible=await snapshot(a);assert.equal(visible.aiRuns.find(x=>x.id===id)!.cancellation?.reason,'');assert.equal(visible.aiRuns.find(x=>x.id===id)!.cancellation?.accounting,'settled');assert.doesNotMatch(JSON.stringify(visible),/REVOKED_REASON_CANARY/);await send({type:'source.revoke',sourceId:String(doc.result.sourceId),delete:true,reason:'Delete evidence'});s=await raw();event=s.events.find(e=>e.id===event.id)!;assert.equal(event.detail,'');assert.doesNotMatch(JSON.stringify(s.receipts),/REVOKED_REASON_CANARY/);
}));

test('real query embedding canceled in flight settles usage, clears vector, skips search and generation',()=>isolated(async()=>{
 process.env.KIARA_V2_RETRIEVAL_MODE='atlas';process.env.KIARA_V2_ATLAS_URI='mongodb://injected-never-connected';process.env.KIARA_V2_ATLAS_SEARCH_INDEX='synthetic-keyword';process.env.KIARA_V2_ATLAS_VECTOR_INDEX='synthetic-vector';await send({type:'document.add',title:'Embedding notice',body:'Notice is required before processor changes.',authority:'draft'});const result=await send({type:'message.send',text:'Explain Embedding notice'}),id=String(result.result.runId),f=fake();let embeddings=0,searches=0;const done=await processConversationRun(a.tenantId,id,{provider:f.adapter,hybridAdapter:{upsert:async()=>{},present:async(_tenant,ids)=>ids,ids:async()=>[],remove:async()=>{},search:async()=>{searches++;return {keywordIds:[],vectorIds:[]};}},embeddingProvider:{create:async request=>{embeddings++;await cancel(id);return {model:request.model,data:[{index:0,embedding:Array(1536).fill(0.01)}],usage:{prompt_tokens:request.input.length,total_tokens:request.input.length},_request_id:'canceled-query-receipt'};}}});assert.equal(done.status,'canceled');assert.equal(done.cancellation?.accounting,'settled');assert.equal(embeddings,1);assert.equal(searches+f.calls+f.counts,0);const job=(await raw()).receipts['embedding:query:'+id].result.job as any;assert.equal(job.vector,null);assert.equal(job.requestId,'canceled-query-receipt');assert.ok((await globalSpendStatus()).actual_spent_usd>0);assert.equal((await globalSpendStatus()).unknown_charges,0);
}));


test('a valid response receipt survives ledger outage and restart without another provider attempt',()=>isolated(async()=>{
 const id=await queue(),path=join(process.env.KIARA_GLOBAL_BUDGET_DIR!,'provider-spend.json');let ledger='';const f=fake(async()=>{await cancel(id);ledger=await readFile(path,'utf8');await writeFile(path,'intentionally invalid synthetic ledger');});assert.equal((await processConversationRun(a.tenantId,id,{provider:f.adapter})).status,'cancel_requested');let at=(await raw()).receipts['conversation-run:'+id].result.run as any;assert.equal(at.attempts[0].responseId,'synthetic-response-1');assert.match(at.attempts[0].responseHash,/^[a-f0-9]{64}$/);assert.ok(at.attempts[0].observedUsage.estimatedUsd>0);assert.equal(at.attempts[0].output,null);assert.equal(at.attempts[0].status,'dispatched');await writeFile(path,ledger);await transactWorkspace(a.tenantId,s=>{controlledRun(s,id).leaseUntil=Date.now()-1;});await closeV2Store();const result=await processConversationRun(a.tenantId,id,{provider:f.adapter});assert.equal(result.status,'canceled');assert.equal(result.cancellation?.accounting,'unknown');assert.equal((await globalSpendStatus()).unknown_charges,1);assert.equal(f.calls,1);at=(await raw()).receipts['conversation-run:'+id].result.run as any;assert.ok(at.attempts[0].observedUsage.estimatedUsd>0);
}));
