import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {command,snapshot} from '../src/v2/service';
import {closeV2Store,readWorkspace,transactWorkspace} from '../src/v2/store';
import {processRetentionReference,type RetentionProcessor} from '../src/v2/orchestration/retention';
import {processLocalOutboxOnce} from '../src/v2/orchestration/conversations';
import {processWithdrawalReference} from '../src/v2/orchestration/withdrawal';
import {dispatchOutbox} from '../src/v2/orchestration/temporal';
import {processArtifactReference} from '../src/v2/orchestration/artifacts';
import {retainIntakeOriginal} from '../src/v2/artifact-intake';
import {readOriginal} from '../src/v2/objects';
import {processIndexReference} from '../src/v2/orchestration/indexing';
import type {ActorContext,WorkspaceCommand} from '../src/v2/contracts';
const actor:ActorContext={tenantId:'retention-worker-test',actorId:'owner',mode:'local_demo',expiresAt:Date.now()+3600000,bootstrapRoles:['member','admin']};
async function isolated(run:()=>Promise<void>){const env={...process.env},fetch=globalThis.fetch,dir=await mkdtemp(join(tmpdir(),'kiara-retention-worker-'));for(const k of Object.keys(process.env))if(/KIARA|MONGO|VERCEL|OPENAI|RESEND|TEMPORAL/.test(k))delete process.env[k];Object.assign(process.env,{KIARA_V2_DATA_DIR:dir,KIARA_V2_AI_MODE:'local'});globalThis.fetch=async()=>{throw Error('No live provider calls');};try{await run();}finally{await closeV2Store();globalThis.fetch=fetch;for(const k of Object.keys(process.env))if(!(k in env))delete process.env[k];Object.assign(process.env,env);await rm(dir,{recursive:true,force:true});}}
async function send(c:WorkspaceCommand){return command(actor,{idempotencyKey:randomUUID(),expectedVersion:(await snapshot(actor)).version,command:c});}
async function deletion(){const added=await send({type:'document.add',title:'Private fixture',body:'Do not retain this synthetic text.',authority:'draft'});await send({type:'source.revoke',sourceId:String(added.result.sourceId),reason:'Attributable synthetic deletion',delete:true});const queued=await readWorkspace(actor.tenantId),withdrawal=queued.outbox.find(o=>o.kind==='source_withdrawal')!;await processWithdrawalReference({tenantId:actor.tenantId,aggregateId:withdrawal.aggregateId,outboxId:withdrawal.id});await transactWorkspace(actor.tenantId,s=>{s.outbox.find(o=>o.id===withdrawal.id)!.status='dispatched';});const s=await readWorkspace(actor.tenantId),job=s.deletionJobs![0],entry=s.outbox.find(o=>o.kind==='retention_cleanup')!;assert.equal(entry.commandId,job.id);return {tenantId:actor.tenantId,aggregateId:job.id,outboxId:entry.id};}
const pending=(jobId:string,overrides:Partial<Awaited<ReturnType<RetentionProcessor>>>={}):Awaited<ReturnType<RetentionProcessor>>=>({jobId,applicationCleanupComplete:false,originalsPending:1,operationalExceptions:0,nextOriginalDueAt:null,failures:[],externalBackupErasureVerified:false,...overrides});

test('deletion atomically retains a refs-only outbox and the local worker completes real application cleanup',()=>isolated(async()=>{
 const ref=await deletion();assert.deepEqual(await processRetentionReference(ref),{status:'complete',nextCheckMs:0});const result=await processLocalOutboxOnce(actor.tenantId);assert.equal(result.completed,1);const s=await readWorkspace(actor.tenantId);assert.equal(s.outbox.find(o=>o.id===ref.outboxId)!.status,'dispatched');assert.equal(s.sources[0].text,'');assert.equal(s.documents[0].body,'');assert.equal(s.deletionJobs![0].backupStatus,'operator_verification_required');
}));
test('retention rejects cross-job or modified references and never exposes object identities in progress',()=>isolated(async()=>{
 const ref=await deletion();let calls=0;const processor:RetentionProcessor=async(_tenant,id)=>{calls++;return pending(id,{nextOriginalDueAt:new Date(Date.now()+30*86400000).toISOString(),failures:['PRIVATE_ADAPTER_DETAIL']});};assert.deepEqual(await processRetentionReference(ref,processor),{status:'waiting',nextCheckMs:6*3600000});await assert.rejects(processRetentionReference({...ref,aggregateId:'foreign-job'},processor),{code:'OUTBOX_NOT_FOUND'});await assert.rejects(processRetentionReference({...ref,privateText:'Never enter workflow history'} as typeof ref,processor),{code:'INVALID_WORKFLOW_REFERENCE'});assert.equal(calls,1);await assert.rejects(processRetentionReference(ref,async()=>pending('wrong-job')),{code:'RETENTION_IDENTITY_MISMATCH'});
}));
test('future holds use bounded durable wakeups and local deferred work resumes after settlement',()=>isolated(async()=>{
 const ref=await deletion();assert.deepEqual(await processRetentionReference(ref,async(_t,id)=>pending(id,{nextOriginalDueAt:new Date(Date.now()+30*86400000).toISOString()})),{status:'waiting',nextCheckMs:24*3600000});assert.deepEqual(await processRetentionReference(ref,async(_t,id)=>pending(id,{operationalExceptions:1})),{status:'waiting',nextCheckMs:6*3600000});
 let complete=false,calls=0;const deferred=new Map<string,number>(),processor=async()=>{calls++;return {status:complete?'complete' as const:'waiting' as const,nextCheckMs:complete?0:6*3600000};};assert.deepEqual(await processLocalOutboxOnce(actor.tenantId,{deferred,retentionProcessor:processor}),{completed:0,waiting:1});await processLocalOutboxOnce(actor.tenantId,{deferred,retentionProcessor:processor});assert.equal(calls,1);assert.equal((await readWorkspace(actor.tenantId)).outbox.find(o=>o.id===ref.outboxId)!.status,'pending');complete=true;deferred.set(ref.outboxId,Date.now()-1);assert.deepEqual(await processLocalOutboxOnce(actor.tenantId,{deferred,retentionProcessor:processor}),{completed:1,waiting:0});assert.equal(calls,2);
}));
test('managed lost-ack replay preserves deletion identity and only sends opaque references',()=>isolated(async()=>{
 const ref=await deletion(),calls:{ref:unknown;kind:unknown}[]=[];let lose=true;const dispatcher={signal:async(r:typeof ref,kind:unknown)=>{calls.push({ref:r,kind});if(lose)throw Error('Acknowledgement lost after scheduling');}};await assert.rejects(dispatchOutbox(actor.tenantId,dispatcher));assert.equal((await readWorkspace(actor.tenantId)).outbox.find(o=>o.id===ref.outboxId)!.status,'pending');lose=false;assert.equal((await dispatchOutbox(actor.tenantId,dispatcher)).dispatched,1);assert.deepEqual(calls,[{ref,kind:'retention_cleanup'},{ref,kind:'retention_cleanup'}]);await transactWorkspace(actor.tenantId,s=>{s.outbox.find(o=>o.id===ref.outboxId)!.status='canceled';});let runs=0;assert.deepEqual(await processRetentionReference(ref,async(_t,id)=>{runs++;return pending(id);}),{status:'complete',nextCheckMs:0});assert.equal(runs,0);
}));

test('an unavailable earlier effect cannot starve later deletion cleanup in the local worker',()=>isolated(async()=>{
 const ref=await deletion();await transactWorkspace(actor.tenantId,s=>{s.outbox.unshift({id:'unavailable-effect',tenantId:s.tenantId,kind:'effect_reconcile',aggregateId:'effect',commandId:'intent',owner:'v2',status:'pending',createdAt:new Date().toISOString()});});let calls=0;const deferred=new Map<string,number>();assert.deepEqual(await processLocalOutboxOnce(actor.tenantId,{deferred,effectProcessor:async()=>{calls++;throw Error('Original adapter is no longer configured');}}),{completed:1,waiting:1});const s=await readWorkspace(actor.tenantId);assert.equal(s.outbox.find(o=>o.id===ref.outboxId)!.status,'dispatched');assert.equal(s.outbox[0].status,'pending');await processLocalOutboxOnce(actor.tenantId,{deferred,effectProcessor:async()=>{calls++;throw Error('Still unavailable');}});assert.equal(calls,1);
}));

async function intake(){const version=(await snapshot(actor)).version,result=await retainIntakeOriginal(actor,'synthetic-upload',Buffer.from('Abandoned synthetic original.'),version),s=await readWorkspace(actor.tenantId),entry=s.outbox.find(o=>o.kind==='artifact_cleanup')!;return {ref:{tenantId:actor.tenantId,aggregateId:entry.aggregateId,outboxId:entry.id},original:result.reference};}
test('abandoned intake retains its cleanup owner and the actual local worker purges expired encrypted bytes',()=>isolated(async()=>{
 const {ref,original}=await intake();const waiting=await processArtifactReference(ref);assert.equal(waiting.status,'waiting');assert.ok(waiting.nextCheckMs>23*3600000&&waiting.nextCheckMs<=24*3600000);assert.equal((await readOriginal(actor.tenantId,original)).toString(),'Abandoned synthetic original.');await transactWorkspace(actor.tenantId,s=>{(s.receipts[`artifact-intake:${ref.aggregateId}`].result.intake as {expiresAt:string}).expiresAt=new Date(0).toISOString();});assert.deepEqual(await processLocalOutboxOnce(actor.tenantId),{completed:1,waiting:0});await assert.rejects(readOriginal(actor.tenantId,original),{code:'ENOENT'});assert.equal((await readWorkspace(actor.tenantId)).outbox[0].status,'dispatched');
}));
test('an original write with no retained acknowledgement stays pending for explicit reconciliation',()=>isolated(async()=>{
 const {ref}=await intake();await transactWorkspace(actor.tenantId,s=>{const row=s.receipts[`artifact-intake:${ref.aggregateId}`].result.intake as {reference:string|null;expiresAt:string;status:string};row.reference=null;row.expiresAt=new Date(0).toISOString();row.status='staging';});assert.deepEqual(await processArtifactReference(ref),{status:'waiting',nextCheckMs:6*3600000});const deferred=new Map<string,number>();assert.deepEqual(await processLocalOutboxOnce(actor.tenantId,{deferred}),{completed:0,waiting:1});const s=await readWorkspace(actor.tenantId);assert.equal(s.outbox[0].status,'pending');assert.equal((s.receipts[`artifact-intake:${ref.aggregateId}`].result.intake as {failureCode:string}).failureCode,'ORIGINAL_REFERENCE_RECONCILIATION_REQUIRED');
}));
test('artifact workflow dispatch carries no original reference and validates scoped intake identity before processing',()=>isolated(async()=>{
 const {ref}=await intake();const sent:unknown[]=[];await dispatchOutbox(actor.tenantId,{signal:async(r,kind)=>{sent.push({ref:r,kind});}});assert.deepEqual(sent,[{ref,kind:'artifact_cleanup'}]);let calls=0;await assert.rejects(processArtifactReference({...ref,aggregateId:'other-intake'},async()=>{calls++;return {complete:true,nextCheckMs:0};}),{code:'OUTBOX_NOT_FOUND'});assert.equal(calls,0);assert.deepEqual(await processArtifactReference(ref,async()=>({complete:false,nextCheckMs:Infinity})),{status:'waiting',nextCheckMs:6*3600000});
}));

test('standing-policy index jobs dispatch only opaque references and terminal uncertainty never retries provider work',()=>isolated(async()=>{
 Object.assign(process.env,{KIARA_V2_RETRIEVAL_MODE:'atlas',KIARA_V2_ATLAS_URI:'mongodb://injected-no-network',KIARA_V2_ATLAS_SEARCH_INDEX:'keyword',KIARA_V2_ATLAS_VECTOR_INDEX:'vector',KIARA_V2_INDEX_POLICY:JSON.stringify([{tenantId:actor.tenantId,enabled:true,actorIds:[actor.actorId],scopeKinds:['team'],maxChunksPerJob:10,validUntil:new Date(Date.now()+3600000).toISOString()}])});
 await send({type:'document.add',title:'Synthetic eligible record',body:'Only this accepted record is indexed.',authority:'draft'});const s=await readWorkspace(actor.tenantId),entry=s.outbox.find(o=>o.kind==='index_maintenance')!;assert.ok(entry);const ref={tenantId:actor.tenantId,aggregateId:entry.aggregateId,outboxId:entry.id},calls:unknown[]=[];
 await dispatchOutbox(actor.tenantId,{signal:async(r,kind)=>{calls.push({ref:r,kind});}});assert.deepEqual(calls,[{ref,kind:'index_maintenance'}]);const view=(status:'queued'|'running'|'complete'|'blocked'|'unknown',id=ref.aggregateId)=>({id,status,recordCount:1,chunkCount:1,reason:'PRIVATE_PROVIDER_DETAIL',nextAttemptAt:null,updatedAt:new Date().toISOString()});
 assert.deepEqual(await processIndexReference(ref,async()=>view('unknown')),{status:'complete',nextCheckMs:0});assert.deepEqual(await processIndexReference(ref,async()=>({...view('queued'),nextAttemptAt:new Date(Date.now()+3600000).toISOString()})),{status:'waiting',nextCheckMs:5*60000});await assert.rejects(processIndexReference(ref,async()=>view('complete','wrong')),{code:'INDEX_IDENTITY_MISMATCH'});await assert.rejects(processIndexReference({...ref,aggregateId:'foreign'},async()=>view('complete')),{code:'OUTBOX_NOT_FOUND'});
 await transactWorkspace(actor.tenantId,state=>{state.outbox[0].status='pending';});const deferred=new Map<string,number>();let attempts=0;await processLocalOutboxOnce(actor.tenantId,{deferred,indexProcessor:async()=>{attempts++;return {status:'waiting',nextCheckMs:60000};}});await processLocalOutboxOnce(actor.tenantId,{deferred,indexProcessor:async()=>{attempts++;return {status:'complete',nextCheckMs:0};}});assert.equal(attempts,1);deferred.set(ref.outboxId,0);await processLocalOutboxOnce(actor.tenantId,{deferred,indexProcessor:async()=>({status:'complete',nextCheckMs:0})});assert.equal((await readWorkspace(actor.tenantId)).outbox[0].status,'dispatched');
}));
