import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createHmac,randomUUID} from 'node:crypto';
import {closeV2Store,readWorkspace,transactWorkspace} from '../src/v2/store';
import {command,snapshot} from '../src/v2/service';
import {canRead} from '../src/v2/authority';
import {currentEvidenceLineage,currentSourceEvidence} from '../src/v2/source-lifecycle';
import {ingestProviderObject,acceptWebhook} from '../src/v2/integrations/intake';
import {readGitHubPullRequest,readSlackThread,type ProviderObject} from '../src/v2/integrations/read';
import type {Installation} from '../src/v2/integrations/config';
import type {ActorContext,WorkspaceCommand} from '../src/v2/contracts';
const actor:ActorContext={tenantId:'source-history',actorId:'owner',mode:'authenticated',expiresAt:Date.now()+3600000};
const common={tenantId:actor.tenantId,actorId:'integration',enabled:true,tokenEnv:'TEST_CHRONOLOGY_TOKEN',webhookSecretEnv:'TEST_CHRONOLOGY_SECRET',scope:{kind:'team' as const,actorIds:['owner','integration']}};
const drive:Installation={...common,id:'drive',provider:'drive',resources:['file:agreement']},github:Installation={...common,id:'github',provider:'github',resources:['acme/product'],providerInstallationId:'777'},slack:Installation={...common,id:'slack',provider:'slack',resources:['C1'],slackTeamId:'T1'};
async function isolated(run:()=>Promise<void>){const env={...process.env},fetch=globalThis.fetch,dir=await mkdtemp(join(tmpdir(),'kiara-source-chronology-'));for(const key of Object.keys(process.env))if(/^(KIARA|MONGO|VERCEL|OPENAI|RESEND|TEMPORAL)/.test(key))delete process.env[key];Object.assign(process.env,{KIARA_V2_DATA_DIR:dir,KIARA_V2_AI_MODE:'local',KIARA_V2_INSTALLATIONS:JSON.stringify([drive,github,slack]),TEST_CHRONOLOGY_TOKEN:'synthetic-token',TEST_CHRONOLOGY_SECRET:'synthetic-secret'});globalThis.fetch=async()=>{throw Error('Live provider access forbidden');};try{await transactWorkspace(actor.tenantId,s=>{for(const id of ['owner','integration'])s.memberships.push({actorId:id,roles:id==='owner'?['member','business_owner','fact_owner','admin','legal_reviewer']:['integration'],version:1,expiresAt:null,revokedAt:null,matterIds:null,entityIds:null});});await run();}finally{await closeV2Store();globalThis.fetch=fetch;for(const key of Object.keys(process.env))if(!(key in env))delete process.env[key];Object.assign(process.env,env);await rm(dir,{recursive:true,force:true});}}
async function send(c:WorkspaceCommand){return command(actor,{idempotencyKey:randomUUID(),expectedVersion:(await readWorkspace(actor.tenantId)).version,command:c});}
const value=(revision:string,text='Agreement evidence',overrides:Partial<ProviderObject>={}):ProviderObject=>({objectId:'agreement',revision,title:'Agreement',text,url:null,occurredAt:'2026-09-27T12:00:00Z',...overrides});
const event=async(i:Installation,v:ProviderObject):Promise<Record<string,unknown>>=>ingestProviderObject(i,randomUUID(),v);
const json=(v:unknown)=>new Response(JSON.stringify(v));
async function confirmObjective(objective:string){const c=await send({type:'conversation.create',title:'Scoped source review',scope:drive.scope}),conversation=c.snapshot.conversations.at(-1)!;const proposed=await send({type:'fact.propose',predicate:'business_objective',value:objective,conversationId:conversation.id,practice:'planned'}),fact=proposed.snapshot.facts.at(-1)!;await send({type:'fact.confirm',factId:fact.id,expectedRecordVersion:fact.version,expectedOriginVersion:fact.originVersion});}
function signed(payload:unknown){const raw=Buffer.from(JSON.stringify(payload)),ts=String(Math.floor(Date.now()/1000));return {raw,headers:new Headers({'x-slack-request-timestamp':ts,'x-slack-signature':'v0='+createHmac('sha256','synthetic-secret').update(`v0:${ts}:`).update(raw).digest('hex')})};}

test('late ordered Drive revision preserves current proposal, approvals and one current queue',()=>isolated(async()=>{
 const newer=await event(drive,value('12','Current clause'));const f=await send({type:'fact.propose',predicate:'notice',value:'Current clause',sourceIds:[String(newer.sourceId)]}),fact=f.snapshot.facts[0];await send({type:'fact.confirm',factId:fact.id,expectedRecordVersion:fact.version,expectedOriginVersion:fact.originVersion});await confirmObjective('Current source review');const m=await send({type:'matter.create',title:'Review notice',objective:'Current source review',scope:drive.scope}),matter=m.snapshot.matters[0];await transactWorkspace(actor.tenantId,s=>{s.matters[0].sourceIds=[String(newer.sourceId)];s.matters[0].provenance.sourceIds=[String(newer.sourceId)];});const p=await send({type:'matter.prepare',matterId:matter.id,expectedRecordVersion:matter.version}),proposal=p.snapshot.proposals[0];await send({type:'approval.record',proposalId:proposal.id,proposalHash:proposal.contentHash,capacity:'business',validUntil:new Date(Date.now()+3600000).toISOString()});const before=await readWorkspace(actor.tenantId),current=before.sources.find(x=>x.id===newer.sourceId)!;
 const older=await event(drive,value('9','Historical clause',{occurredAt:'2030-01-01T00:00:00Z'}));const after=await readWorkspace(actor.tenantId);assert.equal(older.observationState,'historical');assert.deepEqual(after.sources.find(x=>x.id===current.id),current);assert.deepEqual(after.proposals,before.proposals);assert.deepEqual(after.approvals,before.approvals);assert.deepEqual(after.outbox,before.outbox);assert.ok(canRead(after,actor,after.sources.find(x=>x.id===older.sourceId)!));assert.equal(currentSourceEvidence(after,after.sources.find(x=>x.id===older.sourceId)!),false);assert.equal(currentEvidenceLineage(after,after.proposals[0]),true);
}));
test('newer source invalidates dependent proposal but preserves scoped historical access and blocks old fact confirmation',()=>isolated(async()=>{
 const old=await event(drive,value('1','Earlier clause'));const f=await send({type:'fact.propose',predicate:'notice',value:'Earlier clause',sourceIds:[String(old.sourceId)]}),fact=f.snapshot.facts[0];await confirmObjective('Keep audit access');const m=await send({type:'matter.create',title:'Historical review',objective:'Keep audit access',scope:drive.scope});await transactWorkspace(actor.tenantId,s=>{s.matters[0].sourceIds=[String(old.sourceId)];s.matters[0].provenance.sourceIds=[String(old.sourceId)];});await send({type:'matter.prepare',matterId:String(m.result.matterId),expectedRecordVersion:m.snapshot.matters[0].version});await event(drive,value('2','Updated clause'));const state=await readWorkspace(actor.tenantId),source=state.sources.find(x=>x.id===old.sourceId)!;assert.equal(source.observation?.state,'historical');assert.equal(source.status,'active');assert.deepEqual(source.scope,drive.scope);assert.ok(source.installationGrant);assert.equal(state.proposals[0].status,'invalidated');assert.ok(canRead(state,actor,state.matters[0]));assert.ok((await snapshot(actor)).sources.some(x=>x.id===source.id));await assert.rejects(send({type:'fact.confirm',factId:fact.id,expectedRecordVersion:fact.version,expectedOriginVersion:fact.originVersion}),{code:'SOURCE_NOT_CURRENT'});await assert.rejects(send({type:'fact.propose',predicate:'stale',value:'Do not reuse',sourceIds:[source.id]}),{code:'SOURCE_NOT_CURRENT'});
}));
test('same revision conflicting bytes rejects atomically; identical delivery aliases do not duplicate sources or effects',()=>isolated(async()=>{
 const object=value('3','Exact bytes');await event(drive,object);const before=await readWorkspace(actor.tenantId);const replay=await event(drive,object);assert.equal(replay.duplicate,true);assert.equal((await readWorkspace(actor.tenantId)).sources.length,1);assert.deepEqual((await readWorkspace(actor.tenantId)).outbox,before.outbox);await assert.rejects(event(drive,{...object,text:'Different bytes'}),{code:'SOURCE_REVISION_CONFLICT'});const after=await readWorkspace(actor.tenantId);assert.deepEqual(after.sources,before.sources);assert.deepEqual(after.outbox,before.outbox);assert.equal(after.events.length,before.events.length);
}));
test('opaque GitHub heads conflict regardless event time and only stable scoped read selects a current head',()=>isolated(async()=>{
 const pull=(sha:string,time:string)=>({number:7,title:'AI experiment',body:'Synthetic only',state:'closed',merged:true,merged_at:null,head:{sha},base:{sha:'base'},updated_at:time});const payload=(p:ReturnType<typeof pull>)=>({installation:{id:777},repository:{full_name:'acme/product'},action:'closed',pull_request:p});const hook=async(p:ReturnType<typeof pull>)=>{const raw=Buffer.from(JSON.stringify(payload(p)));return acceptWebhook(github.id,new Headers({'x-github-event':'pull_request','x-hub-signature-256':'sha256='+createHmac('sha256','synthetic-secret').update(raw).digest('hex')}),raw);};
 const first=pull('new','2026-09-27T12:00:00Z'),late=pull('old','2020-01-01T00:00:00Z');await hook(first);await hook(late);let s=await readWorkspace(actor.tenantId);assert.equal(s.sources.length,2);assert.ok(s.sources.every(x=>x.observation?.state==='conflicting'&&!currentSourceEvidence(s,x)));const queues=s.outbox.length;const object=await readGitHubPullRequest(github,'acme/product',7,async()=>json(first));await event(github,object);s=await readWorkspace(actor.tenantId);assert.equal(s.sources.length,2);assert.equal(s.sources.filter(x=>currentSourceEvidence(s,x)).length,1);assert.match(s.sources.find(x=>currentSourceEvidence(s,x))!.text,/does not establish deployment/);assert.equal(s.facts.length,0);assert.equal(s.outbox.length,queues+1);await event(github,object);assert.equal((await readWorkspace(actor.tenantId)).outbox.length,s.outbox.length);await assert.rejects(readGitHubPullRequest(github,'acme/product',7,(()=>{let n=0;return async()=>json(n++?late:first);})()),{code:'PROVIDER_REVISION_CHANGED'});
}));
test('withdrawn current object cannot fall back, late events cannot restore it, historical source remains audit-readable',()=>isolated(async()=>{
 const first=await event(drive,value('1','Earlier evidence')),current=await event(drive,value('2','Current evidence'));await send({type:'source.revoke',sourceId:String(current.sourceId),reason:'Operator withdrew object'});let s=await readWorkspace(actor.tenantId);assert.ok(s.sources.every(x=>!currentSourceEvidence(s,x)));assert.ok(canRead(s,actor,s.sources.find(x=>x.id===first.sourceId)!));await assert.rejects(event(drive,value('3','Late unseen bytes',{confirmedCurrent:true})),{code:'SOURCE_OBJECT_WITHDRAWN'});await assert.rejects(event(drive,value('1','Earlier evidence')),{code:'SOURCE_OBJECT_WITHDRAWN'});s=await readWorkspace(actor.tenantId);assert.equal(s.sources.length,2);assert.equal(s.sources.find(x=>x.id===current.sourceId)!.status,'revoked');
}));
test('verified ordered provider read cannot regress a known newer revision',()=>isolated(async()=>{
 await event(drive,value('100','Known latest'));await assert.rejects(event(drive,value('99','Stale read',{confirmedCurrent:true})),{code:'PROVIDER_REVISION_REGRESSION'});const s=await readWorkspace(actor.tenantId);assert.equal(s.sources.length,1);assert.ok(currentSourceEvidence(s,s.sources[0]));
}));
test('Slack edits order per message, late old edit does not displace newer evidence',()=>isolated(async()=>{
 const message=(edited:string,text:string)=>({type:'event_callback',team_id:'T1',event_id:randomUUID(),event:{type:'message',channel:'C1',subtype:'message_changed',message:{ts:'1770000000.001',user:'U1',text,edited:{ts:edited}}}});for(const p of [message('1770000002.000001','Current'),message('1770000001.999999','Historical')]){const r=signed(p);await acceptWebhook(slack.id,r.headers,r.raw);}const s=await readWorkspace(actor.tenantId);assert.equal(s.sources.length,2);assert.match(s.sources.find(x=>currentSourceEvidence(s,x))!.text,/Current/);assert.equal(s.outbox.length,1);
}));
test('complete Slack thread refresh after deletion preserves withdrawn message fence and replay does not revoke fresh snapshot',()=>isolated(async()=>{
 const root={ts:'1770000000.001',user:'U1',text:'Root'},reply={ts:'1770000001.001',user:'U2',text:'Removed reply'};let messages=[root,reply];const get=()=>readSlackThread(slack,'C1',root.ts,async()=>json({ok:true,messages}));await event(slack,await get());const r=signed({type:'event_callback',team_id:'T1',event_id:randomUUID(),event:{type:'message',channel:'C1',subtype:'message_deleted',deleted_ts:reply.ts}});await acceptWebhook(slack.id,r.headers,r.raw);messages=[root];const next=await event(slack,await get());let s=await readWorkspace(actor.tenantId);assert.equal(s.sources.length,2);assert.equal(s.sources[0].status,'revoked');assert.ok(currentSourceEvidence(s,s.sources.find(x=>x.id===next.sourceId)!));await acceptWebhook(slack.id,r.headers,r.raw);s=await readWorkspace(actor.tenantId);assert.ok(currentSourceEvidence(s,s.sources.find(x=>x.id===next.sourceId)!));const late=signed({type:'event_callback',team_id:'T1',event_id:randomUUID(),event:{type:'message',channel:'C1',thread_ts:root.ts,...reply}});await assert.rejects(acceptWebhook(slack.id,late.headers,late.raw),{code:'SOURCE_OBJECT_WITHDRAWN'});s=await readWorkspace(actor.tenantId);assert.ok(currentSourceEvidence(s,s.sources.find(x=>x.id===next.sourceId)!));let calls=0;await assert.rejects(readSlackThread(slack,'C1',root.ts,async()=>json({ok:true,messages:++calls===1?[root]:[root,reply]})),{code:'PROVIDER_REVISION_CHANGED'});
}));

test('current evidence recheck rejects newly historical dependencies while new retrieval excludes old facts and prompt history',()=>isolated(async()=>{
 const {retrieveConversationEvidence,recheckEvidence}=await import('../src/v2/retrieval');const {authorizedHybridChunks}=await import('../src/v2/hybrid');
 const first=await event(drive,value('1','PRIOR_CANARY notice is 90 days'));const f=await send({type:'fact.propose',predicate:'notice_days',value:'PRIOR_CANARY 90 days',sourceIds:[String(first.sourceId)]}),fact=f.snapshot.facts[0];await send({type:'fact.confirm',factId:fact.id,expectedRecordVersion:fact.version,expectedOriginVersion:fact.originVersion});const asked=await send({type:'message.send',text:'Explain agreement notice days'});let s=await readWorkspace(actor.tenantId),c=s.conversations.find(x=>x.id===asked.result.conversationId)!,user=s.messages.find(m=>m.role==='user')!;const packet=retrieveConversationEvidence(s,actor,c,user.id);assert.ok(packet.evidence.some(e=>e.quote.includes('PRIOR_CANARY')));
 await transactWorkspace(actor.tenantId,state=>{const old=structuredClone(state.messages.find(m=>m.role==='user')!);old.id=randomUUID();old.text='PRIOR_HISTORY_CANARY';old.provenance.sourceIds=[String(first.sourceId)];state.messages.unshift(old);});await event(drive,value('2','CURRENT_CANARY notice is 30 days'));s=await readWorkspace(actor.tenantId);assert.throws(()=>recheckEvidence(s,actor,c.id,packet),{code:'EVIDENCE_CHANGED'});c=s.conversations.find(x=>x.id===c.id)!;const current=retrieveConversationEvidence(s,actor,c,user.id);assert.ok(current.evidence.some(e=>e.quote.includes('CURRENT_CANARY')));assert.ok(!JSON.stringify(current).includes('PRIOR_CANARY'));assert.ok(!JSON.stringify(current).includes('PRIOR_HISTORY_CANARY'));assert.ok(!authorizedHybridChunks(s,actor).some(chunk=>chunk.text.includes('PRIOR_CANARY')));assert.equal(s.facts[0].status,'confirmed');assert.equal(currentEvidenceLineage(s,s.facts[0]),false);
}));


test('known deleted Slack message cannot reappear in a different verified thread snapshot or retained readable aggregate',()=>isolated(async()=>{
 const root={ts:'1770000000.001',user:'U1',text:'Root'},deleted={ts:'1770000001.001',user:'U2',text:'DELETED_CANARY'},later={ts:'1770000003.001',user:'U1',text:'Later message'};const object=await readSlackThread(slack,'C1',root.ts,async()=>json({ok:true,messages:[root,deleted]}));const original=await event(slack,object);const r=signed({type:'event_callback',team_id:'T1',event_id:randomUUID(),event:{type:'message',channel:'C1',subtype:'message_deleted',deleted_ts:deleted.ts}});await acceptWebhook(slack.id,r.headers,r.raw);const stale=await readSlackThread(slack,'C1',root.ts,async()=>json({ok:true,messages:[root,deleted,later]}));assert.notEqual(object.revision,stale.revision);await assert.rejects(event(slack,stale),{code:'INSTALLATION_REVOKED'});const state=await readWorkspace(actor.tenantId),retained=state.sources.find(x=>x.id===original.sourceId)!;retained.status='active';assert.equal(canRead(state,actor,retained),false);assert.equal(currentSourceEvidence(state,retained),false);assert.equal((await snapshot(actor)).sources.length,0);
}));

test('manual withdrawal of a signed message hides its existing active aggregate immediately',()=>isolated(async()=>{
 const root={ts:'1770000000.001',user:'U1',text:'Root'},reply={ts:'1770000001.001',user:'U2',text:'Withdraw me'};const aggregate=await event(slack,await readSlackThread(slack,'C1',root.ts,async()=>json({ok:true,messages:[root,reply]})));const request=signed({type:'event_callback',team_id:'T1',event_id:randomUUID(),event:{type:'message',channel:'C1',thread_ts:root.ts,...reply}});const message=await acceptWebhook(slack.id,request.headers,request.raw);assert.ok((await snapshot(actor)).sources.some(x=>x.id===aggregate.sourceId));await send({type:'source.revoke',sourceId:String(message.sourceId),reason:'Access removed'});const s=await readWorkspace(actor.tenantId),snapshotSource=s.sources.find(x=>x.id===aggregate.sourceId)!;assert.equal(snapshotSource.status,'active');assert.equal(canRead(s,actor,snapshotSource),false);assert.ok(!(await snapshot(actor)).sources.some(x=>x.id===aggregate.sourceId));
}));
test('historical Slack deletion relation is exact to installation, channel, revision and bytes',()=>isolated(async()=>{
 const {slackSnapshotIncludesSource,withdrawSourceObservation}=await import('../src/v2/source-lifecycle');const old=await event(slack,{objectId:'C1:message:1770000000.001',revision:'1770000000.001',title:'Slack evidence',text:JSON.stringify({channel:'C1',threadTs:'1770000000.001',user:'U1',text:'Old content'}),url:null,occurredAt:'2026-09-27T12:00:00Z'});await event(slack,{objectId:'C1:message:1770000000.001',revision:'1770000001.001',title:'Slack evidence',text:JSON.stringify({channel:'C1',threadTs:'1770000000.001',user:'U1',text:'New content'}),url:null,occurredAt:'2026-09-27T12:00:01Z'});const s=await readWorkspace(actor.tenantId),m=s.sources.find(x=>x.id===old.sourceId)!,snapshot={...m,externalId:'slack:C1:thread:1770000000.001',text:JSON.stringify({channel:'C1',threadTs:'1770000000.001',messages:[{ts:'1770000000.001',user:'U1',text:'Old content'}]})};assert.equal(slackSnapshotIncludesSource(s,snapshot,m),true);const latest={...snapshot,text:JSON.stringify({channel:'C1',threadTs:'1770000000.001',messages:[{ts:'1770000000.001',edited:'1770000001.001',user:'U1',text:'New content'}]})};assert.equal(slackSnapshotIncludesSource(s,latest,m),false);assert.equal(slackSnapshotIncludesSource(s,{...snapshot,externalId:'slack:C2:thread:1770000000.001'},m),false);assert.equal(slackSnapshotIncludesSource(s,{...snapshot,text:'malformed'},m),false);withdrawSourceObservation(s,s.sources[1]);assert.equal(slackSnapshotIncludesSource(s,latest,m),true);
}));

test('attributed current message deletion physically clears aggregate payload and leaves unrelated malformed evidence alone',()=>isolated(async()=>{
 const message={ts:'1770000000.001',user:'U1',text:'ERASE_AGGREGATE_CANARY'},request=signed({type:'event_callback',team_id:'T1',event_id:randomUUID(),event:{type:'message',channel:'C1',...message}}),accepted=await acceptWebhook(slack.id,request.headers,request.raw);const aggregate=await event(slack,await readSlackThread(slack,'C1',message.ts,async()=>json({ok:true,messages:[message]})));const unrelated=randomUUID();await transactWorkspace(actor.tenantId,s=>{const base=s.sources.find(x=>x.id===aggregate.sourceId)!;s.sources.push({...structuredClone(base),id:unrelated,externalId:'slack:C1:thread:1770000099.001',text:'UNRELATED_MALFORMED_CANARY'});});await send({type:'source.revoke',sourceId:String(accepted.sourceId),reason:'Delete this message payload',delete:true});const s=await readWorkspace(actor.tenantId);assert.equal(s.sources.find(x=>x.id===aggregate.sourceId)!.text,'');assert.equal(s.sources.find(x=>x.id===aggregate.sourceId)!.status,'deleted');assert.equal(s.sources.find(x=>x.id===unrelated)!.text,'UNRELATED_MALFORMED_CANARY');assert.ok(s.deletionJobs!.at(-1)!.records.some(x=>x.id===aggregate.sourceId));assert.ok(!s.deletionJobs!.at(-1)!.records.some(x=>x.id===unrelated));
}));
test('deleting only a historical message revision purges its matching snapshot while preserving newer thread bytes',()=>isolated(async()=>{
 const id='1770000000.001',old={ts:id,user:'U1',text:'Historical private bytes'},newer={ts:id,user:'U1',text:'Current independently reviewed bytes',edited:{ts:'1770000001.001'}};const object=(m:typeof old|typeof newer)=>({objectId:`C1:message:${id}`,revision:'edited'in m?m.edited.ts:m.ts,title:'Slack evidence',text:JSON.stringify({channel:'C1',threadTs:id,user:m.user,text:m.text}),url:null,occurredAt:'2026-09-27T12:00:00Z'});const oldSource=await event(slack,object(old)),oldThread=await event(slack,await readSlackThread(slack,'C1',id,async()=>json({ok:true,messages:[old]})));await event(slack,object(newer));const newThread=await event(slack,await readSlackThread(slack,'C1',id,async()=>json({ok:true,messages:[newer]})));await send({type:'source.revoke',sourceId:String(oldSource.sourceId),reason:'Delete historical revision only',delete:true});const s=await readWorkspace(actor.tenantId);assert.equal(s.sources.find(x=>x.id===oldThread.sourceId)!.text,'');const retained=s.sources.find(x=>x.id===newThread.sourceId)!;assert.match(retained.text,/Current independently reviewed bytes/);assert.equal(retained.status,'active');assert.ok(currentSourceEvidence(s,retained));assert.ok(canRead(s,actor,retained));
}));
