import test,{beforeEach,afterEach} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {command,snapshot} from '../src/v2/service';
import {processConversationRun,type ConversationProvider} from '../src/v2/ai';
import {closeV2Store,readWorkspace,transactWorkspace} from '../src/v2/store';
import {retrievalStrategyBoost,applyStrategyCommand,strategyViews} from '../src/v2/strategies';
import type {ActorContext,Role,WorkspaceCommand} from '../src/v2/contracts';
const keys=['KIARA_V2_DATA_DIR','KIARA_GLOBAL_BUDGET_DIR','MONGODB_URI','VERCEL','KIARA_V2_AI_MODE','KIARA_V2_RETRIEVAL_MODE','OPENAI_API_KEY','KIARA_OPENAI_BUDGET_USD','KIARA_MODEL','KIARA_REVIEW_MODEL','KIARA_REASONING_EFFORT'];const old=Object.fromEntries(keys.map(k=>[k,process.env[k]]));let dir:string;
beforeEach(async()=>{dir=await mkdtemp(join(tmpdir(),'kiara-strategies-'));process.env.KIARA_V2_DATA_DIR=join(dir,'data');process.env.KIARA_GLOBAL_BUDGET_DIR=join(dir,'budget');delete process.env.MONGODB_URI;delete process.env.VERCEL;process.env.KIARA_V2_AI_MODE='local';process.env.KIARA_V2_RETRIEVAL_MODE='local';process.env.OPENAI_API_KEY='mock-only';process.env.KIARA_OPENAI_BUDGET_USD='1';process.env.KIARA_MODEL='gpt-6-sol';process.env.KIARA_REVIEW_MODEL='gpt-6-sol';process.env.KIARA_REASONING_EFFORT='low';});afterEach(async()=>{await closeV2Store();for(const k of keys){if(old[k]===undefined)delete process.env[k];else process.env[k]=old[k];}await rm(dir,{recursive:true,force:true});});
const actor=(actorId='author',roles:Role[]=['member','admin','evaluator','legal_reviewer','business_owner']):ActorContext=>({tenantId:'strategy-test',actorId,mode:'local_demo',expiresAt:Date.now()+3600000,bootstrapRoles:roles});const a=()=>actor(),e=()=>actor('evaluator',['member','evaluator']),o=()=>actor('owner',['member','business_owner','legal_reviewer']);
async function send(c:WorkspaceCommand,who=a()){const s=await snapshot(who);return command(who,{idempotencyKey:randomUUID(),expectedVersion:s.version,command:c});}
const until=()=>new Date(Date.now()+3600000).toISOString();
async function retrieval(){await snapshot(e());await snapshot(o());const wrong=(await send({type:'document.add',title:'Explain section 5.2',body:'See section 5.2 in another agreement.',authority:'draft'})).snapshot.documents.at(-1)!;const right=(await send({type:'document.add',title:'Agreement',body:'5.2 Notice\nA notice is required before renewal.',authority:'draft'})).snapshot.documents.at(-1)!;const cr=(await send({type:'conversation.create',title:'Find provision',scope:{kind:'team',actorIds:[]}})).snapshot.conversations[0];const ans=await send({type:'message.send',conversationId:cr.id,text:'Explain section 5.2'}),m=ans.snapshot.messages.at(-1)!,target=ans.snapshot.strategies.targets.find(t=>t.id===m.id)!;assert.equal(m.citations[0].sourceId,wrong.sourceId);const f=await send({type:'feedback.record',subjectKind:'message',subjectId:m.id,expectedRecordVersion:m.version,subjectHash:target.hash,category:'retrieval_miss',detail:'The specifically requested provision should rank first.',expectedDocumentId:right.id});const feedback=f.snapshot.strategies.feedback.at(-1)!;const p=await send({type:'strategy.propose',feedbackId:feedback.id,expectedFeedbackVersion:feedback.version,title:'Prefer exact clause heading',rationale:'An exact requested clause heading should outrank a repeated title.'});return {c:cr,wrong,right,candidate:p.snapshot.strategies.candidates.at(-1)!};}
async function shadow(candidateId:string){let c=(await snapshot(e())).strategies.candidates.find(c=>c.id===candidateId)!;const evaluated=await send({type:'strategy.evaluate',candidateId,expectedRecordVersion:c.version},e());c=evaluated.snapshot.strategies.candidates.find(c=>c.id===candidateId)!;assert.equal(c.evaluation!.candidateFailures,0);assert.equal(c.evaluation!.originalImproved,true);const r=await send({type:'strategy.shadow',candidateId,expectedRecordVersion:c.version,evaluationHash:c.evaluationHash!,validUntil:until()},o());return r.snapshot.strategies.candidates.find(c=>c.id===candidateId)!;}
async function promote(id:string){const c=(await snapshot(o())).strategies.candidates.find(c=>c.id===id)!;return send({type:'strategy.promote',candidateId:id,expectedRecordVersion:c.version,evaluationHash:c.evaluationHash!,shadowHash:c.shadowHash},o());}

test('real frozen ranking replay requires three people, protected holdouts, shadow then exact controlled adoption',async()=>{const {c,right,wrong,candidate}=await retrieval();await assert.rejects(send({type:'strategy.evaluate',candidateId:candidate.id,expectedRecordVersion:candidate.version}),{code:'INDEPENDENT_EVALUATOR_REQUIRED'});let prepared=await shadow(candidate.id);const authorView=(await snapshot(a())).strategies.candidates[0],evalView=(await snapshot(e())).strategies.candidates[0];assert.ok(authorView.evaluation!.withheldHoldoutCount>0);assert.equal(authorView.evaluation!.cases.some(c=>c.group==='holdout'),false);assert.equal(evalView.evaluation!.cases.some(c=>c.group==='holdout'),false);assert.equal(authorView.evaluation!.corpusHash,evalView.evaluation!.corpusHash);assert.ok(!JSON.stringify(authorView).includes('parenthetical-heading'));await assert.rejects(promote(candidate.id),{code:'SHADOW_REVIEW_REQUIRED'});const baseline=await send({type:'message.send',conversationId:c.id,text:'Explain section 5.2'});assert.equal(baseline.snapshot.messages.at(-1)!.citations[0].sourceId,wrong.sourceId);prepared=(await snapshot(o())).strategies.candidates[0];assert.equal(prepared.shadowCount,1);assert.equal(prepared.shadowChangedCount,1);await assert.rejects(send({type:'strategy.promote',candidateId:candidate.id,expectedRecordVersion:prepared.version,evaluationHash:prepared.evaluationHash!,shadowHash:prepared.shadowHash},a()),{code:'INDEPENDENT_OWNER_REQUIRED'});await promote(candidate.id);const changed=await send({type:'message.send',conversationId:c.id,text:'Explain section 5.2'});assert.equal(changed.snapshot.messages.at(-1)!.citations[0].sourceId,right.sourceId);assert.equal(changed.snapshot.facts.length,0);assert.equal(changed.snapshot.approvals.length,0);assert.equal(changed.snapshot.actions.length,0);});

test('promotion binds the inspected shadow hash; rollback removes actual ranking behavior and identifies affected input',async()=>{const {c,candidate,wrong}=await retrieval();await shadow(candidate.id);await send({type:'message.send',conversationId:c.id,text:'Explain section 5.2'});let view=(await snapshot(o())).strategies.candidates[0];await assert.rejects(send({type:'strategy.promote',candidateId:candidate.id,expectedRecordVersion:view.version,evaluationHash:view.evaluationHash!,shadowHash:'outdated'},o()),{code:'SHADOW_REVIEW_REQUIRED'});await promote(candidate.id);await send({type:'message.send',conversationId:c.id,text:'Explain section 5.2'});view=(await snapshot(o())).strategies.candidates[0];assert.ok(view.affectedRecordIds.length>0);await send({type:'strategy.rollback',candidateId:candidate.id,expectedRecordVersion:view.version,reason:'Revert the bounded ranking policy pending broader comparison'},o());const restored=await send({type:'message.send',conversationId:c.id,text:'Explain section 5.2'});assert.equal(restored.snapshot.messages.at(-1)!.citations[0].sourceId,wrong.sourceId);});

test('scoped policy cannot affect a private conversation and owner revocation removes its effect immediately',async()=>{const {c,candidate,right}=await retrieval();await shadow(candidate.id);await send({type:'message.send',conversationId:c.id,text:'Explain section 5.2'});await promote(candidate.id);const privateConversation=(await send({type:'conversation.create',title:'Private unrelated work',scope:{kind:'private',actorIds:['author']}})).snapshot.conversations.at(-1)!;let s=await readWorkspace(a().tenantId);assert.equal(retrievalStrategyBoost(s,a(),privateConversation,right,'Explain section 5.2'),0);assert.equal(retrievalStrategyBoost(s,a(),s.conversations.find(x=>x.id===c.id)!,right,'Explain section 5.2'),30);await send({type:'membership.revoke',actorId:'owner'});s=await readWorkspace(a().tenantId);assert.equal(retrievalStrategyBoost(s,a(),s.conversations.find(x=>x.id===c.id)!,right,'Explain section 5.2'),0);});

test('classification is explicit and does not promote factual or legal corrections into strategy authority',async()=>{const r=await send({type:'message.send',text:'What is the next step?'}),m=r.snapshot.messages.at(-1)!,t=r.snapshot.strategies.targets.find(t=>t.id===m.id)!;const f=await send({type:'feedback.record',subjectKind:'message',subjectId:m.id,expectedRecordVersion:m.version,subjectHash:t.hash,category:'fact_correction',detail:'This statement needs source-owner confirmation.'}),feedback=f.snapshot.strategies.feedback[0];assert.equal(f.snapshot.facts.length,0);await assert.rejects(send({type:'strategy.propose',feedbackId:feedback.id,expectedFeedbackVersion:feedback.version,title:'Unqualified factual rule',rationale:'Should not become executable'}),{code:'EXECUTABLE_FEEDBACK_REQUIRED'});const ordinary=actor('ordinary',['member']);await snapshot(ordinary);await assert.rejects(send({type:'feedback.record',subjectKind:'message',subjectId:m.id,expectedRecordVersion:m.version,subjectHash:t.hash,category:'legal_judgment',detail:'This is legal clearance'},ordinary));});

function badDraft():ConversationProvider{return {count:async()=>1000,create:async r=>{const d=JSON.parse(String(r.input)),value=d.items?{safe:true,checks:d.items.map((x:{id:string})=>({paragraphId:x.id,supported:true,reason:'Injected support result for guard testing only.'}))}:{title:'Short notice',body:'Give notice before renewal.',changes:['Shortened the wording.'],questions:[],tasks:[],citationIds:[d.evidence.find((e:{id:string})=>e.id.endsWith(':draft-basis')).id]};return {id:randomUUID(),status:'completed',model:String(r.model),output_text:JSON.stringify(value),usage:{input_tokens:100,output_tokens:100,total_tokens:200,input_tokens_details:{cached_tokens:0,cache_write_tokens:0},output_tokens_details:{reasoning_tokens:0}}};}};}
async function requestDraft(id:string){const r=await send({type:'message.send',conversationId:id,text:'Make it shorter'});return processConversationRun(a().tenantId,String(r.result.runId),{provider:badDraft()});}
test('draft preservation comparison shadows actual generated text before adoption blocks a numeric omission',async()=>{await snapshot(e());await snapshot(o());const d=(await send({type:'document.add',title:'Notice text',body:'Give 30 days notice before renewal.',authority:'draft'})).snapshot.documents[0],c=(await send({type:'conversation.create',title:'Shorten notice',scope:{kind:'team',actorIds:[]}})).snapshot.conversations[0];await send({type:'conversation.select_document',conversationId:c.id,expectedConversationVersion:c.version,documentRevisionId:d.id,expectedContentHash:d.contentHash});process.env.KIARA_V2_AI_MODE='openai';assert.equal((await requestDraft(c.id)).status,'complete');let s=await snapshot(a());const draft=s.drafts[0],t=s.strategies.targets.find(t=>t.kind==='draft'&&t.id===draft.id)!;const f=await send({type:'feedback.record',subjectKind:'draft',subjectId:draft.id,expectedRecordVersion:draft.version,subjectHash:t.hash,category:'drafting_fidelity',detail:'Meaning-preserving shortening dropped the explicit 30-day notice value.'});const feedback=f.snapshot.strategies.feedback[0],p=await send({type:'strategy.propose',feedbackId:feedback.id,expectedFeedbackVersion:feedback.version,title:'Preserve material numbers',rationale:'Numeric/date tokens must not disappear in meaning-preserving shortening.'});const id=p.snapshot.strategies.candidates[0].id;await shadow(id);assert.equal((await requestDraft(c.id)).status,'complete');await promote(id);const result=await requestDraft(c.id);assert.equal(result.status,'blocked');assert.equal(result.reason,'DRAFT_STRATEGY_REVIEW_REQUIRED');s=await snapshot(a());assert.equal(s.drafts.length,2);assert.equal(s.documents.length,1);assert.ok(s.strategies.candidates[0].affectedRecordIds.includes(result.id));assert.equal(s.strategies.candidates[0].evaluation!.cases.some(x=>x.group==='holdout'),false);});

test('feedback and strategy authority follow the current conversation container, including source-free outputs',async()=>{const {c,candidate,right}=await retrieval();await shadow(candidate.id);await send({type:'message.send',conversationId:c.id,text:'Explain section 5.2'});await promote(candidate.id);const before=(await snapshot(a())).strategies,feedback=before.feedback[0],target=before.targets.find(t=>t.id===feedback.subjectId)!;await transactWorkspace(a().tenantId,s=>{const origin=s.conversations.find(x=>x.id===c.id)!;origin.scope={kind:'private',actorIds:['evaluator']};origin.version++;});const view=(await snapshot(a())).strategies;assert.equal(view.targets.some(t=>t.id===target.id),false);assert.equal(view.feedback.length,0);assert.equal(view.candidates.length,0);await assert.rejects(send({type:'feedback.record',subjectKind:target.kind,subjectId:target.id,expectedRecordVersion:target.version,subjectHash:target.hash,category:'wording_preference',detail:'Must not use a detached output'}),{code:'FEEDBACK_TARGET_UNAVAILABLE'});const state=await readWorkspace(a().tenantId);assert.equal(retrievalStrategyBoost(state,a(),state.conversations.find(x=>x.id===c.id)!,right,'Explain section 5.2'),0);});

test('actual model evidence ordering changes only in local retrieval; hybrid selection retains its supplied order',async()=>{const {c,candidate,right,wrong}=await retrieval();await shadow(candidate.id);await send({type:'message.send',conversationId:c.id,text:'Explain section 5.2'});await promote(candidate.id);const {retrieveConversationEvidence}=await import('../src/v2/retrieval');const s=await readWorkspace(a().tenantId),conversation=s.conversations.find(x=>x.id===c.id)!,user=s.messages.filter(x=>x.role==='user'&&x.conversationId===c.id).at(-1)!;const local=retrieveConversationEvidence(s,a(),conversation,user.id);assert.equal(local.evidence.find(e=>e.kind==='document')!.sourceId,right.sourceId);const hybrid=retrieveConversationEvidence(s,a(),conversation,user.id,{hybrid:true,chunks:[{kind:'document',id:wrong.id,offset:0},{kind:'document',id:right.id,offset:0}]});assert.equal(hybrid.evidence.find(e=>e.kind==='document')!.sourceId,wrong.sourceId);});

test('policy expiry after model count stops provider dispatch and preserves the original decision history',async()=>{const {c,candidate}=await retrieval();await shadow(candidate.id);await send({type:'message.send',conversationId:c.id,text:'Explain section 5.2'});await promote(candidate.id);process.env.KIARA_V2_AI_MODE='openai';const queued=await send({type:'message.send',conversationId:c.id,text:'Explain section 5.2'});let calls=0;const provider:ConversationProvider={count:async()=>{await transactWorkspace(a().tenantId,s=>{s.strategyCandidates![0].validUntil=new Date(Date.now()-1).toISOString();});return 1000;},create:async()=>{calls++;throw new Error('Must not dispatch');}};const result=await processConversationRun(a().tenantId,String(queued.result.runId),{provider});assert.equal(result.status,'blocked');assert.equal(result.reason,'STRATEGY_POLICY_CHANGED');assert.equal(calls,0);assert.equal((await snapshot(a())).strategies.candidates[0].current,false);});

test('feedback inherits direct fact lineage of replay documents and cannot reveal original labels to another audience',async()=>{const {candidate,right}=await retrieval();const s=await readWorkspace(a().tenantId);{const fact={id:'private-origin',tenantId:s.tenantId,version:1,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),scope:{kind:'private' as const,actorIds:['author']},provenance:{actorId:'author',sourceIds:[],description:'Private source-free assertion'},ownerId:'author',observedAt:new Date().toISOString(),originVersion:1,conversationId:s.conversations[0].id,entityId:s.entityId,predicate:'private_basis',value:'secret',status:'confirmed' as const,reuse:'company' as const,practice:'planned' as const,confirmedBy:'author',confirmedAt:new Date().toISOString(),validFrom:null,validUntil:null,supersedesId:null};s.facts.push(fact);s.documents.find(d=>d.id===right.id)!.provenance.factIds=[fact.id];s.strategyCandidates=[];s.strategyFeedback=[];}const target=strategyViews(s,a()).targets.find(t=>t.kind==='message')!;applyStrategyCommand(s,a(),{type:'feedback.record',subjectKind:'message',subjectId:target.id,expectedRecordVersion:target.version,subjectHash:target.hash,category:'retrieval_miss',detail:'Review actual document ranking',expectedDocumentId:right.id});assert.ok(strategyViews(s,a()).feedback[0].provenance.factIds!.includes('private-origin'));assert.equal(strategyViews(s,o()).feedback.length,0);assert.equal(candidate.key,'exact_clause_reference');});

test('literal guard preserves percent units and does not claim semantic equivalence',async()=>{const {preservesMaterialValues}=await import('../src/v2/strategy-algorithms');assert.equal(preservesMaterialValues({kind:'fidelity',instruction:'Make it shorter',before:'Limit 25% of fees.',after:'Limit 25 of fees.'}),false);assert.equal(preservesMaterialValues({kind:'fidelity',instruction:'Change the limit to 25 dollars',before:'Limit 25% of fees.',after:'Limit 25 dollars.'}),true);});

test('new evidence used only during shadow cannot authorize promotion after withdrawal',async()=>{const {c,candidate}=await retrieval();await shadow(candidate.id);const extra=(await send({type:'document.add',title:'New shadow-only agreement',body:'5.2 Additional notice requirements.',authority:'draft'})).snapshot.documents.at(-1)!;await send({type:'message.send',conversationId:c.id,text:'Explain section 5.2'});const reviewed=(await snapshot(o())).strategies.candidates[0];assert.equal(reviewed.shadowCount,1);await send({type:'source.revoke',sourceId:extra.sourceId,reason:'Remove newly supplied comparison evidence'});const after=(await snapshot(o())).strategies.candidates[0];assert.equal(after.shadowCount,0);assert.notEqual(after.shadowHash,reviewed.shadowHash);await assert.rejects(send({type:'strategy.promote',candidateId:candidate.id,expectedRecordVersion:after.version,evaluationHash:after.evaluationHash!,shadowHash:reviewed.shadowHash},o()),{code:'SHADOW_REVIEW_REQUIRED'});});

test('promoted authority stops when a shadow-only dependency changes',async()=>{const {c,candidate,right}=await retrieval();await shadow(candidate.id);const extra=(await send({type:'document.add',title:'Shadow comparison',body:'Additional context.',authority:'draft'})).snapshot.documents.at(-1)!;await send({type:'message.send',conversationId:c.id,text:'Explain section 5.2'});await promote(candidate.id);await send({type:'source.revoke',sourceId:extra.sourceId,reason:'Withdraw comparison'});const s=await readWorkspace(a().tenantId);assert.equal(retrievalStrategyBoost(s,a(),s.conversations.find(x=>x.id===c.id)!,right,'Explain section 5.2'),0);assert.equal((await snapshot(o())).strategies.candidates[0].current,false);});

test('protected holdout rows remain server-only for every UI actor, including an evaluator who later authors',async()=>{const {candidate}=await retrieval();await shadow(candidate.id);const feedback=(await snapshot(e())).strategies.feedback[0];const result=await send({type:'strategy.propose',feedbackId:feedback.id,expectedFeedbackVersion:feedback.version,title:'A separate bounded candidate',rationale:'No holdout labels were exposed'},e());for(const who of [a(),e(),o()]){const view=(await snapshot(who)).strategies;assert.equal(view.candidates.some(c=>c.evaluation?.cases.some(x=>x.group==='holdout')),false);assert.ok(!JSON.stringify(view).includes('parenthetical-heading'));}assert.equal(result.snapshot.strategies.candidates.length,2);});
