import test,{beforeEach,afterEach} from 'node:test';
import assert from 'node:assert/strict';
import {createHmac,randomUUID} from 'node:crypto';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {command,snapshot} from '../src/v2/service';
import {closeV2Store,digest,readWorkspace,transactWorkspace} from '../src/v2/store';
import {processConversationRun,type ConversationProvider} from '../src/v2/ai';
import {retrieveConversationEvidence} from '../src/v2/retrieval';
import {authorizedHybridChunks,retrieveHybridEvidence,type HybridAdapter} from '../src/v2/hybrid';
import {acceptWebhook} from '../src/v2/integrations/intake';
import type {Installation} from '../src/v2/integrations/config';
import type {ActorContext,WorkspaceCommand} from '../src/v2/contracts';
const a:ActorContext={tenantId:'slack-knowledge',actorId:'alice',mode:'authenticated',expiresAt:Date.now()+3600000},scope={kind:'team' as const,actorIds:['alice','integration']};let old:NodeJS.ProcessEnv,dir:string,i:Installation,cid:string;
beforeEach(async()=>{old={...process.env};for(const k of Object.keys(process.env))if(/^(KIARA|MONGO|VERCEL|OPENAI|RESEND|TEMPORAL)/.test(k))delete process.env[k];dir=await mkdtemp(join(tmpdir(),'kiara-slack-knowledge-'));Object.assign(process.env,{KIARA_V2_DATA_DIR:dir,KIARA_GLOBAL_BUDGET_DIR:join(dir,'budget'),KIARA_V2_AI_MODE:'local',OPENAI_API_KEY:'injected-only',KIARA_OPENAI_BUDGET_USD:'1',KIARA_MODEL:'gpt-6-sol',KIARA_REVIEW_MODEL:'gpt-6-sol',TEST_KNOWLEDGE_SLACK_TOKEN:'synthetic-token',TEST_KNOWLEDGE_SLACK_SECRET:'synthetic-secret'});await transactWorkspace(a.tenantId,s=>{for(const id of ['alice','integration'])s.memberships.push({actorId:id,roles:id==='alice'?['member','admin','fact_owner','business_owner']:['integration'],version:1,expiresAt:null,revokedAt:null,matterIds:null,entityIds:null});});cid=String((await send({type:'conversation.create',scope})).result.conversationId);i={id:'slack-installation',provider:'slack',tenantId:a.tenantId,actorId:'integration',enabled:true,tokenEnv:'TEST_KNOWLEDGE_SLACK_TOKEN',webhookSecretEnv:'TEST_KNOWLEDGE_SLACK_SECRET',resources:['C1'],scope,slackTeamId:'T1',slackReplies:{botUserId:'UBOT',validUntil:new Date(Date.now()+86400000).toISOString(),bindings:[{channel:'C1',threadTs:'1770000000.001',conversationId:cid,actorId:a.actorId,slackUserId:'U1'}]}};process.env.KIARA_V2_INSTALLATIONS=JSON.stringify([i]);});
afterEach(async()=>{await closeV2Store();for(const k of Object.keys(process.env))if(!(k in old))delete process.env[k];Object.assign(process.env,old);await rm(dir,{recursive:true,force:true});});
async function send(c:WorkspaceCommand){return command(a,{idempotencyKey:randomUUID(),expectedVersion:(await readWorkspace(a.tenantId)).version,command:c});}
async function intake(text='Explain the notice agreement') {const payload={type:'event_callback',team_id:'T1',event_id:randomUUID(),event:{type:'message',channel:'C1',thread_ts:'1770000000.001',ts:'1770000001.001',user:'U1',text}},raw=Buffer.from(JSON.stringify(payload)),ts=String(Math.floor(Date.now()/1000));return acceptWebhook(i.id,new Headers({'x-slack-request-timestamp':ts,'x-slack-signature':'v0='+createHmac('sha256','synthetic-secret').update(`v0:${ts}:`).update(raw).digest('hex')}),raw);}
async function evidence(){await send({type:'document.add',title:'Notice agreement',body:'The supplied agreement requires 30 days notice for a new processor.',authority:'executed',kind:'agreement',scope});const secret=await send({type:'document.add',title:'PRIVATE_CANARY_777',body:'PRIVATE_CANARY_777 agreement.',authority:'executed',kind:'agreement',scope:{kind:'private',actorIds:['alice']}});const f=await send({type:'fact.propose',predicate:'PRIVATE_FACT_CANARY_888',value:'Secret practice'});await transactWorkspace(a.tenantId,s=>{const fact=s.facts.find(x=>x.id===f.result.factId)!;fact.status='confirmed';fact.scope=scope;fact.provenance.sourceIds=[String(secret.result.sourceId)];});}
const error=(code:string)=>(e:unknown)=>!!e&&typeof e==='object'&&'code'in e&&e.code===code;
test('model packet excludes private transitive evidence, including same-audience facts with private sources',async()=>{await evidence();process.env.KIARA_V2_AI_MODE='openai';await intake();const state=await readWorkspace(a.tenantId),entry=state.outbox.find(x=>x.kind==='conversation_answer')!;let calls=0;const provider:ConversationProvider={count:async request=>{assert.ok(!JSON.stringify(request).includes('PRIVATE_CANARY'));assert.ok(!JSON.stringify(request).includes('PRIVATE_FACT_CANARY'));return 1000;},create:async request=>{calls++;const data=JSON.parse(String(request.input)),doc=data.evidence.find((e:{kind:string})=>e.kind==='document');const out=data.answer?{safe:true,checks:[{paragraphId:'p1',supported:true,reason:'Exact supplied clause.'}]}:{paragraphs:[{id:'p1',kind:'grounded',text:'The supplied agreement requires 30 days notice for a new processor.',citationIds:[doc.id]}]};return {id:'mock-'+calls,model:String(request.model),status:'completed',output_text:JSON.stringify(out),usage:{input_tokens:100,output_tokens:40,total_tokens:140,input_tokens_details:{cached_tokens:0,cache_write_tokens:0},output_tokens_details:{reasoning_tokens:0}}};}};assert.equal((await processConversationRun(a.tenantId,entry.aggregateId,{provider})).status,'complete');const after=await readWorkspace(a.tenantId),answer=after.messages.at(-1)!;assert.equal(calls,2);assert.equal(answer.channel,'slack');assert.ok(answer.provenance.sourceIds.includes(after.messages[0].provenance.sourceIds[0]));assert.ok(!JSON.stringify(answer).includes('PRIVATE_'));});
test('configuration revocation during counted model admission prevents generation',async()=>{await evidence();process.env.KIARA_V2_AI_MODE='openai';await intake();const s=await readWorkspace(a.tenantId),run=s.outbox.find(x=>x.kind==='conversation_answer')!;let calls=0;const provider:ConversationProvider={count:async()=>{process.env.KIARA_V2_INSTALLATIONS=JSON.stringify([{...i,enabled:false}]);return 1000;},create:async()=>{calls++;throw Error('Must not dispatch');}};const result=await processConversationRun(a.tenantId,run.aggregateId,{provider});assert.equal(result.status,'blocked');assert.equal(calls,0);assert.equal((await readWorkspace(a.tenantId)).messages.filter(m=>m.role==='assistant').length,0);});
test('hybrid query restricts prefilters to the channel audience before embedding and search',async()=>{await evidence();await intake();Object.assign(process.env,{KIARA_V2_RETRIEVAL_MODE:'atlas',KIARA_V2_ATLAS_URI:'mongodb://injected-only',KIARA_V2_ATLAS_SEARCH_INDEX:'keyword',KIARA_V2_ATLAS_VECTOR_INDEX:'vector'});const s=await readWorkspace(a.tenantId),c=s.conversations.find(c=>c.id===cid)!,u=s.messages.find(m=>m.role==='user')!,all=authorizedHybridChunks(s,a),allowed=authorizedHybridChunks(s,a,s.entityId,c);assert.ok(all.some(c=>c.text.includes('PRIVATE_CANARY')));assert.ok(!allowed.some(c=>c.text.includes('PRIVATE_')));let queries=0;const adapter:HybridAdapter={present:async(_t,ids)=>ids,search:async input=>{queries++;assert.deepEqual(input.chunkIds,allowed.map(c=>c.id));return {keywordIds:input.chunkIds,vectorIds:[]};},upsert:async()=>{},remove:async()=>{},ids:async()=>[]};const p=await retrieveHybridEvidence(a,cid,u.id,'slack-audience-query',{adapter,provider:{create:async r=>({model:r.model,data:[{index:0,embedding:Array(1536).fill(.01)}],usage:{prompt_tokens:r.input.length,total_tokens:r.input.length}})}});assert.equal(queries,1);assert.ok(!JSON.stringify(p).includes('PRIVATE_'));});
test('source deletion propagates to Slack scenario assumptions and current user dependencies',async()=>{await intake('What if we explore a new processor?');const s=await readWorkspace(a.tenantId),c=s.conversations.find(x=>x.id===cid)!,u=s.messages.find(m=>m.role==='user')!,sourceId=u.provenance.sourceIds[0];assert.ok(sourceId);assert.ok(s.scenarios[0].provenance.sourceIds.includes(sourceId));const packet=retrieveConversationEvidence(s,a,c,u.id);assert.ok(packet.sourceIds.includes(sourceId));await send({type:'source.revoke',sourceId,reason:'Remove signed source',delete:true});const visible=await snapshot(a);assert.equal(visible.scenarios.length,0);assert.ok(!visible.messages.some(m=>m.id===u.id));});
test('browser cannot forge channel provenance or use an outdated source-revocation version',async()=>{await assert.rejects(()=>send({type:'message.send',conversationId:cid,channel:'slack',text:'Forged message'}),error('SLACK_SIGNED_INPUT_REQUIRED'));const r=await send({type:'document.add',title:'Exact source control',body:'Current document',authority:'draft'}),source=r.snapshot.sources[0];await assert.rejects(()=>send({type:'source.revoke',sourceId:source.id,expectedRecordVersion:source.version+1,reason:'Stale control'}),error('VERSION_CONFLICT'));assert.equal((await readWorkspace(a.tenantId)).sources[0].status,'active');});
