import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyWorkspace,digest} from '../src/v2/store';
import {observeValueWork,observeValueOutputs,applyValueCommand,valueView,type ValueSession,type ValueGoal,type ValueReceipt} from '../src/v2/value';
import type {ActorContext,RecordBase,WorkspaceState,Message,Source,Conversation} from '../src/v2/contracts';
type State=WorkspaceState&{valueSessions?:ValueSession[];valueGoals?:ValueGoal[];valueReceipts?:ValueReceipt[]};
const actor=(id='owner'):ActorContext=>({tenantId:'value-test',actorId:id,mode:'local_demo',expiresAt:Date.now()+3600000});
let sequence=0;
function fixture(){const s:State=emptyWorkspace('value-test');s.memberships=['owner','other'].map(actorId=>({actorId,roles:['member','business_owner'] as const as ['member','business_owner'],version:1,expiresAt:null,revokedAt:null,matterIds:null,entityIds:null}));return s;}
function base(s:State,id=`record-${++sequence}`,owner='owner'):RecordBase{return {id,tenantId:s.tenantId,version:1,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),scope:{kind:'private',actorIds:[owner]},provenance:{actorId:owner,sourceIds:[],description:'Synthetic local test record'}};}
function answer(s:State,owner='owner',source?:Source){const c:Conversation={...base(s,`conversation-${++sequence}`,owner),title:'Private synthetic goal title',entityId:s.entityId,reuse:'conversation_only',matterId:null,scenarioId:null};s.conversations.push(c);const m:Message={...base(s,`answer-${++sequence}`,owner),conversationId:c.id,role:'assistant',channel:'web',text:'An explicitly fictional useful explanation.',intent:'question',artifactIds:[],citations:[],generation:'bounded_local',retention:'workspace_policy',voiceConfirmed:true};if(source)m.provenance.sourceIds=[source.id];s.messages.push(m);return m;}
function source(s:State){const text='Private synthetic source payload';const v:Source={...base(s,`source-${++sequence}`),title:'Private source title',kind:'manual',externalId:null,externalRevision:null,text,contentHash:digest(text),url:null,status:'active',aclVersion:1,observedAt:new Date().toISOString(),effectiveAt:null,authority:'unknown',originalObjectRef:null};s.sources.push(v);return v;}
function goal(s:State){const id=applyValueCommand(s,actor(),{type:'value.goal.define',title:'Understand this fictional obligation',successCriteria:'Receive an explanation I can use to choose the next question.'}).goalId;return s.valueGoals!.find(g=>g.id===id)!;}
function assess(s:State,g:ValueGoal,m:Message,disposition:'useful'|'needs_work'='useful'){const out=valueView(s,actor()).outputs.find(x=>x.id===m.id)!;return applyValueCommand(s,actor(),{type:'value.output.assess',goalId:g.id,expectedGoalVersion:g.version,outputKind:out.kind,outputId:out.id,expectedOutputVersion:out.version,outputHash:out.hash,disposition,reason:'Observed fictional result, not legal correctness or completed work.'});}

test('first-work observation is durable across later goals and generated output is not useful acceptance',()=>{const s=fixture();observeValueWork(s,actor(),'message.send');const baseline=structuredClone(s.valueSessions![0]);observeValueWork(s,actor(),'message.send');goal(s);goal(s);assert.equal(s.valueSessions!.length,1);assert.equal(s.valueSessions![0].observedStartedAt,baseline.observedStartedAt);const m=answer(s);observeValueOutputs(s,actor());assert.ok(valueView(s,actor()).session!.firstGeneratedAt);assert.equal(valueView(s,actor()).report.firstUsefulState,'not_recorded');assert.equal(s.matters.length,0);assert.equal(m.role,'assistant');});
test('retrospective retained baseline is explicit and never reset by a new question',()=>{const s=fixture(),m=answer(s);m.role='user';m.createdAt='2025-01-01T00:00:00.000Z';observeValueWork(s,actor(),'message.send');assert.equal(s.valueSessions![0].baselineKind,'earliest_retained_work');assert.equal(s.valueSessions![0].observedStartedAt,m.createdAt);observeValueWork(s,actor(),'document.add');assert.equal(s.valueSessions![0].observedStartedAt,m.createdAt);});
test('usefulness is exact-version/hash bound, deduplicated and independent of goal achievement',()=>{const s=fixture(),g=goal(s),m=answer(s),out=valueView(s,actor()).outputs.find(x=>x.id===m.id)!;const command={type:'value.output.assess' as const,goalId:g.id,expectedGoalVersion:g.version,outputKind:out.kind,outputId:out.id,expectedOutputVersion:out.version,outputHash:out.hash,disposition:'useful' as const,reason:'I can use the fictional explanation.'};m.version++;assert.throws(()=>applyValueCommand(s,actor(),command),{code:'VALUE_OUTPUT_CHANGED'});m.version--;const result=assess(s,g,m);assert.equal(valueView(s,actor()).report.firstUsefulState,'available');assert.equal(g.status,'working');assert.equal(s.matters.length,0);assert.throws(()=>assess(s,g,m),{code:'VALUE_ALREADY_ASSESSED'});applyValueCommand(s,actor(),{type:'value.goal.assess',goalId:g.id,expectedRecordVersion:g.version,disposition:'reported_achieved',receiptId:String(result.receiptId),reason:'This stated explanatory goal is met; no matter completion is asserted.'});assert.equal(valueView(s,actor()).report.reportedAchievedGoalCount,1);assert.equal(s.matters.length,0);});
test('goal achievement requires the same goal’s current useful receipt and cannot be reported by another actor',()=>{const s=fixture(),g=goal(s),otherGoal=goal(s),m=answer(s);const r=assess(s,otherGoal,m);assert.throws(()=>applyValueCommand(s,actor(),{type:'value.goal.assess',goalId:g.id,expectedRecordVersion:g.version,disposition:'reported_achieved',receiptId:String(r.receiptId),reason:'Unrelated output'}),{code:'USEFUL_RECEIPT_REQUIRED'});assert.throws(()=>applyValueCommand(s,actor('other'),{type:'value.goal.assess',goalId:g.id,expectedRecordVersion:g.version,disposition:'working',reason:'Not mine'}),{code:'NOT_FOUND'});});
test('foreign private outputs and withdrawn-source receipts cannot leak into views or numeric exports',()=>{const s=fixture(),src=source(s),g=goal(s),m=answer(s,'owner',src);answer(s,'other');assert.equal(valueView(s,actor()).outputs.length,1);assess(s,g,m);src.status='revoked';src.version++;const view=valueView(s,actor());assert.equal(view.outputs.length,0);assert.equal(view.goals.length,0);assert.equal(view.receipts.length,0);assert.equal(view.report.firstUsefulState,'unavailable');assert.equal(view.report.firstUsefulElapsedMs,null);assert.equal(view.report.usefulOutputCount,0);assert.doesNotMatch(JSON.stringify(view),/Private synthetic goal title|Private synthetic source payload|Understand this fictional obligation|An explicitly fictional useful explanation/);const exported=JSON.stringify(view.report);assert.doesNotMatch(exported,/owner|other|source-|answer-|conversation-/);});
test('correcting a usefulness report cannot silently replace the original first-useful metric',()=>{const s=fixture(),g=goal(s),first=answer(s),id=String(assess(s,g,first).receiptId),r=s.valueReceipts!.find(r=>r.id===id)!;applyValueCommand(s,actor(),{type:'value.receipt.withdraw',receiptId:r.id,expectedRecordVersion:r.version,reason:'Correction: this output was not useful.'});assess(s,g,answer(s));const view=valueView(s,actor());assert.equal(view.session!.firstUsefulReceiptId,id);assert.equal(view.report.firstUsefulState,'unavailable');assert.equal(view.report.firstUsefulElapsedMs,null);assert.equal(view.report.usefulOutputCount,1);});
test('rehearsals retain learning feedback but never count as observed customer value',()=>{const s=fixture();s.rehearsal=true;const g=goal(s);assess(s,g,answer(s));const view=valueView(s,actor());assert.equal(view.receipts.length,1);assert.equal(view.report.firstUsefulState,'rehearsal_excluded');assert.equal(view.report.firstUsefulElapsedMs,null);assert.equal(view.report.usefulOutputCount,0);});
test('source revision changes invalidate inspected output hash even when answer text is unchanged',()=>{const s=fixture(),src=source(s),g=goal(s),m=answer(s,'owner',src),out=valueView(s,actor()).outputs[0];src.version++;assert.throws(()=>applyValueCommand(s,actor(),{type:'value.output.assess',goalId:g.id,expectedGoalVersion:g.version,outputKind:out.kind,outputId:m.id,expectedOutputVersion:m.version,outputHash:out.hash,disposition:'useful',reason:'Stale preview'}),{code:'VALUE_OUTPUT_CHANGED'});});

test('read projection supports a current integration-only member without granting feedback write capacity',()=>{const s=fixture();s.memberships.push({actorId:'intake',roles:['integration'],version:1,expiresAt:null,revokedAt:null,matterIds:null,entityIds:null});const view=valueView(s,actor('intake'));assert.equal(view.session,null);assert.equal(view.receipts.length,0);assert.throws(()=>applyValueCommand(s,actor('intake'),{type:'value.goal.define',title:'Not authorized',successCriteria:'Not authorized'}),{code:'FORBIDDEN'});});

test('service hooks retain the first message baseline and observe an async answer only after committed output',async()=>{
 const {mkdtemp,rm}=await import('node:fs/promises'),{tmpdir}=await import('node:os'),{join}=await import('node:path'),{randomUUID}=await import('node:crypto');
 const {command,snapshot}=await import('../src/v2/service'),{processConversationRun}=await import('../src/v2/ai'),{closeV2Store}=await import('../src/v2/store');
 const keys=['KIARA_V2_DATA_DIR','KIARA_GLOBAL_BUDGET_DIR','MONGODB_URI','VERCEL','KIARA_V2_AI_MODE','OPENAI_API_KEY','KIARA_OPENAI_BUDGET_USD','KIARA_MODEL','KIARA_REVIEW_MODEL','KIARA_REASONING_EFFORT'];const old=Object.fromEntries(keys.map(k=>[k,process.env[k]])),dir=await mkdtemp(join(tmpdir(),'kiara-value-service-'));
 try{
  process.env.KIARA_V2_DATA_DIR=join(dir,'workspace');process.env.KIARA_GLOBAL_BUDGET_DIR=join(dir,'budget');delete process.env.MONGODB_URI;delete process.env.VERCEL;process.env.KIARA_V2_AI_MODE='local';
  const a:ActorContext={...actor(),tenantId:'value-service',bootstrapRoles:['member','fact_owner','business_owner','admin']};
  const send=async(context:ActorContext,c:import('../src/v2/contracts').WorkspaceCommand)=>{const before=await snapshot(context);return command(context,{idempotencyKey:randomUUID(),expectedVersion:before.version,command:c})};
  const first=await send(a,{type:'message.send',text:'What should I think about before a fictional change?'}),started=first.snapshot.value.session!;
  assert.equal(started.baselineKind,'observed_command');assert.ok(started.firstGeneratedAt);assert.equal(first.snapshot.value.report.firstUsefulState,'not_recorded');
  const second=await send(a,{type:'message.send',text:'Explain the next fictional consideration.'});assert.equal(second.snapshot.value.session!.observedStartedAt,started.observedStartedAt);assert.equal(second.snapshot.value.session!.id,started.id);
  assert.equal('valueSessions' in second.snapshot,false);assert.equal('valueReceipts' in second.snapshot,false);
  await send(a,{type:'document.add',title:'Acme synthetic agreement',body:'Acme requires 30 days notice before a new subprocessor handles personal data.',authority:'executed',kind:'agreement',scope:{kind:'team',actorIds:[]}});
  process.env.KIARA_V2_AI_MODE='openai';process.env.OPENAI_API_KEY='injected-test-only';process.env.KIARA_OPENAI_BUDGET_USD='1';process.env.KIARA_MODEL='gpt-6-sol';process.env.KIARA_REVIEW_MODEL='gpt-6-sol';process.env.KIARA_REASONING_EFFORT='low';
  const b:ActorContext={...a,actorId:'async-user'},queued=await send(b,{type:'message.send',text:'Explain the Acme synthetic agreement notice.'});assert.equal(queued.snapshot.value.session!.firstGeneratedAt,null);const asyncBaseline=queued.snapshot.value.session!.observedStartedAt;
  let calls=0;const adapter:import('../src/v2/ai').ConversationProvider={count:async()=>1000,create:async request=>{calls++;const input=JSON.parse(String(request.input));const body=input.answer?{safe:true,checks:input.answer.paragraphs.map((p:{id:string})=>({paragraphId:p.id,supported:true,reason:'Exact synthetic source support.'}))}:{paragraphs:[{id:'p1',kind:'grounded',text:'The supplied Acme agreement requires 30 days notice before a new subprocessor handles personal data.',citationIds:[input.evidence.find((e:{kind:string})=>e.kind==='document').id]}]};return {id:`injected-${calls}`,model:String(request.model),status:'completed',output_text:JSON.stringify(body),usage:{input_tokens:100,output_tokens:40,total_tokens:140,input_tokens_details:{cached_tokens:0,cache_write_tokens:0},output_tokens_details:{reasoning_tokens:0}}}}};
  assert.equal((await processConversationRun(a.tenantId,String(queued.result.runId),{provider:adapter})).status,'complete');const ready=await snapshot(b);assert.equal(calls,2);assert.equal(ready.value.session!.observedStartedAt,asyncBaseline);assert.ok(ready.value.session!.firstGeneratedAt);assert.equal(ready.value.report.firstUsefulState,'not_recorded');assert.equal(ready.value.receipts.length,0);assert.ok(ready.value.outputs.some(x=>x.kind==='answer'));
  await send(b,{type:'membership.revoke',actorId:b.actorId}).catch(error=>assert.equal(error.code,'MEMBERSHIP_REVOKED'));
  const retained=await (await import('../src/v2/store')).readWorkspace(a.tenantId);assert.ok(retained.memberships.find(m=>m.actorId===b.actorId)?.revokedAt);await assert.rejects(()=>snapshot(b),{code:'MEMBERSHIP_REVOKED'});
 }finally{await closeV2Store();for(const key of keys){if(old[key]===undefined)delete process.env[key];else process.env[key]=old[key];}await rm(dir,{recursive:true,force:true});}
});

test('historical report remains attributed after version change but cannot outlive its conversation access',()=>{const s=fixture(),g=goal(s),m=answer(s);assess(s,g,m);m.version++;m.text='A revised explanation';let view=valueView(s,actor());assert.equal(view.receipts.length,1);assert.equal(view.receipts[0].outputVersion,1);assert.equal(view.outputs[0].version,2);const c=s.conversations.find(c=>c.id===m.conversationId)!;c.scope={kind:'private',actorIds:['other']};view=valueView(s,actor());assert.equal(view.receipts.length,0);assert.equal(view.outputs.length,0);assert.equal(view.report.firstUsefulState,'unavailable');});

test('output observation never rolls back a membership removal or requires a still-valid session',()=>{const s=fixture();goal(s);s.memberships[0].revokedAt=new Date().toISOString();assert.doesNotThrow(()=>observeValueOutputs(s,actor()));assert.doesNotThrow(()=>observeValueOutputs(s,{...actor(),expiresAt:Date.now()-1}));assert.equal(s.valueSessions![0].firstGeneratedAt,null);});
