import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {signup,tick,review,feedback,verifyFact,reset} from '../src/workflow/engine';
import {readState,transaction} from '../src/data/store';
import {id} from '../src/server/hash';
import type {Workflow} from '../src/server/contracts';
const dir=await mkdtemp(join(tmpdir(),'kiara-workflow-'));process.env.KIARA_DATA_DIR=dir;delete process.env.MONGODB_URI;process.env.KIARA_MODEL_MODE='scripted';process.env.KIARA_EMAIL_MODE='preview';
async function advance(wid:string){for(let i=0;i<16;i++){await tick();const w=(await readState()).workflows.find(w=>w.workflow_id===wid)!;if(['awaiting_founder','needs_information','closed_no_change','needs_human_review','failed'].includes(w.state))return w;}throw new Error('Workflow did not reach a review boundary');}
const command=(w:Workflow,action:'approved'|'requested_changes'='approved')=>({action,expected_state_version:w.state_version,expected_reset_epoch:w.reset_epoch,bundle_hash:w.bundle_hash!,note:''});
test('persisted signup without manufactured failure, ordered sealed approval and retained finalization',async()=>{const s=await readState();const input={customer_name:'Jordan Lee',residence:'US-CA',scenario:'covered',expected_reset_epoch:s.reset_epoch};const key=id();const result=await signup(input,key);assert.deepEqual(await signup(input,key),result);await assert.rejects(signup({...input,customer_name:'Different'},key),/different request/);let w=await advance(result.workflow_id);assert.equal(w.state,'awaiting_founder');assert.equal(w.repair_count,0);assert.equal(w.missing_bundle_repairs,0);assert.equal(w.validations.filter(v=>!v.passed).length,0);assert.equal(result.event_id,w.event_id);assert.equal(result.accepted,true);assert.ok(w.bundle_hash);let saved=await readState();assert.ok(saved.events.some(e=>e.event_id===w.event_id&&e.type==='user.signed_up'));await assert.rejects(review(w.workflow_id,'lawyer',command(w),id()),/Founder approval/);const old=command(w);await review(w.workflow_id,'founder',old,id());await assert.rejects(review(w.workflow_id,'founder',old,id()),/changed/);saved=await readState();w=saved.workflows[0];assert.equal(w.state,'awaiting_lawyer');assert.equal(saved.notifications.length,1);assert.equal(saved.notifications[0].status,'pending');await review(w.workflow_id,'lawyer',command(w),id());saved=await readState();assert.equal(saved.workflows[0].state,'finalized');assert.equal(saved.current_revision_id,w.candidate_revision_id);assert.equal(saved.notifications.length,2);});
test('distinct event pins the existing harness and closes only against the finalized packet',async()=>{const s=await readState();const result=await signup({customer_name:'Taylor Chen',residence:'US-CA',scenario:'covered',expected_reset_epoch:s.reset_epoch},id());const w=await advance(result.workflow_id);assert.equal(w.harness_version,s.champion_version);assert.equal(w.missing_bundle_repairs,0);assert.equal(w.state,'closed_no_change');assert.equal((await readState()).champion_version,s.champion_version);});
test('unknown facts block drafting and old reset commands cannot affect reused workspace',async()=>{let s=await readState();await reset(s.reset_epoch);s=await readState();const result=await signup({customer_name:'Sam Unknown',residence:'US-CA',scenario:'unknown',expected_reset_epoch:s.reset_epoch},id());const w=await advance(result.workflow_id);assert.equal(w.state,'needs_information');assert.equal(w.candidate_revision_id,null);const f=await feedback(w.workflow_id,'founder',{type:'fact_correction',text:'Verified synthetic 2025 revenue',fact_key:'annual_gross_revenue_usd',proposed_value:30000000,expected_reset_epoch:s.reset_epoch},id());await verifyFact(f.feedback_id,'founder',s.reset_epoch);const repaired=await advance(w.workflow_id);assert.equal(repaired.state,'awaiting_founder');const oldEpoch=s.reset_epoch;await reset(s.reset_epoch);await assert.rejects(review(repaired.workflow_id,'founder',command(repaired),id()),/reset/);assert.equal((await readState()).reset_epoch,oldEpoch+1);});
test('material edit invalidates earlier founder approval and requires both gates again',async()=>{const s=await readState();const result=await signup({customer_name:'Alex Edit',residence:'US-CA',scenario:'covered',expected_reset_epoch:s.reset_epoch},id());let w=await advance(result.workflow_id);const originalBundle=w.bundle_hash;await review(w.workflow_id,'founder',command(w),id());let saved=await readState();w=saved.workflows[0];const r=saved.revisions.find(r=>r.revision_id===w.candidate_revision_id)!;const clause=r.clauses.find(c=>c.heading==='California privacy rights')!;await feedback(w.workflow_id,'lawyer',{type:'document_edit',text:clause.body+' Contact us with questions.',clause_id:clause.clause_id,expected_state_version:w.state_version,expected_candidate_revision_id:w.candidate_revision_id!,expected_reset_epoch:s.reset_epoch},id());w=await advance(w.workflow_id);assert.equal(w.state,'awaiting_founder');assert.notEqual(w.bundle_hash,originalBundle);await assert.rejects(review(w.workflow_id,'lawyer',command(w),id()),/Founder approval/);});
test('source expiry prevents approval even without a background invalidation job',async()=>{let s=await readState();const w=s.workflows[0];await transaction(state=>{state.workflows[0].freshness_valid_until='2000-01-01T00:00:00Z';});await assert.rejects(review(w.workflow_id,'founder',command(w),id()),/expired/);});
test.after(async()=>{await rm(dir,{recursive:true,force:true});});
