import {V2Error,type Action} from '../contracts';
import {digest} from '../store';
import {retainOriginal,readOriginal,type OriginalReference} from '../objects';
import {credential} from '../integrations/config';
import {DispatchRejected,type ExecutionAdapter,type ExecutionRequest} from './contracts';
export interface ExecutionConfiguration {tenantId:string;email?:{mode:'preview'|'resend';from:string;tokenEnv?:string;allowedRecipients:string[]};publicationUrls?:string[]}
export function executionConfiguration(tenantId:string):ExecutionConfiguration {
 let values:ExecutionConfiguration[]=[];try{values=JSON.parse(process.env.KIARA_V2_EXECUTION||'[]');}catch{throw new V2Error('EXECUTION_CONFIG_INVALID','Execution configuration is invalid.',503);}
 if(!Array.isArray(values)||values.length>100)throw new V2Error('EXECUTION_CONFIG_INVALID','Execution configuration is invalid.',503);
 const value=values.find(v=>v.tenantId===tenantId)||{tenantId};if(value.email&&(!['preview','resend'].includes(value.email.mode)||!Array.isArray(value.email.allowedRecipients)||!value.email.allowedRecipients.length||value.email.allowedRecipients.length>100||![value.email.from,...value.email.allowedRecipients].every(a=>typeof a==='string'&&/^[^\s<>@]+@[^\s<>@]+\.[^\s<>@]+$/.test(a))))throw new V2Error('EXECUTION_CONFIG_INVALID','Configure exact valid sender and recipient addresses.',503);
 if(value.publicationUrls&&(!Array.isArray(value.publicationUrls)||value.publicationUrls.length>100||value.publicationUrls.some(url=>{try{const u=new URL(url);return u.protocol!=='https:'||!!u.username||!!u.password||!!u.hash;}catch{return true;}})))throw new V2Error('EXECUTION_CONFIG_INVALID','Configure exact HTTPS publication read-back targets.',503);return value;
}
export function internalDocumentAdapter():ExecutionAdapter {
 const retain=async(request:ExecutionRequest)=>retainOriginal(request.tenantId,Buffer.from(request.action.content,'utf8'));
 return {id:'internal-immutable-document-v1',configurationHash:digest({kind:'internal_document',storage:process.env.KIARA_ORIGINALS_MODE||'local_encrypted'}),supportedKinds:['internal_document'],effect:'internal',dispatch:async request=>({receipt:JSON.stringify(await retain(request))}),readback:async(request,receipt)=>{const reference:OriginalReference=receipt?JSON.parse(receipt):await retain(request);const bytes=await readOriginal(request.tenantId,reference);if(!bytes.equals(Buffer.from(request.action.content,'utf8')))return {status:'failed',receipt:JSON.stringify(reference),reason:'READBACK_MISMATCH'};return {status:'verified',receipt:JSON.stringify(reference),contentHash:request.action.contentHash,artifact:JSON.stringify(reference),internalDocument:{originalReference:JSON.stringify(reference),body:bytes.toString('utf8')}};}};
}
async function boundedResponse(response:Response){if(Number(response.headers.get('content-length')||0)>500000||!response.body)throw new V2Error('PROVIDER_RESPONSE_LIMIT','The provider response exceeds the verification limit.',503);const chunks:Uint8Array[]=[];let size=0;const reader=response.body.getReader();while(true){const part=await reader.read();if(part.done)break;size+=part.value.length;if(size>500000){await reader.cancel();throw new V2Error('PROVIDER_RESPONSE_LIMIT','The provider response exceeds the verification limit.',503);}chunks.push(part.value);}return Buffer.concat(chunks).toString('utf8');}
export function emailAdapter(configuration:ExecutionConfiguration,fetcher:typeof fetch=fetch):ExecutionAdapter {
 const email=configuration.email;if(!email)throw new V2Error('EXECUTION_UNAVAILABLE','No email installation is configured.',503);
 const payload=(r:ExecutionRequest)=>{if(r.tenantId!==configuration.tenantId||r.action.kind!=='send'||!r.action.recipients.length||r.action.recipients.some(to=>!email.allowedRecipients.includes(to))||r.action.destination!==null||/[\r\n]/.test(r.action.title))throw new V2Error('EXECUTION_SCOPE','The exact sender, recipient or destination is outside this configured email installation.',403);return {from:email.from,to:r.action.recipients,subject:r.action.title,text:r.action.content,tags:[{name:'kiara_effect',value:digest({tenantId:r.tenantId,actionId:r.action.id,idempotencyKey:r.idempotencyKey})},{name:'kiara_content',value:r.action.contentHash}]};};
 return {id:`email-${email.mode}-v1`,configurationHash:digest(configuration),supportedKinds:['send'],effect:email.mode==='preview'?'preview':'email',sender:email.from,validate:request=>{payload(request);if(email.mode==='resend'){if(!email.tokenEnv)throw new V2Error('EXECUTION_UNAVAILABLE','Configure the email credential reference.',503);credential(email.tokenEnv);}},dispatch:async request=>{const body=payload(request);if(email.mode==='preview')return {receipt:`preview:${digest({key:request.idempotencyKey,body})}`};if(!email.tokenEnv)throw new V2Error('EXECUTION_UNAVAILABLE','The email installation requires a credential reference.',503);
  const response=await fetcher('https://api.resend.com/emails',{method:'POST',redirect:'error',signal:AbortSignal.timeout(20000),headers:{Authorization:`Bearer ${credential(email.tokenEnv)}`,'Content-Type':'application/json','Idempotency-Key':request.idempotencyKey},body:JSON.stringify(body)});
  // Conflict may mean another request is running. Never release it as a known rejection.
  if([400,401,403,404,422,429].includes(response.status))throw new DispatchRejected('The provider rejected this request before acceptance.');if(!response.ok)throw new V2Error('PROVIDER_OUTCOME_UNKNOWN','The email outcome is uncertain.',503);let value:any;try{value=JSON.parse(await boundedResponse(response));}catch{throw new V2Error('PROVIDER_OUTCOME_UNKNOWN','The email receipt is unavailable.',503);}if(typeof value.id!=='string'||!value.id||value.id.length>200)throw new V2Error('PROVIDER_OUTCOME_UNKNOWN','The email receipt is unavailable.',503);return {receipt:value.id};
 },readback:async(request,receipt)=>{const expected=payload(request);if(email.mode==='preview')return {status:'pending',receipt:receipt||`preview:${digest(expected)}`,reason:'PREVIEW_NOT_DELIVERY'};if(!receipt)return {status:'pending',receipt:'',reason:'PROVIDER_RECEIPT_REQUIRED'};if(!email.tokenEnv)throw new V2Error('EXECUTION_UNAVAILABLE','The email installation requires its credential.',503);const response=await fetcher(`https://api.resend.com/emails/${encodeURIComponent(receipt)}`,{method:'GET',redirect:'error',signal:AbortSignal.timeout(15000),headers:{Authorization:`Bearer ${credential(email.tokenEnv)}`}});if(!response.ok)throw new V2Error('READBACK_UNAVAILABLE','Delivery read-back is unavailable; no resend is authorized.',503);const value=JSON.parse(await boundedResponse(response));if(value.id!==receipt||value.from!==expected.from||digest(value.to)!==digest(expected.to)||value.subject!==expected.subject||value.text!==expected.text||value.cc?.length||value.bcc?.length||expected.tags.some(tag=>!value.tags?.some((t:{name:string;value:string})=>t.name===tag.name&&t.value===tag.value)))return {status:'failed',receipt,reason:'READBACK_MISMATCH'};if(['bounced','failed','complained','canceled','suppressed'].includes(value.last_event))return {status:'failed',receipt,reason:'DELIVERY_FAILED'};return ['delivered','opened','clicked'].includes(value.last_event)?{status:'verified',receipt,contentHash:request.action.contentHash,artifact:`resend:${receipt}:delivered`}:{status:'pending',receipt,reason:'DELIVERY_PENDING'};}};
}
export function publicationReadbackAdapter(configuration:ExecutionConfiguration,fetcher:typeof fetch=fetch):ExecutionAdapter {
 const check=(action:Action)=>{if(!action.destination||!configuration.publicationUrls?.includes(action.destination))throw new V2Error('EXECUTION_SCOPE','The exact publication target is not configured for read-back.',403);return action.destination;};
 return {id:'publication-exact-readback-v1',configurationHash:digest(configuration),supportedKinds:['publish'],effect:'publication_readback',validate:request=>{if(request.tenantId!==configuration.tenantId)throw new V2Error('EXECUTION_SCOPE','Publication target belongs to a different tenant.',403);check(request.action);},dispatch:async request=>({receipt:`target:${digest(check(request.action))}`}),readback:async(request,receipt)=>{const url=check(request.action);if(request.tenantId!==configuration.tenantId)throw new V2Error('EXECUTION_SCOPE','Publication target belongs to a different tenant.',403);const response=await fetcher(url,{method:'GET',redirect:'error',signal:AbortSignal.timeout(15000),headers:{Accept:'text/plain,text/html'}});if(!response.ok)throw new V2Error('READBACK_UNAVAILABLE','The exact publication target is unavailable.',503);const body=await boundedResponse(response);if(body!==request.action.content)return {status:'pending',receipt:receipt||'',reason:'PUBLICATION_CONTENT_MISMATCH'};const proof=await retainOriginal(request.tenantId,Buffer.from(body));return {status:'verified',receipt:receipt||'',contentHash:request.action.contentHash,artifact:JSON.stringify({url,readback:proof})};}};
}
export function configuredAdapter(tenantId:string,action:Action):ExecutionAdapter {if(action.kind==='internal_document')return internalDocumentAdapter();const configuration=executionConfiguration(tenantId);if(action.kind==='send')return emailAdapter(configuration);if(action.kind==='publish')return publicationReadbackAdapter(configuration);throw new V2Error('EXECUTION_UNAVAILABLE','This action requires its existing manual path or a separately configured qualified provider.',503);}
