import {randomUUID} from 'node:crypto';
import {membership,readRecord,requireRole} from '../authority';
import {V2Error,type Action,type ActorContext,type DocumentRecord,type Source,type WorkspaceState} from '../contracts';
import {digest,readWorkspace,timestamp,transactWorkspace} from '../store';
import {assertExecutable} from './authority';
import {configuredAdapter} from './adapters';
import {DispatchRejected,type EffectIntent,type EffectView,type ExecutionAdapter,type ExecutionRequest,type ExecutionPreview} from './contracts';
const key=(actionId:string)=>`execution:${actionId}`;
const view=(i:EffectIntent):EffectView=>({actionId:i.actionId,status:i.status,providerReceipt:i.providerReceipt,completionArtifact:i.completionArtifact,failure:i.failure});
const intent=(s:WorkspaceState,actionId:string)=>s.receipts[key(actionId)]?.result.intent as EffectIntent|undefined;
const save=(s:WorkspaceState,i:EffectIntent)=>{s.receipts[key(i.actionId)]={hash:digest({id:i.id,actionHash:i.actionHash,idempotencyKey:i.idempotencyKey}),result:{intent:i}};};
const touch=(a:{version:number;updatedAt:string})=>{a.version++;a.updatedAt=timestamp();};
function ensure(ok:unknown,code:string,message:string):asserts ok {if(!ok)throw new V2Error(code,message);}
function select(tenantId:string,a:Action,override?:ExecutionAdapter){const adapter=override||configuredAdapter(tenantId,a);ensure(adapter.supportedKinds.includes(a.kind),'EXECUTION_UNAVAILABLE','This adapter cannot execute this action kind.');return adapter;}
function request(i:EffectIntent):ExecutionRequest{return {tenantId:i.tenantId,action:structuredClone(i.actionSnapshot),idempotencyKey:i.idempotencyKey};}
function previewInState(s:WorkspaceState,actor:ActorContext,action:Action,adapter:ExecutionAdapter):ExecutionPreview {
 const member=requireRole(s,actor,action.kind==='signature_request'?'signatory':action.kind==='no_action'?'business_owner':'publisher',action);
 return {previewHash:digest({tenantId:s.tenantId,actorId:actor.actorId,membershipVersion:member.version,actionVersion:action.version,actionHash:action.contentHash,adapterId:adapter.id,configurationHash:adapter.configurationHash}),actionVersion:action.version,contentHash:action.contentHash,mode:adapter.effect,...(adapter.sender?{sender:adapter.sender}:{}),recipients:[...action.recipients],destination:action.destination,title:action.title,content:action.content};
}
export async function executionPreview(actor:ActorContext,actionId:string,options:{adapter?:ExecutionAdapter}={}):Promise<ExecutionPreview>{const s=await readWorkspace(actor.tenantId),action=readRecord(s,actor,s.actions,actionId),adapter=select(actor.tenantId,action,options.adapter);return previewInState(s,actor,action,adapter);}
async function bounded<T>(operation:Promise<T>,ms=25000):Promise<T>{let timer:ReturnType<typeof setTimeout>|undefined;try{return await Promise.race([operation,new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(new V2Error('PROVIDER_TIMEOUT','The provider outcome is uncertain; reconciliation is required.',503)),ms);})]);}finally{if(timer)clearTimeout(timer);}}
async function fail(tenantId:string,actionId:string,error:unknown,dispatched:boolean){return (await transactWorkspace(tenantId,s=>{const i=intent(s,actionId);ensure(i,'EFFECT_NOT_FOUND','The effect intent is unavailable.');const a=s.actions.find(a=>a.id===actionId)!;if(i.status==='verified'||a.status==='verified'&&a.completion)return {...view(i),status:'verified' as const,completionArtifact:a.completion?.artifact||i.completionArtifact};const known=!dispatched||error instanceof DispatchRejected;i.status=known?'failed':'uncertain';i.failure=error instanceof V2Error?error.code:error instanceof DispatchRejected?'PROVIDER_REJECTED':'PROVIDER_OUTCOME_UNKNOWN';i.leaseToken=null;i.leaseUntil=null;i.updatedAt=timestamp();a.status=known?(s.matters.find(m=>m.id===a.matterId)?.state==='canceled'?'canceled':'failed'):'uncertain';a.leaseUntil=null;touch(a);save(s,i);return view(i);})).result;}
/** Exact action intent is durable before a provider call. Replays never issue another dispatch. */
export async function dispatchAction(actor:ActorContext,actionId:string,input:{expectedVersion:number;contentHash:string;previewHash:string;adapter?:ExecutionAdapter}):Promise<EffectView>{
 const initial=await readWorkspace(actor.tenantId),a=readRecord(initial,actor,initial.actions,actionId);requireRole(initial,actor,a.kind==='signature_request'?'signatory':a.kind==='no_action'?'business_owner':'publisher',a);const prior=intent(initial,actionId);
 if(prior){ensure(prior.actionHash===input.contentHash,'STALE_ACTION','The action hash differs from this retained effect.');if(prior.status==='dispatched'&&Date.parse(prior.leaseUntil||'')<=Date.now())return fail(actor.tenantId,actionId,new V2Error('EFFECT_INTERRUPTED','A prior dispatch needs reconciliation.'),true);return view(prior);}
 const adapter=select(actor.tenantId,a,input.adapter);ensure(input.previewHash===previewInState(initial,actor,a,adapter).previewHash,'EXECUTION_PREVIEW_CHANGED','Inspect and confirm the exact current sender, mode and action before execution.');adapter.validate?.({tenantId:actor.tenantId,action:a,idempotencyKey:a.providerIdempotencyKey});const leaseToken=randomUUID();
 const claimed=await transactWorkspace(actor.tenantId,s=>{const action=readRecord(s,actor,s.actions,actionId),old=intent(s,actionId);if(old)return {claimed:false,intent:old};ensure(action.version===input.expectedVersion&&action.contentHash===input.contentHash,'STALE_ACTION','Review the current action before execution.');ensure(['authorized','pending_manual'].includes(action.status),'ACTION_NOT_READY','Only an explicitly authorized action can begin execution.');ensure(input.previewHash===previewInState(s,actor,action,adapter).previewHash,'EXECUTION_PREVIEW_CHANGED','The execution preview changed before its decision was recorded.');const checked=assertExecutable(s,actor,action);const created:EffectIntent={id:randomUUID(),actionId,tenantId:s.tenantId,owner:'v2',actor:structuredClone(actor),actionHash:action.contentHash,proposalHash:checked.proposal.contentHash,dependencies:structuredClone(checked.proposal.dependencies),authorizationId:checked.authorization.id,executionDecision:{actorId:actor.actorId,membershipVersion:membership(s,actor).version,previewHash:input.previewHash,mode:adapter.effect,sender:adapter.sender||null,approvedAt:timestamp()},actionSnapshot:structuredClone(action),adapterId:adapter.id,adapterConfigurationHash:adapter.configurationHash,idempotencyKey:action.providerIdempotencyKey,status:'prepared',leaseToken,leaseUntil:new Date(Date.now()+60000).toISOString(),providerReceipt:null,createdAt:timestamp(),updatedAt:timestamp(),failure:null,completionArtifact:null};save(s,created);s.outbox.push({id:randomUUID(),tenantId:s.tenantId,kind:'effect_reconcile',aggregateId:actionId,commandId:created.id,status:'pending',owner:'v2',createdAt:timestamp()});action.status='dispatching';action.leaseUntil=created.leaseUntil;touch(action);return {claimed:true,intent:created};});
 if(!claimed.result.claimed)return view(claimed.result.intent);const operation=claimed.result.intent;let dispatched=false;
 try{
  if(adapter.prepare)await bounded(adapter.prepare(request(operation)),15000);
  await transactWorkspace(actor.tenantId,s=>{const i=intent(s,actionId),action=readRecord(s,actor,s.actions,actionId);ensure(i?.status==='prepared'&&i.leaseToken===leaseToken&&Date.parse(i.leaseUntil||'')>Date.now(),'EFFECT_LEASE_EXPIRED','The prepared effect lease expired.');assertExecutable(s,actor,action);ensure(actor.actorId===i.executionDecision.actorId&&membership(s,actor).version===i.executionDecision.membershipVersion,'EXECUTION_PREVIEW_CHANGED','The dispatcher’s authority changed after confirmation; inspect a new execution preview.');ensure(action.contentHash===i.actionHash&&action.authorizationId===i.authorizationId,'ACTION_AUTHORIZATION_CHANGED','The exact action authority changed.');const current=select(actor.tenantId,action,input.adapter);ensure(current.id===i.adapterId&&current.configurationHash===i.adapterConfigurationHash,'EXECUTION_CONFIG_CHANGED','Execution configuration changed before dispatch.');current.validate?.(request(i));i.status='dispatched';i.updatedAt=timestamp();save(s,i);});
  dispatched=true;const receipt=await bounded(adapter.dispatch(request(operation)));ensure(typeof receipt.receipt==='string'&&receipt.receipt.length>0&&receipt.receipt.length<5000,'PROVIDER_RECEIPT_INVALID','The provider did not return a bounded receipt.');
  await transactWorkspace(actor.tenantId,s=>{const i=intent(s,actionId)!;ensure(!i.providerReceipt||i.providerReceipt===receipt.receipt,'PROVIDER_RECEIPT_CONFLICT','Different provider receipts require operator reconciliation.');i.providerReceipt=receipt.receipt;if(i.status!=='verified'){i.status='verifying';i.failure=null;}i.updatedAt=timestamp();i.leaseToken=null;i.leaseUntil=null;const action=s.actions.find(a=>a.id===actionId)!;action.providerReceipt=receipt.receipt;if(action.status!=='verified')action.status=adapter.effect==='preview'?'pending_manual':'verifying';action.leaseUntil=null;touch(action);save(s,i);});
 }catch(error){return fail(actor.tenantId,actionId,error,dispatched);}
 return reconcileEffect(actor.tenantId,actionId,{adapter:input.adapter});
}
/** Server-side read-back only. It may record a late receipt after cancellation/revocation, never redispatch. */
export async function reconcileEffect(tenantId:string,actionId:string,options:{adapter?:ExecutionAdapter;candidateReceipt?:string}={}):Promise<EffectView>{
 const before=await readWorkspace(tenantId),i=intent(before,actionId);ensure(i,'EFFECT_NOT_FOUND','No durable effect intent exists.');if(i.status==='failed')return view(i);const actual=before.actions.find(a=>a.id===actionId);if(actual?.status==='verified'&&actual.completion?.kind!=='readback')return {...view(i),status:'verified',completionArtifact:actual.completion?.artifact||null};
 const adapter=select(tenantId,i.actionSnapshot,options.adapter);ensure(adapter.id===i.adapterId&&adapter.configurationHash===i.adapterConfigurationHash,'EXECUTION_CONFIG_CHANGED','Restore the original adapter configuration before read-back.');
 if(i.status==='verified'&&adapter.effect!=='email')return view(i);
 if((i.status==='prepared'||i.status==='dispatched')&&Date.parse(i.leaseUntil||'')>Date.now())return view(i);
 if(i.status==='prepared')return fail(tenantId,actionId,new V2Error('EFFECT_NOT_DISPATCHED','The interrupted prepared intent did not dispatch.'),false);
 if(options.candidateReceipt){ensure(adapter.effect==='email'&&(!i.providerReceipt||i.providerReceipt===options.candidateReceipt)&&options.candidateReceipt.length<200,'PROVIDER_RECEIPT_CONFLICT','The candidate receipt cannot replace a retained provider identity.');}
 let result;try{result=await bounded(adapter.readback(request(i),options.candidateReceipt||i.providerReceipt),20000);}catch{return fail(tenantId,actionId,new V2Error('READBACK_UNAVAILABLE','Read-back is unavailable; no resend is authorized.'),true);}
 if(options.candidateReceipt)ensure(result.reason!=='READBACK_MISMATCH','PROVIDER_RECEIPT_MISMATCH','The candidate receipt does not match this effect identity and exact payload.');
 return (await transactWorkspace(tenantId,s=>{
  const current=intent(s,actionId)!;if(current.status==='failed'||current.status==='verified'&&result.status!=='failed')return view(current);const action=s.actions.find(a=>a.id===actionId)!;if(action.status==='verified'&&action.completion?.kind!=='readback')return {...view(current),status:'verified' as const,completionArtifact:action.completion?.artifact||null};ensure(current.id===i.id&&current.actionHash===i.actionHash,'EFFECT_CHANGED','The immutable effect identity changed.');
  if(result.receipt){ensure(!current.providerReceipt||current.providerReceipt===result.receipt,'PROVIDER_RECEIPT_CONFLICT','The read-back receipt differs from the retained provider identity.');current.providerReceipt=result.receipt;action.providerReceipt=result.receipt;}
  const verified=result.status==='verified'&&adapter.effect!=='preview'&&action.kind!=='signature_request'&&result.contentHash===current.actionHash&&action.contentHash===current.actionHash;
  if(verified){
   let artifact=result.artifact||current.providerReceipt||'';ensure(artifact,'COMPLETION_ARTIFACT_REQUIRED','Read-back must retain an action-specific artifact.');
   if(result.internalDocument){ensure(result.internalDocument.body===action.content,'READBACK_MISMATCH','Internal document bytes differ from the action.');const source:Source={id:randomUUID(),tenantId:s.tenantId,version:1,createdAt:timestamp(),updatedAt:timestamp(),scope:structuredClone(action.scope),provenance:{...structuredClone(action.provenance),description:'Immutable internal action output; no external publication or signing.'},title:action.title,kind:'manual',externalId:null,externalRevision:null,text:result.internalDocument.body,contentHash:digest(result.internalDocument.body),url:null,status:'active',aclVersion:1,observedAt:timestamp(),effectiveAt:null,authority:'draft',originalObjectRef:result.internalDocument.originalReference};const document:DocumentRecord={id:randomUUID(),tenantId:s.tenantId,version:1,createdAt:timestamp(),updatedAt:timestamp(),scope:structuredClone(action.scope),provenance:{...structuredClone(source.provenance),sourceIds:[source.id]},documentId:randomUUID(),title:action.title,body:source.text,contentHash:digest(source.text),authority:'draft',sourceId:source.id,revision:1,parentRevisionId:null,amendsDocumentId:null,status:'proposed',kind:'draft'};s.sources.push(source);s.documents.push(document);artifact=document.id;
   }
   current.status='verified';current.failure=null;current.completionArtifact=artifact;action.status='verified';action.completion={kind:'readback',artifact,verifierId:`adapter:${adapter.id}`,verifiedAt:timestamp()};const matter=s.matters.find(m=>m.id===action.matterId);if(matter&&['executing','authorized_action','verifying'].includes(matter.state)){matter.state='verifying';matter.blockers=['Review completion evidence for every required action before closure.'];touch(matter);}
  }else if(result.status==='failed'){current.status='failed';current.failure=result.reason||'READBACK_FAILED';action.status='failed';const matter=s.matters.find(m=>m.id===action.matterId);if(matter){if(matter.state!=='canceled'){matter.state='needs_facts';matter.closedAt=null;matter.outcome=null;}matter.blockers=['Provider read-back contradicted this required action. Resolve the owned corrective task; prior receipts remain historical.'];matter.tasks.push({id:randomUUID(),title:'Investigate failed or contradicted action completion',ownerId:matter.ownerId,status:'pending',kind:'verification',dueAt:null,deadlineType:'undated',evidenceIds:[current.id]});touch(matter);s.events.push({id:randomUUID(),tenantId:s.tenantId,version:1,createdAt:timestamp(),updatedAt:timestamp(),scope:structuredClone(action.scope),provenance:structuredClone(action.provenance),type:'execution.readback_contradicted',title:'Required action needs corrective work',detail:'Current provider read-back failed. Earlier completion evidence is retained as historical; closure must be reviewed.',matterId:matter.id,recordId:action.id,measurement:s.rehearsal?'fictional_rehearsal':'observed'});}}
  else{current.status=current.providerReceipt?'verifying':'uncertain';current.failure=action.kind==='signature_request'?'EXECUTED_ORIGINAL_REQUIRED':result.reason||'COMPLETION_PENDING';action.status=adapter.effect==='preview'?'pending_manual':current.status;}
  current.leaseToken=null;current.leaseUntil=null;current.updatedAt=timestamp();action.leaseUntil=null;touch(action);save(s,current);return view(current);
 })).result;
}

/** An operator-supplied ID is accepted only after provider read-back binds exact effect tags and bytes. */
export async function reconcileAction(actor:ActorContext,actionId:string,input:{expectedVersion:number;contentHash:string;providerReceipt?:string;adapter?:ExecutionAdapter}){
 const state=await readWorkspace(actor.tenantId),action=readRecord(state,actor,state.actions,actionId);requireRole(state,actor,action.kind==='signature_request'?'signatory':action.kind==='no_action'?'business_owner':'publisher',action);ensure(action.version===input.expectedVersion&&action.contentHash===input.contentHash,'STALE_ACTION','Refresh the current effect before reconciling.');return reconcileEffect(actor.tenantId,actionId,{adapter:input.adapter,candidateReceipt:input.providerReceipt});
}
