import type {Action,ActorContext,DependencySnapshot} from '../contracts';
export interface EffectIntent {id:string;actionId:string;tenantId:string;owner:'v2';actor:ActorContext;actionHash:string;proposalHash:string;dependencies:DependencySnapshot;authorizationId:string;executionDecision:{actorId:string;membershipVersion:number;previewHash:string;mode:ExecutionAdapter['effect'];sender:string|null;approvedAt:string};actionSnapshot:Action;adapterId:string;adapterConfigurationHash:string;idempotencyKey:string;status:'prepared'|'dispatched'|'verifying'|'uncertain'|'verified'|'failed';leaseToken:string|null;leaseUntil:string|null;providerReceipt:string|null;createdAt:string;updatedAt:string;failure:string|null;completionArtifact:string|null;deletionRequestedAt?:string;redactedAt?:string;retentionOriginalReferences?:string[]}
export interface EffectView {actionId:string;status:EffectIntent['status'];providerReceipt:string|null;completionArtifact:string|null;failure:string|null}
export interface ExecutionRequest {tenantId:string;action:Action;idempotencyKey:string}
export interface Readback {status:'pending'|'verified'|'failed';receipt:string;contentHash?:string;artifact?:string;internalDocument?:{originalReference:string;body:string};reason?:string}
export interface ExecutionAdapter {id:string;configurationHash:string;supportedKinds:Action['kind'][];effect:'internal'|'email'|'publication_readback'|'preview';sender?:string;validate?:(request:ExecutionRequest)=>void;prepare?:(request:ExecutionRequest)=>Promise<void>;dispatch(request:ExecutionRequest):Promise<{receipt:string}>;readback(request:ExecutionRequest,receipt:string|null):Promise<Readback>}
export class DispatchRejected extends Error {readonly code='PROVIDER_REJECTED';}

export interface ExecutionPreview {previewHash:string;actionVersion:number;contentHash:string;mode:ExecutionAdapter['effect'];sender?:string;recipients:string[];destination:string|null;title:string;content:string;timing?:Action['timing']}
