'use client';

import {useEffect,useRef,useState} from 'react';
import type {CommandResult,Scope,WorkspaceSnapshot} from '@/v2/contracts';
import type {ApplicabilityCommand,AgreementApplicability} from '@/v2/applicability';
import {Badge,Empty,Icon,date,human} from './Primitives';
import s from './workspace.module.css';

type AssessmentView=AgreementApplicability&{current:boolean;limitation:string};
type Row=Extract<ApplicabilityCommand,{type:'applicability.record'}>['rows'][number];
type Notice=NonNullable<Row['notice']>;
type Target=Extract<ApplicabilityCommand,{type:'applicability.record'}>['target'];
type Review={kind:'record';inventoryId:string;inspectedVersion:number;target:Target;rows:Row[];registerFingerprint:string}|{kind:'withdraw';assessment:AssessmentView;inspectedVersion:number};
type Props={data:WorkspaceSnapshot;matterId:string;busy:boolean;submit:(command:ApplicabilityCommand)=>Promise<CommandResult|null>;openDocument:(id:string)=>void};
const recordFor=(data:WorkspaceSnapshot,id:string)=>data.documents.find(x=>x.id===id);
const sameAudience=(a:Scope,b:Scope)=>a.kind===b.kind&&a.matterId===b.matterId&&JSON.stringify([...a.actorIds].sort())===JSON.stringify([...b.actorIds].sort());
const registerFingerprint=(data:WorkspaceSnapshot,inventoryId:string,target:Target)=>{const inventory=data.inventories.find(x=>x.id===inventoryId),matter=data.matters.find(x=>x.id===inventory?.matterId);return JSON.stringify({inventory,matter,documents:inventory?.documentIds.map(id=>{const document=recordFor(data,id);return {document,currentHead:data.documentHeadIds.includes(id),source:data.sources.find(x=>x.id===document?.sourceId)}}),counterparty:data.companyMemory.entities.find(x=>x.id===target.counterpartyEntityId),products:target.productEntityIds.map(id=>data.companyMemory.entities.find(x=>x.id===id)),facts:matter?.factIds.map(id=>data.facts.find(x=>x.id===id)),sources:matter?.sourceIds.map(id=>data.sources.find(x=>x.id===id))});};
export function applicabilityReviewReady(data:WorkspaceSnapshot,inventoryId:string,inspectedVersion:number,target:Target,rows:Row[],acknowledgedEmpty:boolean){
 const inventory=data.inventories.find(x=>x.id===inventoryId);
 if(!inventory?.current||inventory.status!=='active'||inspectedVersion!==data.version||rows.length!==inventory.documentIds.length||!rows.length&&!acknowledgedEmpty)return false;
 const matter=data.matters.find(x=>x.id===inventory.matterId);
 if(!matter||target.transaction!==matter.objective.trim()||!target.transaction||target.transaction.length>500||!target.jurisdiction.trim()||target.jurisdiction.length>120)return false;
 if(matter.factIds.some(id=>{const fact=data.facts.find(x=>x.id===id);return !fact||fact.status!=='confirmed'||fact.current===false||!sameAudience(fact.scope,matter.scope)}))return false;
 if(matter.sourceIds.some(id=>{const source=data.sources.find(x=>x.id===id);return !source||source.status!=='active'}))return false;
 const counterparty=target.counterpartyEntityId?data.companyMemory.entities.find(x=>x.id===target.counterpartyEntityId&&x.kind==='counterparty'&&sameAudience(x.scope,matter.scope)):null;
 if(target.counterpartyEntityId&&!counterparty||target.productEntityIds.length>20||target.factIds.length>30||new Set(target.productEntityIds).size!==target.productEntityIds.length||new Set(target.factIds).size!==target.factIds.length)return false;
 if(target.productEntityIds.some(id=>!data.companyMemory.entities.some(x=>x.id===id&&x.kind==='product'&&sameAudience(x.scope,matter.scope))))return false;
 if(target.factIds.some(id=>!matter.factIds.includes(id)||!data.facts.some(x=>x.id===id&&x.status==='confirmed'&&x.current!==false&&sameAudience(x.scope,matter.scope))))return false;
 if(rows.some(row=>row.assessment!=='unknown')&&(!counterparty||target.factIds.length===0))return false;
 if(new Set(rows.map(row=>row.documentId)).size!==rows.length||rows.some(row=>!inventory.documentIds.includes(row.documentId)))return false;
 return rows.every(row=>{const document=recordFor(data,row.documentId);if(!document||inventory.documentHashes[row.documentId]!==document.contentHash||!data.documentHeadIds.includes(document.id)||!row.reason.trim()||row.reason.length>2000)return false;
  if(row.assessment==='unknown')return row.clause===null&&row.notice==null;
  if(row.assessment==='no_notice'&&row.notice!=null)return false;
  if(row.assessment==='notice_required'){const notice=row.notice;if(!notice||!notice.trigger.trim()||notice.trigger.length>500||!notice.channel.trim()||notice.channel.length>200||!notice.timing.trim()||notice.timing.length>300||notice.recipients.length<1||notice.recipients.length>20||notice.recipients.some(value=>!value.trim()||value.length>200)||new Set(notice.recipients.map(value=>value.trim())).size!==notice.recipients.length)return false;}
  return document.authority==='executed'&&!!row.clause&&row.clause.end>row.clause.start&&row.clause.end-row.clause.start<=8000&&document.body.slice(row.clause.start,row.clause.end)===row.clause.quote;
 });
}

/** Legal reviewer assessment of every row in one named, supplied register. */
export function ApplicabilityPanel({data,matterId,busy,submit,openDocument}:Props){
 const [inventoryId,setInventoryId]=useState(''),[inspectedVersion,setInspectedVersion]=useState<number|null>(null),[rows,setRows]=useState<Record<string,Row>>({}),[noticeRecipients,setNoticeRecipients]=useState<Record<string,string>>({}),[emptyAcknowledged,setEmptyAcknowledged]=useState(false),[review,setReview]=useState<Review|null>(null),[withdrawReason,setWithdrawReason]=useState('');
 const [transaction,setTransaction]=useState(''),[jurisdiction,setJurisdiction]=useState(''),[counterpartyId,setCounterpartyId]=useState(''),[productIds,setProductIds]=useState<string[]>([]),[factIds,setFactIds]=useState<string[]>([]);
 const reviewHeading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{if(review)reviewHeading.current?.focus()},[review]);
 const matter=data.matters.find(x=>x.id===matterId),inventories=data.inventories.filter(x=>x.matterId===matterId),inventory=inventories.find(x=>x.id===inventoryId);
 const assessments=(data as WorkspaceSnapshot&{applicabilityAssessments?:AssessmentView[]}).applicabilityAssessments?.filter(x=>x.matterId===matterId)??[];
 const canReview=data.capabilities.includes('legal_reviewer');
 const counterparties=data.companyMemory.entities.filter(x=>x.kind==='counterparty'&&matter&&sameAudience(x.scope,matter.scope));
 const products=data.companyMemory.entities.filter(x=>x.kind==='product'&&matter&&sameAudience(x.scope,matter.scope));
 const facts=data.facts.filter(x=>matter?.factIds.includes(x.id)&&x.status==='confirmed'&&x.current!==false&&sameAudience(x.scope,matter.scope));
 const target:Target={transaction:transaction.trim(),jurisdiction:jurisdiction.trim(),counterpartyEntityId:counterpartyId||null,productEntityIds:productIds,factIds};
 const formRows=inventory?.documentIds.map(id=>rows[id]??{documentId:id,assessment:'unknown' as const,clause:null,notice:null,reason:''})??[];
 const ready=!!inventory&&inspectedVersion!==null&&applicabilityReviewReady(data,inventory.id,inspectedVersion,target,formRows,emptyAcknowledged);
 const frozenReady=!!review&&(review.kind==='withdraw'?data.version===review.inspectedVersion&&assessments.some(x=>x.id===review.assessment.id&&x.version===review.assessment.version&&x.status==='current'):data.version===review.inspectedVersion&&registerFingerprint(data,review.inventoryId,review.target)===review.registerFingerprint&&applicabilityReviewReady(data,review.inventoryId,review.inspectedVersion,review.target,review.rows,true));
 function start(id:string){const chosen=inventories.find(x=>x.id===id);setInventoryId(id);setInspectedVersion(data.version);setRows(Object.fromEntries((chosen?.documentIds??[]).map(documentId=>[documentId,{documentId,assessment:'unknown',clause:null,notice:null,reason:''}])));setNoticeRecipients({});setEmptyAcknowledged(false);setTransaction(matter?.objective.trim()??'');setJurisdiction('');setCounterpartyId('');setProductIds([]);setFactIds([]);setReview(null)}
 const toggle=(id:string,values:string[],set:(next:string[])=>void)=>set(values.includes(id)?values.filter(x=>x!==id):[...values,id]);
 function update(id:string,changes:Partial<Row>){setRows(previous=>({...previous,[id]:{...previous[id],documentId:id,assessment:previous[id]?.assessment??'unknown',clause:previous[id]?.clause??null,notice:previous[id]?.notice??null,reason:previous[id]?.reason??'',...changes}}))}
 function updateNotice(id:string,changes:Partial<Notice>){setRows(previous=>{const existing=previous[id];return {...previous,[id]:{...existing,documentId:id,assessment:existing?.assessment??'notice_required',clause:existing?.clause??null,reason:existing?.reason??'',notice:{trigger:existing?.notice?.trigger??'',recipients:existing?.notice?.recipients??[],channel:existing?.notice?.channel??'',timing:existing?.notice?.timing??'',...changes}}}})}
 async function submitReview(){if(!review||!frozenReady||busy)return;const command:ApplicabilityCommand=review.kind==='record'?{type:'applicability.record',inspectedVersion:review.inspectedVersion,inventoryId:review.inventoryId,target:review.target,rows:review.rows}:{type:'applicability.withdraw',assessmentId:review.assessment.id,expectedRecordVersion:review.assessment.version,reason:withdrawReason};const result=await submit(command);if(result){setReview(null);setInventoryId('');setRows({});setWithdrawReason('')}return result}
 const rowDetails=(row:Row)=>{const document=recordFor(data,row.documentId);return <article key={row.documentId} className={s.card}><div className={s.rowBetween}><h3>{document?.title??'Agreement unavailable'}</h3><Badge tone={row.assessment==='unknown'?'amber':'purple'}>{human(row.assessment)}</Badge></div><p className={s.small}>Document {row.documentId} · revision {document?.revision??'missing'} · {document?.authority??'unavailable'} authority · hash {document?.contentHash??'unavailable'}</p>{document?.amendsDocumentId&&<p className={s.small}>Separate amendment to {document.amendsDocumentId}</p>}{document&&<button className={s.textButton} onClick={()=>openDocument(document.id)}>Inspect full agreement <Icon name="arrow" size={11}/></button>}{row.clause&&<div className={s.previewBox} style={{maxHeight:190}}><p className={s.longText}>{row.clause.quote}</p><p className={s.small}>Exact offsets {row.clause.start}–{row.clause.end}</p></div>}{row.notice&&<div className={s.previewBox} style={{maxHeight:'none'}}><h4>Structured notice requirement</h4><p>Trigger: {row.notice.trigger}</p><p>Recipients: {row.notice.recipients.join('; ')}</p><p>Channel: {row.notice.channel}</p><p>Timing: {row.notice.timing}</p></div>}<p className={s.small}>Reviewer reason: {row.reason||'Not provided'}</p></article>};
 const targetDetails=(selected:Target|AgreementApplicability['target'])=>{
  const recorded='factHashes'in selected?selected:null;
  return <div className={s.stack}><p>Transaction: {selected.transaction} · jurisdiction: {selected.jurisdiction}</p><p>Counterparty: {selected.counterpartyEntityId?(()=>{const entity=data.companyMemory.entities.find(x=>x.id===selected.counterpartyEntityId);return `${entity?`${entity.name} · currently visible`:'unavailable or historical'} · ${selected.counterpartyEntityId}${recorded?.counterpartyHash?` · recorded hash ${recorded.counterpartyHash}`:''}`})():'Unknown · unresolved'}</p><p>Products: {selected.productEntityIds.length?selected.productEntityIds.map(id=>{const entity=data.companyMemory.entities.find(x=>x.id===id);return <span key={id}>{entity?`${entity.name} · currently visible`:'unavailable or historical'} · {id}{recorded?.productHashes[id]?` · recorded hash ${recorded.productHashes[id]}`:''}<br/></span>}):'None selected'}</p><div>Selected matter facts: {selected.factIds.length?selected.factIds.map(id=>{const fact=data.facts.find(x=>x.id===id);return <p key={id}>{id} · {fact?`${human(fact.predicate)} = ${JSON.stringify(fact.value)} · ${fact.status}${fact.current===false?' · historical':''} · value visible now`:'unavailable or historical'}{recorded?.factHashes[id]?` · recorded hash ${recorded.factHashes[id]}`:''}</p>}):'None selected · unresolved for decisive rows'}</div>{recorded&&<p className={s.small}>Recorded hashes identify the reviewed basis. Visible names and fact values may have changed since this assessment.</p>}</div>;
 };
 const noticeFields=(id:string,row:Row)=><div className={s.card}><h5>Reviewed notice terms for this clause</h5><p className={s.small}>Record the trigger, recipients, channel, and timing. This assessment does not send or authorize a notice.</p><label className={s.field}>Trigger<textarea value={row.notice?.trigger??''} maxLength={500} disabled={busy||inspectedVersion!==data.version} onChange={e=>updateNotice(id,{trigger:e.target.value})}/></label><label className={s.field}>Recipients · one exact recipient per line<textarea value={noticeRecipients[id]??row.notice?.recipients.join('\n')??''} disabled={busy||inspectedVersion!==data.version} onChange={e=>{const raw=e.target.value;setNoticeRecipients(previous=>({...previous,[id]:raw}));updateNotice(id,{recipients:raw.split('\n').map(value=>value.trim()).filter(Boolean)})}}/></label><div className={s.row}><label className={s.field} style={{flex:1}}>Channel<input value={row.notice?.channel??''} maxLength={200} disabled={busy||inspectedVersion!==data.version} onChange={e=>updateNotice(id,{channel:e.target.value})}/></label><label className={s.field} style={{flex:1}}>Timing<input value={row.notice?.timing??''} maxLength={300} disabled={busy||inspectedVersion!==data.version} onChange={e=>updateNotice(id,{timing:e.target.value})}/></label></div></div>;
 return <div className={s.stack}>
  <div className={s.card}><h2>Agreement applicability review</h2><p>A named legal reviewer assesses every agreement and amendment in one supplied register. Unknown rows remain unresolved. This does not certify missing external agreements or authorize notices.</p><p className={s.small}>A factual owner attests the bounded register separately. Review exact executed clauses before resolving an operative notice requirement.</p></div>
  <div className={s.card}><h3>Named supplied registers</h3>{inventories.length?<div className={s.stack}>{inventories.map(item=><div className={s.task} style={{flexWrap:'wrap'}} key={item.id}><div style={{flex:'1 1 220px',minWidth:0}}><strong>{item.title}</strong><p className={s.small}>ID {item.id} · {item.count} agreement/amendment heads · owner {item.ownerId} · valid until {date(item.validUntil)}</p><p className={s.small}>Supplied population: {item.scopeDescription}</p><Badge tone={item.current?'green':'amber'}>{item.current?'Current supplied register':item.status==='revoked'?'Withdrawn register':'Stale supplied register'}</Badge></div><button className={s.button} disabled={busy||!canReview||!item.current} onClick={()=>start(item.id)}>Review all rows</button></div>)}</div>:<Empty icon="file" title="No supplied register for this matter.">A factual owner must attest an exact current agreement and amendment register before legal applicability review.</Empty>}</div>
  {inventory&&<section className={s.card} style={{overflowWrap:'anywhere'}} aria-label="Assess every supplied agreement"><h3>{inventory.title} · every row</h3><p>{inventory.scopeDescription}</p><p className={s.small}>Inspected workspace version {inspectedVersion}. {inventory.documentIds.length} agreement/amendment heads. Draft or unknown-authority records can only remain unknown.</p><div className={s.card}><h4>Exact business target for this review</h4><p className={s.small}>The transaction is the exact current matter objective. Specify the jurisdiction. Unknown rows may keep the counterparty or facts unknown; a decisive row requires an exact current counterparty and at least one selected confirmed matter fact.</p><div className={s.row}><label className={s.field} style={{flex:1}}>Transaction or change<input value={transaction} readOnly aria-readonly="true"/></label><label className={s.field} style={{flex:1}}>Jurisdiction<input value={jurisdiction} maxLength={120} disabled={busy||inspectedVersion!==data.version} onChange={e=>setJurisdiction(e.target.value)} placeholder="Exact jurisdiction for this assessment"/></label></div><label className={s.field}>Declared counterparty<select value={counterpartyId} disabled={busy||inspectedVersion!==data.version} onChange={e=>setCounterpartyId(e.target.value)}><option value="">Unknown · unresolved</option>{counterparties.map(entity=><option key={entity.id} value={entity.id}>{entity.name} · {entity.id.slice(-8)}</option>)}</select></label><h4>Current declared products</h4>{products.length?products.map(entity=><label className={s.field} key={entity.id}><input type="checkbox" checked={productIds.includes(entity.id)} disabled={busy||inspectedVersion!==data.version} onChange={()=>toggle(entity.id,productIds,setProductIds)}/>{entity.name} · {entity.id}</label>):<p className={s.small}>No current product identity is selected in this audience.</p>}<h4>Confirmed exact matter facts</h4>{facts.length?facts.map(fact=><label className={s.field} key={fact.id}><input type="checkbox" checked={factIds.includes(fact.id)} disabled={busy||inspectedVersion!==data.version} onChange={()=>toggle(fact.id,factIds,setFactIds)}/>{human(fact.predicate)} = {JSON.stringify(fact.value)} · {fact.id}</label>):<p className={s.small}>No current confirmed matter fact is available. Decisive conclusions remain blocked.</p>}</div>{inspectedVersion!==data.version&&<p className={s.error} role="alert">The workspace changed after this register opened. Start a fresh review of every row.</p>}{inventory.documentIds.length===0&&<label className={s.field}><input type="checkbox" checked={emptyAcknowledged} onChange={e=>setEmptyAcknowledged(e.target.checked)}/>I inspected this named supplied register and confirm it contains zero agreement or amendment rows. External discovery remains unverified.</label>}
   {inventory.documentIds.map(id=>{const document=recordFor(data,id),row=rows[id]??{documentId:id,assessment:'unknown' as const,clause:null,notice:null,reason:''};return <article className={s.card} key={id}><div className={s.rowBetween}><h4>{document?.title??'Agreement unavailable'}</h4><Badge tone={document?.authority==='executed'?'green':'amber'}>{document?.authority==='executed'?'Marked executed':human(document?.authority??'unavailable')}</Badge></div><p className={s.small}>ID {id} · revision {document?.revision??'missing'} · hash {document?.contentHash??'unavailable'}{document?.amendsDocumentId?` · amendment to ${document.amendsDocumentId}`:''}</p>{document&&<button className={s.textButton} onClick={()=>openDocument(id)}>Inspect full revision <Icon name="arrow" size={11}/></button>}<label className={s.field}>Notice assessment<select value={row.assessment} disabled={!document||busy||inspectedVersion!==data.version} onChange={e=>{const assessment=e.target.value as Row['assessment'];setNoticeRecipients(previous=>({...previous,[id]:''}));update(id,{assessment,clause:null,notice:assessment==='notice_required'?{trigger:'',recipients:[],channel:'',timing:''}:null})}}><option value="unknown">Unknown · unresolved</option>{document?.authority==='executed'&&<><option value="notice_required">Notice required for supplied agreement</option><option value="no_notice">No notice under selected clause</option></>}</select></label>{row.assessment!=='unknown'&&document?.authority==='executed'&&<><p className={s.small}>Select the decisive clause in this exact executed revision with mouse, touch selection, or keyboard Shift+arrows.</p><textarea className={s.longText} aria-label={`Select decisive clause in ${document.title}`} readOnly value={document.body} style={{width:'100%',minHeight:170}} onSelect={e=>{const start=e.currentTarget.selectionStart,end=e.currentTarget.selectionEnd;update(id,{clause:end>start&&end-start<=8000?{start,end,quote:document.body.slice(start,end)}:null})}}/>{row.clause&&<div className={s.previewBox}><p className={s.longText}>{row.clause.quote}</p><p className={s.small}>Exact offsets {row.clause.start}–{row.clause.end}</p></div>}</>}{row.assessment==='notice_required'&&noticeFields(id,row)}<label className={s.field}>Specific reason {row.assessment==='unknown'?'for remaining unresolved':'for this clause interpretation'}<textarea value={row.reason} maxLength={2000} onChange={e=>update(id,{reason:e.target.value})} disabled={busy||inspectedVersion!==data.version}/></label></article>})}<div className={s.row}><button className={s.primary} disabled={busy||!canReview||!ready} onClick={()=>setReview({kind:'record',inventoryId:inventory.id,inspectedVersion:inspectedVersion!,target:structuredClone(target),rows:structuredClone(formRows),registerFingerprint:registerFingerprint(data,inventory.id,target)})}>Review frozen assessment</button><button className={s.button} onClick={()=>start(inventory.id)}>Start fresh review</button></div></section>}
  <div className={s.card} style={{overflowWrap:'anywhere'}}><h3>Assessment history</h3>{assessments.length?<div className={s.stack}>{assessments.slice().reverse().map(item=><article key={item.id} className={s.card}><div className={s.rowBetween}><h4>Supplied register {inventories.find(x=>x.id===item.inventoryId)?.title??item.inventoryId}</h4><Badge tone={item.status==='withdrawn'?'red':item.current?'green':'amber'}>{item.status==='withdrawn'?'Withdrawn':item.current?'Current':'Stale · review again'}</Badge></div><p className={s.small}>Reviewer {item.reviewerId} · version {item.version} · {date(item.createdAt)} · {item.rows.length} exact rows</p><p className={s.boundary}>{item.limitation}</p><details><summary>Inspect recorded target, context, and every assessment</summary><h5>Recorded target · {item.current?'current':'stale or withdrawn'} assessment</h5>{targetDetails(item.target)}<div className={s.stack}>{item.rows.map(rowDetails)}</div></details>{item.withdrawalReason&&<p className={s.small}>Withdrawal reason: {item.withdrawalReason}</p>}{item.status==='current'&&<button className={s.textButton} disabled={busy||!canReview} onClick={()=>{setWithdrawReason('');setReview({kind:'withdraw',assessment:item,inspectedVersion:data.version})}}>Withdraw assessment</button>}</article>)}</div>:<p className={s.small}>No legal reviewer assessment has been recorded for this supplied register.</p>}</div>
  {review&&<section className={s.card} style={{overflowWrap:'anywhere'}} aria-label="Review exact applicability decision"><h3 ref={reviewHeading} tabIndex={-1}>Review exact applicability decision</h3>{review.kind==='record'?<><p>Supplied register {data.inventories.find(x=>x.id===review.inventoryId)?.title??review.inventoryId} · owner {data.inventories.find(x=>x.id===review.inventoryId)?.ownerId} · version inspected {review.inspectedVersion}</p><p className={s.small}>{data.inventories.find(x=>x.id===review.inventoryId)?.scopeDescription}</p><div className={s.previewBox} style={{maxHeight:'none'}}><h4>Frozen target context</h4>{targetDetails(review.target)}</div><div className={s.stack}>{review.rows.length?review.rows.map(rowDetails):<p className={s.boundary}>Zero rows in this named supplied register. This does not establish external agreement completeness.</p>}</div><p className={s.boundary}>This records legal review of the supplied register only. Unknown rows remain unresolved. No notice is authorized or sent.</p></>:<><p>Withdraw assessment {review.assessment.id} · version {review.assessment.version} by {review.assessment.reviewerId}.</p><div className={s.previewBox} style={{maxHeight:'none'}}><h4>Recorded target</h4>{targetDetails(review.assessment.target)}</div><div className={s.stack}>{review.assessment.rows.map(rowDetails)}</div><label className={s.field}>Reason<textarea value={withdrawReason} maxLength={2000} onChange={e=>setWithdrawReason(e.target.value)}/></label></>}{!frozenReady&&<p className={s.error} role="alert">The register, document, or assessment changed while you reviewed it. Close and inspect current records.</p>}<div className={s.row}><button className={s.primary} disabled={busy||!canReview||!frozenReady||review.kind==='withdraw'&&!withdrawReason.trim()} onClick={()=>void submitReview()}>{review.kind==='record'?'Record named legal assessment':'Withdraw assessment'}</button><button className={s.button} onClick={()=>setReview(null)}>Close review</button></div></section>}
 </div>;
}
