'use client';

import {useCallback,useEffect,useState} from 'react';
import type {CommandResult,WorkspaceCommand,WorkspaceSnapshot} from '@/v2/contracts';
import type {AttentionItem,AttentionSettings} from '@/v2/attention';
import {Badge,human,Icon} from './Primitives';
import {Modal} from './ReviewDialog';
import s from './workspace.module.css';

type Props={data:WorkspaceSnapshot;busy:boolean;error:string;pending:boolean;submit:(command:WorkspaceCommand)=>Promise<CommandResult|null>;retryPending:()=>Promise<CommandResult|null>;clearError:()=>void};
type AttentionProps=Props&{compact?:boolean;open:(item:AttentionItem)=>void;viewAll:()=>void};
const when=(value:string|null)=>value?new Date(value).toLocaleString():'No dated obligation recorded';

export function AttentionPanel({data,busy,error,pending,submit,retryPending,clearError,compact=false,open,viewAll}:AttentionProps){
 const attention=data.attention,items=attention?.items??[],now=items.filter(item=>item.placement==='now'),digest=items.filter(item=>item.placement==='digest');
 const [review,setReview]=useState<{item:AttentionItem;decision:'acknowledged'|'dismissed';actorId:string}|null>(null),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false);
 const close=useCallback(()=>setReview(null),[]),current=review&&items.find(item=>item.id===review.item.id),fresh=!!review&&current?.fingerprint===review.item.fingerprint;
 useEffect(()=>{if(review&&(review.actorId!==data.actor.id||!current))close()},[review,data.actor.id,current,close]);
 function inspect(item:AttentionItem,decision:'acknowledged'|'dismissed'){clearError();setReview({item:structuredClone(item),decision,actorId:data.actor.id});setReason('');setConfirmed(false)}
 const summary=(item:AttentionItem)=><button className={s.attentionItem} style={{width:'100%'}} onClick={()=>open(item)}><div className={s.row}><Badge tone={item.required?'amber':'purple'}>{item.required?'Required attention':item.decisionRequired?'Your decision':'Work update'}</Badge>{item.acknowledged&&<Badge>Acknowledged · still open</Badge>}</div><strong>{item.title}</strong><small>{item.detail}</small>{item.dueAt&&<small>{human(item.deadlineType??'recorded_target')} · {when(item.dueAt)}</small>}</button>;
 if(compact)return <section className={s.sideCard}><div className={s.sideCardHead}><h2>Needs your attention</h2><Icon name="work" size={15}/></div><div className={s.sideCardBody}>{now.length?now.slice(0,3).map(item=><div key={item.id}>{summary(item)}</div>):<div className={s.emptyAttention}><span><Icon name="check" size={14}/>Room to think.</span><p>{digest.length?'Ordinary updates are grouped in your digest.':'No current item is assigned for your attention.'}</p></div>}{attention?.quietNow&&<p className={s.small}>Quiet hours are on. Required escalations remain visible.</p>}<button className={s.textButton} style={{marginTop:12}} onClick={viewAll}>View attention{items.length?` (${items.length})`:''}{digest.length?` · ${digest.length} in digest`:''}<Icon name="arrow" size={12}/></button></div></section>;
 const group=(list:AttentionItem[])=>list.map(item=><article className={s.previewBox} style={{maxHeight:'none'}} key={item.id}>{summary(item)}<div className={s.row}><button className={s.button} disabled={busy||pending||item.acknowledged} onClick={()=>inspect(item,'acknowledged')}>Acknowledge this item</button>{!item.required&&<button className={s.textButton} disabled={busy||pending} onClick={()=>inspect(item,'dismissed')}>Dismiss with a reason</button>}</div>{item.required&&<p className={s.small} style={{marginTop:10}}>Required attention stays visible until the underlying condition is resolved. Acknowledgment is not completion.</p>}</article>);
 return <section className={s.card} aria-label="Your attention feed"><div className={s.rowBetween}><h2>The next thing that needs you.</h2><Badge>In-app attention</Badge></div><p>Assigned decisions, recorded deadlines and unresolved effects are separate from ordinary updates. A dismissal records your reason; it does not close work or teach Kiara that the issue is irrelevant.</p><div className={s.row} style={{marginTop:14}}><Badge>{human(attention?.mode??'decisions')} preference</Badge>{attention?.quietNow&&<Badge>Quiet hours active</Badge>}</div><h3 style={{marginTop:20}}>Now · {now.length}</h3>{now.length?group(now):<p>No current item needs your attention now.</p>}<details style={{marginTop:18}}><summary className={s.small}>Digest · {digest.length} items · next configured time {when(attention?.nextDigestAt??null)}</summary>{digest.length?group(digest):<p className={s.small}>No ordinary update is currently grouped in your digest.</p>}</details>{!!attention?.dismissedCount&&<p className={s.small} style={{marginTop:15}}>{attention.dismissedCount} unchanged items dismissed with a reason. A changed underlying record can reappear.</p>}
 {review&&<Modal title={review.decision==='acknowledged'?'Acknowledge this exact attention item':'Dismiss this exact attention item'} close={close} error={error} footer={pending?<button className={s.primary} disabled={busy} onClick={async()=>{if(await retryPending())close()}}>Check saved attention decision</button>:<button className={s.primary} disabled={busy||!fresh||!confirmed||!reason.trim()} onClick={async()=>{if(await submit({type:'attention.decide',itemId:review.item.id,fingerprint:review.item.fingerprint,decision:review.decision,reason}))close()}}>{review.decision==='acknowledged'?'Acknowledge; keep work open':'Dismiss with this reason'}</button>}><Badge tone={review.item.required?'amber':'purple'}>{review.item.required?'Required escalation':'Ordinary attention item'}</Badge><h3 style={{marginTop:15}}>{review.item.title}</h3><p>{review.item.detail}</p>{review.item.dueAt&&<p>{human(review.item.deadlineType??'recorded_target')} · {when(review.item.dueAt)}</p>}<p className={s.documentMeta}>Inspected fingerprint: {review.item.fingerprint}</p><p>{review.decision==='acknowledged'?'This records that you saw the item. It does not satisfy a review, fulfill an obligation or verify an external effect.':'This hides only the unchanged attention item. The underlying work remains open, and a material change can bring the item back.'}</p><label className={s.field}>Reason and intended follow-up<textarea maxLength={2000} value={reason} onChange={event=>{setReason(event.target.value);setConfirmed(false)}}/></label><label className={s.field}><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>I reviewed this exact item and its effect on my attention feed.</label>{!fresh&&<p className={s.error}>This item changed. Close the preview and inspect its current basis.</p>}</Modal>}
 </section>;
}

type SettingsForm=Pick<AttentionSettings,'timezone'|'quietEnabled'|'quietStart'|'quietEnd'|'digestAt'|'approachingHours'>;
function defaults(settings:AttentionSettings|null|undefined):SettingsForm{return {timezone:settings?.timezone??'UTC',quietEnabled:settings?.quietEnabled??false,quietStart:settings?.quietStart??'18:00',quietEnd:settings?.quietEnd??'09:00',digestAt:settings?.digestAt??'09:00',approachingHours:settings?.approachingHours??24}}
export function AttentionSettingsPanel({data,busy,error,pending,submit,retryPending,clearError}:Props){
 const attention=data.attention,current=attention?.settings;
 const [review,setReview]=useState<{version:number;actorId:string}|null>(null),[form,setForm]=useState<SettingsForm>(defaults(current)),[confirmed,setConfirmed]=useState(false);
 const close=useCallback(()=>setReview(null),[]),fresh=!!review&&(current?.version??0)===review.version;
 useEffect(()=>{if(review&&review.actorId!==data.actor.id)close()},[review,data.actor.id,close]);
 const field=(key:'timezone'|'quietStart'|'quietEnd'|'digestAt')=>({value:form[key],onChange:(event:React.ChangeEvent<HTMLInputElement>)=>{setForm(old=>({...old,[key]:event.target.value}));setConfirmed(false)}});
 const valid=!!form.timezone.trim()&&['quietStart','quietEnd','digestAt'].every(key=>/^([01]\d|2[0-3]):[0-5]\d$/.test(String(form[key as keyof SettingsForm])))&&(!form.quietEnabled||form.quietStart!==form.quietEnd)&&Number.isInteger(form.approachingHours)&&form.approachingHours>=1&&form.approachingHours<=168;
 return <section className={s.card}><div className={s.rowBetween}><h2>Make room for focused work.</h2><Icon name="clock" size={17}/></div><p>Quiet hours and the digest group ordinary in-app updates. Required escalations remain visible. The approaching-deadline window changes reminders; it never changes an obligation’s due date.</p><p className={s.small} style={{marginTop:13}}>{current?.timezone??'UTC'} · {current?.quietEnabled?`Quiet ${current.quietStart}–${current.quietEnd}`:'Quiet hours off'} · Digest {current?.digestAt??'09:00'} · Remind within {current?.approachingHours??24} hours</p><p className={s.small}>These settings group in-app attention. Optional email delivery has a separate verified recipient and opt-in below.</p><button className={s.button} style={{marginTop:15}} disabled={busy||pending} onClick={()=>{clearError();setReview({version:current?.version??0,actorId:data.actor.id});setForm(defaults(current));setConfirmed(false)}}>Configure quiet hours and digest</button>
 {review&&<Modal title="Your exact attention settings" close={close} error={error} footer={pending?<button className={s.primary} disabled={busy} onClick={async()=>{if(await retryPending())close()}}>Check saved settings</button>:<button className={s.primary} disabled={busy||!fresh||!valid||!confirmed} onClick={async()=>{if(await submit({type:'attention.configure',expectedRecordVersion:review.version,...form}))close()}}>Save these attention settings</button>}><label className={s.field}>Timezone<input {...field('timezone')} placeholder="America/New_York" maxLength={100}/><small>Use an IANA timezone. The displayed schedule is evaluated in this timezone.</small></label><label className={s.field}><input type="checkbox" checked={form.quietEnabled} onChange={event=>{setForm(old=>({...old,quietEnabled:event.target.checked}));setConfirmed(false)}}/>Group ordinary items during quiet hours</label><div className={s.twoColumns}><label className={s.field}>Quiet hours start<input type="time" {...field('quietStart')}/></label><label className={s.field}>Quiet hours end<input type="time" {...field('quietEnd')}/></label></div><label className={s.field}>In-app digest time<input type="time" {...field('digestAt')}/></label><label className={s.field}>Approaching-deadline reminder window in hours<input type="number" min={1} max={168} value={form.approachingHours} onChange={event=>{setForm(old=>({...old,approachingHours:Number(event.target.value)}));setConfirmed(false)}}/><small>From 1 to 168 hours. The source-authorized due date is unchanged.</small></label><div className={s.previewBox}><h3>Schedule to save</h3><p>{form.timezone} · {form.quietEnabled?`Quiet ${form.quietStart}–${form.quietEnd}`:'Quiet hours off'}<br/>Digest {form.digestAt} · Deadline window {form.approachingHours} hours</p><p className={s.small}>Required escalations bypass quiet and digest grouping. Acknowledgment keeps required work visible.</p></div><label className={s.field}><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>I reviewed this personal schedule and its limits.</label>{!fresh&&<p className={s.error}>Your settings changed. Close and inspect their current version.</p>}</Modal>}
 </section>;
}
