'use client';

import {useCallback,useEffect,useState,type ReactNode} from 'react';
import type {CommandResult,Conversation,Matter,Scenario,WorkspaceCommand,WorkspaceSnapshot} from '@/v2/contracts';
import type {RoutingDelegationView,RoutingRuleView,RoutingTopic,ScenarioShareView} from '@/v2/collaboration';
import {Badge,Empty,human,Icon} from './Primitives';
import {Modal} from './ReviewDialog';
import s from './workspace.module.css';

type Props={data:WorkspaceSnapshot;busy:boolean;error:string;pending:boolean;submit:(command:WorkspaceCommand)=>Promise<CommandResult|null>;retryPending:()=>Promise<CommandResult|null>;clearError:()=>void};
const topicLabels:Record<RoutingTopic,string>={product_facts:'Product and deployment facts',business_decisions:'Business decisions',legal_questions:'Legal questions'};
const topicRoles:Record<RoutingTopic,string>={product_facts:'factual owner',business_decisions:'business owner',legal_questions:'legal reviewer'};
const topics=Object.keys(topicLabels) as RoutingTopic[];
function localExpiry(){const date=new Date(Date.now()+86400000);date.setMinutes(date.getMinutes()-date.getTimezoneOffset());return date.toISOString().slice(0,16)}
function validExpiry(value:string){const time=Date.parse(value);return Number.isFinite(time)&&time>Date.now()&&time<=Date.now()+30*86400000}
function expiryText(value:string){return Number.isFinite(Date.parse(value))?new Date(value).toLocaleString():'Choose an expiry'}
function Confirm({checked,change,children}:{checked:boolean;change:(next:boolean)=>void;children:ReactNode}){return <label className={s.field}><input type="checkbox" checked={checked} onChange={event=>change(event.target.checked)}/>{children}</label>}
function Retry({busy,retry,close}:{busy:boolean;retry:Props['retryPending'];close:()=>void}){return <button className={s.primary} disabled={busy} onClick={async()=>{if(await retry())close()}}>Check saved collaboration decision</button>}

export function ScenarioShareControl({scenario,unsaved,...props}:Props&{scenario:Scenario;unsaved:boolean}){
 const {data,busy,pending,error,submit,retryPending,clearError}=props;
 const [record,setRecord]=useState<{scenario:Scenario;actorId:string}|null>(null),[title,setTitle]=useState(''),[indexes,setIndexes]=useState<number[]>([]),[questions,setQuestions]=useState(false),[recipientText,setRecipientText]=useState(''),[until,setUntil]=useState(''),[confirmed,setConfirmed]=useState(false);
 const close=useCallback(()=>setRecord(null),[]);
 const current=record&&data.scenarios.find(item=>item.id===record.scenario.id);
 const fresh=!!record&&current?.version===record.scenario.version&&current?.status==='exploring';
 useEffect(()=>{if(record&&(record.actorId!==data.actor.id||!current))close()},[record,data.actor.id,current,close]);
 const recipients=recipientText.split(/[\s,]+/).filter(Boolean),distinct=new Set(recipients).size===recipients.length;
 const allowed=scenario.provenance.actorId===data.actor.id&&data.conversations.some(c=>c.id===scenario.conversationId&&c.provenance.actorId===data.actor.id);
 const reset=()=>setConfirmed(false);
 async function save(){if(!record||!fresh||!confirmed||!validExpiry(until))return;if(await submit({type:'scenario.share',scenarioId:record.scenario.id,expectedRecordVersion:record.scenario.version,title,assumptionIndexes:indexes,includeQuestions:questions,recipientActorIds:recipients,validUntil:new Date(until).toISOString()}))close()}
 return <><button className={s.button} disabled={busy||pending||unsaved||!allowed} onClick={()=>{clearError();setRecord({scenario:structuredClone(scenario),actorId:data.actor.id});setTitle(scenario.title);setIndexes([]);setQuestions(false);setRecipientText('');setUntil(localExpiry());reset()}}><Icon name="link" size={13}/>Share selected assumptions</button>
 {record&&<Modal title="Share a selected scenario snapshot" close={close} error={error} footer={pending?<Retry busy={busy} retry={retryPending} close={close}/>:<button className={s.primary} disabled={busy||!fresh||!confirmed||!indexes.length||!title.trim()||!recipients.length||!distinct||!validExpiry(until)} onClick={()=>void save()}>Share this exact selection</button>}>
 <Badge tone="purple">Exploratory snapshot · version {record.scenario.version}</Badge><p style={{marginTop:14}}>Choose the assumptions and recipients below. This shares the selected text, title and optional questions. The private conversation and other assumptions stay outside this snapshot. It creates no company fact, matter or approval.</p>
 <label className={s.field}>Snapshot title<input maxLength={300} value={title} onChange={event=>{setTitle(event.target.value);reset()}}/></label>
 <fieldset className={s.previewBox}><legend>Assumptions to share</legend>{record.scenario.assumptions.map((assumption,index)=><Confirm key={index} checked={indexes.includes(index)} change={checked=>{setIndexes(old=>checked?[...old,index].sort((a,b)=>a-b):old.filter(i=>i!==index));reset()}}>{assumption}</Confirm>)}</fieldset>
 {record.scenario.questions.length>0&&<><Confirm checked={questions} change={checked=>{setQuestions(checked);reset()}}>Include all displayed open questions</Confirm><ul>{record.scenario.questions.map((question,index)=><li key={index} className={s.small}>{question}</li>)}</ul></>}
 <label className={s.field}>Recipient workspace IDs<input value={recipientText} onChange={event=>{setRecipientText(event.target.value);reset()}} placeholder="One or more current member IDs"/><small>Separate IDs with commas. Recipients must already be provisioned and able to access any underlying evidence. No invitation or email is sent.</small></label>
 <label className={s.field}>Access expires at your local time<input type="datetime-local" value={until} onChange={event=>{setUntil(event.target.value);reset()}}/><small>Within the next 30 days. Source, scenario or access changes can make this snapshot unavailable sooner.</small></label>
 <div className={s.previewBox}><h3>What recipients will receive</h3><strong>{title||'No title yet'}</strong><ul>{indexes.map(index=><li key={index}>{record.scenario.assumptions[index]}</li>)}</ul>{questions&&record.scenario.questions.map((question,index)=><p key={index} className={s.small}>{question}</p>)}<p className={s.small}>Recipients: {recipients.join(', ')||'None selected'}<br/>Expires: {expiryText(until)}</p></div>
 <Confirm checked={confirmed} change={setConfirmed}>I inspected this selected text, the exact recipients and expiry.</Confirm>{!fresh&&<p className={s.error}>The scenario changed. Close this preview and inspect the current assumptions.</p>}
 </Modal>}</>;
}

export function SharedScenariosPanel({data,busy,error,pending,submit,retryPending,clearError}:Props){
 const [review,setReview]=useState<{record:ScenarioShareView;actorId:string}|null>(null),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false);
 const close=useCallback(()=>setReview(null),[]),records=data.sharedScenarios??[];
 const current=review&&records.find(record=>record.id===review.record.id),fresh=!!review&&current?.version===review.record.version;
 useEffect(()=>{if(review&&(review.actorId!==data.actor.id||!current))close()},[review,data.actor.id,current,close]);
 return <div className={s.stack}><div className={s.card}><h2>Share the part that helps.</h2><p>Selected scenario snapshots preserve their exploratory status. Open an exploratory scenario in Kiara to choose its exact assumptions, recipients and expiry.</p></div>{!records.length?<Empty icon="link" title="No selected scenario snapshots yet.">Your received snapshots and your own sharing decisions appear here. Private conversation history stays with its original audience.</Empty>:records.slice().reverse().map(record=><article key={record.id} className={s.card}><div className={s.rowBetween}><h2>{record.title}</h2><Badge tone={record.status==='active'?'purple':'amber'}>{human(record.status)}</Badge></div><div className={s.row} style={{marginTop:12}}><Badge>Hypothetical · not company practice</Badge><span className={s.small}>Shared by {record.grantorId}</span></div><ul>{record.assumptions.map((assumption,index)=><li key={index}>{assumption}</li>)}</ul>{record.questions.length>0&&<><h3>Included questions</h3><ul>{record.questions.map((question,index)=><li key={index}>{question}</li>)}</ul></>}<p className={s.small}>Recipients: {record.recipientActorIds.join(', ')} · Expires {expiryText(record.validUntil)}</p><p className={s.documentMeta}>Selected snapshot fingerprint: {record.snapshotHash}</p>{record.grantorId===data.actor.id&&record.status!=='revoked'&&<button className={s.button} disabled={busy||pending} onClick={()=>{clearError();setReview({record:structuredClone(record),actorId:data.actor.id});setReason('');setConfirmed(false)}}>Withdraw selected sharing</button>}</article>)}
 {review&&<Modal title="Withdraw selected scenario sharing" close={close} error={error} footer={pending?<Retry busy={busy} retry={retryPending} close={close}/>:<button className={s.primary} disabled={busy||!fresh||!confirmed||!reason.trim()} onClick={async()=>{if(await submit({type:'scenario.share_revoke',shareId:review.record.id,expectedRecordVersion:review.record.version,reason}))close()}}>Withdraw this snapshot</button>}><h3>{review.record.title}</h3><p>Recipients: {review.record.recipientActorIds.join(', ')}</p><p className={s.documentMeta}>{review.record.snapshotHash}</p><p>The snapshot will no longer appear for recipients. Your private conversation is retained. Previously viewed or copied text cannot be recalled.</p><label className={s.field}>Withdrawal reason<textarea maxLength={2000} value={reason} onChange={event=>{setReason(event.target.value);setConfirmed(false)}}/></label><Confirm checked={confirmed} change={setConfirmed}>Withdraw access to this exact shared snapshot.</Confirm>{!fresh&&<p className={s.error}>This sharing record changed. Inspect it again before deciding.</p>}</Modal>}
 </div>;
}

type RoutingReview={kind:'offer';matter:Matter;actorId:string}|{kind:'accept'|'revoke'|'route';record:RoutingDelegationView;topic?:RoutingTopic;actorId:string}|{kind:'clear';record:RoutingRuleView;actorId:string};
export function RoutingPanel({matter,...props}:Props&{matter?:Matter}){
 const {data,busy,pending,error,submit,retryPending,clearError}=props;
 const [selectedId,setSelectedId]=useState(''),[review,setReview]=useState<RoutingReview|null>(null),[recipient,setRecipient]=useState(''),[selectedTopics,setSelectedTopics]=useState<RoutingTopic[]>([]),[until,setUntil]=useState(''),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false);
 const close=useCallback(()=>setReview(null),[]),selected=matter??data.matters.find(record=>record.id===selectedId),canOffer=data.capabilities.includes('business_owner');
 const delegations=(data.delegations??[]).filter(record=>!matter||record.matterId===matter.id),rules=(data.routing??[]).filter(record=>!matter||record.matterId===matter.id);
 const current=review?.kind==='offer'?data.matters.find(record=>record.id===review.matter.id):review?.kind==='clear'?data.routing.find(record=>record.id===review.record.id):review?data.delegations.find(record=>record.id===review.record.id):undefined;
 const fresh=!!review&&!!current&&current.version===(review.kind==='offer'?review.matter.version:review.record.version);
 useEffect(()=>{if(review&&(review.actorId!==data.actor.id||!current))close()},[review,data.actor.id,current,close]);
 function open(next:RoutingReview){clearError();setReview(structuredClone(next));setRecipient('');setSelectedTopics([]);setUntil(localExpiry());setReason('');setConfirmed(false)}
 async function save(){if(!review||!fresh||!confirmed)return;let command:WorkspaceCommand;
 if(review.kind==='offer'){if(!validExpiry(until))return;command={type:'delegation.offer',matterId:review.matter.id,expectedMatterVersion:review.matter.version,recipientActorId:recipient.trim(),topics:selectedTopics,validUntil:new Date(until).toISOString()}}
 else if(review.kind==='clear')command={type:'routing.clear',ruleId:review.record.id,expectedRecordVersion:review.record.version,reason};
 else if(review.kind==='revoke')command={type:'delegation.revoke',delegationId:review.record.id,expectedRecordVersion:review.record.version,reason};
 else if(review.kind==='accept')command={type:'delegation.accept',delegationId:review.record.id,expectedRecordVersion:review.record.version};
 else command={type:'routing.set',delegationId:review.record.id,expectedRecordVersion:review.record.version,topic:review.topic!};
 if(await submit(command))close();}
 const offerValid=review?.kind!=='offer'||!!recipient.trim()&&selectedTopics.length>0&&validExpiry(until),reasonValid=review?.kind!=='revoke'&&review?.kind!=='clear'||!!reason.trim();
 return <div className={s.stack}><section className={s.card}><div className={s.rowBetween}><h2>Route the question to its owner.</h2><Icon name="company" size={17}/></div><p>Routing is bounded to one matter and question type. The recipient must already hold the required capacity, accept the delegation, and be selected by its grantor. Expiry or withdrawal restores the recorded task owner.</p><p className={s.small} style={{marginTop:12}}>Fact confirmation, business decisions, legal clearance and permission to execute remain separate. A routing choice never satisfies a review gate or sends a provider notification.</p>
 {!matter&&<label className={s.field}>Matter for a new delegation<select value={selectedId} onChange={event=>setSelectedId(event.target.value)}><option value="">Choose current work</option>{data.matters.filter(record=>!['closed','canceled'].includes(record.state)&&!record.legacyWorkflowId).map(record=><option value={record.id} key={record.id}>{record.title}</option>)}</select></label>}
 <button className={s.button} style={{marginTop:16}} disabled={busy||pending||!canOffer||!selected||['closed','canceled'].includes(selected.state)} onClick={()=>selected&&open({kind:'offer',matter:selected,actorId:data.actor.id})}>Offer a bounded delegation</button></section>
 {delegations.length===0&&<p className={s.small}>No delegation is awaiting you or offered by you in this scope.</p>}
 {delegations.slice().reverse().map(record=><article className={s.card} key={record.id}><div className={s.rowBetween}><h3>{record.recipientActorId}</h3><Badge tone={record.status==='accepted'?'green':'amber'}>{human(record.status)}</Badge></div><p>{data.matters.find(item=>item.id===record.matterId)?.title??'Permitted matter'} · Offered by {record.grantorId}</p><p className={s.small}>Expires {expiryText(record.validUntil)}</p><ul>{record.topics.map(topic=><li key={topic}>{topicLabels[topic]} · existing {topicRoles[topic]} capacity</li>)}</ul><div className={s.row}>{record.status==='offered'&&record.recipientActorId===data.actor.id&&<button className={s.primary} disabled={busy||pending} onClick={()=>open({kind:'accept',record,actorId:data.actor.id})}>Review and accept delegation</button>}{record.status==='accepted'&&record.grantorId===data.actor.id&&record.topics.map(topic=><button key={topic} className={s.button} disabled={busy||pending||rules.some(rule=>rule.delegationId===record.id&&rule.topic===topic&&rule.effective)} onClick={()=>open({kind:'route',record,topic,actorId:data.actor.id})}>Route {topicLabels[topic].toLowerCase()}</button>)}{['offered','accepted'].includes(record.status)&&<button className={s.textButton} disabled={busy||pending} onClick={()=>open({kind:'revoke',record,actorId:data.actor.id})}>Withdraw delegation</button>}</div></article>)}
 {rules.filter(rule=>rule.active).map(rule=><div className={s.card} key={rule.id}><div className={s.rowBetween}><h3>{topicLabels[rule.topic]}</h3><Badge tone={rule.effective?'green':'amber'}>{rule.effective?'Routing active':'Base owner restored'}</Badge></div><p>{data.matters.find(item=>item.id===rule.matterId)?.title??'Permitted matter'}</p><p className={s.small}>{rule.effective?'Current tasks use the accepted recipient.':'The delegation is unavailable, expired or withdrawn. Required tasks remain open with their recorded owner.'}</p>{rule.ownerId===data.actor.id&&<button className={s.textButton} disabled={busy||pending} onClick={()=>open({kind:'clear',record:rule,actorId:data.actor.id})}>Clear routing preference</button>}</div>)}
 {review&&<Modal title={review.kind==='offer'?'Offer an exact routing delegation':review.kind==='accept'?'Accept this bounded responsibility':review.kind==='route'?'Apply this question routing':review.kind==='clear'?'Clear this routing preference':'Withdraw this delegation'} close={close} error={error} footer={pending?<Retry busy={busy} retry={retryPending} close={close}/>:<button className={s.primary} disabled={busy||!fresh||!confirmed||!offerValid||!reasonValid} onClick={()=>void save()}>{review.kind==='offer'?'Send the in-app delegation offer':review.kind==='accept'?'Accept this exact delegation':review.kind==='route'?'Apply this routing preference':review.kind==='clear'?'Restore the recorded owner':'Withdraw this delegation'}</button>}>
 {review.kind==='offer'?<><h3>{review.matter.title}</h3><Badge>{human(review.matter.scope.kind)} matter · version {review.matter.version}</Badge><label className={s.field}>Recipient workspace ID<input value={recipient} onChange={event=>{setRecipient(event.target.value);setConfirmed(false)}}/><small>The recipient must already be provisioned, able to read this matter, and hold the relevant capacity.</small></label><fieldset className={s.previewBox}><legend>Bounded responsibilities</legend>{topics.map(topic=><Confirm key={topic} checked={selectedTopics.includes(topic)} change={checked=>{setSelectedTopics(old=>checked?[...old,topic]:old.filter(item=>item!==topic));setConfirmed(false)}}>{topicLabels[topic]} · {topicRoles[topic]}</Confirm>)}</fieldset><label className={s.field}>Expires at your local time<input type="datetime-local" value={until} onChange={event=>{setUntil(event.target.value);setConfirmed(false)}}/><small>{expiryText(until)} · maximum 30 days</small></label><p>The named recipient must accept before you can apply routing. No role or evidence access is granted.</p></>:<><Badge>Inspected version {review.record.version}</Badge><p className={s.documentMeta}>Matter reference: {review.record.matterId}</p>{review.kind==='clear'?<p>{topicLabels[review.record.topic]} will return to the recorded base owner.</p>:<><h3>{review.record.grantorId} → {review.record.recipientActorId}</h3><ul>{review.record.topics.map(topic=><li key={topic}>{topicLabels[topic]}</li>)}</ul><p>Valid through {expiryText(review.record.validUntil)}</p>{review.kind==='route'&&<p><strong>Apply only: {topicLabels[review.topic!]}</strong></p>}{review.kind==='accept'&&<p>You accept this exact scope and expiry. The grantor still chooses whether to apply each routing rule.</p>}{review.kind==='revoke'&&<p>Active routing will fall back to the recorded task owner. Existing evidence and decisions are retained.</p>}</>}{(review.kind==='revoke'||review.kind==='clear')&&<label className={s.field}>Reason<textarea maxLength={2000} value={reason} onChange={event=>{setReason(event.target.value);setConfirmed(false)}}/></label>}</>}
 <Confirm checked={confirmed} change={setConfirmed}>I reviewed this exact matter, responsibility, recipient and scope. Required review capacities remain unchanged.</Confirm>{!fresh&&<p className={s.error}>This record changed. Close the preview and inspect its current version.</p>}
 </Modal>}
 </div>;
}

export function ConversationLinkControl({conversation,openMatter,...props}:Props&{conversation:Conversation;openMatter:(id:string)=>void}){
 const {data,busy,error,pending,submit,retryPending,clearError}=props;
 const [review,setReview]=useState<{conversation:Conversation;actorId:string}|null>(null),[selected,setSelected]=useState<Matter|null>(null),[confirmed,setConfirmed]=useState(false);
 const close=useCallback(()=>setReview(null),[]),current=review&&data.conversations.find(record=>record.id===review.conversation.id),matter=selected&&data.matters.find(record=>record.id===selected.id);
 const fresh=!!review&&current?.version===review.conversation.version&&!!selected&&matter?.version===selected.version;
 useEffect(()=>{if(review&&(review.actorId!==data.actor.id||!current||selected&&!matter))close()},[review,data.actor.id,current,selected,matter,close]);
 if(conversation.matterId)return <button className={s.textButton} onClick={()=>openMatter(conversation.matterId!)}><Icon name="work" size={12}/>Open linked work</button>;
 return <><button className={s.textButton} disabled={busy||pending||!data.capabilities.includes('business_owner')} onClick={()=>{clearError();setReview({conversation:structuredClone(conversation),actorId:data.actor.id});setSelected(null);setConfirmed(false)}}><Icon name="link" size={12}/>Link to existing work</button>{review&&<Modal title="Continue in the same matter" close={close} error={error} footer={pending?<Retry busy={busy} retry={retryPending} close={close}/>:<button className={s.primary} disabled={busy||!fresh||!confirmed} onClick={async()=>{if(!selected)return;if(await submit({type:'conversation.link_matter',conversationId:review.conversation.id,matterId:selected.id,expectedConversationVersion:review.conversation.version,expectedMatterVersion:selected.version}))close()}}>Link this conversation</button>}><h3>{review.conversation.title}</h3><Badge>{human(review.conversation.scope.kind)} conversation · version {review.conversation.version}</Badge><p style={{marginTop:13}}>Choose existing work with exactly the same visibility. This retains the conversation and matter identities. Web messages and reviewed voice transcripts continue in this one conversation.</p><label className={s.field}>Existing matter<select value={selected?.id??''} onChange={event=>{setSelected(structuredClone(data.matters.find(record=>record.id===event.target.value)??null));setConfirmed(false)}}><option value="">Choose an existing matter</option>{data.matters.filter(record=>!['closed','canceled'].includes(record.state)&&!record.legacyWorkflowId).map(record=><option key={record.id} value={record.id}>{record.title} · {human(record.scope.kind)}</option>)}</select></label>{selected&&<div className={s.previewBox}><h3>{selected.title}</h3><p>{selected.objective}</p><Badge>{human(selected.scope.kind)} visibility · version {selected.version}</Badge></div>}<p className={s.small}>A private conversation cannot expand into broader work. Slack and email connections require their own configured, verified channel bindings.</p><Confirm checked={confirmed} change={setConfirmed}>Link these exact records while preserving their current visibility.</Confirm>{selected&&!fresh&&<p className={s.error}>One of these records changed. Close this preview and inspect the current versions.</p>}</Modal>}</>;
}
