'use client';

import {useCallback,useEffect,useState} from 'react';
import type {CommandResult,CounselEngagement,Matter,Proposal,WorkspaceCommand,WorkspaceSnapshot} from '@/v2/contracts';
import {Badge,Icon,date,human} from './Primitives';
import {Modal} from './ReviewDialog';
import {counselPreviewCurrent,proposalPreviewCurrent} from './review-intent';
import s from './workspace.module.css';

type Step='intake'|'engage'|'share'|'return'|'revoke'|'escalate';
type Review={step:Step;engagement:CounselEngagement;proposal?:Proposal;actorId:string};
type Props={data:WorkspaceSnapshot;matter:Matter;proposal?:Proposal;busy:boolean;error:string;pending:boolean;submit:(command:WorkspaceCommand)=>Promise<CommandResult|null>;retryPending:()=>Promise<CommandResult|null>;clearError:()=>void};
const titles:Record<Step,string>={intake:'Record intake and conflicts evidence',engage:'Approve counsel engagement terms',share:'Approve exact packet access',return:'Return counsel review work',revoke:'Revoke counsel packet access',escalate:'Escalate counsel coordination'};
function localFuture(hours:number){const time=new Date(Date.now()+hours*3600000);return new Date(time.getTime()-time.getTimezoneOffset()*60000).toISOString().slice(0,16)}
function iso(value:string){const n=Date.parse(value);return Number.isFinite(n)?new Date(n).toISOString():''}
function exportPacket(e:CounselEngagement){const url=URL.createObjectURL(new Blob([e.packet],{type:'text/plain;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=`kiara-counsel-packet-${e.id}.txt`;link.click();URL.revokeObjectURL(url)}

export function CounselPanel({data,matter,proposal,busy,error,pending,submit,retryPending,clearError}:Props){
  const [review,setReview]=useState<Review|null>(null),[form,setForm]=useState<Record<string,string>>({}),[confirmed,setConfirmed]=useState(false);
  const close=useCallback(()=>setReview(null),[]);
  useEffect(()=>{if(review&&(review.actorId!==data.actor.id||!data.counsel.some(e=>e.id===review.engagement.id)))setReview(null)},[data,review]);
  const field=(name:string)=>({value:form[name]??'',onChange:(event:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>)=>{setForm(old=>({...old,[name]:event.target.value}));setConfirmed(false)}});
  const open=(step:Step,engagement:CounselEngagement)=>{clearError();setConfirmed(false);setReview({step,engagement,proposal,actorId:data.actor.id});setForm({counselActorId:engagement.counselActorId??'',intakeEvidence:engagement.intakeEvidence??'',terms:engagement.terms??'',feeCap:engagement.feeCap===null?'':String(engagement.feeCap),currency:engagement.currency,responseDueAt:localFuture(72),validUntil:localFuture(24),body:proposal?.body??'',note:'',disposition:'evidence_request',reason:'non_response',detail:''})};
  const owner=data.capabilities.includes('business_owner'),closed=['closed','canceled'].includes(matter.state);
  const e=review?.engagement,current=e?data.counsel.find(x=>x.id===e.id):undefined;
  const needsProposal=review?.step==='share'||review?.step==='return';
  const preparedMatches=(engagement:CounselEngagement)=>!!proposal&&engagement.preparedProposal?.id===proposal.id&&engagement.preparedProposal.contentHash===proposal.contentHash;
  const fresh=!!e&&counselPreviewCurrent(e,current)&&(review?.step!=='share'||preparedMatches(e))&&(!needsProposal||!!review?.proposal&&proposalPreviewCurrent(review.proposal,data.proposals.find(p=>p.id===review.proposal!.id)));
  const allowed=review?.step==='return'?data.capabilities.includes('legal_reviewer')&&e?.counselActorId===data.actor.id:owner;
  const filled=!!review&&({intake:!!form.counselActorId?.trim()&&!!form.intakeEvidence?.trim(),engage:!!form.terms?.trim()&&form.feeCap!==''&&Number.isFinite(Number(form.feeCap))&&Number(form.feeCap)>=0&&/^[A-Z]{3}$/.test(form.currency??'')&&Date.parse(form.responseDueAt)>Date.now(),share:!!e?.packetHash&&!!e.counselActorId&&Date.parse(form.validUntil)>Date.now()&&Date.parse(form.validUntil)<=Date.now()+30*86400000,return:!!review.proposal&&!!form.note?.trim()&&(form.disposition==='evidence_request'||!!form.body?.trim()),revoke:!!form.detail?.trim(),escalate:!!form.detail?.trim()}[review.step]);
  async function save(){
    if(!review||!e||!fresh||!allowed||!confirmed||!filled)return;
    const base={engagementId:e.id,expectedRecordVersion:e.version};let command:WorkspaceCommand;
    switch(review.step){
      case 'intake':command={type:'counsel.intake',...base,counselActorId:form.counselActorId.trim(),conflictsCleared:true,intakeEvidence:form.intakeEvidence};break;
      case 'engage':command={type:'counsel.engage',...base,terms:form.terms,feeCap:Number(form.feeCap),currency:form.currency,responseDueAt:iso(form.responseDueAt)};break;
      case 'share':command={type:'counsel.share',...base,packetHash:e.packetHash!,recipientActorId:e.counselActorId!,validUntil:iso(form.validUntil)};break;
      case 'return':command={type:'counsel.return',...base,proposalId:review.proposal!.id,proposalHash:review.proposal!.contentHash,disposition:form.disposition as 'revised_proposal'|'evidence_request',note:form.note,...(form.disposition==='revised_proposal'?{body:form.body}:{})};break;
      case 'revoke':command={type:'counsel.revoke',...base,reason:form.detail};break;
      case 'escalate':command={type:'counsel.escalate',...base,reason:form.reason as 'non_response'|'unavailable_expertise'|'rejected_scope'|'budget_increase',detail:form.detail};break;
    }
    if(await submit(command))close();
  }
  return <>{data.counsel.filter(c=>c.matterId===matter.id).map(c=>{
    const grant=c.sharing,active=!!grant&&!grant.revokedAt&&Date.parse(grant.expiresAt)>Date.now();
    return <section className={s.card} key={c.id} aria-label={`Counsel packet for ${c.providerName??'unassigned counsel'}`}>
      <div className={s.rowBetween}><h2>{c.providerName??'Counsel not yet assigned'}</h2><Badge tone={c.status==='returned'?'green':'amber'}>{human(c.status)}</Badge></div>
      <p>{c.recipient??'No recipient or engagement created'} · Owner: {c.ownerId}</p>
      <dl className={s.definitionList} style={{margin:'18px 0'}}><dt>Reviewer identity</dt><dd>{c.counselActorId??'Not assigned to a provisioned reviewer'}</dd><dt>Intake evidence</dt><dd>{c.conflictsCleared?`Conflicts clearance recorded by ${c.intakeRecordedBy??'owner'}`:'Pending intake and conflicts clearance'}{c.intakeEvidence&&<div className={s.longText}>{c.intakeEvidence}</div>}</dd><dt>Terms approval</dt><dd>{c.engagementApproval?`Recorded by ${c.engagementApproval.actorId} on ${date(c.engagementApproval.approvedAt)}`:c.terms?'Previous approval withdrawn — new decision required':'Not approved'}</dd><dt>Last recorded scope</dt><dd>{c.terms??'Terms not approved'}</dd><dt>Professional fee cap</dt><dd>{c.feeCap===null?'Not approved':`${c.currency} ${c.feeCap.toLocaleString()}`}</dd><dt>Expected response</dt><dd>{c.responseDueAt?new Date(c.responseDueAt).toLocaleString():'Not agreed'}</dd><dt>Selected evidence</dt><dd>{c.provenance.sourceIds.length} full source records · {c.provenance.factIds?.length??0} factual assertions</dd><dt>Packet access</dt><dd>{grant?.revokedAt?`Revoked ${date(grant.revokedAt)}`:active?`Recorded grant to ${grant!.recipientActorId} until ${new Date(grant!.expiresAt).toLocaleString()}`:grant?'Sharing expired or no longer current':'Not granted'}{active&&<p>Source, fact, membership and approval validity are checked on every access.</p>}</dd></dl>
      <div className={s.row}>
        <button className={s.button} onClick={()=>exportPacket(c)}><Icon name="download" size={14}/>Export review packet</button>
        {owner&&c.route==='existing'&&!closed&&<>
          {['intake_pending','engagement_pending'].includes(c.status)&&<button className={s.button} disabled={busy} onClick={()=>open('intake',c)}>{c.conflictsCleared?'Update intake evidence':'Record intake evidence'}</button>}
          {c.conflictsCleared&&['engagement_pending','sharing_pending'].includes(c.status)&&<button className={s.button} disabled={busy} onClick={()=>open('engage',c)}>{c.engagementApproval?'Change engagement terms':'Approve engagement terms'}</button>}
          {c.status==='sharing_pending'&&c.engagementApproval&&<button className={s.primary} disabled={busy||!c.packetHash||!preparedMatches(c)} onClick={()=>open('share',c)}>Review exact sharing scope <Icon name="arrow" size={13}/></button>}
        </>}
        {!closed&&c.status==='review_pending'&&c.counselActorId===data.actor.id&&data.capabilities.includes('legal_reviewer')&&<button className={s.primary} disabled={busy||!active||!proposal} onClick={()=>open('return',c)}>Return edits or request evidence</button>}
        {owner&&!closed&&<>{active&&<button className={s.button} disabled={busy} onClick={()=>open('revoke',c)}>Revoke packet access</button>}<button className={s.textButton} disabled={busy} onClick={()=>open('escalate',c)}>Record an escalation</button></>}
      </div>
      {c.route==='existing'&&['intake_pending','engagement_pending','sharing_pending'].includes(c.status)&&!preparedMatches(c)&&<div className={s.boundary} style={{marginTop:14}}>This packet does not match the current proposal. Prepare a fresh counsel request before sharing; the prior packet is retained for history.</div>}{c.status==='unavailable'&&<p style={{marginTop:14}}>No referral provider is configured. Legal review remains pending with the matter owner; export this packet or prepare a new request for existing counsel.</p>}
      {c.reviewNotes?.length? <div style={{marginTop:20}}><h3>Returned review notes</h3>{c.reviewNotes.map((note,i)=><p key={i} className={s.longText}>{note}</p>)}{c.returnedProposalId&&<p>A separate proposal version was returned. Inspect the current proposed work before making new decisions.</p>}</div>:null}
      {c.escalation&&<div className={s.boundary} style={{marginTop:16}}>{human(c.escalation.reason)}: {c.escalation.detail} Previous sharing was revoked; changed scope, fees or recipient need a new decision.</div>}
      <details style={{marginTop:17}}><summary className={s.small}>Read full packet and selected source records</summary><div className={s.longText} style={{marginTop:15}}>{c.packet}</div></details>
      <p className={s.small} style={{marginTop:14}}>Workspace coordination only. No email invitation, provider matching or charge is initiated. Professional fees are separate from Kiara subscription fees.</p>
    </section>
  })}
  {review&&e&&<Modal title={titles[review.step]} error={error} close={close} footer={pending?<button className={s.primary} disabled={busy} onClick={async()=>{if(await retryPending())close()}}>Check saved decision</button>:<><button className={s.button} onClick={close}>Cancel</button><button className={s.primary} disabled={busy||closed||!fresh||!allowed||!filled||!confirmed} onClick={()=>void save()}>{review.step==='share'?'Grant this exact packet access':review.step==='engage'?'Approve these terms and fee cap':review.step==='intake'?'Record this intake evidence':review.step==='return'?'Return this review work':review.step==='revoke'?'Revoke this packet access':'Save escalation and revoke access'}</button></>}>
    <Badge tone="purple">Frozen review · packet version {e.version}</Badge>
    <p className={s.small} style={{marginTop:12}}>{e.providerName??'Unassigned counsel'} · {e.recipient??'No contact'} · Owner: {e.ownerId}</p>
    {review.step==='intake'&&<><p className={s.muted} style={{marginTop:15}}>Record evidence of completed intake and conflicts clearance. This is attributed manual evidence; Kiara has not verified it with a provider.</p><label className={s.field}>Provisioned legal reviewer identity<input aria-label="Provisioned legal reviewer identity" {...field('counselActorId')} placeholder={data.actor.mode==='local_demo'?'local-counsel':'Reviewer identity from workspace administrator'}/><small>{data.actor.mode==='local_demo'?'For the local demonstration, switch to the counsel role once to provision local-counsel, then return to the founder role.':'The reviewer must already be provisioned for this company and matter.'}</small></label><label className={s.field}>Intake and conflicts clearance evidence<textarea {...field('intakeEvidence')} placeholder="Who cleared conflicts, when, and where the confirmation is recorded…" maxLength={4000}/></label></>}
    {review.step==='engage'&&<><p className={s.muted} style={{marginTop:15}}>Approve the exact professional scope, fee limit and response time for {e.counselActorId}. This records internal authorization; it does not make a payment.</p><label className={s.field}>Exact engagement scope and terms<textarea {...field('terms')} placeholder="Questions counsel will answer, exclusions and agreed terms…" maxLength={100000}/></label><div className={s.row}><label className={s.field} style={{flex:1}}>Professional fee cap<input type="number" min={0} max={10000000} step="0.01" {...field('feeCap')}/></label><label className={s.field} style={{flex:1}}>Currency<input {...field('currency')} maxLength={3} placeholder="USD"/></label></div><label className={s.field}>Agreed response due (your local time)<input type="datetime-local" {...field('responseDueAt')}/></label><p className={s.small}>Professional fees are separate from subscription fees. Changes revoke prior sharing and require a new exact sharing approval.</p></>}
    {review.step==='share'&&<><div className={s.boundary} style={{marginTop:16}}>This grants the named workspace reviewer access to the complete selected records below. Read the full source text before approving.</div><dl className={s.definitionList}><dt>Exact recipient</dt><dd>{e.counselActorId}</dd><dt>Contact reference</dt><dd>{e.recipient}</dd><dt>Terms</dt><dd>{e.terms}</dd><dt>Fee limit</dt><dd>{e.currency} {e.feeCap}</dd><dt>Response due</dt><dd>{e.responseDueAt?new Date(e.responseDueAt).toLocaleString():'Unknown'}</dd><dt>Record scope</dt><dd>Matter, proposed work, engagement, {e.provenance.sourceIds.length} complete source records and {e.provenance.factIds?.length??0} factual assertions. Conversation history is not included.</dd></dl><div className={s.previewBox}><div className={s.longText}>{e.packet}</div></div><label className={s.field}>Access expires (your local time, within 30 days)<input type="datetime-local" {...field('validUntil')}/></label><div className={s.documentMeta}>Exact packet fingerprint: {e.packetHash??'Unavailable — refresh before approving'}</div><p className={s.small} style={{marginTop:12}}>No email is sent. Current source access, confirmed facts and reviewer membership remain required.</p></>}
    {review.step==='return'&&<><p className={s.muted} style={{marginTop:15}}>Assigned review of proposal version {review.proposal?.version}. Returned edits create a new proposal and invalidate prior decisions; returning work alone does not give legal clearance.</p><label className={s.field}>Review outcome<select {...field('disposition')}><option value="evidence_request">Request more evidence</option><option value="revised_proposal">Return a revised proposal</option></select></label>{form.disposition==='revised_proposal'&&<label className={s.field}>Complete revised proposal<textarea {...field('body')} style={{minHeight:260}} maxLength={100000}/></label>}<label className={s.field}>Review notes and outstanding questions<textarea {...field('note')} maxLength={8000} placeholder="Explain the evidence required or the changes returned…"/></label><details><summary className={s.small}>Inspect the proposal under review</summary><div className={s.longText}>{review.proposal?.body}</div></details></>}
    {(review.step==='revoke'||review.step==='escalate')&&<><p className={s.muted} style={{marginTop:15}}>Current packet access will be revoked. A new sharing decision is needed before the reviewer can regain access.</p>{review.step==='escalate'&&<label className={s.field}>Escalation reason<select {...field('reason')}><option value="non_response">No response</option><option value="unavailable_expertise">Required expertise unavailable</option><option value="rejected_scope">Review scope rejected</option><option value="budget_increase">Budget increase requested</option></select></label>}<label className={s.field}>{review.step==='revoke'?'Reason for revocation':'Detail and next owner action'}<textarea {...field('detail')} maxLength={review.step==='revoke'?2000:4000}/></label></>}
    <label className={s.field}><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>{review.step==='intake'?'I have reviewed the cited intake evidence and confirm that conflicts clearance is recorded.':review.step==='share'?'I reviewed the full packet, complete source records, exact recipient, terms and access expiry.':review.step==='engage'?'I approve these exact engagement terms, professional fee cap and response time.':'I reviewed this exact decision within my assigned capacity.'}</label>
    {!fresh&&<div className={s.error}>This packet or proposal changed. Close this preview and inspect the current version before deciding.</div>}
  </Modal>}
  </>;
}
