'use client';
import {useCallback,useEffect,useState} from 'react';
import type {CommandResult,CoverageEntry,LegalAuthority,Source,WorkspaceCommand,WorkspaceSnapshot} from '@/v2/contracts';
import {Badge,Empty,Icon,date,human} from './Primitives';
import {Modal} from './ReviewDialog';
import {LegalMaintenancePanel} from './LegalMaintenancePanel';
import s from './workspace.module.css';
type Step='register'|'verify'|'define'|'review'|'unavailable';
type Review={step:Step;authority?:LegalAuthority;coverage?:CoverageEntry;sources:Source[];authorities:LegalAuthority[];actorId:string};
type Props={data:WorkspaceSnapshot;busy:boolean;error:string;pending:boolean;submit:(command:WorkspaceCommand)=>Promise<CommandResult|null>;retryPending:()=>Promise<CommandResult|null>;clearError:()=>void};
const titles:Record<Step,string>={register:'Register a retained legal source',verify:'Record current source verification',define:'Define a bounded coverage scope',review:'Record named coverage review',unavailable:'Mark coverage unavailable'};
const lines=(text:string)=>text.split('\n').map(v=>v.trim()).filter(Boolean);
export function CoveragePanel({data,busy,error,pending,submit,retryPending,clearError}:Props){
 const [review,setReview]=useState<Review|null>(null),[form,setForm]=useState<Record<string,string>>({}),[selected,setSelected]=useState<string[]>([]),[confirmed,setConfirmed]=useState(false);
 const close=useCallback(()=>setReview(null),[]);
 useEffect(()=>{if(review&&(review.actorId!==data.actor.id||review.authority&&!data.legalAuthorities.some(a=>a.id===review.authority!.id)||review.coverage&&!data.coverage.some(c=>c.id===review.coverage!.id)))close()},[data,review,close]);
 const field=(name:string)=>({value:form[name]??'',onChange:(event:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>)=>{setForm(old=>({...old,[name]:event.target.value}));setConfirmed(false)}});
 const open=(step:Step,authority?:LegalAuthority,coverage?:CoverageEntry)=>{clearError();const authorities=authority?[authority]:data.legalAuthorities.filter(a=>coverage?.authorityIds?.includes(a.id));setReview({step,authority,coverage,authorities,sources:data.sources.filter(src=>authorities.some(a=>a.sourceId===src.id)),actorId:data.actor.id});setForm({authorityType:'guidance',limitations:coverage?.limitations.join('\n')??'',domain:coverage?.domain??'',jurisdiction:coverage?.jurisdiction??''});setSelected([]);setConfirmed(false)};
 const owner=data.capabilities.includes('business_owner'),legal=data.capabilities.includes('legal_reviewer');
 const fresh=!!review&&(!review.authority||data.legalAuthorities.find(a=>a.id===review.authority!.id)?.version===review.authority.version)&&(!review.coverage||data.coverage.find(c=>c.id===review.coverage!.id)?.version===review.coverage.version)&&review.authorities.every(a=>data.legalAuthorities.find(x=>x.id===a.id)?.version===a.version)&&review.sources.every(src=>data.sources.some(x=>x.id===src.id&&x.version===src.version&&x.status==='active'));
 const valid=!!review&&({register:!!form.sourceId&&!!form.title?.trim()&&!!form.sourceUrl?.startsWith('https://')&&!!form.domain?.trim()&&!!form.jurisdiction?.trim(),verify:!!form.evidence?.trim()&&Date.parse(form.reviewDueAt)>Date.now(),define:!!form.domain?.trim()&&!!form.jurisdiction?.trim()&&selected.length>0,review:!!form.evidence?.trim()&&Date.parse(form.reviewDueAt)>Date.now(),unavailable:!!form.reason?.trim()}[review.step]);
 const allowed=!!review&&(review.step==='verify'||review.step==='review'?legal:review.step==='register'?data.capabilities.includes('member'):owner);
 async function save(){if(!review||!fresh||!valid||!allowed||!confirmed)return;let command:WorkspaceCommand;
  if(review.step==='register')command={type:'coverage.source.add',sourceId:form.sourceId,title:form.title,sourceUrl:form.sourceUrl,domain:form.domain,jurisdiction:form.jurisdiction,authorityType:form.authorityType as LegalAuthority['authorityType'],...(form.publishedAt?{publishedAt:new Date(form.publishedAt).toISOString()}:{}),...(form.effectiveFrom?{effectiveFrom:new Date(form.effectiveFrom).toISOString()}:{}),...(form.effectiveUntil?{effectiveUntil:new Date(form.effectiveUntil).toISOString()}:{})};
  else if(review.step==='verify')command={type:'coverage.source.verify',authorityId:review.authority!.id,expectedRecordVersion:review.authority!.version,sourceVersion:review.sources.find(src=>src.id===review.authority!.sourceId)!.version,verificationEvidence:form.evidence,reviewDueAt:new Date(form.reviewDueAt).toISOString()};
  else if(review.step==='define')command={type:'coverage.define',domain:form.domain,jurisdiction:form.jurisdiction,authorityIds:selected,limitations:lines(form.limitations??'')};
  else if(review.step==='review')command={type:'coverage.review',coverageId:review.coverage!.id,expectedRecordVersion:review.coverage!.version,qualificationEvidence:form.evidence,reviewDueAt:new Date(form.reviewDueAt).toISOString(),limitations:lines(form.limitations??'')};
  else command={type:'coverage.unavailable',coverageId:review.coverage!.id,expectedRecordVersion:review.coverage!.version,reason:form.reason};
  if(await submit(command))close();
 }
 return <div className={s.stack}><div className={s.boundary}><Icon name="shield" size={15}/>Coverage is maintained by named reviewers against source versions and review dates. Reviewer attestation is not external certification or matter-specific legal clearance.</div>
 <div className={s.row}><button className={s.button} disabled={busy||!data.sources.some(src=>src.status==='active')} onClick={()=>open('register')}>Register retained source</button><button className={s.button} disabled={busy||!owner||!data.legalAuthorities.length} onClick={()=>open('define')}>Define coverage scope</button></div>
 {!data.coverage.length&&<Empty icon="shield" title="Coverage has not been established.">Retain the relevant source, register its jurisdiction and domain, then record source review and a qualified reviewer’s scoped assessment.</Empty>}
 {data.coverage.map(entry=><section className={s.card} key={entry.id} aria-label={`Coverage: ${entry.domain} · ${entry.jurisdiction}`}><div className={s.rowBetween}><h2>{human(entry.domain)} · {entry.jurisdiction}</h2><Badge tone={entry.status==='available'?'green':'amber'}>{human(entry.status)}</Badge></div><p>Scope owner: {entry.ownerId??'Not assigned'} · Named reviewer: {entry.qualifiedReviewerId??'Pending'}</p><p>Reviewed {date(entry.reviewedAt)} · Review due {date(entry.reviewDueAt)}</p>{entry.qualification&&<Badge tone="purple">{human(entry.qualification)}</Badge>}{entry.qualificationEvidence&&<p style={{marginTop:12}}>{entry.qualificationEvidence}</p>}<div style={{marginTop:15}}>{entry.authorityIds?.map(id=><p key={id}>{data.legalAuthorities.find(a=>a.id===id)?.title??'Authority unavailable'}</p>)}</div>{entry.limitations.map((limit,i)=><p key={i} style={{marginTop:8}}>Limit: {limit}</p>)}<div className={s.row} style={{marginTop:16}}><button className={s.button} disabled={busy||!legal} onClick={()=>open('review',undefined,entry)}>Review exact coverage scope</button><button className={s.textButton} disabled={busy||!owner} onClick={()=>open('unavailable',undefined,entry)}>Mark unavailable</button></div></section>)}
 {data.legalAuthorities.length>0&&<div className={s.card}><h2>Maintained source registry</h2>{data.legalAuthorities.map(authority=><div className={s.task} key={authority.id}><div><h3>{authority.title}</h3><p className={s.small}>{authority.domain} · {authority.jurisdiction} · {human(authority.authorityType)}</p><p className={s.small}>{authority.verifiedAt?`Review recorded ${date(authority.verifiedAt)} by ${authority.reviewOwnerId}`:'Source verification pending'} · Due {date(authority.reviewDueAt??null)}</p><p className={s.small}>Effective {date(authority.effectiveFrom)} to {date(authority.effectiveUntil)}</p><a className={s.textButton} href={authority.sourceUrl} target="_blank" rel="noreferrer">Open source reference</a></div><button className={s.button} disabled={busy||!legal} onClick={()=>open('verify',authority)}>Verify source revision</button></div>)}</div>}
 {review&&<Modal title={titles[review.step]} error={error} close={close} footer={pending?<button className={s.primary} disabled={busy} onClick={async()=>{if(await retryPending())close()}}>Check saved review</button>:<button className={s.primary} disabled={busy||!fresh||!valid||!allowed||!confirmed} onClick={()=>void save()}>{review.step==='register'?'Register for review':review.step==='define'?'Save scope for review':review.step==='unavailable'?'Mark this coverage unavailable':'Record this exact review'}</button>}>
 {review.step==='register'&&<><label className={s.field}>Retained source<select {...field('sourceId')}><option value="">Select previously retained source</option>{data.sources.filter(src=>src.status==='active').map(src=><option key={src.id} value={src.id}>{src.title}</option>)}</select></label><label className={s.field}>Registry title<input {...field('title')} maxLength={300}/></label><label className={s.field}>Exact original source URL<input type="url" {...field('sourceUrl')} placeholder="https://…"/></label><label className={s.field}>Authority type<select {...field('authorityType')}><option value="guidance">Guidance</option><option value="statute">Statute</option><option value="regulation">Regulation</option><option value="contract">Contract</option><option value="company_policy">Company policy</option></select></label></>}
 {['register','define'].includes(review.step)&&<><label className={s.field}>Exact domain<input {...field('domain')} maxLength={100} placeholder="e.g. privacy"/></label><label className={s.field}>Exact jurisdiction<input {...field('jurisdiction')} maxLength={100} placeholder="e.g. California"/></label></>}
 {review.step==='register'&&<><label className={s.field}>Published date, if known<input type="date" {...field('publishedAt')}/></label><label className={s.field}>Effective from, if known<input type="date" {...field('effectiveFrom')}/></label><label className={s.field}>Effective until, if known<input type="date" {...field('effectiveUntil')}/></label></>}
 {review.step==='define'&&<><p className={s.small}>Select authorities with exactly this domain, jurisdiction and the same access scope.</p>{data.legalAuthorities.filter(a=>a.domain===form.domain&&a.jurisdiction===form.jurisdiction).map(a=><label className={s.field} key={a.id}><input type="checkbox" checked={selected.includes(a.id)} onChange={event=>{setSelected(old=>event.target.checked?[...old,a.id]:old.filter(id=>id!==a.id));setConfirmed(false)}}/>{a.title} · {human(a.scope.kind)} scope</label>)}</>}
 {review.authority&&<><Badge tone="purple">Frozen authority · version {review.authority.version}</Badge><h3 style={{marginTop:14}}>{review.authority.title}</h3><p className={s.small}>{review.authority.domain} · {review.authority.jurisdiction} · {human(review.authority.authorityType)}</p></>}
 {review.coverage&&<><Badge tone="purple">Frozen scope · version {review.coverage.version}</Badge><h3 style={{marginTop:14}}>{review.coverage.domain} · {review.coverage.jurisdiction}</h3></>}
 {review.sources.map(source=><details key={source.id} style={{marginTop:14}}><summary className={s.small}>{source.title} · exact source version {source.version}</summary><p className={s.longText}>{source.text}</p></details>)}
 {['verify','review'].includes(review.step)&&<><label className={s.field}>{review.step==='verify'?'Source verification evidence':'Named reviewer qualification and scope evidence'}<textarea {...field('evidence')} maxLength={4000}/></label><label className={s.field}>Review due (local time, within 90 days)<input type="datetime-local" {...field('reviewDueAt')}/></label><p className={s.small}>Re-verifying sources does not silently renew coverage. Coverage requires its own current assessment.</p></>}
 {['define','review'].includes(review.step)&&<label className={s.field}>Limitations, one per line<textarea {...field('limitations')} maxLength={10000}/></label>}
 {review.step==='unavailable'&&<label className={s.field}>Reason and current limits<textarea {...field('reason')} maxLength={2000}/></label>}
 <label className={s.field}><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>I reviewed these exact sources, scope and statements within my assigned capacity.</label>{!fresh&&<div className={s.error}>The source or scope changed. Close this preview and review the current versions.</div>}
 </Modal>}
 <LegalMaintenancePanel data={data} busy={busy} error={error} pending={pending} submit={submit} retryPending={retryPending} clearError={clearError}/>
 </div>;
}
