'use client';
import {useCallback,useEffect,useState} from 'react';
import type {CommandResult,WorkspaceCommand,WorkspaceSnapshot} from '@/v2/contracts';
import type {EffortEntry,EffortStage} from '@/v2/measurement';
import {Badge,Icon,human} from './Primitives';
import {Modal} from './ReviewDialog';
import s from './workspace.module.css';
type Step='log'|'stop'|'void'|'baseline';
type Props={data:WorkspaceSnapshot;matterId?:string;busy:boolean;error:string;pending:boolean;submit:(command:WorkspaceCommand)=>Promise<CommandResult|null>;retryPending:()=>Promise<CommandResult|null>;clearError:()=>void};
const stages:EffortStage[]=['setup','research','drafting','review','correction','coordination','execution'];

export function EffortPanel({data,matterId,busy,error,pending,submit,retryPending,clearError}:Props){
 const [selected,setSelected]=useState(matterId??''),[stage,setStage]=useState<EffortStage>('review'),[now,setNow]=useState(Date.now()),[review,setReview]=useState<{step:Step;matterId:string;entry?:EffortEntry;actorId:string}|null>(null),[form,setForm]=useState<Record<string,string>>({});
 const close=useCallback(()=>setReview(null),[]);const id=matterId??selected,matter=data.matters.find(m=>m.id===id);
 const entries=(data.effortEntries??[]).filter(e=>e.matterId===id),runningAny=(data.effortEntries??[]).find(e=>e.actorId===data.actor.id&&!e.stoppedAt&&!e.voidReason),running=runningAny?.matterId?runningAny:undefined,comparison=data.effortComparisons?.find(c=>c.matterId===id),baseline=data.effortBaselines?.find(b=>b.matterId===id&&b.current),observedMatter=baseline?.observedMatterId?data.matters.find(m=>m.id===baseline.observedMatterId):null;
 useEffect(()=>{if(!running)return;const timer=setInterval(()=>setNow(Date.now()),10000);return()=>clearInterval(timer)},[running]);
 useEffect(()=>{if(review&&(review.actorId!==data.actor.id||!data.matters.some(m=>m.id===review.matterId)||review.entry&&!data.effortEntries?.some(e=>e.id===review.entry!.id)))close()},[data,review,close]);
 const field=(name:string)=>({value:form[name]??'',onChange:(event:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>)=>setForm(old=>({...old,[name]:event.target.value}))});
 const open=(step:Step,entry?:EffortEntry)=>{clearError();setReview({step,entry,matterId:entry?.matterId??id,actorId:data.actor.id});setForm({stage,method:'observed_comparable_work'})};
 const fresh=!review?.entry||data.effortEntries?.find(e=>e.id===review.entry!.id)?.version===review.entry.version;
 const filled=review?.step==='void'?!!form.reason?.trim():!!form.evidence?.trim()&&(review?.step==='stop'||Number(form.minutes)>0&&Number(form.minutes)<=100000)&&(review?.step!=='baseline'||!!form.scope?.trim());
 async function save(){if(!review||!fresh||!filled)return;let command:WorkspaceCommand;
  if(review.step==='stop')command={type:'effort.stop',entryId:review.entry!.id,expectedRecordVersion:review.entry!.version,evidence:form.evidence};
  else if(review.step==='void')command={type:'effort.void',entryId:review.entry!.id,expectedRecordVersion:review.entry!.version,reason:form.reason};
  else if(review.step==='baseline')command={type:'baseline.record',matterId:review.matterId,minutes:Number(form.minutes),method:form.method as 'observed_comparable_work'|'estimate',comparisonScope:form.scope,evidence:form.evidence,...(form.method==='observed_comparable_work'&&form.observedMatterId?{observedMatterId:form.observedMatterId}:{})};
  else command={type:'effort.log',matterId:review.matterId,stage:form.stage as EffortStage,minutes:Number(form.minutes),evidence:form.evidence};
  if(await submit(command))close();
 }
 return <section className={s.card} style={{marginBottom:22}} aria-label="Human effort and comparable work"><h2>Human effort, with a comparison you can inspect.</h2><p>Record all stages, including setup, review and correction. Elapsed timers include idle time; manual entries are attributed reports. Matter totals and goal-only totals remain separate.</p>
 {!matterId&&<label className={s.field}>Matter to measure<select value={selected} onChange={event=>setSelected(event.target.value)}><option value="">Choose a matter</option>{data.matters.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select></label>}
 {running&&<div className={s.boundary} style={{marginTop:15}}><Icon name="clock" size={15}/><div>Your {human(running.stage).toLowerCase()} timer is running · {Math.max(0,(now-Date.parse(running.startedAt))/60000).toFixed(1)} elapsed minutes.<br/><button className={s.textButton} disabled={busy} onClick={()=>open('stop',running)}>Stop and describe the work</button></div></div>}
 {matter&&<><div className={s.row}><label className={s.field} style={{flex:1}}>Work stage<select value={stage} disabled={busy} onChange={event=>setStage(event.target.value as EffortStage)}>{stages.map(stage=><option key={stage} value={stage}>{human(stage)}</option>)}</select></label><button className={s.button} disabled={busy||!!runningAny} onClick={()=>void submit({type:'effort.start',matterId:id,stage})}><Icon name="clock" size={13}/>Start elapsed timer</button><button className={s.button} disabled={busy||!!runningAny} onClick={()=>open('log')}>Log actual time</button></div>
 <div className={s.outcomeStats} style={{marginTop:17}}><div className={s.stat}><strong>{comparison?.recordedMinutes??0}</strong><span>Recorded matter minutes</span><small>All seven work stages</small></div><div className={s.stat}><strong>{comparison?.baselineMinutes??'—'}</strong><span>Comparable matter baseline</span><small>{comparison?.baselineMethod?human(comparison.baselineMethod):'No baseline recorded'}</small></div><div className={s.stat}><strong>{comparison?.differenceMinutes===null||comparison?.differenceMinutes===undefined?'—':comparison.differenceMinutes}</strong><span>Matter-only difference</span><small>Baseline minus matter effort</small></div></div>
 <p className={s.small} style={{marginTop:12}}>Attributed correction rework: {comparison?.correctionMinutes??0} minutes across {comparison?.correctionIntervals??0} completed intervals. These minutes are already included in recorded effort.</p>
 <p className={s.small}>{comparison?.interpretation??'No savings claim can be made from an incomplete work log.'} {comparison?.runningTimers?`${comparison.runningTimers} running timers are not yet included.`:''} {comparison&&!comparison.matterClosed?'The matter remains open.':''}</p>
 {baseline&&<details style={{marginTop:15}}><summary className={s.small}>Inspect baseline and comparison scope</summary><p>{baseline.comparisonScope}</p><p>{baseline.evidence}</p><p className={s.small}>{human(baseline.method)} · {baseline.provenance.actorId}</p>{baseline.observedMatterId&&<p className={s.small}>Observed case: {observedMatter?`${observedMatter.title} (${observedMatter.id})`:'Unavailable'} · {comparison?.baselineBindingStatus==='stale'?'Changed since baseline recording; review a successor baseline':'Exact recorded basis current'}</p>}</details>}
 <button className={s.textButton} style={{marginTop:13}} disabled={busy||!data.capabilities.includes('business_owner')} onClick={()=>open('baseline')}>{baseline?'Record a successor baseline':'Add an evidenced comparable baseline'}</button>
 <div style={{marginTop:15}}>{entries.map(entry=><div className={s.task} key={entry.id}><div><h3>{human(entry.stage)} · {entry.minutes===null?'Running':`${entry.minutes} minutes`}</h3><p className={s.small}>{human(entry.method)} · {entry.actorId}</p><p className={s.small}>{entry.voidReason?`Excluded: ${entry.voidReason}`:entry.evidence}</p></div>{entry.voidReason?<Badge>Excluded</Badge>:entry.actorId===data.actor.id&&<button className={s.textButton} disabled={busy} onClick={()=>open('void',entry)}>Exclude with a reason</button>}</div>)}</div></>}
 {review&&<Modal title={review.step==='baseline'?'Record a comparable baseline':review.step==='stop'?'Stop and attribute elapsed time':review.step==='void'?'Exclude this effort record':'Log actual human time'} error={error} close={close} footer={pending?<button className={s.primary} disabled={busy} onClick={async()=>{if(await retryPending())close()}}>Check saved entry</button>:<button className={s.primary} disabled={busy||!fresh||!filled} onClick={()=>void save()}>{review.step==='stop'?'Stop timer and save elapsed time':review.step==='void'?'Exclude this record':'Save this attributed record'}</button>}>
 <p className={s.muted}>{data.matters.find(m=>m.id===review.matterId)?.title}</p>
 {review.entry&&<div className={s.previewBox}><p className={s.small}>{human(review.entry.stage)} · {review.entry.actorId} · version {review.entry.version}</p><p>{review.entry.minutes===null?'Timer includes all elapsed time since '+new Date(review.entry.startedAt).toLocaleString():`${review.entry.minutes} recorded minutes`}</p></div>}
 {review.step==='void'?<label className={s.field}>Reason for exclusion<textarea {...field('reason')} maxLength={3000}/></label>:<>{review.step==='log'&&<label className={s.field}>Work stage<select {...field('stage')}>{stages.map(stage=><option key={stage} value={stage}>{human(stage)}</option>)}</select></label>}{review.step!=='stop'&&<label className={s.field}>{review.step==='baseline'?'Comparable minutes':'Actual minutes worked'}<input type="number" min="0.1" max="100000" step="0.1" {...field('minutes')}/></label>}{review.step==='baseline'&&<><label className={s.field}>Baseline evidence type<select {...field('method')}><option value="observed_comparable_work">Observed comparable work</option><option value="estimate">Explicit estimate</option></select></label>{form.method==='observed_comparable_work'&&<label className={s.field}>Completed Kiara comparison case (optional)<select {...field('observedMatterId')}><option value="">Observed work outside Kiara; no paired-case binding</option>{data.matters.filter(item=>item.id!==review.matterId&&item.state==='closed').map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label>}<label className={s.field}>Equivalent work, scope and quality<textarea {...field('scope')} maxLength={3000}/></label></>}<label className={s.field}>{review.step==='stop'?'What this elapsed time includes, including idle time':review.step==='baseline'?'Evidence or explicit estimating assumptions':'Work performed and source of the time report'}<textarea {...field('evidence')} maxLength={3000}/></label><p className={s.small}>No customer or financial savings claim is created by this record.</p></>}
 {!fresh&&<div className={s.error}>This entry changed. Close the preview and inspect the current record.</div>}
 </Modal>}
 {!matterId&&<GoalEffortPanel data={data} busy={busy} error={error} pending={pending} submit={submit} retryPending={retryPending} clearError={clearError}/>}
 </section>;
}

function GoalEffortPanel({data,busy,error,pending,submit,retryPending,clearError}:Props){
 const [selected,setSelected]=useState(''),[stage,setStage]=useState<EffortStage>('review'),[now,setNow]=useState(Date.now());
 const [review,setReview]=useState<{step:Step;goalId:string;entry?:EffortEntry;actorId:string}|null>(null),[form,setForm]=useState<Record<string,string>>({});
 const close=useCallback(()=>setReview(null),[]),goal=data.value.goals.find(g=>g.id===selected);
 const entries=(data.effortEntries||[]).filter(e=>e.goalId===goal?.id&&!e.matterId),running=(data.effortEntries||[]).find(e=>e.actorId===data.actor.id&&!e.stoppedAt&&!e.voidReason),runningGoal=data.value.goals.find(g=>g.id===running?.goalId);
 const comparison=data.goalEffortComparisons?.find(c=>c.goalId===goal?.id),baseline=data.effortBaselines?.find(b=>b.goalId===goal?.id&&!b.matterId&&b.current);
 useEffect(()=>{if(!running)return;const timer=setInterval(()=>setNow(Date.now()),10000);return()=>clearInterval(timer)},[running]);
 useEffect(()=>{if(review&&(review.actorId!==data.actor.id||!data.value.goals.some(g=>g.id===review.goalId)||review.entry&&!data.effortEntries?.some(e=>e.id===review.entry!.id)))close()},[data,review,close]);
 const field=(name:string)=>({value:form[name]??'',onChange:(event:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>)=>setForm(old=>({...old,[name]:event.target.value}))});
 const open=(step:Step,entry?:EffortEntry)=>{if(!goal&&!entry)return;clearError();setReview({step,goalId:entry?.goalId||goal!.id,entry,actorId:data.actor.id});setForm({stage,method:'observed_comparable_work'})};
 const fresh=!review?.entry||data.effortEntries?.find(e=>e.id===review.entry!.id)?.version===review.entry.version;
 const filled=review?.step==='void'?!!form.reason?.trim():!!form.evidence?.trim()&&(review?.step==='stop'||Number(form.minutes)>0&&Number(form.minutes)<=100000)&&(review?.step!=='baseline'||!!form.scope?.trim());
 async function save(){if(!review||!fresh||!filled)return;let command:WorkspaceCommand;
  if(review.step==='stop')command={type:'effort.stop',entryId:review.entry!.id,expectedRecordVersion:review.entry!.version,evidence:form.evidence};
  else if(review.step==='void')command={type:'effort.void',entryId:review.entry!.id,expectedRecordVersion:review.entry!.version,reason:form.reason};
  else if(review.step==='baseline')command={type:'baseline.record',goalId:review.goalId,minutes:Number(form.minutes),method:form.method as 'observed_comparable_work'|'estimate',comparisonScope:form.scope,evidence:form.evidence};
  else command={type:'effort.log',goalId:review.goalId,stage:form.stage as EffortStage,minutes:Number(form.minutes),evidence:form.evidence};
  if(await submit(command))close();
 }
 return <div className={s.stack} style={{marginTop:24}} aria-label="Goal-only human effort"><h3>Effort toward a goal, before or apart from a matter</h3><p className={s.small}>Record setup, review and correction for a useful answer without creating a matter. Goal effort is compared separately and never added to a matter total.</p>
  <label className={s.field}>Goal to measure<select value={goal?.id||''} onChange={event=>setSelected(event.target.value)}><option value="">Choose your goal</option>{data.value.goals.map(g=><option value={g.id} key={g.id}>{g.title}</option>)}</select></label>
  {running&&!!running.goalId&&<div className={s.boundary}><Icon name="clock" size={15}/><div>Timer for {runningGoal?.title??'another available goal'}: {human(running.stage).toLowerCase()} · {Math.max(0,(now-Date.parse(running.startedAt))/60000).toFixed(1)} elapsed minutes.<br/><button className={s.textButton} disabled={busy} onClick={()=>open('stop',running)}>Stop and describe that goal's work</button></div></div>}
  {goal&&<><div className={s.row}><label className={s.field} style={{flex:1}}>Work stage<select value={stage} disabled={busy} onChange={event=>setStage(event.target.value as EffortStage)}>{stages.map(item=><option key={item} value={item}>{human(item)}</option>)}</select></label><button className={s.button} disabled={busy||!!running} onClick={()=>void submit({type:'effort.start',goalId:goal.id,stage})}><Icon name="clock" size={13}/>Start elapsed timer</button><button className={s.button} disabled={busy||!!running} onClick={()=>open('log')}>Log actual time</button></div>
   <div className={s.outcomeStats}><div className={s.stat}><strong>{comparison?.recordedMinutes??0}</strong><span>Goal-only minutes</span><small>All seven work stages</small></div><div className={s.stat}><strong>{comparison?.baselineMinutes??'—'}</strong><span>Comparable goal baseline</span><small>{comparison?.baselineMethod?human(comparison.baselineMethod):'No baseline recorded'}</small></div><div className={s.stat}><strong>{comparison?.differenceMinutes===null||comparison?.differenceMinutes===undefined?'—':comparison.differenceMinutes}</strong><span>Goal-only difference</span><small>Shown after reported achievement</small></div></div>
   <p className={s.small}>Attributed correction rework: {comparison?.correctionMinutes??0} minutes across {comparison?.correctionIntervals??0} completed intervals. Already included in the goal total.</p><p className={s.small}>{comparison?.interpretation}</p>
   {baseline&&<details><summary className={s.small}>Inspect goal baseline and comparison scope</summary><p>{baseline.comparisonScope}</p><p>{baseline.evidence}</p><p className={s.small}>{human(baseline.method)} · {baseline.provenance.actorId}</p></details>}
   <button className={s.textButton} disabled={busy} onClick={()=>open('baseline')}>{baseline?'Record a successor goal baseline':'Add a goal-only comparable baseline'}</button>
   <div>{entries.map(entry=><div className={s.task} key={entry.id}><div><h3>{human(entry.stage)} · {entry.minutes===null?'Running':`${entry.minutes} minutes`}</h3><p className={s.small}>{human(entry.method)} · {entry.actorId}</p><p className={s.small}>{entry.voidReason?`Excluded: ${entry.voidReason}`:entry.evidence}</p></div>{entry.voidReason?<Badge>Excluded</Badge>:<button className={s.textButton} disabled={busy} onClick={()=>open('void',entry)}>Exclude with a reason</button>}</div>)}</div></>}
  {review&&<Modal title={review.step==='baseline'?'Record a goal-only comparable baseline':review.step==='stop'?'Stop and attribute goal time':review.step==='void'?'Exclude this goal effort':'Log actual goal effort'} error={error} close={close} footer={pending?<button className={s.primary} disabled={busy} onClick={async()=>{if(await retryPending())close()}}>Check saved entry</button>:<button className={s.primary} disabled={busy||!fresh||!filled} onClick={()=>void save()}>{review.step==='stop'?'Stop timer and save elapsed time':review.step==='void'?'Exclude this record':'Save this attributed record'}</button>}>
   <p className={s.muted}>{data.value.goals.find(g=>g.id===review.goalId)?.title}</p>{review.entry&&<div className={s.previewBox}><p className={s.small}>{human(review.entry.stage)} · version {review.entry.version}</p><p>{review.entry.minutes===null?'Timer includes all elapsed time since '+new Date(review.entry.startedAt).toLocaleString():`${review.entry.minutes} recorded minutes`}</p></div>}
   {review.step==='void'?<label className={s.field}>Reason for exclusion<textarea {...field('reason')} maxLength={3000}/></label>:<>{review.step==='log'&&<label className={s.field}>Work stage<select {...field('stage')}>{stages.map(item=><option key={item} value={item}>{human(item)}</option>)}</select></label>}{review.step!=='stop'&&<label className={s.field}>{review.step==='baseline'?'Comparable goal minutes':'Actual minutes worked'}<input type="number" min="0.1" max="100000" step="0.1" {...field('minutes')}/></label>}{review.step==='baseline'&&<><label className={s.field}>Baseline evidence type<select {...field('method')}><option value="observed_comparable_work">Observed comparable work</option><option value="estimate">Explicit estimate</option></select></label><label className={s.field}>Equivalent goal, scope and quality<textarea {...field('scope')} maxLength={3000}/></label></>}<label className={s.field}>{review.step==='stop'?'What this elapsed time includes, including idle time':review.step==='baseline'?'Evidence or explicit estimating assumptions':'Work performed and source of the time report'}<textarea {...field('evidence')} maxLength={3000}/></label><p className={s.small}>This goal-only record does not count matter work or certify savings.</p></>}
   {!fresh&&<div className={s.error}>This entry changed. Close the preview and inspect the current record.</div>}
  </Modal>}
 </div>;
}
