'use client';

import {useCallback,useEffect,useRef,useState} from 'react';
import type {WorkspaceSnapshot} from '@/v2/contracts';
import type {EmailIntakeView,EmailReviewInput} from '@/v2/integrations/email';
import {Badge,human} from './Primitives';
import {Modal} from './ReviewDialog';
import s from './workspace.module.css';

export type EmailDecisionAttempt={id:string;input:EmailReviewInput};
type Props={data:WorkspaceSnapshot;busy:boolean;blocked:boolean;error:string;attempt:EmailDecisionAttempt|null;decide:(id:string,input:EmailReviewInput,retry?:boolean)=>Promise<EmailIntakeView|null>;clearError:()=>void};
type Preview={actorId:string;intake:EmailIntakeView};
type EmailEnvelope={from?:string;receivedAt?:string;messageId?:string;text?:string|null;authentication?:Record<string,string>;attachments?:{id:string;filename:string|null;contentType:string;bytes:number;extraction:string}[];limitations?:string[]};
function envelope(value:string):EmailEnvelope|null{try{const parsed=JSON.parse(value);if(!parsed||typeof parsed!=='object'||Array.isArray(parsed)||typeof parsed.from!=='string'||!(typeof parsed.text==='string'||parsed.text===null)||!Array.isArray(parsed.attachments)||!Array.isArray(parsed.limitations))return null;return parsed as EmailEnvelope}catch{return null}}
export function EmailIntakePanel({data,busy,blocked,error,attempt,decide,clearError}:Props){
 const [preview,setPreview]=useState<Preview|null>(null),[loading,setLoading]=useState(false),[loadError,setLoadError]=useState(''),[decision,setDecision]=useState<'accept'|'reject'>('reject'),[confirmed,setConfirmed]=useState(false),sequence=useRef(0),actorId=useRef(data.actor.id);actorId.current=data.actor.id;
 const close=useCallback(()=>{sequence.current++;setPreview(null);setLoading(false);setLoadError('')},[]);
 const current=preview&&data.emailIntakes?.find(i=>i.intakeId===preview.intake.intakeId),source=preview&&data.sources.find(s=>s.id===preview.intake.sourceId);
 const fresh=!!preview&&current?.reviewAvailable&&current.status===preview.intake.status&&source?.version===preview.intake.sourceVersion&&source?.contentHash===preview.intake.sourceHash;
 useEffect(()=>{if(preview&&(preview.actorId!==data.actor.id||!current?.reviewAvailable))close()},[data.actor.id,current,preview,close]);
 async function inspect(id:string){const seq=++sequence.current,actor=data.actor.id;clearError();setPreview(null);setLoading(true);setLoadError('');setConfirmed(false);setDecision('reject');try{const response=await fetch(`/api/v2/email/intakes/${encodeURIComponent(id)}/review`,{cache:'no-store'}),payload=await response.json();if(!response.ok)throw new Error(payload.error?.message??'This received source is unavailable.');if(seq===sequence.current&&actorId.current===actor)setPreview({actorId:actor,intake:payload.intake})}catch(e){if(seq===sequence.current)setLoadError(e instanceof Error?e.message:'The source preview could not be loaded.')}finally{if(seq===sequence.current)setLoading(false)}}
 const content=preview?.intake.source?envelope(preview.intake.source.text):null;
 return <section className={s.card} aria-label="Received email evidence"><div className={s.rowBetween}><h2>Review what arrived.</h2><Badge>Received evidence</Badge></div><p>A configured receiving installation retains email as source evidence. Sender assertions, forwarded headers and attached documents do not become company facts, legal approval or instructions to act.</p>{loadError&&<p className={s.error} role="alert">{loadError}</p>}{loading&&<p role="status" className={s.small}>Loading your permitted retained source…</p>}{attempt&&<div className={s.boundary}><p>The decision response was interrupted. Check the saved result with the same inspected source and decision before starting another mutation.</p><button className={s.button} disabled={busy} onClick={async()=>{if(await decide(attempt.id,attempt.input,true))close()}}>Check saved intake decision</button></div>}{!data.emailIntakes?.length?<p className={s.small} style={{marginTop:14}}>No received intake is available in your receiving-owner scope. Manual document intake remains available; this does not imply an email connection is configured.</p>:data.emailIntakes.map(item=><article className={s.previewBox} key={item.intakeId}><div className={s.rowBetween}><h3>{item.sourceTitle??'Received source unavailable'}</h3><Badge tone={item.status==='quarantined'?'amber':'neutral'}>{item.status==='quarantined'?'Quarantined · owner review':item.status==='accepted'?'Admitted as untrusted evidence':human(item.status)}</Badge></div>{item.failureCode&&<p className={s.small}>{human(item.failureCode.toLowerCase())}</p>}<p className={s.documentMeta}>Intake reference: {item.intakeId}</p><button className={s.button} disabled={busy||blocked||loading||!item.reviewAvailable} onClick={()=>void inspect(item.intakeId)}>Inspect retained email</button></article>)}
  {preview&&<Modal title="Inspect the exact received evidence" close={close} error={error||loadError} footer={attempt?<button className={s.primary} disabled={busy} onClick={async()=>{if(await decide(attempt.id,attempt.input,true))close()}}>Check saved intake decision</button>:preview.intake.status==='quarantined'?<button className={s.primary} disabled={busy||blocked||!fresh||!confirmed||!data.capabilities.includes('member')||!preview.intake.sourceVersion||!preview.intake.sourceHash||!preview.intake.receiptHash} onClick={async()=>{const i=preview.intake;if(await decide(i.intakeId,{expectedSourceVersion:i.sourceVersion!,expectedSourceHash:i.sourceHash!,expectedReceiptHash:i.receiptHash!,decision}))close()}}>{decision==='accept'?'Admit this source as untrusted evidence':'Reject this source from retrieval'}</button>:<button className={s.button} onClick={close}>Close inspected source</button>}>
   <div className={s.row}><Badge>{human(preview.intake.status)}</Badge><Badge>Unknown authority</Badge><Badge>{preview.intake.source?.originalRetained?'Original retained':'No original receipt available'}</Badge></div><h3 style={{marginTop:16}}>{preview.intake.source?.title??'Received source'}</h3>
   {content?<><dl className={s.definitionList}><dt>From assertion</dt><dd>{content.from}</dd><dt>Received</dt><dd>{content.receivedAt}</dd><dt>Message reference</dt><dd>{content.messageId}</dd><dt>Provider authentication</dt><dd>{Object.entries(content.authentication??{}).map(([key,value])=>`${key.toUpperCase()}: ${value}`).join(' · ')||'Unknown'}</dd></dl><div className={s.previewBox}><div className={s.longText}>{content.text||'No extracted plain-text body. Inspect the retained source limitations before deciding.'}</div></div><h3 style={{marginTop:18}}>Attachments · preserved, not parsed</h3>{content.attachments?.length?content.attachments.map((file,index)=><p className={s.small} key={`${file.id}-${index}`}>{file.filename||'Unnamed attachment'} · {file.contentType} · {file.bytes} bytes · no extracted attachment text</p>):<p className={s.small}>No attachment metadata was retained.</p>}<div className={s.boundary} style={{display:'block'}}>{content.limitations?.map((line,index)=><p key={index}>{line}</p>)}</div></>:<div className={s.previewBox}><div className={s.longText}>{preview.intake.source?.text}</div></div>}
   <p className={s.documentMeta}>Inspected source version {preview.intake.sourceVersion}<br/>Content fingerprint: {preview.intake.sourceHash}<br/>Intake receipt fingerprint: {preview.intake.receiptHash}</p>
   {preview.intake.status==='quarantined'&&<><label className={s.field}>Evidence admission decision<select value={decision} onChange={e=>{setDecision(e.target.value as typeof decision);setConfirmed(false)}}><option value="reject">Reject from retrieval</option><option value="accept">Admit as untrusted evidence</option></select></label><p>Admission permits retrieval of this source within its existing scope. It does not authenticate a forwarded identity, extract attachment text, confirm a fact or approve any action.</p><label className={s.field}><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed the exact retained text, sender limits and unparsed attachments.</label>{!fresh&&<p className={s.error}>The source or its receiving permission changed. Close and inspect the current intake.</p>}</>}
  </Modal>}
 </section>;
}
