'use client';

import {useEffect,useRef,useState} from 'react';
import type {CommandResult,Matter,Scope,Source,WorkspaceCommand,WorkspaceSnapshot} from '@/v2/contracts';
import {Badge,Empty,Icon,date,human} from './Primitives';
import s from './workspace.module.css';

type LinkCommand=Extract<WorkspaceCommand,{type:'event.link_matter'}>;
type Review={command:LinkCommand;inspectedVersion:number;fingerprint:string};
type Props={data:WorkspaceSnapshot;matter:Matter;busy:boolean;submit:(command:WorkspaceCommand)=>Promise<CommandResult|null>;openSource:(id:string)=>void;openConversation:(id:string)=>void};
const sameAudience=(a:Scope,b:Scope)=>a.kind===b.kind&&a.matterId===b.matterId&&JSON.stringify([...a.actorIds].sort())===JSON.stringify([...b.actorIds].sort());
const provider=(source:Source)=>source.kind==='github'||source.kind==='slack'||source.kind==='drive';
const ingested=(data:WorkspaceSnapshot,source:Source)=>data.events.some(event=>event.type==='event.ingest'&&event.recordId===source.id);

export function eventLinkCandidates(data:WorkspaceSnapshot,matterId:string){
 const matter=data.matters.find(item=>item.id===matterId);
 if(!matter||matter.legacyWorkflowId||['closed','canceled'].includes(matter.state))return [];
 const linked=new Set(data.matters.flatMap(item=>item.sourceIds));
 return data.sources.filter(source=>provider(source)&&source.status==='active'&&source.observation?.state==='current'&&!!source.installationGrant&&ingested(data,source)&&sameAudience(source.scope,matter.scope)&&!linked.has(source.id));
}
export const eventLinkFingerprint=(data:WorkspaceSnapshot,command:LinkCommand)=>JSON.stringify({matter:data.matters.find(item=>item.id===command.matterId),source:data.sources.find(item=>item.id===command.sourceId),ingest:data.events.filter(event=>event.type==='event.ingest'&&event.recordId===command.sourceId),links:data.matters.filter(item=>item.sourceIds.includes(command.sourceId)).map(item=>item.id)});
export function eventLinkReviewReady(data:WorkspaceSnapshot,command:LinkCommand,inspectedVersion:number,inspectedFingerprint:string){
 const matter=data.matters.find(item=>item.id===command.matterId),source=data.sources.find(item=>item.id===command.sourceId);
 return !!matter&&!!source&&data.version===inspectedVersion&&matter.version===command.expectedMatterVersion&&matter.ownerId===data.actor.id&&source.version===command.expectedSourceVersion&&data.capabilities.includes('business_owner')&&eventLinkCandidates(data,matter.id).some(item=>item.id===source.id)&&eventLinkFingerprint(data,command)===inspectedFingerprint;
}

/** Explicit owner inspection of authenticated provider observations before linking to work. */
export function EventLinkPanel({data,matter,busy,submit,openSource,openConversation}:Props){
 const [review,setReview]=useState<Review|null>(null),[saved,setSaved]=useState('');
 const heading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{if(review)heading.current?.focus()},[review]);
 const candidates=eventLinkCandidates(data,matter.id);
 const history=matter.sourceIds.map(id=>data.sources.find(source=>source.id===id)).filter((source):source is Source=>!!source&&provider(source));
 const ready=!!review&&eventLinkReviewReady(data,review.command,review.inspectedVersion,review.fingerprint);
 function inspect(source:Source){const command:LinkCommand={type:'event.link_matter',sourceId:source.id,expectedSourceVersion:source.version,matterId:matter.id,expectedMatterVersion:matter.version};setReview({command,inspectedVersion:data.version,fingerprint:eventLinkFingerprint(data,command)});setSaved('')}
 async function link(){if(!review||!ready||busy)return;const result=await submit(review.command);if(result){setReview(null);setSaved('Source linked for review. An observation update was added to this matter’s conversation. No deployment or legal conclusion was inferred.')}return result}
 const evidence=(source:Source)=><div className={s.previewBox} style={{maxHeight:280}}><p className={s.longText}>{source.text}</p></div>;
 return <section className={s.card} style={{overflowWrap:'anywhere'}} aria-label="Link provider events to this matter"><h2>Link a provider observation</h2><p>Inspect a retained GitHub, Slack, or Drive observation and explicitly link it to this matter. Linking records context for review; it does not confirm deployment, a company fact, or a legal conclusion.</p>{saved&&<p className={s.notice} role="status">{saved}</p>}<h3>Current unlinked observations ({candidates.length})</h3>{candidates.length?<div className={s.stack}>{candidates.map(source=><article className={s.task} key={source.id} style={{flexWrap:'wrap'}}><div style={{flex:'1 1 220px',minWidth:0}}><strong>{source.title}</strong><p className={s.small}>{human(source.kind)} · revision {source.externalRevision??'unavailable'} · source version {source.version} · observed {date(source.observedAt)}</p><p className={s.small}>ID {source.id} · evidence hash {source.contentHash}</p></div><button className={s.button} disabled={busy||!data.capabilities.includes('business_owner')||matter.ownerId!==data.actor.id} onClick={()=>inspect(source)}>Review link</button></article>)}</div>:<Empty icon="link" title="No current unlinked provider observations in this matter audience.">Provider events appear here only after authenticated ingestion and remain observations until an owner links them.</Empty>}
  <h3>Linked provider source history ({history.length})</h3>{history.length?<div className={s.stack}>{history.map(source=>{const links=data.events.filter(event=>event.type==='event.link_matter'&&event.recordId===source.id&&event.matterId===matter.id);return <article className={s.task} key={source.id} style={{flexWrap:'wrap'}}><div style={{flex:'1 1 220px',minWidth:0}}><strong>{source.title}</strong><p className={s.small}>{human(source.kind)} · {source.id} · revision {source.externalRevision??'unavailable'} · source version {source.version}</p><Badge tone={source.status==='active'&&source.observation?.state==='current'?'green':'amber'}>{source.status==='active'&&source.observation?.state==='current'?'Current observation':'Historical or unavailable observation'}</Badge><p className={s.small}>{links.length?links.map(event=>`Linked ${date(event.createdAt)} · ${event.id}`).join('; '):'Retained in this matter; no separate owner-link event recorded.'}</p></div><button className={s.textButton} onClick={()=>openSource(source.id)}>Inspect source <Icon name="arrow" size={11}/></button></article>})}</div>:<p className={s.small}>No provider source is linked to this matter.</p>}{matter.conversationIds[0]&&history.length>0&&<button className={s.textButton} onClick={()=>openConversation(matter.conversationIds[0])}>Open linked conversation update <Icon name="arrow" size={11}/></button>}
  {review&&<section className={s.card} aria-label="Review exact provider observation link"><h3 ref={heading} tabIndex={-1}>Review exact observation and matter</h3><p>Matter {matter.title} · {matter.id} · version {review.command.expectedMatterVersion}</p><p>Objective: {matter.objective}</p>{(()=>{const source=data.sources.find(item=>item.id===review.command.sourceId);return source?<><h4>{source.title}</h4><p className={s.small}>{human(source.kind)} · source {source.id} · version {review.command.expectedSourceVersion} · external object {source.externalId??'unavailable'} · exact revision {source.externalRevision??'unavailable'}</p><p className={s.small}>Observed {date(source.observedAt)} · effective {date(source.effectiveAt)} · hash {source.contentHash} · dependency {source.evidenceDependencyHash??'unavailable'}</p><p className={s.small}>Observation {source.observation?.state??'unavailable'} · {source.observation?.basis??'unavailable'} · installation {source.installationGrant?.installationId??'unavailable'}</p>{evidence(source)}<button className={s.textButton} onClick={()=>openSource(source.id)}>Inspect full source <Icon name="arrow" size={11}/></button></>:<p className={s.error}>Source unavailable.</p>})()}<p className={s.boundary}>This links an observation for review and adds an update to the matter’s conversation. It does not infer deployment, confirm a fact, or authorize an external action.</p>{!ready&&<p className={s.error} role="alert">The matter, provider revision, source access, or workspace changed. Close and inspect the current observation.</p>}<div className={s.row}><button className={s.primary} disabled={busy||!ready} onClick={()=>void link()}>Link exact observation</button><button className={s.button} onClick={()=>setReview(null)}>Close review</button></div></section>}
 </section>;
}
