'use client';

import {useCallback,useEffect,useState} from 'react';
import type {CommandResult,DocumentRecord,Matter,Source,WorkspaceCommand,WorkspaceSnapshot} from '@/v2/contracts';
import type {InventoryView} from '@/v2/inventory';
import {Badge,human,Icon} from './Primitives';
import {Modal} from './ReviewDialog';
import s from './workspace.module.css';

type Props={data:WorkspaceSnapshot;matter:Matter;busy:boolean;error:string;pending:boolean;submit:(command:WorkspaceCommand)=>Promise<CommandResult|null>;retryPending:()=>Promise<CommandResult|null>;clearError:()=>void};
type Review={kind:'attest';actorId:string;matter:Matter;documents:DocumentRecord[];sources:Source[]}|{kind:'revoke';actorId:string;record:InventoryView};
function tomorrow(){const date=new Date(Date.now()+86400000);date.setMinutes(date.getMinutes()-date.getTimezoneOffset());return date.toISOString().slice(0,16)}
function validUntil(value:string){const n=Date.parse(value);return Number.isFinite(n)&&n>Date.now()&&n<=Date.now()+30*86400000}
const sameIds=(a:string[],b:string[])=>a.length===b.length&&[...a].sort().every((id,i)=>id===[...b].sort()[i]);

export function InventoryPanel({data,matter,busy,error,pending,submit,retryPending,clearError}:Props){
 const candidate=data.inventoryCandidates?.find(record=>record.matterId===matter.id),records=(data.inventories??[]).filter(record=>record.matterId===matter.id);
 const [review,setReview]=useState<Review|null>(null),[title,setTitle]=useState(''),[scope,setScope]=useState(''),[sourceIds,setSourceIds]=useState<string[]>([]),[until,setUntil]=useState(''),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false);
 const close=useCallback(()=>setReview(null),[]);
 const current=review?.kind==='revoke'?records.find(record=>record.id===review.record.id):matter;
 const accessible=review?.kind==='attest'?review.documents.every(doc=>data.documents.some(item=>item.id===doc.id))&&review.sources.every(source=>data.sources.some(item=>item.id===source.id)):!!current;
 const fresh=review?.kind==='attest'?matter.version===review.matter.version&&!!candidate?.available&&sameIds(candidate.documentIds,review.documents.map(doc=>doc.id))&&review.documents.every(doc=>data.documents.some(item=>item.id===doc.id&&item.contentHash===doc.contentHash&&item.version===doc.version))&&review.sources.every(source=>data.sources.some(item=>item.id===source.id&&item.version===source.version)):!!review&&current?.version===review.record.version;
 useEffect(()=>{if(review&&(review.actorId!==data.actor.id||!accessible))close()},[review,data.actor.id,accessible,close]);
 const canAttest=data.capabilities.includes('fact_owner')&&!['closed','canceled'].includes(matter.state);
 async function save(){if(!review||!fresh||!confirmed)return;const command:WorkspaceCommand=review.kind==='revoke'?{type:'inventory.revoke',inventoryId:review.record.id,expectedRecordVersion:review.record.version,reason}:{type:'inventory.attest',matterId:review.matter.id,expectedMatterVersion:review.matter.version,title,scopeDescription:scope,documentIds:review.documents.map(doc=>doc.id),sourceIds,validUntil:new Date(until).toISOString()};if(await submit(command))close()}
 return <section className={s.card} aria-label="Supplied agreement inventory"><div className={s.rowBetween}><h2>Know what this register covers.</h2><Icon name="file" size={18}/></div><p>A named factual owner can attest to the complete supplied agreement register for this matter’s exact audience. This does not discover outside agreements or establish which terms legally apply.</p>
 <div className={s.row} style={{marginTop:14}}><Badge tone={candidate?.available?'purple':'amber'}>{candidate?.available?`${candidate.count} current supplied agreement and amendment heads`:'Register unavailable in your current scope'}</Badge></div>
 <p className={s.small} style={{marginTop:12}}>Draft and unknown-authority records remain in the register. An amendment is separate from its original. New heads, changed evidence, expiry or lost owner capacity invalidate the attestation.</p>
 <button className={s.button} style={{marginTop:15}} disabled={busy||pending||!canAttest||!candidate?.available} onClick={()=>{if(!candidate)return;clearError();setReview({kind:'attest',actorId:data.actor.id,matter:structuredClone(matter),documents:structuredClone(candidate.documentIds.flatMap(id=>{const doc=data.documents.find(item=>item.id===id);return doc?[doc]:[]})),sources:structuredClone(data.sources.filter(source=>source.status==='active'))});setTitle(`Supplied agreement register · ${matter.title}`.slice(0,300));setScope('');setSourceIds([]);setUntil(tomorrow());setConfirmed(false)}}>Inspect and attest supplied register</button>
 {!canAttest&&<p className={s.small}>A factual owner must make this attributed completeness decision.</p>}
 {records.slice().reverse().map(record=><div className={s.previewBox} style={{marginTop:18}} key={record.id}><div className={s.rowBetween}><h3>{record.title}</h3><Badge tone={record.current?'green':'amber'}>{record.status==='revoked'?'Withdrawn':record.current?'Current owner attestation':'Stale attestation'}</Badge></div><p>{record.scopeDescription}</p><p className={s.small}>{record.count} supplied heads · Named owner: {record.ownerId}<br/>Expires {new Date(record.validUntil).toLocaleString()}</p><p className={s.documentMeta}>Register fingerprint: {record.registerHash}</p>{record.status==='active'&&data.capabilities.includes('fact_owner')&&<button className={s.textButton} disabled={busy||pending} onClick={()=>{clearError();setReview({kind:'revoke',actorId:data.actor.id,record:structuredClone(record)});setReason('');setConfirmed(false)}}>Withdraw this attestation</button>}</div>)}
 {review&&<Modal title={review.kind==='attest'?'Attest this supplied agreement register':'Withdraw inventory attestation'} close={close} error={error} footer={pending?<button className={s.primary} disabled={busy} onClick={async()=>{if(await retryPending())close()}}>Check saved inventory decision</button>:<button className={s.primary} disabled={busy||!fresh||!confirmed||(review.kind==='attest'?(!title.trim()||!scope.trim()||!sourceIds.length||!validUntil(until)):!reason.trim())} onClick={()=>void save()}>{review.kind==='attest'?'Record my bounded inventory attestation':'Withdraw this exact attestation'}</button>}>
 {review.kind==='attest'?<><Badge tone="purple">Named factual owner · {data.actor.id}</Badge><h3 style={{marginTop:14}}>{review.matter.title}</h3><p>{review.documents.length} current supplied agreement and amendment heads. Inspect every row; there is no search-result cutoff.</p><label className={s.field}>Attestation title<input maxLength={300} value={title} onChange={event=>{setTitle(event.target.value);setConfirmed(false)}}/></label><label className={s.field}>Customer or business population and completeness basis<textarea maxLength={4000} value={scope} onChange={event=>{setScope(event.target.value);setConfirmed(false)}} placeholder="Name the bounded population, records reconciled and why this supplied register is complete for that scope."/></label>
 <div className={s.stack}>{review.documents.map(doc=><details className={s.previewBox} key={doc.id}><summary><strong>{doc.title}</strong> · revision {doc.revision} · {doc.authority==='executed'?'Marked executed':human(doc.authority)}{doc.amendsDocumentId?' · Separate amendment':''}</summary><p className={s.documentMeta}>{doc.id} · {doc.contentHash}</p><div className={s.documentBody}>{doc.body}</div></details>)}</div>{!review.documents.length&&<p className={s.boundary}>The current supplied register contains zero agreement heads. A zero-record attestation still needs an explicit bounded population and retained evidence; it does not assert that no external agreements exist.</p>}
 <fieldset className={s.previewBox} style={{marginTop:20}}><legend>Retained evidence supporting completeness</legend>{review.sources.map(source=><div key={source.id}><label className={s.field}><input type="checkbox" checked={sourceIds.includes(source.id)} onChange={event=>{setSourceIds(old=>event.target.checked?[...old,source.id]:old.filter(id=>id!==source.id));setConfirmed(false)}}/>{source.title} · {source.authority==='executed'?'Marked executed':human(source.authority)} · version {source.version}</label><details><summary className={s.small}>Inspect this evidence</summary><div className={s.documentBody}>{source.text}</div></details></div>)}</fieldset>
 <label className={s.field}>Attestation expires at your local time<input type="datetime-local" value={until} onChange={event=>{setUntil(event.target.value);setConfirmed(false)}}/><small>Within 30 days. Prepare a new packet after this decision to bind the exact register.</small></label><label className={s.field}><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>I attest that every supplied agreement and amendment head above covers the stated population, based on the selected evidence. This is my factual attestation; legal applicability and external discovery remain unverified.</label></>:<><h3>{review.record.title}</h3><p>{review.record.scopeDescription}</p><p className={s.documentMeta}>{review.record.registerHash}</p><p>Prepared work depending on this attestation will require a current inventory basis before approval or execution.</p><label className={s.field}>Reason<textarea maxLength={2000} value={reason} onChange={event=>{setReason(event.target.value);setConfirmed(false)}}/></label><label className={s.field}><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>Withdraw this exact inventory attestation.</label></>}
 {!fresh&&<p className={s.error}>The matter, register or evidence changed. Close this preview and inspect the current complete set.</p>}
 </Modal>}
 </section>;
}
