'use client';

import {useCallback,useEffect,useState} from 'react';
import type {CommandResult,LearningCandidate,WorkspaceCommand,WorkspaceSnapshot} from '@/v2/contracts';
import {Badge,Empty,Icon,date,human} from './Primitives';
import {Modal} from './ReviewDialog';
import {selectedLessonOrigin} from './review-intent';
import s from './workspace.module.css';

type Step='evaluate'|'promote'|'renew'|'rollback';
type Props={data:WorkspaceSnapshot;busy:boolean;error:string;pending:boolean;propose:(matterId:string)=>void;clearError:()=>void;submit:(command:WorkspaceCommand)=>Promise<CommandResult|null>;retryPending:()=>Promise<CommandResult|null>};

export function LearningPanel({data,busy,error,pending,propose,clearError,submit,retryPending}:Props){
  const [review,setReview]=useState<{step:Step;candidate:LearningCandidate;actorId:string}|null>(null),[confirmed,setConfirmed]=useState(false),[reason,setReason]=useState(''),[originMatterId,setOriginMatterId]=useState('');
  const close=useCallback(()=>setReview(null),[]);
  useEffect(()=>{if(review&&(review.actorId!==data.actor.id||!data.learning.some(l=>l.id===review.candidate.id)))close()},[data,review,close]);
  useEffect(()=>{if(originMatterId&&!selectedLessonOrigin(data.matters,originMatterId))setOriginMatterId('')},[data.matters,originMatterId]);
  const open=(step:Step,candidate:LearningCandidate)=>{clearError();setReview({step,candidate,actorId:data.actor.id});setConfirmed(false);setReason('')};
  const c=review?.candidate,current=data.learning.find(l=>l.id===c?.id);
  const fresh=!!c&&!!current&&c.version===current.version&&c.status===current.status&&c.evaluationHash===current.evaluationHash;
  const owner=(candidate:LearningCandidate)=>data.capabilities.includes(candidate.kind==='legal_playbook'?'legal_reviewer':'business_owner');
  const canEvaluate=(candidate:LearningCandidate)=>!!candidate.procedureKey&&data.capabilities.includes('evaluator')&&candidate.provenance.actorId!==data.actor.id;
  const canPromote=(candidate:LearningCandidate)=>owner(candidate)&&candidate.evaluatedBy!==data.actor.id&&candidate.evaluation?.candidateFailures===0&&(candidate.evaluation?.baselineFailures??0)>0&&!!candidate.evaluationHash;
  async function save(){if(!c||!review||!fresh||!confirmed)return;let command:WorkspaceCommand;
    if(review.step==='evaluate'){if(!canEvaluate(c))return;command={type:'learning.run_evaluation',candidateId:c.id,expectedRecordVersion:c.version}}
    else if(review.step==='promote'){if(!canPromote(c))return;command={type:'learning.promote',candidateId:c.id,expectedRecordVersion:c.version,evaluationHash:c.evaluationHash!}}
    else if(review.step==='renew'){if(!canPromote(c))return;command={type:'learning.renew',candidateId:c.id,expectedRecordVersion:c.version,evaluationHash:c.evaluationHash!}}
    else {if(!owner(c)||!reason.trim())return;command={type:'learning.rollback',candidateId:c.id,expectedRecordVersion:c.version,reason}}
    if(await submit(command))close();
  }
  return <><div className={s.rowBetween} style={{marginBottom:20,flexWrap:'wrap'}}><p className={s.muted}>A useful lesson has an origin, a tested effect and a way back.</p>{data.matters.length>0&&<div className={s.row} style={{minWidth:0}}><label className={s.field} style={{minWidth:0}}>Origin matter<select aria-label="Lesson origin matter" value={originMatterId} onChange={event=>setOriginMatterId(event.target.value)}><option value="">Choose a matter</option>{data.matters.map(m=><option key={m.id} value={m.id}>{m.title} · {m.id.slice(-8)} · {human(m.scope.kind)}</option>)}</select></label><button className={s.button} disabled={busy||pending||!selectedLessonOrigin(data.matters,originMatterId)} onClick={()=>{const selected=selectedLessonOrigin(data.matters,originMatterId);if(selected){propose(selected.id);setOriginMatterId('')}}}>Propose a lesson</button></div>}</div>
    <div className={s.boundary}><Icon name="shield" size={15}/>Supported procedures are checked against frozen original, near-miss and held-out cases. These deterministic checks do not establish legal or model quality.</div>
    {data.learning.length?<div className={s.stack}>{data.learning.map(l=><section className={s.card} key={l.id} aria-label={`Lesson: ${l.title}`}>
      <div className={s.rowBetween}><h2>{l.title}</h2><Badge tone={l.status==='promoted'?'green':'purple'}>{human(l.status)}</Badge></div><p>{l.rule}</p>
      <dl className={s.definitionList} style={{margin:'16px 0'}}><dt>Intended scope</dt><dd>{l.scopeDescription}</dd><dt>Actual access scope</dt><dd>{human(l.scope.kind)} · inherited from the origin matter</dd><dt>Origin</dt><dd>{data.matters.find(m=>m.id===l.originMatterId)?.title??l.originMatterId}</dd><dt>Proposed by</dt><dd>{l.provenance.actorId}</dd><dt>Evaluation owner</dt><dd>{l.evaluatedBy??'Independent evaluator required'}</dd><dt>Approval owner</dt><dd>{l.approvedBy??'Pending'}</dd>{l.reviewDueAt&&<><dt>Review due</dt><dd>{date(l.reviewDueAt)}</dd></>}</dl>
      {l.procedureKey?<><h3>Supported behavior</h3><p>{l.effectSummary??'Require current release evidence before treating deployment as live.'}</p><p className={s.small} style={{marginTop:8}}>The supported procedure defines executable behavior. Free-form wording and reported test results cannot change it.</p></>:<div className={s.boundary}>This is a prose candidate. It has no executable effect and cannot be promoted through the supported procedure evaluation.</div>}
      {l.evaluation?<Evaluation candidate={l}/>:<p style={{marginTop:15}}>No server-executed comparison recorded.</p>}
      <div className={s.row} style={{marginTop:18}}>{['candidate','evaluated'].includes(l.status)&&l.procedureKey&&<button className={s.button} disabled={busy||!canEvaluate(l)} onClick={()=>open('evaluate',l)}>Run frozen comparison</button>}{l.status==='evaluated'&&<button className={s.primary} disabled={busy||!canPromote(l)} onClick={()=>open('promote',l)}>Review promotion <Icon name="arrow" size={12}/></button>}{l.status==='promoted'&&<button className={s.button} disabled={busy||!canPromote(l)} onClick={()=>open('renew',l)}>Review and renew for 30 days</button>}{l.status==='promoted'&&<button className={s.button} disabled={busy||!owner(l)} onClick={()=>open('rollback',l)}>Roll back and review affected work</button>}</div>
      {['candidate','evaluated'].includes(l.status)&&l.procedureKey&&!canEvaluate(l)&&<p className={s.small} style={{marginTop:9}}>An independently provisioned evaluator must run this comparison; the candidate author cannot evaluate it.</p>}
      {l.status==='promoted'&&<p style={{marginTop:12}}>{l.appliedMatterIds?.length??0} matters recorded use of this procedure. Changes to evidence, authority or review validity can block further work.</p>}
      {l.status==='rolled_back'&&<p style={{marginTop:12}}>{l.affectedMatterIds.length} affected matters identified for review. The lesson is no longer active.</p>}
    </section>)}</div>:<Empty icon="spark" title="Lessons need more than a thumbs-up.">Suggest a scoped correction from a matter. A supported behavior, executed evaluation and responsible owner’s approval come before reusable changes.</Empty>}
    {review&&c&&<Modal title={review.step==='evaluate'?'Run the frozen procedure comparison':review.step==='promote'?'Approve this evaluated procedure':review.step==='renew'?'Review this unchanged procedure':'Roll back this procedure'} error={error} close={close} footer={pending?<button className={s.primary} disabled={busy} onClick={async()=>{if(await retryPending())close()}}>Check saved decision</button>:<button className={s.primary} disabled={busy||!fresh||!confirmed||(review.step==='rollback'&&!reason.trim())||(review.step==='evaluate'&&!canEvaluate(c))||(['promote','renew'].includes(review.step)&&!canPromote(c))} onClick={()=>void save()}>{review.step==='evaluate'?'Run server-owned evaluation':review.step==='promote'?'Approve this exact evaluated behavior':review.step==='renew'?'Renew this exact procedure for 30 days':'Roll back and identify affected matters'}</button>}>
      <Badge tone="purple">Frozen review · lesson version {c.version}</Badge><h3 style={{marginTop:16}}>{c.title}</h3><p className={s.muted}>{c.rule}</p><div className={s.previewBox}><h3>Exact supported effect</h3><p className={s.longText}>{c.effectSummary}</p><p className={s.small}>Scope: {c.scopeDescription} · {human(c.scope.kind)} access</p></div>
      {review.step==='evaluate'&&<p className={s.muted}>The server replays the frozen origin input, near misses and held-out cases against baseline and candidate behavior. You cannot submit passing results. This evaluates the bounded deployment-evidence guard only.</p>}
      {['promote','renew'].includes(review.step)&&<><Evaluation candidate={c}/><p className={s.muted} style={{marginTop:16}}>Promotion activates this bounded procedure for comparable work in its scope and marks existing proposals for fresh review. It does not certify legal interpretation or grant publication authority.</p><div className={s.documentMeta}>Evaluation fingerprint: {c.evaluationHash}</div></>}
      {review.step==='rollback'&&<><p className={s.muted}>Rollback disables this current procedure and identifies work that relied on it. Affected proposals will require review.</p><label className={s.field}>Reason and follow-up<textarea value={reason} onChange={event=>{setReason(event.target.value);setConfirmed(false)}} maxLength={2000}/></label></>}
      <label className={s.field}><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>{review.step==='evaluate'?'I am independently assigned to evaluate this fixed procedure.':['promote','renew'].includes(review.step)?'I reviewed the exact behavior, scope, measured comparison and its limits.':'I reviewed this rollback and the need to revisit affected work.'}</label>
      {!fresh&&<div className={s.error}>The lesson or evaluation changed. Close this preview and inspect the current version.</div>}
    </Modal>}
  </>;
}

function Evaluation({candidate}:{candidate:LearningCandidate}){const evaluation=candidate.evaluation;if(!evaluation)return null;return <div style={{marginTop:18}}><div className={s.rowBetween}><h3>Frozen procedure comparison</h3><Badge tone={evaluation.candidateFailures===0?'green':'amber'}>{evaluation.candidateFailures} candidate failures</Badge></div><p className={s.small}>{evaluation.baselineFailures} baseline failures → {evaluation.candidateFailures} candidate failures · {evaluation.totalCaseCount??evaluation.cases.length} cases · Run {date(evaluation.runAt)}</p>{!!evaluation.withheldHoldoutCount&&<p className={s.small} style={{marginTop:10}}>{evaluation.withheldHoldoutCount} held-out cases are withheld from this identity. Their aggregate results are included above.</p>}<div className={s.tableWrap}><table className={s.dataTable}><thead><tr><th>Case</th><th>Expected</th><th>Baseline</th><th>Candidate</th></tr></thead><tbody>{evaluation.cases.map(t=><tr key={t.id}><td>{human(t.id)}<br/><Badge>{human(t.group)}</Badge></td><td>{human(t.expected)}</td><td>{human(t.baseline)}</td><td><Badge tone={t.passed?'green':'amber'}>{human(t.candidate)}</Badge></td></tr>)}</tbody></table></div><div className={s.documentMeta}>{evaluation.suiteVersion} · corpus {evaluation.corpusHash}</div><p className={s.small} style={{marginTop:8}}>Executed deterministic replay; legal and model-quality performance remains unqualified.</p></div>}
