'use client';

import {useCallback,useEffect,useState} from 'react';
import type {CommandResult,LegalAuthority,RecordBase,Source,WorkspaceCommand,WorkspaceSnapshot} from '@/v2/contracts';
import type {LegalSourceChange,LegalWatchView} from '@/v2/legal-maintenance';
import {Badge,date,Empty,human} from './Primitives';
import {Modal} from './ReviewDialog';
import s from './workspace.module.css';

type Props={data:WorkspaceSnapshot;busy:boolean;error:string;pending:boolean;submit:(command:WorkspaceCommand)=>Promise<CommandResult|null>;retryPending:()=>Promise<CommandResult|null>;clearError:()=>void};
type Review={kind:'configure'|'stop'|'assess';actorId:string;authority?:LegalAuthority;watch?:LegalWatchView;change?:LegalSourceChange;sources:Source[];targets:RecordBase[]};
const sameScope=(a:RecordBase,b:RecordBase)=>a.scope.kind===b.scope.kind&&a.scope.matterId===b.scope.matterId&&[...a.scope.actorIds].sort().join('\n')===[...b.scope.actorIds].sort().join('\n');
const availabilityReason=(reason:string|null|undefined)=>reason==='LEGAL_SOURCE_NOT_ALLOWED'?'The exact URL policy is unavailable or expired.':'No current operator policy allows this source.';
const time=(value:string|null)=>value?new Date(value).toLocaleString():'Not checked';

export function LegalMaintenancePanel({data,busy,error,pending,submit,retryPending,clearError}:Props){
 const maintenance=data.legalMaintenance,watches=maintenance?.watches??[],changes=maintenance?.changes??[],legal=data.capabilities.includes('legal_reviewer');
 const [review,setReview]=useState<Review|null>(null),[intervalHours,setInterval]=useState(24),[decision,setDecision]=useState<'no_applicability_change'|'affected_work'>('no_applicability_change'),[reason,setReason]=useState(''),[matterIds,setMatterIds]=useState<string[]>([]),[learningIds,setLearningIds]=useState<string[]>([]),[adopt,setAdopt]=useState(false),[confirmed,setConfirmed]=useState(false);
 const close=useCallback(()=>setReview(null),[]);
 useEffect(()=>{if(review&&(review.actorId!==data.actor.id||review.authority&&!data.legalAuthorities.some(a=>a.id===review.authority!.id)||review.change&&!changes.some(c=>c.id===review.change!.id)||review.watch&&!watches.some(w=>w.id===review.watch!.id)||review.sources.some(source=>!data.sources.some(current=>current.id===source.id))))close()},[data,review,changes,watches,close]);
 function inspect(kind:Review['kind'],authority?:LegalAuthority,watch?:LegalWatchView,change?:LegalSourceChange){
  clearError();const sourceIds=change?[change.oldSourceId,change.newSourceId]:authority?[authority.sourceId]:[];
  setReview(structuredClone({kind,actorId:data.actor.id,authority,watch,change,sources:data.sources.filter(src=>sourceIds.includes(src.id)),targets:change?[...data.matters.filter(m=>sameScope(m,change)&&m.state!=='canceled'&&!m.legacyWorkflowId),...data.learning.filter(l=>sameScope(l,change))]:[]}));
  setInterval(24);setDecision('no_applicability_change');setReason('');setMatterIds([]);setLearningIds([]);setAdopt(false);setConfirmed(false);
 }
 const currentTargets=[...data.matters,...data.learning];
 const fresh=!!review&&(review.kind!=='configure'||!!maintenance?.availability?.find(item=>item.authorityId===review.authority?.id)?.configured)&&review.actorId===data.actor.id&&(!review.authority||data.legalAuthorities.find(a=>a.id===review.authority!.id)?.version===review.authority.version)&&(!review.watch||watches.find(w=>w.id===review.watch!.id)?.version===review.watch.version)&&(!review.change||changes.find(c=>c.id===review.change!.id)?.version===review.change.version)&&review.sources.every(src=>data.sources.some(current=>current.id===src.id&&current.version===src.version&&current.contentHash===src.contentHash&&current.status==='active'))&&review.targets.filter(t=>matterIds.includes(t.id)||learningIds.includes(t.id)).every(t=>currentTargets.some(current=>current.id===t.id&&current.version===t.version));
 const valid=!!review&&(review.kind==='configure'?Number.isInteger(intervalHours)&&intervalHours>=1&&intervalHours<=720:review.kind==='stop'?true:!!reason.trim()&&review.sources.length===2&&(decision==='affected_work'?matterIds.length+learningIds.length>0:matterIds.length+learningIds.length===0));
 function toggle(id:string,kind:'matter'|'learning',checked:boolean){const set=kind==='matter'?setMatterIds:setLearningIds;set(old=>checked?[...old,id]:old.filter(x=>x!==id));setConfirmed(false)}
 async function save(){
  if(!review||!fresh||!valid||!legal||!confirmed)return;
  const command:WorkspaceCommand=review.kind==='configure'?{type:'legal.watch.configure',authorityId:review.authority!.id,expectedAuthorityVersion:review.authority!.version,intervalHours}:review.kind==='stop'?{type:'legal.watch.stop',watchId:review.watch!.id,expectedRecordVersion:review.watch!.version}:{type:'legal.change.assess',changeId:review.change!.id,expectedRecordVersion:review.change!.version,oldHash:review.change!.oldHash,newHash:review.change!.newHash,decision,reason,matterIds,learningIds,adoptSource:adopt};
  if(await submit(command))close();
 }
 return <section className={s.card} aria-label="Legal source monitoring">
  <div className={s.rowBetween}><h2>Keep the source review current.</h2><Badge>Named legal review</Badge></div>
  <p>Monitoring compares retained text at an exact public source URL. An operator must allow that URL and configure a worker. An observed change does not decide legal applicability or establish coverage.</p>
  {!data.legalAuthorities.length&&<Empty icon="shield" title="No retained legal source is registered.">Register a source and its exact URL above before requesting a monitor. Monitoring availability has not been established.</Empty>}
  {data.legalAuthorities.map(authority=>{const availability=maintenance?.availability?.find(item=>item.authorityId===authority.id),watch=watches.find(w=>w.authorityId===authority.id&&w.active),latest=watch??[...watches].reverse().find(w=>w.authorityId===authority.id),unreviewed=changes.filter(c=>c.authorityId===authority.id&&c.status==='pending_review');return <article className={s.previewBox} style={{maxHeight:'none'}} key={authority.id}>
   <div className={s.rowBetween}><h3>{authority.title}</h3><Badge tone={unreviewed.length||latest?.status==='blocked'||latest?.overdue?'amber':'purple'}>{latest?human(latest.status):'Monitor not configured'}</Badge></div><p className={s.documentMeta}>{authority.sourceUrl}</p>{availability?.configured?<p className={s.small}>Exact URL allowed by operator policy. Successful connectivity, current source verification and coverage are not implied.</p>:<p className={s.small}>Monitoring unavailable. {availabilityReason(availability?.reason)} An operator must allow this exact URL before a monitor can be requested.</p>}
   {latest?<><p className={s.small}>Monitor owner: {latest.ownerId} · Every {latest.intervalHours} hours<br/>Last check: {time(latest.lastCheckedAt)} · Next: {time(latest.nextCheckAt)}</p>{latest.overdue&&<p className={s.small}>The scheduled check is overdue. Source freshness is not confirmed.</p>}{latest.failureCode&&<p className={s.error}>The check is blocked: {human(latest.failureCode)}. No successful source read is claimed.</p>}</>:<p className={s.small}>No successful source check has been recorded. Configuration is conditional on the operator’s exact URL policy.</p>}
   {!!unreviewed.length&&<p className={s.small}>{unreviewed.length} observed changes await named applicability assessment. Source freshness and dependent coverage need review.</p>}
   <button className={s.button} style={{marginTop:12}} disabled={busy||pending||!legal||(!watch&&!availability?.configured)} onClick={()=>inspect(watch?'stop':'configure',authority,watch)}>{watch?'Stop this source monitor':'Configure source monitor'}</button>
  </article>})}
  {changes.length>0&&<h3 style={{marginTop:22}}>Observed changes</h3>}
  {changes.map(change=><article className={s.previewBox} style={{maxHeight:'none'}} key={change.id}><div className={s.rowBetween}><h3>{data.legalAuthorities.find(a=>a.id===change.authorityId)?.title??'Retained legal source'}</h3><Badge tone={change.status==='pending_review'?'amber':'purple'}>{human(change.status)}</Badge></div><p>Observed {date(change.createdAt)}. Retained text changes require a named assessment.</p>{change.assessment&&<><p>Reviewed by {change.assessment.actorId}: {human(change.assessment.decision)}</p><p>{change.assessment.reason}</p><p className={s.small}>{change.assessment.matterIds.length} matters · {change.assessment.learningIds.length} maintained rules · {change.assessment.adoptedSource?'New source adopted; verification and coverage review remain separate.':'Registry source not replaced.'}</p></>}<button className={s.button} disabled={busy||pending||!legal||change.status!=='pending_review'||![change.oldSourceId,change.newSourceId].every(id=>data.sources.some(src=>src.id===id&&src.status==='active'))} onClick={()=>inspect('assess',data.legalAuthorities.find(a=>a.id===change.authorityId),undefined,change)}>Inspect exact texts and assess</button></article>)}
  {review&&<Modal title={review.kind==='configure'?'Configure this exact source monitor':review.kind==='stop'?'Stop this exact source monitor':'Assess this exact observed source change'} close={close} error={error} footer={pending?<button className={s.primary} disabled={busy} onClick={async()=>{if(await retryPending())close()}}>Check saved source decision</button>:<button className={s.primary} disabled={busy||!fresh||!valid||!legal||!confirmed} onClick={()=>void save()}>{review.kind==='configure'?'Request this source monitor':review.kind==='stop'?'Stop this monitor':'Record this applicability assessment'}</button>}>
   <h3>{review.authority?.title??'Legal source'}</h3><p className={s.documentMeta}>{review.authority?.sourceUrl??review.watch?.sourceUrl}</p>
   {review.kind==='configure'&&<><p>Only this exact URL is requested. The server must validate a current operator allowlist before scheduling any read. A saved request does not establish source freshness or legal coverage.</p><label className={s.field}>Check interval in hours<input type="number" min={1} max={720} value={intervalHours} onChange={event=>{setInterval(Number(event.target.value));setConfirmed(false)}}/></label><p className={s.small}>Owner: {data.actor.id}. Checks require the owner’s current legal-review capacity and unchanged access.</p></>}
   {review.kind==='stop'&&<p>Future checks stop. Retained observations and pending assessments remain; this does not resolve affected work or restore source freshness.</p>}
   {review.kind==='assess'&&<><p>Compare the complete retained extracted text. This is not a formatting, signature or authoritative publication diff. No affected matter or rule is inferred automatically.</p>{review.sources.map(source=><div className={s.previewBox} style={{maxHeight:'none'}} key={source.id}><h3>{source.id===review.change!.oldSourceId?'Previously retained source':'Observed source update'}</h3><p>{source.title}</p><p className={s.documentMeta}>Source version {source.version} · Exact hash {source.contentHash}</p><p className={s.longText}>{source.text}</p></div>)}
    <label className={s.field}>Named assessment<select value={decision} onChange={event=>{setDecision(event.target.value as typeof decision);setMatterIds([]);setLearningIds([]);setConfirmed(false)}}><option value="no_applicability_change">No applicability change identified</option><option value="affected_work">Named work requires review</option></select></label>
    {decision==='affected_work'&&<><p className={s.small}>Only available matters and rules with this source’s exact audience are offered. Selection reopens review; it does not decide the eventual legal outcome.</p>{review.targets.map(target=>{const matter=data.matters.find(m=>m.id===target.id),lesson=data.learning.find(l=>l.id===target.id);return <label className={s.field} key={target.id}><input type="checkbox" checked={(matter?matterIds:learningIds).includes(target.id)} onChange={event=>toggle(target.id,matter?'matter':'learning',event.target.checked)}/>{matter?`Matter: ${matter.title}`:`Maintained rule: ${lesson?.title??'Unavailable'}`} · inspected version {target.version}</label>})}{!review.targets.length&&<p>No eligible same-audience work is available in your access.</p>}</>}
    <label className={s.field}>Reason, applicability and limits<textarea maxLength={4000} value={reason} onChange={event=>{setReason(event.target.value);setConfirmed(false)}}/></label>
    <label className={s.field}><input type="checkbox" checked={adopt} onChange={event=>{setAdopt(event.target.checked);setConfirmed(false)}}/>Replace the registry source with this exact observed revision.</label><p className={s.small}>Adoption removes the earlier source-verification status. Verify the new source revision and separately review dependent coverage. Affected matters require new approvals; maintained rules require renewed review.</p>
   </>}
   <label className={s.field}><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>I reviewed this exact source, selected scope and consequence within my legal-review capacity.</label>{!fresh&&<p className={s.error}>The source, monitor or selected work changed. Close this preview and inspect the current versions.</p>}
  </Modal>}
 </section>;
}
