'use client';

import {useCallback,useEffect,useState} from 'react';
import type {CommandResult,WorkspaceCommand,WorkspaceSnapshot} from '@/v2/contracts';
import type {NotificationEnrollment,NotificationView} from '@/v2/notifications';
import {Badge,human,Icon} from './Primitives';
import {Modal} from './ReviewDialog';
import s from './workspace.module.css';

type Delivery=NotificationView['deliveries'][number];
type Props={data:WorkspaceSnapshot;busy:boolean;error:string;pending:boolean;submit:(command:WorkspaceCommand)=>Promise<CommandResult|null>;retryPending:()=>Promise<CommandResult|null>;clearError:()=>void;reconcile:(id:string,version:number,receipt:string)=>Promise<boolean>};
type Review={kind:'configure';actorId:string;version:number;configuration:NotificationView['configuration']}|{kind:'reconcile';actorId:string;delivery:Delivery};
const status=(value:Delivery['status'])=>({prepared:'Prepared · no send recorded',sending:'Delivery attempt · confirmation pending',accepted:'Provider accepted · delivery pending',delivered:'Provider delivery verified',unknown:'Delivery unknown · do not resend',failed:'Delivery failed',canceled:'Future delivery canceled',preview:'Preview only · no email delivered'}[value]);
export function NotificationPanel({data,busy,error,pending,submit,retryPending,clearError,reconcile}:Props){
 const notifications=data.notifications,configuration=notifications?.configuration,enrollment=notifications?.enrollment;
 const [review,setReview]=useState<Review|null>(null),[mode,setMode]=useState<NotificationEnrollment['mode']>('off'),[receipt,setReceipt]=useState(''),[confirmed,setConfirmed]=useState(false);
 const close=useCallback(()=>setReview(null),[]),current=review?.kind==='reconcile'?notifications?.deliveries.find(d=>d.id===review.delivery.id):null;
 const fresh=!!review&&review.actorId===data.actor.id&&(review.kind==='configure'?(enrollment?.version??0)===review.version&&(mode==='off'||configuration?.available&&configuration.grantHash===review.configuration.grantHash):current?.version===review.delivery.version&&['accepted','unknown'].includes(current.status));
 useEffect(()=>{if(review&&(review.actorId!==data.actor.id||review.kind==='reconcile'&&!current))close()},[review,data.actor.id,current,close]);
 function configure(){if(!configuration)return;clearError();setReview(structuredClone({kind:'configure',actorId:data.actor.id,version:enrollment?.version??0,configuration}));setMode(enrollment?.mode??'off');setConfirmed(false)}
 return <section className={s.card} aria-label="Email attention notifications"><div className={s.rowBetween}><h2>Bring your attention back when it matters.</h2><Badge tone={notifications?.effective?'purple':'amber'}>{notifications?.effective?'Preference enabled':enrollment?.active?'Review configuration':'Email notifications off'}</Badge></div><p>Optional email contains a generic link to your authenticated attention page. Company names, matter titles, facts, source text and deadline details stay in the workspace.</p>{configuration?.available?<p className={s.small} style={{marginTop:12}}>Configured recipient: {configuration.email}<br/>{configuration.mode==='preview'?'Preview mode: no email is sent.':'Live email transport: delivery depends on configured workers and provider receipts.'}</p>:<div className={s.boundary}>No current operator-verified email identity and delivery origin are available. In-app attention remains available.</div>}<p className={s.small} style={{marginTop:12}}>Preference: {enrollment?.mode==='required_and_digest'?'Required alerts and daily digest':enrollment?.mode==='digest'?'Daily digest':'Off'}. Digest timing follows your attention settings. Turning email off keeps required items visible in the app.</p><button className={s.button} style={{marginTop:15}} disabled={busy||pending||!configuration||!configuration.available&&!enrollment?.active} onClick={configure}>Review email notification preference</button><a className={s.textButton} style={{marginLeft:12}} href="/review/attention">Open authenticated attention page <Icon name="arrow" size={12}/></a>
  {!!notifications?.deliveries.length&&<details style={{marginTop:18}}><summary className={s.small}>Your latest delivery records ({notifications.deliveries.length})</summary>{notifications.deliveries.map(delivery=><article className={s.previewBox} key={delivery.id}><div className={s.rowBetween}><h3>{delivery.kind==='required'?'Required attention link':'Daily attention link'}</h3><Badge tone={delivery.status==='delivered'?'green':['unknown','failed'].includes(delivery.status)?'amber':'neutral'}>{status(delivery.status)}</Badge></div><p className={s.small}>Prepared {new Date(delivery.createdAt).toLocaleString()}{delivery.completedAt?` · Updated ${new Date(delivery.completedAt).toLocaleString()}`:''}</p>{delivery.reason&&<p className={s.small}>Status detail: {human(delivery.reason.toLowerCase())}</p>}{['accepted','unknown'].includes(delivery.status)&&<><p className={s.small}>Check the existing provider receipt. This can verify the original attempt; it cannot send another email.</p><button className={s.textButton} disabled={busy||pending} onClick={()=>{clearError();setReview({kind:'reconcile',actorId:data.actor.id,delivery:structuredClone(delivery)});setReceipt('');setConfirmed(false)}}>Inspect provider readback</button></>}</article>)}</details>}
  {review&&<Modal title={review.kind==='configure'?'Review your exact email preference':'Verify an existing delivery receipt'} close={close} error={error} footer={pending?<button className={s.primary} disabled={busy} onClick={async()=>{if(await retryPending())close()}}>Check saved notification preference</button>:<button className={s.primary} disabled={busy||!fresh||!confirmed||review.kind==='reconcile'&&!/^[A-Za-z0-9_-]{1,200}$/.test(receipt)} onClick={async()=>{if(review.kind==='configure'){if(await submit({type:'notification.configure',expectedRecordVersion:review.version,mode,expectedGrantHash:mode==='off'?null:review.configuration.grantHash}))close()}else if(await reconcile(review.delivery.id,review.delivery.version,receipt))close()}}>{review.kind==='configure'?'Save this email preference':'Read back this receipt; do not resend'}</button>}>
   {review.kind==='configure'?<><label className={s.field}>Email preference<select value={mode} onChange={e=>{setMode(e.target.value as typeof mode);setConfirmed(false)}}><option value="off">Off · keep in-app attention</option><option value="digest" disabled={!review.configuration.available}>Daily digest</option><option value="required_and_digest" disabled={!review.configuration.available}>Required alerts and daily digest</option></select></label><div className={s.previewBox}><h3>{mode==='off'?'Disable future email notifications':'Exact delivery configuration'}</h3>{mode!=='off'&&<><p>Recipient: {review.configuration.email}<br/>Mode: {review.configuration.mode==='preview'?'Preview only · no send':'Live email transport'}</p><p className={s.documentMeta}>Authorized review destination: {review.configuration.reviewUrl}<br/>Configuration fingerprint: {review.configuration.grantHash}</p></>}<p className={s.small}>Only a generic authenticated review link is included. Access is checked again when you open it. Required in-app items remain visible if email is off or delivery fails.</p></div><p className={s.small}>A configured worker prepares eligible alerts and digests. Enabling this preference does not prove an email has been accepted or delivered.</p></>:<><Badge>{status(review.delivery.status)}</Badge><p className={s.documentMeta}>Inspected delivery {review.delivery.id} · version {review.delivery.version}</p><label className={s.field}>Exact provider email receipt<input value={receipt} onChange={e=>{setReceipt(e.target.value);setConfirmed(false)}} maxLength={200}/><small>Readback must match the authorized sender, recipient and generic review link. A mismatched receipt is rejected.</small></label></>}
   <label className={s.field}><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>{review.kind==='configure'?'I reviewed this exact recipient, delivery mode and preference.':'I am checking the original attempt without authorizing a resend.'}</label>{!fresh&&<p className={s.error}>This configuration or delivery changed. Close and inspect its current state.</p>}
  </Modal>}
 </section>;
}
