'use client';
import {useCallback,useEffect,useState} from 'react';
import type {CommandResult,Matter,WorkspaceCommand,WorkspaceSnapshot} from '@/v2/contracts';
import type {Obligation} from '@/v2/obligations';
import {Badge,Empty,Icon,human} from './Primitives';
import {Modal} from './ReviewDialog';
import s from './workspace.module.css';

type Step='propose'|'review'|'fulfill'|'cancel';
type Props={data:WorkspaceSnapshot;matter:Matter;busy:boolean;error:string;pending:boolean;submit:(command:WorkspaceCommand)=>Promise<CommandResult|null>;retryPending:()=>Promise<CommandResult|null>;clearError:()=>void};
const isLegal=(type:string)=>['contractual','legal'].includes(type);
const dateTime=(value:string)=>new Date(value).toLocaleString();

export function ObligationsPanel({data,matter,busy,error,pending,submit,retryPending,clearError}:Props){
 const [review,setReview]=useState<{step:Step;obligation?:Obligation;actorId:string}|null>(null),[form,setForm]=useState<Record<string,string>>({}),[confirmed,setConfirmed]=useState(false);
 const close=useCallback(()=>setReview(null),[]);
 useEffect(()=>{if(review&&(review.actorId!==data.actor.id||review.obligation&&!data.obligations?.some(o=>o.id===review.obligation!.id)))close()},[data,review,close]);
 const field=(name:string)=>({value:form[name]??'',onChange:(event:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>)=>{setForm(old=>({...old,[name]:event.target.value}));setConfirmed(false)}});
 const open=(step:Step,obligation?:Obligation)=>{clearError();setReview({step,obligation,actorId:data.actor.id});setForm({ownerId:data.actor.id,deadlineType:'response_target',dueAt:'',sourceId:'',kind:'human_attestation',actionId:''});setConfirmed(false)};
 const owner=data.capabilities.includes('business_owner'),terminal=['closed','canceled'].includes(matter.state),o=review?.obligation,current=data.obligations?.find(v=>v.id===o?.id);
 const fresh=!o||!!current&&current.version===o.version&&current.basisHash===o.basisHash;
 const allowed=o?review?.step==='fulfill'?(isLegal(o.deadlineType)?data.capabilities.includes('legal_reviewer'):owner||o.ownerId===data.actor.id):data.capabilities.includes(isLegal(o.deadlineType)?'legal_reviewer':'business_owner'):owner;
 const source=data.sources.find(source=>source.id===form.sourceId);
 const valid=!!review&&({propose:!!form.title?.trim()&&!!form.ownerId?.trim()&&!!form.rationale?.trim()&&!!form.fulfillmentCriteria?.trim()&&Number.isFinite(Date.parse(form.dueAt))&&(!isLegal(form.deadlineType)||!!source&&!!form.quote?.trim())&&(!source||!!form.quote?.trim()),review:true,fulfill:!!form.evidence?.trim()&&(form.kind!=='verified_action'||!!form.actionId),cancel:!!form.reason?.trim()}[review.step]);
 async function save(){if(!review||!fresh||!confirmed||!valid||!allowed)return;let command:WorkspaceCommand;
   if(review.step==='propose')command={type:'obligation.propose',matterId:matter.id,title:form.title,ownerId:form.ownerId,dueAt:new Date(form.dueAt).toISOString(),deadlineType:form.deadlineType as Obligation['deadlineType'],rationale:form.rationale,fulfillmentCriteria:form.fulfillmentCriteria,...(form.fulfillmentActionId?{fulfillmentActionId:form.fulfillmentActionId}:{}),...(form.sourceId?{sourceId:form.sourceId,quote:form.quote}:{})};
   else if(review.step==='review')command={type:'obligation.review',obligationId:o!.id,expectedRecordVersion:o!.version,basisHash:o!.basisHash};
   else if(review.step==='fulfill')command={type:'obligation.fulfill',obligationId:o!.id,expectedRecordVersion:o!.version,basisHash:o!.basisHash,kind:form.kind as 'verified_action'|'human_attestation',evidence:form.evidence,...(form.kind==='verified_action'?{actionId:form.actionId}:{})};
   else command={type:'obligation.cancel',obligationId:o!.id,expectedRecordVersion:o!.version,reason:form.reason};
   if(await submit(command))close();
 }
 const records=(data.obligations??[]).filter(x=>x.matterId===matter.id);
 return <div className={s.stack}><div className={s.rowBetween}><div><h2 style={{fontSize:18}}>Obligations and dates</h2><p className={s.muted}>The source, interpretation and accountable owner stay visible.</p></div><button className={s.button} disabled={busy||!owner||terminal} onClick={()=>open('propose')}><Icon name="plus" size={13}/>Propose an obligation</button></div>
 <div className={s.boundary}>Legal and contractual dates require their exact source clause and legal review. Internal launch and response targets are separate. No legal due date is calculated automatically; reminders here are in-app only.</div>
 {!records.length&&<Empty icon="clock" title="Give the next commitment an owner.">Record the exact obligation, a date with its basis, and who will provide the evidence of completion.</Empty>}
 {records.map(record=><section className={s.card} key={record.id} aria-label={`Obligation: ${record.title}`}><div className={s.rowBetween}><h2>{record.title}</h2><div className={s.row}><Badge tone={record.status==='fulfilled'?'green':record.overdue?'red':'amber'}>{human(record.status)}</Badge>{record.overdue&&<Badge tone="red">Overdue</Badge>}{record.status==='active'&&record.eligibility!=='current'&&<Badge tone="amber">Review stale</Badge>}</div></div>
 <dl className={s.definitionList}><dt>Owner</dt><dd>{record.ownerId}</dd><dt>Due</dt><dd>{dateTime(record.dueAt)} · {human(record.deadlineType)}<br/>{record.dueAt}</dd><dt>Calculation / basis</dt><dd>{record.rationale}</dd><dt>Fulfillment criteria</dt><dd>{record.fulfillmentCriteria??'Not recorded'}{record.actionBinding&&<p className={s.small}>Bound action: {data.actions.find(a=>a.id===record.actionBinding!.id)?.title??record.actionBinding.id}</p>}</dd><dt>Source clause</dt><dd>{record.quote||'Internal target; no legal source claimed'}{record.sourceId&&<p className={s.small}>{data.sources.find(src=>src.id===record.sourceId)?.title??'Source unavailable'} · version {record.sourceVersion}</p>}</dd><dt>Review</dt><dd>{record.review?`${record.review.actorId} · ${dateTime(record.review.reviewedAt)} · ${human(record.eligibility??'stale')}`:'Pending the required review capacity'}</dd><dt>Reminder</dt><dd>{record.acknowledgedAt?`Acknowledged ${dateTime(record.acknowledgedAt)}; completion is separate`:'Not acknowledged'}</dd></dl>
 <div className={s.row} style={{marginTop:18}}>{!terminal&&record.status==='proposed'&&<button className={s.primary} disabled={busy||!data.capabilities.includes(isLegal(record.deadlineType)?'legal_reviewer':'business_owner')} onClick={()=>open('review',record)}>Review exact deadline basis</button>}{!terminal&&record.status==='active'&&<button className={s.button} disabled={busy||record.eligibility!=='current'||!(isLegal(record.deadlineType)?data.capabilities.includes('legal_reviewer'):owner||record.ownerId===data.actor.id)} onClick={()=>open('fulfill',record)}>Record fulfillment evidence</button>}{!terminal&&!['fulfilled','canceled'].includes(record.status)&&<><button className={s.button} disabled={busy||!(owner||record.ownerId===data.actor.id)} onClick={()=>void submit({type:'obligation.acknowledge',obligationId:record.id,expectedRecordVersion:record.version})}>Acknowledge reminder</button><button className={s.textButton} disabled={busy||!data.capabilities.includes(isLegal(record.deadlineType)?'legal_reviewer':'business_owner')} onClick={()=>open('cancel',record)}>Cancel with a basis</button></>}</div>
 {record.completion&&<div className={s.previewBox}><Badge tone="green">{human(record.completion.kind)}</Badge>{record.completion.completedLate&&<Badge tone="amber">Completed after due date</Badge>}<p>{record.completion.evidence}</p><p className={s.small}>{record.completion.actorId} · {dateTime(record.completion.recordedAt)}</p></div>}{record.cancellationReason&&<p style={{marginTop:15}}>Cancellation: {record.cancellationReason}</p>}</section>)}
 {review&&<Modal title={review.step==='propose'?'Propose an owned obligation':review.step==='review'?'Review the exact deadline basis':review.step==='fulfill'?'Record obligation fulfillment':'Cancel this obligation'} error={error} close={close} footer={pending?<button className={s.primary} disabled={busy} onClick={async()=>{if(await retryPending())close()}}>Check saved decision</button>:<button className={s.primary} disabled={busy||terminal||!fresh||!allowed||!valid||!confirmed} onClick={()=>void save()}>{review.step==='propose'?'Save for deadline review':review.step==='review'?'Approve this exact basis':review.step==='fulfill'?'Record this completion evidence':'Cancel with this recorded basis'}</button>}>
 {o&&<><Badge tone="purple">Frozen obligation · version {o.version}</Badge><h3 style={{marginTop:15}}>{o.title}</h3><dl className={s.definitionList} style={{marginTop:15}}><dt>Owner</dt><dd>{o.ownerId}</dd><dt>Exact date</dt><dd>{dateTime(o.dueAt)}<br/>{o.dueAt}</dd><dt>Authority type</dt><dd>{human(o.deadlineType)}</dd><dt>Source</dt><dd>{data.sources.find(src=>src.id===o.sourceId)?.title??'Internal target'}</dd><dt>Exact clause</dt><dd>{o.quote??'No legal clause claimed'}</dd><dt>Calculation</dt><dd>{o.rationale}</dd><dt>Fulfillment criteria</dt><dd>{o.fulfillmentCriteria??'Not recorded'}</dd><dt>Bound action</dt><dd>{o.actionBinding?data.actions.find(a=>a.id===o.actionBinding!.id)?.title??o.actionBinding.id:'No action pre-bound; named attestation required'}</dd></dl><div className={s.documentMeta} style={{marginTop:15}}>Deadline basis fingerprint: {o.basisHash}</div></>}
 {review.step==='propose'&&<><label className={s.field}>Obligation title<input {...field('title')} maxLength={300}/></label><label className={s.field}>Provisioned owner identity<input {...field('ownerId')}/></label><label className={s.field}>Date authority<select {...field('deadlineType')}><option value="response_target">Internal response target</option><option value="launch_target">Internal launch target</option><option value="contractual">Contractual deadline</option><option value="legal">Legal deadline</option></select></label><label className={s.field}>Exact due date (your local time)<input type="datetime-local" {...field('dueAt')}/></label><label className={s.field}>Supporting source<select {...field('sourceId')}><option value="">No source — internal target only</option>{data.sources.filter(src=>src.status==='active').map(src=><option key={src.id} value={src.id}>{src.title}</option>)}</select></label>{source&&<><details><summary className={s.small}>Read the complete source</summary><p className={s.longText}>{source.text}</p></details><label className={s.field}>Exact supporting clause<textarea {...field('quote')} maxLength={4000}/></label></>}<label className={s.field}>Date calculation, assumptions and rationale<textarea {...field('rationale')} maxLength={3000} placeholder="Explain the trigger date, period, timezone and assumptions requiring review…"/></label><label className={s.field}>Exact fulfillment criteria<textarea {...field('fulfillmentCriteria')} maxLength={3000} placeholder="What action-specific evidence proves this obligation was met?"/></label><label className={s.field}>Pre-bind a specific action (optional)<select {...field('fulfillmentActionId')}><option value="">No action binding — named attestation</option>{data.actions.filter(a=>a.matterId===matter.id&&a.status!=='canceled').map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select></label></>}
 {review.step==='review'&&<p className={s.muted} style={{marginTop:16}}>Approve the interpretation, date and source version shown above within your assigned capacity. Acknowledging a reminder does not approve its legal basis or fulfill the obligation.</p>}
 {review.step==='fulfill'&&<><label className={s.field}>Completion evidence type<select {...field('kind')}><option value="human_attestation">Named human attestation</option><option value="verified_action" disabled={!o?.actionBinding}>Pre-bound verified action</option></select></label>{form.kind==='verified_action'&&<label className={s.field}>Verified action<select {...field('actionId')}><option value="">Choose completed action</option>{data.actions.filter(a=>a.matterId===matter.id&&a.status==='verified'&&a.completion&&a.id===o?.actionBinding?.id&&a.contentHash===o?.actionBinding?.contentHash).map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select></label>}<label className={s.field}>Action-specific evidence and outcome<textarea {...field('evidence')} maxLength={5000}/></label><p className={s.small}>Human attestation is labeled as such. Legal and contractual fulfillment requires legal reviewer assessment of the exact criteria. Uncertain external effects must be reconciled before fulfillment.</p></>}
 {review.step==='cancel'&&<label className={s.field}>Cancellation basis and follow-up<textarea {...field('reason')} maxLength={3000}/></label>}
 <label className={s.field}><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>I reviewed the exact date, evidence and this decision within my assigned capacity.</label>{!fresh&&<div className={s.error}>The obligation changed. Close this preview and inspect the current version.</div>}
 </Modal>}
 </div>;
}
