import {Badge,Brand,Icon} from './Primitives';
import s from './workspace.module.css';

export default function PublicPage(){return <main className={s.publicPage}>
  <header className={s.publicHeader}><a href="/welcome" aria-label="Kiara home"><Brand/></a><nav className={s.publicLinks}><a href="#how-it-works">How it works</a><a href="#your-control">Your control</a><a href="/" className={s.primary}>Open your workspace <Icon name="arrow" size={13}/></a></nav></header>
  <section className={s.publicHero}><div><div className={s.eyebrow}>A legal partner that knows your company</div><h1>Talk to Kiara.<br/><em>Keep legal in step</em><br/>with your business.</h1><p>Think through a change. Understand your commitments. Prepare the work and bring the right people into the decision—with your company’s context already in the conversation.</p><div className={s.row}><a href="/" className={s.primary}>Start with a question <Icon name="arrow" size={14}/></a><a href="#example" className={s.button}>Explore the journey</a></div><p style={{fontSize:10,marginTop:17}}>Start with one question or document. Connections can come later.</p></div><div id="example" className={s.publicMock}><div className={s.rowBetween}><Brand/><Badge tone="purple">Illustrative journey</Badge></div><div className={s.mockConversation}><div className={s.mockQuestion}>We’re thinking of adding AI summaries to support calls. What should we consider?</div><p>Let’s look at the data flow, your existing customer commitments, and the choices you haven’t made yet.</p><div className={s.artifact}><Icon name="spark"/><span><strong>AI summaries for support calls</strong><small>Scenario · exploring, not deployed</small></span><Icon name="chevron" size={14}/></div></div><div className={s.sourceRow}><Icon name="file" size={15}/><span>Current agreement · §4, subprocessors</span><Badge>Source</Badge></div><div className={s.sourceRow}><Icon name="company" size={15}/><span>Customer transcripts · fact to confirm</span><Badge tone="amber">Pending</Badge></div><a href="/" className={s.textButton} style={{marginTop:17}}>Continue the conversation <Icon name="arrow" size={13}/></a></div></section>
  <section className={s.publicSection} id="how-it-works"><div className={s.eyebrow}>From a question to useful work</div><h2>A little less context to rebuild.<br/>A much clearer next step.</h2><div className={s.threeColumns}>{[{n:'01',title:'Ask in your company’s context.',body:'Understand an agreement or explore an idea. See the sources, assumptions and open questions without turning every conversation into a legal project.'},{n:'02',title:'Connect a change to what matters.',body:'Bring a planned change and its evidence into one matter. Confirm actual practice, identify relevant commitments and route the right factual question.'},{n:'03',title:'Prepare, decide and follow through.',body:'Build a review packet for your counsel. Approve exact content and actions. Keep the work open until the required outcome has evidence.'}].map(item=><article className={s.journeyCard} key={item.n}><span>{item.n}</span><h3>{item.title}</h3><p>{item.body}</p></article>)}</div></section>
  <section className={s.publicSection} id="your-control"><div className={s.twoColumns}><div><div className={s.eyebrow}>Company memory, on your terms</div><h2>It remembers the right things.<br/>You can see why.</h2><p className={s.muted} style={{maxWidth:520,lineHeight:1.9}}>Hypotheticals stay separate from reality. Useful facts need attribution and confirmation. Lessons have a scope, evaluation and an owner. Your decisions stay inspectable.</p></div><div className={s.card}><h3>What stays in your control</h3><ul className={s.checkList}><li><Icon name="check" size={15}/>What sources are included and who can see them</li><li><Icon name="check" size={15}/>Which facts become company memory</li><li><Icon name="check" size={15}/>What is shared with named counsel</li><li><Icon name="check" size={15}/>Exact versions, recipients and destinations</li><li><Icon name="check" size={15}/>Evidence of completion and changes after review</li></ul></div></div></section>
  <section className={s.publicSection}><div className={s.twoColumns}><div><div className={s.eyebrow}>Work with your counsel</div><h2>Bring the whole picture.<br/>Keep the judgment accountable.</h2><p className={s.muted} style={{lineHeight:1.9}}>Give your lawyer a bounded brief, relevant sources, draft wording and specific questions. If you don’t have counsel, prepare an exportable packet and retain an owned review task.</p></div><div className={s.card}><h3>Clear about what’s available</h3><p>This workspace supports saved conversations, scenarios, document intake and controlled review records. Voice input requires browser speech support and permission. Live source connections, referral providers and external delivery depend on configured services. Legal coverage and missing prerequisites are shown in the workspace.</p><p style={{marginTop:15}}>No instant counsel engagement, legal clearance or savings guarantee is implied.</p></div></div></section>
  <section className={s.publicSection}><div className={s.rowBetween}><div><div className={s.eyebrow}>Start where you are</div><h2 style={{marginBottom:0}}>What’s on your mind?</h2></div><a href="/" className={s.primary}>Talk to Kiara <Icon name="arrow" size={14}/></a></div></section><footer className={s.publicFooter}><Brand/><span>Company context. Clear decisions. Work that follows through.</span><a href="/legacy">Original California workflow</a></footer>
</main>}
