'use client';

import {useCallback,useEffect,useState} from 'react';
import type {CommandResult,WorkspaceCommand,WorkspaceSnapshot} from '@/v2/contracts';
import type {RecoveryView} from '@/v2/recovery';
import {Badge,human} from './Primitives';
import {Modal} from './ReviewDialog';
import s from './workspace.module.css';

type Review={kind:'delete';record:RecoveryView['sources'][number];actorId:string}|{kind:'withdraw';record:RecoveryView['matters'][number];actorId:string}|{kind:'stop'|'void';record:RecoveryView['timers'][number];actorId:string};
type Props={data:WorkspaceSnapshot;busy:boolean;error:string;pending:boolean;submit:(command:WorkspaceCommand)=>Promise<CommandResult|null>;retryPending:()=>Promise<CommandResult|null>;clearError:()=>void};

/** Recovery receives only opaque control records. Removed evidence must stay absent. */
export function RecoveryPanel({data,busy,error,pending,submit,retryPending,clearError}:Props){
 const [review,setReview]=useState<Review|null>(null),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false);
 const close=useCallback(()=>setReview(null),[]);
 const recovery=data.recovery??{matters:[],timers:[],sources:[]};
 const current=review?(review.kind==='withdraw'?recovery.matters:review.kind==='delete'?recovery.sources:recovery.timers).find(record=>record.id===review.record.id):undefined;
 const fresh=!!review&&current?.version===review.record.version;
 useEffect(()=>{if(review&&(review.actorId!==data.actor.id||!current))close()},[review,data.actor.id,current,close]);
 const open=(next:Review)=>{clearError();setReview(next);setReason('');setConfirmed(false)};
 async function save(){if(!review||!fresh||!confirmed||!reason.trim())return;const record=review.record;const command:WorkspaceCommand=review.kind==='delete'?{type:'source.revoke',sourceId:record.id,expectedRecordVersion:record.version,reason,delete:true}:review.kind==='withdraw'?{type:'recovery.withdraw',matterId:record.id,expectedRecordVersion:record.version,reason}:review.kind==='stop'?{type:'effort.stop',entryId:record.id,expectedRecordVersion:record.version,evidence:reason}:{type:'effort.void',entryId:record.id,expectedRecordVersion:record.version,reason};if(await submit(command))close()}
 const count=recovery.matters.length+recovery.timers.length+recovery.sources.length;
 return <section className={s.card} aria-label="Recovery after evidence access changes"><h2>When evidence becomes unavailable</h2><p>Removed evidence stays hidden. You can still control your own affected work and time records within your current access scope.</p>
 {!count&&<p className={s.small} style={{marginTop:15}}>No unavailable work or time records currently need recovery.</p>}
 {recovery.matters.map(record=><div key={record.id} className={s.previewBox} style={{marginTop:17}}><div className={s.rowBetween}><h3>Work with removed evidence</h3><Badge>{human(record.state)}</Badge></div><p className={s.documentMeta}>Work reference: {record.id}</p><p className={s.small}>{record.unresolvedEffects} unresolved effects · {record.completedEffects} verified effects retained</p>{record.unresolvedEffects>0&&<p className={s.small}>Previously submitted actions still need reconciliation. Withdrawing future work does not resend or reverse them.</p>}<button className={s.button} style={{marginTop:13}} disabled={busy||pending||!record.canWithdraw} onClick={()=>open({kind:'withdraw',record,actorId:data.actor.id})}>Review withdrawal of future work</button></div>)}
 {recovery.timers.map(record=><div className={s.task} key={record.id}><div><h3>Your time record · removed evidence</h3><p className={s.documentMeta}>Time reference: {record.id}</p><p className={s.small}>Started {new Date(record.startedAt).toLocaleString()} · {record.canStop?'Running, including idle time':record.stoppedAt?`Stopped ${new Date(record.stoppedAt).toLocaleString()}`:'Attributed time record'}</p></div><div className={s.row}>{record.canStop&&<button className={s.button} disabled={busy||pending} onClick={()=>open({kind:'stop',record,actorId:data.actor.id})}>Stop my timer</button>}<button className={s.textButton} disabled={busy||pending} onClick={()=>open({kind:'void',record,actorId:data.actor.id})}>Exclude my record</button></div></div>)}
 {recovery.sources.length>0&&<details style={{marginTop:18}}><summary className={s.small}>Removed source references ({recovery.sources.length})</summary>{recovery.sources.map(record=><div className={s.task} key={record.id}><div><h3>Removed evidence</h3><p className={s.documentMeta}>{record.id}</p></div><div className={s.row}><Badge>{human(record.status)}</Badge>{record.status==='revoked'&&<button className={s.textButton} disabled={busy||pending||!data.capabilities.includes('admin')} onClick={()=>open({kind:'delete',record,actorId:data.actor.id})}>Request deletion of removed source</button>}</div></div>)}</details>}
 {review&&<Modal title={review.kind==='delete'?'Request deletion of removed evidence':review.kind==='withdraw'?'Withdraw future work with removed evidence':review.kind==='stop'?'Stop your timer with unavailable evidence':'Exclude your unavailable time record'} close={close} error={error} footer={pending?<button className={s.primary} disabled={busy} onClick={async()=>{if(await retryPending())close()}}>Check saved decision</button>:<button className={s.primary} disabled={busy||!fresh||!reason.trim()||!confirmed||review.kind==='delete'&&!data.capabilities.includes('admin')} onClick={()=>void save()}>{review.kind==='delete'?'Request deletion of this exact source':review.kind==='withdraw'?'Withdraw future work':review.kind==='stop'?'Stop and attribute elapsed time':'Exclude with this recorded reason'}</button>}>
 <Badge tone="purple">Inspected version {review.record.version}</Badge><p className={s.documentMeta}>Reference: {review.record.id}</p>
 {review.kind==='delete'?<><h3>Removed evidence</h3><p>The title and source content stay unavailable. This requests irreversible removal of retained content and dependent records for the exact opaque source reference above.</p><p className={s.boundary} style={{marginTop:15}}>Current records, search indexes, historical copies, retained originals and backups have separate cleanup states. Necessary action evidence can remain for reconciliation. Completed external actions are not undone, and this workspace cannot restore deleted content.</p></>:review.kind==='withdraw'?<><p>Future work and unused authorizations will be withdrawn. The evidence and its title remain unavailable.</p><p className={s.boundary} style={{marginTop:15}}>{review.record.completedEffects} completed effects and {review.record.unresolvedEffects} unresolved effects are retained. Completed external work is not undone, and uncertain effects still need reconciliation.</p></>:<p>{review.kind==='stop'?'This records all elapsed time through the stop, including idle time.':'This excludes your attributed record from effort comparisons with a retained reason.'} The underlying work and evidence remain hidden.</p>}
 <label className={s.field}>{review.kind==='stop'?'What this elapsed time includes':'Reason and follow-up'}<textarea maxLength={2000} value={reason} onChange={event=>{setReason(event.target.value);setConfirmed(false)}}/></label>
 <label className={s.field}><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>{review.kind==='delete'?'I reviewed this exact source reference, irreversible deletion and remaining retention obligations.':'I reviewed this exact record and the limits of this recovery action.'}</label>
 {!fresh&&<p className={s.error}>This control record changed. Close the preview and inspect its current status.</p>}
 </Modal>}
 </section>;
}
