'use client';

import {useCallback,useEffect,useState} from 'react';
import type {CommandResult,ConversationRunView,WorkspaceCommand,WorkspaceSnapshot} from '@/v2/contracts';
import {Badge,Icon} from './Primitives';
import {Modal} from './ReviewDialog';
import s from './workspace.module.css';

type Props={data:WorkspaceSnapshot;conversationId:string;busy:boolean;error:string;pending:boolean;submit:(command:WorkspaceCommand)=>Promise<CommandResult|null>;retryPending:()=>Promise<CommandResult|null>;clearError:()=>void;viewStatus:()=>void};
const title=(run:ConversationRunView)=>run.status==='queued'?'Your request is saved.':run.status==='running'?'Preparing your response.':run.status==='cancel_requested'?'Generation stopped · accounting is settling.':run.status==='canceled'?'This investigation is stopped.':run.status==='unknown'?'The provider outcome is uncertain.':'This response needs attention.';
export function RunPanel({data,conversationId,busy,error,pending,submit,retryPending,clearError,viewStatus}:Props){
 const [review,setReview]=useState<{run:ConversationRunView;actorId:string;request:string}|null>(null),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),close=useCallback(()=>setReview(null),[]);
 const runs=(data.aiRuns??[]).filter(r=>r.conversationId===conversationId&&r.status!=='complete'),current=runs.find(r=>r.id===review?.run.id);
 const owner=(run:ConversationRunView)=>data.capabilities.includes('member')&&data.messages.some(m=>m.id===run.userMessageId&&m.role==='user'&&m.provenance.actorId===data.actor.id),cancelable=(run:ConversationRunView)=>['queued','running'].includes(run.status)&&owner(run);
 const fresh=!!review&&review.actorId===data.actor.id&&current?.version===review.run.version&&current.status===review.run.status&&cancelable(current);
 useEffect(()=>{if(review&&(review.actorId!==data.actor.id||review.run.conversationId!==conversationId||!data.aiRuns?.some(r=>r.id===review.run.id)||!data.messages.some(m=>m.id===review.run.userMessageId)))close()},[review,data,conversationId,close]);
 if(!runs.length)return null;
 return <section aria-label="Investigation status">{runs.map(run=><div key={run.id} className={['blocked','unknown','cancel_requested','canceled'].includes(run.status)?s.boundary:s.notice} role="status"><Icon name="clock" size={14}/><div><strong>{title(run)}</strong>{run.cancellation?<><p className={s.small} style={{marginTop:7}}>No more generation or output attachment is allowed for this run. Saved conversation history remains.</p>{run.cancellation.reason&&<p className={s.small}>Owner’s reason: {run.cancellation.reason}</p>}<p className={s.small}>{run.cancellation.accounting==='settling'?'Submitted requests are still being reconciled; provider costs may remain.':run.cancellation.accounting==='unknown'?'Provider charge outcome remains unknown; the ledger retains the uncertainty.':'Accounting is settled for the recorded attempts.'} Stopping does not prove a provider abort, refund or data deletion.</p></>:<p className={s.small} style={{marginTop:7}}>{run.reason??'Kiara is working with your permitted context. The saved request remains available if you leave this conversation.'}</p>}{cancelable(run)&&<button className={s.textButton} style={{marginTop:9}} disabled={busy||pending} onClick={()=>{clearError();setReview({run:structuredClone(run),actorId:data.actor.id,request:data.messages.find(m=>m.id===run.userMessageId)!.text});setReason('');setConfirmed(false)}}>Review stopping this investigation</button>}{(run.status==='unknown'||run.status==='blocked')&&<button className={s.textButton} onClick={viewStatus}>View operating status</button>}</div></div>)}
  {review&&<Modal title="Stop this exact investigation" close={close} error={error} footer={pending?<button className={s.primary} disabled={busy} onClick={async()=>{if(await retryPending())close()}}>Check saved stop request</button>:<button className={s.primary} disabled={busy||!fresh||!confirmed||!reason.trim()} onClick={async()=>{if(!fresh)return;if(await submit({type:'run.cancel',runId:review.run.id,expectedRecordVersion:review.run.version,reason}))close()}}>Stop further generation for this run</button>}><Badge>Initiating owner only · run version {review.run.version}</Badge><h3 style={{marginTop:16}}>Your retained request</h3><div className={s.previewBox}><div className={s.longText}>{review.request}</div></div><p className={s.documentMeta}>Run reference: {review.run.id}<br/>Current inspected state: {review.run.status}</p><p>Stopping prevents further generation and output attachment for this investigation. A submitted provider request may still finish and incur costs. Accounting continues until known or explicitly uncertain; this does not refund charges, delete evidence, withdraw approvals or reverse external actions.</p><label className={s.field}>Reason for stopping<textarea maxLength={1000} value={reason} onChange={e=>{setReason(e.target.value);setConfirmed(false)}}/></label><label className={s.field}><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed this exact run and the remaining accounting obligations.</label>{!fresh&&<p className={s.error}>The run changed or is no longer cancelable. Close and inspect its current status.</p>}</Modal>}
 </section>;
}
