'use client';

import {useCallback,useEffect,useState} from 'react';
import type {CommandResult,Source,WorkspaceCommand,WorkspaceSnapshot} from '@/v2/contracts';
import {Badge,human} from './Primitives';
import {Modal} from './ReviewDialog';
import s from './workspace.module.css';

type Props={data:WorkspaceSnapshot;busy:boolean;error:string;pending:boolean;submit:(command:WorkspaceCommand)=>Promise<CommandResult|null>;retryPending:()=>Promise<CommandResult|null>;clearError:()=>void};
export function SourceAccessPanel({data,busy,error,pending,submit,retryPending,clearError}:Props){
 const [review,setReview]=useState<{source:Source;deletion:boolean;actorId:string}|null>(null),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false);
 const close=useCallback(()=>setReview(null),[]);
 const current=data.sources.find(source=>source.id===review?.source.id),fresh=!!review&&!!current&&current.version===review.source.version&&current.aclVersion===review.source.aclVersion&&current.contentHash===review.source.contentHash&&current.status==='active';
 useEffect(()=>{if(review&&(review.actorId!==data.actor.id||!current))close()},[review,data.actor.id,current,close]);
 const open=(source:Source,deletion:boolean)=>{clearError();setReview({source,deletion,actorId:data.actor.id});setReason('');setConfirmed(false)};
 return <>
 {data.sources.length>0&&<section className={s.card} aria-label="Source access controls"><h3>Source access</h3>{data.sources.map(source=><div className={s.task} key={source.id}><div><h3>{source.title}</h3><small>{human(source.scope.kind)} · {human(source.status)}</small></div><div className={s.row}><button className={s.textButton} disabled={busy||pending||source.status!=='active'||!data.capabilities.includes('admin')} onClick={()=>open(source,false)}>Revoke access</button><button className={s.textButton} disabled={busy||pending||source.status!=='active'||!data.capabilities.includes('admin')} onClick={()=>open(source,true)}>Request deletion</button></div></div>)}</section>}
 {(data.deletions??[]).length>0&&<section className={s.card} aria-label="Source deletion progress"><h3>Deletion progress</h3><p>Access removal, current records, search indexes, retained originals, historical copies and backups have separate completion states.</p>{data.deletions.map(job=><div className={s.previewBox} key={job.id}><h3>Removed evidence</h3><p className={s.documentMeta}>Source reference: {job.sourceId}</p><dl className={s.definitionList}><dt>Requested</dt><dd>{new Date(job.requestedAt).toLocaleString()}</dd><dt>Current records</dt><dd>{job.recordsRedacted} redacted records</dd><dt>Retained originals</dt><dd>{job.originalsPending} pending purge</dd><dt>Search index cleanup</dt><dd>{human(job.indexCleanup)}</dd><dt>Historical cleanup</dt><dd>{human(job.historicalCleanup)}</dd><dt>Operational exceptions</dt><dd>{job.operationalExceptions} action records retained for completion or reconciliation</dd><dt>Backups</dt><dd>{human(job.backupStatus)}{job.backupExpiresAt&&<p className={s.small}>Recorded expiry: {new Date(job.backupExpiresAt).toLocaleString()}</p>}</dd></dl><p className={s.small}>A removed source is not proof that every copy has been erased. Pending cleanup and operator verification remain visible.</p></div>)}</section>}
 {review&&<Modal title={review.deletion?'Request deletion of this source':'Revoke access to this source'} close={close} error={error} footer={pending?<button className={s.primary} disabled={busy} onClick={async()=>{if(await retryPending())close()}}>Check saved request</button>:<button className={s.primary} disabled={busy||!fresh||!data.capabilities.includes('admin')||!reason.trim()||!confirmed} onClick={async()=>{if(!fresh||!review)return;if(await submit({type:'source.revoke',sourceId:review.source.id,reason,delete:review.deletion}))close()}}>{review.deletion?'Request this source’s deletion':'Revoke this source’s access'}</button>}>
 <Badge tone="purple">Inspected source · version {review.source.version}</Badge><h3 style={{marginTop:15}}>{review.source.title}</h3><p className={s.small}>{human(review.source.scope.kind)} access · {human(review.source.authority)} authority</p>
 <p style={{marginTop:18}}>The source and records derived from it become unavailable to retrieval and current decisions. Affected work may need owner recovery.</p>
 {review.deletion?<p className={s.boundary} style={{marginTop:15}}>This requests removal of retained source content and dependent records. It cannot restore the original through this workspace. Original purge, index cleanup, historical copies and backups complete separately under retention controls. Necessary action records may remain for reconciliation. Previously completed external actions are not undone.</p>:<p className={s.small} style={{marginTop:15}}>This removes current access. It does not claim deletion of retained originals, historical copies or backups.</p>}
 <label className={s.field}>Reason and follow-up<textarea value={reason} maxLength={1000} onChange={event=>{setReason(event.target.value);setConfirmed(false)}}/></label><label className={s.field}><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>{review.deletion?'I reviewed the exact source, irreversible removal and remaining retention obligations.':'I reviewed the exact source and its effect on dependent work.'}</label>{!fresh&&<p className={s.error}>This source changed. Close the preview and inspect the current record.</p>}
 </Modal>}
 </>;
}
