import {randomUUID} from 'node:crypto';
import {canRead,membership} from './authority';
import {routedTaskOwner} from './collaboration';
import {coverageStatus} from './coverage';
import {obligationCurrent} from './obligations';
import {digest,timestamp} from './store';
import {V2Error,type ActorContext,type RecordBase,type WorkspaceState} from './contracts';

export interface AttentionSettings extends RecordBase {ownerId:string;timezone:string;quietEnabled:boolean;quietStart:string;quietEnd:string;digestAt:string;approachingHours:number}
export interface AttentionDecision extends RecordBase {ownerId:string;itemId:string;fingerprint:string;decision:'acknowledged'|'dismissed';reason:string;matterId:string|null}
type State=WorkspaceState&{attentionSettings?:AttentionSettings[];attentionDecisions?:AttentionDecision[]};
export interface AttentionItem {id:string;fingerprint:string;kind:'task'|'obligation'|'effect'|'counsel'|'coverage'|'update';title:string;detail:string;matterId:string|null;recordId:string;ownerId:string;required:boolean;decisionRequired:boolean;dueAt:string|null;deadlineType:string|null;acknowledged:boolean;placement:'now'|'digest'}
export interface AttentionView {settings:AttentionSettings|null;mode:'decisions'|'digest'|'all';quietNow:boolean;digestReady:boolean;nextDigestAt:string;items:AttentionItem[];dismissedCount:number;delivery:'in_app'}
export type AttentionCommand={type:'attention.configure';expectedRecordVersion:number;timezone:string;quietEnabled:boolean;quietStart:string;quietEnd:string;digestAt:string;approachingHours:number}|{type:'attention.decide';itemId:string;fingerprint:string;decision:'acknowledged'|'dismissed';reason:string};
export const attentionCommandFields:Record<AttentionCommand['type'],string[]>={'attention.configure':['expectedRecordVersion','timezone','quietEnabled','quietStart','quietEnd','digestAt','approachingHours'],'attention.decide':['itemId','fingerprint','decision','reason']};
const ensure=(v:unknown,code:string,message:string)=>{if(!v)throw new V2Error(code,message);};
function minute(value:string){if(typeof value!=='string'||!/^([01]\d|2[0-3]):[0-5]\d$/.test(value))throw new V2Error('INVALID_TIME','Use a 24-hour time such as 09:00.',400);return Number(value.slice(0,2))*60+Number(value.slice(3));}
function clockIn(timezone:string){const formatter=new Intl.DateTimeFormat('en-US',{timeZone:timezone,hour:'2-digit',minute:'2-digit',hourCycle:'h23'});return (at:number)=>{const parts=formatter.formatToParts(at);return Number(parts.find(p=>p.type==='hour')!.value)*60+Number(parts.find(p=>p.type==='minute')!.value);};}
function settings(s:State,a:ActorContext){return [...s.attentionSettings||[]].reverse().find(p=>p.ownerId===a.actorId&&canRead(s,a,p))||null;}
function windowAt(p:AttentionSettings|null,now:number){const clock=clockIn(p?.timezone||'UTC'),at=clock(now),start=minute(p?.quietStart||'18:00'),end=minute(p?.quietEnd||'09:00'),quietNow=!!p?.quietEnabled&&(start<end?at>=start&&at<end:at>=start||at<end),digestMinute=minute(p?.digestAt||'09:00');let next=now-now%60000+60000;for(let n=0;n<48*60;n++,next+=60000)if(clock(next)===digestMinute)break;return {quietNow,digestReady:at>=digestMinute&&!quietNow,nextDigestAt:new Date(next).toISOString()};}
function base(s:State,a:ActorContext,record?:RecordBase):RecordBase{return {id:randomUUID(),tenantId:s.tenantId,version:1,createdAt:timestamp(),updatedAt:timestamp(),scope:{kind:'private',actorIds:[a.actorId],...(record?.scope.matterId?{matterId:record.scope.matterId}:{})},provenance:{actorId:a.actorId,sourceIds:[...record?.provenance.sourceIds||[]],factIds:[...record?.provenance.factIds||[]],description:'Personal attention decision; no work approval, legal conclusion or relevance training label.'}};}
type Candidate={item:Omit<AttentionItem,'fingerprint'|'acknowledged'|'placement'>;basis:unknown;record:RecordBase};
function candidates(s:State,a:ActorContext,now:number,p:AttentionSettings|null):Candidate[]{
 const result:Candidate[]=[],hours=p?.approachingHours||24;
 const add=(record:RecordBase,item:Candidate['item'],basis:unknown)=>{if(canRead(s,a,record))result.push({record,item,basis});};
 for(const m of s.matters.filter(m=>canRead(s,a,m)&&!['closed','canceled'].includes(m.state))){
  const own=m.tasks.filter(t=>t.status!=='done'&&routedTaskOwner(s,m,t)===a.actorId);
  for(const t of own){const due=t.dueAt?Date.parse(t.dueAt):NaN,overdue=Number.isFinite(due)&&due<=now;add(m,{id:`task:${t.id}`,kind:'task',title:t.title,detail:overdue?'The recorded target has passed. Inspect its authority and current work.':t.status==='blocked'?'This owned task is blocked. Open the matter for its current dependency.':'A decision or factual response is assigned to you.',matterId:m.id,recordId:t.id,ownerId:a.actorId,required:overdue,decisionRequired:true,dueAt:t.dueAt,deadlineType:t.deadlineType,}, {matterVersion:m.version,task:t,owner:a.actorId,overdue});}
  if(m.ownerId===a.actorId&&!own.length)add(m,{id:`update:${m.id}`,kind:'update',title:m.title,detail:m.blockers[0]||'This work remains open. Open the matter for its actual status.',matterId:m.id,recordId:m.id,ownerId:a.actorId,required:false,decisionRequired:false,dueAt:null,deadlineType:null},{version:m.version,state:m.state});
 }
 for(const o of s.obligations||[]){if(!['active','proposed'].includes(o.status)||!canRead(s,a,o))continue;const m=s.matters.find(m=>m.id===o.matterId);if(o.ownerId!==a.actorId&&m?.ownerId!==a.actorId)continue;const due=Date.parse(o.dueAt),overdue=o.status==='active'&&Number.isFinite(due)&&due<=now,current=obligationCurrent(s,a,o),approaching=Number.isFinite(due)&&due>now&&due-now<=hours*3600000;if(!overdue&&!approaching&&current)continue;add(o,{id:`obligation:${o.id}`,kind:'obligation',title:o.title,detail:!current?'The obligation basis needs a current authorized review.':overdue?'The reviewed obligation is past its recorded deadline. Acknowledgment does not fulfill it.':'The recorded deadline is approaching. Inspect its authority and fulfillment criteria.',matterId:o.matterId,recordId:o.id,ownerId:o.ownerId,required:overdue||!current,decisionRequired:true,dueAt:o.dueAt,deadlineType:o.deadlineType},{version:o.version,basisHash:o.basisHash,overdue,approaching,current});}
 for(const effect of s.actions.filter(x=>['uncertain','verifying','failed'].includes(x.status))){const m=s.matters.find(m=>m.id===effect.matterId);if(m?.ownerId!==a.actorId)continue;add(effect,{id:`effect:${effect.id}`,kind:'effect',title:effect.title,detail:effect.status==='failed'?'The required effect failed. Its completion needs an owned corrective decision.':'Provider completion has not been established. Reconcile the retained effect; do not resend.',matterId:effect.matterId,recordId:effect.id,ownerId:a.actorId,required:true,decisionRequired:true,dueAt:null,deadlineType:null},{version:effect.version,status:effect.status});}
 for(const engagement of s.counsel){if(engagement.ownerId!==a.actorId||['complete','returned'].includes(engagement.status))continue;const overdue=!!engagement.responseDueAt&&Date.parse(engagement.responseDueAt)<=now;if(!overdue&&engagement.status!=='unavailable'&&!engagement.escalation)continue;add(engagement,{id:`counsel:${engagement.id}`,kind:'counsel',title:'Counsel coordination needs a decision',detail:engagement.status==='unavailable'?'No engaged provider is available. Keep the pending review owned or export a scoped packet.':overdue?'The agreed response target has passed. Inspect the engagement and escalation options.':'The engagement scope or budget needs review.',matterId:engagement.matterId,recordId:engagement.id,ownerId:a.actorId,required:true,decisionRequired:true,dueAt:engagement.responseDueAt,deadlineType:'response_target'},{version:engagement.version,status:engagement.status,overdue});}
 for(const c of s.coverage){if(c.ownerId!==a.actorId&&c.qualifiedReviewerId!==a.actorId||!canRead(s,a,c))continue;const status=coverageStatus(s,a,c);if(status!=='stale'&&status!=='pending_review')continue;add(c,{id:`coverage:${c.id}`,kind:'coverage',title:`Review ${c.domain} coverage`,detail:status==='stale'?'Source or reviewer freshness is no longer established. Dependent legal conclusions need renewed review.':'This declared coverage has not received its required review.',matterId:null,recordId:c.id,ownerId:c.ownerId||a.actorId,required:true,decisionRequired:true,dueAt:c.reviewDueAt,deadlineType:'response_target'},{version:c.version,status});}
 return result;
}
export function attentionView(s:State,a:ActorContext,now=Date.now()):AttentionView{
 membership(s,a);const p=settings(s,a),window=windowAt(p,now),value=[...s.preferences].reverse().find(p=>p.active&&p.ownerId===a.actorId&&p.target==='personal'&&p.key==='interruptions'&&canRead(s,a,p))?.value,mode=value==='digest'||value==='all'?value:'decisions';let dismissedCount=0;
 const items=candidates(s,a,now,p).flatMap(({item,basis})=>{const fingerprint=digest({item,basis}),decision=[...s.attentionDecisions||[]].reverse().find(d=>d.ownerId===a.actorId&&d.itemId===item.id&&d.fingerprint===fingerprint&&canRead(s,a,d));if(decision?.decision==='dismissed'&&!item.required){dismissedCount++;return [];}const placement=item.required?'now':window.quietNow||mode==='digest'&&!window.digestReady||mode==='decisions'&&!item.decisionRequired?'digest':'now';return [{...item,fingerprint,acknowledged:decision?.decision==='acknowledged',placement} as AttentionItem];});
 items.sort((x,y)=>Number(y.required)-Number(x.required)||(Date.parse(x.dueAt||'')||Infinity)-(Date.parse(y.dueAt||'')||Infinity)||x.id.localeCompare(y.id));
 return {settings:p?structuredClone(p):null,mode,...window,items,dismissedCount,delivery:'in_app'};
}
export function applyAttentionCommand(s:State,a:ActorContext,c:AttentionCommand):Record<string,unknown>{
 membership(s,a);if(c.type==='attention.configure'){
  const prior=settings(s,a);ensure(Number.isSafeInteger(c.expectedRecordVersion)&&(prior?.version||0)===c.expectedRecordVersion,'VERSION_CONFLICT','Inspect the current attention settings before changing them.');
  ensure(typeof c.timezone==='string'&&c.timezone.length<=100,'INVALID_TIMEZONE','Choose an IANA timezone.');try{clockIn(c.timezone)(Date.now());}catch{throw new V2Error('INVALID_TIMEZONE','Choose a valid IANA timezone.',400);}
  minute(c.quietStart);minute(c.quietEnd);minute(c.digestAt);ensure(typeof c.quietEnabled==='boolean'&&(!c.quietEnabled||c.quietStart!==c.quietEnd),'INVALID_QUIET_HOURS','Choose distinct start and end times for enabled quiet hours.');ensure(Number.isInteger(c.approachingHours)&&c.approachingHours>=1&&c.approachingHours<=168,'INVALID_THRESHOLD','Choose a deadline reminder window from 1 to 168 hours.');
  const record:AttentionSettings={...(prior||base(s,a)),ownerId:a.actorId,timezone:c.timezone,quietEnabled:c.quietEnabled,quietStart:c.quietStart,quietEnd:c.quietEnd,digestAt:c.digestAt,approachingHours:c.approachingHours};if(prior){record.version++;record.updatedAt=timestamp();Object.assign(prior,record);}else(s.attentionSettings||=[]).push(record);return {settingsId:record.id};
 }
 ensure(typeof c.reason==='string'&&c.reason.trim().length>0&&c.reason.length<=2000,'REASON_REQUIRED','Record why you acknowledged or dismissed this item.');ensure(['acknowledged','dismissed'].includes(c.decision),'INVALID_DECISION','Choose acknowledgment or dismissal.');
 const item=attentionView(s,a).items.find(item=>item.id===c.itemId);ensure(item&&item.fingerprint===c.fingerprint,'ATTENTION_CHANGED','The item changed or is no longer available. Inspect the current work.');ensure(c.decision!=='dismissed'||!item!.required,'REQUIRED_ATTENTION','Required escalation stays visible. Acknowledge it without hiding the pending work.');
 const candidate=candidates(s,a,Date.now(),settings(s,a)).find(x=>x.item.id===c.itemId)!;const record:AttentionDecision={...base(s,a,candidate.record),ownerId:a.actorId,itemId:c.itemId,fingerprint:c.fingerprint,decision:c.decision,reason:c.reason.trim(),matterId:item!.matterId};(s.attentionDecisions||=[]).push(record);return {decisionId:record.id};
}
