import {randomUUID} from 'node:crypto';
import {canRead,membership,readRecord,requireRole} from './authority';
import {V2Error,type ActorContext,type Approval,type CounselEngagement,type Matter,type Proposal,type RecordBase,type WorkspaceState} from './contracts';
import {activePacketGrant,counselPacketHash,grantRecordHash,matterPacketHash,type CounselLifecycle} from './sharing';
import {digest,timestamp} from './store';
import {resetReviewTasks} from './tasks';

export type CounselCommand =
 | {type:'counsel.intake';engagementId:string;expectedRecordVersion:number;counselActorId:string;conflictsCleared:boolean;intakeEvidence:string}
 | {type:'counsel.engage';engagementId:string;expectedRecordVersion:number;terms:string;feeCap:number;currency:string;responseDueAt:string}
 | {type:'counsel.share';engagementId:string;expectedRecordVersion:number;packetHash:string;recipientActorId:string;validUntil:string}
 | {type:'counsel.revoke';engagementId:string;expectedRecordVersion:number;reason:string}
 | {type:'counsel.escalate';engagementId:string;expectedRecordVersion:number;reason:'non_response'|'unavailable_expertise'|'rejected_scope'|'budget_increase';detail:string}
 | {type:'counsel.return';engagementId:string;expectedRecordVersion:number;proposalId:string;proposalHash:string;body?:string;note:string;disposition:'revised_proposal'|'evidence_request'};
export const counselCommandFields:Record<CounselCommand['type'],string[]>={
 'counsel.intake':['engagementId','expectedRecordVersion','counselActorId','conflictsCleared','intakeEvidence'],
 'counsel.engage':['engagementId','expectedRecordVersion','terms','feeCap','currency','responseDueAt'],
 'counsel.share':['engagementId','expectedRecordVersion','packetHash','recipientActorId','validUntil'],
 'counsel.revoke':['engagementId','expectedRecordVersion','reason'],
 'counsel.escalate':['engagementId','expectedRecordVersion','reason','detail'],
 'counsel.return':['engagementId','expectedRecordVersion','proposalId','proposalHash','body','note','disposition'],
};
type Engagement=CounselEngagement & CounselLifecycle;
function ensure(value:unknown,code:string,message:string,status=409):asserts value {if(!value)throw new V2Error(code,message,status);}
function text(value:unknown,label:string,max=12000){ensure(typeof value==='string'&&value.trim()&&value.length<=max,'INVALID_INPUT',`Provide ${label} (up to ${max} characters).`,400);return value.trim();}
function touch(r:RecordBase){r.version++;r.updatedAt=timestamp();}
function base(s:WorkspaceState,a:ActorContext,record:RecordBase):RecordBase{return {id:randomUUID(),tenantId:s.tenantId,version:1,createdAt:timestamp(),updatedAt:timestamp(),scope:structuredClone(record.scope),provenance:{actorId:a.actorId,sourceIds:[...record.provenance.sourceIds],factIds:[...(record.provenance.factIds||[])],description:'Attributed counsel coordination decision'}};}
function openMatter(s:WorkspaceState,a:ActorContext,id:string){const m=readRecord(s,a,s.matters,id);ensure(!['closed','canceled'].includes(m.state),'MATTER_TERMINAL','Open corrective work for a closed or canceled matter.');ensure(!m.legacyWorkflowId,'LEGACY_EXECUTION_OWNER','Legacy work keeps its existing execution owner.');return m;}
function event(s:WorkspaceState,a:ActorContext,e:Engagement,title:string,detail:string){s.events.push({...base(s,a,e),type:'counsel.coordination',title,detail,matterId:e.matterId,recordId:e.id,measurement:s.rehearsal?'fictional_rehearsal':'observed'});}
function currentProposal(s:WorkspaceState,a:ActorContext,m:Matter){ensure(m.proposalId,'PROPOSAL_REQUIRED','Prepare a current proposal before sharing substantive material.');const p=readRecord(s,a,s.proposals,m.proposalId);ensure(p.status==='current','STALE_PROPOSAL','Prepare a current proposal before continuing.');ensure(p.dependencies.policyVersion===s.ruleVersion,'DEPENDENCIES_CHANGED','Procedure changed; prepare a current proposal.');for(const [id,v] of Object.entries(p.dependencies.sourceVersions))ensure(readRecord(s,a,s.sources,id).version===v,'DEPENDENCIES_CHANGED','Source evidence changed.');for(const [id,v] of Object.entries(p.dependencies.factVersions)){const f=readRecord(s,a,s.facts,id);ensure(f.version===v&&f.status==='confirmed','DEPENDENCIES_CHANGED','Confirmed facts changed.');}for(const [id,hash] of Object.entries(p.dependencies.documentHashes))ensure(readRecord(s,a,s.documents,id).contentHash===hash,'DEPENDENCIES_CHANGED','Document evidence changed.');return p;}
function recordsForPacket(s:WorkspaceState,a:ActorContext,m:Matter,p:Proposal,e:Engagement):RecordBase[]{
 const sources=e.provenance.sourceIds.map(id=>readRecord(s,a,s.sources,id));
 const facts=(e.provenance.factIds||[]).map(id=>readRecord(s,a,s.facts,id));
 const docs=s.documents.filter(d=>sources.some(x=>x.id===d.sourceId));for(const d of docs)ensure(canRead(s,a,d),'SHARING_SCOPE','A selected document is unavailable.',403);
 return [m,p,e,...sources,...facts,...docs];
}
function packetEvidenceHash(s:WorkspaceState,a:ActorContext,e:Engagement){const sources=e.provenance.sourceIds.map(id=>readRecord(s,a,s.sources,id));const facts=(e.provenance.factIds||[]).map(id=>readRecord(s,a,s.facts,id));const documents=s.documents.filter(d=>sources.some(x=>x.id===d.sourceId));for(const d of documents)ensure(canRead(s,a,d),'SHARING_SCOPE','A selected document is unavailable.',403);return digest({sources,facts,documents});}
function revoke(s:WorkspaceState,e:Engagement){if(e.sharing){e.sharing.revokedAt=timestamp();const approval=s.approvals.find(x=>x.id===e.sharing!.approvalId);if(approval){approval.status='revoked';touch(approval);}}e.sharingApprovalId=null;}
function requireRecipient(s:WorkspaceState,e:Engagement){const r=s.memberships.find(m=>m.actorId===e.counselActorId);ensure(r&&!r.revokedAt&&r.roles.includes('legal_reviewer')&&(!r.expiresAt||Date.parse(r.expiresAt)>Date.now())&&(!r.matterIds||r.matterIds.includes(e.matterId))&&(!r.entityIds||r.entityIds.includes(s.entityId)),'COUNSEL_MEMBERSHIP_REQUIRED','Choose an active legal reviewer with access to this entity and matter.',403);return r;}
function termsHash(e:Engagement){return digest({terms:e.terms,feeCap:e.feeCap,currency:e.currency,responseDueAt:e.responseDueAt,counselActorId:e.counselActorId});}
export function prepareCounselRequest(s:WorkspaceState,a:ActorContext,c:{matterId:string;route:'existing'|'referral';providerName?:string;recipient?:string;sourceIds?:string[];feeCap?:number;terms?:string}){
 const m=openMatter(s,a,c.matterId);requireRole(s,a,'business_owner',m);ensure(['existing','referral'].includes(c.route),'INVALID_INPUT','Choose existing counsel or opt-in referral.',400);
 const p=m.proposalId?readRecord(s,a,s.proposals,m.proposalId):null;
 ensure(!c.sourceIds||Array.isArray(c.sourceIds)&&c.sourceIds.length<=100,'INVALID_INPUT','Choose up to 100 source records.',400);
 const ids=[...new Set([...(c.sourceIds||m.sourceIds),...(p?.provenance.sourceIds||[])])];const sources=ids.map(id=>readRecord(s,a,s.sources,id));
 const factIds=p?.provenance.factIds||[];const facts=factIds.map(id=>readRecord(s,a,s.facts,id));
 const packet=`${m.title}\n\nObjective\n${m.objective}\n\nQuestions and unknowns\n${m.blockers.join('\n')}\n\nVerified facts\n${facts.map(f=>`${f.predicate}: ${JSON.stringify(f.value)} (${f.practice}; ${f.status}; owner ${f.ownerId})`).join('\n')||'No confirmed facts selected.'}\n\nProposed work\n${p?.body||'Preparation pending.'}\n\nFull selected source records (sharing grants access to these complete records)\n${sources.map(x=>`${x.title} [${x.authority}; revision ${x.version}]\n${x.text}`).join('\n\n')||'No sources selected.'}`;
 ensure(packet.length<=500000,'PACKET_TOO_LARGE','Narrow the matter evidence before preparing the counsel packet.',413);
 const e:Engagement={...base(s,a,m),matterId:m.id,route:c.route,providerName:c.providerName?text(c.providerName,'a provider name',200):null,recipient:c.recipient?text(c.recipient,'a recipient',300):null,status:c.route==='referral'?'unavailable':'intake_pending',conflictsCleared:false,sharingApprovalId:null,approvedSourceIds:[],terms:null,feeCap:null,currency:'USD',responseDueAt:null,ownerId:a.actorId,packet,returnedProposalId:null,counselActorId:null,intakeEvidence:null,intakeRecordedBy:null,engagementApproval:null,sharing:null,reviewNotes:[],escalation:null};
 e.provenance.sourceIds=ids;e.provenance.factIds=factIds;s.counsel.push(e);m.state='legal_review';m.blockers=[c.route==='referral'?'No qualified referral provider is configured. Export the packet and appoint counsel; legal review stays pending.':'Record existing counsel intake and conflicts evidence, approve terms and fee cap, then review the exact sharing scope.'];touch(m);e.preparedProposal=p?{id:p.id,contentHash:p.contentHash,dependenciesHash:digest(p.dependencies),matterHash:matterPacketHash(m),evidenceHash:packetEvidenceHash(s,a,e)}:null;event(s,a,e,'Counsel packet prepared','No invitation, substantive sharing, engagement or fee commitment has occurred.');return {engagementId:e.id,packetHash:counselPacketHash(e)};
}
export function applyCounselCommand(s:WorkspaceState,a:ActorContext,c:CounselCommand):Record<string,unknown>{
 const e=readRecord(s,a,s.counsel,c.engagementId) as Engagement;ensure(e.version===c.expectedRecordVersion,'VERSION_CONFLICT','Counsel coordination changed; inspect the current packet.');const m=openMatter(s,a,e.matterId);
 if(c.type==='counsel.return')requireRole(s,a,'legal_reviewer',e);else requireRole(s,a,'business_owner',e);
 switch(c.type){
 case 'counsel.intake':{
  ensure(e.route==='existing','REFERRAL_UNAVAILABLE','No qualified referral provider is configured. Bring named existing counsel to a new packet.');ensure(c.conflictsCleared===true,'CONFLICTS_PENDING','Record completed conflicts clearance before substantive sharing.');
  revoke(s,e);e.counselActorId=text(c.counselActorId,'a provisioned reviewer identity',200);requireRecipient(s,e);e.intakeEvidence=text(c.intakeEvidence,'the intake and conflicts evidence',4000);e.intakeRecordedBy=a.actorId;e.conflictsCleared=true;e.engagementApproval=null;e.status='engagement_pending';touch(e);event(s,a,e,'Counsel intake recorded','A business owner attributed external intake/conflicts evidence; no provider verification is implied.');break;
 }
 case 'counsel.engage':{
  ensure(e.conflictsCleared&&e.intakeEvidence,'CONFLICTS_PENDING','Complete intake and conflicts first.');requireRecipient(s,e);ensure(Number.isFinite(c.feeCap)&&c.feeCap>=0&&c.feeCap<=10000000,'INVALID_FEE','Approve an explicit nonnegative fee cap.',400);ensure(/^[A-Z]{3}$/.test(c.currency),'INVALID_CURRENCY','Use a three-letter currency.',400);ensure(Number.isFinite(Date.parse(c.responseDueAt))&&Date.parse(c.responseDueAt)>Date.now(),'INVALID_DEADLINE','Choose the agreed future response time.',400);
  revoke(s,e);e.terms=text(c.terms,'the exact engagement scope and terms');e.feeCap=c.feeCap;e.currency=c.currency;e.responseDueAt=new Date(c.responseDueAt).toISOString();const member=membership(s,a);e.engagementApproval={actorId:a.actorId,membershipVersion:member.version,termsHash:termsHash(e),approvedAt:timestamp()};e.status='sharing_pending';e.escalation=null;touch(e);event(s,a,e,'Engagement terms approved',`Approved fee cap ${e.currency} ${e.feeCap}. Professional fees are separate from subscription fees; no charge was initiated.`);break;
 }
 case 'counsel.share':{
  const p=currentProposal(s,a,m),recipient=requireRecipient(s,e),member=membership(s,a);ensure(e.preparedProposal&&e.preparedProposal.id===p.id&&e.preparedProposal.contentHash===p.contentHash&&e.preparedProposal.dependenciesHash===digest(p.dependencies)&&e.preparedProposal.matterHash===matterPacketHash(m)&&e.preparedProposal.evidenceHash===packetEvidenceHash(s,a,e),'COUNSEL_PACKET_STALE','The proposal or material matter context changed after this packet was prepared. Prepare and inspect a new counsel packet.');const owner=e.engagementApproval&&s.memberships.find(x=>x.actorId===e.engagementApproval!.actorId);
  ensure(e.status==='sharing_pending'&&e.engagementApproval?.termsHash===termsHash(e)&&owner&&!owner.revokedAt&&owner.version===e.engagementApproval.membershipVersion&&owner.roles.includes('business_owner')&&(!owner.expiresAt||Date.parse(owner.expiresAt)>Date.now()),'ENGAGEMENT_REQUIRED','Approve current engagement terms and fee cap first.');ensure(e.counselActorId===c.recipientActorId&&c.packetHash===counselPacketHash(e),'SHARING_INTENT_CHANGED','Review the exact packet, full source records, recipient and engagement terms.');
  const expires=Date.parse(c.validUntil);ensure(Number.isFinite(expires)&&expires>Date.now()&&expires<=Date.now()+30*86400000,'INVALID_EXPIRY','Choose a sharing expiry within 30 days.',400);ensure(e.provenance.sourceIds.every(id=>p.provenance.sourceIds.includes(id)||s.sources.some(x=>x.id===id&&canRead(s,a,x))),'SHARING_SCOPE','Source scope changed.');
  const approval:Approval={...base(s,a,e),matterId:m.id,proposalId:p.id,proposalHash:p.contentHash,actionId:null,actionHash:c.packetHash,capacity:'sharing',actorId:a.actorId,membershipVersion:member.version,dependencies:structuredClone(p.dependencies),conditions:[],recipients:[recipient.actorId],destination:`workspace:reviewer:${recipient.actorId}`,validUntil:new Date(expires).toISOString(),status:'active',note:'Explicitly approved the full selected records and exact counsel packet.'};s.approvals.push(approval);e.sharingApprovalId=approval.id;e.approvedSourceIds=[...e.provenance.sourceIds];e.status='review_pending';touch(e);m.blockers=['Awaiting named counsel review under the approved engagement terms.'];for(const task of m.tasks.filter(t=>t.kind==='legal'&&t.status!=='done'))task.ownerId=recipient.actorId;touch(m);
  e.sharing={recipientActorId:recipient.actorId,recipientMembershipVersion:recipient.version,approvalId:approval.id,packetHash:c.packetHash,expiresAt:approval.validUntil,revokedAt:null,records:[],sourceVersions:Object.fromEntries(e.provenance.sourceIds.map(id=>{const x=readRecord(s,a,s.sources,id);return [id,x.version];})),factVersions:Object.fromEntries((e.provenance.factIds||[]).map(id=>{const x=readRecord(s,a,s.facts,id);ensure(x.status==='confirmed','FACT_CONFIRMATION_REQUIRED','Share confirmed facts or label unknowns in a new packet.');return [id,x.version];}))};
  e.sharing.records=recordsForPacket(s,a,m,p,e).map(r=>({id:r.id,hash:grantRecordHash(r)}));event(s,a,e,'Exact counsel packet shared',`Access granted to provisioned reviewer ${recipient.actorId} until ${approval.validUntil}. No email invitation was sent.`);break;
 }
 case 'counsel.revoke':revoke(s,e);e.status='sharing_pending';touch(e);event(s,a,e,'Counsel packet access revoked',text(c.reason,'a revocation reason',2000));break;
 case 'counsel.escalate':{
  ensure(['non_response','unavailable_expertise','rejected_scope','budget_increase'].includes(c.reason),'INVALID_ESCALATION','Choose an escalation reason.',400);revoke(s,e);e.escalation={reason:c.reason,detail:text(c.detail,'the escalation and next owner action',4000),recordedAt:timestamp()};e.engagementApproval=null;e.status='engagement_pending';touch(e);m.blockers=[`Counsel escalation: ${c.reason.replaceAll('_',' ')}. ${e.escalation.detail}`];touch(m);event(s,a,e,'Counsel coordination needs a new decision','Prior sharing was revoked. Changed fees, scope or recipient require new approval.');break;
 }
 case 'counsel.return':{
  ensure(e.status==='review_pending'&&e.counselActorId===a.actorId&&e.sharing&&activePacketGrant(s,a,e),'COUNSEL_ASSIGNMENT_REQUIRED','Only the assigned reviewer can return this currently shared packet.',403);const p=currentProposal(s,a,m);ensure(p.id===c.proposalId&&p.contentHash===c.proposalHash,'STALE_PROPOSAL','Inspect the current exact proposal.');ensure(['revised_proposal','evidence_request'].includes(c.disposition),'INVALID_DISPOSITION','Choose edits or an evidence request.',400);const note=text(c.note,'review notes and outstanding questions',8000);(e.reviewNotes||=[]).push(note);
  if(c.disposition==='revised_proposal'){
   const body=text(c.body,'the returned proposal',100000);p.status='superseded';touch(p);const next:Proposal={...structuredClone(p),...base(s,a,p),body,contentHash:digest(body),status:'current',supersedesId:p.id};s.proposals.push(next);m.proposalId=next.id;m.state='business_review';m.blockers=['Counsel returned edits. Business and legal decisions must inspect the new exact proposal.'];e.returnedProposalId=next.id;e.status='returned';resetReviewTasks(s,m,next);for(const approval of s.approvals.filter(x=>x.proposalId===p.id&&x.capacity!=='sharing'&&x.status==='active')){approval.status='invalidated';touch(approval);}for(const action of s.actions.filter(x=>x.proposalId===p.id&&!['verified','dispatching','uncertain'].includes(x.status))){action.status='planned';action.authorizationId=null;touch(action);}e.sharing.records.push({id:next.id,hash:grantRecordHash(next)});
  }else {m.state='needs_facts';m.blockers=[note];}
  touch(e);touch(m);for(const r of [e,m,p]){const grant=e.sharing.records.find(x=>x.id===r.id);if(grant)grant.hash=grantRecordHash(r);}event(s,a,e,c.disposition==='revised_proposal'?'Counsel edits returned':'Counsel requested evidence','This records review work; it does not itself grant legal clearance or authorize external action.');break;
 }
 }
 return {engagementId:e.id,packetHash:counselPacketHash(e),status:e.status,proposalId:e.returnedProposalId};
}
