import {currentEvidenceLineage} from './source-lifecycle';
import {randomUUID} from 'node:crypto';
import {legalAuthorityHasPendingChange} from './legal-maintenance';
import {canRead,membership,readRecord,requireRole} from './authority';
import {V2Error,type ActorContext,type CoverageEntry,type LegalAuthority,type RecordBase,type Source,type WorkspaceState} from './contracts';
import {digest,timestamp} from './store';
export interface AuthorityMaintenance {verifiedSourceVersion?:number;verifiedSourceHash?:string;verificationEvidence?:string;reviewDueAt?:string;reviewMembershipVersion?:number}
export interface CoverageMaintenance {authorityIds?:string[];authorityVersions?:Record<string,number>;qualificationEvidence?:string;reviewMembershipVersion?:number;qualification?:'named_reviewer_attestation'|'fictional_local_attestation'}
export type CoverageCommand=
 | {type:'coverage.source.add';sourceId:string;title:string;sourceUrl:string;jurisdiction:string;domain:string;authorityType:LegalAuthority['authorityType'];publishedAt?:string;effectiveFrom?:string;effectiveUntil?:string}
 | {type:'coverage.source.verify';authorityId:string;expectedRecordVersion:number;sourceVersion:number;verificationEvidence:string;reviewDueAt:string}
 | {type:'coverage.define';domain:string;jurisdiction:string;authorityIds:string[];limitations:string[]}
 | {type:'coverage.review';coverageId:string;expectedRecordVersion:number;qualificationEvidence:string;reviewDueAt:string;limitations:string[]}
 | {type:'coverage.unavailable';coverageId:string;expectedRecordVersion:number;reason:string};
export const coverageCommandFields:Record<CoverageCommand['type'],string[]>={'coverage.source.add':['sourceId','title','sourceUrl','jurisdiction','domain','authorityType','publishedAt','effectiveFrom','effectiveUntil'],'coverage.source.verify':['authorityId','expectedRecordVersion','sourceVersion','verificationEvidence','reviewDueAt'],'coverage.define':['domain','jurisdiction','authorityIds','limitations'],'coverage.review':['coverageId','expectedRecordVersion','qualificationEvidence','reviewDueAt','limitations'],'coverage.unavailable':['coverageId','expectedRecordVersion','reason']};
function need(v:unknown,code:string,message:string):asserts v {if(!v)throw new V2Error(code,message);}
function text(v:unknown,label:string,max=2000){need(typeof v==='string'&&v.trim().length>0&&v.length<=max,'INVALID_INPUT',`Provide bounded ${label}.`);return v.trim();}
function date(v:string|undefined){if(v===undefined)return null;need(Number.isFinite(Date.parse(v)),'INVALID_TIME','Provide a valid date.');return new Date(v).toISOString();}
function due(v:string){const at=Date.parse(v);need(Number.isFinite(at)&&at>Date.now()&&at<=Date.now()+90*86400000,'INVALID_REVIEW_DEADLINE','Set a review date within the next 90 days.');return new Date(at).toISOString();}
function base(s:WorkspaceState,a:ActorContext,scope:RecordBase['scope'],sourceIds:string[]):RecordBase{return {id:randomUUID(),tenantId:s.tenantId,version:1,createdAt:timestamp(),updatedAt:timestamp(),scope:structuredClone(scope),provenance:{actorId:a.actorId,sourceIds,description:'Named legal source maintenance decision'}};}
function touch(r:RecordBase){r.version++;r.updatedAt=timestamp();}
function version(r:RecordBase,expected:number){need(r.version===expected,'VERSION_CONFLICT','Inspect the current source or coverage entry.');}
function limitations(v:string[]){need(Array.isArray(v)&&v.length<=20,'INVALID_INPUT','Provide up to 20 coverage limitations.');return v.map(x=>text(x,'limitation',1000));}
function sourceUrlMatches(source:Source,claimedUrl:string):boolean {
 if(!source.url)return true; // A manually supplied source can have a reviewer-declared reference URL.
 try{const retained=new URL(source.url);return retained.protocol==='https:'&&!retained.username&&!retained.password&&retained.href===claimedUrl;}catch{return false;}
}
function stagedGovInfoSource(source:Source){return !!source.govInfo||source.kind==='legal'&&/^(?:USCODE|CFR)-\d{4}-[^/]+\/(?:USCODE|CFR)-\d{4}-[^/]+$/i.test(source.externalId||'');}
export function authorityCurrent(s:WorkspaceState,a:ActorContext,record:LegalAuthority):boolean {
 if(legalAuthorityHasPendingChange(s,record.id)||!currentEvidenceLineage(s,record)||!canRead(s,a,record)||!record.verifiedAt||!record.reviewDueAt||Date.parse(record.reviewDueAt)<=Date.now()||record.effectiveFrom&&Date.parse(record.effectiveFrom)>Date.now()||record.effectiveUntil&&Date.parse(record.effectiveUntil)<=Date.now())return false;
 const source=s.sources.find(x=>x.id===record.sourceId),reviewer=s.memberships.find(x=>x.actorId===record.reviewOwnerId);
 return !!source&&source.status==='active'&&sourceUrlMatches(source,record.sourceUrl)&&source.version===record.verifiedSourceVersion&&source.contentHash===record.verifiedSourceHash&&!!reviewer&&!reviewer.revokedAt&&reviewer.version===record.reviewMembershipVersion&&reviewer.roles.includes('legal_reviewer')&&(!reviewer.expiresAt||Date.parse(reviewer.expiresAt)>Date.now());
}
export function coverageStatus(s:WorkspaceState,a:ActorContext,c:CoverageEntry):CoverageEntry['status'] {
 if(c.status==='unsupported'||c.status==='pending_review')return c.status;
 const reviewer=s.memberships.find(x=>x.actorId===c.qualifiedReviewerId);
 if(!canRead(s,a,c)||!c.reviewDueAt||Date.parse(c.reviewDueAt)<=Date.now()||!reviewer||reviewer.revokedAt||reviewer.version!==c.reviewMembershipVersion||!reviewer.roles.includes('legal_reviewer')||(reviewer.expiresAt&&Date.parse(reviewer.expiresAt)<=Date.now())||!c.authorityIds?.length||c.authorityIds.some(id=>!s.legalAuthorities.some(x=>x.id===id&&x.version===c.authorityVersions?.[id]&&authorityCurrent(s,a,x))))return 'stale';return 'available';
}
export function coverageViews(s:WorkspaceState,a:ActorContext){return s.coverage.filter(c=>canRead(s,a,c)).map(c=>({...structuredClone(c),status:coverageStatus(s,a,c)}));}
/** A staged or registered legal source cannot enter retrieval until its exact version and coverage are both reviewed. */
export function legalSourceAnswerEligible(s:WorkspaceState,a:ActorContext,source:Source){
 const authorities=s.legalAuthorities.filter(authority=>authority.sourceId===source.id);
 if(source.kind!=='legal'&&authorities.length===0)return true;
 return authorities.some(authority=>authorityCurrent(s,a,authority)&&s.coverage.some(entry=>entry.authorityIds?.includes(authority.id)&&coverageStatus(s,a,entry)==='available'));
}
function activity(s:WorkspaceState,a:ActorContext,record:RecordBase,type:string,title:string){s.events.push({...base(s,a,record.scope,record.provenance.sourceIds),type,title,detail:'Named source/coverage maintenance. Reviewer attestation is not external certification or matter-specific legal approval.',matterId:null,recordId:record.id,measurement:a.mode==='local_demo'?'fictional_rehearsal':'observed'});}
export function applyCoverageCommand(s:WorkspaceState,a:ActorContext,c:CoverageCommand):Record<string,unknown>{
 switch(c.type){
 case 'coverage.source.add':{requireRole(s,a,'member');const source=readRecord(s,a,s.sources,c.sourceId);need(!stagedGovInfoSource(source),'SOURCE_ALREADY_REGISTERED','This GovInfo source already has an unverified authority. Review that authority instead.');need(!s.legalAuthorities.some(item=>item.sourceId===source.id&&item.domain===c.domain?.trim()&&item.jurisdiction===c.jurisdiction?.trim()),'SOURCE_ALREADY_REGISTERED','This retained source already has an authority for the same domain and jurisdiction. Review that authority instead.');need(['statute','regulation','guidance','contract','company_policy'].includes(c.authorityType),'INVALID_AUTHORITY','Choose the source authority type.');let url:URL;try{url=new URL(c.sourceUrl);}catch{throw new V2Error('INVALID_URL','Provide the exact HTTPS source URL.');}need(url.protocol==='https:'&&!url.username&&!url.password,'INVALID_URL','Provide an HTTPS source URL without embedded credentials.');need(sourceUrlMatches(source,url.href),'SOURCE_URL_MISMATCH','The registered reference URL must match the retained source URL.');const from=date(c.effectiveFrom),until=date(c.effectiveUntil);need(!from||!until||Date.parse(from)<Date.parse(until),'INVALID_EFFECTIVE_RANGE','Effective start must precede the end.');const authority:LegalAuthority={...base(s,a,source.scope,[source.id]),title:text(c.title,'source title',300),sourceUrl:url.href,jurisdiction:text(c.jurisdiction,'jurisdiction',100),domain:text(c.domain,'domain',100),authorityType:c.authorityType,publishedAt:date(c.publishedAt),effectiveFrom:from,effectiveUntil:until,verifiedAt:null,reviewOwnerId:null,sourceId:source.id};s.legalAuthorities.push(authority);activity(s,a,authority,c.type,'Legal source registered for review');return {authorityId:authority.id};}
 case 'coverage.source.verify':{const authority=readRecord(s,a,s.legalAuthorities,c.authorityId),reviewer=requireRole(s,a,'legal_reviewer',authority);version(authority,c.expectedRecordVersion);const source=readRecord(s,a,s.sources,authority.sourceId);need(currentEvidenceLineage(s,source)&&source.version===c.sourceVersion,'SOURCE_CHANGED','Review the current source revision.');need(sourceUrlMatches(source,authority.sourceUrl),'SOURCE_URL_MISMATCH','The registered reference URL must match the retained source URL.');authority.verificationEvidence=text(c.verificationEvidence,'review evidence',4000);authority.verifiedSourceVersion=source.version;authority.verifiedSourceHash=source.contentHash;authority.reviewDueAt=due(c.reviewDueAt);authority.reviewMembershipVersion=reviewer.version;authority.reviewOwnerId=a.actorId;authority.verifiedAt=timestamp();touch(authority);activity(s,a,authority,c.type,'Source review recorded');return {authorityId:authority.id,current:authorityCurrent(s,a,authority)};}
 case 'coverage.define':{requireRole(s,a,'business_owner');const domain=text(c.domain,'domain',100),jurisdiction=text(c.jurisdiction,'jurisdiction',100);need(Array.isArray(c.authorityIds)&&c.authorityIds.length>0&&c.authorityIds.length<=50,'SOURCES_REQUIRED','Select 1 to 50 registered authorities.');const authorities=[...new Set(c.authorityIds)].map(id=>readRecord(s,a,s.legalAuthorities,id));need(authorities.every(x=>x.domain===domain&&x.jurisdiction===jurisdiction),'COVERAGE_SCOPE','Sources must match the exact coverage domain and jurisdiction.');const scope=authorities[0].scope;need(authorities.every(x=>digest(x.scope)===digest(scope)),'COVERAGE_SCOPE','A coverage entry must preserve one explicit source scope.');const sourceIds=[...new Set(authorities.map(x=>x.sourceId))];const coverage:CoverageEntry={...base(s,a,scope,sourceIds),domain,jurisdiction,sourceIds,authorityIds:authorities.map(x=>x.id),ownerId:a.actorId,qualifiedReviewerId:null,status:'pending_review',reviewedAt:null,reviewDueAt:null,limitations:limitations(c.limitations)};s.coverage.push(coverage);activity(s,a,coverage,c.type,'Coverage scope awaits reviewer');return {coverageId:coverage.id};}
 case 'coverage.review':{const entry=readRecord(s,a,s.coverage,c.coverageId),reviewer=requireRole(s,a,'legal_reviewer',entry);version(entry,c.expectedRecordVersion);need(entry.authorityIds?.length&&entry.authorityIds.every(id=>s.legalAuthorities.some(x=>x.id===id&&authorityCurrent(s,a,x))),'SOURCE_REVIEW_REQUIRED','Every source must have current version-bound review before coverage is available.');entry.authorityVersions=Object.fromEntries(entry.authorityIds!.map(id=>[id,s.legalAuthorities.find(x=>x.id===id)!.version]));entry.qualificationEvidence=text(c.qualificationEvidence,'the named reviewer qualification and scope evidence',4000);entry.qualifiedReviewerId=a.actorId;entry.reviewMembershipVersion=reviewer.version;entry.qualification=a.mode==='local_demo'?'fictional_local_attestation':'named_reviewer_attestation';entry.reviewedAt=timestamp();entry.reviewDueAt=due(c.reviewDueAt);entry.limitations=limitations(c.limitations);entry.status='available';touch(entry);activity(s,a,entry,c.type,'Named coverage review recorded');return {coverageId:entry.id,status:coverageStatus(s,a,entry)};}
 case 'coverage.unavailable':{const entry=readRecord(s,a,s.coverage,c.coverageId);requireRole(s,a,'business_owner',entry);version(entry,c.expectedRecordVersion);entry.status='unsupported';entry.limitations=[...entry.limitations,text(c.reason,'unavailability reason')];touch(entry);activity(s,a,entry,c.type,'Coverage marked unavailable');return {coverageId:entry.id};}
 }
}
