import {slackAudienceEligible} from './integrations/slack-scope';
import {currentEvidenceLineage,currentSourceEvidence} from './source-lifecycle';
import {factCurrentlyConfirmed} from './fact-validity';
import {SOURCE_STRUCTURE_VERSION,structuredSourceChunks} from './source-structure';
import {documentHeads} from './document-lifecycle';
import {legalSourceAnswerEligible} from './coverage';
import {MongoClient,type Document as MongoDocument} from 'mongodb';
import {canRead,membership,readRecord,requireRole} from './authority';
import {V2Error,type ActorContext,type RecordBase,type Conversation,type WorkspaceState} from './contracts';
import {digest,readWorkspace,transactWorkspace} from './store';
import {v2DatabaseName} from './database-target';
import {EMBEDDING_POLICY,embedAuthorized,type EmbeddingProvider} from './embeddings';
import {retrieveConversationEvidence,recheckEvidence,type EvidencePacket} from './retrieval';

export interface HybridChunk {id:string;tenantId:string;entityId:string;kind:'document'|'source'|'fact';recordId:string;recordHash:string;offset:number;title:string;text:string;protocol:'kiara-atlas-chunks-1';embeddingPolicyHash:string;structureVersion:typeof SOURCE_STRUCTURE_VERSION}
export interface HybridConfig {collection:'v2_search_chunks';searchIndex:string;vectorIndex:string;embeddingPolicyHash:string;protocol:'kiara-atlas-chunks-1'}
export interface HybridAdapter {search(input:{config:HybridConfig;tenantId:string;entityId:string;chunkIds:string[];question:string;vector:number[]}):Promise<{keywordIds:string[];vectorIds:string[]}>;upsert(chunk:HybridChunk,vector:number[]):Promise<void>;ids(tenantId:string):Promise<string[]>;remove(tenantId:string,ids:string[]):Promise<void>;present(tenantId:string,ids:string[]):Promise<string[]>;removeRecords?(tenantId:string,recordIds:string[]):Promise<void>}
export function retrievalMode():'local'|'atlas'|'invalid'{const value=process.env.KIARA_V2_RETRIEVAL_MODE||'local';return value==='local'||value==='atlas'?value:'invalid';}
export function hybridConfig():HybridConfig {if(retrievalMode()!=='atlas'||!(process.env.KIARA_V2_ATLAS_URI||process.env.MONGODB_URI)||!process.env.KIARA_V2_ATLAS_SEARCH_INDEX||!process.env.KIARA_V2_ATLAS_VECTOR_INDEX)throw new V2Error('HYBRID_NOT_CONFIGURED','Atlas retrieval requires explicit mode, durable MongoDB and both configured indexes.',503);for(const value of [process.env.KIARA_V2_ATLAS_SEARCH_INDEX,process.env.KIARA_V2_ATLAS_VECTOR_INDEX])if(!/^[a-zA-Z0-9_-]{1,100}$/.test(value))throw new V2Error('HYBRID_CONFIG_INVALID','Atlas index names must be valid operator configuration.',503);return {collection:'v2_search_chunks',searchIndex:process.env.KIARA_V2_ATLAS_SEARCH_INDEX,vectorIndex:process.env.KIARA_V2_ATLAS_VECTOR_INDEX,embeddingPolicyHash:digest(EMBEDDING_POLICY),protocol:'kiara-atlas-chunks-1'};}
/** Index definitions are exposed to operator tooling, never implicitly created in a customer request. */
export function hybridIndexDefinitions(config:HybridConfig){return [{name:config.searchIndex,type:'search' as const,definition:{mappings:{dynamic:false,fields:{tenantId:{type:'token'},entityId:{type:'token'},id:{type:'token'},protocol:{type:'token'},embeddingPolicyHash:{type:'token'},title:{type:'string'},text:{type:'string'}}}}},{name:config.vectorIndex,type:'vectorSearch' as const,definition:{fields:[{type:'vector',path:'vector',numDimensions:EMBEDDING_POLICY.dimensions,similarity:'cosine'},...['tenantId','entityId','id','protocol','embeddingPolicyHash'].map(path=>({type:'filter',path}))]}}];}
export function authorizedHybridChunks(s:WorkspaceState,a:ActorContext,entityId=s.entityId,conversation?:Conversation):HybridChunk[]{
 membership(s,a);if(entityId!==s.entityId)throw new V2Error('ENTITY_SCOPE','Retrieval must use the current entity.');const result:HybridChunk[]=[];
 const add=(r:RecordBase,kind:HybridChunk['kind'],title:string,text:string)=>{if(!text.trim()||!canRead(s,a,r)||conversation&&!slackAudienceEligible(s,conversation,r)||!currentEvidenceLineage(s,r))return;const recordHash=digest(r);for(const excerpt of kind==='fact'?[{offset:0,text}]:structuredSourceChunks(text)){const chunk:Omit<HybridChunk,'id'>={tenantId:s.tenantId,entityId,kind,recordId:r.id,recordHash,offset:excerpt.offset,title,text:excerpt.text,structureVersion:SOURCE_STRUCTURE_VERSION,protocol:'kiara-atlas-chunks-1' as const,embeddingPolicyHash:digest(EMBEDDING_POLICY)};result.push({id:digest(chunk),...chunk});}};
 const docs=documentHeads(s.documents).filter(d=>d.status!=='superseded'&&canRead(s,a,d)&&s.sources.some(x=>x.id===d.sourceId&&currentSourceEvidence(s,x)&&legalSourceAnswerEligible(s,a,x)));for(const d of docs)add(d,'document',d.title,d.body);
 for(const source of s.sources.filter(x=>x.status==='active'&&!s.documents.some(d=>d.sourceId===x.id)&&legalSourceAnswerEligible(s,a,x)))add(source,'source',source.title,source.text);
 for(const fact of s.facts.filter(f=>factCurrentlyConfirmed(f)&&f.reuse==='company'&&f.entityId===entityId))add(fact,'fact',fact.predicate,JSON.stringify({predicate:fact.predicate,value:fact.value,practice:fact.practice,confirmedAt:fact.confirmedAt}));
 if(result.length>10000)throw new V2Error('HYBRID_SCOPE_TOO_LARGE','Narrow the selected workspace scope before retrieving more than 10,000 authorized chunks.');return result;
}
/** Every search branch is prefiltered, and projections contain IDs only, never indexed text. */
export function hybridPipelines(input:Parameters<HybridAdapter['search']>[0]){
 const {config,tenantId,entityId,chunkIds,question,vector}=input;if(!chunkIds.length)throw new V2Error('HYBRID_SCOPE_EMPTY','No authorized indexed records are available.');
 const fields={tenantId,entityId,protocol:config.protocol,embeddingPolicyHash:config.embeddingPolicyHash};
 const keyword:MongoDocument[]=[{$search:{index:config.searchIndex,compound:{filter:[...Object.entries(fields).map(([path,value])=>({equals:{path,value}})),{in:{path:'id',value:chunkIds}}],must:[{text:{query:question,path:['title','text']}}]}}},{$limit:80},{$project:{_id:0,id:1}}];
 const semantic:MongoDocument[]=[{$vectorSearch:{index:config.vectorIndex,path:'vector',queryVector:vector,numCandidates:400,limit:80,filter:{...fields,id:{$in:chunkIds}}}},{$project:{_id:0,id:1}}];return {keyword,semantic};
}
/** RRF ranks start at one. Duplicate IDs within one branch count only once. */
export function reciprocalRankFusion(branches:string[][],limit=16){const scores=new Map<string,number>();for(const branch of branches)for(const [index,id] of [...new Set(branch)].entries())scores.set(id,(scores.get(id)||0)+1/(60+index+1));return [...scores].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).slice(0,limit).map(([id,score])=>({id,score}));}
let client:MongoClient|undefined,clientUri:string|undefined;
async function collection(){const uri=process.env.KIARA_V2_ATLAS_URI||process.env.MONGODB_URI;if(!uri)throw new V2Error('HYBRID_NOT_CONFIGURED','The Atlas data connection is unavailable.',503);const target=v2DatabaseName();if(client&&clientUri!==uri)throw new V2Error('HYBRID_CONFIG_CHANGED','Restart the index adapter after configuration changes.');if(!client){clientUri=uri;client=new MongoClient(uri,{maxPoolSize:4,serverSelectionTimeoutMS:5000,socketTimeoutMS:15000});await client.connect();}return client.db(target).collection<HybridChunk&{_id:string;vector:number[]}>('v2_search_chunks');}
export async function closeHybridIndex(){await client?.close();client=undefined;clientUri=undefined;}
export function mongoHybridAdapter():HybridAdapter {return {
 async search(input){const c=await collection(),pipelines=hybridPipelines(input);try{const [keyword,vector]=await Promise.all([c.aggregate<{id:string}>(pipelines.keyword,{maxTimeMS:10000}).toArray(),c.aggregate<{id:string}>(pipelines.semantic,{maxTimeMS:10000}).toArray()]);return {keywordIds:keyword.map(x=>x.id),vectorIds:vector.map(x=>x.id)};}catch{throw new V2Error('HYBRID_INDEX_UNAVAILABLE','Atlas full-text or vector search is unavailable. No keyword fallback was substituted.',503);}},
 async upsert(chunk,vector){const c=await collection(),session=client!.startSession(),fences=client!.db(v2DatabaseName()).collection<{_id:string;tenantId:string;recordId:string;deleted:boolean;epoch:number}>('v2_search_record_fences');try{await session.withTransaction(async()=>{const id=digest({tenantId:chunk.tenantId,recordId:chunk.recordId}),fence=await fences.findOne({_id:id},{session});if(fence?.deleted)throw new V2Error('INDEX_RECORD_DELETED','Deleted record identities cannot be indexed again.');await fences.updateOne({_id:id,deleted:{$ne:true}},{$setOnInsert:{tenantId:chunk.tenantId,recordId:chunk.recordId,deleted:false},$inc:{epoch:1}},{upsert:true,session});await c.updateOne({_id:chunk.id,tenantId:chunk.tenantId},{$setOnInsert:{...chunk,vector}},{upsert:true,session});const saved=await c.findOne({_id:chunk.id,tenantId:chunk.tenantId},{session});if(!saved||digest({...saved,_id:undefined,vector:undefined})!==digest({...chunk,_id:undefined,vector:undefined})||digest(saved.vector)!==digest(vector))throw new V2Error('HYBRID_INDEX_CONFLICT','Immutable index content differs from the retained chunk.');},{readConcern:{level:'snapshot'},writeConcern:{w:'majority'},maxCommitTimeMS:15000});}finally{await session.endSession();}},
 async ids(tenantId){return (await(await collection()).find({tenantId},{projection:{_id:0,id:1},limit:100001}).toArray()).map(x=>x.id);},
 async remove(tenantId,ids){if(ids.length)await(await collection()).deleteMany({tenantId,id:{$in:ids}},{writeConcern:{w:'majority'}});},
 async removeRecords(tenantId,recordIds){if(!recordIds.length)return;const c=await collection(),session=client!.startSession(),fences=client!.db(v2DatabaseName()).collection<{_id:string;tenantId:string;recordId:string;deleted:boolean;epoch:number}>('v2_search_record_fences');try{await session.withTransaction(async()=>{for(const recordId of recordIds)await fences.updateOne({_id:digest({tenantId,recordId})},{$set:{tenantId,recordId,deleted:true},$inc:{epoch:1}},{upsert:true,session});await c.deleteMany({tenantId,recordId:{$in:recordIds}},{session});},{readConcern:{level:'snapshot'},writeConcern:{w:'majority'},maxCommitTimeMS:15000});}finally{await session.endSession();}},
 async present(tenantId,ids){if(!ids.length)return [];return (await(await collection()).find({tenantId,id:{$in:ids}},{projection:{_id:0,id:1}}).toArray()).map(x=>x.id);}
 };}
/** Explicit scoped operator action; indexing is not triggered by a model or a customer question. */
export async function syncHybridIndex(a:ActorContext,recordIds:string[],options:{adapter?:HybridAdapter;provider?:EmbeddingProvider;authorityCheck?:(state:WorkspaceState)=>void;chunkIds?:string[]}={}){
 const config=hybridConfig(),state=await readWorkspace(a.tenantId);if(options.authorityCheck)options.authorityCheck(state);else requireRole(state,a,'admin');if(!recordIds.length||recordIds.length>20||new Set(recordIds).size!==recordIds.length)throw new V2Error('INDEX_SELECTION_REQUIRED','Select 1–20 exact authorized source, document or fact records.');
 const selected=authorizedHybridChunks(state,a).filter(c=>recordIds.includes(c.recordId)&&(!options.chunkIds||options.chunkIds.includes(c.id)));if(recordIds.some(id=>!selected.some(c=>c.recordId===id))||selected.length>200)throw new V2Error('INDEX_SELECTION_SCOPE','Selected records must be current, authorized and contain at most 200 chunks.');const adapter=options.adapter||mongoHybridAdapter();
 let indexed=0;for(const chunk of selected){const authorize=(s:WorkspaceState)=>{if(options.authorityCheck)options.authorityCheck(s);else requireRole(s,a,'admin');if(digest(hybridConfig())!==digest(config)||!authorizedHybridChunks(s,a).some(c=>c.id===chunk.id))throw new V2Error('INDEX_SOURCE_CHANGED','Selected index authority or source changed.');};const vector=await embedAuthorized(a,`index:${digest({actor:a.actorId,chunk:chunk.id})}`,chunk.text,digest({config,chunk:chunk.id}),authorize,{provider:options.provider,evidenceIds:[chunk.recordId]});authorize(await readWorkspace(a.tenantId));const receiptKey=`index-sync:${chunk.id}`;await transactWorkspace(a.tenantId,s=>{authorize(s);s.receipts[receiptKey]={hash:digest({chunkId:chunk.id,recordId:chunk.recordId}),result:{status:'pending',chunkId:chunk.id,recordId:chunk.recordId,actorId:a.actorId}};});try{await adapter.upsert(chunk,vector);await transactWorkspace(a.tenantId,s=>{authorize(s);s.receipts[receiptKey].result.status='complete';});}catch(error){await adapter.remove(a.tenantId,[chunk.id]);await transactWorkspace(a.tenantId,s=>{s.receipts[receiptKey].result.status='blocked';});throw error;}indexed++;}return {indexed,recordIds,configHash:digest(config),liveVerified:false};
}
/** Physical removal follows authoritative tombstones; inaccessible active private content is retained. */
export async function reconcileHybridIndex(a:ActorContext,options:{adapter?:HybridAdapter}={}){const state=await readWorkspace(a.tenantId);requireRole(state,a,'admin');const adapter=options.adapter||mongoHybridAdapter(),ids=await adapter.ids(a.tenantId);if(ids.length>100000)throw new V2Error('INDEX_RECONCILIATION_LIMIT','Use a bounded operator index migration for this corpus.');const allCurrent=new Set<string>();for(const member of state.memberships.filter(m=>!m.revokedAt)){const actor:ActorContext={tenantId:state.tenantId,actorId:member.actorId,mode:'authenticated',expiresAt:Date.now()+10000};try{for(const c of authorizedHybridChunks(state,actor))allCurrent.add(c.id);}catch{/* Expired memberships have no eligible index rows. */}}const removed=ids.filter(id=>!allCurrent.has(id));requireRole(await readWorkspace(a.tenantId),a,'admin');await adapter.remove(a.tenantId,removed);return {removed:removed.length};}
/** Retention-worker hook. The source-deletion transaction owns the exact affected record manifest. */
export async function purgeHybridRecords(tenantId:string,deletionId:string,recordIds:string[],options:{adapter?:HybridAdapter}={}){
 const key=`hybrid-purge:${digest({deletionId,recordIds:[...new Set(recordIds)].sort()})}`;
 const claim=await transactWorkspace(tenantId,s=>{if(!s.tombstones.length)throw new V2Error('DELETION_REQUIRED','Commit source deletion before purging derived indexes.');const old=s.receipts[key]?.result;if(old?.status==='complete')return false;s.receipts[key]={hash:digest({deletionId,recordIds}),result:{status:'pending',deletionId,recordIds:[...new Set(recordIds)],externalBackupErasureVerified:false}};return true;});
 if(!claim.result)return {status:'complete' as const,replayed:true,externalBackupErasureVerified:false};
 const adapter=options.adapter||mongoHybridAdapter();if(!adapter.removeRecords)throw new V2Error('INDEX_PURGE_UNAVAILABLE','The configured index adapter cannot erase exact record revisions.',503);await adapter.removeRecords(tenantId,[...new Set(recordIds)]);
 await transactWorkspace(tenantId,s=>{s.receipts[key].result.status='complete';});return {status:'complete' as const,replayed:false,externalBackupErasureVerified:false};
}
export async function retrieveHybridEvidence(a:ActorContext,conversationId:string,userMessageId:string,ownerKey:string,options:{adapter?:HybridAdapter;provider?:EmbeddingProvider;authorize?:(state:WorkspaceState)=>void}={}):Promise<EvidencePacket>{
 const config=hybridConfig(),state=await readWorkspace(a.tenantId),conversation=readRecord(state,a,state.conversations,conversationId),base=retrieveConversationEvidence(state,a,conversation,userMessageId),chunks=authorizedHybridChunks(state,a,conversation.entityId,conversation),ids=chunks.map(c=>c.id),adapter=options.adapter||mongoHybridAdapter();
 options.authorize?.(state);const authorize=(s:WorkspaceState)=>{options.authorize?.(s);recheckEvidence(s,a,conversationId,base);if(digest(hybridConfig())!==digest(config)||digest(authorizedHybridChunks(s,a,conversation.entityId,readRecord(s,a,s.conversations,conversationId)).map(c=>c.id))!==digest(ids))throw new V2Error('HYBRID_AUTHORITY_CHANGED','Search eligibility or configuration changed.');};
 if(!chunks.length)return {...base,version:'v2-atlas-hybrid-1',evidence:[],limitations:[...base.limitations.filter(x=>!x.startsWith('Exact and keyword')),'Atlas mode selected; no authorized records are available to search.']};
 const indexed=await adapter.present(a.tenantId,ids);authorize(await readWorkspace(a.tenantId));if(indexed.length!==ids.length||ids.some(id=>!indexed.includes(id)))throw new V2Error('HYBRID_INDEX_STALE','Authorized source revisions are not fully indexed. Run scoped index synchronization before asking in Atlas mode.',503);
 const vector=await embedAuthorized(a,`query:${ownerKey}`,base.question,digest({config,ids,conversationId,userMessageId}),authorize,{provider:options.provider,evidenceIds:[...chunks.map(c=>c.recordId),...base.references.map(r=>r.id)]});authorize(await readWorkspace(a.tenantId));
 const result=await adapter.search({config,tenantId:a.tenantId,entityId:conversation.entityId,chunkIds:ids,question:base.question,vector});const current=await readWorkspace(a.tenantId);authorize(current);
 const allow=new Set(ids);if([...result.keywordIds,...result.vectorIds].some(id=>!allow.has(id)))throw new V2Error('HYBRID_RESULT_SCOPE','The search index returned an ineligible record.');
 const literal=base.question.trim().toLowerCase(),exact=chunks.filter(c=>literal.length>2&&(c.title.toLowerCase().includes(literal)||c.text.toLowerCase().includes(literal))).map(c=>c.id);
 const selected=reciprocalRankFusion([exact,result.keywordIds,result.vectorIds]).map(r=>chunks.find(c=>c.id===r.id)!);
 return retrieveConversationEvidence(current,a,readRecord(current,a,current.conversations,conversationId),userMessageId,{chunks:selected.map(c=>({kind:c.kind,id:c.recordId,offset:c.offset})),hybrid:true});
}
