import {randomUUID} from 'node:crypto';
import {membership} from './authority';
import {V2Error,type ActorContext,type WorkspaceState} from './contracts';
import {authorizedHybridChunks,hybridConfig,retrievalMode,syncHybridIndex,type HybridAdapter} from './hybrid';
import {reconcilePendingEmbeddings,type EmbeddingProvider} from './embeddings';
import {digest,readWorkspace,timestamp,transactWorkspace} from './store';
interface IndexPolicy {tenantId:string;enabled:boolean;actorIds:string[];scopeKinds:('private'|'team'|'matter')[];maxChunksPerJob:number;validUntil:string}
export interface IndexJobView {id:string;status:'queued'|'running'|'complete'|'blocked'|'unknown';recordCount:number;chunkCount:number;reason:string|null;nextAttemptAt:string|null;updatedAt:string}
interface IndexJob extends IndexJobView {actorId:string;membershipVersion:number;policyHash:string;configHash:string;recordIds:string[];chunkIds:string[];leaseToken:string|null;leaseUntil:number|null;createdAt:string}
const PREFIX='index-maintenance:',LEASE=300000;
function policy(tenantId:string):IndexPolicy|null {const raw=process.env.KIARA_V2_INDEX_POLICY;if(!raw)return null;if(raw.length>65536)throw new V2Error('INDEX_POLICY_INVALID','Index policy exceeds its configured bound.');let values:unknown;try{values=JSON.parse(raw);}catch{throw new V2Error('INDEX_POLICY_INVALID','Index maintenance requires valid protected operator policy.');}if(!Array.isArray(values))throw new V2Error('INDEX_POLICY_INVALID','Index policy must be a tenant policy list.');const matches=values.filter(p=>p?.tenantId===tenantId);if(matches.length>1)throw new V2Error('INDEX_POLICY_INVALID','Each tenant needs one index maintenance policy.');const p=matches[0] as IndexPolicy|undefined;if(!p)return null;if(Object.keys(p).some(k=>!['tenantId','enabled','actorIds','scopeKinds','maxChunksPerJob','validUntil'].includes(k))||typeof p.enabled!=='boolean'||!Array.isArray(p.actorIds)||!p.actorIds.length||p.actorIds.length>100||p.actorIds.some(id=>typeof id!=='string'||!id||id.length>200)||!Array.isArray(p.scopeKinds)||!p.scopeKinds.length||p.scopeKinds.some(k=>!['private','team','matter'].includes(k))||!Number.isInteger(p.maxChunksPerJob)||p.maxChunksPerJob<1||p.maxChunksPerJob>100||!Number.isFinite(Date.parse(p.validUntil)))throw new V2Error('INDEX_POLICY_INVALID','Index maintenance policy fields are invalid.');return p;}
export function indexMaintenancePolicyStatus(tenantId:string){try{const p=policy(tenantId);return {enabled:!!p?.enabled&&Date.parse(p.validUntil)>Date.now(),expiresAt:p?.validUntil||null,reason:null};}catch{return {enabled:false,expiresAt:null,reason:'INDEX_POLICY_INVALID'};}}
function get(s:WorkspaceState,id:string){const j=s.receipts[PREFIX+id]?.result.job as IndexJob|undefined;if(!j||j.id!==id)throw new V2Error('INDEX_JOB_NOT_FOUND','The index maintenance job is unavailable.');return j;}
function view(j:IndexJob):IndexJobView{return {id:j.id,status:j.status,recordCount:j.recordCount,chunkCount:j.chunkCount,reason:j.reason,nextAttemptAt:j.nextAttemptAt,updatedAt:j.updatedAt};}
export function indexingViews(s:WorkspaceState,a:ActorContext){membership(s,a);return Object.entries(s.receipts).filter(([key])=>key.startsWith(PREFIX)).map(([,r])=>r.result.job as IndexJob).filter(j=>j.actorId===a.actorId).slice(-100).map(view);}
export function indexRecordFingerprints(s:WorkspaceState){return new Map([...s.documents,...s.sources,...s.facts].map(r=>[r.id,digest(r)]));}
/** Accepts maintenance only under explicit operator standing policy, within the initiating actor's ACL. */
export function enqueueIndexMaintenance(s:WorkspaceState,a:ActorContext,before:Map<string,string>,commandId:string){
 const changed=[...s.documents,...s.sources,...s.facts].filter(r=>before.get(r.id)!==digest(r));if(!changed.length||retrievalMode()!=='atlas')return;
 try{const p=policy(s.tenantId);if(!p?.enabled||Date.parse(p.validUntil)<=Date.now()||!p.actorIds.includes(a.actorId)||retrievalMode()!=='atlas')return;
 const member=membership(s,a),config=hybridConfig(),records=new Map([...s.documents,...s.sources,...s.facts].map(r=>[r.id,r]));const chunks=authorizedHybridChunks(s,a).filter(c=>{const r=records.get(c.recordId)!;return p.scopeKinds.includes(r.scope.kind)&&before.get(c.recordId)!==digest(r);});
 for(let start=0;start<chunks.length;){const selected:typeof chunks=[],ids=new Set<string>();while(start<chunks.length&&selected.length<p.maxChunksPerJob){const chunk=chunks[start];if(!ids.has(chunk.recordId)&&ids.size===20)break;selected.push(chunk);ids.add(chunk.recordId);start++;}const chunkIds=selected.map(c=>c.id),policyHash=digest(p),configHash=digest(config),id=digest({actorId:a.actorId,policyHash,configHash,chunkIds});if(s.receipts[PREFIX+id])continue;const job:IndexJob={id,status:'queued',actorId:a.actorId,membershipVersion:member.version,policyHash,configHash,recordIds:[...ids],chunkIds,recordCount:ids.size,chunkCount:chunkIds.length,reason:null,nextAttemptAt:null,leaseToken:null,leaseUntil:null,createdAt:timestamp(),updatedAt:timestamp()};s.receipts[PREFIX+id]={hash:digest({id,actorId:a.actorId,policyHash,configHash,chunkIds}),result:{job}};s.outbox.push({id:randomUUID(),tenantId:s.tenantId,kind:'index_maintenance',aggregateId:id,commandId,status:'pending',owner:'v2',createdAt:timestamp()});}
 }catch(error){
  // Background admission failure must never roll back primary source or membership control.
  const reason=error instanceof V2Error?error.code:'INDEX_ADMISSION_FAILED',id=digest({actorId:a.actorId,commandId,reason,records:changed.map(r=>[r.id,digest(r)])});
  const j:IndexJob={id,status:'blocked',actorId:a.actorId,membershipVersion:s.memberships.find(m=>m.actorId===a.actorId)?.version||0,policyHash:digest(null),configHash:digest(null),recordIds:changed.map(r=>r.id),chunkIds:[],recordCount:changed.length,chunkCount:0,reason,nextAttemptAt:null,leaseToken:null,leaseUntil:null,createdAt:timestamp(),updatedAt:timestamp()};s.receipts[PREFIX+id]={hash:digest({id}),result:{job:j}};
 }
}
function assertGrant(s:WorkspaceState,j:IndexJob,token:string):ActorContext {const p=policy(s.tenantId);if(!p?.enabled||Date.parse(p.validUntil)<=Date.now()||!p.actorIds.includes(j.actorId)||digest(p)!==j.policyHash||digest(hybridConfig())!==j.configHash)throw new V2Error('INDEX_GRANT_CHANGED','The operator standing index grant expired or changed.');if(j.status!=='running'||j.leaseToken!==token||!j.leaseUntil||j.leaseUntil<=Date.now())throw new V2Error('INDEX_LEASE_EXPIRED','The maintenance lease expired.');const a:ActorContext={tenantId:s.tenantId,actorId:j.actorId,mode:'authenticated',expiresAt:Math.min(j.leaseUntil,Date.parse(p.validUntil))};if(membership(s,a).version!==j.membershipVersion)throw new V2Error('INDEX_MEMBERSHIP_CHANGED','The initiating member authority changed.');const chunks=authorizedHybridChunks(s,a);if(j.chunkIds.some(id=>!chunks.some(c=>c.id===id)))throw new V2Error('INDEX_EVIDENCE_CHANGED','A selected source revision or its access changed.');return a;}
/** Refs-only worker entry. No model or caller can choose a new role, identity or expanded scope. */
export async function processIndexJob(tenantId:string,jobId:string,options:{provider?:EmbeddingProvider;adapter?:HybridAdapter}={}):Promise<IndexJobView>{
 await reconcilePendingEmbeddings(tenantId);const token=randomUUID();const claim=await transactWorkspace(tenantId,s=>{const j=get(s,jobId);if(j.status==='running'&&j.leaseUntil&&j.leaseUntil>Date.now()||j.status==='complete'||j.status==='blocked'||j.status==='unknown'||j.nextAttemptAt&&Date.parse(j.nextAttemptAt)>Date.now())return {claimed:false,job:view(j)};j.status='running';j.leaseToken=token;j.leaseUntil=Date.now()+LEASE;j.nextAttemptAt=null;j.updatedAt=timestamp();return {claimed:true,job:view(j)};});if(!claim.result.claimed)return claim.result.job;
 try{const s=await readWorkspace(tenantId),j=get(s,jobId),a=assertGrant(s,j,token);await syncHybridIndex(a,j.recordIds,{provider:options.provider,adapter:options.adapter,chunkIds:j.chunkIds,authorityCheck:state=>{assertGrant(state,get(state,jobId),token);}});return (await transactWorkspace(tenantId,state=>{const current=get(state,jobId);assertGrant(state,current,token);current.status='complete';current.reason=null;current.leaseToken=null;current.leaseUntil=null;current.updatedAt=timestamp();return view(current);})).result;}catch(error){const reason=error instanceof V2Error?error.code:typeof error==='object'&&error&&'code'in error?String(error.code):'INDEX_MAINTENANCE_FAILED';return (await transactWorkspace(tenantId,s=>{const j=get(s,jobId);if(j.leaseToken!==token)return view(j);const embeddings=j.chunkIds.map(chunk=>s.receipts['embedding:index:'+digest({actor:j.actorId,chunk})]?.result.job as {status:string;recoveryPending:boolean;leaseUntil:number}|undefined).filter(x=>!!x);const unsettled=embeddings.some(x=>x.recoveryPending||['prepared','dispatched'].includes(x.status));j.status=unsettled||['GLOBAL_RATE_LIMIT','GLOBAL_CONCURRENCY_LIMIT','STORE_BUSY'].includes(reason)?'queued':embeddings.some(x=>x.status==='unknown')||reason.includes('UNKNOWN')?'unknown':'blocked';j.reason=reason;j.nextAttemptAt=j.status==='queued'?new Date(Date.now()+60000).toISOString():null;j.leaseToken=null;j.leaseUntil=null;j.updatedAt=timestamp();return view(j);})).result;}
}
