import {randomUUID} from 'node:crypto';
import {canRead,membership,readRecord,requireRole} from './authority';
import {documentHeads} from './document-lifecycle';
import {V2Error,type ActorContext,type Matter,type Proposal,type RecordBase,type WorkspaceState} from './contracts';
import {digest,timestamp} from './store';
export interface AgreementInventory extends RecordBase {matterId:string;title:string;scopeDescription:string;documentIds:string[];documentHashes:Record<string,string>;registerHash:string;sourceVersions:Record<string,number>;ownerId:string;membershipVersion:number;validUntil:string;status:'active'|'revoked';attestation:'named_owner_supplied_register';revocationReason:string|null}
export interface InventoryView extends AgreementInventory {current:boolean;count:number}
export interface InventoryCandidate {matterId:string;documentIds:string[];count:number;available:boolean}
export type InventoryCommand={type:'inventory.attest';matterId:string;expectedMatterVersion:number;title:string;scopeDescription:string;documentIds:string[];sourceIds:string[];validUntil:string}|{type:'inventory.revoke';inventoryId:string;expectedRecordVersion:number;reason:string};
export const inventoryCommandFields:Record<InventoryCommand['type'],string[]>={'inventory.attest':['matterId','expectedMatterVersion','title','scopeDescription','documentIds','sourceIds','validUntil'],'inventory.revoke':['inventoryId','expectedRecordVersion','reason']};
const ensure=(v:unknown,code:string,message:string)=>{if(!v)throw new V2Error(code,message);};
function text(value:unknown,name:string,max:number){ensure(typeof value==='string'&&value.trim().length>0&&value.length<=max,'INVALID_INPUT',`Provide ${name} within ${max} characters.`);return (value as string).trim();}
const audience=(scope:RecordBase['scope'])=>digest({kind:scope.kind,actorIds:[...scope.actorIds].sort(),matterId:scope.matterId||null});
function activity(s:WorkspaceState,a:ActorContext,i:AgreementInventory,type:string){s.events.push({id:randomUUID(),tenantId:s.tenantId,version:1,createdAt:timestamp(),updatedAt:timestamp(),scope:structuredClone(i.scope),provenance:structuredClone(i.provenance),type,title:type==='inventory.attest'?'Supplied agreement register attested':'Inventory attestation revoked',detail:type==='inventory.attest'?`${i.documentIds.length} current agreement/amendment heads; named human attestation expires ${i.validUntil}.`:i.revocationReason||'Owner revoked completeness attestation.',matterId:i.matterId,recordId:i.id,measurement:s.rehearsal?'fictional_rehearsal':'observed'});}
/** Full register enumeration precedes ACL checks. An inaccessible current head never revives an old revision. */
function register(s:WorkspaceState,m:Matter){return documentHeads(s.documents).filter(d=>(d.kind==='agreement'||!!d.amendsDocumentId)&&audience(d.scope)===audience(m.scope)).sort((a,b)=>a.id.localeCompare(b.id));}
function registerHash(s:WorkspaceState,m:Matter){return digest(register(s,m).map(d=>({id:d.id,hash:d.contentHash,authority:d.authority,sourceId:d.sourceId,sourceVersion:s.sources.find(x=>x.id===d.sourceId)?.version||null})));}
export function inventoryCandidates(s:WorkspaceState,a:ActorContext):InventoryCandidate[]{membership(s,a);return s.matters.filter(m=>canRead(s,a,m)).map(m=>{const docs=register(s,m),available=docs.every(d=>canRead(s,a,d));return {matterId:m.id,documentIds:available?docs.map(d=>d.id):[],count:available?docs.length:0,available};});}
export function inventoryCurrent(s:WorkspaceState,i:AgreementInventory):boolean {try{const m=s.matters.find(x=>x.id===i.matterId);if(!m||i.status!=='active'||Date.parse(i.validUntil)<=Date.now()||!Number.isFinite(Date.parse(i.validUntil))||audience(i.scope)!==audience(m.scope)||registerHash(s,m)!==i.registerHash)return false;const a:ActorContext={tenantId:s.tenantId,actorId:i.ownerId,mode:'authenticated',expiresAt:Date.now()+10000};const member=requireRole(s,a,'fact_owner',m);return member.version===i.membershipVersion&&canRead(s,a,i)&&register(s,m).every(d=>canRead(s,a,d)&&i.documentHashes[d.id]===d.contentHash)&&Object.entries(i.sourceVersions).every(([id,v])=>s.sources.some(source=>source.id===id&&source.version===v&&canRead(s,a,source)));}catch{return false;}}
export function inventoryViews(s:WorkspaceState,a:ActorContext):InventoryView[]{return (s.inventories||[]).filter(i=>canRead(s,a,i)).map(i=>({...i,current:inventoryCurrent(s,i),count:i.documentIds.length}));}
export function currentInventory(s:WorkspaceState,a:ActorContext,m:Matter){return [...s.inventories||[]].reverse().find(i=>i.matterId===m.id&&canRead(s,a,i)&&inventoryCurrent(s,i));}
export function inventoryBinding(i:AgreementInventory){return {id:i.id,hash:digest(i),count:i.documentIds.length,scopeDescription:i.scopeDescription};}
export function assertProposalInventory(s:WorkspaceState,p:Proposal){if(!p.inventoryComplete)return;const i=s.inventories?.find(x=>x.id===p.inventory?.id);ensure(i&&p.inventory&&digest(i)===p.inventory.hash&&inventoryCurrent(s,i),'INVENTORY_CHANGED','The named inventory attestation expired or its owner, scope or agreement register changed. Prepare and review a current packet.');}
export function applyInventoryCommand(s:WorkspaceState,a:ActorContext,c:InventoryCommand):Record<string,unknown>{
 if(c.type==='inventory.revoke'){const i=readRecord(s,a,s.inventories||[],c.inventoryId);requireRole(s,a,'fact_owner',i);ensure(i.version===c.expectedRecordVersion,'VERSION_CONFLICT','Inspect the current inventory.');i.status='revoked';i.revocationReason=text(c.reason,'a revocation reason',2000);i.version++;i.updatedAt=timestamp();activity(s,a,i,c.type);return {inventoryId:i.id};}
 const m=readRecord(s,a,s.matters,c.matterId),member=requireRole(s,a,'fact_owner',m);ensure(m.version===c.expectedMatterVersion,'VERSION_CONFLICT','Inspect the current matter before attesting its agreement register.');ensure(!['closed','canceled'].includes(m.state),'MATTER_TERMINAL','A terminal matter cannot receive a new inventory decision.');
 const docs=register(s,m);ensure(docs.length<=100,'INVENTORY_LIMIT','This bounded attestation supports at most 100 agreement heads.');ensure(Array.isArray(c.documentIds)&&new Set(c.documentIds).size===c.documentIds.length&&digest([...c.documentIds].sort())===digest(docs.map(d=>d.id)),'INVENTORY_SET_CHANGED','Enumerate every current agreement and amendment head in the matter audience; no search subset is sufficient.');ensure(docs.every(d=>canRead(s,a,d)),'INVENTORY_SCOPE','Every current head in this register must be readable by the attesting owner.');ensure(Array.isArray(c.sourceIds)&&c.sourceIds.length>0&&c.sourceIds.length<=100,'INVENTORY_BASIS_REQUIRED','Retain at least one source supporting the named owner’s completeness attestation.');const sources=[...new Set([...docs.map(d=>d.sourceId),...c.sourceIds])].map(id=>readRecord(s,a,s.sources,id));ensure(Number.isFinite(Date.parse(c.validUntil))&&Date.parse(c.validUntil)>Date.now()&&Date.parse(c.validUntil)<=Date.now()+30*86400000,'INVALID_EXPIRY','Inventory attestations expire within 30 days.');
 const i:AgreementInventory={id:randomUUID(),tenantId:s.tenantId,version:1,createdAt:timestamp(),updatedAt:timestamp(),scope:structuredClone(m.scope),provenance:{actorId:a.actorId,sourceIds:sources.map(x=>x.id),description:'Named fact-owner attestation of the supplied agreement register; no external discovery or legal applicability certified.'},matterId:m.id,title:text(c.title,'an inventory title',300),scopeDescription:text(c.scopeDescription,'the exact customer/business population and completeness basis',4000),documentIds:docs.map(d=>d.id),documentHashes:Object.fromEntries(docs.map(d=>[d.id,d.contentHash])),registerHash:registerHash(s,m),sourceVersions:Object.fromEntries(sources.map(x=>[x.id,x.version])),ownerId:a.actorId,membershipVersion:member.version,validUntil:new Date(c.validUntil).toISOString(),status:'active',attestation:'named_owner_supplied_register',revocationReason:null};(s.inventories||=[]).push(i);activity(s,a,i,c.type);return {inventoryId:i.id,count:i.documentIds.length};
}
