import {createHash,randomUUID} from 'node:crypto';
import {isIP} from 'node:net';
import {lookup} from 'node:dns/promises';
import {request as httpsRequest} from 'node:https';
import {canRead,readRecord,requireRole} from './authority';
import {retainIntakeOriginal} from './artifact-intake';
import {assertOriginalNotDeleted} from './retention';
import {indexRecordFingerprints,enqueueIndexMaintenance} from './index-maintenance';
import {digest,readWorkspace,timestamp,transactWorkspace} from './store';
import {V2Error,type ActorContext,type RecordBase,type Source,type WorkspaceState} from './contracts';

export interface LegalSourceWatch extends RecordBase {authorityId:string;ownerId:string;membershipVersion:number;sourceUrl:string;policyHash:string;intervalHours:number;active:boolean;nextCheckAt:string;lastCheckedAt:string|null;lastObservedHash:string|null;lastObservedWorkspaceVersion?:number;status:'scheduled'|'checking'|'review_required'|'blocked'|'stopped';failureCode:string|null;leaseToken:string|null;leaseUntil:string|null}
export interface LegalSourceChange extends RecordBase {watchId:string;authorityId:string;oldSourceId:string;newSourceId:string;oldHash:string;newHash:string;rawHash:string;status:'pending_review'|'assessed';assessment:null|{actorId:string;membershipVersion:number;decision:'no_applicability_change'|'affected_work';reason:string;matterIds:string[];learningIds:string[];adoptedSource:boolean;assessedAt:string}}
export interface LegalMaintenanceView {watches:LegalWatchView[];changes:LegalSourceChange[];availability:{authorityId:string;configured:boolean;reason:string|null}[]}
export interface LegalWatchView extends Omit<LegalSourceWatch,'leaseToken'|'leaseUntil'|'policyHash'|'membershipVersion'|'lastObservedWorkspaceVersion'> {overdue:boolean}
type State=WorkspaceState&{legalWatches?:LegalSourceWatch[];legalChanges?:LegalSourceChange[]};
export type LegalMaintenanceCommand=
 |{type:'legal.watch.configure';authorityId:string;expectedAuthorityVersion:number;intervalHours:number}
 |{type:'legal.watch.stop';watchId:string;expectedRecordVersion:number}
 |{type:'legal.change.assess';changeId:string;expectedRecordVersion:number;oldHash:string;newHash:string;decision:'no_applicability_change'|'affected_work';reason:string;matterIds:string[];learningIds:string[];adoptSource:boolean};
export const legalMaintenanceCommandFields:Record<LegalMaintenanceCommand['type'],string[]>={'legal.watch.configure':['authorityId','expectedAuthorityVersion','intervalHours'],'legal.watch.stop':['watchId','expectedRecordVersion'],'legal.change.assess':['changeId','expectedRecordVersion','oldHash','newHash','decision','reason','matterIds','learningIds','adoptSource']};
interface ReadPolicy {tenantId:string;urls:string[];validUntil:string;maxBytes:number}
const ensure=(v:unknown,code:string,message:string)=>{if(!v)throw new V2Error(code,message);};
function sameScope(a:RecordBase,b:RecordBase){return digest({...a.scope,actorIds:[...a.scope.actorIds].sort()})===digest({...b.scope,actorIds:[...b.scope.actorIds].sort()});}
function base(s:State,a:ActorContext,record:RecordBase,sources=record.provenance.sourceIds):RecordBase{return {id:randomUUID(),tenantId:s.tenantId,version:1,createdAt:timestamp(),updatedAt:timestamp(),scope:structuredClone(record.scope),provenance:{actorId:a.actorId,sourceIds:[...new Set(sources)],description:'Observed source maintenance and attributed applicability review; no automatic legal conclusion.'}};}
function touch(r:RecordBase){r.version++;r.updatedAt=timestamp();}
function actor(s:State,w:LegalSourceWatch):ActorContext{return {tenantId:s.tenantId,actorId:w.ownerId,mode:'authenticated',expiresAt:Date.now()+60000};}
function readPolicy(tenantId:string,url:string):ReadPolicy{
 let entries:ReadPolicy[];try{entries=JSON.parse(process.env.KIARA_V2_LEGAL_SOURCE_POLICY||'[]');}catch{throw new V2Error('LEGAL_WATCH_NOT_CONFIGURED','Configure an operator-approved exact source URL list.',503);}
 ensure(Array.isArray(entries)&&entries.length<=100,'LEGAL_WATCH_NOT_CONFIGURED','Configure a bounded operator source policy.');const matches=entries.filter(p=>p?.tenantId===tenantId);ensure(matches.length===1,'LEGAL_WATCH_NOT_CONFIGURED','This tenant has no unique legal-source read policy.');const p=matches[0];
 ensure(Object.keys(p).every(k=>['tenantId','urls','validUntil','maxBytes'].includes(k))&&Array.isArray(p.urls)&&p.urls.length<=100&&p.urls.every(u=>typeof u==='string')&&p.urls.includes(url)&&Number.isInteger(p.maxBytes)&&p.maxBytes>=1&&p.maxBytes<=1_000_000&&Number.isFinite(Date.parse(p.validUntil))&&Date.parse(p.validUntil)>Date.now(),'LEGAL_SOURCE_NOT_ALLOWED','The exact source URL or read policy is unavailable or expired.');
 const parsed=new URL(url);ensure(parsed.protocol==='https:'&&!parsed.username&&!parsed.password&&!parsed.hash&&(!parsed.port||parsed.port==='443')&&!isIP(parsed.hostname.replace(/^\[|\]$/g,''))&&!['localhost','localhost.localdomain'].includes(parsed.hostname)&&!parsed.hostname.endsWith('.local'),'LEGAL_SOURCE_NOT_ALLOWED','Only operator-selected public HTTPS sources are supported.');return p;
}
export function publicLegalAddress(address:string){
 if(isIP(address)===4){const [a,b]=address.split('.').map(Number);return a>0&&a!==10&&a!==127&&a<224&&!(a===169&&b===254)&&!(a===172&&b>=16&&b<=31)&&!(a===192&&(b===168||b===0))&&!(a===100&&b>=64&&b<=127)&&!(a===198&&(b===18||b===19));}
 if(isIP(address)===6){const value=address.toLowerCase();return /^[23]/.test(value)&&!value.startsWith('2001:db8:')&&!value.startsWith('2001::')&&!/^2001:0{1,4}:/.test(value)&&!value.startsWith('2002:');}
 return false;
}
/** Resolve once and pin the public address to TLS; redirects and DNS rebinding cannot target a private service. */
async function publicRead(url:string,p:ReadPolicy):Promise<Response>{
 const endpoint=new URL(url);let timer:ReturnType<typeof setTimeout>|undefined;const addresses=await Promise.race([lookup(endpoint.hostname,{all:true}),new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(new V2Error('LEGAL_SOURCE_UNAVAILABLE','Source DNS resolution timed out.',503)),15000);})]).finally(()=>{if(timer)clearTimeout(timer);});ensure(addresses.length>0&&addresses.every(a=>publicLegalAddress(a.address)),'LEGAL_SOURCE_NETWORK_SCOPE','The monitored source must resolve only to public network addresses.');const selected=addresses[0];
 return new Promise((resolve,reject)=>{const request=httpsRequest(endpoint,{method:'GET',agent:false,signal:AbortSignal.timeout(15000),family:selected.family,lookup:(_host,options,callback)=>callback(null,options.all?[selected]:selected.address,selected.family),headers:{Accept:'text/plain, text/html;q=0.9, application/xml;q=0.8','Accept-Encoding':'identity'}},response=>{if((response.statusCode||0)<200||(response.statusCode||0)>=300||response.headers['content-encoding']&&response.headers['content-encoding']!=='identity'){response.destroy();reject(new V2Error('LEGAL_SOURCE_UNAVAILABLE','Redirected, compressed or unavailable source requires explicit adapter review.',503));return;}const chunks:Buffer[]=[];let count=0;response.on('data',(chunk:Buffer)=>{count+=chunk.byteLength;if(count>p.maxBytes){response.destroy();reject(new V2Error('LEGAL_SOURCE_CAPACITY','The monitored source exceeds its approved byte bound.',413));}else chunks.push(chunk);});response.on('error',reject);response.on('end',()=>resolve(new Response(Buffer.concat(chunks),{status:response.statusCode,headers:{'content-type':String(response.headers['content-type']||'')}})));});request.setTimeout(15000,()=>request.destroy(new V2Error('LEGAL_SOURCE_UNAVAILABLE','The selected public source timed out.',503)));request.on('error',reject);request.end();});
}
function eligible(s:State,w:LegalSourceWatch,token?:string){const a=actor(s,w),authority=readRecord(s,a,s.legalAuthorities,w.authorityId),member=requireRole(s,a,'legal_reviewer',authority),p=readPolicy(s.tenantId,w.sourceUrl);ensure(w.active&&member.version===w.membershipVersion&&authority.sourceUrl===w.sourceUrl&&digest(p)===w.policyHash,'LEGAL_WATCH_CHANGED','Source ownership, permission or operator policy changed.');if(token)ensure(w.leaseToken===token&&!!w.leaseUntil&&Date.parse(w.leaseUntil)>Date.now(),'LEGAL_WATCH_LEASE','The source check lease expired.');return {a,authority,policy:p,source:readRecord(s,a,s.sources,authority.sourceId)};}
function decodeHtmlEntities(value:string){
 const named:Record<string,string>={amp:'&',lt:'<',gt:'>',quot:'"',apos:"'",nbsp:' ',sect:'§',ndash:'–',mdash:'—',lsquo:'‘',rsquo:'’',ldquo:'“',rdquo:'”',hellip:'…',copy:'©',reg:'®',trade:'™',bull:'•',middot:'·'};
 return value.replace(/&(?:#[xX][0-9a-fA-F]+|#[0-9]+|[A-Za-z][A-Za-z0-9]+);/g,entity=>{if(entity[1]!=='#')return named[entity.slice(1,-1)]??entity;const hex=entity[2]?.toLowerCase()==='x',point=Number.parseInt(entity.slice(hex?3:2,-1),hex?16:10);return point>0&&point<=0x10ffff&&!(point>=0xd800&&point<=0xdfff)?String.fromCodePoint(point):entity;});
}
/** Plain-text extraction preserves raw bytes separately; it is never an applicability assessment. */
export function extractLegalSource(bytes:Uint8Array,contentType:string){let text:string;try{text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);}catch{throw new V2Error('LEGAL_SOURCE_ENCODING','The selected source is not supported UTF-8 text.',422);}if(contentType==='text/html'){text=decodeHtmlEntities(text.replace(/<!--[\s\S]*?-->/g,'').replace(/<(script|style|noscript)\b[^>]*>[\s\S]*?<\/\1\s*>/gi,'').replace(/<(?:\/p|\/div|\/h[1-6]|\/tr|br|\/li)\b[^>]*>/gi,'\n').replace(/<[^>]*>/g,' ')).replace(/[ \t]+/g,' ').replace(/\n[ \t]+/g,'\n').trim();}
 if(contentType==='application/xml'||contentType==='text/xml'){
  ensure(!/<!DOCTYPE\b|<!ENTITY\b/i.test(text)&&/<CFRGRANULE\b[^>]*>[\s\S]*<\/CFRGRANULE>\s*$/i.test(text),'LEGAL_SOURCE_FORMAT','The selected CFR XML rendition is unsupported.');
  text=text.replace(/<!--[\s\S]*?-->/g,'').replace(/<\?[\s\S]*?\?>/g,'').replace(/<(?:\/SECTNO|\/SUBJECT|\/P|\/SECTION|\/APPENDIX|\/ITEM)\b[^>]*>/gi,'\n').replace(/<[^>]*>/g,' ').replace(/&(?:amp|lt|gt|quot|apos);|&#(?:x[0-9a-f]+|[0-9]+);/gi,entity=>{const named:{[key:string]:string}={'&amp;':'&','&lt;':'<','&gt;':'>','&quot;':'"','&apos;':"'"};const known=named[entity.toLowerCase()];if(known)return known;const hex=entity[2].toLowerCase()==='x',value=Number.parseInt(entity.slice(hex?3:2,-1),hex?16:10);return value>0&&value<=0x10ffff&&!(value>=0xd800&&value<=0xdfff)?String.fromCodePoint(value):'';}).replace(/[ \t]+/g,' ').replace(/\n[ \t]+/g,'\n').trim();
 }
 ensure(text.trim().length>0&&text.length<=100000,'LEGAL_SOURCE_CAPACITY','Extracted source text must contain 1–100,000 characters.');return text;
}
async function fetchSource(w:LegalSourceWatch,p:ReadPolicy,fetcher?:typeof fetch){let r:Response;try{r=fetcher?await fetcher(w.sourceUrl,{method:'GET',redirect:'error',credentials:'omit',signal:AbortSignal.timeout(15000),headers:{Accept:'text/plain, text/html;q=0.9, application/xml;q=0.8'}}):await publicRead(w.sourceUrl,p);}catch(error){if(error instanceof V2Error)throw error;throw new V2Error('LEGAL_SOURCE_UNAVAILABLE','The selected public source did not complete its read.',503);}ensure(r.ok,'LEGAL_SOURCE_UNAVAILABLE','The selected public source is unavailable.');const type=(r.headers.get('content-type')||'').split(';')[0].trim().toLowerCase();ensure(['text/plain','text/html','application/xml','text/xml'].includes(type),'LEGAL_SOURCE_FORMAT','This monitored source requires a supported text, HTML or CFR XML representation.');const target=new URL(w.sourceUrl);if(target.hostname==='www.govinfo.gov'&&/^\/content\/pkg\/CFR-[^/]+\/xml\/[^/]+\.xml$/.test(target.pathname))ensure(['application/xml','text/xml'].includes(type),'LEGAL_SOURCE_FORMAT','The selected CFR XML source returned a different format.');ensure(!!r.body&&Number(r.headers.get('content-length')||0)<=p.maxBytes,'LEGAL_SOURCE_CAPACITY','The selected source exceeds its approved read bound.');const reader=r.body!.getReader(),parts:Uint8Array[]=[];let size=0;while(true){const part=await reader.read();if(part.done)break;size+=part.value.byteLength;if(size>p.maxBytes){await reader.cancel();throw new V2Error('LEGAL_SOURCE_CAPACITY','The selected source exceeds its approved byte bound.');}parts.push(part.value);}const bytes=Buffer.concat(parts);if(target.hostname==='www.govinfo.gov'&&target.pathname.startsWith('/content/pkg/')&&type==='text/html')ensure(!/<title>\s*(?:Page Not Found|Error)\s*\|\s*GovInfo\s*<\/title>/i.test(bytes.toString('utf8')),'LEGAL_SOURCE_FORMAT','GovInfo returned an HTML error page instead of the selected publication.');return {bytes,text:extractLegalSource(bytes,type),type,rawHash:createHash('sha256').update(bytes).digest('hex')};}
/** Initial authority intake uses the same exact URL policy and bounded reader as scheduled observations. */
export function assertLegalSourceReadPolicy(tenantId:string,url:string){readPolicy(tenantId,url);}
export function readSelectedLegalSource(tenantId:string,url:string,fetcher?:typeof fetch){return fetchSource({sourceUrl:url} as LegalSourceWatch,readPolicy(tenantId,url),fetcher);}
function initialRawHash(source:Source,tenantId:string){
 if(!source.originalObjectRef)return createHash('sha256').update(source.text).digest('hex');
 let reference:unknown;try{reference=JSON.parse(source.originalObjectRef);}catch{throw new V2Error('LEGAL_SOURCE_ORIGINAL_INVALID','The retained source original cannot establish a monitoring baseline.',503);}
 const row=reference as {key?:unknown;sha256?:unknown;bytes?:unknown;storage?:unknown}|null;
 const tenantHash=createHash('sha256').update(tenantId).digest('hex');
 if(!row||typeof row.key!=='string'||!row.key.startsWith(`${tenantHash}/`)||typeof row.sha256!=='string'||!/^[a-f0-9]{64}$/.test(row.sha256)||row.key.split('/')[1]!==row.sha256||typeof row.bytes!=='number'||!Number.isSafeInteger(row.bytes)||row.bytes<0||!['local_encrypted','mongo_encrypted','s3_kms'].includes(String(row.storage)))throw new V2Error('LEGAL_SOURCE_ORIGINAL_INVALID','The retained source original cannot establish a monitoring baseline.',503);
 return row.sha256;
}
export function legalMaintenanceViews(s:State,a:ActorContext):LegalMaintenanceView{return {availability:s.legalAuthorities.filter(r=>canRead(s,a,r)).map(r=>{try{readPolicy(s.tenantId,r.sourceUrl);return {authorityId:r.id,configured:true,reason:null};}catch(error){return {authorityId:r.id,configured:false,reason:error instanceof V2Error?error.code:'LEGAL_WATCH_NOT_CONFIGURED'};}}),watches:(s.legalWatches||[]).filter(w=>canRead(s,a,w)).map(w=>{const {leaseToken:_token,leaseUntil:_lease,policyHash:_policy,membershipVersion:_member,lastObservedWorkspaceVersion:_revision,...visible}=structuredClone(w);return {...visible,overdue:w.active&&Date.parse(w.nextCheckAt)<Date.now()};}),changes:(s.legalChanges||[]).filter(c=>canRead(s,a,c)).map(c=>structuredClone(c))};}
export function legalAuthorityHasPendingChange(s:State,authorityId:string){return (s.legalChanges||[]).some(c=>c.authorityId===authorityId&&c.status==='pending_review');}
export function applyLegalMaintenanceCommand(s:State,a:ActorContext,c:LegalMaintenanceCommand):Record<string,unknown>{
 s.legalWatches??=[];s.legalChanges??=[];
 if(c.type==='legal.watch.configure'){
  const authority=readRecord(s,a,s.legalAuthorities,c.authorityId),member=requireRole(s,a,'legal_reviewer',authority);ensure(authority.version===c.expectedAuthorityVersion,'VERSION_CONFLICT','Inspect the current legal source before monitoring.');ensure(Number.isInteger(c.intervalHours)&&c.intervalHours>=1&&c.intervalHours<=720,'INVALID_INTERVAL','Choose a check interval from 1 to 720 hours.');const policy=readPolicy(s.tenantId,authority.sourceUrl);ensure(!s.legalWatches.some(w=>w.authorityId===authority.id&&w.active),'WATCH_EXISTS','Stop the existing source monitor before replacing its policy.');
  const watch:LegalSourceWatch={...base(s,a,authority,[authority.sourceId]),authorityId:authority.id,ownerId:a.actorId,membershipVersion:member.version,sourceUrl:authority.sourceUrl,policyHash:digest(policy),intervalHours:c.intervalHours,active:true,nextCheckAt:timestamp(),lastCheckedAt:null,lastObservedHash:null,lastObservedWorkspaceVersion:undefined,status:'scheduled',failureCode:null,leaseToken:null,leaseUntil:null};s.legalWatches.push(watch);s.outbox.push({id:randomUUID(),tenantId:s.tenantId,kind:'legal_watch',aggregateId:watch.id,commandId:watch.id,status:'pending',owner:'v2',createdAt:timestamp()});return {watchId:watch.id};
 }
 if(c.type==='legal.watch.stop'){const watch=readRecord(s,a,s.legalWatches,c.watchId);requireRole(s,a,'legal_reviewer',watch);ensure(watch.version===c.expectedRecordVersion,'VERSION_CONFLICT','Inspect the current monitor.');watch.active=false;watch.status='stopped';watch.leaseToken=null;watch.leaseUntil=null;touch(watch);return {watchId:watch.id};}
 const change=readRecord(s,a,s.legalChanges,c.changeId),member=requireRole(s,a,'legal_reviewer',change);ensure(change.version===c.expectedRecordVersion&&change.status==='pending_review'&&change.oldHash===c.oldHash&&change.newHash===c.newHash,'CHANGE_REVIEW_CHANGED','Inspect the exact old and observed source texts before assessment.');
 const old=readRecord(s,a,s.sources,change.oldSourceId),next=readRecord(s,a,s.sources,change.newSourceId);ensure(old.contentHash===change.oldHash&&next.contentHash===change.newHash,'SOURCE_CHANGED','The source review basis changed.');ensure(['no_applicability_change','affected_work'].includes(c.decision)&&typeof c.adoptSource==='boolean'&&typeof c.reason==='string'&&c.reason.trim().length>0&&c.reason.length<=4000,'INVALID_ASSESSMENT','Record a bounded attributed applicability assessment.');ensure(Array.isArray(c.matterIds)&&Array.isArray(c.learningIds)&&c.matterIds.length<=100&&c.learningIds.length<=100&&new Set(c.matterIds).size===c.matterIds.length&&new Set(c.learningIds).size===c.learningIds.length,'INVALID_TARGETS','Choose distinct bounded affected work.');ensure(c.decision==='affected_work'?c.matterIds.length+c.learningIds.length>0:c.matterIds.length+c.learningIds.length===0,'INVALID_TARGETS','A no-change assessment has no affected work; an affected assessment names its targets.');
 const watch=s.legalWatches.find(w=>w.id===change.watchId&&w.authorityId===change.authorityId);
 const latest=s.legalChanges.filter(item=>item.authorityId===change.authorityId).at(-1);
 const observed=s.legalWatches.filter(w=>w.authorityId===change.authorityId&&Number.isSafeInteger(w.lastObservedWorkspaceVersion)).sort((left,right)=>right.lastObservedWorkspaceVersion!-left.lastObservedWorkspaceVersion!)[0];
 const latestObservation=!!watch&&observed?.id===watch.id&&observed.lastObservedHash===change.rawHash&&latest?.id===change.id&&latest.newSourceId===change.newSourceId;
 ensure(latestObservation||!c.adoptSource&&c.decision==='no_applicability_change','CHANGE_OBSERVATION_SUPERSEDED','A newer source observation exists. Earlier observations may be closed without source adoption or affected-work targeting; inspect the latest source before changing work.');
 const matters=c.matterIds.map(id=>readRecord(s,a,s.matters,id)),lessons=c.learningIds.map(id=>readRecord(s,a,s.learning,id));ensure(matters.every(m=>m.state!=='canceled'&&!m.legacyWorkflowId),'MATTER_TERMINAL','Canceled and legacy-owned work cannot be reopened by source monitoring.');ensure([...matters,...lessons].every(r=>sameScope(r,change)),'APPLICABILITY_SCOPE','Affected work must have the same audience as the reviewed legal source.');
 for(const m of matters){m.sourceIds=[...new Set([...m.sourceIds,next.id])];m.provenance.sourceIds=[...new Set([...m.provenance.sourceIds,next.id])];if(m.state!=='canceled'){m.state='legal_review';m.closedAt=null;m.outcome=null;}m.blockers=[...new Set([...m.blockers,'A reviewed legal-source change requires matter-specific applicability review.'])];m.tasks.push({id:randomUUID(),title:'Review the assessed legal-source change',ownerId:a.actorId,status:'pending',kind:'legal',dueAt:null,deadlineType:'undated',evidenceIds:[change.id,next.id]});for(const p of s.proposals.filter(p=>p.matterId===m.id&&p.status==='current')){p.status='invalidated';touch(p);}for(const approval of s.approvals.filter(x=>x.matterId===m.id&&x.status==='active')){approval.status='invalidated';touch(approval);}for(const action of s.actions.filter(x=>x.matterId===m.id&&['planned','authorized','pending_manual'].includes(x.status))){action.status='planned';action.authorizationId=null;touch(action);}touch(m);s.outbox.push({id:randomUUID(),tenantId:s.tenantId,kind:'matter_changed',aggregateId:m.id,commandId:change.id,status:'pending',owner:'v2',createdAt:timestamp()});}
 for(const lesson of lessons){lesson.provenance.sourceIds=[...new Set([...lesson.provenance.sourceIds,next.id])];if(lesson.status==='promoted')lesson.reviewDueAt=timestamp();touch(lesson);}
 if(c.adoptSource){const authority=readRecord(s,a,s.legalAuthorities,change.authorityId);ensure(authority.sourceId===old.id,'SOURCE_CHANGED','This authority already adopted another observed version.');authority.sourceId=next.id;authority.provenance.sourceIds=[...new Set([...authority.provenance.sourceIds,next.id])];authority.verifiedAt=null;authority.verifiedSourceHash=undefined;authority.verifiedSourceVersion=undefined;authority.reviewDueAt=timestamp();touch(authority);for(const coverage of s.coverage.filter(entry=>entry.authorityIds?.includes(authority.id))){coverage.sourceIds=[...new Set([...coverage.sourceIds,next.id])];coverage.provenance.sourceIds=[...new Set([...coverage.provenance.sourceIds,next.id])];coverage.status='pending_review';touch(coverage);}}
 change.status='assessed';change.assessment={actorId:a.actorId,membershipVersion:member.version,decision:c.decision,reason:c.reason.trim(),matterIds:[...c.matterIds],learningIds:[...c.learningIds],adoptedSource:c.adoptSource,assessedAt:timestamp()};touch(change);return {changeId:change.id,matterIds:c.matterIds,learningIds:c.learningIds,sourceReviewRequired:c.adoptSource};
}
/** The scheduled worker performs reads only; assessed applicability and source approval remain human commands. */
export async function processLegalWatch(tenantId:string,watchId:string,options:{fetcher?:typeof fetch}={}):Promise<{complete:boolean;nextCheckMs:number;status:LegalSourceWatch['status']}>{
 const token=randomUUID(),claimed=await transactWorkspace(tenantId,state=>{const s=state as State,w=s.legalWatches?.find(w=>w.id===watchId);if(!w)throw new V2Error('WATCH_NOT_FOUND','Source monitor unavailable.',404);if(!w.active)return {claimed:false,complete:true,status:w.status,nextCheckMs:0};if(w.leaseUntil&&Date.parse(w.leaseUntil)>Date.now()||Date.parse(w.nextCheckAt)>Date.now())return {claimed:false,complete:false,status:w.status,nextCheckMs:Math.max(60000,Date.parse(w.nextCheckAt)-Date.now())};w.leaseToken=token;w.leaseUntil=new Date(Date.now()+60000).toISOString();w.status='checking';touch(w);return {claimed:true,complete:false,status:w.status,nextCheckMs:60000};});if(!claimed.result.claimed)return claimed.result;
 try{
  const before=await readWorkspace(tenantId) as State,w=before.legalWatches!.find(w=>w.id===watchId)!,basis=eligible(before,w,token),observed=await fetchSource(w,basis.policy,options.fetcher),latest=await readWorkspace(tenantId) as State,current=latest.legalWatches!.find(w=>w.id===watchId)!;const checked=eligible(latest,current,token);ensure(checked.authority.version===basis.authority.version&&checked.source.id===basis.source.id&&checked.source.contentHash===basis.source.contentHash,'LEGAL_SOURCE_CHANGED','The reviewed authority changed during source retrieval.');
  const changed=observed.rawHash!==(current.lastObservedHash||initialRawHash(checked.source,tenantId)),original=changed?await retainIntakeOriginal(checked.a,`legal-watch:${watchId}:${observed.rawHash}`,observed.bytes,latest.version):null;
  return (await transactWorkspace(tenantId,state=>{const s=state as State,indexBefore=indexRecordFingerprints(s),watch=s.legalWatches!.find(w=>w.id===watchId)!,check=eligible(s,watch,token);ensure(check.authority.version===basis.authority.version&&check.source.contentHash===basis.source.contentHash,'LEGAL_SOURCE_CHANGED','The source assessment changed during original retention.');if(changed&&original){const encoded=JSON.stringify(original.reference);assertOriginalNotDeleted(s,encoded,digest({actor:check.a.actorId,key:`legal-watch:${watchId}:${observed.rawHash}`}));const source:Source={...base(s,check.a,check.source,[check.source.id]),title:`Observed update: ${check.authority.title}`,kind:'legal',externalId:watch.id,externalRevision:observed.rawHash,text:observed.text,contentHash:digest(observed.text),url:watch.sourceUrl,status:'active',aclVersion:1,observedAt:timestamp(),effectiveAt:null,authority:'unknown',originalObjectRef:encoded};s.sources.push(source);const change:LegalSourceChange={...base(s,check.a,check.authority,[check.source.id,source.id]),watchId:watch.id,authorityId:check.authority.id,oldSourceId:check.source.id,newSourceId:source.id,oldHash:check.source.contentHash,newHash:source.contentHash,rawHash:observed.rawHash,status:'pending_review',assessment:null};(s.legalChanges||=[]).push(change);check.authority.reviewDueAt=timestamp();touch(check.authority);s.events.push({...base(s,check.a,change),type:'legal.source.changed',title:'Legal source changed; applicability review pending',detail:'Observed text is retained with its original. A named reviewer must determine applicability before affected work is identified.',matterId:null,recordId:change.id,measurement:s.rehearsal?'fictional_rehearsal':'observed'});}
   enqueueIndexMaintenance(s,check.a,indexBefore,watch.id+':'+observed.rawHash);watch.lastCheckedAt=timestamp();watch.lastObservedHash=observed.rawHash;watch.lastObservedWorkspaceVersion=s.version+1;watch.nextCheckAt=new Date(Date.now()+watch.intervalHours*3600000).toISOString();watch.status=legalAuthorityHasPendingChange(s,watch.authorityId)?'review_required':'scheduled';watch.failureCode=null;watch.leaseToken=null;watch.leaseUntil=null;touch(watch);return {complete:false,nextCheckMs:watch.intervalHours*3600000,status:watch.status};})).result;
 }catch(error){return (await transactWorkspace(tenantId,state=>{const watch=(state as State).legalWatches?.find(w=>w.id===watchId);if(!watch)throw error;if(watch.leaseToken!==token)return {complete:!watch.active,nextCheckMs:60000,status:watch.status};watch.failureCode=error instanceof V2Error?error.code:'LEGAL_SOURCE_CHECK_FAILED';if(['NOT_FOUND','MEMBERSHIP_REVOKED','LEGAL_WATCH_CHANGED'].includes(watch.failureCode))watch.active=false;watch.status=watch.active?'blocked':'stopped';watch.nextCheckAt=new Date(Date.now()+3600000).toISOString();watch.leaseToken=null;watch.leaseUntil=null;touch(watch);return {complete:!watch.active,nextCheckMs:3600000,status:watch.status};})).result;}
}
