import {randomUUID} from 'node:crypto';
import {canRead,readRecord,requireRole} from './authority';
import {digest,timestamp} from './store';
import {currentEvidenceLineage} from './source-lifecycle';
import {factCurrentlyConfirmed} from './fact-validity';
import {documentHeads} from './document-lifecycle';
import {scopeAudienceHash} from './integrations/slack-scope';
import {resetReviewTasks} from './tasks';
import {currentInventory,inventoryBinding} from './inventory';
import {procedureAssessment} from './procedures';
import {V2Error,type ActorContext,type Conversation,type Matter,type MatterTask,type Proposal,type RecordBase,type WorkspaceState} from './contracts';
import type {DraftProposal,DraftRequest} from './drafting';
import {coveragePacket,type EvidencePacket,type EvidenceReference} from './retrieval';
export interface MatterPreparationBasis {matterId:string;matterVersion:number;matterHash:string;planId:string;planHash:string;objective:string;tasks:MatterTask[];ruleVersion:number}
const need=(v:unknown,code:string,message:string)=>{if(!v)throw new V2Error(code,message);};
const touch=(r:RecordBase)=>{r.version++;r.updatedAt=timestamp();};
export function acceptedPlan(s:WorkspaceState,m:Matter){return (s.drafts||[]).find(d=>d.request.kind==='plan'&&d.status==='accepted'&&d.acceptedMatterId===m.id);}
/** The accepted plan is attributed intent, never an assertion that its proposed work occurred. */
export function buildMatterPreparation(s:WorkspaceState,a:ActorContext,m:Matter,c:Conversation):DraftRequest {
 requireRole(s,a,'business_owner',m);const plan=acceptedPlan(s,m);need(plan&&eligible(s,a,c,m)&&eligible(s,a,c,plan)&&currentEvidenceLineage(s,plan)&&plan.conversationId===c.id&&c.matterId===m.id&&m.conversationIds.includes(c.id)&&scopeAudienceHash(c.scope)===scopeAudienceHash(m.scope),'MATTER_PLAN_UNAVAILABLE','Inspect the accepted plan and its current linked conversation.');need(!m.legacyWorkflowId&&!['closed','canceled'].includes(m.state),'MATTER_TERMINAL','This matter cannot accept new preparation.');need(!s.actions.some(x=>x.matterId===m.id&&['dispatching','uncertain','verifying'].includes(x.status)),'RECONCILIATION_REQUIRED','Resolve outstanding effects before preparing a replacement packet.');
 if(!m.tasks.some(t=>t.kind==='business'&&t.title==='Review the prepared artifact for the accepted plan')){m.tasks.push({id:randomUUID(),title:'Review the prepared artifact for the accepted plan',kind:'business',purpose:'artifact_review',ownerId:m.ownerId,status:'pending',dueAt:null,deadlineType:'undated',evidenceIds:[]});touch(m);}
 const basis:MatterPreparationBasis={matterId:m.id,matterVersion:m.version,matterHash:digest(m),planId:plan!.id,planHash:digest(plan),objective:m.objective,tasks:structuredClone(m.tasks),ruleVersion:s.ruleVersion};
 return {kind:'matter_packet',matter:basis,instruction:'Prepare a concrete review artifact for the exact accepted work plan. Follow its objective and required tasks. Identify unresolved facts and decisions explicitly. Do not substitute a generic data-flow or notice checklist when the objective concerns different work. The accepted plan is user-approved intent, not evidence of facts, legal applicability or completion. Produce proposed text and bounded additional work only; no actions or approvals are authorized.',baseRevisionId:null,baseHash:null,templateApprovalId:null,templateApprovalHash:null,fieldFactIds:{},factHashes:{},missingFields:[],amendment:false};
}
export function assertMatterPreparation(s:WorkspaceState,a:ActorContext,r:DraftRequest){
 const b=r.matter;need(r.kind==='matter_packet'&&b,'MATTER_BASIS_REQUIRED','A prepared packet must bind its accepted matter plan.');const m=readRecord(s,a,s.matters,b!.matterId),plan=readRecord(s,a,s.drafts||[],b!.planId),c=readRecord(s,a,s.conversations,plan.conversationId);requireRole(s,a,'business_owner',m);need(m.version===b!.matterVersion&&digest(m)===b!.matterHash&&digest(plan)===b!.planHash&&plan.status==='accepted'&&plan.acceptedMatterId===m.id&&plan.request.kind==='plan'&&s.ruleVersion===b!.ruleVersion&&c.matterId===m.id&&scopeAudienceHash(c.scope)===scopeAudienceHash(m.scope)&&eligible(s,a,c,m)&&eligible(s,a,c,plan)&&!m.legacyWorkflowId&&!['closed','canceled'].includes(m.state),'MATTER_BASIS_CHANGED','The accepted objective, work, plan, evidence or policy changed. Prepare another packet.');need(!s.actions.some(x=>x.matterId===m.id&&['dispatching','uncertain','verifying'].includes(x.status)),'RECONCILIATION_REQUIRED','Resolve outstanding submitted effects before replacing this packet.');return m;
}
function eligible(s:WorkspaceState,a:ActorContext,c:Conversation,r:RecordBase,seen=new Set<string>()):boolean {if(seen.has(r.id))return true;seen.add(r.id);if(scopeAudienceHash(r.scope)!==scopeAudienceHash(c.scope)||!canRead(s,a,r)||!currentEvidenceLineage(s,r))return false;return r.provenance.sourceIds.every(id=>{const source=s.sources.find(x=>x.id===id);return !!source&&eligible(s,a,c,source,seen);})&&(r.provenance.factIds||[]).every(id=>{const f=s.facts.find(x=>x.id===id);return !!f&&factCurrentlyConfirmed(f)&&eligible(s,a,c,f,seen);});}
function refRecord(s:WorkspaceState,ref:EvidenceReference):RecordBase|undefined{return (ref.kind==='source'?s.sources:ref.kind==='document'?s.documents:ref.kind==='fact'?s.facts:ref.kind==='message'?s.messages:ref.kind==='conversation'?s.conversations:ref.kind==='scenario'?s.scenarios:ref.kind==='authority'?s.legalAuthorities:s.coverage).find(r=>r.id===ref.id);}
/** Narrow the shared retrieval packet to the matter audience before any model request. */
export function matterPreparationPacket(s:WorkspaceState,a:ActorContext,c:Conversation,r:DraftRequest,packet:EvidencePacket):EvidencePacket {
 const matter=assertMatterPreparation(s,a,r),plan=s.drafts!.find(d=>d.id===r.matter!.planId)!;const refs=packet.references.filter(ref=>{const record=refRecord(s,ref);return !!record&&eligible(s,a,c,record);});
 // The frozen objective and completed-work notes are model input independently of ranked excerpts.
 // Bind their entire proof graph even when retrieval selected none of those records.
 const basisSeen=new Set<string>();const bind=(record:RecordBase)=>{for(const [kind,ids] of [['source',record.provenance.sourceIds],['fact',record.provenance.factIds||[]]] as const)for(const id of ids){const key=`${kind}:${id}`;if(basisSeen.has(key))continue;basisSeen.add(key);const dependency=(kind==='source'?s.sources:s.facts).find(x=>x.id===id);need(dependency&&eligible(s,a,c,dependency)&&(kind!=='fact'||factCurrentlyConfirmed(dependency as WorkspaceState['facts'][number])),'MATTER_BASIS_CHANGED','The complete accepted-plan evidence must remain current and in this exact audience.');refs.push({kind,id,hash:digest(dependency)});bind(dependency!);}};bind(matter);bind(plan);
 const references=[...new Map(refs.map(ref=>[`${ref.kind}:${ref.id}`,ref])).values()],ids=new Set(references.map(x=>x.id));const evidence=packet.evidence.filter(e=>{if(e.sourceId&&!ids.has(e.sourceId)||e.factId&&!ids.has(e.factId))return false;if(e.kind==='document'){const doc=s.documents.find(d=>e.anchor.startsWith(`document:${d.id}:`));return !!doc&&ids.has(doc.id);}return true;});
 return {...structuredClone(packet),audienceScopeHash:scopeAudienceHash(c.scope),history:[],evidence,references,sourceIds:references.filter(ref=>ref.kind==='source').map(ref=>ref.id),factIds:references.filter(ref=>ref.kind==='fact').map(ref=>ref.id),hypotheses:[],coverage:coveragePacket(s,a,c,scopeAudienceHash(c.scope)),agreementInventory:packet.agreementInventory.filter(x=>ids.has(x.documentId)),limitations:[...packet.limitations,'Prepared for the exact accepted plan and same audience only. Prior conversation text and unrelated private evidence are excluded. Legal coverage is limited to registered records with this exact audience and dependency audience; broader, narrower or unrelated coverage is omitted and provides no qualification. Inventory completeness requires a separately current attestation.']};
}
/** Exact owner adoption creates a review proposal; generated questions/tasks never complete work. */
export function adoptMatterPreparation(s:WorkspaceState,a:ActorContext,d:DraftProposal,commandId:string){
 const m=assertMatterPreparation(s,a,d.request);requireRole(s,a,'business_owner',d);need(d.request.kind==='matter_packet','MATTER_BASIS_REQUIRED','This artifact is not a prepared matter packet.');const sourceIds=[...new Set(d.provenance.sourceIds)],factIds=[...new Set(d.provenance.factIds||[])],documents=documentHeads(s.documents).filter(x=>(d.evidenceReferences||[]).some(ref=>ref.kind==='document'&&ref.id===x.id));
 m.sourceIds=sourceIds;m.factIds=factIds;m.documentIds=documents.map(x=>x.id);m.provenance.sourceIds=sourceIds;m.provenance.factIds=factIds;m.ruleVersion=s.ruleVersion;
 need(m.tasks.length+d.tasks.length<=100,'MATTER_TASK_LIMIT','Resolve or consolidate the existing work before adding more proposed tasks.');
 for(const proposed of d.tasks)if(!m.tasks.some(t=>t.kind===proposed.kind&&t.title===proposed.title&&digest(t.requiredFactPredicates||[])===digest(proposed.requiredFactPredicates)))m.tasks.push({id:randomUUID(),title:proposed.title,kind:proposed.kind,purpose:'work',requiredFactPredicates:proposed.requiredFactPredicates,ownerId:m.ownerId,status:'pending',dueAt:null,deadlineType:'undated',evidenceIds:[]});
 for(const task of m.tasks.filter(t=>t.kind==='fact')){const requirements=task.requiredFactPredicates||[],matches=factIds.filter(id=>{const f=s.facts.find(x=>x.id===id)!;return requirements.includes(f.predicate)&&factCurrentlyConfirmed(f)&&currentEvidenceLineage(s,f);});task.status=requirements.length&&requirements.every(p=>matches.some(id=>s.facts.find(f=>f.id===id)!.predicate===p))?'done':'pending';task.evidenceIds=matches;}
 const inventory=currentInventory(s,a,m);if(inventory){m.sourceIds=[...new Set([...m.sourceIds,...inventory.provenance.sourceIds])];m.provenance.sourceIds=m.sourceIds;}const procedure=procedureAssessment(s,a,m),unknowns=[...d.questions,...procedure.blockers,'Qualified legal review and applicability remain pending.',...(!inventory?['Agreement inventory completeness has not been attested.']:[])];
 const p:Proposal={id:randomUUID(),tenantId:s.tenantId,version:1,createdAt:timestamp(),updatedAt:timestamp(),scope:structuredClone(m.scope),provenance:{actorId:a.actorId,sourceIds:m.sourceIds,factIds:m.factIds,description:'Exact owner-adopted model preparation for the accepted plan; separate business/legal review remains required.'},matterId:m.id,title:d.title,body:d.body,contentHash:d.contentHash,baselineRevisionIds:m.documentIds,dependencies:{sourceVersions:Object.fromEntries(m.sourceIds.map(id=>[id,s.sources.find(x=>x.id===id)!.version])),factVersions:Object.fromEntries(m.factIds.map(id=>[id,s.facts.find(x=>x.id===id)!.version])),documentHashes:Object.fromEntries(documents.map(x=>[x.id,x.contentHash])),policyVersion:s.ruleVersion,scopeHash:digest(m.scope)},status:'current',route:'legal_review',noticeMatrix:documents.filter(x=>x.kind==='agreement'&&x.authority==='executed').map(x=>({documentId:x.id,title:x.title,clause:'Review this complete supplied agreement and its amendments against the prepared objective; applicability is not established.',status:'review_required'})),inventoryComplete:!!inventory,...(inventory?{inventory:inventoryBinding(inventory)}:{}),unknowns,supersedesId:m.proposalId};
 if(m.proposalId){const prior=s.proposals.find(x=>x.id===m.proposalId);if(prior){prior.status='superseded';touch(prior);}for(const approval of s.approvals.filter(x=>x.proposalId===m.proposalId&&x.status==='active')){approval.status='invalidated';touch(approval);}for(const action of s.actions.filter(x=>x.proposalId===m.proposalId&&!['verified','uncertain','dispatching','verifying','canceled'].includes(x.status))){action.status='planned';action.authorizationId=null;touch(action);}}
 for(const task of m.tasks.filter(t=>t.purpose==='artifact_review')){task.status='done';task.evidenceIds=[d.id];}
 s.proposals.push(p);m.proposalId=p.id;resetReviewTasks(s,m,p);m.state='business_review';m.blockers=['Review the exact adopted artifact and resolve required factual questions before legal review.',...procedure.blockers];touch(m);d.acceptedMatterId=m.id;d.acceptedProposalId=p.id;s.outbox.push({id:randomUUID(),tenantId:s.tenantId,kind:'matter_changed',aggregateId:m.id,commandId,status:'pending',owner:'v2',createdAt:timestamp()});return p;
}
