import {randomUUID} from 'node:crypto';
import {MongoClient,type ClientSession,type Db} from 'mongodb';
import {V2Error,type WorkspaceState} from './contracts';
import {digest,emptyWorkspace,validateWorkspace,type WorkspaceBackup} from './store';
import {v2DatabaseName} from './database-target';

export const NORMALIZED_COLLECTIONS=['memberships','memoryEntities','memoryRelationships','scopedPrecedents','precedentTargets','applicabilityAssessments','conversations','messages','scenarios','facts','preferences','sources','documents','legalAuthorities','coverage','matters','proposals','approvals','actions','counsel','learning','connections','events','outbox','tombstones','obligations','effortEntries','effortBaselines','deletionJobs','scenarioShares','routingDelegations','routingRules','inventories','attentionSettings','attentionDecisions','legalWatches','legalChanges','templateApprovals','drafts','valueSessions','valueGoals','valueReceipts','notificationEnrollments','notificationDeliveries','strategyFeedback','strategyCandidates','strategyShadows','receipts'] as const;
type Kind=typeof NORMALIZED_COLLECTIONS[number];
export interface NormalizedRow {_id:string;tenantId:string;generation:string;recordKey:string;ordinal:number;hash:string;value:unknown}
export interface NormalizedHead {_id:string;format:1;version:number;generation:string;stateHash:string;arrayKinds:Kind[];metadata:Record<string,unknown>;mode:'normalized'|'aggregate';migrationId:string|null}
export interface NormalizedImage {head:NormalizedHead;rows:Record<Kind,NormalizedRow[]>}
/** Pure image builder used by transaction writes, migration dry run and offline integrity tests. */
export function normalizeWorkspace(state:WorkspaceState,generation:string,migrationId:string|null=null):NormalizedImage {
 validateWorkspace(state,undefined,{aggregateLimit:false});if(!/^[a-zA-Z0-9_-]{1,100}$/.test(generation))throw new V2Error('NORMALIZED_GENERATION','Invalid immutable generation.');
 const metadata=structuredClone(state) as unknown as Record<string,unknown>,rows={} as NormalizedImage['rows'],arrayKinds:Kind[]=[];
 for(const kind of NORMALIZED_COLLECTIONS){const value=metadata[kind];delete metadata[kind];if(kind!=='receipts'&&Array.isArray(value))arrayKinds.push(kind);const values=kind==='receipts'?Object.entries(value||{}).map(([key,item])=>({key,item})):Array.isArray(value)?value.map((item,index)=>({key:String(item.id??item.actorId??item.sourceId??index),item})):[];const keys=new Set<string>();rows[kind]=values.map(({key,item},ordinal)=>{if(keys.has(key))throw new V2Error('STORE_RECORD_IDENTITY','Normalized record keys must be unique.',503);keys.add(key);const row={_id:digest({tenantId:state.tenantId,generation,kind,key}),tenantId:state.tenantId,generation,recordKey:key,ordinal,hash:digest(item),value:structuredClone(item)};if(Buffer.byteLength(JSON.stringify(row))>12_000_000)throw new V2Error('RECORD_CAPACITY','An individual normalized record exceeds the bounded BSON allowance.',413);return row;});}
 return {head:{_id:state.tenantId,format:1,version:state.version,generation,stateHash:digest(state),arrayKinds,metadata,mode:'normalized',migrationId},rows};
}
export function hydrateWorkspace(image:NormalizedImage):WorkspaceState {
 const {head,rows}=image;if(head.format!==1||head.mode!=='normalized')throw new V2Error('NORMALIZED_HEAD_INVALID','The normalized head is unavailable.',503);const state=structuredClone(head.metadata) as unknown as WorkspaceState;
 for(const kind of NORMALIZED_COLLECTIONS){const items=[...rows[kind]].sort((a,b)=>a.ordinal-b.ordinal),ids=new Set<string>();for(const [index,row] of items.entries()){if(row.tenantId!==head._id||row.generation!==head.generation||row.ordinal!==index||ids.has(row.recordKey)||row.hash!==digest(row.value)||row._id!==digest({tenantId:head._id,generation:head.generation,kind,key:row.recordKey}))throw new V2Error('NORMALIZED_INTEGRITY','A scoped normalized record failed integrity validation.',503);ids.add(row.recordKey);}if(kind==='receipts')state.receipts=Object.fromEntries(items.map(row=>[row.recordKey,row.value])) as WorkspaceState['receipts'];else if(head.arrayKinds.includes(kind))(state as unknown as Record<string,unknown>)[kind]=items.map(row=>row.value);else if(items.length)throw new V2Error('NORMALIZED_INTEGRITY','Unexpected records outside the head manifest.',503);}
 if(state.tenantId!==head._id||state.version!==head.version||digest(state)!==head.stateHash)throw new V2Error('NORMALIZED_INTEGRITY','Normalized workspace checksum failed.',503);validateWorkspace(state,undefined,{aggregateLimit:false});return state;
}
export function normalizedDiff(before:NormalizedImage,after:NormalizedImage){if(before.head._id!==after.head._id||before.head.generation!==after.head.generation)throw new V2Error('NORMALIZED_IDENTITY','A transaction cannot change tenant or generation.');return NORMALIZED_COLLECTIONS.map(kind=>{const old=new Map(before.rows[kind].map(r=>[r._id,r])),next=new Map(after.rows[kind].map(r=>[r._id,r]));return {kind,upserts:after.rows[kind].filter(r=>{const previous=old.get(r._id);return !previous||previous.hash!==r.hash||previous.ordinal!==r.ordinal;}),deletes:before.rows[kind].filter(r=>!next.has(r._id)).map(r=>r._id)};});}
let client:MongoClient|undefined,uri:string|undefined,initialized:Promise<void>|undefined;
async function database(){const next=process.env.MONGODB_URI;if(!next)throw new V2Error('NORMALIZED_STORE_NOT_CONFIGURED','Normalized storage requires a MongoDB replica set or Atlas cluster.',503);const target=v2DatabaseName();if(client&&uri!==next)throw new V2Error('STORE_CONFIG_CHANGED','Close storage before changing database identity.',503);if(!client){uri=next;client=new MongoClient(next,{maxPoolSize:8,serverSelectionTimeoutMS:5000});await client.connect();}return client.db(target);}
async function ensureNormalizedIndexes(){const db=await database();initialized||=(async()=>{for(const kind of NORMALIZED_COLLECTIONS)await db.collection<NormalizedRow>(`v2_records_${kind}`).createIndex({tenantId:1,generation:1,ordinal:1});await db.collection('v2_normalized_heads').createIndex({mode:1});})();await initialized;}
export async function closeNormalizedStore(){await client?.close();client=undefined;uri=undefined;initialized=undefined;}
async function load(db:Db,tenantId:string,session:ClientSession):Promise<NormalizedImage|null>{const head=await db.collection<NormalizedHead>('v2_normalized_heads').findOne({_id:tenantId},{session});if(!head)return null;if(head.mode!=='normalized')throw new V2Error('STORE_CUTOVER_REQUIRED','This workspace was rolled back to aggregate storage; switch the operator store mode.',503);const rows={} as NormalizedImage['rows'];for(const kind of NORMALIZED_COLLECTIONS)rows[kind]=await db.collection<NormalizedRow>(`v2_records_${kind}`).find({tenantId,generation:head.generation},{session}).sort({ordinal:1}).toArray();return {head,rows};}
async function transaction<T>(fn:(db:Db,session:ClientSession)=>Promise<T>):Promise<T>{const db=await database(),session=client!.startSession();try{let result:T|undefined;await session.withTransaction(async()=>{result=await fn(db,session);},{readConcern:{level:'snapshot'},writeConcern:{w:'majority'},readPreference:'primary',maxCommitTimeMS:15000});return result!;}finally{await session.endSession();}}
async function assertNew(db:Db,tenantId:string,session:ClientSession){if(await db.collection('v2_workspaces').findOne({_id:tenantId} as never,{session}))throw new V2Error('NORMALIZED_MIGRATION_REQUIRED','Migrate the existing aggregate before selecting normalized mode.',503);}
export async function readNormalized(tenantId:string):Promise<WorkspaceState>{return transaction(async(db,session)=>{const image=await load(db,tenantId,session);if(image)return hydrateWorkspace(image);await assertNew(db,tenantId,session);return emptyWorkspace(tenantId);});}
export async function transactNormalized<T>(tenantId:string,fn:(state:WorkspaceState)=>T):Promise<{state:WorkspaceState;result:T}>{await ensureNormalizedIndexes();return transaction(async(db,session)=>{
 const prior=await load(db,tenantId,session);if(!prior)await assertNew(db,tenantId,session);const before=prior?hydrateWorkspace(prior):emptyWorkspace(tenantId),state=structuredClone(before),result=fn(state);if(result&&typeof (result as {then?:unknown}).then==='function')throw new V2Error('ASYNC_TRANSACTION','External effects cannot run inside a storage transaction.',500);validateWorkspace(state,before,{aggregateLimit:false});if(digest(state)===digest(before))return {state,result};state.version=before.version+1;const generation=prior?.head.generation||randomUUID(),image=normalizeWorkspace(state,generation,prior?.head.migrationId),baseline=prior||normalizeWorkspace(before,generation);
 for(const change of normalizedDiff(baseline,image)){const collection=db.collection<NormalizedRow>(`v2_records_${change.kind}`);if(change.deletes.length)await collection.deleteMany({tenantId,generation,_id:{$in:change.deletes}},{session});for(let n=0;n<change.upserts.length;n+=200)await collection.bulkWrite(change.upserts.slice(n,n+200).map(row=>({replaceOne:{filter:{_id:row._id,tenantId,generation},replacement:row,upsert:true}})),{session});}
 // The common aggregate _id is the ownership arbiter even for an empty tenant.
 if(!prior)await db.collection<Aggregate>('v2_workspaces').insertOne(normalizedBootstrapFence(before,generation),{session});
 const heads=db.collection<NormalizedHead>('v2_normalized_heads');if(prior){const saved=await heads.replaceOne({_id:tenantId,version:prior.head.version,generation,stateHash:prior.head.stateHash,mode:'normalized'},image.head,{session});if(saved.matchedCount!==1)throw new V2Error('STORE_BUSY','Normalized workspace changed during commit.',503);}else await heads.insertOne(image.head,{session});return {state,result:structuredClone(result)};
 });}
interface Aggregate {_id:string;version:number;state:WorkspaceState;storageFence?:{mode:'normalized';generation:string;migrationId:string}}
export function normalizedBootstrapFence(before:WorkspaceState,generation:string):Aggregate{return {_id:before.tenantId,version:before.version,state:structuredClone(before),storageFence:{mode:'normalized',generation,migrationId:`bootstrap:${generation}`}};}
interface Migration {_id:string;tenantId:string;sourceVersion:number;sourceHash:string;generation:string;status:'staging'|'complete'|'rolled_back'|'redacted';redactionIds?:string[];backup:WorkspaceBackup;imageHash:string}
export function normalizedMigrationPlan(state:WorkspaceState){const image=normalizeWorkspace(state,`migration_${digest(state).slice(0,32)}`);return {tenantId:state.tenantId,sourceVersion:state.version,sourceHash:digest(state),generation:image.head.generation,records:Object.fromEntries(NORMALIZED_COLLECTIONS.map(k=>[k,image.rows[k].length])),bytes:Buffer.byteLength(JSON.stringify(state)),unresolvedEffects:state.actions.filter(a=>['uncertain','dispatching','verifying'].includes(a.status)).map(a=>a.id),providerDispatches:0};}
/** Staging is restartable and inert. The majority transaction fences old writers before publishing the head. */
export async function migrateAggregateToNormalized(tenantId:string,expectedHash:string,dryRun=true){
 const db=await database(),aggregates=db.collection<Aggregate>('v2_workspaces'),aggregate=await aggregates.findOne({_id:tenantId});if(!aggregate)throw new V2Error('AGGREGATE_NOT_FOUND','Select an existing aggregate workspace.');const plan=normalizedMigrationPlan(aggregate.state);if(expectedHash!==plan.sourceHash)throw new V2Error('MIGRATION_SOURCE_CHANGED','Inspect the current aggregate before migration.');if(dryRun)return {...plan,dryRun:true};
 const migrationId=digest({tenantId,sourceHash:plan.sourceHash}),migrations=db.collection<Migration>('v2_normalized_migrations'),existing=await migrations.findOne({_id:migrationId});if(aggregate.storageFence){if(aggregate.storageFence.migrationId===migrationId&&existing?.status==='complete')return {...plan,dryRun:false,replayed:true};throw new V2Error('MIGRATION_FENCED','Aggregate is already owned by another normalized generation.');}
 await ensureNormalizedIndexes();if(existing?.status==='rolled_back')await migrations.updateOne({_id:migrationId,status:'rolled_back'},{$set:{status:'staging'}},{writeConcern:{w:'majority'}});const image=normalizeWorkspace(aggregate.state,plan.generation,migrationId),backup:WorkspaceBackup={format:'kiara-v2-backup',createdAt:new Date().toISOString(),hash:plan.sourceHash,state:structuredClone(aggregate.state)};
 await transaction(async(database,session)=>{const source=await database.collection<Aggregate>('v2_workspaces').findOne({_id:tenantId},{session});if(!source||source.storageFence||source.version!==plan.sourceVersion||digest(source.state)!==plan.sourceHash)throw new V2Error('MIGRATION_SOURCE_CHANGED','The source changed before staging.');
  // A real write on the canonical tenant arbiter serializes staging with deletion and aggregate writers.
  await database.collection('v2_workspaces').updateOne({_id:tenantId} as never,{$inc:{stagingVersion:1}},{session});
  const records=database.collection<Migration>('v2_normalized_migrations');await records.updateOne({_id:migrationId},{$setOnInsert:{tenantId,sourceVersion:plan.sourceVersion,sourceHash:plan.sourceHash,generation:plan.generation,status:'staging',backup,imageHash:digest(image)}},{upsert:true,session});const saved=await records.findOne({_id:migrationId},{session});if(!saved||saved.status==='redacted'||saved.imageHash!==digest(image)||saved.backup.hash!==digest(saved.backup.state))throw new V2Error('MIGRATION_INTEGRITY','Restarted staging does not match its retained backup.');
  for(const kind of NORMALIZED_COLLECTIONS)for(let n=0;n<image.rows[kind].length;n+=200)await database.collection<NormalizedRow>(`v2_records_${kind}`).bulkWrite(image.rows[kind].slice(n,n+200).map(row=>({updateOne:{filter:{_id:row._id},update:{$setOnInsert:row},upsert:true}})),{session});
 });
 await transaction(async(database,session)=>{const source=await database.collection<Aggregate>('v2_workspaces').findOne({_id:tenantId},{session});if(!source||source.storageFence||source.version!==plan.sourceVersion||digest(source.state)!==plan.sourceHash)throw new V2Error('MIGRATION_SOURCE_CHANGED','Aggregate changed while staging. Re-run a fresh dry run; no cutover occurred.');const rows={} as NormalizedImage['rows'];for(const kind of NORMALIZED_COLLECTIONS)rows[kind]=await database.collection<NormalizedRow>(`v2_records_${kind}`).find({tenantId,generation:plan.generation},{session}).sort({ordinal:1}).toArray();hydrateWorkspace({head:image.head,rows});const heads=database.collection<NormalizedHead>('v2_normalized_heads'),head=await heads.findOne({_id:tenantId},{session});if(head?.mode==='normalized')throw new V2Error('MIGRATION_HEAD_EXISTS','A normalized owner already exists.');const fenced=await database.collection<Aggregate>('v2_workspaces').updateOne({_id:tenantId,version:plan.sourceVersion,storageFence:{$exists:false}},{$set:{storageFence:{mode:'normalized',generation:plan.generation,migrationId}}},{session});if(!fenced.matchedCount)throw new V2Error('MIGRATION_SOURCE_CHANGED','Another writer changed the aggregate.');await heads.replaceOne({_id:tenantId},image.head,{upsert:true,session});await database.collection<Migration>('v2_normalized_migrations').updateOne({_id:migrationId,status:'staging'},{$set:{status:'complete'}},{session});});return {...plan,dryRun:false,replayed:false};
}
/** A downgrade copies the CURRENT state, including receipts/effects/revocations, never the old backup. */
export async function rollbackNormalizedToAggregate(tenantId:string,expectedHash:string,dryRun=true){return transaction(async(db,session)=>{const image=await load(db,tenantId,session);if(!image)throw new V2Error('NORMALIZED_NOT_FOUND','A normalized workspace is required.');const state=hydrateWorkspace(image);if(digest(state)!==expectedHash)throw new V2Error('VERSION_CONFLICT','Inspect the current normalized state before rollback.');validateWorkspace(state);const result={tenantId,version:state.version,stateHash:expectedHash,dryRun,preservedReceipts:Object.keys(state.receipts).length,providerDispatches:0};if(!dryRun){await db.collection<Aggregate>('v2_workspaces').replaceOne({_id:tenantId},{version:state.version,state},{upsert:true,session});await db.collection<NormalizedHead>('v2_normalized_heads').updateOne({_id:tenantId,version:state.version,stateHash:expectedHash,mode:'normalized'},{$set:{mode:'aggregate'}},{session});if(image.head.migrationId)await db.collection<Migration>('v2_normalized_migrations').updateOne({_id:image.head.migrationId},{$set:{status:'rolled_back'}},{session});}return result;});}
export interface HistoricalRedactors {redactRecord:(kind:string,value:unknown)=>unknown;redactWorkspace:(state:WorkspaceState)=>void}
/** Retention-only hook. Active records are already redacted in the canonical deletion transaction. */
export async function purgeNormalizedHistory(tenantId:string,deletionId:string,redactors:HistoricalRedactors){
 return transaction(async(db,session)=>{
  const markerId=digest({tenantId,deletionId}),markers=db.collection<{_id:string;tenantId:string;deletionId:string;status:'complete';records:number;archives:number}>('v2_normalized_redactions');const prior=await markers.findOne({_id:markerId},{session});if(prior)return {status:'complete' as const,records:prior.records,archives:prior.archives,replayed:true,externalBackupErasureVerified:false};
  const head=await db.collection<NormalizedHead>('v2_normalized_heads').findOne({_id:tenantId},{session});
  // These writes conflict with both a normal workspace mutation and migration staging/cutover.
  if(head)await db.collection('v2_normalized_heads').updateOne({_id:tenantId} as never,{$inc:{retentionEpoch:1}},{session});
  const aggregate=await db.collection<Aggregate>('v2_workspaces').findOne({_id:tenantId},{session});if(aggregate)await db.collection('v2_workspaces').updateOne({_id:tenantId} as never,{$inc:{retentionEpoch:1}},{session});
  const rows={} as NormalizedImage['rows'];const generations=new Set<string>();for(const kind of NORMALIZED_COLLECTIONS){rows[kind]=await db.collection<NormalizedRow>(`v2_records_${kind}`).find({tenantId,...(head?.mode==='normalized'?{generation:{$ne:head.generation}}:{})},{session}).toArray();for(const row of rows[kind])generations.add(row.generation);}
  let count=0;for(const generation of generations){const historical=emptyWorkspace(tenantId);for(const kind of NORMALIZED_COLLECTIONS){const selected=rows[kind].filter(r=>r.generation===generation).sort((a,b)=>a.ordinal-b.ordinal);if(kind==='receipts')historical.receipts=Object.fromEntries(selected.map(r=>[r.recordKey,structuredClone(r.value)])) as WorkspaceState['receipts'];else (historical as unknown as Record<string,unknown>)[kind]=selected.map(r=>redactors.redactRecord(kind,structuredClone(r.value)));}redactors.redactWorkspace(historical);
   for(const kind of NORMALIZED_COLLECTIONS){const selected=rows[kind].filter(r=>r.generation===generation).sort((a,b)=>a.ordinal-b.ordinal);for(const row of selected){const values=(historical as unknown as Record<string,unknown>)[kind];const value=kind==='receipts'?historical.receipts[row.recordKey]:(values as unknown[])[row.ordinal];if(value===undefined)throw new V2Error('HISTORICAL_REDACTION_IDENTITY','Historical redaction may not remove record identities.');const hash=digest(value);if(hash!==row.hash){await db.collection<NormalizedRow>(`v2_records_${kind}`).updateOne({_id:row._id,tenantId,generation,hash:row.hash},{$set:{value,hash}},{session});count++;}}}
  }
  let archives=0;for(const migration of await db.collection<Migration>('v2_normalized_migrations').find({tenantId},{session}).toArray()){const state=structuredClone(migration.backup.state);redactors.redactWorkspace(state);const hash=digest(state);if(hash!==migration.backup.hash){await db.collection<Migration>('v2_normalized_migrations').updateOne({_id:migration._id,tenantId},{$set:{backup:{...migration.backup,state,hash},status:'redacted'},$addToSet:{redactionIds:deletionId}},{session});archives++;}}
  // A frozen aggregate retained solely as a normalized ownership fence is also historical data.
  if(aggregate?.storageFence){const state=structuredClone(aggregate.state);redactors.redactWorkspace(state);if(digest(state)!==digest(aggregate.state)){await db.collection<Aggregate>('v2_workspaces').updateOne({_id:tenantId,storageFence:aggregate.storageFence},{$set:{state}},{session});archives++;}}
  await markers.insertOne({_id:markerId,tenantId,deletionId,status:'complete',records:count,archives},{session});return {status:'complete' as const,records:count,archives,replayed:false,externalBackupErasureVerified:false};
 });
}
