import {V2Error} from './contracts';
import {digest} from './store';
import {credential} from './integrations/config';
import type {NotificationGrant,NotificationDelivery} from './notifications';
export type NotificationFetch=typeof fetch;
export class NotificationRejected extends Error {}
export function notificationTransportReady(g:NotificationGrant){if(g.mode!=='resend')return;if(process.env.KIARA_ALLOW_LIVE_EMAIL!=='true'||!g.tokenEnv)throw new V2Error('LIVE_EMAIL_DISABLED','Live notification delivery is not enabled.',503);credential(g.tokenEnv);}
function payload(g:NotificationGrant,d:NotificationDelivery){return {from:g.from,to:[g.email],subject:'Review your Kiara workspace',text:`You have a workspace update to review. Sign in to Kiara to see your current permitted work.\n\n${g.appOrigin}/review/attention\n\nThis email does not authorize any action or confirm that work is complete. Manage notification preferences in your workspace.`,tags:[{name:'kiara_notification',value:d.id},{name:'kiara_intent',value:digest({id:d.id,tenantId:d.tenantId,ownerId:d.ownerId,grantHash:d.grantHash,kind:d.kind,window:d.window,itemKeys:d.itemKeys})}]};}
async function body(response:Response):Promise<any>{if(!response.body||Number(response.headers.get('content-length')||0)>200000)throw new V2Error('NOTIFICATION_RESPONSE_LIMIT','The provider response cannot be verified.',503);const reader=response.body.getReader(),parts:Uint8Array[]=[];let size=0;while(true){const part=await reader.read();if(part.done)break;size+=part.value.length;if(size>200000){await reader.cancel();throw new V2Error('NOTIFICATION_RESPONSE_LIMIT','The provider response cannot be verified.',503);}parts.push(part.value);}return JSON.parse(Buffer.concat(parts).toString('utf8'));}
export async function sendNotificationEmail(g:NotificationGrant,d:NotificationDelivery,fetcher:NotificationFetch=fetch):Promise<string>{
 notificationTransportReady(g);const response=await fetcher('https://api.resend.com/emails',{method:'POST',redirect:'error',signal:AbortSignal.timeout(15000),headers:{Authorization:`Bearer ${credential(g.tokenEnv!)}`,'Content-Type':'application/json','Idempotency-Key':'kiara-notification-'+d.id},body:JSON.stringify(payload(g,d))});
 if([400,401,403,404,422,429].includes(response.status))throw new NotificationRejected('The provider rejected this notification.');if(!response.ok)throw new V2Error('NOTIFICATION_OUTCOME_UNKNOWN','The provider outcome is uncertain.',503);const value=await body(response);if(typeof value.id!=='string'||!/^[A-Za-z0-9_-]{1,200}$/.test(value.id))throw new V2Error('NOTIFICATION_OUTCOME_UNKNOWN','The provider outcome is uncertain.',503);return value.id;
}
export async function readNotificationEmail(g:NotificationGrant,d:NotificationDelivery,receipt:string,fetcher:NotificationFetch=fetch):Promise<{matches:boolean;status:'accepted'|'delivered'|'failed'}>{
 if(g.mode!=='resend'||!g.tokenEnv)throw new V2Error('NOTIFICATION_READBACK_UNAVAILABLE','A configured provider is required to reconcile email delivery.',503);const response=await fetcher(`https://api.resend.com/emails/${encodeURIComponent(receipt)}`,{method:'GET',redirect:'error',signal:AbortSignal.timeout(15000),headers:{Authorization:`Bearer ${credential(g.tokenEnv)}`}});if(!response.ok)throw new V2Error('NOTIFICATION_READBACK_UNAVAILABLE','Email delivery read-back is unavailable; no resend is authorized.',503);
 // Retrieve-email omits tags and attachments. The original dispatch receipt binds the immutable intent.
 const value=await body(response),expected=payload(g,d),matches=value.id===receipt&&value.from===expected.from&&digest(value.to)===digest(expected.to)&&value.subject===expected.subject&&value.text===expected.text&&!value.cc?.length&&!value.bcc?.length&&(value.html===undefined||value.html===null||value.html==='')&&(value.attachments===undefined||Array.isArray(value.attachments)&&value.attachments.length===0);
 if(!matches)return {matches:false,status:'accepted'};
 const attachmentsResponse=await fetcher(`https://api.resend.com/emails/${encodeURIComponent(receipt)}/attachments`,{method:'GET',redirect:'error',signal:AbortSignal.timeout(15000),headers:{Authorization:`Bearer ${credential(g.tokenEnv)}`}});
 if(!attachmentsResponse.ok)throw new V2Error('NOTIFICATION_READBACK_UNAVAILABLE','Attachment read-back is unavailable; no resend is authorized.',503);
 const attachments=await body(attachmentsResponse);
 return {matches:attachments?.object==='list'&&attachments.has_more===false&&Array.isArray(attachments.data)&&attachments.data.length===0,status:['bounced','failed','complained','canceled','suppressed'].includes(value.last_event)?'failed':['delivered','opened','clicked'].includes(value.last_event)?'delivered':'accepted'};
}
