import {randomUUID} from 'node:crypto';
import {canRead,membership,readRecord,requireRole} from './authority';
import {attentionView,type AttentionItem} from './attention';
import {digest,readWorkspace,timestamp,transactWorkspace} from './store';
import {V2Error,type ActorContext,type RecordBase,type WorkspaceState} from './contracts';
import {sendNotificationEmail,readNotificationEmail,notificationTransportReady,type NotificationFetch,NotificationRejected} from './notification-delivery';

export interface NotificationGrant {tenantId:string;actorId:string;email:string;from:string;tokenEnv?:string;mode:'preview'|'resend';appOrigin:string;validUntil:string}
export interface NotificationEnrollment extends RecordBase {ownerId:string;mode:'off'|'digest'|'required_and_digest';grantHash:string|null;membershipVersion:number;active:boolean}
export interface NotificationDelivery extends RecordBase {ownerId:string;enrollmentId:string;grantHash:string;identityHash?:string;membershipVersion:number;kind:'required'|'digest';window:string;itemKeys:string[];status:'prepared'|'sending'|'accepted'|'delivered'|'unknown'|'failed'|'canceled'|'preview';providerReceipt:string|null;reason:string|null;leaseToken:string|null;leaseUntil:number|null;dispatchedAt:string|null;dispatchToken:string|null;completedAt:string|null}
type State=WorkspaceState&{notificationEnrollments?:NotificationEnrollment[];notificationDeliveries?:NotificationDelivery[]};
export type NotificationCommand={type:'notification.configure';expectedRecordVersion:number;mode:NotificationEnrollment['mode'];expectedGrantHash:string|null};
export const notificationCommandFields={'notification.configure':['expectedRecordVersion','mode','expectedGrantHash']};
const ensure=(v:unknown,code:string,message:string,status=409)=>{if(!v)throw new V2Error(code,message,status);};
const badConfig=()=>new V2Error('NOTIFICATION_NOT_CONFIGURED','A current operator-verified email identity and application origin are required.',503);
/** Protected operator identity binding; a typed email address never establishes a recipient. */
export function notificationGrant(tenantId:string,actorId:string):NotificationGrant {
 let values:NotificationGrant[];try{values=JSON.parse(process.env.KIARA_V2_NOTIFICATION_GRANTS||'[]');}catch{throw badConfig();}
 if(!Array.isArray(values)||values.length>1000)throw badConfig();const matches=values.filter(x=>x&&x.tenantId===tenantId&&x.actorId===actorId);if(matches.length!==1)throw badConfig();const g=matches[0];
 if(!['preview','resend'].includes(g.mode)||![g.email,g.from].every(x=>typeof x==='string'&&x.length<=254&&/^[^\s<>@]+@[^\s<>@]+\.[^\s<>@]+$/.test(x))||!Number.isFinite(Date.parse(g.validUntil))||Date.parse(g.validUntil)<=Date.now())throw badConfig();
 try{const u=new URL(g.appOrigin),local=['localhost','127.0.0.1','[::1]'].includes(u.hostname);if(u.username||u.password||u.hash||u.search||u.pathname!=='/'||u.origin!==g.appOrigin||u.protocol!=='https:'&&!(g.mode==='preview'&&u.protocol==='http:'&&local))throw badConfig();}catch{throw badConfig();}
 if(g.mode==='resend'&&(!g.tokenEnv||!/^[A-Z][A-Z0-9_]{0,100}$/.test(g.tokenEnv)||/\.test$/i.test(g.email)))throw badConfig();return structuredClone(g);
}
function identityHash(g:NotificationGrant){return digest({email:g.email,from:g.from,mode:g.mode,appOrigin:g.appOrigin});}
function sameIdentity(d:NotificationDelivery,g:NotificationGrant){return d.identityHash?d.identityHash===identityHash(g):d.grantHash===digest(g);}
function latest(s:State,ownerId:string){return [...s.notificationEnrollments||[]].reverse().find(x=>x.ownerId===ownerId)||null;}
function actorFor(s:State,e:NotificationEnrollment):ActorContext{return {tenantId:s.tenantId,actorId:e.ownerId,mode:'authenticated',expiresAt:Date.now()+60000};}
function admitted(s:State,e:NotificationEnrollment){const a=actorFor(s,e),member=membership(s,a);ensure(latest(s,e.ownerId)?.id===e.id&&e.active&&e.mode!=='off','NOTIFICATION_OPTED_OUT','Email notifications are disabled.');ensure(member.version===e.membershipVersion,'NOTIFICATION_AUTHORITY_CHANGED','Review notification enrollment after membership changes.');const grant=notificationGrant(s.tenantId,e.ownerId);ensure(digest(grant)===e.grantHash,'NOTIFICATION_GRANT_CHANGED','Review the current configured recipient before enabling notifications.');return {actor:a,grant};}
const base=(s:State,a:ActorContext):RecordBase=>({id:randomUUID(),tenantId:s.tenantId,version:1,createdAt:timestamp(),updatedAt:timestamp(),scope:{kind:'private',actorIds:[a.actorId]},provenance:{actorId:a.actorId,sourceIds:[],factIds:[],description:'Private notification enrollment or generic authenticated review-link delivery.'}});
/** A semantic condition key deliberately excludes unrelated matter-version changes. */
export function notificationItemKey(item:AttentionItem){return digest({id:item.id,kind:item.kind,title:item.title,detail:item.detail,required:item.required,decisionRequired:item.decisionRequired,dueAt:item.dueAt,deadlineType:item.deadlineType,ownerId:item.ownerId});}
function localWindow(timezone:string,now:number){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(now);return ['year','month','day'].map(k=>parts.find(p=>p.type===k)!.value).join('-')+':'+timezone;}
function itemRecord(s:State,a:ActorContext,item:AttentionItem):RecordBase {
 const record=item.kind==='task'||item.kind==='update'?s.matters.find(x=>x.id===item.matterId):item.kind==='obligation'?(s.obligations||[]).find(x=>x.id===item.recordId):item.kind==='effect'?s.actions.find(x=>x.id===item.recordId):item.kind==='counsel'?s.counsel.find(x=>x.id===item.recordId):s.coverage.find(x=>x.id===item.recordId);
 ensure(record&&canRead(s,a,record),'NOTIFICATION_SOURCE_CHANGED','Notification eligibility changed.');return record!;
}
export interface NotificationView {enrollment:NotificationEnrollment|null;configuration:{available:boolean;reason:string|null;email:string|null;mode:'preview'|'resend'|null;grantHash:string|null;reviewUrl:string|null};effective:boolean;deliveries:{id:string;version:number;kind:NotificationDelivery['kind'];status:NotificationDelivery['status'];createdAt:string;completedAt:string|null;reason:string|null;hasReceipt:boolean}[]}
export function notificationView(s:State,a:ActorContext):NotificationView {
 membership(s,a);const e=latest(s,a.actorId);let configuration:NotificationView['configuration']={available:false,reason:'NOTIFICATION_NOT_CONFIGURED',email:null,mode:null,grantHash:null,reviewUrl:null},effective=false;
 try{const g=notificationGrant(s.tenantId,a.actorId);configuration={available:true,reason:null,email:g.email,mode:g.mode,grantHash:digest(g),reviewUrl:g.appOrigin+'/review/attention'};if(e){admitted(s,e);effective=true;}}catch(error){if(e?.active)configuration.reason=error instanceof V2Error?error.code:'NOTIFICATION_UNAVAILABLE';}
 return {enrollment:e&&canRead(s,a,e)?structuredClone(e):null,configuration,effective,deliveries:[...s.notificationDeliveries||[]].reverse().filter(d=>d.ownerId===a.actorId&&canRead(s,a,d)).slice(0,50).map(d=>({id:d.id,version:d.version,kind:d.kind,status:d.status,createdAt:d.createdAt,completedAt:d.completedAt,reason:d.reason,hasReceipt:!!d.providerReceipt}))};
}
export function applyNotificationCommand(s:State,a:ActorContext,c:NotificationCommand):Record<string,unknown>{
 const member=requireRole(s,a,'member'),prior=latest(s,a.actorId);ensure(Number.isSafeInteger(c.expectedRecordVersion)&&c.expectedRecordVersion===(prior?.version||0),'VERSION_CONFLICT','Inspect current notification preferences.');ensure(['off','digest','required_and_digest'].includes(c.mode),'INVALID_NOTIFICATION_MODE','Choose off, daily digest, or required alerts and digest.');const g=c.mode==='off'?null:notificationGrant(s.tenantId,a.actorId);ensure(!g||digest(g)===c.expectedGrantHash,'NOTIFICATION_GRANT_CHANGED','Inspect the exact recipient and delivery mode.');const version=(prior?.version||0)+1;if(prior){prior.active=false;prior.version++;prior.updatedAt=timestamp();}
 const e:NotificationEnrollment={...base(s,a),version,ownerId:a.actorId,mode:c.mode,grantHash:g?digest(g):null,membershipVersion:member.version,active:c.mode!=='off'};(s.notificationEnrollments||=[]).push(e);
 for(const d of s.notificationDeliveries||[])if(d.ownerId===a.actorId&&d.status==='prepared'){d.status='canceled';d.reason='NOTIFICATION_ENROLLMENT_CHANGED';d.version++;d.updatedAt=timestamp();}
 if(e.active)s.outbox.push({id:randomUUID(),tenantId:s.tenantId,kind:'notification_watch' as WorkspaceState['outbox'][number]['kind'],aggregateId:e.id,commandId:e.id,status:'pending',owner:'v2',createdAt:timestamp()});return {enrollmentId:e.id,enabled:e.active};
}
function stillEligible(s:State,d:NotificationDelivery){const e=(s.notificationEnrollments||[]).find(x=>x.id===d.enrollmentId);ensure(e,'NOTIFICATION_OPTED_OUT','Notification enrollment is unavailable.');const {actor,grant}=admitted(s,e!);ensure(d.grantHash===digest(grant)&&d.membershipVersion===membership(s,actor).version&&canRead(s,actor,d),'NOTIFICATION_AUTHORITY_CHANGED','Notification authority changed.');const view=attentionView(s,actor),current=view.items.filter(x=>!x.acknowledged&&(d.kind==='digest'||x.required));ensure(d.itemKeys.every(key=>current.some(item=>notificationItemKey(item)===key)),'NOTIFICATION_SOURCE_CHANGED','Review need changed before delivery.');if(d.kind==='digest')ensure(view.digestReady,'NOTIFICATION_DEFERRED','Wait for the configured digest window.');return {actor,grant};}
function get(s:State,id:string){const d=(s.notificationDeliveries||[]).find(x=>x.id===id);if(!d)throw new V2Error('NOT_FOUND','Notification receipt is unavailable.',404);return d;}
function setStatus(d:NotificationDelivery,status:NotificationDelivery['status'],reason:string|null){d.status=status;d.reason=reason;d.version++;d.updatedAt=timestamp();if(['delivered','failed','canceled','preview'].includes(status))d.completedAt=timestamp();d.leaseToken=null;d.leaseUntil=null;}
/** No payload, token, or email address appears in workflow references. */
export async function processNotificationWatch(tenantId:string,enrollmentId:string,options:{fetcher?:NotificationFetch;now?:number}={}):Promise<{status:'active'|'stopped'|'blocked';nextCheckMs:number}> {
 const now=options.now??Date.now();let ids:string[]=[];
 try{const admission=await transactWorkspace(tenantId,(s:State)=>{const e=(s.notificationEnrollments||[]).find(x=>x.id===enrollmentId);if(!e||!e.active||latest(s,e.ownerId)?.id!==e.id)return null;const {actor,grant}=admitted(s,e),view=attentionView(s,actor,now),available=view.items.filter(i=>!i.acknowledged),deliveries=s.notificationDeliveries||=[];const make=(kind:NotificationDelivery['kind'],items:AttentionItem[],window:string)=>{if(!items.length)return;const keys=items.map(notificationItemKey).sort();if(deliveries.some(d=>d.ownerId===e.ownerId&&!d.identityHash&&['unknown','sending','accepted'].includes(d.status)&&d.kind===kind&&(kind==='digest'?d.window===window:keys.every(key=>d.itemKeys.includes(key)))))return;const dedupe=digest({ownerId:e.ownerId,identityHash:identityHash(grant),kind,window,...(kind==='required'?{keys}:{})});const priorId=s.receipts['notification:'+dedupe]?.result.notificationId,prior=deliveries.find(d=>d.id===priorId);if(priorId&&!(prior?.status==='canceled'&&!prior.dispatchedAt))return;const records=items.map(item=>itemRecord(s,actor,item)),d:NotificationDelivery={...base(s,actor),ownerId:e.ownerId,enrollmentId:e.id,grantHash:digest(grant),identityHash:identityHash(grant),membershipVersion:e.membershipVersion,kind,window,itemKeys:keys,status:'prepared',providerReceipt:null,reason:null,leaseToken:null,leaseUntil:null,dispatchedAt:null,dispatchToken:null,completedAt:null};d.provenance.sourceIds=[...new Set(records.flatMap(r=>r.provenance.sourceIds))];d.provenance.factIds=[...new Set(records.flatMap(r=>r.provenance.factIds||[]))];deliveries.push(d);s.outbox.push({id:randomUUID(),tenantId:s.tenantId,kind:'notification_delivery' as WorkspaceState['outbox'][number]['kind'],aggregateId:d.id,commandId:d.id,status:'pending',owner:'v2',createdAt:timestamp()});s.receipts['notification:'+dedupe]={hash:dedupe,result:{notificationId:d.id}};};
  if(e.mode==='required_and_digest'){const required=available.filter(i=>i.required).filter(i=>!deliveries.some(d=>d.ownerId===e.ownerId&&sameIdentity(d,grant)&&d.kind==='required'&&d.itemKeys.includes(notificationItemKey(i))&&d.status!=='canceled'));for(const item of required.slice(0,10))make('required',[item],'condition');}
  if(view.digestReady){const window=localWindow(view.settings?.timezone||'UTC',now),alreadyAlerted=new Set(deliveries.filter(d=>d.ownerId===e.ownerId&&d.kind==='required'&&d.status!=='canceled'&&localWindow(view.settings?.timezone||'UTC',Date.parse(d.createdAt))===window).flatMap(d=>d.itemKeys));make('digest',available.filter(item=>!alreadyAlerted.has(notificationItemKey(item))).slice(0,100),window);}return deliveries.filter(d=>d.ownerId===e.ownerId&&d.enrollmentId===e.id&&['prepared','sending'].includes(d.status)).slice(0,20).map(d=>d.id);
 });if(admission.result===null)return {status:'stopped',nextCheckMs:0};ids=admission.result;
 }catch{return {status:'blocked',nextCheckMs:60000};}
 for(const id of ids)await processNotificationDelivery(tenantId,id,options);return {status:'active',nextCheckMs:60000};
}
/** Durable dispatch admission occurs once. Expired sending leases become unknown, never resend. */
export async function processNotificationDelivery(tenantId:string,id:string,options:{fetcher?:NotificationFetch;beforeDispatch?:()=>Promise<void>}={}):Promise<void>{
 const token=randomUUID();let outgoing:{grant:NotificationGrant;delivery:NotificationDelivery}|null=null;
 try{const claim=await transactWorkspace(tenantId,(s:State)=>{const d=get(s,id);if(d.status==='sending'){if(d.leaseUntil&&d.leaseUntil>Date.now())return null;setStatus(d,'unknown','DELIVERY_UNKNOWN');return null;}if(d.status!=='prepared'||d.leaseUntil&&d.leaseUntil>Date.now())return null;const {grant}=stillEligible(s,d);d.leaseToken=token;d.leaseUntil=Date.now()+30000;return {grant,delivery:structuredClone(d)};});outgoing=claim.result;
  if(outgoing){if(outgoing.grant.mode==='preview'){await transactWorkspace(tenantId,(s:State)=>{const d=get(s,id);if(d.leaseToken===token&&d.status==='prepared'){stillEligible(s,d);setStatus(d,'preview','PREVIEW_NOT_DELIVERY');}});return;}
   notificationTransportReady(outgoing.grant);
   await options.beforeDispatch?.();
   const admittedSend=await transactWorkspace(tenantId,(s:State)=>{const d=get(s,id);ensure(d.status==='prepared'&&d.leaseToken===token&&!!d.leaseUntil&&d.leaseUntil>Date.now(),'NOTIFICATION_LEASE','Notification lease changed.');const {grant}=stillEligible(s,d);ensure(digest(grant)===digest(outgoing!.grant),'NOTIFICATION_GRANT_CHANGED','Recipient configuration changed.');d.status='sending';d.dispatchToken=token;d.dispatchedAt=timestamp();d.version++;d.updatedAt=timestamp();return {grant,delivery:structuredClone(d)};});
   try{const receipt=await sendNotificationEmail(admittedSend.result.grant,admittedSend.result.delivery,options.fetcher);await transactWorkspace(tenantId,(s:State)=>{const d=get(s,id);if(d.dispatchToken===token&&['sending','unknown'].includes(d.status)&&(!d.providerReceipt||d.providerReceipt===receipt)){d.providerReceipt=receipt;setStatus(d,'accepted','DELIVERY_PENDING');}});}catch(error){await transactWorkspace(tenantId,(s:State)=>{const d=get(s,id);if(d.dispatchToken===token&&['sending','unknown'].includes(d.status)&&!d.providerReceipt)setStatus(d,error instanceof NotificationRejected?'failed':'unknown',error instanceof NotificationRejected?'PROVIDER_REJECTED':'DELIVERY_UNKNOWN');});}
  }
  const current=get(await readWorkspace(tenantId),id);if(current.providerReceipt&&['accepted','unknown'].includes(current.status))await reconcileNotificationDelivery(tenantId,id,current.providerReceipt,options);
 }catch(error){await transactWorkspace(tenantId,(s:State)=>{const d=get(s,id);if(d.status==='prepared'&&(!d.leaseToken||d.leaseToken===token)){if(error instanceof V2Error&&['NOTIFICATION_DEFERRED','LIVE_EMAIL_DISABLED','CONNECTION_UNAVAILABLE'].includes(error.code)){d.leaseToken=null;d.leaseUntil=null;d.reason=error.code;}else setStatus(d,'canceled',error instanceof V2Error?error.code:'NOTIFICATION_UNAVAILABLE');}});}
}
/** Read-only provider verification may attach a lost receipt, but cannot authorize another send. */
export async function reconcileNotificationDelivery(tenantId:string,id:string,receipt:string,options:{fetcher?:NotificationFetch;actor?:ActorContext;expectedVersion?:number}={}):Promise<void>{
 ensure(typeof receipt==='string'&&/^[A-Za-z0-9_-]{1,200}$/.test(receipt),'INVALID_PROVIDER_RECEIPT','Provide the exact provider email receipt.');const s=await readWorkspace(tenantId) as State,d=get(s,id);if(options.actor){membership(s,options.actor);ensure(d.ownerId===options.actor.actorId&&canRead(s,options.actor,d),'NOT_FOUND','This notification is unavailable.',404);ensure(d.version===options.expectedVersion,'VERSION_CONFLICT','Inspect current delivery status.');}
 if(!['accepted','unknown'].includes(d.status))return;const e=(s.notificationEnrollments||[]).find(x=>x.id===d.enrollmentId);ensure(e,'NOTIFICATION_UNAVAILABLE','The retained enrollment is unavailable.');const actor=actorFor(s,e!),member=membership(s,actor),g=notificationGrant(tenantId,d.ownerId);ensure(sameIdentity(d,g)&&canRead(s,actor,d),'NOTIFICATION_AUTHORITY_CHANGED','Read-back authority changed.');const result=await readNotificationEmail(g,d,receipt,options.fetcher);
 await transactWorkspace(tenantId,(current:State)=>{const retained=get(current,id);if(!['accepted','unknown'].includes(retained.status))return;ensure(membership(current,actor).version===member.version&&digest(notificationGrant(tenantId,d.ownerId))===digest(g)&&sameIdentity(retained,g)&&canRead(current,actor,retained),'NOTIFICATION_AUTHORITY_CHANGED','Read-back authority changed.');if(options.actor)readRecord(current,options.actor,current.notificationDeliveries||[],id);ensure(!retained.providerReceipt||retained.providerReceipt===receipt,'NOTIFICATION_RECEIPT_CHANGED','Another receipt was already retained.');if(!result.matches)throw new V2Error('NOTIFICATION_READBACK_MISMATCH','Provider receipt does not match this exact generic notification.');retained.providerReceipt=receipt;setStatus(retained,result.status,result.status==='accepted'?'DELIVERY_PENDING':result.status==='failed'?'DELIVERY_FAILED':null);});
}

export async function notificationDeliveryProgress(tenantId:string,id:string){const d=get(await readWorkspace(tenantId),id);return {status:d.status,nextCheckMs:d.status==='prepared'?60000:d.status==='sending'?Math.max(1000,(d.leaseUntil||Date.now())-Date.now()+1000):d.status==='accepted'?300000:d.status==='unknown'?21600000:0};}
