import {applyInventoryCommand,inventoryCommandFields,inventoryCandidates,inventoryViews,currentInventory,inventoryBinding,assertProposalInventory,type InventoryCommand} from './inventory';
import {indexRecordFingerprints,enqueueIndexMaintenance,indexingViews} from './index-maintenance';
import {scenarioShareViews,routingDelegationViews,routingRuleViews,routedMatterViews,collaborationCommandFields,applyCollaborationCommand,type CollaborationCommand} from './collaboration';
import {applySourceDeletion,deletionViews,assertOriginalNotDeleted} from './retention';
import {documentHeads,applyDocumentCommand,documentCommandFields,type DocumentCommand} from './document-lifecycle';
import {recoveryViews,applyRecoveryCommand,recoveryCommandFields,mayDeleteRemovedSource} from './recovery';
import {factCurrentlyConfirmed} from './fact-validity';
import {applyMeasurementCommand,measurementCommandFields,effortComparisons,type MeasurementCommand} from './measurement';
import {applyObligationCommand,obligationCommandFields,obligationViews,assertObligationsReady,type ObligationCommand} from './obligations';
import {sourceInstallationEligible} from './integrations/config';
import {randomUUID} from 'node:crypto';
import {V2Error, type Action, type ActorContext, type Approval, type CommandEnvelope, type CommandResult, type Conversation, type DependencySnapshot, type FactAssertion, type Json, type Matter, type Message, type Proposal, type RecordBase, type Role, type Scope, type Source, type WorkspaceCommand, type WorkspaceSnapshot, type WorkspaceState} from './contracts';
import {canRead, membership, readRecord, requestedScope, requireRole} from './authority';
import {digest, readWorkspace, timestamp, transactWorkspace} from './store';
import {applyCounselCommand,counselCommandFields,prepareCounselRequest,type CounselCommand} from './counsel';
import {counselPacketHash,advancePacketReviewState} from './sharing';
import {conversationAIMode,conversationRunViews,enqueueConversationRun} from './ai';
import {resetReviewTasks} from './tasks';
import {PROCEDURES,procedureInput,procedureAssessment,evaluateProcedure,learningViews} from './procedures';
import {applyCoverageCommand,coverageCommandFields,coverageViews} from './coverage';

const roles:Role[]=['member','fact_owner','business_owner','legal_reviewer','publisher','signatory','admin','evaluator','integration'];
function ensure(value:unknown,code:string,message:string,status=409):asserts value {if(!value)throw new V2Error(code,message,status);}
function text(value:unknown,name:string,max=12000){ensure(typeof value==='string'&&value.trim().length>0&&value.length<=max,'INVALID_INPUT',`Provide ${name} (up to ${max} characters).`,400);return value.trim();}
function version(record:RecordBase,expected:number){ensure(record.version===expected,'VERSION_CONFLICT','This record changed. Refresh and review the current version.');}
function touch(record:RecordBase){record.version++;record.updatedAt=timestamp();}
function base(s:WorkspaceState,a:ActorContext,scope:Scope,sourceIds:string[]=[],description='Attributed user command'):RecordBase {return {id:randomUUID(),tenantId:s.tenantId,version:1,createdAt:timestamp(),updatedAt:timestamp(),scope:structuredClone(scope),provenance:{actorId:a.actorId,sourceIds:[...new Set(sourceIds)],description}};}
function bootstrap(s:WorkspaceState,a:ActorContext){ensure(a.tenantId===s.tenantId&&a.expiresAt>Date.now(),'SESSION_EXPIRED','Sign in again.',401);if(!s.memberships.some(m=>m.actorId===a.actorId)&&a.mode==='local_demo'){ensure(a.bootstrapRoles?.length&&a.bootstrapRoles.every(r=>roles.includes(r)),'MEMBERSHIP_REQUIRED','Local role profile is not configured.',403);s.memberships.push({actorId:a.actorId,roles:[...a.bootstrapRoles],version:1,expiresAt:null,revokedAt:null,matterIds:null,entityIds:null});}return membership(s,a);}
function activity(s:WorkspaceState,a:ActorContext,type:string,title:string,detail:string,record?:RecordBase,matterId:string|null=null){s.events.push({...base(s,a,record?.scope||{kind:'private',actorIds:[a.actorId]},record?.provenance.sourceIds),type,title,detail,matterId,recordId:record?.id||null,measurement:s.rehearsal?'fictional_rehearsal':'observed'});}
function queue(s:WorkspaceState,aggregateId:string,commandId:string){if(!s.outbox.some(o=>o.aggregateId===aggregateId&&o.commandId===commandId))s.outbox.push({id:randomUUID(),tenantId:s.tenantId,kind:'matter_changed',aggregateId,commandId,status:'pending',owner:'v2',createdAt:timestamp()});}
function sourceIds(s:WorkspaceState,a:ActorContext,ids:string[]=[]){ensure(Array.isArray(ids)&&ids.length<=100,'INVALID_INPUT','Provide at most 100 sources.',400);return [...new Set(ids.map(id=>readRecord(s,a,s.sources,id).id))];}
function createConversation(s:WorkspaceState,a:ActorContext,title='A new conversation',scope?:Scope,reuse:Conversation['reuse']='propose_memory'){const c:Conversation={...base(s,a,requestedScope(s,a,scope)),title:text(title,'a conversation title',200),entityId:s.entityId,reuse,matterId:null,scenarioId:null};s.conversations.push(c);return c;}
function createMatter(s:WorkspaceState,a:ActorContext,title:string,objective:string,scope:Scope,conversationId?:string,scenarioId?:string){requireRole(s,a,'business_owner');const m:Matter={...base(s,a,scope),title:text(title,'a matter title',200),objective:text(objective,'an objective',5000),entityId:s.entityId,state:'needs_facts',ownerId:a.actorId,conversationIds:conversationId?[conversationId]:[],scenarioId:scenarioId||null,eventIds:[],sourceIds:[],factIds:[],documentIds:[],proposalId:null,tasks:[{id:randomUUID(),title:'Confirm the intended business change and factual scope',ownerId:a.actorId,status:'pending',kind:'fact',dueAt:null,deadlineType:'undated',evidenceIds:[]}],blockers:['Confirm relevant facts and select authoritative documents.'],outcome:null,closedAt:null,ruleVersion:s.ruleVersion,correlationKeys:[]};s.matters.push(m);if(conversationId){const c=readRecord(s,a,s.conversations,conversationId);c.matterId=m.id;touch(c);}return m;}
function deps(s:WorkspaceState,m:Matter):DependencySnapshot {const sources=m.sourceIds.map(id=>s.sources.find(x=>x.id===id)).filter((x):x is Source=>!!x);return {sourceVersions:Object.fromEntries(sources.map(x=>[x.id,x.version])),factVersions:Object.fromEntries(m.factIds.map(id=>s.facts.find(x=>x.id===id)).filter((x):x is FactAssertion=>!!x).map(x=>[x.id,x.version])),documentHashes:Object.fromEntries(m.documentIds.map(id=>s.documents.find(x=>x.id===id)).filter(x=>!!x).map(x=>[x.id,x.contentHash])),policyVersion:s.ruleVersion,scopeHash:digest(m.scope)};}
function fresh(s:WorkspaceState,a:ActorContext,p:Proposal){assertProposalInventory(s,p);const m=readRecord(s,a,s.matters,p.matterId);ensure(!['closed','canceled'].includes(m.state),'MATTER_TERMINAL','Open corrective work for a closed or canceled matter.');ensure(!m.legacyWorkflowId,'LEGACY_EXECUTION_OWNER','Imported work remains owned by the legacy engine.');ensure(p.status==='current'&&m.proposalId===p.id,'STALE_PROPOSAL','Open and review the current proposal.');ensure(digest(p.dependencies)===digest(deps(s,m)),'DEPENDENCIES_CHANGED','Facts, sources, documents or rules changed. Prepare and review a new proposal.');for(const id of Object.keys(p.dependencies.sourceVersions))readRecord(s,a,s.sources,id);for(const id of Object.keys(p.dependencies.factVersions))ensure(factCurrentlyConfirmed(readRecord(s,a,s.facts,id)),'FACT_VALIDITY_CHANGED','A bound fact is no longer current. Prepare and review a new proposal.');ensure(!procedureAssessment(s,a,m).blockers.length,'PROCEDURE_REQUIREMENTS_PENDING','The approved procedure requires current evidence or owner review before this decision.');return m;}
function invalidate(s:WorkspaceState,reason:string,sourceId?:string){for(const p of s.proposals.filter(p=>p.status==='current'&&(!sourceId||p.provenance.sourceIds.includes(sourceId)))){p.status='invalidated';touch(p);for(const approval of s.approvals.filter(x=>x.proposalId===p.id&&x.status==='active')){approval.status='invalidated';touch(approval);}const m=s.matters.find(x=>x.id===p.matterId);if(m&&!['canceled'].includes(m.state)){m.state='needs_facts';m.closedAt=null;m.outcome=null;m.blockers=[reason];resetReviewTasks(s,m,p);touch(m);}for(const action of s.actions.filter(x=>x.proposalId===p.id&&!['verified','uncertain','dispatching'].includes(x.status))){action.status='planned';action.authorizationId=null;touch(action);}}}
function approvalValid(s:WorkspaceState,p:Proposal,capacity:Approval['capacity']){return s.approvals.some(x=>{const member=s.memberships.find(m=>m.actorId===x.actorId);return x.proposalId===p.id&&x.proposalHash===p.contentHash&&x.capacity===capacity&&x.conditions.length===0&&x.status==='active'&&Date.parse(x.validUntil)>Date.now()&&digest(x.dependencies)===digest(p.dependencies)&&member&&!member.revokedAt&&(!member.expiresAt||Date.parse(member.expiresAt)>Date.now())&&member.version===x.membershipVersion;});}
function dateFuture(value:string){ensure(typeof value==='string'&&Number.isFinite(Date.parse(value))&&Date.parse(value)>Date.now()&&Date.parse(value)<=Date.now()+30*86400000,'INVALID_EXPIRY','Choose an approval expiry within the next 30 days.',400);return new Date(value).toISOString();}
const capacityRole:Record<Approval['capacity'],Role>={business:'business_owner',legal:'legal_reviewer',sharing:'business_owner',publication:'publisher',signature:'signatory',no_action:'business_owner'};
function addApproval(s:WorkspaceState,a:ActorContext,p:Proposal,capacity:Approval['capacity'],validUntil:string,options:Partial<Approval>={}){ensure(Object.hasOwn(capacityRole,capacity),'INVALID_CAPACITY','Choose a specific decision capacity.',400);const member=requireRole(s,a,capacityRole[capacity],p);fresh(s,a,p);const approval:Approval={...base(s,a,p.scope,p.provenance.sourceIds),matterId:p.matterId,proposalId:p.id,proposalHash:p.contentHash,actionId:null,actionHash:null,capacity,actorId:a.actorId,membershipVersion:member.version,dependencies:structuredClone(p.dependencies),conditions:[],recipients:[],destination:null,validUntil:dateFuture(validUntil),status:'active',note:'',...options};approval.provenance.factIds=p.provenance.factIds||[];s.approvals.push(approval);return approval;}
function usefulAnswer(s:WorkspaceState,a:ActorContext,c:Conversation,prompt:string):{text:string;citations:Message['citations'];sourceIds:string[];factIds?:string[]}{
 const available=documentHeads(s.documents).filter(d=>canRead(s,a,d)&&s.sources.some(x=>x.id===d.sourceId&&x.status==='active'));
 const terms=prompt.toLowerCase().split(/\W+/).filter(t=>t.length>3);const ranked=available.map(d=>({d,score:terms.filter(t=>`${d.title} ${d.body}`.toLowerCase().includes(t)).length})).sort((x,y)=>y.score-x.score);
 const chosen=ranked.some(x=>x.score>0)?ranked.filter(x=>x.score>0).slice(0,3):ranked.length===1?ranked:[];const citations=chosen.map(({d})=>({sourceId:d.sourceId,anchor:`document:${d.id}`,quote:d.body.slice(0,700)}));
 const confirmed=s.facts.filter(f=>factCurrentlyConfirmed(f)&&f.reuse==='company'&&canRead(s,a,f)&&(!f.validUntil||Date.parse(f.validUntil)>Date.now()));
 const concise=s.preferences.some(p=>p.active&&p.ownerId===a.actorId&&p.key==='response_length'&&/short|concise|brief/i.test(p.value));
 let answer=chosen.length?`Here is the relevant wording from ${chosen.map(x=>x.d.title).join(', ')}:\n\n${citations.map(x=>`“${x.quote}”`).join('\n\n')}\n\nCheck the defined terms, exceptions and any amendments before relying on an isolated passage.`:'Start with the intended purpose, the information or commitments involved, and who will receive or rely on them. Separate your current practice from the change you are considering.';
 if(confirmed.length)answer+=`\n\nConfirmed company context: ${confirmed.slice(0,concise?2:5).map(f=>`${f.predicate}: ${typeof f.value==='string'?f.value:JSON.stringify(f.value)} (${f.practice})`).join('; ')}.`;
 if(/summar|transcript|vendor|retention|recording|\bai\b/i.test(prompt))answer+='\n\nFor this change, establish whether you will use synthetic or customer data, the vendor’s role and retention, deployment status, and the commitments in each applicable customer agreement. A merged PR alone does not establish production deployment.';
 if(!available.length)answer+='\n\nYou can attach or paste one relevant agreement, or describe the real change. Broad integrations are optional.';
 answer+='\n\nThis is a bounded local response from the available records. Jurisdiction-specific legal coverage is unverified; novel interpretation stays with a qualified reviewer.';
 return {text:answer,citations,factIds:confirmed.slice(0,concise?2:5).map(f=>f.id),sourceIds:[...new Set([...citations.map(x=>x.sourceId),...confirmed.flatMap(f=>f.provenance.sourceIds)])]};
}
export function snapshotFromState(s:WorkspaceState,a:ActorContext):WorkspaceSnapshot {
 const member=membership(s,a);const visible=<T extends RecordBase>(records:T[])=>records.filter(r=>canRead(s,a,r));
 const {receipts:_r,memberships:_m,migration:_g,outbox:_o,deletionJobs:_d,scenarioShares:_ss,routingDelegations:_rd,routingRules:_rr,...rest}=structuredClone(s);
 const output:WorkspaceSnapshot={...rest,inventories:inventoryViews(s,a),inventoryCandidates:inventoryCandidates(s,a),indexing:indexingViews(s,a),sharedScenarios:scenarioShareViews(s,a),delegations:routingDelegationViews(s,a),routing:routingRuleViews(s,a),deletions:deletionViews(s,a),documentHeadIds:visible(documentHeads(s.documents)).map(d=>d.id),recovery:recoveryViews(s,a),effortEntries:visible(s.effortEntries||[]),effortBaselines:visible(s.effortBaselines||[]),effortComparisons:effortComparisons(s,a),obligations:obligationViews(s,a),conversations:visible(s.conversations),messages:visible(s.messages),scenarios:visible(s.scenarios),facts:visible(s.facts),preferences:visible(s.preferences).filter(p=>p.target==='team'||p.ownerId===a.actorId),sources:visible(s.sources),documents:visible(s.documents),legalAuthorities:visible(s.legalAuthorities),coverage:coverageViews(s,a),matters:routedMatterViews(s,visible(s.matters)),proposals:visible(s.proposals),approvals:visible(s.approvals),actions:visible(s.actions),counsel:visible(s.counsel).map(e=>({...e,packetHash:counselPacketHash(e)})),learning:learningViews(s,a),connections:visible(s.connections),events:visible(s.events),tombstones:[],aiMode:conversationAIMode(),aiRuns:conversationRunViews(s,a),actor:{id:a.actorId,roles:member.roles,mode:a.mode},capabilities:member.roles,migrationStatus:s.migration?.status||null,limitations:[conversationAIMode()==='local'?'Local responses use bounded deterministic assistance; no connected model quality has been validated.':'Configured model answers use exact/keyword evidence and bounded support checks; live provider execution and legal quality are not certified.','No legal coverage or counsel availability is certified. External actions remain pending until action-specific completion evidence is recorded.','Managed Temporal, Atlas retrieval indexes and provider connections require deployment configuration and connected-service qualification.','Conversation-only reuse prevents company-memory reuse; retained conversation records follow workspace retention policy.']};
 const allowed=(list:RecordBase[])=>new Set(list.map(x=>x.id));const docIds=allowed(output.documents),srcIds=allowed(output.sources),factIds=allowed(output.facts),convIds=allowed(output.conversations);
 output.matters=output.matters.map(m=>({...m,sourceIds:m.sourceIds.filter(id=>srcIds.has(id)),documentIds:m.documentIds.filter(id=>docIds.has(id)),factIds:m.factIds.filter(id=>factIds.has(id)),conversationIds:m.conversationIds.filter(id=>convIds.has(id))}));
 return structuredClone(output);
}
export async function snapshot(actor:ActorContext):Promise<WorkspaceSnapshot>{const {state}=await transactWorkspace(actor.tenantId,s=>{bootstrap(s,actor);return null;});return snapshotFromState(state,actor);}
const commandFields:Record<WorkspaceCommand['type'],string[]>={...inventoryCommandFields,...collaborationCommandFields,...documentCommandFields,...recoveryCommandFields,
 ...measurementCommandFields,
 ...obligationCommandFields,
 ...coverageCommandFields,
 ...counselCommandFields,
 'company.configure':['name'],'demo.load':[],'conversation.create':['title','scope','reuse'],'message.send':['text','conversationId','scope','channel','voiceConfirmed'],'scenario.update':['scenarioId','assumptions','expectedRecordVersion'],'scenario.adopt':['scenarioId','expectedRecordVersion','objective'],'fact.propose':['predicate','value','practice','sourceIds','conversationId','reuse','supersedesId'],'fact.confirm':['factId','expectedRecordVersion','expectedOriginVersion'],'preference.set':['key','value','target'],'document.add':['title','body','authority','kind','scope','amendsDocumentId'],'matter.create':['title','objective','conversationId','scope'],'matter.prepare':['matterId','expectedRecordVersion'],'matter.cancel':['matterId','reason','expectedRecordVersion'],'matter.close':['matterId','reason','expectedRecordVersion','noAction'],'proposal.revise':['proposalId','body','expectedRecordVersion'],'approval.record':['proposalId','proposalHash','capacity','validUntil','note','recipients','destination','conditions'],'action.plan':['matterId','proposalId','kind','title','content','recipients','destination'],'action.authorize':['actionId','contentHash','expectedRecordVersion','validUntil'],'action.attest':['actionId','expectedRecordVersion','artifact','completionKind'],'counsel.request':['matterId','route','providerName','recipient','sourceIds','feeCap','terms'],'source.revoke':['sourceId','reason','delete'],'learning.propose':['matterId','title','rule','kind','scopeDescription','procedureKey'],'learning.run_evaluation':['candidateId','expectedRecordVersion'],'learning.evaluate':['candidateId','tests','expectedRecordVersion'],'learning.promote':['candidateId','evaluationHash','expectedRecordVersion'],'learning.rollback':['candidateId','expectedRecordVersion','reason'],'learning.renew':['candidateId','expectedRecordVersion','evaluationHash'],'membership.revoke':['actorId'],'event.ingest':['provider','externalEventId','externalObjectId','externalRevision','occurredAt','title','text','matterId','correlationKey','scope']
};
export async function command(actor:ActorContext,envelope:CommandEnvelope,trusted?:{originalObjectRef?:string}):Promise<CommandResult>{
 ensure(envelope&&typeof envelope==='object'&&Number.isSafeInteger(envelope.expectedVersion),'INVALID_COMMAND','A current workspace version is required.',400);text(envelope.idempotencyKey,'a command key',150);ensure(envelope.command&&typeof envelope.command.type==='string','INVALID_COMMAND','A typed command is required.',400);ensure(Object.hasOwn(commandFields,envelope.command.type),'UNKNOWN_COMMAND','This command is not supported.',400);ensure(Object.keys(envelope.command).every(k=>k==='type'||commandFields[envelope.command.type].includes(k)),'UNKNOWN_FIELD','The command contains an unsupported field.',400);ensure(Buffer.byteLength(JSON.stringify(envelope.command))<=150000,'COMMAND_TOO_LARGE','This command is too large.',413);
 const {state,result:saved}=await transactWorkspace(actor.tenantId,s=>{bootstrap(s,actor);if(trusted?.originalObjectRef)assertOriginalNotDeleted(s,trusted.originalObjectRef,digest({actor:actor.actorId,key:envelope.idempotencyKey}));const key=digest({actorId:actor.actorId,key:envelope.idempotencyKey}),bodyHash=digest({command:envelope.command,originalObjectRef:trusted?.originalObjectRef||null}),old=s.receipts[key];if(old){ensure(old.hash===bodyHash,'IDEMPOTENCY_CONFLICT','This key is already bound to another command.');return {result:old.result,replayed:true};}ensure(s.version===envelope.expectedVersion,'VERSION_CONFLICT','The workspace changed. Refresh and review before sending this command.');const indexBefore=indexRecordFingerprints(s);const result=applyCommand(s,actor,envelope.command,envelope.idempotencyKey,trusted);enqueueIndexMaintenance(s,actor,indexBefore,envelope.idempotencyKey);s.receipts[key]={hash:bodyHash,result};return {result,replayed:false};});
 return {snapshot:snapshotFromState(state,actor),...saved};
}
function applyCommand(s:WorkspaceState,a:ActorContext,c:WorkspaceCommand,commandId:string,trusted?:{originalObjectRef?:string}):Record<string,unknown>{
 if(Object.hasOwn(inventoryCommandFields,c.type))return applyInventoryCommand(s,a,c as InventoryCommand);
 if(Object.hasOwn(collaborationCommandFields,c.type))return applyCollaborationCommand(s,a,c as CollaborationCommand);
 if(Object.hasOwn(documentCommandFields,c.type))return applyDocumentCommand(s,a,c as DocumentCommand,trusted);
 if(Object.hasOwn(recoveryCommandFields,c.type))return applyRecoveryCommand(s,a,c as import('./recovery').RecoveryCommand);
 if(c.type.startsWith('coverage.'))return applyCoverageCommand(s,a,c as Parameters<typeof applyCoverageCommand>[2]);
 if(Object.hasOwn(measurementCommandFields,c.type))return applyMeasurementCommand(s,a,c as MeasurementCommand);
 if(Object.hasOwn(obligationCommandFields,c.type))return applyObligationCommand(s,a,c as ObligationCommand);
 if(Object.hasOwn(counselCommandFields,c.type))return applyCounselCommand(s,a,c as CounselCommand);
 switch(c.type){
 case 'company.configure':requireRole(s,a,'business_owner');s.companyName=text(c.name,'the company name',200);activity(s,a,c.type,'Company updated',s.companyName);return {companyName:s.companyName};
 case 'conversation.create':{const record=createConversation(s,a,c.title||'A new conversation',c.scope,c.reuse);return {conversationId:record.id};}
 case 'message.send':{
  const prompt=text(c.text,'a message',20000);const conversation=c.conversationId?readRecord(s,a,s.conversations,c.conversationId):createConversation(s,a,prompt.slice(0,80),c.scope);ensure(!c.channel||['web','slack','voice'].includes(c.channel),'INVALID_CHANNEL','Choose a supported channel.',400);const voice=c.channel==='voice';
  const intent:Message['intent']=/^\s*(looks good|go ahead|yes|approved|send it|publish it)[.!\s]*$/i.test(prompt)?'ambiguous':/\b(what if|hypothetical|thinking of|considering|explore|maybe|suppose)\b/i.test(prompt)?'scenario':/\b(remember|actually|correction|our .* is|we retain|we use)\b/i.test(prompt)?'correction':/\b(short answer|be concise|keep .* brief|shorter responses)\b/i.test(prompt)?'preference':'question';
  const user:Message={...base(s,a,conversation.scope),conversationId:conversation.id,role:'user',channel:c.channel||'web',text:prompt,intent,artifactIds:[],citations:[],generation:'human',retention:'workspace_policy',voiceConfirmed:!voice||c.voiceConfirmed===true};s.messages.push(user);
  let response=usefulAnswer(s,a,conversation,prompt);const artifacts:string[]=[];
  if(voice&&!c.voiceConfirmed){response={text:'Review and correct this transcript first, especially names, dates and amounts. This message has not changed company facts or authorized any action.',citations:[],sourceIds:[]};}
  else if(intent==='ambiguous'){response={text:'Your feedback is recorded. To authorize a consequential step, open the exact proposal or action and review its content, recipients, destination and expiry. This message does not authorize sending, sharing, publishing or signing.',citations:[],sourceIds:[]};}
  else if(intent==='scenario'){
   let scenario=conversation.scenarioId?s.scenarios.find(x=>x.id===conversation.scenarioId&&x.status==='exploring'):undefined;
   if(!scenario){scenario={...base(s,a,conversation.scope),conversationId:conversation.id,title:prompt.slice(0,120),assumptions:[prompt],questions:['Which choices are hypothetical?','What customer data and agreements would be affected?','Who can confirm actual deployment and commitments?'],status:'exploring',adoptedMatterId:null,adoptionDecisionId:null};s.scenarios.push(scenario);conversation.scenarioId=scenario.id;}else{scenario.assumptions.push(prompt);touch(scenario);}
   artifacts.push(scenario.id);response.text+='\n\nI saved this as an exploratory scenario. Its assumptions are separate from company facts. Adopt the plan explicitly when you want durable work.';
  }else if(intent==='correction'){response={text:'I recorded your statement in this conversation. Use “What I’ll remember” to propose a specific fact, choose its scope and identify whether it is planned or live. An authorized fact owner must confirm it before company-wide reuse.',citations:[],sourceIds:[]};}
  else if(intent==='preference'){setPreference(s,a,'response_length','short answer first','personal');response={text:'I’ll give you the short answer first. This personal preference is visible and reversible in Company; it does not change company policy.',citations:[],sourceIds:[]};}
  if(conversationAIMode()!=='local'&&user.voiceConfirmed&&(intent==='question'||intent==='scenario')){user.artifactIds=artifacts;touch(conversation);const run=enqueueConversationRun(s,a,conversation,user,commandId);activity(s,a,c.type,'Message accepted',run.status==='queued'?'A bounded answer is queued for processing.':'The configured model is unavailable; your message is retained.',conversation,conversation.matterId);return {conversationId:conversation.id,userMessageId:user.id,runId:run.id,answerStatus:run.status,artifactIds:artifacts};}
  const assistant:Message={...base(s,a,conversation.scope,response.sourceIds,'Bounded local response from authorized evidence'),conversationId:conversation.id,role:'assistant',channel:c.channel||'web',text:response.text,intent,artifactIds:artifacts,citations:response.citations,generation:'bounded_local',retention:'workspace_policy',voiceConfirmed:true};assistant.provenance.factIds=response.factIds||[];s.messages.push(assistant);user.artifactIds=artifacts;touch(conversation);activity(s,a,c.type,'Conversation continued','Response and linked records saved.',conversation,conversation.matterId);return {conversationId:conversation.id,messageId:assistant.id,artifactIds:artifacts};
 }
 case 'scenario.update':{const scenario=readRecord(s,a,s.scenarios,c.scenarioId);version(scenario,c.expectedRecordVersion);ensure(scenario.status==='exploring','SCENARIO_ADOPTED','Create another scenario to explore a different plan.');ensure(Array.isArray(c.assumptions)&&c.assumptions.length<=30,'INVALID_INPUT','Use at most 30 assumptions.',400);scenario.assumptions=c.assumptions.map(v=>text(v,'an assumption',3000));touch(scenario);return {scenarioId:scenario.id};}
 case 'scenario.adopt':{const scenario=readRecord(s,a,s.scenarios,c.scenarioId);requireRole(s,a,'business_owner',scenario);if(scenario.adoptedMatterId)return {matterId:scenario.adoptedMatterId};version(scenario,c.expectedRecordVersion);const m=createMatter(s,a,scenario.title,c.objective||scenario.assumptions.join('\n'),scenario.scope,scenario.conversationId,scenario.id);scenario.status='adopted';scenario.adoptedMatterId=m.id;scenario.adoptionDecisionId=randomUUID();touch(scenario);activity(s,a,c.type,'Scenario adopted','Explicit adoption created one matter. Assumptions remain planned and unconfirmed.',scenario,m.id);queue(s,m.id,commandId);return {matterId:m.id};}
 case 'fact.propose':{const predicate=text(c.predicate,'a fact name',150);ensure(!c.practice||['planned','live','unknown'].includes(c.practice),'INVALID_FACT','Choose planned, live or unknown practice.',400);ensure(!c.reuse||['company','conversation_only'].includes(c.reuse),'INVALID_REUSE','Choose a supported reuse policy.',400);ensure(c.value!==undefined&&Buffer.byteLength(JSON.stringify(c.value))<10000,'INVALID_FACT','Provide a bounded factual value.',400);const conversation=c.conversationId?readRecord(s,a,s.conversations,c.conversationId):null;const sources=sourceIds(s,a,c.sourceIds);const targetScope=conversation?.scope||{kind:'team' as const,actorIds:[]};const existing=s.facts.find(f=>f.predicate===predicate&&f.entityId===s.entityId&&f.status==='confirmed'&&digest(f.scope)===digest(targetScope)&&canRead(s,a,f));if(c.supersedesId){const prior=readRecord(s,a,s.facts,c.supersedesId);ensure(digest(prior.scope)===digest(targetScope)&&prior.predicate===predicate,'FACT_SCOPE_MISMATCH','A correction must preserve the scope and identity of its original fact.');}const f:FactAssertion={...base(s,a,targetScope,sources),entityId:s.entityId,predicate,value:structuredClone(c.value),status:existing?'disputed':'candidate',practice:c.practice||'unknown',ownerId:a.actorId,observedAt:timestamp(),validFrom:null,validUntil:null,confirmedBy:null,confirmedAt:null,supersedesId:c.supersedesId||existing?.id||null,originVersion:s.version,reuse:conversation?.reuse==='conversation_only'?'conversation_only':c.reuse||'company',conversationId:conversation?.id||null};s.facts.push(f);activity(s,a,c.type,'Memory proposed','Candidate statement awaits an authorized fact owner.',f);return {factId:f.id};}
 case 'fact.confirm':{const f=readRecord(s,a,s.facts,c.factId);requireRole(s,a,'fact_owner',f);version(f,c.expectedRecordVersion);ensure(f.originVersion===c.expectedOriginVersion,'STALE_FACT_INTENT','This fact proposal changed. Inspect it again.');ensure(['candidate','disputed'].includes(f.status),'FACT_ALREADY_RESOLVED','This candidate is already resolved.');const current=s.facts.find(x=>x.id!==f.id&&x.predicate===f.predicate&&x.entityId===f.entityId&&x.status==='confirmed'&&x.reuse===f.reuse&&digest(x.scope)===digest(f.scope));ensure((current?.id||null)===f.supersedesId,'STALE_FACT_INTENT','Another fact owner confirmed a newer assertion. Reconcile the conflict first.');if(current){current.status='superseded';touch(current);}f.status='confirmed';f.confirmedBy=a.actorId;f.confirmedAt=timestamp();touch(f);if(f.reuse==='company')invalidate(s,'A confirmed fact changed; prepare and review current evidence.');activity(s,a,c.type,'Fact confirmed',`${f.predicate} confirmed with ${f.practice} status.`,f);return {factId:f.id};}
 case 'preference.set':{setPreference(s,a,c.key,c.value,c.target);return {applied:true};}
 case 'document.add':{requireRole(s,a,'member');ensure(!c.kind||['agreement','notice','template','draft','other'].includes(c.kind),'INVALID_DOCUMENT_KIND','Choose a supported document kind.',400);let scope=requestedScope(s,a,c.scope||{kind:'team',actorIds:[]});let amendmentSourceId:string|null=null;const title=text(c.title,'a document title',300),body=text(c.body,'document text',100000);ensure(['draft','executed','effective','template','unknown'].includes(c.authority),'INVALID_AUTHORITY','Choose document authority.',400);if(c.amendsDocumentId){const original=s.documents.find(d=>d.documentId===c.amendsDocumentId);ensure(original&&canRead(s,a,original),'NOT_FOUND','The original agreement is unavailable.',404);ensure(!c.scope||digest(c.scope)===digest(original.scope),'AMENDMENT_SCOPE','An amendment must preserve the original agreement scope.');scope=structuredClone(original.scope);amendmentSourceId=original.sourceId;}const source:Source={...base(s,a,scope,amendmentSourceId?[amendmentSourceId]:[]),title,kind:'manual',externalId:null,externalRevision:null,text:body,contentHash:digest(body),url:null,status:'active',aclVersion:1,observedAt:timestamp(),effectiveAt:null,authority:c.authority,originalObjectRef:trusted?.originalObjectRef||null};s.sources.push(source);const document={...base(s,a,scope,[source.id]),documentId:randomUUID(),title,body,contentHash:digest(body),authority:c.authority,sourceId:source.id,revision:1,parentRevisionId:null,amendsDocumentId:c.amendsDocumentId||null,status:'current' as const,kind:c.kind||'other' as const};s.documents.push(document);activity(s,a,c.type,'Document added',`${title}; authority attributed to the uploading member.`,document);return {documentId:document.id,sourceId:source.id};}
 case 'matter.create':{const conv=c.conversationId?readRecord(s,a,s.conversations,c.conversationId):null;const m=createMatter(s,a,c.title,c.objective,conv?.scope||requestedScope(s,a,c.scope||{kind:'team',actorIds:[]}),conv?.id);queue(s,m.id,commandId);activity(s,a,c.type,'Matter opened',m.objective,m,m.id);return {matterId:m.id};}
 case 'matter.prepare':{const m=readRecord(s,a,s.matters,c.matterId);requireRole(s,a,'business_owner',m);version(m,c.expectedRecordVersion);ensure(!m.legacyWorkflowId,'LEGACY_EXECUTION_OWNER','Imported work remains owned by the legacy engine.');ensure(!['closed','canceled'].includes(m.state),'MATTER_TERMINAL','Open corrective work for a closed or canceled matter.');m.documentIds=documentHeads(s.documents).filter(d=>canRead(s,a,d)).map(d=>d.id);m.sourceIds=[...new Set([...m.documentIds.map(id=>s.documents.find(d=>d.id===id)!.sourceId),...m.sourceIds.filter(id=>s.sources.some(x=>x.id===id&&canRead(s,a,x)))])];m.factIds=s.facts.filter(f=>factCurrentlyConfirmed(f)&&f.reuse==='company'&&canRead(s,a,f)).map(f=>f.id);m.provenance.sourceIds=m.sourceIds;m.provenance.factIds=m.factIds;for(const task of m.tasks.filter(t=>t.kind==='fact')){task.status=m.factIds.length?'done':'pending';task.evidenceIds=[...m.factIds];}
  const procedure=procedureAssessment(s,a,m);for(const lesson of procedure.lessons){(lesson.appliedMatterIds||=[]);if(!lesson.appliedMatterIds.includes(m.id))lesson.appliedMatterIds.push(m.id);}m.ruleVersion=s.ruleVersion;const agreements=s.documents.filter(d=>m.documentIds.includes(d.id)&&d.kind==='agreement'&&d.authority==='executed');const inventory=currentInventory(s,a,m);if(inventory){m.sourceIds=[...new Set([...m.sourceIds,...inventory.provenance.sourceIds])];m.provenance.sourceIds=m.sourceIds;}const unknowns=['Legal/domain coverage and qualified review are not yet verified.',...(!m.factIds.length?['No current confirmed company facts.']:[]),...(!m.documentIds.length?['No authoritative documents supplied.']:[]),...(!inventory?['Agreement inventory has not been attested complete.']:[]),...procedure.blockers];
  const body=`Objective\n${m.objective}\n\nConfirmed facts\n${m.factIds.length?m.factIds.map(id=>{const f=s.facts.find(f=>f.id===id)!;return `${f.predicate}: ${JSON.stringify(f.value)} (${f.practice})`;}).join('\n'):'Facts remain unconfirmed.'}\n\nProposed work\nReview the intended data flow and actual deployment evidence. Check each applicable executed agreement and amendment. Identify product, contractual and notice remedies before choosing an external action.\n\nSupplied agreement register\n${inventory?`Named owner ${inventory.ownerId} attests ${inventory.documentIds.length} current agreement/amendment heads for: ${inventory.scopeDescription}. Expires ${inventory.validUntil}. This is a human attestation of the supplied register; external discovery and legal applicability are unverified.`:'Completeness remains unverified.'}\n\nOpen questions\n${unknowns.map(x=>`• ${x}`).join('\n')}\n\nThis packet is preparation for review; it is not legal clearance or publication.`;
  const p:Proposal={...base(s,a,m.scope,m.sourceIds),matterId:m.id,title:`Review packet · ${m.title}`,body,contentHash:digest(body),baselineRevisionIds:m.documentIds,dependencies:deps(s,m),status:'current',route:'legal_review',noticeMatrix:agreements.map(d=>({documentId:d.id,title:d.title,clause:d.body.split(/\n\s*\n/).find(p=>/notice|notif|subprocess/i.test(p))?.slice(0,1200)||'No notice clause identified in the supplied text; review the whole agreement.',status:'review_required'})),inventoryComplete:!!inventory,...(inventory?{inventory:inventoryBinding(inventory)}:{}),unknowns,supersedesId:m.proposalId};if(m.proposalId){const old=s.proposals.find(p=>p.id===m.proposalId);if(old){old.status='superseded';touch(old);}for(const approval of s.approvals.filter(x=>x.proposalId===m.proposalId)){approval.status='invalidated';touch(approval);}}p.provenance.factIds=m.factIds;s.proposals.push(p);m.proposalId=p.id;resetReviewTasks(s,m,p);m.state=procedure.blockers.length?'needs_facts':'business_review';m.blockers=[...procedure.blockers,'Business decision and qualified legal review pending.'];touch(m);activity(s,a,c.type,'Review packet prepared','Applicable supplied agreements enumerated; missing inventory coverage remains visible.',p,m.id);queue(s,m.id,commandId);return {proposalId:p.id,matterId:m.id};}
 case 'proposal.revise':{const p=readRecord(s,a,s.proposals,c.proposalId);requireRole(s,a,'member',p);version(p,c.expectedRecordVersion);const m=fresh(s,a,p);const body=text(c.body,'the revised proposal',100000);p.status='superseded';touch(p);const next:Proposal={...structuredClone(p),...base(s,a,p.scope,p.provenance.sourceIds),body,contentHash:digest(body),status:'current',supersedesId:p.id};s.proposals.push(next);for(const approval of s.approvals.filter(x=>x.proposalId===p.id)){approval.status='invalidated';touch(approval);}m.proposalId=next.id;resetReviewTasks(s,m,next);m.state='business_review';touch(m);activity(s,a,c.type,'Proposal revised','Both business and legal decisions must inspect this successor version.',next,m.id);return {proposalId:next.id};}
 case 'approval.record':{const p=readRecord(s,a,s.proposals,c.proposalId);ensure(c.proposalHash===p.contentHash,'STALE_PROPOSAL','The inspected proposal hash no longer matches.');ensure(!['publication','signature'].includes(c.capacity),'ACTION_AUTHORIZATION_REQUIRED','Authorize publication and signature through an exact action preview.');if(c.capacity==='legal')ensure(approvalValid(s,p,'business'),'BUSINESS_APPROVAL_REQUIRED','Record the business decision before legal clearance.');const approval=addApproval(s,a,p,c.capacity,c.validUntil,{note:c.note?text(c.note,'a decision note',5000):'',recipients:(c.recipients||[]).map(r=>text(r,'a recipient',300)),destination:c.destination||null,conditions:(c.conditions||[]).map(x=>text(x,'a condition',1000))});const m=s.matters.find(x=>x.id===p.matterId)!,before=structuredClone(m);const business=approvalValid(s,p,'business'),legal=approvalValid(s,p,'legal');m.state=business&&legal?'authorized_action':business?'legal_review':'business_review';m.blockers=business&&legal?['Authorize exact required actions.']:business?['Qualified legal review pending; unmet conditions do not grant clearance.']:['Business review or its conditions remain pending.'];for(const task of m.tasks.filter(t=>t.kind==='business'||t.kind==='legal')){const valid=task.kind==='business'?business:legal;task.status=valid?'done':'pending';if(task.kind===c.capacity){task.ownerId=a.actorId;task.evidenceIds=valid?[approval.id]:[];if(approval.conditions.length&&!valid)task.status='blocked';}}touch(m);advancePacketReviewState(s,before,m);activity(s,a,c.type,`${c.capacity} decision recorded`,'Decision binds the inspected proposal, source snapshot, role and expiry.',approval,m.id);return {approvalId:approval.id};}
 case 'action.plan':{const m=readRecord(s,a,s.matters,c.matterId),p=readRecord(s,a,s.proposals,c.proposalId);requireRole(s,a,'business_owner',m);fresh(s,a,p);ensure(p.matterId===m.id,'SCOPE_MISMATCH','Proposal belongs to a different matter.');ensure(['publish','send','signature_request','internal_document','product_change','no_action'].includes(c.kind),'INVALID_ACTION','Choose a supported action.',400);ensure(!c.recipients||Array.isArray(c.recipients)&&c.recipients.length<=100,'INVALID_RECIPIENTS','Choose at most 100 explicit recipients.',400);if(['send','signature_request'].includes(c.kind))ensure(c.recipients?.length,'RECIPIENT_REQUIRED','Specify the exact recipient list.',400);if(c.kind==='publish')ensure(c.destination&&/^https:\/\//.test(c.destination),'DESTINATION_REQUIRED','Specify the HTTPS publication destination.',400);const content=text(c.content,'exact action content',100000);ensure(content===p.body,'ACTION_CONTENT_REVIEW_REQUIRED','Revise and review the proposal with this exact content before planning its action.');const recipients=(c.recipients||[]).map(r=>text(r,'a recipient',300)),destination=c.destination||null;const action:Action={...base(s,a,m.scope,p.provenance.sourceIds),matterId:m.id,proposalId:p.id,kind:c.kind,title:text(c.title,'an action title',300),content,contentHash:digest({content,title:text(c.title,'an action title',300),recipients,destination,kind:c.kind,proposalId:p.id}),recipients,destination,status:'planned',authorizationId:null,providerIdempotencyKey:randomUUID(),providerReceipt:null,completion:null,executionOwner:'v2',leaseUntil:null};action.provenance.factIds=p.provenance.factIds||[];s.actions.push(action);activity(s,a,c.type,'Action planned','Exact content and destination are ready for explicit authorization.',action,m.id);return {actionId:action.id};}
 case 'action.authorize':{const action=readRecord(s,a,s.actions,c.actionId);version(action,c.expectedRecordVersion);ensure(action.contentHash===c.contentHash,'STALE_ACTION','Inspect the current content and recipients.');ensure(action.status==='planned','ACTION_ALREADY_DISPATCHED','This action is already authorized or has an unresolved effect.');const p=readRecord(s,a,s.proposals,action.proposalId),m=fresh(s,a,p);assertObligationsReady(s,a,m.id);ensure(approvalValid(s,p,'business')&&approvalValid(s,p,'legal'),'REVIEW_REQUIRED','Current business and legal decisions are required.');const capacity:Approval['capacity']=action.kind==='signature_request'?'signature':action.kind==='no_action'?'no_action':'publication';const approval=addApproval(s,a,p,capacity,c.validUntil,{actionId:action.id,actionHash:action.contentHash,recipients:action.recipients,destination:action.destination});action.authorizationId=approval.id;action.status='pending_manual';touch(action);m.state='executing';m.blockers=['Review the configured execution method, or complete the authorized manual action and retain action-specific evidence.'];touch(m);activity(s,a,c.type,'Exact action authorized','Authorization saved. No external request has been sent.',action,m.id);return {actionId:action.id,approvalId:approval.id};}
 case 'action.attest':{const action=readRecord(s,a,s.actions,c.actionId);version(action,c.expectedRecordVersion);requireRole(s,a,action.kind==='signature_request'?'signatory':'publisher',action);ensure(action.status==='pending_manual','ACTION_NOT_READY','Only an authorized pending manual action can be attested.');const p=readRecord(s,a,s.proposals,action.proposalId),m=fresh(s,a,p);const approval=s.approvals.find(x=>x.id===action.authorizationId);ensure(approval&&approval.status==='active'&&Date.parse(approval.validUntil)>Date.now()&&approval.actionHash===action.contentHash&&approval.membershipVersion===s.memberships.find(x=>x.actorId===approval.actorId)?.version,'AUTHORIZATION_EXPIRED','Authorization changed or expired. Review and authorize this action again.');ensure(approvalValid(s,p,'business')&&approvalValid(s,p,'legal'),'REVIEW_EXPIRED','Review authority has changed or expired.');ensure(['human_attestation','executed_agreement'].includes(c.completionKind),'INVALID_COMPLETION','Choose a supported completion evidence type.',400);if(action.kind==='signature_request'){ensure(c.completionKind==='executed_agreement','EXECUTED_AGREEMENT_REQUIRED','A signing request is not an executed agreement. Attach the executed original.');const signed=s.documents.find(d=>d.id===c.artifact&&d.authority==='executed'&&canRead(s,a,d));ensure(signed&&s.sources.find(x=>x.id===signed.sourceId)?.originalObjectRef,'SIGNED_ORIGINAL_REQUIRED','An executed original in encrypted artifact storage is required. This action remains pending.');}else ensure(c.completionKind==='human_attestation','INVALID_COMPLETION','This action requires a named human attestation.',400);action.completion={kind:c.completionKind,artifact:text(c.artifact,'an action-specific artifact reference or attestation',5000),verifierId:a.actorId,verifiedAt:timestamp()};action.status='verified';touch(action);m.state='verifying';m.blockers=['Review all required action evidence before closing.'];touch(m);activity(s,a,c.type,'Manual completion evidence recorded','Named human attestation; no direct provider read-back is claimed.',action,m.id);return {actionId:action.id};}
 case 'matter.close':{const m=readRecord(s,a,s.matters,c.matterId);requireRole(s,a,'business_owner',m);version(m,c.expectedRecordVersion);ensure(!m.legacyWorkflowId,'LEGACY_EXECUTION_OWNER','Imported legacy work remains owned by its original engine.');const p=m.proposalId?readRecord(s,a,s.proposals,m.proposalId):null;ensure(p,'REVIEW_REQUIRED','Prepare an assessed proposal before closure.');fresh(s,a,p);assertObligationsReady(s,a,m.id,true);ensure(approvalValid(s,p,'business')&&approvalValid(s,p,'legal'),'REVIEW_REQUIRED','Current business and legal review are required.');const actions=s.actions.filter(x=>x.matterId===m.id&&x.status!=='canceled');ensure(!actions.some(x=>['uncertain','dispatching','verifying'].includes(x.status)),'RECONCILIATION_REQUIRED','Reconcile every unresolved external effect before closure.');ensure(m.tasks.every(t=>t.status==='done'),'TASKS_PENDING','Every required task needs evidence before closure.');if(c.noAction){ensure(approvalValid(s,p,'no_action'),'NO_ACTION_DECISION_REQUIRED','A version-bound no-action decision is required.');for(const action of actions.filter(x=>x.status!=='verified')){action.status='canceled';touch(action);}}else ensure(actions.length>0&&actions.every(x=>x.status==='verified'&&x.completion),'COMPLETION_PENDING','Every required action must have completion evidence.');m.state='closed';m.outcome=text(c.reason,'a closure rationale',5000);m.closedAt=timestamp();m.blockers=[];touch(m);activity(s,a,c.type,'Matter closed',m.outcome,m,m.id);return {matterId:m.id};}
 case 'matter.cancel':{const m=readRecord(s,a,s.matters,c.matterId);requireRole(s,a,'business_owner',m);version(m,c.expectedRecordVersion);ensure(!m.legacyWorkflowId,'LEGACY_EXECUTION_OWNER','Imported legacy work remains owned by its original engine.');for(const action of s.actions.filter(x=>x.matterId===m.id&&!['verified','uncertain','dispatching'].includes(x.status))){action.status='canceled';touch(action);}m.state='canceled';m.outcome=text(c.reason,'a cancellation reason',5000);m.blockers=s.actions.some(x=>x.matterId===m.id&&['uncertain','dispatching'].includes(x.status))?['Cancellation stops future dispatch; existing uncertain effects still require reconciliation.']:[];touch(m);for(const outbox of s.outbox.filter(x=>x.aggregateId===m.id&&x.status==='pending'))outbox.status='canceled';activity(s,a,c.type,'Matter canceled',m.outcome,m,m.id);return {matterId:m.id};}
 case 'counsel.request':return prepareCounselRequest(s,a,c);
 case 'source.revoke':{const removed=c.delete&&mayDeleteRemovedSource(s,a,c.sourceId);const source=removed?s.sources.find(x=>x.id===c.sourceId)!:readRecord(s,a,s.sources,c.sourceId);requireRole(s,a,'admin',removed?undefined:source);source.status=c.delete?'deleted':'revoked';source.aclVersion++;touch(source);invalidate(s,'Source access was removed; derived records and approvals are unavailable.',source.id);if(c.delete){text(c.reason,'a deletion reason',1000);applySourceDeletion(s,a,source.id);}activity(s,a,c.type,c.delete?'Source deleted':'Source access revoked','Current eligibility denies source and dependent content before any index cleanup.');return {sourceId:source.id};}
 case 'learning.propose':{const m=readRecord(s,a,s.matters,c.matterId);ensure(['procedure','legal_playbook'].includes(c.kind),'INVALID_LESSON','Choose a supported lesson kind.',400);ensure(!c.procedureKey||Object.hasOwn(PROCEDURES,c.procedureKey),'UNSUPPORTED_PROCEDURE','Choose a catalogued executable procedure.',400);ensure(!c.procedureKey||c.kind==='procedure','PROCEDURE_KIND','This catalogued rule is an operational procedure, not legal clearance.',400);const originInput=procedureInput(s,a,m.factIds.map(id=>s.facts.find(f=>f.id===id)).filter((f):f is FactAssertion=>!!f));const record={...base(s,a,m.scope,m.provenance.sourceIds),title:text(c.title,'a lesson title',300),rule:text(c.rule,'a proposed rule',4000),kind:c.kind,scopeDescription:text(c.scopeDescription,'an intended scope',1000),originMatterId:m.id,status:'candidate' as const,tests:[],evaluationHash:null,evaluatedBy:null,approvedBy:null,effectiveVersion:null,rollbackVersion:null,affectedMatterIds:[],...(c.procedureKey?{procedureKey:c.procedureKey,originInput,originInputHash:digest(originInput),effectSummary:PROCEDURES[c.procedureKey].description,appliedMatterIds:[]}: {})};record.provenance.factIds=m.provenance.factIds||[];s.learning.push(record);activity(s,a,c.type,'Learning candidate proposed','Candidate has no effect on future work until independent evaluation and owner approval.',record,m.id);return {candidateId:record.id};}
 case 'learning.run_evaluation':{const candidate=readRecord(s,a,s.learning,c.candidateId);const evaluator=requireRole(s,a,'evaluator',candidate);version(candidate,c.expectedRecordVersion);ensure(candidate.provenance.actorId!==a.actorId,'INDEPENDENT_EVALUATOR_REQUIRED','The candidate author cannot run their own promotion evaluation.');ensure(candidate.status==='candidate'||candidate.status==='evaluated','CANDIDATE_STATE','Evaluate a candidate before promotion.');ensure(candidate.procedureKey&&Object.hasOwn(PROCEDURES,candidate.procedureKey)&&candidate.originInput&&digest(candidate.originInput)===candidate.originInputHash,'EXECUTABLE_PROCEDURE_REQUIRED','Manual prose and reported passing tests do not define executable behavior. Choose a supported procedure.');const baseline=s.learning.some(l=>l.id!==candidate.id&&l.status==='promoted'&&l.procedureKey===candidate.procedureKey&&digest(l.scope)===digest(candidate.scope));const result=evaluateProcedure(candidate.originInput,baseline);const fullEvaluation={...result,totalCaseCount:result.cases.length,withheldHoldoutCount:0,runAt:timestamp(),qualification:'deterministic_replay_not_legal_quality' as const,inputHash:candidate.originInputHash!,baselinePolicyVersion:s.ruleVersion,membershipVersion:evaluator.version};candidate.evaluation={...fullEvaluation,cases:result.cases.filter(t=>t.group!=='holdout'),withheldHoldoutCount:result.cases.filter(t=>t.group==='holdout').length};candidate.tests=result.cases.filter(t=>t.group!=='holdout').map(t=>({name:t.id,group:t.group,passed:t.passed,evidence:`frozen:${result.corpusHash}:${t.id}`}));candidate.evaluatedBy=a.actorId;candidate.evaluationHash=digest({procedureKey:candidate.procedureKey,rule:candidate.rule,scope:candidate.scope,evaluation:candidate.evaluation,actorId:a.actorId});candidate.status='evaluated';touch(candidate);s.receipts[`learning-evaluation:${candidate.evaluationHash}`]={hash:candidate.evaluationHash,result:{candidateId:candidate.id,procedureKey:candidate.procedureKey,evaluation:structuredClone(fullEvaluation),candidateVersion:candidate.version,ruleHash:digest(candidate.rule),scopeHash:digest(candidate.scope)}};activity(s,a,c.type,'Frozen procedure comparison completed',`${result.baselineFailures} baseline failures; ${result.candidateFailures} candidate failures. Deterministic checks only; no legal or model-quality qualification.`,candidate,candidate.originMatterId);return {candidateId:candidate.id,evaluationHash:candidate.evaluationHash,qualification:candidate.evaluation.qualification};}
 case 'learning.evaluate':{const candidate=readRecord(s,a,s.learning,c.candidateId);requireRole(s,a,'evaluator',candidate);version(candidate,c.expectedRecordVersion);ensure(candidate.provenance.actorId!==a.actorId,'INDEPENDENT_EVALUATOR_REQUIRED','The candidate author cannot evaluate their own candidate.');ensure(candidate.status==='candidate','CANDIDATE_STATE','Evaluate a new candidate.');ensure(Array.isArray(c.tests)&&c.tests.length>=3&&c.tests.length<=100&&['original','near_miss','holdout'].every(group=>c.tests.some(t=>t.group===group)),'EVALUATION_COVERAGE','Record original, near-miss and independent holdout evidence.');candidate.tests=c.tests.map(t=>({name:text(t.name,'a case name',200),group:t.group,passed:t.passed===true,evidence:text(t.evidence,'an immutable evaluation evidence reference',1000)}));candidate.evaluationHash=digest({rule:candidate.rule,scope:candidate.scopeDescription,tests:candidate.tests,evaluator:a.actorId,version:candidate.version});candidate.evaluatedBy=a.actorId;candidate.status='evaluated';touch(candidate);return {candidateId:candidate.id,evaluationHash:candidate.evaluationHash,qualification:'independently_attributed_manual_evidence'};}
 case 'learning.promote':{const candidate=readRecord(s,a,s.learning,c.candidateId);const owner=requireRole(s,a,candidate.kind==='legal_playbook'?'legal_reviewer':'business_owner',candidate);version(candidate,c.expectedRecordVersion);ensure(candidate.status==='evaluated'&&candidate.evaluationHash===c.evaluationHash&&candidate.tests.every(t=>t.passed),'EVALUATION_REQUIRED','Passing frozen evidence is required.');ensure(candidate.evaluatedBy!==a.actorId&&candidate.evaluatedBy!==candidate.provenance.actorId,'INDEPENDENT_APPROVAL_REQUIRED','An independent responsible owner must approve the evaluated candidate.');const receipt=candidate.evaluationHash&&s.receipts[`learning-evaluation:${candidate.evaluationHash}`],evaluation=candidate.evaluation,evaluator=s.memberships.find(x=>x.actorId===candidate.evaluatedBy);ensure(receipt&&receipt.result.candidateId===candidate.id&&receipt.result.candidateVersion===candidate.version&&receipt.result.ruleHash===digest(candidate.rule)&&receipt.result.scopeHash===digest(candidate.scope)&&evaluation?.qualification==='deterministic_replay_not_legal_quality'&&evaluation.candidateFailures===0&&evaluation.baselineFailures>0&&evaluation.baselinePolicyVersion===s.ruleVersion&&evaluator&&!evaluator.revokedAt&&evaluator.roles.includes('evaluator')&&evaluator.version===evaluation.membershipVersion&&(!evaluator.expiresAt||Date.parse(evaluator.expiresAt)>Date.now()),'EXECUTED_EVALUATION_REQUIRED','A current server-executed frozen comparison with measured improvement and independent evaluator authority is required.');candidate.approvalMembershipVersion=owner.version;candidate.reviewDueAt=new Date(Date.now()+30*86400000).toISOString();candidate.rollbackVersion=s.ruleVersion;candidate.effectiveVersion=++s.ruleVersion;candidate.approvedBy=a.actorId;candidate.status='promoted';touch(candidate);invalidate(s,'Approved procedure changed; prepare a current proposal.');activity(s,a,c.type,'Scoped lesson promoted','Named owner approval and recorded evaluation retained; this is not a measured legal-quality claim.',candidate);return {candidateId:candidate.id,ruleVersion:s.ruleVersion};}
 case 'learning.renew':{const candidate=readRecord(s,a,s.learning,c.candidateId),owner=requireRole(s,a,candidate.kind==='legal_playbook'?'legal_reviewer':'business_owner',candidate);version(candidate,c.expectedRecordVersion);ensure(candidate.status==='promoted'&&candidate.procedureKey&&candidate.evaluationHash===c.evaluationHash&&candidate.evaluation?.qualification==='deterministic_replay_not_legal_quality'&&candidate.evaluation.suiteVersion==='release-evidence-protocol-1'&&candidate.evaluation.candidateFailures===0&&s.receipts[`learning-evaluation:${c.evaluationHash}`],'EXECUTED_EVALUATION_REQUIRED','Renew only the unchanged executable procedure and its frozen passing evidence.');ensure(candidate.evaluatedBy!==a.actorId,'INDEPENDENT_APPROVAL_REQUIRED','The evaluator cannot renew their own policy approval.');candidate.approvedBy=a.actorId;candidate.approvalMembershipVersion=owner.version;candidate.reviewDueAt=new Date(Date.now()+30*86400000).toISOString();touch(candidate);activity(s,a,c.type,'Procedure owner review renewed','The exact unchanged deterministic procedure was reviewed for another 30 days; legal/model quality is not implied.',candidate);return {candidateId:candidate.id,reviewDueAt:candidate.reviewDueAt};}
 case 'learning.rollback':{const candidate=readRecord(s,a,s.learning,c.candidateId);requireRole(s,a,candidate.kind==='legal_playbook'?'legal_reviewer':'business_owner',candidate);version(candidate,c.expectedRecordVersion);ensure(candidate.status==='promoted'&&candidate.effectiveVersion===s.ruleVersion,'ROLLBACK_ORDER','Only the current promoted version can be rolled back.');candidate.affectedMatterIds=s.matters.filter(m=>candidate.appliedMatterIds?.includes(m.id)||m.ruleVersion===candidate.effectiveVersion||s.proposals.some(p=>p.matterId===m.id&&p.dependencies.policyVersion===candidate.effectiveVersion)).map(m=>m.id);candidate.status='rolled_back';s.ruleVersion++;touch(candidate);invalidate(s,'A promoted lesson was rolled back; affected work requires review.');activity(s,a,c.type,'Lesson rolled back',text(c.reason,'a rollback reason',1000),candidate);return {candidateId:candidate.id,affectedMatterIds:candidate.affectedMatterIds};}
 case 'membership.revoke':{requireRole(s,a,'admin');const m=s.memberships.find(x=>x.actorId===c.actorId);ensure(m,'NOT_FOUND','Member not found.',404);m.revokedAt=timestamp();m.version++;for(const approval of s.approvals.filter(x=>x.actorId===c.actorId&&x.status==='active')){approval.status='revoked';touch(approval);}return {revoked:true};}
 case 'event.ingest':return ingestEvent(s,a,c,commandId);
 case 'demo.load':return loadDemo(s,a);
 default:throw new V2Error('UNKNOWN_COMMAND','This command is not supported.',400);
 }
}
function setPreference(s:WorkspaceState,a:ActorContext,key:'response_length'|'interruptions'|'routing',value:string,target:'personal'|'team'){ensure(['response_length','interruptions','routing'].includes(key)&&['personal','team'].includes(target),'INVALID_PREFERENCE','Choose a supported preference.',400);if(target==='team')requireRole(s,a,'business_owner');ensure(key!=='routing'||target==='personal','DELEGATION_REQUIRED','Team routing requires a verified delegation; it cannot be granted through a preference.',403);const scope:Scope=target==='personal'?{kind:'private',actorIds:[a.actorId]}:{kind:'team',actorIds:[]};for(const old of s.preferences.filter(x=>x.ownerId===a.actorId&&x.key===key&&x.target===target&&x.active)){old.active=false;touch(old);}s.preferences.push({...base(s,a,scope),key,value:text(value,'a preference',500),target,ownerId:a.actorId,active:true});}
function ingestEvent(s:WorkspaceState,a:ActorContext,c:Extract<WorkspaceCommand,{type:'event.ingest'}>,commandId:string){
 if(c.provider!=='manual'){requireRole(s,a,'integration');ensure(a.installationId&&a.installationGrant?.installationId===a.installationId,'INSTALLATION_REQUIRED','Events must be authenticated to a configured installation.',403);}else requireRole(s,a,'member');
 const receiptKey=`event:${digest({installation:a.installationId||a.actorId,provider:c.provider,id:text(c.externalEventId,'an event ID',200)})}`;const fingerprint=digest(c);if(s.receipts[receiptKey]){ensure(s.receipts[receiptKey].hash===fingerprint,'EVENT_ID_CONFLICT','This provider event identity was reused with different content.');return s.receipts[receiptKey].result;}
 const scope=requestedScope(s,a,c.scope||{kind:'team',actorIds:[]}),content=text(c.text,'event evidence',100000);ensure(Number.isFinite(Date.parse(c.occurredAt)),'INVALID_TIME','Record a valid event time.',400);
 const previous=s.sources.filter(x=>x.kind===c.provider&&x.externalId===c.externalObjectId).at(-1);const source:Source={...base(s,a,scope),title:text(c.title,'event title',300),kind:c.provider,externalId:text(c.externalObjectId,'external object ID',300),externalRevision:text(c.externalRevision,'external revision',300),text:content,contentHash:digest(content),url:null,status:'active',aclVersion:1,observedAt:timestamp(),effectiveAt:c.occurredAt,authority:'unknown',originalObjectRef:null,...(c.provider!=='manual'?{installationGrant:structuredClone(a.installationGrant)}:{})};ensure(sourceInstallationEligible(s,source),'INSTALLATION_REVOKED','The current installation grant does not authorize this source.',403);s.sources.push(source);
 let matter=c.matterId?readRecord(s,a,s.matters,c.matterId):s.matters.find(m=>c.correlationKey&&m.correlationKeys?.includes(c.correlationKey)&&canRead(s,a,m));
 if(previous&&previous.externalRevision!==source.externalRevision){previous.version++;invalidate(s,'A related source revision changed; current evidence requires review.',previous.id);}
 if(matter){ensure(!matter.legacyWorkflowId,'LEGACY_EXECUTION_OWNER','Do not attach v2 effects to a legacy-owned workflow.');matter.sourceIds.push(source.id);matter.provenance.sourceIds.push(source.id);if(c.correlationKey&&!matter.correlationKeys?.includes(c.correlationKey))(matter.correlationKeys||=[]).push(c.correlationKey);touch(matter);}
 activity(s,a,c.type,matter?'Related event linked':'Uncorrelated event retained','Event evidence does not establish deployment or confirmed company truth.',source,matter?.id||null);const eventId=s.events.at(-1)!.id;if(matter){matter.eventIds.push(eventId);queue(s,matter.id,commandId);}else queue(s,source.id,commandId);const result={eventId,sourceId:source.id,matterId:matter?.id||null,durablyAccepted:true};s.receipts[receiptKey]={hash:fingerprint,result};return result;
}
function loadDemo(s:WorkspaceState,a:ActorContext){requireRole(s,a,'business_owner');ensure(a.mode==='local_demo','REHEARSAL_LOCAL_ONLY','Fictional rehearsal is available only in a local simulated workspace.',403);ensure(!s.matters.length&&!s.documents.length&&!s.facts.length&&!s.messages.length,'WORKSPACE_NOT_EMPTY','Use an empty local workspace for rehearsal. Existing work is preserved.');s.companyName='Northstar · fictional rehearsal';s.rehearsal=true;applyCommand(s,a,{type:'document.add',title:'Acme DPA · fictional executed agreement',body:'Subprocessor changes\nNorthstar will give Acme at least 30 days’ prior written notice before adding a new subprocessor that processes Acme personal data. Acme may object on reasonable data-protection grounds.\n\nExceptions and scope\nThis clause applies to Acme production personal data. Synthetic test data with no personal information is outside this provision. Review the executed agreement and amendments before determining the notice obligation.',authority:'executed',kind:'agreement'},'rehearsal-document');applyCommand(s,a,{type:'fact.propose',predicate:'support_summary_deployment',value:'Not deployed; scenario only',practice:'planned'},'rehearsal-fact');const c=createConversation(s,a,'Explore AI support summaries',{kind:'team',actorIds:[]});activity(s,a,'demo.loaded','Fictional rehearsal loaded','Northstar and Acme records are synthetic. No real customer, counsel or provider result is represented.',c);return {conversationId:c.id,rehearsal:true};}
