import {permittedHistoryRedaction,redactHistoricalWorkspace} from './retention';
import {createHash, randomUUID} from 'node:crypto';
import {mkdir, open, readFile, rename, rm, stat} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {MongoClient} from 'mongodb';
import {V2Error, type WorkspaceState} from './contracts';
import {v2DatabaseName} from './database-target';

export const digest=(value:unknown):string=>createHash('sha256').update(JSON.stringify(sort(value))).digest('hex');
function sort(value:unknown):unknown {if(Array.isArray(value))return value.map(sort);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>[k,sort(v)]));return value;}
export const timestamp=()=>new Date().toISOString();
export function emptyWorkspace(tenantId:string):WorkspaceState {
 return {memoryEntities:[],memoryRelationships:[],scopedPrecedents:[],precedentTargets:[],applicabilityAssessments:[],effortEntries:[],effortBaselines:[],obligations:[],schemaVersion:2,tenantId,version:0,companyName:'Your company',entityId:`entity_${digest(tenantId).slice(0,20)}`,rehearsal:false,memberships:[],conversations:[],messages:[],scenarios:[],facts:[],preferences:[],sources:[],documents:[],legalAuthorities:[],coverage:[],matters:[],proposals:[],approvals:[],actions:[],counsel:[],learning:[],connections:[],events:[],outbox:[],tombstones:[],receipts:{},ruleVersion:1,migration:null};
}
const lists=['memoryEntities','memoryRelationships','scopedPrecedents','precedentTargets','applicabilityAssessments','conversations','messages','scenarios','facts','preferences','sources','documents','legalAuthorities','coverage','matters','proposals','approvals','actions','counsel','learning','connections','events'] as const;
export function validateWorkspace(state:WorkspaceState,before?:WorkspaceState,options:{aggregateLimit?:boolean}={}){
 if(state.schemaVersion!==2||!state.tenantId||!Number.isSafeInteger(state.version))throw new V2Error('STORE_SCHEMA_INVALID','The workspace requires a supported migration.',503);
 for(const list of lists){const ids=new Set<string>();for(const record of state[list]||[]){if(record.tenantId!==state.tenantId||ids.has(record.id)||!Number.isSafeInteger(record.version)||record.version<1)throw new V2Error('STORE_INVARIANT','Invalid scoped record.',503);ids.add(record.id);}}
 for(const obligation of [...state.notificationEnrollments||[],...state.notificationDeliveries||[],...state.strategyFeedback||[],...state.strategyCandidates||[],...state.strategyShadows||[],...state.valueSessions||[],...state.valueGoals||[],...state.valueReceipts||[],...state.templateApprovals||[],...state.drafts||[],...state.legalWatches||[],...state.legalChanges||[],...state.attentionSettings||[],...state.attentionDecisions||[],...state.inventories||[],...state.applicabilityAssessments||[],...state.precedentTargets||[],...state.obligations||[],...state.effortEntries||[],...state.effortBaselines||[]])if(obligation.tenantId!==state.tenantId||!Number.isSafeInteger(obligation.version)||obligation.version<1)throw new V2Error('STORE_INVARIANT','Invalid scoped obligation.',503);
 for(const document of state.documents)if(document.contentHash!==digest(document.body))throw new V2Error('DOCUMENT_INTEGRITY','Document bytes differ from the retained revision.',503);
 if(before){if(before.tenantId!==state.tenantId)throw new V2Error('TENANT_MISMATCH','A transaction cannot change its tenant.',403);for(let i=0;i<before.events.length;i++)if(digest(before.events[i])!==digest(state.events[i])&&!permittedHistoryRedaction(state,'events',before.events[i],state.events[i]))throw new V2Error('IMMUTABLE_HISTORY','Activity history is append-only.');for(const old of before.documents){const next=state.documents.find(x=>x.id===old.id);if(!next||(digest(next)!==digest(old)&&!permittedHistoryRedaction(state,'documents',old,next)))throw new V2Error('IMMUTABLE_DOCUMENT','Create an amendment or successor revision; originals are immutable.');}for(const a of before.actions.filter(a=>['uncertain','verified','dispatching'].includes(a.status))){if(!state.actions.some(x=>x.id===a.id))throw new V2Error('EFFECT_HISTORY_REQUIRED','Retain unresolved and completed action records.');}}
 if(options.aggregateLimit!==false&&Buffer.byteLength(JSON.stringify(state))>12_000_000)throw new V2Error('WORKSPACE_CAPACITY','The bounded local aggregate is full. Existing records remain retained; configure aggregate storage before adding more.',413);
}
function tenantKey(tenantId:string){if(typeof tenantId!=='string'||tenantId.length<1||tenantId.length>200)throw new V2Error('TENANT_REQUIRED','Authenticated tenant identity is required.',401);return digest(tenantId);}
const root=()=>process.env.KIARA_V2_DATA_DIR||join(process.env.KIARA_DATA_DIR||join(process.cwd(),'.kiara'),'v2');
const directory=(tenantId:string)=>join(root(),tenantKey(tenantId));
function persistenceMode(){if(process.env.KIARA_V2_STORE_MODE&&!['aggregate','normalized'].includes(process.env.KIARA_V2_STORE_MODE))throw new V2Error('STORE_MODE_INVALID','Choose aggregate or normalized storage explicitly.',503);if(process.env.KIARA_V2_STORE_MODE==='normalized'){if(!process.env.MONGODB_URI)throw new V2Error('NORMALIZED_STORE_NOT_CONFIGURED','Normalized storage requires MongoDB.',503);return 'normalized';}if(process.env.VERCEL&&!process.env.MONGODB_URI)throw new V2Error('STORE_NOT_CONFIGURED','Hosted v2 workspaces require durable MongoDB storage.',503);return process.env.MONGODB_URI?'mongo':'local';}
/** Secret-free identity for the exact operator data and original stores. */
export function operatorDestinationIdentity(){
 const storageMode=persistenceMode(),database=storageMode==='local'?null:v2DatabaseName(),originalsMode=process.env.KIARA_ORIGINALS_MODE||(process.env.MONGODB_URI?'mongo_encrypted':'local_encrypted');
 const fingerprint=digest({storageMode,database,mongoUri:storageMode==='local'?null:process.env.MONGODB_URI,localRoot:storageMode==='local'?resolve(root()):null,originalsMode,originalsRoot:originalsMode==='local_encrypted'?resolve(process.env.KIARA_ORIGINALS_DIR||join(process.env.KIARA_V2_DATA_DIR||process.env.KIARA_DATA_DIR||join(process.cwd(),'.kiara'),'originals')):null,originalsBucket:originalsMode==='s3_kms'?process.env.KIARA_ORIGINALS_S3_BUCKET:null,originalsRegion:originalsMode==='s3_kms'?process.env.AWS_REGION:null,originalsKmsKey:originalsMode==='s3_kms'?process.env.KIARA_ORIGINALS_KMS_KEY_ID:null,originalsKey:process.env.KIARA_ORIGINALS_KEY||null});
 return {storageMode,database,fingerprint};
}
let client:MongoClient|undefined;let mongoUri:string|undefined;
async function collection(){const uri=process.env.MONGODB_URI!,target=v2DatabaseName();if(client&&mongoUri!==uri)throw new V2Error('STORE_CONFIG_CHANGED','Close the v2 store before changing database configuration.',503);if(!client){mongoUri=uri;client=new MongoClient(uri,{serverSelectionTimeoutMS:5000,maxPoolSize:8});await client.connect();}return client.db(target).collection<{_id:string;version:number;state:WorkspaceState;storageFence?:{mode:string}}>('v2_workspaces');}
async function readLocal(tenantId:string):Promise<WorkspaceState>{try{const envelope=JSON.parse(await readFile(join(directory(tenantId),'workspace.json'),'utf8'));if(envelope.format!==2||envelope.hash!==digest(envelope.state))throw new V2Error('STORE_INTEGRITY','Workspace storage checksum failed.',503);validateWorkspace(envelope.state);if(envelope.state.tenantId!==tenantId)throw new V2Error('TENANT_MISMATCH','Scoped storage identity mismatch.',503);return envelope.state;}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT')return emptyWorkspace(tenantId);throw error;}}
export async function readWorkspace(tenantId:string):Promise<WorkspaceState>{tenantKey(tenantId);if(persistenceMode()==='normalized')return (await import('./normalized-store')).readNormalized(tenantId);if(persistenceMode()==='local')return readLocal(tenantId);await assertAggregateOwner(tenantId);const row=await(await collection()).findOne({_id:tenantId});if(row?.storageFence)throw new V2Error('STORE_MIGRATED','This workspace is owned by normalized storage; update the operator mode.',503);const state=row?.state||emptyWorkspace(tenantId);validateWorkspace(state);return structuredClone(state);}
async function acquire(tenantId:string){const dir=directory(tenantId);await mkdir(dir,{recursive:true,mode:0o700});const lock=join(dir,'write.lock');const recovery=join(dir,'recovery.lock');const token=randomUUID();for(let attempt=0;attempt<600;attempt++){try{await mkdir(lock);const f=await open(join(lock,'owner'),'wx',0o600);try{await f.writeFile(JSON.stringify({pid:process.pid,token}));await f.sync();}finally{await f.close();}return async()=>{const owner=JSON.parse(await readFile(join(lock,'owner'),'utf8'));if(owner.token===token)await rm(lock,{recursive:true,force:true});};}catch(error){if((error as NodeJS.ErrnoException).code!=='EEXIST')throw error;}
 let held=false;try{await mkdir(recovery);held=true;let owner:{pid:number}|null=null;try{owner=JSON.parse(await readFile(join(lock,'owner'),'utf8'));}catch{}const info=await stat(lock).catch(()=>null);let dead=false;if(owner?.pid){try{process.kill(owner.pid,0);}catch(e){dead=(e as NodeJS.ErrnoException).code==='ESRCH';}}if(info&&(dead||(!owner&&Date.now()-info.mtimeMs>30000)))await rm(lock,{recursive:true,force:true});}catch(error){if(!['EEXIST','ENOENT'].includes((error as NodeJS.ErrnoException).code||''))throw error;}finally{if(held)await rm(recovery,{recursive:true,force:true});}await new Promise(resolve=>setTimeout(resolve,15));}throw new V2Error('STORE_BUSY','Workspace is busy. Retry the same command key.',503);}
async function writeLocal(state:WorkspaceState){const dir=directory(state.tenantId),temp=join(dir,`${randomUUID()}.tmp`),f=await open(temp,'wx',0o600);try{await f.writeFile(JSON.stringify({format:2,hash:digest(state),state}));await f.sync();}finally{await f.close();}try{await rename(temp,join(dir,'workspace.json'));const d=await open(dir,'r');try{await d.sync();}finally{await d.close();}}finally{await rm(temp,{force:true});}}
export async function transactWorkspace<T>(tenantId:string,fn:(state:WorkspaceState)=>T):Promise<{state:WorkspaceState;result:T}>{
 tenantKey(tenantId);if(persistenceMode()==='normalized')return (await import('./normalized-store')).transactNormalized(tenantId,fn);
 const apply=(before:WorkspaceState)=>{const state=structuredClone(before),result=fn(state);if(result&&typeof (result as {then?:unknown}).then==='function')throw new V2Error('ASYNC_TRANSACTION','External effects cannot run inside a transaction.',500);validateWorkspace(state,before);const changed=digest(state)!==digest(before);if(changed)state.version=before.version+1;return {state,result:structuredClone(result),changed};};
 if(persistenceMode()==='mongo'){const c=await collection();for(let n=0;n<20;n++){await assertAggregateOwner(tenantId);const row=await c.findOne({_id:tenantId});if(row?.storageFence)throw new V2Error('STORE_MIGRATED','This workspace is owned by normalized storage.',503);const change=apply(row?.state||emptyWorkspace(tenantId));if(!change.changed)return change;if(row){const r=await c.replaceOne({_id:tenantId,version:row.version,storageFence:{$exists:false}},{version:change.state.version,state:change.state});if(r.matchedCount)return change;}else{try{await c.insertOne({_id:tenantId,version:change.state.version,state:change.state});return change;}catch(e){if((e as {code?:number}).code!==11000)throw e;}}}throw new V2Error('STORE_BUSY','Workspace changed. Retry the same command key.',503);}
 const release=await acquire(tenantId);try{const change=apply(await readLocal(tenantId));if(change.changed)await writeLocal(change.state);return change;}finally{await release();}
}
async function assertAggregateOwner(tenantId:string){await collection();const head=await client!.db(v2DatabaseName()).collection('v2_normalized_heads').findOne({_id:tenantId} as never);if(head?.mode==='normalized')throw new V2Error('STORE_MIGRATED','This workspace is owned by normalized storage; update the operator mode.',503);}
export async function closeV2Store(){await (await import('./normalized-store')).closeNormalizedStore();await client?.close();client=undefined;mongoUri=undefined;}
export interface WorkspaceBackup {format:'kiara-v2-backup';createdAt:string;hash:string;state:WorkspaceState}
export async function backupWorkspace(tenantId:string):Promise<WorkspaceBackup>{const state=await readWorkspace(tenantId);return {format:'kiara-v2-backup',createdAt:timestamp(),hash:digest(state),state};}
/** Operator restore is deliberately unavailable over the customer command API. */
export async function restoreWorkspace(backup:WorkspaceBackup,expectedVersion:number,dryRun=true,expectedPlanHash:string|null=null){
 if(backup.format!=='kiara-v2-backup'||backup.hash!==digest(backup.state))throw new V2Error('BACKUP_INTEGRITY','Backup checksum failed.');validateWorkspace(backup.state,undefined,{aggregateLimit:persistenceMode()!=='normalized'});
 const current=await readWorkspace(backup.state.tenantId);if(current.version!==expectedVersion)throw new V2Error('VERSION_CONFLICT','Workspace changed before restore.');
 if(current.version>0&&digest(current)!==backup.hash)throw new V2Error('RESTORE_TARGET_NOT_EMPTY','Restore into an isolated recovery store, then reconcile current access and history before cutover.');
 const destination=operatorDestinationIdentity(),backupHash=digest(backup),destinationStateHash=digest(current),planHash=digest({operation:'restore',tenantId:backup.state.tenantId,backupHash,expectedVersion,destinationStateHash,destination});
 if(!dryRun&&(!expectedPlanHash||expectedPlanHash!==planHash))throw new V2Error('RESTORE_PLAN_CHANGED','The backup or destination differs from the reviewed restore check. Repeat the check before applying.',409);
 // Never roll back identity revocations, accepted commands, tombstones or external effects.
 const restored=structuredClone(backup.state);restored.version=current.version;restored.receipts={...restored.receipts,...current.receipts};restored.deletionJobs=[...new Map([...(restored.deletionJobs||[]),...(current.deletionJobs||[])].map(j=>[j.id,j])).values()];restored.outbox=[...new Map([...restored.outbox,...current.outbox].map(o=>[o.id,o])).values()];restored.tombstones=[...new Map([...restored.tombstones,...current.tombstones].map(t=>[t.sourceId,t])).values()];
 for(const m of current.memberships){const target=restored.memberships.find(x=>x.actorId===m.actorId);if(target)Object.assign(target,m);else restored.memberships.push(m);}
 for(const action of current.actions.filter(x=>['dispatching','uncertain','verifying','verified'].includes(x.status))){const old=restored.actions.find(x=>x.id===action.id);if(old)Object.assign(old,action);else restored.actions.push(action);}
 for(const tombstone of restored.tombstones){const source=restored.sources.find(s=>s.id===tombstone.sourceId);if(source){source.status='deleted';source.text='';}for(const doc of restored.documents.filter(d=>d.sourceId===tombstone.sourceId)){doc.body='';doc.contentHash=digest('');}}
 for(const job of restored.deletionJobs)redactHistoricalWorkspace(restored,job);
 // A nonempty live aggregate cannot have its immutable history rewritten by restore.
 if(current.events.length&&digest(current.events)!==digest(restored.events))throw new V2Error('RESTORE_TARGET_NOT_EMPTY','Restore into an isolated recovery store, then reconcile history before cutover.');
 const result={dryRun,tenantId:restored.tenantId,backupHash,destinationStateHash,destination,planHash,records:lists.reduce((n,k)=>n+(restored[k]||[]).length,0),tombstones:restored.tombstones.length,unresolvedEffects:restored.actions.filter(x=>['uncertain','dispatching'].includes(x.status)).length};
 if(!dryRun)await transactWorkspace(restored.tenantId,state=>{if(state.version!==expectedVersion||digest(state)!==destinationStateHash||operatorDestinationIdentity().fingerprint!==destination.fingerprint)throw new V2Error('RESTORE_PLAN_CHANGED','The reviewed restore destination changed before commit.');if(state.version>0&&digest(state)!==backup.hash)throw new V2Error('RESTORE_TARGET_NOT_EMPTY','Restore target diverged before apply.');Object.assign(state,restored);});return result;
}
