// Server-only custody: this module contains holdout answers and must never enter a client import graph.
import {createHash} from 'node:crypto';
import type {StrategyInput,StrategyKey} from './strategy-algorithms';
export interface StrategyCase {id:string;group:'original'|'near_miss'|'holdout';input:StrategyInput;expected:string|boolean}
const rank=(id:string,group:'near_miss'|'holdout',query:string,correct:string,distractor:string,expected='target'):StrategyCase=>({id,group,input:{kind:'ranking',query,items:[{id:'distractor',title:query,body:distractor},{id:'target',title:'Agreement',body:correct}]},expected});
const fidelity=(id:string,group:'near_miss'|'holdout',instruction:string,before:string,after:string,expected:boolean):StrategyCase=>({id,group,input:{kind:'fidelity',instruction,before,after},expected});
const cases:Record<StrategyKey,StrategyCase[]>={
 exact_clause_reference:[rank('explicit-heading','near_miss','Explain section 5.2','5.2 Notice\nNotice is required.','See section 5.2 in another agreement.'),rank('avoid-prefix-collision','near_miss','Read clause 7.1','7.1 Term\nThe term is three years.','7.10 Renewal\nThis section is different.'),rank('ordinary-question','near_miss','Describe renewal','1. Definitions\nUnrelated definitions.','Renewal requires notice.','distractor'),rank('schedule-exact','holdout','Explain § 12.4','§ 12.4 Audit\nInspect the scope of this clause.','The title repeats § 12.4 but this text has no matching heading.'),rank('parenthetical-heading','holdout','Find clause 8.2(a)','8.2(a) Transfer\nTransfer is limited.','8.2(b) Disclosure\nDifferent permission.'),rank('reference-is-not-heading','holdout','Show section 4.3','4.3 Fees\nAmounts are agreed.','Paragraph says see section 4.3 only.')],
 preserve_material_values:[fidelity('shorten-keeps-term','near_miss','Make it shorter','Notice must be provided at least 30 days beforehand.','Give 30 days prior notice.',true),fidelity('shorten-drops-term','near_miss','Make it shorter','Notice is required 30 days before renewal.','Notice is required before renewal.',false),fidelity('explicit-change','near_miss','Change 30 days to 45 days','Give 30 days notice.','Give 45 days notice.',true),fidelity('calendar-date','holdout','Make it clearer','The effective date is 2027-03-12.','The contract has an effective date.',false),fidelity('decimal-amount','holdout','Simplify this wording','The fee shall be 1250.50 payable within 14 days.','Pay 1250.50 within 14 days.',true),fidelity('drop-percentage','holdout','Make it shorter','Liability is capped at 25% of fees for 12 months.','Liability is capped at fees for 12 months.',false),fidelity('no-numeric-obligation','holdout','Rephrase this sentence','Keep supplied information confidential.','Maintain confidentiality of supplied information.',true)]
};
export function frozenStrategyCases(key:StrategyKey,original:Omit<StrategyCase,'group'|'id'>):StrategyCase[]{return [{id:'original-feedback',group:'original',...structuredClone(original)},...structuredClone(cases[key])];}
export const STRATEGY_CORPUS_HASH=createHash('sha256').update(JSON.stringify({protocol:'strategy-frozen-1',cases})).digest('hex');
