import {randomUUID} from 'node:crypto';
import {canRead,membership,readRecord,requireRole} from './authority';
import {documentHeads} from './document-lifecycle';
import {currentEvidenceLineage} from './source-lifecycle';
import {slackAudienceEligible,scopeAudienceHash} from './integrations/slack-scope';
import {digest,timestamp} from './store';
import {V2Error,type ActorContext,type Conversation,type Message,type Proposal,type RecordBase,type WorkspaceState,type Role} from './contracts';
import type {DraftProposal} from './drafting';
import {clauseReferenceBoost,strategyOutput,type StrategyKey,type StrategyInput,type FidelityInput} from './strategy-algorithms';
import {frozenStrategyCases,STRATEGY_CORPUS_HASH,type StrategyCase} from './strategy-corpus';

export type FeedbackCategory='retrieval_miss'|'drafting_fidelity'|'wording_preference'|'business_preference'|'fact_correction'|'legal_judgment'|'scope_clarification';
export interface StrategyFeedback extends RecordBase {ownerId:string;subjectKind:'message'|'draft'|'proposal';subjectId:string;subjectVersion:number;subjectHash:string;category:FeedbackCategory;detail:string;issueKey?:string|null;status:'active'|'withdrawn';original:{input:StrategyInput;expected:string|boolean}|null;withdrawalReason:string|null}
interface EvaluationCase {id:string;group:StrategyCase['group'];baseline:string|boolean;candidate:string|boolean;expected:string|boolean;passed:boolean}
export interface StrategyEvaluation {corpusHash:string;protocol:'strategy-frozen-1';baselineFailures:number;candidateFailures:number;originalImproved:boolean;caseCount:number;cases:EvaluationCase[];withheldHoldoutCount:number}
export interface StrategyCandidate extends RecordBase {key:StrategyKey;feedbackId:string;feedbackHash:string;title:string;rationale:string;authorId:string;status:'candidate'|'evaluated'|'shadow'|'promoted'|'rolled_back';evaluation:StrategyEvaluation|null;evaluationHash:string|null;evaluatorId:string|null;evaluatorMembershipVersion:number|null;ownerId:string|null;ownerMembershipVersion:number|null;validUntil:string|null;shadowIds:string[];promotionShadowHash:string|null;effectiveVersion:number|null;affectedRecordIds:string[];rollbackReason:string|null}
export interface StrategyShadow extends RecordBase {conversationId:string;references:{kind:'source'|'fact'|'document';id:string;version:number;hash:string}[];candidateId:string;inputHash:string;baselineHash:string;candidateHash:string;changed:boolean;recordId:string;createdBy:string}
export interface FeedbackTarget {kind:StrategyFeedback['subjectKind'];id:string;version:number;hash:string;title:string}
export interface StrategyView {limitations:string[];feedback:Omit<StrategyFeedback,'original'>[];repeatIssues:{issueKey:string;category:FeedbackCategory;occurrences:number;subjectIds:string[]}[];targets:FeedbackTarget[];candidates:(StrategyCandidate&{current:boolean;shadowCount:number;shadowChangedCount:number;shadowHash:string})[]}
type State=WorkspaceState&{strategyFeedback?:StrategyFeedback[];strategyCandidates?:StrategyCandidate[];strategyShadows?:StrategyShadow[]};
export type StrategyCommand=
 |{type:'feedback.record';subjectKind:StrategyFeedback['subjectKind'];subjectId:string;expectedRecordVersion:number;subjectHash:string;category:FeedbackCategory;detail:string;issueKey?:string;expectedDocumentId?:string}
 |{type:'feedback.withdraw';feedbackId:string;expectedRecordVersion:number;reason:string}
 |{type:'strategy.propose';feedbackId:string;expectedFeedbackVersion:number;title:string;rationale:string}
 |{type:'strategy.evaluate';candidateId:string;expectedRecordVersion:number}
 |{type:'strategy.shadow';candidateId:string;expectedRecordVersion:number;evaluationHash:string;validUntil:string}
 |{type:'strategy.promote';candidateId:string;expectedRecordVersion:number;evaluationHash:string;shadowHash:string}
 |{type:'strategy.rollback';candidateId:string;expectedRecordVersion:number;reason:string};
export const strategyCommandFields:Record<StrategyCommand['type'],string[]>={'feedback.record':['subjectKind','subjectId','expectedRecordVersion','subjectHash','category','detail','issueKey','expectedDocumentId'],'feedback.withdraw':['feedbackId','expectedRecordVersion','reason'],'strategy.propose':['feedbackId','expectedFeedbackVersion','title','rationale'],'strategy.evaluate':['candidateId','expectedRecordVersion'],'strategy.shadow':['candidateId','expectedRecordVersion','evaluationHash','validUntil'],'strategy.promote':['candidateId','expectedRecordVersion','evaluationHash','shadowHash'],'strategy.rollback':['candidateId','expectedRecordVersion','reason']};
const need=(v:unknown,code:string,message:string)=>{if(!v)throw new V2Error(code,message);};
function boundedText(v:unknown,name:string,max:number){need(typeof v==='string'&&v.trim().length>0&&v.length<=max,'INVALID_FEEDBACK',`Provide ${name} within ${max} characters.`);return (v as string).trim();}
const touch=(r:RecordBase)=>{r.version++;r.updatedAt=timestamp();};
function base(s:State,a:ActorContext,r:RecordBase,sources=r.provenance.sourceIds):RecordBase{return {id:randomUUID(),tenantId:s.tenantId,version:1,createdAt:timestamp(),updatedAt:timestamp(),scope:structuredClone(r.scope),provenance:{actorId:a.actorId,sourceIds:[...new Set(sources)],factIds:[...r.provenance.factIds||[]],description:'Classified feedback and bounded executable strategy evidence; no automatic factual/legal authority or model-quality claim.'}};}
const role=(c:StrategyCandidate):Role=>c.key==='preserve_material_values'?'legal_reviewer':'business_owner';
function feedback(s:State,id:string){return (s.strategyFeedback||[]).find(f=>f.id===id);}
function subject(s:State,kind:StrategyFeedback['subjectKind'],id:string){return (kind==='message'?s.messages:kind==='draft'?s.drafts||[]:s.proposals).find(r=>r.id===id);}
function subjectVisible(s:State,a:ActorContext,kind:StrategyFeedback['subjectKind'],r:RecordBase):boolean {const container=kind==='proposal'?s.matters.find(m=>m.id===(r as Proposal).matterId):s.conversations.find(c=>c.id===(r as Message|DraftProposal).conversationId);return canRead(s,a,r)&&!!container&&canRead(s,a,container);}
function feedbackVisible(s:State,a:ActorContext,f:StrategyFeedback):boolean {const r=subject(s,f.subjectKind,f.subjectId);return canRead(s,a,f)&&!!r&&subjectVisible(s,a,f.subjectKind,r);}
function candidateVisible(s:State,a:ActorContext,c:StrategyCandidate):boolean {const f=feedback(s,c.feedbackId);return canRead(s,a,c)&&!!f&&feedbackVisible(s,a,f);}
function authority(s:State,c:StrategyCandidate):boolean {try{const f=feedback(s,c.feedbackId);if(!f||f.status!=='active'||digest(f)!==c.feedbackHash||!currentEvidenceLineage(s,c)||!c.ownerId||!c.evaluatorId||!c.validUntil||Date.parse(c.validUntil)<=Date.now()||!Number.isFinite(Date.parse(c.validUntil)))return false;const owner:ActorContext={tenantId:s.tenantId,actorId:c.ownerId,mode:'authenticated',expiresAt:Date.now()+10000},evaluator:ActorContext={...owner,actorId:c.evaluatorId};return feedbackVisible(s,owner,f)&&feedbackVisible(s,evaluator,f)&&requireRole(s,owner,role(c),c).version===c.ownerMembershipVersion&&requireRole(s,evaluator,'evaluator',c).version===c.evaluatorMembershipVersion&&new Set([c.authorId,c.ownerId,c.evaluatorId]).size===3&&(c.status!=='promoted'||shadows(s,c,owner).length>0&&strategyShadowHash(s,c,owner)===c.promotionShadowHash&&strategyShadowHash(s,c,evaluator)===c.promotionShadowHash);}catch{return false;}}
function sameScope(a:RecordBase,b:RecordBase){return scopeAudienceHash(a.scope)===scopeAudienceHash(b.scope);}
function shadowActor(s:State,c:StrategyCandidate):ActorContext{return {tenantId:s.tenantId,actorId:c.ownerId||c.authorId,mode:'authenticated',expiresAt:Date.now()+10000};}
function shadowCurrent(s:State,a:ActorContext,x:StrategyShadow):boolean {try{const conversation=s.conversations.find(c=>c.id===x.conversationId);return !!conversation&&canRead(s,a,conversation)&&canRead(s,a,x)&&currentEvidenceLineage(s,x)&&x.references.every(ref=>{const r=(ref.kind==='source'?s.sources:ref.kind==='fact'?s.facts:s.documents).find(r=>r.id===ref.id);return !!r&&r.version===ref.version&&digest(r)===ref.hash&&canRead(s,a,r)&&currentEvidenceLineage(s,r)&&(ref.kind!=='document'||documentHeads(s.documents).some(d=>d.id===r.id));});}catch{return false;}}
function shadows(s:State,c:StrategyCandidate,a=shadowActor(s,c)){return (s.strategyShadows||[]).filter(x=>x.candidateId===c.id&&c.shadowIds.includes(x.id)&&shadowCurrent(s,a,x));}
export function strategyShadowHash(s:State,c:StrategyCandidate,a=shadowActor(s,c)){return digest(shadows(s,c,a).map(x=>({id:x.id,inputHash:x.inputHash,baselineHash:x.baselineHash,candidateHash:x.candidateHash,references:x.references})));}
function shadowReferences(s:State,input:StrategyInput,sources:string[]){const references:StrategyShadow['references']=[],visited=new Set<string>();const add=(kind:'source'|'fact'|'document',id:string)=>{if(visited.has(kind+id))return;visited.add(kind+id);const r=(kind==='source'?s.sources:kind==='fact'?s.facts:s.documents).find(r=>r.id===id);if(!r)return;references.push({kind,id,version:r.version,hash:digest(r)});for(const sourceId of r.provenance.sourceIds)add('source',sourceId);for(const factId of r.provenance.factIds||[])add('fact',factId);};sources.forEach(id=>add('source',id));if(input.kind==='ranking')input.items.forEach(x=>add('document',x.id));else documentHeads(s.documents).filter(d=>sources.includes(d.sourceId)).forEach(d=>add('document',d.id));return references;}
function active(s:State,a:ActorContext,c:Conversation,key:StrategyKey,status:'shadow'|'promoted'){return (s.strategyCandidates||[]).filter(p=>p.key===key&&p.status===status&&sameScope(p,c)&&candidateVisible(s,a,p)&&authority(s,p));}
/** Only adds rank within the caller's already-authorized records. No text or capability is retrieved here. */
export function retrievalStrategyBoost(s:State,a:ActorContext,c:Conversation,item:{title:string;body:string},query:string){return active(s,a,c,'exact_clause_reference','promoted').length?clauseReferenceBoost(query,item.body):0;}
export function observeStrategyShadow(s:State,a:ActorContext,c:Conversation,key:StrategyKey,input:StrategyInput,recordId:string,sources:string[]=[]){
 for(const candidate of active(s,a,c,key,'shadow')){const inputHash=digest(input);if(shadows(s,candidate).some(x=>x.inputHash===inputHash))continue;const baseline=strategyOutput(input,false),changed=strategyOutput(input,true),references=shadowReferences(s,input,sources);const observed:StrategyShadow={...base(s,a,c,references.filter(x=>x.kind==='source').map(x=>x.id)),conversationId:c.id,references,candidateId:candidate.id,inputHash,baselineHash:digest(baseline),candidateHash:digest(changed),changed:baseline!==changed,recordId,createdBy:a.actorId};observed.provenance.factIds=references.filter(x=>x.kind==='fact').map(x=>x.id);(s.strategyShadows||=[]).push(observed);candidate.shadowIds.push(observed.id);touch(candidate);}
 recordStrategiesApplied(s,a,c,key,recordId);
}
export function recordStrategiesApplied(s:State,a:ActorContext,c:Conversation,key:StrategyKey,recordId:string){for(const candidate of active(s,a,c,key,'promoted'))if(!candidate.affectedRecordIds.includes(recordId)){candidate.affectedRecordIds.push(recordId);touch(candidate);}}
export function observeRetrievalStrategy(s:State,a:ActorContext,c:Conversation,query:string,recordId:string){const documents=documentHeads(s.documents).filter(d=>canRead(s,a,d)&&currentEvidenceLineage(s,d)&&slackAudienceEligible(s,c,d)&&sameScope(d,c)).slice(0,30);observeStrategyShadow(s,a,c,'exact_clause_reference',{kind:'ranking',query,items:documents.map(d=>({id:d.id,title:d.title,body:d.body}))},recordId,documents.map(d=>d.sourceId));}
export function assertDraftStrategy(s:State,a:ActorContext,c:Conversation,input:FidelityInput,recordId:string,sources:string[]=[]){observeStrategyShadow(s,a,c,'preserve_material_values',input,recordId,sources);need(!active(s,a,c,'preserve_material_values','promoted').length||strategyOutput(input,true)===true,'DRAFT_STRATEGY_REVIEW_REQUIRED','The scoped preservation strategy found missing numeric/date values in a meaning-preserving rewrite. Request an explicit substantive change or review the original terms.');}
export function strategyViews(s:State,a:ActorContext):StrategyView {
 const targets:FeedbackTarget[]=[...s.messages.filter(m=>m.role==='assistant').map(r=>({kind:'message' as const,r,title:s.conversations.find(c=>c.id===r.conversationId)?.title||'Answer'})),...(s.drafts||[]).map(r=>({kind:'draft' as const,r,title:r.title})),...s.proposals.map(r=>({kind:'proposal' as const,r,title:r.title}))].filter(x=>subjectVisible(s,a,x.kind,x.r)).map(({kind,r,title})=>({kind,id:r.id,version:r.version,hash:digest(r),title}));
 const visibleFeedback=(s.strategyFeedback||[]).filter(f=>feedbackVisible(s,a,f)),groups=new Map<string,{issueKey:string;category:FeedbackCategory;subjectIds:Set<string>}>();
 for(const item of visibleFeedback.filter(f=>f.status==='active'&&!!f.issueKey)){const key=JSON.stringify([scopeAudienceHash(item.scope),item.category,item.issueKey]),group=groups.get(key)||{issueKey:item.issueKey!,category:item.category,subjectIds:new Set<string>()};group.subjectIds.add(item.subjectId);groups.set(key,group);}
 const repeatIssues=[...groups.values()].filter(group=>group.subjectIds.size>=2).map(group=>({issueKey:group.issueKey,category:group.category,occurrences:group.subjectIds.size,subjectIds:[...group.subjectIds].sort()}));
 return {limitations:['Only two finite catalog behaviors are evaluated. Passing a frozen synthetic corpus and reported original issue does not establish legal quality or generalized learning.','Exact clause ranking affects local exact/keyword retrieval only; Atlas reciprocal rank fusion is unchanged. Shadow comparisons use a bounded same-audience document set, which can differ from the full authorized retrieval population.','The rewrite guard compares literal numeric/date tokens for recognized meaning-preserving requests; it does not validate semantic equivalence, number words or every material term.','Repeat issue counts include only active, accessible feedback with an explicitly reused issue key in the same audience and category. They are attributed reports, not independently adjudicated errors.'],targets,feedback:visibleFeedback.map(f=>{const {original:_o,...view}=structuredClone(f);return view;}),repeatIssues,candidates:(s.strategyCandidates||[]).filter(c=>candidateVisible(s,a,c)).map(c=>{const result=structuredClone(c);const observations=shadows(s,c,a);return {...result,current:authority(s,c),shadowCount:observations.length,shadowChangedCount:observations.filter(x=>x.changed).length,shadowHash:strategyShadowHash(s,c,a)};})};
}
export function applyStrategyCommand(s:State,a:ActorContext,c:StrategyCommand):Record<string,unknown>{
 requireRole(s,a,'member');s.strategyFeedback??=[];s.strategyCandidates??=[];s.strategyShadows??=[];
 if(c.type==='feedback.record'){
  need(['message','draft','proposal'].includes(c.subjectKind),'INVALID_FEEDBACK','Choose a retained feedback target.');const collection:RecordBase[]=c.subjectKind==='message'?s.messages:c.subjectKind==='draft'?s.drafts||[]:s.proposals,subject=readRecord(s,a,collection,c.subjectId);need(subjectVisible(s,a,c.subjectKind,subject),'FEEDBACK_TARGET_UNAVAILABLE','The output and its conversation or matter must remain available.');need(subject.version===c.expectedRecordVersion&&digest(subject)===c.subjectHash,'FEEDBACK_TARGET_CHANGED','Inspect the exact retained output before recording feedback.');need(['retrieval_miss','drafting_fidelity','wording_preference','business_preference','fact_correction','legal_judgment','scope_clarification'].includes(c.category),'INVALID_FEEDBACK','Choose an explicit feedback category.');if(c.category==='legal_judgment')requireRole(s,a,'legal_reviewer',subject);if(c.category==='business_preference')requireRole(s,a,'business_owner',subject);
  let original:StrategyFeedback['original']=null;const sourceIds=[...subject.provenance.sourceIds],factIds=[...subject.provenance.factIds||[]];const include=(record:RecordBase)=>{sourceIds.push(...record.provenance.sourceIds);factIds.push(...record.provenance.factIds||[]);};
  if(c.category==='drafting_fidelity'){need(c.subjectKind==='draft','FEEDBACK_TARGET_REQUIRED','Select the actual proposed rewrite.');const d=subject as DraftProposal;need(d.request.kind==='revision'&&d.request.baseRevisionId,'DRAFT_BASE_REQUIRED','A rewritten draft and its retained baseline are required.');const before=readRecord(s,a,s.documents,d.request.baseRevisionId!);original={input:{kind:'fidelity',instruction:d.request.instruction,before:before.body,after:d.body},expected:false};sourceIds.push(before.sourceId);include(before);}
  if(c.category==='retrieval_miss'){need(c.subjectKind==='message','FEEDBACK_TARGET_REQUIRED','Select the answer with its original question.');const message=s.messages.find(m=>m.id===subject.id)!;need(message.role==='assistant','FEEDBACK_TARGET_REQUIRED','Select an assistant answer.');const conversation=readRecord(s,a,s.conversations,message.conversationId),position=s.messages.findIndex(m=>m.id===message.id),user=message.provenance.messageId?s.messages.find(m=>m.id===message.provenance.messageId):s.messages.slice(0,position).reverse().find(m=>m.conversationId===message.conversationId&&m.role==='user');need(user&&canRead(s,a,user),'FEEDBACK_QUESTION_REQUIRED','The exact retained question is unavailable.');const docs=documentHeads(s.documents).filter(d=>canRead(s,a,d)&&currentEvidenceLineage(s,d)&&sameScope(d,conversation)&&slackAudienceEligible(s,conversation,d));need(docs.length>1&&docs.length<=30&&docs.some(d=>d.id===c.expectedDocumentId)&&docs.reduce((n,d)=>n+d.body.length,0)<=100000,'FEEDBACK_SCOPE_REQUIRED','Choose the expected current document within a bounded same-audience register.');original={input:{kind:'ranking',query:user!.text,items:docs.map(d=>({id:d.id,title:d.title,body:d.body}))},expected:c.expectedDocumentId!};sourceIds.push(...docs.map(d=>d.sourceId));docs.forEach(include);include(user!);}
  const issueKey=c.issueKey?.trim().toLowerCase().replace(/\s+/g,'-')||null;need(!issueKey||/^[a-z0-9][a-z0-9_-]{2,79}$/.test(issueKey),'INVALID_ISSUE_KEY','Use a 3–80 character issue key with letters, numbers, dashes or underscores.');
  const f:StrategyFeedback={...base(s,a,subject,sourceIds),ownerId:a.actorId,subjectKind:c.subjectKind,subjectId:subject.id,subjectVersion:subject.version,subjectHash:c.subjectHash,category:c.category,detail:boundedText(c.detail,'the observed issue and intended behavior',4000),issueKey,status:'active',original,withdrawalReason:null};f.provenance.factIds=[...new Set(factIds)];s.strategyFeedback.push(f);return {feedbackId:f.id,changedFacts:false,changedApprovals:false};
 }
 if(c.type==='feedback.withdraw'){const f=readRecord(s,a,s.strategyFeedback,c.feedbackId);need(feedbackVisible(s,a,f)&&f.ownerId===a.actorId&&f.version===c.expectedRecordVersion,'FEEDBACK_CHANGED','Only the original reporter may withdraw the current feedback.');f.status='withdrawn';f.withdrawalReason=boundedText(c.reason,'the withdrawal reason',2000);touch(f);return {feedbackId:f.id};}
 if(c.type==='strategy.propose'){const f=readRecord(s,a,s.strategyFeedback,c.feedbackId);need(feedbackVisible(s,a,f)&&f.version===c.expectedFeedbackVersion&&f.status==='active'&&f.original,'EXECUTABLE_FEEDBACK_REQUIRED','Select an active original retrieval or drafting issue with replayable inputs.');const record:StrategyCandidate={...base(s,a,f),key:f.category==='retrieval_miss'?'exact_clause_reference':'preserve_material_values',feedbackId:f.id,feedbackHash:digest(f),title:boundedText(c.title,'candidate title',200),rationale:boundedText(c.rationale,'candidate rationale',4000),authorId:a.actorId,status:'candidate',evaluation:null,evaluationHash:null,evaluatorId:null,evaluatorMembershipVersion:null,ownerId:null,ownerMembershipVersion:null,validUntil:null,shadowIds:[],promotionShadowHash:null,effectiveVersion:null,affectedRecordIds:[],rollbackReason:null};s.strategyCandidates.push(record);return {candidateId:record.id};}
 const candidate=readRecord(s,a,s.strategyCandidates,c.candidateId);need(candidateVisible(s,a,candidate),'STRATEGY_UNAVAILABLE','The strategy and its original output container must remain available.');need(candidate.version===c.expectedRecordVersion,'VERSION_CONFLICT','Inspect the current strategy candidate.');const origin=feedback(s,candidate.feedbackId);need(c.type==='strategy.rollback'||origin&&origin.status==='active'&&digest(origin)===candidate.feedbackHash&&currentEvidenceLineage(s,candidate),'STRATEGY_BASIS_CHANGED','Feedback or its supporting evidence changed.');
 if(c.type==='strategy.evaluate'){const evaluator=requireRole(s,a,'evaluator',candidate);need(a.actorId!==candidate.authorId&&['candidate','evaluated'].includes(candidate.status),'INDEPENDENT_EVALUATOR_REQUIRED','An independent evaluator must replay the unchanged candidate.');const rows=frozenStrategyCases(candidate.key,origin!.original!).map(t=>{const baseline=strategyOutput(t.input,false),next=strategyOutput(t.input,true);return {id:t.id,group:t.group,baseline,candidate:next,expected:t.expected,passed:next===t.expected};}),evaluation:StrategyEvaluation={corpusHash:STRATEGY_CORPUS_HASH,protocol:'strategy-frozen-1',baselineFailures:rows.filter(x=>x.baseline!==x.expected).length,candidateFailures:rows.filter(x=>!x.passed).length,originalImproved:rows[0].baseline!==rows[0].expected&&rows[0].passed,caseCount:rows.length,cases:rows,withheldHoldoutCount:0};candidate.evaluation={...evaluation,cases:rows.filter(x=>x.group!=='holdout'),withheldHoldoutCount:rows.filter(x=>x.group==='holdout').length};candidate.evaluatorId=a.actorId;candidate.evaluatorMembershipVersion=evaluator.version;candidate.status='evaluated';touch(candidate);candidate.evaluationHash=digest({candidateId:candidate.id,version:candidate.version,key:candidate.key,feedbackHash:candidate.feedbackHash,evaluation,actorId:a.actorId});s.receipts[`strategy-evaluation:${candidate.evaluationHash}`]={hash:candidate.evaluationHash,result:{candidateId:candidate.id,evaluation,feedbackHash:candidate.feedbackHash,key:candidate.key}};return {candidateId:candidate.id,evaluationHash:candidate.evaluationHash};}
 const owner=requireRole(s,a,role(candidate),candidate);need(a.actorId!==candidate.authorId&&a.actorId!==candidate.evaluatorId,'INDEPENDENT_OWNER_REQUIRED','Candidate author, evaluator and adoption owner must be three different people.');
 if(c.type==='strategy.rollback'){need(candidate.status==='promoted'||candidate.status==='shadow','STRATEGY_NOT_ACTIVE','Only an active strategy can be stopped.');candidate.status='rolled_back';candidate.rollbackReason=boundedText(c.reason,'the rollback reason',2000);s.ruleVersion++;touch(candidate);return {candidateId:candidate.id,affectedRecordIds:candidate.affectedRecordIds,ruleVersion:s.ruleVersion};}
 need(candidate.evaluationHash===c.evaluationHash&&candidate.evaluation?.originalImproved&&candidate.evaluation.candidateFailures===0&&candidate.evaluation.baselineFailures>0&&s.receipts[`strategy-evaluation:${c.evaluationHash}`]?.result.candidateId===candidate.id,'EXECUTED_STRATEGY_EVALUATION_REQUIRED','A server-executed frozen comparison must improve the original issue without frozen regressions.');
 if(c.type==='strategy.shadow'){need(candidate.status==='evaluated','STRATEGY_STATE','Evaluate before starting a no-effect shadow.');need(Number.isFinite(Date.parse(c.validUntil))&&Date.parse(c.validUntil)>Date.now()&&Date.parse(c.validUntil)<=Date.now()+30*86400000,'INVALID_EXPIRY','Choose an expiry within 30 days.');candidate.ownerId=a.actorId;candidate.ownerMembershipVersion=owner.version;candidate.validUntil=new Date(c.validUntil).toISOString();candidate.status='shadow';touch(candidate);need(authority(s,candidate),'STRATEGY_AUTHORITY_CHANGED','Evaluator or owner authority changed.');return {candidateId:candidate.id};}
 need(candidate.ownerId===a.actorId&&candidate.ownerMembershipVersion===owner.version&&candidate.status==='shadow'&&authority(s,candidate)&&shadows(s,candidate).length>0&&strategyShadowHash(s,candidate)===c.shadowHash,'SHADOW_REVIEW_REQUIRED','Inspect actual no-effect shadow observations before controlled adoption.');need(!s.strategyCandidates.some(p=>p.id!==candidate.id&&p.key===candidate.key&&p.status==='promoted'&&sameScope(p,candidate)&&authority(s,p)),'STRATEGY_ALREADY_ACTIVE','Roll back the active scoped strategy before replacing it.');candidate.status='promoted';candidate.promotionShadowHash=c.shadowHash;candidate.effectiveVersion=++s.ruleVersion;touch(candidate);return {candidateId:candidate.id,ruleVersion:s.ruleVersion};
}

/** Provider runs pin only active behavior policy identity; observational counters cannot change authority. */
export function strategyPolicyFingerprint(s:State,a:ActorContext,c:Conversation){return digest({protocol:'bounded-strategy-1',policies:(s.strategyCandidates||[]).filter(p=>p.status==='promoted'&&sameScope(p,c)&&candidateVisible(s,a,p)&&authority(s,p)).map(p=>({id:p.id,key:p.key,effectiveVersion:p.effectiveVersion,evaluationHash:p.evaluationHash,ownerId:p.ownerId,ownerMembershipVersion:p.ownerMembershipVersion,validUntil:p.validUntil})).sort((a,b)=>a.id.localeCompare(b.id))});}
