import {randomUUID} from 'node:crypto';
import {canRead,readRecord,requireRole} from './authority';
import {currentEvidenceLineage} from './source-lifecycle';
import {withinConversationAudience} from './retrieval';
import {routedTaskOwner} from './collaboration';
import {digest,timestamp} from './store';
import {V2Error,type ActorContext,type Conversation,type Matter,type MatterTask,type Proposal,type WorkspaceState} from './contracts';
const titles={business:'Review the exact business proposal',legal:'Obtain qualified legal review of the exact proposal'};
/** Compatibility applies only to service-created historical gates, never generated planned tasks. */
export function isProposalReviewTask(task:MatterTask){return ['business','legal'].includes(task.kind)&&(task.purpose==='proposal_review'||task.purpose===undefined&&task.requiredFactPredicates===undefined&&[titles[task.kind as keyof typeof titles],task.kind==='business'?'Review the exact internal preparation and its approved purpose':'Current standing approval for unchanged template terms'].includes(task.title));}
/** Required review gates remain separate from substantive business/legal work. */
export function resetReviewTasks(s:WorkspaceState,m:Matter,_proposal?:Proposal){
 for(const kind of ['business','legal'] as const){let task=m.tasks.find(t=>t.kind===kind&&isProposalReviewTask(t));const reviewer=s.memberships.find(member=>member.roles.includes('legal_reviewer')&&!member.revokedAt&&(!member.expiresAt||Date.parse(member.expiresAt)>Date.now())&&(!member.matterIds||member.matterIds.includes(m.id))&&(!member.entityIds||member.entityIds.includes(m.entityId)));
  if(!task){task={id:randomUUID(),title:titles[kind],purpose:'proposal_review',ownerId:kind==='legal'?reviewer?.actorId||m.ownerId:m.ownerId,status:'pending',kind,dueAt:null,deadlineType:'undated',evidenceIds:[]};m.tasks.push(task);}else{task.purpose='proposal_review';task.status='pending';task.evidenceIds=[];}
 }
}
export type TaskCommand={type:'matter.task_complete';matterId:string;taskId:string;expectedRecordVersion:number;evidenceSourceIds:string[];evidenceSourceVersions:Record<string,number>;evidenceSourceHashes:Record<string,string>;evidenceSourceDependencyHashes:Record<string,string>;note:string};
export const taskCommandFields={'matter.task_complete':['matterId','taskId','expectedRecordVersion','evidenceSourceIds','evidenceSourceVersions','evidenceSourceHashes','evidenceSourceDependencyHashes','note']};
const need=(v:unknown,code:string,message:string)=>{if(!v)throw new V2Error(code,message);};
export function completeMatterTask(s:WorkspaceState,a:ActorContext,c:TaskCommand){
 const m=readRecord(s,a,s.matters,c.matterId),task=m.tasks.find(t=>t.id===c.taskId);need(m.version===c.expectedRecordVersion,'VERSION_CONFLICT','Inspect the current task and matter before recording completion.');need(task&&!isProposalReviewTask(task)&&task.purpose!=='artifact_review'&&['business','legal'].includes(task.kind)&&(task.status!=='done'||!taskCompletionCurrent(s,a,m,task))&&!['closed','canceled'].includes(m.state)&&!m.legacyWorkflowId,'TASK_NOT_COMPLETABLE','Only pending substantive business/legal work can receive an owned completion attestation.');const member=requireRole(s,a,task!.kind==='legal'?'legal_reviewer':'business_owner',m),effectiveOwner=routedTaskOwner(s,m,{...task!,status:'pending'});need(effectiveOwner===a.actorId,'TASK_OWNER_REQUIRED','The current assigned owner must attest their completed work.');need(typeof c.note==='string'&&c.note.trim().length>0&&c.note.length<=4000&&Array.isArray(c.evidenceSourceIds)&&c.evidenceSourceIds.length>0&&c.evidenceSourceIds.length<=20,'TASK_EVIDENCE_REQUIRED','Retain current evidence and a short account of the completed work.');
 const ids=[...new Set(c.evidenceSourceIds)],sources=ids.map(id=>readRecord(s,a,s.sources,id));need([c.evidenceSourceVersions,c.evidenceSourceHashes,c.evidenceSourceDependencyHashes].every(map=>map&&typeof map==='object'&&!Array.isArray(map)&&digest(Object.keys(map).sort())===digest([...ids].sort()))&&sources.every(source=>source.version===c.evidenceSourceVersions[source.id]&&source.contentHash===c.evidenceSourceHashes[source.id]&&sourceDependencyHash(s,[source.id])===c.evidenceSourceDependencyHashes[source.id]),'TASK_EVIDENCE_CHANGED','Inspect the exact current evidence and its dependency versions before attesting completion.');need(sources.every(source=>currentEvidenceLineage(s,source)&&withinConversationAudience(s,m as unknown as Conversation,source)),'TASK_EVIDENCE_SCOPE','Completion evidence and its dependencies must remain current in this exact matter audience.');task!.purpose='work';task!.status='done';task!.evidenceIds=sources.map(x=>x.id);task!.completion={kind:'human_attestation',actorId:a.actorId,membershipVersion:member.version,at:timestamp(),note:c.note.trim(),sourceIds:task!.evidenceIds,sourceVersions:Object.fromEntries(sources.map(x=>[x.id,x.version])),proofHash:sourceDependencyHash(s,ids)};m.sourceIds=[...new Set([...m.sourceIds,...task!.evidenceIds])];m.provenance.sourceIds=[...new Set([...m.provenance.sourceIds,...task!.evidenceIds])];if(m.proposalId){const p=s.proposals.find(x=>x.id===m.proposalId);if(p){p.status='invalidated';p.version++;p.updatedAt=timestamp();}for(const approval of s.approvals.filter(x=>x.proposalId===m.proposalId&&x.status==='active')){approval.status='invalidated';approval.version++;approval.updatedAt=timestamp();}m.state='needs_facts';m.blockers=['Completed work evidence changed the review basis. Prepare and review a current packet.'];resetReviewTasks(s,m);}m.version++;m.updatedAt=timestamp();s.events.push({id:randomUUID(),tenantId:s.tenantId,version:1,createdAt:timestamp(),updatedAt:timestamp(),scope:structuredClone(m.scope),provenance:{actorId:a.actorId,sourceIds:task!.evidenceIds,description:'Named owner human attestation of substantive work; no proposal approval or provider verification inferred.'},type:'matter.task_completed',title:'Owned work completion attested',detail:c.note.trim(),matterId:m.id,recordId:m.id,measurement:s.rehearsal?'fictional_rehearsal':'observed'});return {matterId:m.id,taskId:task!.id,completion:'human_attestation'};
}
export function taskCompletionCurrent(s:WorkspaceState,a:ActorContext,m:Matter,task:MatterTask){if(!task.completion)return !(['business','legal'].includes(task.kind)&&!isProposalReviewTask(task)&&task.purpose!=='artifact_review'&&(task.purpose==='work'||task.requiredFactPredicates!==undefined));const completion=task.completion,member=s.memberships.find(x=>x.actorId===completion.actorId);return completion.proofHash===sourceDependencyHash(s,completion.sourceIds)&&!!member&&!member.revokedAt&&member.version===completion.membershipVersion&&(!member.expiresAt||Date.parse(member.expiresAt)>Date.now())&&member.roles.includes(task.kind==='legal'?'legal_reviewer':'business_owner')&&completion.sourceIds.every(id=>{const source=s.sources.find(x=>x.id===id);return !!source&&source.version===completion.sourceVersions?.[id]&&canRead(s,a,source)&&currentEvidenceLineage(s,source)&&withinConversationAudience(s,m as unknown as Conversation,source);});}

/** Snapshot proof hash covers the retained source graph, including source-free confirmed facts. */
export function sourceDependencyHash(s:WorkspaceState,sourceIds:string[]){const sources=new Map<string,string>(),facts=new Map<string,string>();const visit=(kind:'source'|'fact',id:string)=>{const map=kind==='source'?sources:facts;if(map.has(id))return;const record=(kind==='source'?s.sources:s.facts).find(x=>x.id===id);map.set(id,record?digest(record):'missing');if(!record)return;record.provenance.sourceIds.forEach(id=>visit('source',id));(record.provenance.factIds||[]).forEach(id=>visit('fact',id));};sourceIds.forEach(id=>visit('source',id));return digest({sources:[...sources].sort(([a],[b])=>a.localeCompare(b)),facts:[...facts].sort(([a],[b])=>a.localeCompare(b))});}
export function taskView(s:WorkspaceState,a:ActorContext,m:Matter,t:MatterTask):MatterTask{const current=taskCompletionCurrent(s,a,m,t),base=s.matters.find(x=>x.id===m.id)?.tasks.find(x=>x.id===t.id)||t;return {...t,purpose:t.purpose||(isProposalReviewTask(t)?'proposal_review':'work'),ownerId:routedTaskOwner(s,m,!current?{...base,status:'pending'}:base),...((t.completion||!current)?{completionCurrent:current}:{})};}
