import {randomUUID} from 'node:crypto';
import {canRead,membership,readRecord,requireRole} from './authority';
import {currentEvidenceLineage} from './source-lifecycle';
import {assertDraftEvidence,type DraftProposal} from './drafting';
import {digest,timestamp} from './store';
import {V2Error,type ActorContext,type Message,type Proposal,type RecordBase,type Scenario,type WorkspaceState} from './contracts';

export type ValueOutputKind='answer'|'scenario'|'draft'|'proposal';
export interface ValueSession extends RecordBase {ownerId:string;observedStartedAt:string;baselineKind:'observed_command'|'earliest_retained_work';measurement:'observed'|'fictional_rehearsal';firstGeneratedAt:string|null;firstUsefulReceiptId:string|null}
export interface ValueGoal extends RecordBase {ownerId:string;sessionId:string;title:string;successCriteria:string;conversationId:string|null;status:'working'|'reported_achieved';outcomeNote:string|null;outcomeReceiptId:string|null}
export interface ValueReceipt extends RecordBase {ownerId:string;sessionId:string;goalId:string;outputKind:ValueOutputKind;outputId:string;outputVersion:number;outputHash:string;outputTitle:string;outputCreatedAt:string;disposition:'useful'|'needs_work';reason:string;status:'current'|'withdrawn';withdrawalReason:string|null}
export interface ValueOutputView {kind:ValueOutputKind;id:string;version:number;hash:string;title:string;body:string;createdAt:string;conversationId:string|null}
export interface ValueReport {population:'current_actor_authorized_records';measurement:'observed'|'fictional_rehearsal'|'not_started';baselineKind:ValueSession['baselineKind']|null;firstGeneratedElapsedMs:number|null;firstUsefulElapsedMs:number|null;firstUsefulState:'not_recorded'|'available'|'unavailable'|'rehearsal_excluded';usefulOutputCount:number;needsWorkCount:number;workingGoalCount:number;reportedAchievedGoalCount:number;interpretation:string}
export interface ValueGoalView extends ValueGoal {outcomeAvailable:boolean}
export interface ValueView {session:ValueSession|null;goals:ValueGoalView[];receipts:ValueReceipt[];outputs:ValueOutputView[];report:ValueReport}
export type ValueCommand=
 |{type:'value.goal.define';title:string;successCriteria:string;conversationId?:string}
 |{type:'value.goal.assess';goalId:string;expectedRecordVersion:number;disposition:'working'|'reported_achieved';receiptId?:string;reason:string}
 |{type:'value.output.assess';goalId:string;expectedGoalVersion:number;outputKind:ValueOutputKind;outputId:string;expectedOutputVersion:number;outputHash:string;disposition:'useful'|'needs_work';reason:string}
 |{type:'value.receipt.withdraw';receiptId:string;expectedRecordVersion:number;reason:string};
export const valueCommandFields:Record<ValueCommand['type'],string[]>={'value.goal.define':['title','successCriteria','conversationId'],'value.goal.assess':['goalId','expectedRecordVersion','disposition','receiptId','reason'],'value.output.assess':['goalId','expectedGoalVersion','outputKind','outputId','expectedOutputVersion','outputHash','disposition','reason'],'value.receipt.withdraw':['receiptId','expectedRecordVersion','reason']};
type State=WorkspaceState&{valueSessions?:ValueSession[];valueGoals?:ValueGoal[];valueReceipts?:ValueReceipt[]};
type OutputRecord=Message|Scenario|DraftProposal|Proposal;
const ensure=(condition:unknown,code:string,message:string)=>{if(!condition)throw new V2Error(code,message);};
function text(value:unknown,label:string,max:number){ensure(typeof value==='string'&&!!value.trim()&&value.length<=max,'INVALID_VALUE_INPUT',`Provide ${label} within ${max} characters.`);return (value as string).trim();}
function base(s:State,a:ActorContext,record?:RecordBase):RecordBase{return {id:randomUUID(),tenantId:s.tenantId,version:1,createdAt:timestamp(),updatedAt:timestamp(),scope:{kind:'private',actorIds:[a.actorId]},provenance:{actorId:a.actorId,sourceIds:[...record?.provenance.sourceIds||[]],factIds:[...record?.provenance.factIds||[]],description:'Attributed usefulness or goal report; not legal approval, company truth, work completion or validated savings.'}};}
function touch(record:RecordBase){record.version++;record.updatedAt=timestamp();}
function own<T extends RecordBase&{ownerId:string}>(s:State,a:ActorContext,records:T[],id:string){const record=readRecord(s,a,records,id);ensure(record.ownerId===a.actorId,'VALUE_OWNER_REQUIRED','Only the reporting person can change this record.');return record;}
function session(s:State,a:ActorContext){return (s.valueSessions||[]).find(r=>r.ownerId===a.actorId&&canRead(s,a,r));}
/** Call inside the command transaction, before the first meaningful request mutates state. */
export function observeValueWork(s:State,a:ActorContext,type:string){
 if(!['message.send','document.add','document.reimport','value.goal.define'].includes(type))return;
 requireRole(s,a,'member');if(session(s,a))return;
 const prior=[...s.messages.filter(m=>m.role==='user'),...s.documents].filter(r=>r.provenance.actorId===a.actorId&&canRead(s,a,r)).map(r=>Date.parse(r.createdAt)).filter(Number.isFinite),now=Date.now(),earliest=prior.length?Math.min(...prior,now):now;
 const record:ValueSession={...base(s,a),ownerId:a.actorId,observedStartedAt:new Date(earliest).toISOString(),baselineKind:prior.length?'earliest_retained_work':'observed_command',measurement:s.rehearsal?'fictional_rehearsal':'observed',firstGeneratedAt:null,firstUsefulReceiptId:null};(s.valueSessions||=[]).push(record);
}
function sourceLineage(s:State,r:RecordBase){const sources=new Set<string>(),facts=new Set<string>();const visit=(record:RecordBase)=>{for(const id of record.provenance.sourceIds){if(sources.has(id))continue;sources.add(id);const source=s.sources.find(x=>x.id===id);if(source)visit(source);}for(const id of record.provenance.factIds||[]){if(facts.has(id))continue;facts.add(id);const fact=s.facts.find(x=>x.id===id);if(fact)visit(fact);}};visit(r);return {sources:[...sources].sort().map(id=>{const x=s.sources.find(r=>r.id===id);return {id,version:x?.version,hash:x?.contentHash};}),facts:[...facts].sort().map(id=>{const x=s.facts.find(r=>r.id===id);return {id,version:x?.version};})};}
function output(s:State,a:ActorContext,kind:ValueOutputKind,r:OutputRecord):ValueOutputView|null{
 if(!canRead(s,a,r)||!currentEvidenceLineage(s,r))return null;
 let title:string,body:string,conversationId:string|null=null;
 if(kind==='answer'){const m=r as Message,c=s.conversations.find(c=>c.id===m.conversationId);if(m.role!=='assistant'||!c||!canRead(s,a,c))return null;title=c.title;body=m.text;conversationId=c.id;}
 else if(kind==='scenario'){const v=r as Scenario,c=s.conversations.find(c=>c.id===v.conversationId);if(v.status==='withdrawn'||!c||!canRead(s,a,c))return null;title=v.title;body=`Assumptions\n${v.assumptions.join('\n')}\n\nOpen questions\n${v.questions.join('\n')}`;conversationId=c.id;}
 else if(kind==='draft'){const d=r as DraftProposal,c=s.conversations.find(c=>c.id===d.conversationId);if(!['proposed','accepted'].includes(d.status)||!d.body.trim()||!c||!canRead(s,a,c))return null;try{assertDraftEvidence(s,a,d);}catch{return null;}title=d.title;body=d.body;conversationId=c.id;}
 else {const p=r as Proposal,m=s.matters.find(m=>m.id===p.matterId);if(p.status!=='current'||!m||!canRead(s,a,m))return null;title=p.title;body=p.body;conversationId=m.conversationIds.find(id=>s.conversations.some(c=>c.id===id&&canRead(s,a,c)))||null;}
 return {kind,id:r.id,version:r.version,hash:digest({kind,record:r,lineage:sourceLineage(s,r)}),title,body,createdAt:r.createdAt,conversationId};
}
function records(s:State,kind:ValueOutputKind):OutputRecord[]{return kind==='answer'?s.messages:kind==='scenario'?s.scenarios:kind==='draft'?s.drafts||[]:s.proposals;}
function outputs(s:State,a:ActorContext){return (['answer','scenario','draft','proposal'] as const).flatMap(kind=>records(s,kind).flatMap(r=>{const view=output(s,a,kind,r);return view?[view]:[]}));}
/** Called after command output or async answer commit. Never mutate a read projection. */
export function observeValueOutputs(s:State,a:ActorContext){try{membership(s,a)}catch{return;}const started=session(s,a);if(!started||started.firstGeneratedAt)return;const times=outputs(s,a).filter(v=>records(s,v.kind).find(r=>r.id===v.id)?.provenance.actorId===a.actorId&&Date.parse(v.createdAt)>=Date.parse(started.observedStartedAt)).map(v=>Date.parse(v.createdAt));if(times.length){started.firstGeneratedAt=new Date(Math.min(...times)).toISOString();touch(started);}}
function goalVisible(s:State,a:ActorContext,g:ValueGoal){return g.ownerId===a.actorId&&canRead(s,a,g)&&(!g.conversationId||s.conversations.some(c=>c.id===g.conversationId&&canRead(s,a,c)));}
function receiptVisible(s:State,a:ActorContext,r:ValueReceipt){const origin=records(s,r.outputKind).find(x=>x.id===r.outputId);if(!origin||!canRead(s,a,origin))return false;const container=r.outputKind==='proposal'?s.matters.find(m=>m.id===(origin as Proposal).matterId):s.conversations.find(c=>c.id===(origin as Message|Scenario|DraftProposal).conversationId);return r.ownerId===a.actorId&&canRead(s,a,r)&&!!container&&canRead(s,a,container)&&!!s.valueGoals?.some(g=>g.id===r.goalId&&goalVisible(s,a,g));}
export function valueView(s:State,a:ActorContext):ValueView{
 membership(s,a);const started=session(s,a),goals=(s.valueGoals||[]).filter(g=>goalVisible(s,a,g)),receipts=(s.valueReceipts||[]).filter(r=>receiptVisible(s,a,r)),current=receipts.filter(r=>r.status==='current'),first=started?.firstUsefulReceiptId?current.find(r=>r.id===started.firstUsefulReceiptId):null,rehearsal=s.rehearsal||started?.measurement==='fictional_rehearsal';
 const elapsed=(at:string|null|undefined)=>at&&started?Math.max(0,Date.parse(at)-Date.parse(started.observedStartedAt)):null;
 const report:ValueReport={population:'current_actor_authorized_records',measurement:started?(rehearsal?'fictional_rehearsal':'observed'):'not_started',baselineKind:started?.baselineKind??null,firstGeneratedElapsedMs:rehearsal?null:elapsed(started?.firstGeneratedAt),firstUsefulElapsedMs:rehearsal?null:elapsed(first?.createdAt),firstUsefulState:rehearsal?'rehearsal_excluded':!started?.firstUsefulReceiptId?'not_recorded':first?'available':'unavailable',usefulOutputCount:rehearsal?0:current.filter(r=>r.disposition==='useful').length,needsWorkCount:rehearsal?0:current.filter(r=>r.disposition==='needs_work').length,workingGoalCount:rehearsal?0:goals.filter(g=>g.status==='working').length,reportedAchievedGoalCount:rehearsal?0:goals.filter(g=>g.status==='reported_achieved'&&current.some(r=>r.id===g.outcomeReceiptId&&r.disposition==='useful')).length,interpretation:'Current actor only. Usefulness and goal achievement are attributed historical user reports, not current output eligibility, legal correctness or matter completion. A newer output or evidence version requires a new exact assessment. Elapsed time includes idle time, is separate from human effort and is not savings. Rehearsals are excluded. An earliest-retained-work baseline can have incomplete history; an unavailable first receipt is never replaced with a later favorable result.'};
 return {session:started?structuredClone(started):null,goals:goals.map(g=>({...structuredClone(g),outcomeAvailable:current.some(r=>r.id===g.outcomeReceiptId&&r.disposition==='useful')})),receipts:structuredClone(receipts),outputs:outputs(s,a),report};
}
export function applyValueCommand(s:State,a:ActorContext,c:ValueCommand):Record<string,unknown>{
 requireRole(s,a,'member');s.valueGoals??=[];s.valueReceipts??=[];
 if(c.type==='value.goal.define'){observeValueWork(s,a,c.type);const conversation=c.conversationId?readRecord(s,a,s.conversations,c.conversationId):null;const goal:ValueGoal={...base(s,a,conversation??undefined),ownerId:a.actorId,sessionId:session(s,a)!.id,title:text(c.title,'the intended useful result',300),successCriteria:text(c.successCriteria,'the success criteria',2000),conversationId:conversation?.id||null,status:'working',outcomeNote:null,outcomeReceiptId:null};s.valueGoals.push(goal);return {goalId:goal.id};}
 if(c.type==='value.receipt.withdraw'){const r=own(s,a,s.valueReceipts,c.receiptId);ensure(receiptVisible(s,a,r)&&r.version===c.expectedRecordVersion&&r.status==='current','VALUE_RECEIPT_CHANGED','Inspect your current available usefulness receipt.');r.status='withdrawn';r.withdrawalReason=text(c.reason,'the correction reason',2000);touch(r);return {receiptId:r.id};}
 const goal=own(s,a,s.valueGoals,c.goalId);ensure(goalVisible(s,a,goal),'VALUE_GOAL_UNAVAILABLE','This goal is no longer available.');
 if(c.type==='value.goal.assess'){ensure(goal.version===c.expectedRecordVersion,'VERSION_CONFLICT','Inspect the current goal before reporting progress.');ensure(['working','reported_achieved'].includes(c.disposition),'INVALID_GOAL_STATE','Report ongoing work or your observed goal achievement.');const reason=text(c.reason,'your observed result and limits',2000);if(c.disposition==='reported_achieved'){const r=c.receiptId?s.valueReceipts.find(r=>r.id===c.receiptId):null;ensure(r&&receiptVisible(s,a,r)&&r.goalId===goal.id&&r.status==='current'&&r.disposition==='useful','USEFUL_RECEIPT_REQUIRED','Choose your available useful-output receipt for this exact goal.');goal.outcomeReceiptId=r!.id;}else goal.outcomeReceiptId=null;goal.status=c.disposition;goal.outcomeNote=reason;touch(goal);return {goalId:goal.id};}
 ensure(goal.version===c.expectedGoalVersion,'VERSION_CONFLICT','Inspect the current goal before assessing an output.');ensure(['answer','scenario','draft','proposal'].includes(c.outputKind),'INVALID_OUTPUT_KIND','Choose a prepared answer, scenario, draft or proposal.');const origin=records(s,c.outputKind).find(r=>r.id===c.outputId),view=origin?output(s,a,c.outputKind,origin):null;ensure(view&&view.version===c.expectedOutputVersion&&view.hash===c.outputHash,'VALUE_OUTPUT_CHANGED','Inspect the current exact output and its evidence before assessing usefulness.');ensure(!goal.conversationId||view!.conversationId===goal.conversationId,'VALUE_GOAL_SCOPE','This output belongs to a different conversation.');ensure(['useful','needs_work'].includes(c.disposition),'INVALID_VALUE_DECISION','Choose useful or needs work.');ensure(!s.valueReceipts.some(r=>r.ownerId===a.actorId&&r.goalId===goal.id&&r.outputHash===view!.hash&&r.status==='current'),'VALUE_ALREADY_ASSESSED','This exact output already has your current report for this goal.');const reason=text(c.reason,'what was useful or still missing',2000),started=session(s,a);ensure(started&&goal.sessionId===started.id,'VALUE_SESSION_REQUIRED','The goal needs its observed first-work baseline.');
 const r:ValueReceipt={...base(s,a,origin!),ownerId:a.actorId,sessionId:started!.id,goalId:goal.id,outputKind:c.outputKind,outputId:view!.id,outputVersion:view!.version,outputHash:view!.hash,outputTitle:view!.title,outputCreatedAt:view!.createdAt,disposition:c.disposition,reason,status:'current',withdrawalReason:null};s.valueReceipts.push(r);goal.provenance.sourceIds=[...new Set([...goal.provenance.sourceIds,...r.provenance.sourceIds])];goal.provenance.factIds=[...new Set([...goal.provenance.factIds||[],...r.provenance.factIds||[]])];touch(goal);if(c.disposition==='useful'&&!started!.firstUsefulReceiptId){started!.firstUsefulReceiptId=r.id;touch(started!);}return {receiptId:r.id,goalId:goal.id};
}
