import type {Assessment,Fact,Workflow,Revision} from '../server/contracts';
export function assess(facts:Fact[]):Assessment {const by=new Map(facts.map(f=>[f.fact_key,f]));const booleanKeys=new Set(['for_profit','collects_personal_information','determines_purposes_and_means','does_business_in_california','natural_person','ordinary_signup_data_nonexempt','wholly_outside_california_exception','related_entity_business_route','joint_venture_business_route','voluntary_cppa_certification']);const numericKeys=new Set(['annual_gross_revenue_usd','prior_calendar_year','annual_buy_sell_share_ca_consumers_or_households','sale_share_revenue_percent']);const value=(key:string)=>{const f=by.get(key);if(f?.knowledge!=='known'||f.value===null)return undefined;const v=f.value;if(booleanKeys.has(key)&&typeof v!=='boolean')return undefined;if(numericKeys.has(key)&&(typeof v!=='number'||!Number.isFinite(v)||v<0))return undefined;if(key==='prior_calendar_year'&&(!Number.isInteger(v)||v!==2025))return undefined;if(key==='sale_share_revenue_percent'&&typeof v==='number'&&v>100)return undefined;if(key==='annual_buy_sell_share_ca_consumers_or_households'&&!Number.isInteger(v))return undefined;if(key==='declared_legal_residence'&&(typeof v!=='string'||!/^US-[A-Z]{2}$/.test(v)))return undefined;return v;};const missing:string[]=[];const need=(key:string)=>{const v=value(key);if(v===undefined)missing.push(key);return v;};const criteria:Assessment['criteria']=[];const residence=need('declared_legal_residence');let outcome:Assessment['outcome']='needs_information';const basis:string[]=[];
 if(residence && residence!=='US-CA'){outcome='not_covered';basis.push('This signup is outside the assessed California consumer scope; this is not a company-wide exemption.');}
 else if(residence==='US-CA'){
 const checks=['for_profit','collects_personal_information','determines_purposes_and_means','does_business_in_california','natural_person','ordinary_signup_data_nonexempt'];let failed=false;for(const k of checks){const v=need(k);if(v===false)failed=true;criteria.push({label:k.replaceAll('_',' '),result:v===true?'pass':v===false?'fail':'unknown',evidence:'Synthetic company fact: '+k});}
 const r=value('annual_gross_revenue_usd'),year=value('prior_calendar_year'),volume=value('annual_buy_sell_share_ca_consumers_or_households'),share=value('sale_share_revenue_percent');const revenue=typeof r==='number'&&year===2025?r>26625000:undefined;const vol=typeof volume==='number'?volume>=100000:undefined;const pct=typeof share==='number'?share>=50:undefined;
 criteria.push({label:'2025 gross revenue exceeds $26,625,000',result:revenue===undefined?'unknown':revenue?'pass':'fail',evidence:'Civil Code §1798.140(d)(1)(A) · CPPA 2025 CPI adjustment'});
 const routes=[revenue,vol,pct,...['related_entity_business_route','joint_venture_business_route','voluntary_cppa_certification'].map(k=>value(k))];
 const exempt=need('exemption_screen');const special=!exempt||typeof exempt!=='object'||Array.isArray(exempt)||Object.keys(exempt).length<12||Object.entries(exempt).some(([k,v])=>k!=='scope'&&v!==false);
 const outside=need('wholly_outside_california_exception');if(special||outside===true){missing.push('lawyer_exemption_scope_review');}
 if(failed){outcome='not_covered';basis.push('A required business or assessed-scope criterion is explicitly false.');}else if(missing.length){outcome='needs_information';}else if(routes.some(x=>x===true)){outcome='covered';basis.push(revenue?'Revenue prong: explicit 2025 gross revenue exceeds the operative $26,625,000 threshold.':vol?'Volume prong: at least 100,000 California consumers or households.':pct?'At least 50% of annual revenue derives from sale or sharing.':'An explicitly verified alternative business route applies.');}else if(routes.some(x=>x===undefined)){outcome='needs_information';for(const k of ['annual_gross_revenue_usd','prior_calendar_year','annual_buy_sell_share_ca_consumers_or_households','sale_share_revenue_percent','related_entity_business_route','joint_venture_business_route','voluntary_cppa_certification'])if(value(k)===undefined)missing.push(k);}else{outcome='not_covered';basis.push('All assessed business routes are explicitly false. Equality with the revenue threshold does not satisfy “in excess of”.');}
 }
 return {outcome,summary:outcome==='covered'?'The explicit synthetic facts support CCPA applicability. Proposed policy changes require founder and lawyer review.':outcome==='needs_information'?'Applicability is unresolved. Missing or conflicting facts must be resolved before a draft can enter review.':'CCPA coverage is not established for this assessed scope. Other obligations may still apply.',missing_facts:[...new Set(missing)],basis,criteria};}
export {requiredEvidence, contextCheck, validateProposal} from '../validation/proposal';
export function fixtureFacts(input:Record<string,any>):Fact[]{return Object.entries(input).map(([key,f])=>({fact_id:f.factId,fact_key:key.replace(/[A-Z]/g,m=>'_'+m.toLowerCase()),knowledge:f.knowledgeState==='known'?'known':f.knowledgeState==='conflicted'?'conflicted':'unknown',value:f.value,provenance:'Frozen legal evaluation fixture'}));}
