import {readFileSync,statSync} from 'node:fs';
import {V2Error,type Source,type Scope,type WorkspaceState} from '../contracts';
import {digest} from '../store';
export interface EmailInstallation {id:string;tenantId:string;actorId:string;ownerId:string;accountId:string;accountScope:'exclusive_owner';enabled:boolean;validUntil:string;receivingAddress:string;allowedSenders:string[];tokenEnv:string;webhookSecretEnv:string;rawDownloadHosts:string[];scope:Scope}
const envKey=/^[A-Z][A-Z0-9_]{0,99}$/;
export function emailAddress(value:unknown):string|null {if(typeof value!=='string'||value.length>320||/[\r\n\x00]/.test(value))return null;const trimmed=value.trim(),address=trimmed.includes('<')||trimmed.includes('>')?trimmed.match(/^[^<>]*<([^<>]+)>$/)?.[1]:trimmed;return address&&/^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9.-]*[a-zA-Z0-9])?$/.test(address)?address.toLowerCase():null;}
export function emailCredential(name:string){if(!envKey.test(name)||!process.env[name])throw new V2Error('EMAIL_NOT_CONFIGURED','A receiving credential is unavailable.',503);return process.env[name]!;}
export function emailInstallations():EmailInstallation[]{
 let raw=process.env.KIARA_V2_EMAIL_INSTALLATIONS;if(process.env.KIARA_V2_EMAIL_INSTALLATIONS_FILE){const path=process.env.KIARA_V2_EMAIL_INSTALLATIONS_FILE,stat=statSync(path);if(!stat.isFile()||stat.size>256000||(stat.mode&0o077)!==0)throw new V2Error('EMAIL_CONFIG_INVALID','Receiving installation files must be private and bounded.',503);raw=readFileSync(path,'utf8');}
 let list:EmailInstallation[];try{list=JSON.parse(raw||'[]');}catch{throw new V2Error('EMAIL_CONFIG_INVALID','Receiving configuration is invalid.',503);}if(!Array.isArray(list)||list.length>100)throw new V2Error('EMAIL_CONFIG_INVALID','Receiving configuration is invalid.',503);const ids=new Set<string>(),aliases=new Set<string>(),accounts=new Set<string>(),tokens=new Set<string>(),secrets=new Set<string>(),tokenValues=new Set<string>(),secretValues=new Set<string>();
 for(const i of list){if(!i||![i.id,i.tenantId,i.actorId,i.ownerId,i.accountId].every(x=>typeof x==='string'&&x.length>0&&x.length<=200)||i.actorId===i.ownerId||i.accountScope!=='exclusive_owner'||typeof i.enabled!=='boolean'||!Number.isFinite(Date.parse(i.validUntil))||!envKey.test(i.tokenEnv)||!envKey.test(i.webhookSecretEnv)||emailAddress(i.receivingAddress)!==i.receivingAddress||!Array.isArray(i.allowedSenders)||i.allowedSenders.length>100||i.allowedSenders.some(x=>emailAddress(x)!==x)||!Array.isArray(i.rawDownloadHosts)||!i.rawDownloadHosts.length||i.rawDownloadHosts.length>10||i.rawDownloadHosts.some(x=>typeof x!=='string'||!/^([a-z0-9-]+\.)+[a-z]{2,}$/.test(x)||x.endsWith('.local'))||i.scope?.kind!=='private'||!Array.isArray(i.scope.actorIds)||digest([...new Set(i.scope.actorIds)].sort())!==digest([i.actorId,i.ownerId].sort())||ids.has(i.id)||aliases.has(i.receivingAddress)||accounts.has(i.accountId)||tokens.has(i.tokenEnv)||secrets.has(i.webhookSecretEnv)||!!process.env[i.tokenEnv]&&tokenValues.has(digest(process.env[i.tokenEnv]))||!!process.env[i.webhookSecretEnv]&&secretValues.has(digest(process.env[i.webhookSecretEnv])))throw new V2Error('EMAIL_CONFIG_INVALID','Receiving installations require a dedicated provider account per private owner, unique credentials, exact alias and selected raw-download hosts.',503);ids.add(i.id);aliases.add(i.receivingAddress);accounts.add(i.accountId);tokens.add(i.tokenEnv);secrets.add(i.webhookSecretEnv);if(process.env[i.tokenEnv])tokenValues.add(digest(process.env[i.tokenEnv]));if(process.env[i.webhookSecretEnv])secretValues.add(digest(process.env[i.webhookSecretEnv]));}return list;
}
export function emailInstallation(id:string){const i=emailInstallations().find(x=>x.id===id);if(!i?.enabled||Date.parse(i.validUntil)<=Date.now())throw new V2Error('EMAIL_NOT_CONFIGURED','The receiving installation is unavailable or expired.',503);return i;}
export function emailInstallationMembers(s:WorkspaceState,i:EmailInstallation){const active=(id:string,role:string)=>s.memberships.find(m=>m.actorId===id&&!m.revokedAt&&(!m.expiresAt||Date.parse(m.expiresAt)>Date.now())&&m.roles.some(r=>r===role)&&(!m.entityIds||m.entityIds.includes(s.entityId))&&m.matterIds===null),owner=active(i.ownerId,'member'),integration=active(i.actorId,'integration');if(s.tenantId!==i.tenantId||!owner||!integration)throw new V2Error('EMAIL_MEMBERSHIP_CHANGED','The receiving owner or installation membership is unavailable.',403);return {owner,integration};}
export function emailSourceEligible(s:WorkspaceState,source:Source):boolean {try{const metadata=source.emailIntake,grant=source.installationGrant;if(source.kind!=='email'||!metadata||!grant)return false;const i=emailInstallation(grant.installationId);const members=emailInstallationMembers(s,i),receipt=s.receipts[`email-intake:${metadata.receiptId}`]?.result.intake as {membershipVersion?:number;integrationVersion?:number;sourceId?:string;configurationHash?:string}|undefined;if(!receipt||receipt.membershipVersion!==members.owner.version||receipt.integrationVersion!==members.integration.version||receipt.sourceId!==source.id||receipt.configurationHash!==grant.configurationHash)return false;return metadata.installationId===i.id&&metadata.ownerId===i.ownerId&&i.actorId===source.provenance.actorId&&i.tenantId===source.tenantId&&grant.configurationHash===digest(i)&&digest(i.scope)===digest(source.scope)&&!!source.externalId?.startsWith(`${i.id}:received:`);}catch{return false;}}
