import {randomUUID} from 'node:crypto';
import {Resend} from 'resend';
import {canRead,membership,readRecord,requireRole} from '../authority';
import {retainIntakeOriginal} from '../artifact-intake';
import {assertOriginalNotDeleted} from '../retention';
import {enqueueIndexMaintenance,indexRecordFingerprints} from '../index-maintenance';
import {V2Error,type ActorContext,type Source,type WorkspaceState} from '../contracts';
import {digest,readWorkspace,timestamp,transactWorkspace} from '../store';
import {emailAddress,emailCredential,emailInstallation,emailInstallationMembers,type EmailInstallation} from './email-config';
import {readReceivedEmail} from './email-read';
export interface EmailIntake {id:string;installationId:string;configurationHash:string;emailId:string;payloadHash:string;ownerId:string;membershipVersion:number;integrationVersion:number;createdAt:string;updatedAt:string;status:'queued'|'running'|'quarantined'|'accepted'|'rejected'|'blocked';sourceId:string|null;leaseToken:string|null;leaseUntil:string|null;failureCode:string|null;attempts:number;nextAttemptAt:string|null;decision?:{inputHash:string;actorId:string;membershipVersion:number;at:string;decision:'accept'|'reject'}}
export interface EmailIntakeProgress {status:EmailIntake['status'];nextCheckMs:number}
export interface EmailIntakeView {intakeId:string;status:EmailIntake['status'];failureCode:string|null;sourceId:string|null;sourceVersion:number|null;sourceHash:string|null;receiptHash:string|null;source:{title:string;text:string;authority:Source['authority'];originalRetained:boolean}|null}
export interface EmailIntakeSummary {intakeId:string;status:EmailIntake['status'];failureCode:string|null;sourceId:string|null;sourceTitle:string|null;reviewAvailable:boolean}
export interface EmailReviewInput {expectedSourceVersion:number;expectedSourceHash:string;expectedReceiptHash:string;decision:'accept'|'reject'}
const key=(id:string)=>`email-intake:${id}`;
function ensure(v:unknown,code:string,message:string,status=409):asserts v {if(!v)throw new V2Error(code,message,status);}
function intake(s:WorkspaceState,id:string):EmailIntake {const job=s.receipts[key(id)]?.result.intake as unknown as EmailIntake|undefined;if(!job)throw new V2Error('EMAIL_INTAKE_NOT_FOUND','This intake is unavailable.',404);return job;}
function actor(s:WorkspaceState,j:EmailIntake):ActorContext{return {tenantId:s.tenantId,actorId:j.ownerId,mode:'authenticated',expiresAt:Date.now()+60000};}
function eligible(s:WorkspaceState,j:EmailIntake,token?:string){const i=emailInstallation(j.installationId),members=emailInstallationMembers(s,i);ensure(i.tenantId===s.tenantId&&i.ownerId===j.ownerId&&digest(i)===j.configurationHash&&members.owner.version===j.membershipVersion&&members.integration.version===j.integrationVersion,'EMAIL_AUTHORITY_CHANGED','Receiving scope, ownership or membership changed.');if(token)ensure(j.status==='running'&&j.leaseToken===token&&!!j.leaseUntil&&Date.parse(j.leaseUntil)>Date.now(),'EMAIL_LEASE_LOST','This receiving worker no longer owns its lease.');return i;}
const remaining=(j:EmailIntake)=>Math.max(60000,Math.min(21600000,Date.parse(j.nextAttemptAt||j.leaseUntil||'')-Date.now()||60000));
/** Authentication accepts only a durable read reference. Webhook body content is never source evidence. */
export async function acceptEmailWebhook(installationId:string,headers:Headers,raw:Uint8Array):Promise<{accepted:true;intakeId:string}>{
 const i=emailInstallation(installationId);ensure(raw.byteLength>0&&raw.byteLength<=1_000_000,'EMAIL_WEBHOOK_LIMIT','The receiving webhook exceeds its bounded size.',413);let event:any;try{event=new Resend('webhook-verification-only').webhooks.verify({payload:new TextDecoder('utf-8',{fatal:true}).decode(raw),headers:{id:headers.get('svix-id')||'',timestamp:headers.get('svix-timestamp')||'',signature:headers.get('svix-signature')||''},webhookSecret:emailCredential(i.webhookSecretEnv)});}catch{throw new V2Error('EMAIL_WEBHOOK_INVALID','Invalid or expired receiving webhook signature.',401);}
 ensure(event?.type==='email.received'&&/^[a-f0-9-]{36}$/i.test(event.data?.email_id)&&Array.isArray(event.data?.to)&&event.data.to.map(emailAddress).includes(i.receivingAddress),'EMAIL_RECEIVING_SCOPE','This webhook is not addressed to the selected receiving alias.',403);const id=digest({installationId:i.id,emailId:event.data.email_id}),payloadHash=digest(event.data);
 await transactWorkspace(i.tenantId,s=>{const current=emailInstallation(i.id),members=emailInstallationMembers(s,current);ensure(digest(current)===digest(i),'EMAIL_AUTHORITY_CHANGED','The receiving grant changed during webhook verification.');const old=s.receipts[key(id)]?.result.intake as unknown as EmailIntake|undefined;if(old){ensure(old.payloadHash===payloadHash,'EMAIL_EVENT_CONFLICT','The provider email identity was reused with conflicting metadata.');return;}
  const job:EmailIntake={id,installationId:i.id,configurationHash:digest(i),emailId:event.data.email_id,payloadHash,ownerId:i.ownerId,membershipVersion:members.owner.version,integrationVersion:members.integration.version,createdAt:timestamp(),updatedAt:timestamp(),status:'queued',sourceId:null,leaseToken:null,leaseUntil:null,failureCode:null,attempts:0,nextAttemptAt:null};s.receipts[key(id)]={hash:digest({id,payloadHash}),result:{intake:job}};s.outbox.push({id:`email_${id}`,tenantId:s.tenantId,kind:'email_intake',aggregateId:id,commandId:id,status:'pending',owner:'v2',createdAt:job.createdAt});});return {accepted:true,intakeId:id};
}
/** Provider reads and original retention precede one transaction attaching untrusted source evidence. */
export async function processEmailIntake(tenantId:string,id:string,options:{fetcher?:typeof fetch}={}):Promise<EmailIntakeProgress>{
 const token=randomUUID(),claim=await transactWorkspace(tenantId,s=>{const j=intake(s,id);if(!['queued','running'].includes(j.status))return false;if(j.leaseUntil&&Date.parse(j.leaseUntil)>Date.now()||j.nextAttemptAt&&Date.parse(j.nextAttemptAt)>Date.now())return false;eligible(s,j);j.status='running';j.leaseToken=token;j.leaseUntil=new Date(Date.now()+120000).toISOString();j.nextAttemptAt=null;j.attempts++;j.updatedAt=timestamp();return true;});
 if(!claim.result){const j=intake(claim.state,id);return {status:j.status,nextCheckMs:['queued','running'].includes(j.status)?remaining(j):0};}
 try{const before=await readWorkspace(tenantId),j=intake(before,id),i=eligible(before,j,token),received=await readReceivedEmail(i,j.emailId,options),latest=await readWorkspace(tenantId);eligible(latest,intake(latest,id),token);const owner=actor(latest,j),originalKey=`email:${id}:original`,original=await retainIntakeOriginal(owner,originalKey,received.bytes,latest.version);
  return (await transactWorkspace(tenantId,s=>{const job=intake(s,id),current=eligible(s,job,token);ensure(digest(emailCredential(current.tokenEnv))===received.credentialHash,'EMAIL_AUTHORITY_CHANGED','The receiving credential changed before attachment.');const encoded=JSON.stringify(original.reference);assertOriginalNotDeleted(s,encoded,digest({actor:owner.actorId,key:originalKey}));const e=received.email,from=emailAddress(e.from)!,trusted=current.allowedSenders.includes(from)&&e.authentication?.dmarc==='pass'&&(e.authentication.dkim==='pass'||e.authentication.spf==='pass')&&typeof e.text==='string'&&e.text.trim().length>0,status=trusted?'accepted':'quarantined';
   const text=JSON.stringify({subject:e.subject,from,receivedAt:e.created_at,messageId:e.message_id,text:e.text||null,authentication:{spf:e.authentication?.spf||'unknown',dkim:e.authentication?.dkim||'unknown',dmarc:e.authentication?.dmarc||'unknown'},attachments:e.attachments.map(a=>({id:a.id,filename:a.filename,contentType:a.content_type,bytes:a.size,extraction:'not_parsed'})),limitations:['Forwarded headers and quoted sender identities are unverified source text.','Attachments are preserved in the raw original; attachment text is not extracted.','Email content is evidence for review, never an approval, company fact or execution instruction.']});ensure(text.length<=100000,'EMAIL_SIZE_LIMIT','Email evidence exceeds the bounded extraction size.');
   const indexBefore=indexRecordFingerprints(s),source:Source={id:randomUUID(),tenantId:s.tenantId,version:1,createdAt:timestamp(),updatedAt:timestamp(),scope:structuredClone(current.scope),provenance:{actorId:current.actorId,sourceIds:[],description:'Provider-authenticated received email; original sender assertions remain untrusted.'},title:e.subject.slice(0,300)||'Received email',kind:'email',externalId:`${current.id}:received:${job.emailId}`,externalRevision:original.reference.sha256,text,contentHash:digest(text),url:null,status:'active',aclVersion:1,observedAt:timestamp(),effectiveAt:e.created_at,authority:'unknown',originalObjectRef:encoded,installationGrant:{installationId:current.id,configurationHash:job.configurationHash},emailIntake:{receiptId:id,installationId:current.id,ownerId:current.ownerId,status}};s.sources.push(source);job.sourceId=source.id;job.status=status;job.leaseToken=null;job.leaseUntil=null;job.failureCode=null;job.updatedAt=timestamp();s.events.push({id:randomUUID(),tenantId:s.tenantId,version:1,createdAt:timestamp(),updatedAt:timestamp(),scope:structuredClone(source.scope),provenance:{actorId:current.actorId,sourceIds:[source.id],description:'Received source intake'},type:'email.received',title:'Received email retained for review',detail:status==='quarantined'?'Sender authentication or mapping requires owner review.':'Configured sender transmission authenticated; its contents remain untrusted evidence.',matterId:null,recordId:source.id,measurement:'observed'});enqueueIndexMaintenance(s,owner,indexBefore,id);return {status:job.status,nextCheckMs:0};})).result;
 }catch(error){return (await transactWorkspace(tenantId,s=>{const j=intake(s,id);if(j.leaseToken!==token)return {status:j.status,nextCheckMs:remaining(j)};const code=error instanceof V2Error?error.code:'EMAIL_READ_UNAVAILABLE',retry=['EMAIL_READ_UNAVAILABLE','VERSION_CONFLICT','STORE_BUSY'].includes(code)&&j.attempts<10;j.status=retry?'queued':'blocked';j.failureCode=code;j.nextAttemptAt=retry?new Date(Date.now()+300000).toISOString():null;j.leaseToken=null;j.leaseUntil=null;j.updatedAt=timestamp();return {status:j.status,nextCheckMs:retry?300000:0};})).result;}
}
function reviewHash(j:EmailIntake,source:Source){return digest({intakeId:j.id,sourceId:source.id,sourceVersion:source.version,contentHash:source.contentHash,original:source.originalObjectRef,configurationHash:j.configurationHash,membershipVersion:j.membershipVersion,status:j.status});}
function view(s:WorkspaceState,a:ActorContext,id:string):EmailIntakeView{const j=intake(s,id);ensure(a.actorId===j.ownerId,'EMAIL_OWNER_REQUIRED','Only the configured receiving owner can review this private intake.',403);membership(s,a);eligible(s,j);const source=j.sourceId?s.sources.find(x=>x.id===j.sourceId):undefined;if(source)ensure(canRead(s,a,source),'NOT_FOUND','This intake source is unavailable.',404);return {intakeId:j.id,status:j.status,failureCode:j.failureCode,sourceId:source?.id||null,sourceVersion:source?.version||null,sourceHash:source?.contentHash||null,receiptHash:source?reviewHash(j,source):null,source:source?{title:source.title,text:source.text,authority:source.authority,originalRetained:!!source.originalObjectRef}:null};}
/** Exact owner's metadata-only discovery. Revoked evidence never supplies a title or source identifier. */
export function emailIntakeSummaries(s:WorkspaceState,a:ActorContext):EmailIntakeSummary[]{
 membership(s,a);return Object.entries(s.receipts).filter(([k])=>k.startsWith('email-intake:')).map(([,receipt])=>receipt.result.intake as unknown as EmailIntake).filter(j=>j&&j.ownerId===a.actorId).sort((x,y)=>y.createdAt.localeCompare(x.createdAt)).slice(0,50).map(j=>{try{eligible(s,j);const source=j.sourceId?s.sources.find(x=>x.id===j.sourceId):undefined;if(source&&!canRead(s,a,source))throw new V2Error('EMAIL_SOURCE_UNAVAILABLE','This source is unavailable.');return {intakeId:j.id,status:j.status,failureCode:j.failureCode,sourceId:source?.id||null,sourceTitle:source?.title||null,reviewAvailable:!!source};}catch{return {intakeId:j.id,status:j.status,failureCode:'EMAIL_AUTHORITY_CHANGED',sourceId:null,sourceTitle:null,reviewAvailable:false};}});
}
export async function emailIntakeView(a:ActorContext,id:string){return view(await readWorkspace(a.tenantId),a,id);}
/** An authenticated exact owner decision admits evidence; it never invokes chat commands or approves an action. */
export async function reviewEmailIntake(a:ActorContext,id:string,input:EmailReviewInput){return (await transactWorkspace(a.tenantId,s=>{const j=intake(s,id);ensure(a.actorId===j.ownerId,'EMAIL_OWNER_REQUIRED','Only the configured receiving owner may decide.',403);const i=eligible(s,j),member=requireRole(s,a,'member'),source=readRecord(s,a,s.sources,j.sourceId||'');ensure(['accept','reject'].includes(input.decision),'EMAIL_REVIEW_INVALID','Choose accept or reject.',400);const hash=digest(input);if(j.decision?.inputHash===hash&&j.decision.actorId===a.actorId)return view(s,a,id);ensure(j.status==='quarantined'&&source.emailIntake?.status==='quarantined'&&source.version===input.expectedSourceVersion&&source.contentHash===input.expectedSourceHash&&reviewHash(j,source)===input.expectedReceiptHash,'EMAIL_REVIEW_CHANGED','Inspect the exact current email and attachment limitations before deciding.');const before=indexRecordFingerprints(s);source.emailIntake!.status=input.decision==='accept'?'accepted':'rejected';source.version++;source.updatedAt=timestamp();j.status=source.emailIntake!.status;j.decision={inputHash:hash,actorId:a.actorId,membershipVersion:member.version,at:timestamp(),decision:input.decision};j.updatedAt=timestamp();s.events.push({id:randomUUID(),tenantId:s.tenantId,version:1,createdAt:timestamp(),updatedAt:timestamp(),scope:structuredClone(i.scope),provenance:{actorId:a.actorId,sourceIds:[source.id],description:'Exact authenticated email evidence review'},type:'email.reviewed',title:'Received source reviewed',detail:'Owner decision concerns evidence admission only; no sender impersonation, factual confirmation or consequential action.',matterId:null,recordId:source.id,measurement:'observed'});enqueueIndexMaintenance(s,a,before,id+':review');return view(s,a,id);})).result;}
