import {isIP} from 'node:net';
import {lookup} from 'node:dns/promises';
import {request as httpsRequest} from 'node:https';
import {publicLegalAddress} from '../legal-maintenance';
import {V2Error} from '../contracts';
import {digest} from '../store';
import {emailAddress,emailCredential,type EmailInstallation} from './email-config';
export interface ReceivedEmail {id:string;from:string;to:string[];subject:string;text:string|null;created_at:string;message_id:string;received_for?:string[];authentication?:{spf?:string;dkim?:string;dmarc?:string}|null;attachments:{id:string;filename:string|null;content_type:string;size:number}[];raw:{download_url:string;expires_at:string}}
const MAX_RAW=10_000_000;
async function boundedBody(response:Response,max:number){if(!response.ok||!response.body||Number(response.headers.get('content-length')||0)>max)throw new V2Error('EMAIL_READ_UNAVAILABLE','The receiving object is unavailable or exceeds its bounded size.',503);const reader=response.body.getReader(),parts:Uint8Array[]=[];let length=0;while(true){const p=await reader.read();if(p.done)break;length+=p.value.byteLength;if(length>max){await reader.cancel();throw new V2Error('EMAIL_SIZE_LIMIT','The received object exceeds the intake size limit.',413);}parts.push(p.value);}return Buffer.concat(parts);}
async function download(url:URL):Promise<Response>{
 let timer:ReturnType<typeof setTimeout>|undefined;const addresses=await Promise.race([lookup(url.hostname,{all:true}),new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(new V2Error('EMAIL_READ_UNAVAILABLE','Raw email DNS lookup timed out.',503)),15000);})]).finally(()=>{if(timer)clearTimeout(timer);});if(!addresses.length||addresses.some(x=>!publicLegalAddress(x.address)))throw new V2Error('EMAIL_RAW_ORIGIN','Raw originals must resolve only to public addresses.',403);const selected=addresses[0];
 return new Promise((resolve,reject)=>{const request=httpsRequest(url,{method:'GET',agent:false,signal:AbortSignal.timeout(15000),family:selected.family,lookup:(_host,options,callback)=>callback(null,options.all?[selected]:selected.address,selected.family),headers:{Accept:'message/rfc822, application/octet-stream','Accept-Encoding':'identity'}},response=>{if((response.statusCode||0)<200||(response.statusCode||0)>=300||response.headers['content-encoding']&&response.headers['content-encoding']!=='identity'){response.destroy();reject(new V2Error('EMAIL_READ_UNAVAILABLE','Raw original redirects or compression are unsupported.',503));return;}const parts:Buffer[]=[];let size=0;response.on('data',(chunk:Buffer)=>{size+=chunk.byteLength;if(size>MAX_RAW){response.destroy();reject(new V2Error('EMAIL_SIZE_LIMIT','Raw email exceeds its intake bound.',413));}else parts.push(chunk);});response.on('error',reject);response.on('end',()=>resolve(new Response(Buffer.concat(parts))));});request.on('error',reject);request.setTimeout(15000,()=>request.destroy());request.end();});
}
export async function readReceivedEmail(i:EmailInstallation,id:string,options:{fetcher?:typeof fetch}={}){
 if(!/^[a-f0-9-]{36}$/i.test(id))throw new V2Error('EMAIL_ID_INVALID','The provider email identifier is invalid.',400);const token=emailCredential(i.tokenEnv),fetcher=options.fetcher||fetch;let email:ReceivedEmail;try{email=JSON.parse((await boundedBody(await fetcher(`https://api.resend.com/emails/receiving/${id}?html_format=cid`,{method:'GET',redirect:'error',credentials:'omit',signal:AbortSignal.timeout(15000),headers:{Authorization:`Bearer ${token}`,Accept:'application/json'}}),2_000_000)).toString('utf8'));}catch(error){if(error instanceof V2Error)throw error;throw new V2Error('EMAIL_READ_UNAVAILABLE','The receiving API read did not complete.',503);}
 if(email.id!==id||!Array.isArray(email.to)||!email.to.map(emailAddress).includes(i.receivingAddress)||email.received_for!==undefined&&(!Array.isArray(email.received_for)||email.received_for.some(value=>!emailAddress(value))||email.received_for.length>0&&!email.received_for.map(emailAddress).includes(i.receivingAddress))||!emailAddress(email.from)||typeof email.subject!=='string'||email.subject.length>1000||!Number.isFinite(Date.parse(email.created_at))||typeof email.message_id!=='string'||email.message_id.length>1000||email.text!==null&&typeof email.text!=='string'||email.text&&email.text.length>80000||!Array.isArray(email.attachments)||email.attachments.length>50||email.attachments.some(a=>!a||typeof a.id!=='string'||typeof a.content_type!=='string'||a.filename!==null&&typeof a.filename!=='string'||!Number.isSafeInteger(a.size)||a.size<0))throw new V2Error('EMAIL_RESPONSE_INVALID','The retrieved email does not match its selected receiving identity or size contract.',502);
 let rawUrl:URL;try{rawUrl=new URL(email.raw.download_url);}catch{throw new V2Error('EMAIL_RAW_UNAVAILABLE','The provider did not supply a retained original download.',503);}if(rawUrl.protocol!=='https:'||rawUrl.username||rawUrl.password||rawUrl.hash||rawUrl.port&&rawUrl.port!=='443'||isIP(rawUrl.hostname)||!i.rawDownloadHosts.includes(rawUrl.hostname)||!Number.isFinite(Date.parse(email.raw.expires_at))||Date.parse(email.raw.expires_at)<=Date.now())throw new V2Error('EMAIL_RAW_ORIGIN','The raw original does not match the configured public download hosts or expiry.',403);
 let bytes:Buffer;try{bytes=await boundedBody(options.fetcher?await options.fetcher(rawUrl,{method:'GET',redirect:'error',credentials:'omit',signal:AbortSignal.timeout(15000),headers:{Accept:'message/rfc822, application/octet-stream'}}):await download(rawUrl),MAX_RAW);}catch(error){if(error instanceof V2Error)throw error;throw new V2Error('EMAIL_READ_UNAVAILABLE','The raw email original read did not complete.',503);}if(!bytes.length)throw new V2Error('EMAIL_RAW_UNAVAILABLE','The original is empty.',503);if(emailCredential(i.tokenEnv)!==token)throw new V2Error('EMAIL_CONFIG_CHANGED','The receiving credential changed during the read.');return {email,bytes,credentialHash:digest(token)};
}
