/** Explicit synthetic cancellation fixture and accounting recovery; never dispatches a provider. */
import {randomUUID} from 'node:crypto';
import {mkdir,readFile,writeFile,chmod} from 'node:fs/promises';
import {resolve,join} from 'node:path';
import {command,snapshot} from '../src/v2/service';
import {controlledRun,touchRun} from '../src/v2/run-control';
import {processConversationRun} from '../src/v2/ai';
import {closeV2Store,digest,transactWorkspace} from '../src/v2/store';
import {reserveGlobalSpend,globalSpendStatus} from '../src/server/global-spend';
import type {ActorContext,WorkspaceCommand} from '../src/v2/contracts';
const protocol='kiara-synthetic-cancellation-ui-1';
async function main(){
 const path=(name:string)=>{const arg=process.argv.find(v=>v.startsWith(`--${name}=`));if(!arg)throw Error(`Supply explicit --${name}=/private/tmp/kiara-...`);const value=resolve(arg.slice(name.length+3));if(!/^\/(?:private\/)?tmp\/kiara-[A-Za-z0-9_./-]+$/.test(value))throw Error('Fixture paths must be temporary kiara-* local directories.');return value;},dir=path('data-dir'),budget=path('budget-dir');if(dir===budget)throw Error('Use a separate synthetic budget directory.');
 for(const key of Object.keys(process.env))if(/^(KIARA|MONGO|OPENAI|RESEND|TEMPORAL|VERCEL)/.test(key))delete process.env[key];Object.assign(process.env,{KIARA_V2_DATA_DIR:dir,KIARA_GLOBAL_BUDGET_DIR:budget,KIARA_V2_AI_MODE:'openai',KIARA_V2_AUTH_MODE:'local_demo',KIARA_AUTH_MODE:'demo_simulated',KIARA_MODEL:'gpt-6-sol',KIARA_REVIEW_MODEL:'gpt-6-sol',KIARA_REASONING_EFFORT:'low',KIARA_OPENAI_BUDGET_USD:'1',OPENAI_API_KEY:'synthetic-never-provider-authority',MONGODB_URI:''});globalThis.fetch=async()=>{throw Error('Synthetic fixture forbids external requests');};
 const owner:ActorContext={tenantId:'local-workspace',actorId:'local-founder',mode:'local_demo',expiresAt:Date.now()+3600000,bootstrapRoles:['member','admin','business_owner','fact_owner','publisher']},manifestPath=join(dir,'run-ui-fixtures.json');await mkdir(dir,{recursive:true,mode:0o700});
 if(process.argv.includes('--recover')){const manifest=JSON.parse(await readFile(manifestPath,'utf8'));if(manifest.protocol!==protocol||manifest.dataDir!==dir||manifest.budgetDir!==budget||typeof manifest.running?.runId!=='string')throw Error('Only this script’s exact labeled synthetic fixture may be recovered.');await transactWorkspace(owner.tenantId,s=>{const r=controlledRun(s,manifest.running.runId) as ReturnType<typeof controlledRun>&{uiFixture?:string};if(r.uiFixture!==protocol||r.actor.actorId!==owner.actorId||!r.cancellation)throw Error('Explicitly cancel the labeled synthetic run before recovery.');r.leaseUntil=Date.now()-1;touchRun(r);});const recovered=await processConversationRun(owner.tenantId,manifest.running.runId);console.log(JSON.stringify({protocol,providerCalls:0,recovered,syntheticLedger:await globalSpendStatus()},null,2));await closeV2Store();return;}
 const send=async(c:WorkspaceCommand)=>command(owner,{idempotencyKey:randomUUID(),expectedVersion:(await snapshot(owner)).version,command:c});
 const fixtures=[];for(const state of ['queued','running'] as const){const created=await send({type:'conversation.create',title:`Synthetic cancellation UI — ${state}`,scope:{kind:'private',actorIds:[owner.actorId]}}),result=await send({type:'message.send',conversationId:String(created.result.conversationId),text:`SYNTHETIC UI FIXTURE ONLY. Explain what evidence is missing for the ${state} cancellation example. Do not take any action.`}),runId=String(result.result.runId);if(!result.snapshot.aiRuns.some(r=>r.id===runId&&r.status==='queued'))throw Error('The synthetic fixture was not queued.');let chargeId:string|null=null;if(state==='running'){chargeId=randomUUID();await reserveGlobalSpend(chargeId,0.001);}
 await transactWorkspace(owner.tenantId,s=>{const r=controlledRun(s,runId) as ReturnType<typeof controlledRun>&{uiFixture?:string};r.uiFixture=protocol;if(chargeId){r.status='running';r.leaseToken='synthetic-no-provider-dispatch';r.leaseUntil=Date.now()+300000;r.attempts.push({id:chargeId,status:'dispatched',stage:'answer',requestHash:digest(protocol),model:'gpt-6-sol',inputTokens:100,maxOutputTokens:100,reservedUsd:0.001,actualUsd:null,responseId:null,responseHash:null,output:null,startedAt:new Date().toISOString(),finishedAt:null} as typeof r.attempts[number]);touchRun(r);}});const run=(await snapshot(owner)).aiRuns.find(r=>r.id===runId)!;fixtures.push({state,conversationId:run.conversationId,runId,version:run.version,chargeId});}
 const manifest={protocol,dataDir:dir,budgetDir:budget,queued:fixtures[0],running:fixtures[1],providerCalls:0,ledgerIsSynthetic:true};await writeFile(manifestPath,JSON.stringify(manifest,null,2),{mode:0o600});await chmod(manifestPath,0o600);console.log(JSON.stringify({...manifest,manifestPath,previewAiMode:'local',note:'Do not enable model providers in the preview. Run --recover with these exact dirs only after canceling the labeled running fixture.'},null,2));await closeV2Store();
}
main().catch(async error=>{await closeV2Store();console.error(error instanceof Error?error.message:String(error));process.exitCode=1;});
