/** Explicit synthetic local UI fixture. Never loads .env or contacts a mailbox/provider. */
import {createHmac,randomUUID} from 'node:crypto';
import {mkdir,writeFile,chmod} from 'node:fs/promises';
import {resolve,join} from 'node:path';
import {acceptEmailWebhook,processEmailIntake,emailIntakeView} from '../src/v2/integrations/email';
import type {EmailInstallation} from '../src/v2/integrations/email-config';
import {closeV2Store,transactWorkspace} from '../src/v2/store';
import type {ActorContext} from '../src/v2/contracts';

async function main(){
 const arg=process.argv.find(v=>v.startsWith('--data-dir='));if(!arg)throw Error('Supply --data-dir=/private/tmp/kiara-... for an explicitly synthetic local preview.');const dir=resolve(arg.slice('--data-dir='.length));if(!/^\/(?:private\/)?tmp\/kiara-[A-Za-z0-9_./-]+$/.test(dir))throw Error('Fixture directory must be an explicit temporary kiara-* local preview, never the project or remote database.');
 const originalArg=process.argv.find(v=>v.startsWith('--originals-dir=')),originalsDir=originalArg?resolve(originalArg.slice('--originals-dir='.length)):join(dir,'originals');if(!/^\/(?:private\/)?tmp\/kiara-[A-Za-z0-9_./-]+$/.test(originalsDir))throw Error('Originals directory must be an explicit temporary kiara-* local path.');
 for(const key of Object.keys(process.env))if(/^(KIARA|MONGO|OPENAI|RESEND|TEMPORAL|VERCEL)/.test(key))delete process.env[key];
 globalThis.fetch=async()=>{throw Error('Synthetic fixture forbids all external requests');};
 const secret='whsec_'+Buffer.from('synthetic-kiara-email-ui-not-a-real-secret').toString('base64'),owner:ActorContext={tenantId:'local-workspace',actorId:'local-founder',mode:'local_demo',expiresAt:Date.now()+3600000},installation:EmailInstallation={id:'synthetic-email-ui',tenantId:owner.tenantId,actorId:'synthetic-email-integration',ownerId:owner.actorId,accountId:'synthetic-exclusive-ui-account',accountScope:'exclusive_owner',enabled:true,validUntil:'2099-01-01T00:00:00Z',receivingAddress:'synthetic-owner@inbox.example.test',allowedSenders:[],tokenEnv:'KIARA_EMAIL_UI_TOKEN',webhookSecretEnv:'KIARA_EMAIL_UI_WEBHOOK_SECRET',rawDownloadHosts:['synthetic-raw.example.test'],scope:{kind:'private',actorIds:[owner.actorId,'synthetic-email-integration']}};
 await mkdir(dir,{recursive:true,mode:0o700});const configPath=join(dir,'email-ui-installations.json'),envPath=join(dir,'email-ui-environment.json');
 const environment={KIARA_V2_DATA_DIR:dir,KIARA_ORIGINALS_DIR:originalsDir,KIARA_V2_AI_MODE:'local',KIARA_V2_AUTH_MODE:'local_demo',KIARA_AUTH_MODE:'demo_simulated',MONGODB_URI:'',KIARA_V2_EMAIL_INSTALLATIONS_FILE:configPath,KIARA_EMAIL_UI_TOKEN:'synthetic-no-provider-access',KIARA_EMAIL_UI_WEBHOOK_SECRET:secret};Object.assign(process.env,environment);
 await writeFile(configPath,JSON.stringify([installation],null,2),{mode:0o600});await chmod(configPath,0o600);await writeFile(envPath,JSON.stringify(environment,null,2),{mode:0o600});await chmod(envPath,0o600);
 await transactWorkspace(owner.tenantId,s=>{if(!s.memberships.some(m=>m.actorId===owner.actorId))s.memberships.push({actorId:owner.actorId,roles:['member','fact_owner','business_owner','publisher','admin'],version:1,expiresAt:null,revokedAt:null,matterIds:null,entityIds:null});if(!s.memberships.some(m=>m.actorId===installation.actorId))s.memberships.push({actorId:installation.actorId,roles:['integration'],version:1,expiresAt:null,revokedAt:null,matterIds:null,entityIds:null});});
 const fixtures=[];for(const label of ['accept evidence','reject evidence']){const emailId=randomUUID(),subject=`Synthetic quarantine — ${label}`,body=`SYNTHETIC UI FIXTURE ONLY. This is a forwarded source for ${label}. The quoted sender and the legal assertions are unverified. No email was received or sent. Attachment contents are preserved in a synthetic raw original but not extracted.`,time=String(Math.floor(Date.now()/1000)),eventId='msg_'+randomUUID(),raw=Buffer.from(JSON.stringify({type:'email.received',created_at:new Date().toISOString(),data:{email_id:emailId,from:'unverified-sender@example.test',to:[installation.receivingAddress],subject}})),signature=createHmac('sha256',Buffer.from(secret.slice(6),'base64')).update(`${eventId}.${time}.`).update(raw).digest('base64');
 const accepted=await acceptEmailWebhook(installation.id,new Headers({'svix-id':eventId,'svix-timestamp':time,'svix-signature':`v1,${signature}`}),raw),original=Buffer.from(`From: unverified-sender@example.test\r\nTo: ${installation.receivingAddress}\r\nSubject: ${subject}\r\n\r\n${body}\r\n`);
 const fetcher:typeof fetch=async(url,options)=>{if(options?.method!=='GET')throw Error('Read-only injected fixture');const parsed=new URL(String(url));if(parsed.origin==='https://api.resend.com'&&parsed.pathname===`/emails/receiving/${emailId}`)return Response.json({id:emailId,from:'unverified-sender@example.test',to:[installation.receivingAddress],received_for:[installation.receivingAddress],subject,text:body,created_at:new Date().toISOString(),message_id:`<${emailId}@synthetic.example.test>`,authentication:null,attachments:[],raw:{download_url:`https://synthetic-raw.example.test/${emailId}.eml`,expires_at:'2099-01-01T00:00:00Z'}});if(parsed.origin==='https://synthetic-raw.example.test')return new Response(original);throw Error('Unexpected synthetic fixture URL');};
 const result=await processEmailIntake(owner.tenantId,accepted.intakeId,{fetcher});if(result.status!=='quarantined')throw Error(`Synthetic intake failed: ${result.status}`);fixtures.push({label,...await emailIntakeView(owner,accepted.intakeId)});}
 await closeV2Store();console.log(JSON.stringify({dataDir:dir,originalsDir,environmentFile:envPath,installationFile:configPath,providerCalls:0,fixtures:fixtures.map(({source,...x})=>({...x,title:source?.title}))},null,2));
}
main().catch(async e=>{await closeV2Store();console.error(e instanceof Error?e.message:String(e));process.exitCode=1;});
